import { notFound } from "next/navigation";
import { VendorForm } from "@/components/vendor-form";
import { PageHeader, PageShell, SectionCard, StatusBadge } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { money } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { hasRolePermission } from "@/lib/role-permissions";

export default async function VendorDetailPage({ params }: { params: Promise<{ id: string }> }) { const user = await requirePermission("VIEW_VENDORS"); const { id } = await params; const manage = await hasRolePermission(prisma, user.role, "MANAGE_VENDORS"); const row = await prisma.vendor.findUnique({ where: { id }, include: { expenses: { select: { netAmount: true, approvalStatus: true } } } }); if (!row) notFound(); const active = row.expenses.filter((expense) => expense.approvalStatus !== "CANCELLED"); const formVendor = manage ? { id: row.id, vendorCode: row.vendorCode, name: row.name, contactPerson: row.contactPerson, mobile: row.mobile, alternateMobile: row.alternateMobile, email: row.email, address: row.address, gstin: row.gstin, pan: row.pan, bankName: row.bankName, accountLastFour: row.accountLastFour, ifsc: row.ifsc, paymentTermsDays: row.paymentTermsDays, notes: row.notes, status: row.status } : null; return <PageShell><PageHeader title={row.name} description={`${row.vendorCode} · vendor record`} action={<StatusBadge status={row.status} />} /><div className="stats"><div className="card stat"><span>Related expenses</span><strong>{row.expenses.length}</strong></div><div className="card stat"><span>Active spend</span><strong>{money(active.reduce((sum, expense) => sum + Number(expense.netAmount), 0))}</strong></div></div>{!manage ? <SectionCard title="Vendor details" description="Tax and banking fields are hidden for this read-only access."><dl className="detail-grid"><div><dt>Contact</dt><dd>{row.contactPerson || "—"}</dd></div><div><dt>Mobile</dt><dd>{row.mobile || "—"}</dd></div><div><dt>Email</dt><dd>{row.email || "—"}</dd></div><div><dt>Status</dt><dd>{row.status}</dd></div></dl></SectionCard> : null}{manage && formVendor ? <VendorForm editable vendor={formVendor} /> : null}{manage ? <div className="notice">Use INACTIVE or BLOCKED instead of deletion. Linked vendor records are never hard deleted.</div> : null}</PageShell>; }
