import { notFound } from "next/navigation";
import { MiscReceiptActions } from "@/components/misc-receipt-actions";
import { PageHeader, PageShell, StatusBadge } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { displayDate, moneyExact } from "@/lib/format";
import { miscReceiptInclude, publicAccountLabel } from "@/lib/misc-income";
import { prisma } from "@/lib/prisma";
import { hasRolePermission } from "@/lib/role-permissions";
export default async function MiscIncomeDetailPage({ params }: { params: Promise<{ id: string }> }) { const user = await requirePermission("VIEW_MISC_INCOME"); const { id } = await params; const row = await prisma.miscIncomeReceipt.findUnique({ where: { id }, include: miscReceiptInclude }); if (!row) notFound(); const [canCancel, sensitive] = await Promise.all([hasRolePermission(prisma, user.role, "CANCEL_MISC_INCOME"), hasRolePermission(prisma, user.role, "MANAGE_MISC_INCOME")]); return <PageShell><PageHeader title={`Receipt ${row.receiptNumber}`} description="Issued miscellaneous-income receipts are preserved and are not editable." action={<MiscReceiptActions id={id} canCancel={canCancel} status={row.status} />} /><section className="card receipt-detail">{row.status === "CANCELLED" ? <div className="cancelled-watermark">CANCELLED</div> : null}<div className="detail-grid"><div><span>Date</span><strong>{displayDate(row.receiptDate)}</strong></div><div><span>Status</span><StatusBadge status={row.status} /></div><div><span>Student / payer</span><strong>{row.student ? `${row.student.studentName} (${row.student.admissionNo})` : row.payerName ?? "Walk-in payer"}</strong></div><div><span>Payment method</span><strong>{row.paymentMethod.replaceAll("_", " ")}</strong></div><div><span>Received account</span><strong>{publicAccountLabel(row.receivedAccount) ?? "—"}</strong></div>{sensitive && row.transactionReference ? <div><span>Transaction reference</span><strong>{row.transactionReference}</strong></div> : null}</div><div className="table-wrap"><table><thead><tr><th>Item</th><th>Quantity</th><th>Rate</th><th>Discount</th><th>Total</th></tr></thead><tbody>{row.lines.map((line) => <tr key={line.id}><td>{line.itemNameSnapshot}</td><td>{line.quantity}</td><td>{moneyExact(Number(line.unitAmount))}</td><td>{moneyExact(Number(line.discountAmount))}</td><td>{moneyExact(Number(line.lineTotal))}</td></tr>)}</tbody></table></div><div className="receipt-total"><span>Gross <strong>{moneyExact(Number(row.grossAmount))}</strong></span><span>Discount <strong>{moneyExact(Number(row.discountAmount))}</strong></span><span>Net <strong>{moneyExact(Number(row.netAmount))}</strong></span></div>{sensitive ? <div className="audit-box"><p><strong>Created by:</strong> {row.createdBy?.name ?? "System / restored record"}</p>{row.status === "CANCELLED" ? <p><strong>Cancellation:</strong> {row.cancellationReason} — {row.cancelledBy?.name ?? "Restored actor"}</p> : null}</div> : <p className="muted-text">Sensitive references and actor details are hidden for this read-only role.</p>}</section></PageShell>; }
