import Link from "next/link";
import { redirect } from "next/navigation";
import { TeacherAnalyticsResponseForm } from "@/components/teacher-analytics-forms";
import { PageHeader, StatusBadge } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { ownTeacherSnapshotWhere, requireOwnTeacherStaff, safeTeacherReview } from "@/lib/teacher-analytics-scope";
import { publicTeacherAnalyticsSnapshot } from "@/lib/teacher-analytics";

export default async function OwnTeacherAnalyticsPage({ searchParams }: { searchParams: Promise<{ snapshotId?: string }> }) {
  const user = await requirePermission("VIEW_OWN_TEACHER_ANALYTICS"); if (user.role !== "TEACHER") redirect("/unauthorized"); const staff = await requireOwnTeacherStaff(prisma,user); const q = await searchParams;
  const rows = await prisma.teacherAnalyticsSnapshot.findMany({ where: ownTeacherSnapshotWhere(staff.id), include: { reviewCycle:true,review:true }, orderBy:{reviewCycle:{periodStart:"desc"}} });
  const selected = rows.find((row)=>row.id===q.snapshotId) ?? rows[0]; const data = selected ? publicTeacherAnalyticsSnapshot(selected) : null; const review = selected ? safeTeacherReview(selected.review) : null;
  return <div className="page teacher-analytics-page"><PageHeader title="My Teacher Analytics" description="Your own shared or finalised evidence and response. No peer analytics are available."/><p className="notice">This self-view contains contextual evidence only. It has no composite score, rank, automatic employment decision, or Student identity.</p><section className="card card-pad"><h3>My Review Cycles</h3><div className="table-wrap"><table><thead><tr><th>Cycle</th><th>Period</th><th>Review Status</th><th>Open</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td>{row.reviewCycle.title}</td><td>{row.reviewCycle.periodStart.toLocaleDateString("en-IN")} – {row.reviewCycle.periodEnd.toLocaleDateString("en-IN")}</td><td><StatusBadge status={row.review?.status ?? "NOT_STARTED"}/></td><td><Link href={`/teacher/analytics?snapshotId=${row.id}`}>View My Evidence</Link></td></tr>)}{!rows.length?<tr><td colSpan={4}>No analytics review has been shared with this linked Teacher account.</td></tr>:null}</tbody></table></div></section>{data&&selected&&review?<><section className="card card-pad"><h3>My Evidence Categories</h3><div className="table-wrap"><table><thead><tr><th>Category</th><th>Source State</th><th>Context</th></tr></thead><tbody>{[["Workload",data.workload],["Attendance",data.attendance],["Approved Leave",data.leave],["Substitute Periods",data.substitute],["Homework",data.homework],["Assessment Workflow",data.assessmentWorkflow],["Student Outcomes",data.studentOutcome],["Report Cards",data.reportCard],["KG Rubric",data.kgRubric]].map(([label,item]:any)=><tr key={label}><td>{label}</td><td>{item.completeness}</td><td>{item.warning}<details><summary>View evidence</summary><pre className="json-evidence">{JSON.stringify(item.value,null,2)}</pre></details></td></tr>)}</tbody></table></div></section><section className="card card-pad"><h3>Shared Leadership Notes</h3><dl className="detail-list"><div><dt>Evidence and strengths</dt><dd>{review.strengthsNote??"—"}</dd></div><div><dt>Support needed</dt><dd>{review.supportNeededNote??"—"}</dd></div><div><dt>Agreed actions</dt><dd>{review.agreedActionsNote??"—"}</dd></div><div><dt>Leadership context</dt><dd>{review.leadershipContextNote??"—"}</dd></div></dl></section><TeacherAnalyticsResponseForm reviewId={selected.review!.id} existing={review.teacherResponse} finalised={review.status==="FINALISED"}/></>:null}</div>;
}
