import Link from "next/link";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getSchoolSettings } from "@/lib/school-settings";
import { attendanceDay, attendanceReportData, localDateText, optionalAttendanceFilter } from "@/lib/student-attendance";
import { PageHeader } from "@/components/ui";

export default async function StudentAttendanceReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requirePermission("VIEW_STUDENT_ATTENDANCE_REPORTS"); const sp = await searchParams; const settings = await getSchoolSettings(prisma); const today = localDateText();
  const from = sp.from ?? `${today.slice(0, 8)}01`; const to = sp.to ?? today; const className = optionalAttendanceFilter(sp.className); const section = optionalAttendanceFilter(sp.section);
  const data = await attendanceReportData(prisma, { from: attendanceDay(from), to: attendanceDay(to), academicYear: settings.academicYear, className, section });
  const exportQuery = new URLSearchParams({ from, to, academicYear: settings.academicYear, ...(className ? { className } : {}), ...(section ? { section } : {}) });
  return <div className="page"><PageHeader title="Student Attendance Reports" description="Review date-wise attendance, absences, late arrivals, and a simple student summary." action={<Link className="button" href={`/api/attendance/students/reports/export?${exportQuery}`}>Export CSV</Link>} />
    <div className="subnav"><Link href="/attendance/students">Take Attendance</Link><Link className="active" href="/attendance/students/reports">Reports</Link></div>
    <form className="card card-pad attendance-report-filters"><label>From<input name="from" type="date" defaultValue={from} /></label><label>To<input name="to" type="date" defaultValue={to} /></label><label>Class<input name="className" defaultValue={className ?? ""} placeholder="All classes" /></label><label>Section<input name="section" defaultValue={section ?? ""} placeholder="All sections" /></label><button>Apply Filters</button></form>
    <p className="notice">Official totals include submitted and locked attendance only. Draft work is excluded.</p>
    <div className="grid stats"><div className="stat"><span>Marked</span><strong>{data.totals.total}</strong></div><div className="stat"><span>Present</span><strong>{data.totals.PRESENT}</strong></div><div className="stat"><span>Absent</span><strong>{data.totals.ABSENT}</strong></div><div className="stat"><span>Late</span><strong>{data.totals.LATE}</strong></div></div>
    <section className="card"><div className="section-title"><h3>Date-wise Class / Section Report</h3></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Class</th><th>Status</th><th>Students</th><th>Present</th><th>Absent</th><th>Late</th><th>Half Day</th><th>Excused</th></tr></thead><tbody>{data.sessions.map((session) => { const totals = { PRESENT: 0, ABSENT: 0, LATE: 0, HALF_DAY: 0, EXCUSED: 0 }; session.records.forEach((row) => { if (row.status in totals) totals[row.status as keyof typeof totals] += 1; }); return <tr key={session.id}><td>{session.attendanceDate.toISOString().slice(0, 10)}</td><td>{session.className}{session.section ? `-${session.section}` : ""}</td><td>{session.status}</td><td>{session.records.length}</td><td>{totals.PRESENT}</td><td>{totals.ABSENT}</td><td>{totals.LATE}</td><td>{totals.HALF_DAY}</td><td>{totals.EXCUSED}</td></tr>; })}{!data.sessions.length ? <tr><td colSpan={9}>No attendance sessions match these filters.</td></tr> : null}</tbody></table></div></section>
    <div className="grid two"><ReportList title="Absent List" rows={data.rows.filter((row) => row.status === "ABSENT")} /><ReportList title="Late List" rows={data.rows.filter((row) => row.status === "LATE")} /></div>
    <section className="card"><div className="section-title"><h3>Monthly Summary by Student</h3></div><div className="table-wrap"><table><thead><tr><th>Admission No.</th><th>Student</th><th>Class</th><th>Marked Days</th><th>Present</th><th>Absent</th><th>Late</th><th>Half Day</th><th>Excused</th></tr></thead><tbody>{data.byStudent.map((row) => <tr key={row.admissionNo}><td>{row.admissionNo}</td><td>{row.studentName}</td><td>{row.className}{row.section ? `-${row.section}` : ""}</td><td>{row.total}</td><td>{row.present}</td><td>{row.absent}</td><td>{row.late}</td><td>{row.halfDay}</td><td>{row.excused}</td></tr>)}{!data.byStudent.length ? <tr><td colSpan={9}>No student attendance records match these filters.</td></tr> : null}</tbody></table></div></section>
  </div>;
}

function ReportList({ title, rows }: { title: string; rows: Array<{ attendanceDate: Date; admissionNo: string; studentName: string; className: string; section: string; remarks: string | null }> }) {
  return <section className="card"><div className="section-title"><h3>{title}</h3></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Student</th><th>Class</th><th>Remarks</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.admissionNo}-${row.attendanceDate.toISOString()}-${index}`}><td>{row.attendanceDate.toISOString().slice(0, 10)}</td><td>{row.studentName}<small className="muted-text"> {row.admissionNo}</small></td><td>{row.className}{row.section ? `-${row.section}` : ""}</td><td>{row.remarks ?? "-"}</td></tr>)}{!rows.length ? <tr><td colSpan={4}>No students in this list.</td></tr> : null}</tbody></table></div></section>;
}
