BEGIN;

ALTER TABLE "BiometricDevice" DROP CONSTRAINT "BiometricDevice_profile_check";
ALTER TABLE "BiometricDevice" ADD CONSTRAINT "BiometricDevice_profile_check" CHECK ("protocolProfile" IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH','GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','GENERIC_CSV_IMPORT','ETIMETRACKLITE_RAW_EXPORT_V1','SIMULATOR'));

ALTER TABLE "BiometricDevice" DROP CONSTRAINT "BiometricDevice_protocol_proof_check";
ALTER TABLE "BiometricDevice" ADD CONSTRAINT "BiometricDevice_protocol_proof_check" CHECK (("protocolProfile" IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH') AND "protocolProofStatus" IN ('NOT_PROVIDED','OFFICIAL_VERIFIED')) OR ("protocolProfile" IN ('GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','ETIMETRACKLITE_RAW_EXPORT_V1') AND "protocolProofStatus" IN ('ADAPTER_CONTRACT_PENDING','ADAPTER_CONTRACT_APPROVED')) OR ("protocolProfile" IN ('GENERIC_CSV_IMPORT','SIMULATOR') AND "protocolProofStatus" = 'NOT_REQUIRED'));

ALTER TABLE "BiometricDevice" DROP CONSTRAINT "BiometricDevice_vendor_activation_check";
ALTER TABLE "BiometricDevice" ADD CONSTRAINT "BiometricDevice_vendor_activation_check" CHECK ("status" <> 'ACTIVE' OR "protocolProfile" IN ('GENERIC_CSV_IMPORT','SIMULATOR') OR ("protocolProfile" IN ('GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','ETIMETRACKLITE_RAW_EXPORT_V1') AND "protocolProofStatus" = 'ADAPTER_CONTRACT_APPROVED') OR ("protocolProfile" IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH') AND "protocolProofStatus" = 'OFFICIAL_VERIFIED'));

CREATE OR REPLACE FUNCTION "nalanda_trigger_e67d32b6b9775deb0fdf"() RETURNS trigger
LANGUAGE plpgsql
AS $nalanda_trigger$
BEGIN
  IF (NEW."status" NOT IN ('PENDING_APPROVAL','ACTIVE','REVOKED','RETIRED') OR NEW."clockDriftStatus" NOT IN ('HEALTHY','WARNING','UNTRUSTED_TIME','UNKNOWN') OR NEW."protocolProfile" NOT IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH','GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','GENERIC_CSV_IMPORT','ETIMETRACKLITE_RAW_EXPORT_V1','SIMULATOR')
  OR (NEW."protocolProfile" IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH') AND NEW."protocolProofStatus" NOT IN ('NOT_PROVIDED','OFFICIAL_VERIFIED'))
  OR (NEW."protocolProfile" IN ('GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','ETIMETRACKLITE_RAW_EXPORT_V1') AND NEW."protocolProofStatus" NOT IN ('ADAPTER_CONTRACT_PENDING','ADAPTER_CONTRACT_APPROVED'))
  OR (NEW."protocolProfile" IN ('GENERIC_CSV_IMPORT','SIMULATOR') AND NEW."protocolProofStatus" <> 'NOT_REQUIRED')
  OR (NEW."status" = 'ACTIVE' AND NEW."protocolProfile" IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH') AND NEW."protocolProofStatus" <> 'OFFICIAL_VERIFIED')
  OR (NEW."status" = 'ACTIVE' AND NEW."protocolProfile" IN ('GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','ETIMETRACKLITE_RAW_EXPORT_V1') AND NEW."protocolProofStatus" <> 'ADAPTER_CONTRACT_APPROVED')) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'BIOMETRIC_DEVICE_CONTRACT_INVALID';
  END IF;
  RETURN NEW;
END;
$nalanda_trigger$;

CREATE OR REPLACE FUNCTION "nalanda_trigger_ad6cfbe0d1159fafd566"() RETURNS trigger
LANGUAGE plpgsql
AS $nalanda_trigger$
BEGIN
  IF (NEW."status" NOT IN ('PENDING_APPROVAL','ACTIVE','REVOKED','RETIRED') OR NEW."clockDriftStatus" NOT IN ('HEALTHY','WARNING','UNTRUSTED_TIME','UNKNOWN') OR OLD."status" IN ('REVOKED','RETIRED')
  OR NEW."protocolProfile" NOT IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH','GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','GENERIC_CSV_IMPORT','ETIMETRACKLITE_RAW_EXPORT_V1','SIMULATOR')
  OR (NEW."protocolProfile" IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH') AND NEW."protocolProofStatus" NOT IN ('NOT_PROVIDED','OFFICIAL_VERIFIED'))
  OR (NEW."protocolProfile" IN ('GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','ETIMETRACKLITE_RAW_EXPORT_V1') AND NEW."protocolProofStatus" NOT IN ('ADAPTER_CONTRACT_PENDING','ADAPTER_CONTRACT_APPROVED'))
  OR (NEW."protocolProfile" IN ('GENERIC_CSV_IMPORT','SIMULATOR') AND NEW."protocolProofStatus" <> 'NOT_REQUIRED')
  OR (NEW."status" = 'ACTIVE' AND NEW."protocolProfile" IN ('ESSL_K30_PRO_PUSH','ESSL_ZK_LAN_SDK','ZK_ADMS_PUSH') AND NEW."protocolProofStatus" <> 'OFFICIAL_VERIFIED')
  OR (NEW."status" = 'ACTIVE' AND NEW."protocolProfile" IN ('GENERIC_ADMS_PUSH','GENERIC_LAN_POLL','ETIMETRACKLITE_RAW_EXPORT_V1') AND NEW."protocolProofStatus" <> 'ADAPTER_CONTRACT_APPROVED')
  OR ((NEW."protocolProfile" <> OLD."protocolProfile" OR NEW."protocolProofStatus" <> OLD."protocolProofStatus") AND (OLD."status" <> 'PENDING_APPROVAL' OR NEW."status" <> 'PENDING_APPROVAL'))) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'BIOMETRIC_DEVICE_TRANSITION_INVALID';
  END IF;
  RETURN NEW;
END;
$nalanda_trigger$;

COMMIT;
