import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createBackupDocument } from "../lib/backup";
import { emptyEntityResult, parseAndValidateBackup } from "../lib/restore";
import { restoreBooksFinanceData } from "../lib/restore-database";

const now = "2026-07-15T00:00:00.000Z";

function fixture() {
  return createBackupDocument({
    generatedAt: new Date(now), generatedBy: "Director", students: [], feeStructures: [], payments: [], paymentAudits: [],
    users: [{ id: "user-1", username: "director", passwordHash: "must-not-export" }],
    vendors: [{ id: "vendor-1", vendorCode: "BOOKPUB", name: "Book Publisher", status: "ACTIVE", createdAt: now, updatedAt: now }],
    bookCatalogItems: [{ id: "book-1", itemCode: "MATH-1", title: "Mathematics", itemType: "TEXTBOOK", publisherVendorId: "vendor-1", studentLinkRequired: false, status: "ACTIVE", createdAt: now, updatedAt: now }],
    bookCatalogRates: [{ id: "rate-1", itemId: "book-1", academicYear: "2026-27", amount: "100.00", effectiveFrom: now, effectiveTo: "2027-03-31T00:00:00.000Z", status: "ACTIVE", createdAt: now, updatedAt: now }],
    bookSaleReceipts: [{ id: "receipt-1", receiptNumber: "BOOK-20260715-ABC123", receiptDate: now, academicYear: "2026-27", payerName: "Parent", paymentMethod: "CASH", receivedAccount: "BOOKS_CASH_COUNTER", grossAmount: "100.00", discountAmount: "0.00", netAmount: "100.00", status: "ACTIVE", createdByUserId: "user-1", createdAt: now, updatedAt: now }],
    bookSaleReceiptLines: [{ id: "line-1", receiptId: "receipt-1", itemId: "book-1", itemCodeSnapshot: "MATH-1", itemTitleSnapshot: "Mathematics", publisherNameSnapshot: "Book Publisher", rateId: "rate-1", quantity: 1, unitAmount: "100.00", discountAmount: "0.00", lineTotal: "100.00", createdAt: now }],
    cashBookDays: [{ id: "day-1", cashDate: now, academicYear: "2026-27", openingBalance: "0.00", status: "LOCKED", feeCashSnapshot: "0.00", miscIncomeCashSnapshot: "0.00", bookSalesCashSnapshot: "100.00", cashExpenseSnapshot: "0.00", manualInflowSnapshot: "0.00", manualOutflowSnapshot: "0.00", bankDepositSnapshot: "0.00", directorHandoverSnapshot: "100.00", calculatedClosingBalance: "0.00", countedClosingBalance: "0.00", varianceAmount: "0.00", sourceSummarySnapshot: "{}", createdByUserId: "user-1", submittedByUserId: "user-1", approvedByUserId: "user-1", lockedByUserId: "user-1", submittedAt: now, approvedAt: now, lockedAt: now, createdAt: now, updatedAt: now }],
    cashBookMovements: [{ id: "movement-1", cashBookDayId: "day-1", movementType: "DIRECTOR_HANDOVER", amount: "100.00", movementDate: now, recipientName: "Director Sir", reason: "Daily book cash", status: "ACTIVE", recordedByUserId: "user-1", createdAt: now, updatedAt: now }],
    bookCashSettlements: [{ id: "settlement-1", settlementDate: now, academicYear: "2026-27", status: "APPROVED", expectedBookCash: "100.00", handedToDirectorAmount: "100.00", handedToCashCounterAmount: "0.00", retainedByBooksInchargeAmount: "0.00", varianceAmount: "0.00", cashBookMovementId: "movement-1", createdByUserId: "user-1", submittedByUserId: "user-1", approvedByUserId: "user-1", submittedAt: now, approvedAt: now, createdAt: now, updatedAt: now }]
  });
}

describe("books-finance backup restore v18", () => {
  it("includes all books arrays, the locked book-cash snapshot, and no password hash", () => { const backup = fixture(); expect(backup.metadata.backupVersion).toBe(37); for (const key of ["bookCatalogItems", "bookCatalogRates", "bookSaleReceipts", "bookSaleReceiptLines", "bookCashSettlements"] as const) expect(backup[key]).toHaveLength(1); expect(backup.cashBookDays[0]).toMatchObject({ bookSalesCashSnapshot: "100.00", status: "LOCKED" }); expect(JSON.stringify(backup)).not.toContain("must-not-export"); expect(JSON.stringify(backup)).not.toContain("passwordHash"); });
  it("preserves catalog, rate, receipt-line, settlement, and movement snapshots", () => { const parsed = parseAndValidateBackup(fixture()); expect(parsed.bookCatalogItems[0]).toMatchObject({ itemCode: "MATH-1", publisherVendorId: "vendor-1" }); expect(parsed.bookCatalogRates[0]).toMatchObject({ amount: "100.00" }); expect(parsed.bookSaleReceiptLines[0]).toMatchObject({ itemTitleSnapshot: "Mathematics", publisherNameSnapshot: "Book Publisher", lineTotal: "100.00" }); expect(parsed.bookCashSettlements[0]).toMatchObject({ status: "APPROVED", cashBookMovementId: "movement-1" }); });
  it("rejects missing vendor, item, rate, receipt, and student links", () => { const vendor: any = fixture(); vendor.bookCatalogItems[0].publisherVendorId = "missing"; expect(() => parseAndValidateBackup(vendor)).toThrow(/publisherVendorId/); const item: any = fixture(); item.bookCatalogRates[0].itemId = "missing"; expect(() => parseAndValidateBackup(item)).toThrow(/itemId/); const rate: any = fixture(); rate.bookSaleReceiptLines[0].rateId = "missing"; expect(() => parseAndValidateBackup(rate)).toThrow(/rateId/); const receipt: any = fixture(); receipt.bookSaleReceiptLines[0].receiptId = "missing"; expect(() => parseAndValidateBackup(receipt)).toThrow(/receiptId/); const student: any = fixture(); student.bookSaleReceipts[0].studentId = "missing"; expect(() => parseAndValidateBackup(student)).toThrow(/studentId/); });
  it("rejects overlapping active rates and cross-item rate attachment", () => { const overlap: any = fixture(); overlap.bookCatalogRates.push({ ...overlap.bookCatalogRates[0], id: "rate-2", effectiveFrom: "2026-08-01T00:00:00.000Z" }); expect(() => parseAndValidateBackup(overlap)).toThrow(/overlaps an active rate/); const cross: any = fixture(); cross.bookCatalogItems.push({ ...cross.bookCatalogItems[0], id: "book-2", itemCode: "SCI-1" }); cross.bookSaleReceiptLines[0].itemId = "book-2"; expect(() => parseAndValidateBackup(cross)).toThrow(/rateId/); });
  it("rejects duplicate item codes, receipt numbers, and settlement dates", () => { const item: any = fixture(); item.bookCatalogItems.push({ ...item.bookCatalogItems[0], id: "book-2" }); expect(() => parseAndValidateBackup(item)).toThrow(/duplicates a catalog item/); const receipt: any = fixture(); receipt.bookSaleReceipts.push({ ...receipt.bookSaleReceipts[0], id: "receipt-2" }); expect(() => parseAndValidateBackup(receipt)).toThrow(/duplicates a receipt/); const settlement: any = fixture(); settlement.bookCashSettlements.push({ ...settlement.bookCashSettlements[0], id: "settlement-2", cashBookMovementId: null, status: "DRAFT" }); expect(() => parseAndValidateBackup(settlement)).toThrow(/duplicates a settlement/); });
  it("rejects receipt policy and reconciliation violations", () => { const account: any = fixture(); account.bookSaleReceipts[0].receivedAccount = "NPS_CURRENT_ACCOUNT"; expect(() => parseAndValidateBackup(account)).toThrow(/BOOKS_CASH_COUNTER/); const required: any = fixture(); required.bookCatalogItems[0].studentLinkRequired = true; expect(() => parseAndValidateBackup(required)).toThrow(/student-linked/); const totals: any = fixture(); totals.bookSaleReceiptLines[0].lineTotal = "99.99"; expect(() => parseAndValidateBackup(totals)).toThrow(/inconsistent totals/); });
  it("rejects settlement reconciliation, variance, and Director-movement violations", () => { const total: any = fixture(); total.bookCashSettlements[0].handedToDirectorAmount = "99.99"; expect(() => parseAndValidateBackup(total)).toThrow(/reconcile/); const variance: any = fixture(); variance.bookCashSettlements[0].handedToDirectorAmount = "99.99"; variance.bookCashSettlements[0].varianceAmount = "0.01"; expect(() => parseAndValidateBackup(variance)).toThrow(/varianceReason/); const link: any = fixture(); link.cashBookMovements[0].amount = "99.99"; link.cashBookDays[0].directorHandoverSnapshot = "99.99"; link.cashBookDays[0].calculatedClosingBalance = "0.01"; link.cashBookDays[0].countedClosingBalance = "0.01"; expect(() => parseAndValidateBackup(link)).toThrow(/matching Director handover/); });
  it("keeps version 17 backups compatible when books fields and the snapshot are absent", () => { const backup: any = fixture(); for (const key of ["bookCatalogItems", "bookCatalogRates", "bookSaleReceipts", "bookSaleReceiptLines", "bookCashSettlements"]) { delete backup[key]; delete backup.metadata.counts[key]; } delete backup.cashBookDays[0].bookSalesCashSnapshot; backup.cashBookDays[0].directorHandoverSnapshot = "0.00"; backup.cashBookDays[0].calculatedClosingBalance = "0.00"; backup.cashBookDays[0].countedClosingBalance = "0.00"; backup.cashBookMovements = []; backup.metadata.counts.cashBookMovements = 0; backup.metadata.backupVersion = 17; const parsed = parseAndValidateBackup(backup); expect(parsed.bookCatalogItems).toEqual([]); expect(parsed.bookCashSettlements).toEqual([]); expect(parsed.cashBookDays[0].bookSalesCashSnapshot).toBeUndefined(); });
  it("documents collision isolation, local-newer preservation, and exact settlement movement matching", () => { const source = readFileSync("lib/restore-database.ts", "utf8"); expect(source).toContain("dependent backup records were isolated"); expect(source).toContain("backup lines were isolated"); expect(source).toContain("overlaps a local active rate"); expect(source).toContain("exact cash movement was unavailable"); expect(source).toContain("local record is newer"); });
  it("restores the same books-finance backup twice without creating duplicates", async () => {
    const backup: any = parseAndValidateBackup(fixture());
    const stores = { items: new Map<string, any>(), rates: new Map<string, any>(), receipts: new Map<string, any>(), lines: new Map<string, any>(), settlements: new Map<string, any>() };
    const byDate = (store: Map<string, any>, value: Date) => [...store.values()].find((row) => row.settlementDate?.getTime() === value.getTime()) ?? null;
    const client: any = {
      bookCatalogItem: { findUnique: async ({ where }: any) => where.id ? stores.items.get(where.id) ?? null : [...stores.items.values()].find((row) => row.itemCode === where.itemCode) ?? null, create: async ({ data }: any) => (stores.items.set(data.id, data), data), update: async ({ where, data }: any) => { const row = { ...stores.items.get(where.id), ...data }; stores.items.set(where.id, row); return row; } },
      bookCatalogRate: { findUnique: async ({ where }: any) => stores.rates.get(where.id) ?? null, findMany: async () => [], create: async ({ data }: any) => (stores.rates.set(data.id, data), data), update: async ({ where, data }: any) => { const row = { ...stores.rates.get(where.id), ...data }; stores.rates.set(where.id, row); return row; } },
      bookSaleReceipt: { findUnique: async ({ where }: any) => where.id ? stores.receipts.get(where.id) ?? null : [...stores.receipts.values()].find((row) => row.receiptNumber === where.receiptNumber) ?? null, create: async ({ data }: any) => (stores.receipts.set(data.id, data), data), update: async ({ where, data }: any) => { const row = { ...stores.receipts.get(where.id), ...data }; stores.receipts.set(where.id, row); return row; } },
      bookSaleReceiptLine: { findUnique: async ({ where }: any) => stores.lines.get(where.id) ?? null, create: async ({ data }: any) => (stores.lines.set(data.id, data), data) },
      bookCashSettlement: { findUnique: async ({ where }: any) => where.id ? stores.settlements.get(where.id) ?? null : byDate(stores.settlements, where.settlementDate), create: async ({ data }: any) => (stores.settlements.set(data.id, data), data), update: async ({ where, data }: any) => { const row = { ...stores.settlements.get(where.id), ...data }; stores.settlements.set(where.id, row); return row; } },
      cashBookMovement: { findUnique: async ({ where }: any) => where.id === "movement-1" ? { id: "movement-1" } : null }
    };
    const result = () => ({ bookCatalogItems: emptyEntityResult(), bookCatalogRates: emptyEntityResult(), bookSaleReceipts: emptyEntityResult(), bookSaleReceiptLines: emptyEntityResult(), bookCashSettlements: emptyEntityResult(), warnings: [] as string[] });
    const first = result(); await restoreBooksFinanceData(client, backup, new Map(), new Map([["user-1", "local-user"]]), new Map([["vendor-1", "local-vendor"]]), first);
    const second = result(); await restoreBooksFinanceData(client, backup, new Map(), new Map([["user-1", "local-user"]]), new Map([["vendor-1", "local-vendor"]]), second);
    expect(first.bookCatalogItems.created).toBe(1); expect(first.bookCatalogRates.created).toBe(1); expect(first.bookSaleReceipts.created).toBe(1); expect(first.bookSaleReceiptLines.created).toBe(1); expect(first.bookCashSettlements.created).toBe(1);
    expect(second.bookCatalogItems.created + second.bookCatalogRates.created + second.bookSaleReceipts.created + second.bookSaleReceiptLines.created + second.bookCashSettlements.created).toBe(0);
    expect(stores.items.size).toBe(1); expect(stores.rates.size).toBe(1); expect(stores.receipts.size).toBe(1); expect(stores.lines.size).toBe(1); expect(stores.settlements.size).toBe(1);
  });
  it("never deletes local books-finance records during restore", () => { const source = readFileSync("lib/restore-database.ts", "utf8"); const section = source.slice(source.indexOf("export async function restoreBooksFinanceData"), source.indexOf("export async function restoreNoticesData")); expect(section).not.toContain("deleteMany"); expect(section).not.toContain("delete("); });
});

