import { readFileSync } from "node:fs";
import { Prisma } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { expectedBookCashForDate, reconcileBookCash, validateBookCashSettlementInput } from "../lib/book-cash-settlement";
import { assertNoBookRateOverlap, bookSalesCsv, newBookReceiptNumber, normalizeBookItemCode, validateBookCatalogItemInput, validateBookRateInput, validateBookSaleInput } from "../lib/books-finance";
import { createBackupDocument } from "../lib/backup";
import { can, PERMISSIONS } from "../lib/permissions";
import { publisherBillTotals } from "../lib/publisher-bills";
import { parseAndValidateBackup } from "../lib/restore";

function saleDb(options: { required?: boolean; rate?: string; student?: boolean } = {}) { const item = { id: "book-1", itemCode: "MATH-1", title: "Math Book", itemType: "TEXTBOOK", className: "I", studentLinkRequired: options.required ?? true, publisherVendor: { name: "QA Publisher" }, rates: [{ id: "rate-1", academicYear: "2026-27", amount: new Prisma.Decimal(options.rate ?? "10.11"), effectiveFrom: null, effectiveTo: null, status: "ACTIVE" }] }; return { bookCatalogItem: { findMany: async () => [item] }, student: { findFirst: async () => options.student === false ? null : { id: "student-1" } } } as any; }
const baseSale = { receiptDate: "2026-07-15", academicYear: "2026-27", studentId: "student-1", payerName: "QA Payer", paymentMethod: "CASH", receivedAccount: "BOOKS_CASH_COUNTER", lines: [{ itemId: "book-1", quantity: 2, discountAmount: "0.01" }] };

describe("books, library income, publisher bills, and settlement foundation", () => {
  it("normalizes catalog item codes consistently", () => { expect(normalizeBookItemCode(" math book/1 ")).toBe("MATH-BOOK1"); expect(validateBookCatalogItemInput({ itemCode: "ab 1", title: "Book", itemType: "TEXTBOOK" }).itemCode).toBe("AB-1"); });
  it("rejects invalid item types", () => { expect(() => validateBookCatalogItemInput({ itemCode: "A", title: "Book", itemType: "INVENTORY" })).toThrow(/not supported/); });
  it("rejects reversed rate dates", () => { expect(() => validateBookRateInput({ itemId: "i", academicYear: "2026-27", amount: 1, effectiveFrom: "2026-07-16", effectiveTo: "2026-07-15" })).toThrow(/before/); });
  it("prevents active rate overlap while preserving historical rates", async () => { const client: any = { bookCatalogRate: { findMany: async () => [{ effectiveFrom: new Date("2026-07-01"), effectiveTo: new Date("2026-07-31") }] } }; const data = validateBookRateInput({ itemId: "i", academicYear: "2026-27", amount: 1, effectiveFrom: "2026-07-15", effectiveTo: "2026-08-15" }); await expect(assertNoBookRateOverlap(client, data)).rejects.toThrow(/overlapping/); await expect(assertNoBookRateOverlap(client, { ...data, status: "INACTIVE" })).resolves.toBeUndefined(); });
  it("requires a student when any selected catalog item requires it", async () => { await expect(validateBookSaleInput(saleDb(), { ...baseSale, studentId: null })).rejects.toThrow(/student is required/); });
  it("calculates multi-line exact paise totals on the server", async () => { const result = await validateBookSaleInput(saleDb(), baseSale); expect(result.grossAmount.toFixed(2)).toBe("20.22"); expect(result.discountAmount.toFixed(2)).toBe("0.01"); expect(result.netAmount.toFixed(2)).toBe("20.21"); expect(result.lines[0]).toMatchObject({ itemCodeSnapshot: "MATH-1", itemTitleSnapshot: "Math Book", publisherNameSnapshot: "QA Publisher" }); });
  it("requires positive whole quantities and bounded discounts", async () => { await expect(validateBookSaleInput(saleDb(), { ...baseSale, lines: [{ itemId: "book-1", quantity: 1.5, discountAmount: 0 }] })).rejects.toThrow(/whole number/); await expect(validateBookSaleInput(saleDb(), { ...baseSale, lines: [{ itemId: "book-1", quantity: 1, discountAmount: 20 }] })).rejects.toThrow(/cannot exceed/); });
  it("enforces cash and non-cash reference conventions", async () => { const cash = await validateBookSaleInput(saleDb(), baseSale); expect(cash.receivedAccount).toBe("BOOKS_CASH_COUNTER"); await expect(validateBookSaleInput(saleDb(), { ...baseSale, paymentMethod: "UPI", receivedAccount: "NPS_CURRENT_ACCOUNT", transactionReference: "" })).rejects.toThrow(/reference/); await expect(validateBookSaleInput(saleDb(), { ...baseSale, paymentMethod: "CHEQUE", receivedAccount: "NPS_CURRENT_ACCOUNT", chequeNumber: "", chequeDate: "" })).rejects.toThrow(/Cheque number/); });
  it("keeps book receipt numbering separate from fee and miscellaneous receipts", () => { const number = newBookReceiptNumber(new Date("2026-07-15T00:00:00Z")); expect(number).toMatch(/^BOOK-/); expect(number).not.toMatch(/^MISC-/); expect(readFileSync("lib/books-finance.ts", "utf8")).not.toContain("client.payment.create"); });
  it("calculates only active CASH receipts as expected book cash", async () => { const state: any = {}; const client: any = { bookSaleReceipt: { findMany: async (args: any) => { state.where = args.where; return [{ netAmount: new Prisma.Decimal("30.25") }]; } } }; const result = await expectedBookCashForDate(client, new Date("2026-07-15T00:00:00Z")); expect(result.amount.toFixed(2)).toBe("30.25"); expect(state.where).toMatchObject({ status: "ACTIVE", paymentMethod: "CASH" }); });
  it("reconciles Director, cash counter, retained, and variance exactly", () => { expect(reconcileBookCash(new Prisma.Decimal("100.01"), new Prisma.Decimal("40"), new Prisma.Decimal("50"), new Prisma.Decimal("10.01")).toFixed(2)).toBe("0.00"); expect(() => validateBookCashSettlementInput({ academicYear: "2026-27", handedToDirectorAmount: 40, handedToCashCounterAmount: 50, retainedByBooksInchargeAmount: 5 }, new Prisma.Decimal(100))).toThrow(/variance reason/); });
  it("makes Director handover unique and cash-counter transfer non-outflow by design", () => { const schema = readFileSync("prisma/schema.prisma", "utf8"); const helper = readFileSync("lib/book-cash-settlement.ts", "utf8"); expect(schema).toContain("cashBookMovementId"); expect(schema).toContain("@unique"); expect(helper).toContain('movementType: "DIRECTOR_HANDOVER"'); expect(helper).not.toContain('movementType: "HAND_TO_CASH_COUNTER"'); });
  it("uses compare-and-set transitions to protect repeated approval", () => { const helper = readFileSync("lib/book-cash-settlement.ts", "utf8"); expect(helper).toContain("updateMany"); expect(helper).toContain("updatedAt: current.updatedAt"); expect(helper).toContain("cashBookMovementId: null"); });
  it("integrates book-sale cash once in the authoritative cash-book formula", () => { const helper = readFileSync("lib/cash-book.ts", "utf8"); expect(helper).toContain("client as any).bookSaleReceipt"); expect(helper).toContain("add(bookSalesCash)"); expect(helper).not.toContain("bookCashSettlement.findMany"); });
  it("reuses ExpenseRecord and ExpensePayment for publisher bills", () => { const helper = readFileSync("lib/publisher-bills.ts", "utf8"); expect(helper).toContain("tx.expenseRecord.create"); expect(helper).not.toContain("publisherPayment.create"); expect(readFileSync("app/api/books/publisher-bills/route.ts", "utf8")).toContain("ExpenseRecord/ExpensePayment"); });
  it("creates annual library service only as an expense draft and never hardcodes 25000", () => { const helper = readFileSync("lib/publisher-bills.ts", "utf8"); expect(helper).toContain("CREATED_FROM_LIBRARY_SERVICE_TEMPLATE"); expect(helper).toContain("payrollUsed: false"); expect(helper).not.toContain("25000"); });
  it("calculates publisher paid and outstanding from existing payment rows", () => { const result = publisherBillTotals([{ netAmount: new Prisma.Decimal(100), approvalStatus: "APPROVED", payments: [{ amount: new Prisma.Decimal(40) }] }]); expect(result.paid.toFixed(2)).toBe("40.00"); expect(result.outstanding.toFixed(2)).toBe("60.00"); });
  it("sets leadership, scoped staff, and read-only role defaults", () => { for (const permission of ["VIEW_BOOKS_FINANCE", "MANAGE_BOOK_SALES", "APPROVE_BOOK_CASH_SETTLEMENT", "MANAGE_PUBLISHER_BILLS"]) expect(PERMISSIONS).toContain(permission); expect(can("DIRECTOR", "APPROVE_BOOK_CASH_SETTLEMENT")).toBe(true); expect(can("ADMIN", "APPROVE_BOOK_CASH_SETTLEMENT")).toBe(false); expect(can("ACCOUNTANT", "SUBMIT_BOOK_CASH_SETTLEMENT")).toBe(true); expect(can("ACCOUNTANT", "APPROVE_BOOK_CASH_SETTLEMENT")).toBe(false); expect(can("PRINCIPAL", "VIEW_BOOK_REPORTS")).toBe(true); expect(can("VIEWER", "EXPORT_BOOK_REPORTS")).toBe(false); expect(can("TEACHER", "VIEW_BOOKS_FINANCE")).toBe(false); expect(can("PARENT", "VIEW_BOOKS_FINANCE")).toBe(false); });
  it("guards pages and direct mutation APIs server-side", () => { expect(readFileSync("app/books/page.tsx", "utf8")).toContain('requirePermission("VIEW_BOOKS_FINANCE")'); expect(readFileSync("app/api/books/sales/route.ts", "utf8")).toContain('requireApiPermission("MANAGE_BOOK_SALES")'); expect(readFileSync("app/api/books/settlements/[date]/workflow/route.ts", "utf8")).toContain("APPROVE_BOOK_CASH_SETTLEMENT"); });
  it("exports formula-safe CSV without private IDs or references", () => { const csv = bookSalesCsv([{ receiptNumber: "=BOOK", receiptDate: new Date("2026-07-15"), academicYear: "2026-27", status: "ACTIVE", student: null, payerName: "QA", lines: [{ itemCodeSnapshot: "A", itemTitleSnapshot: "Book", classNameSnapshot: "I", publisherNameSnapshot: "Pub" }], paymentMethod: "CASH", receivedAccount: "BOOKS_CASH_COUNTER", grossAmount: new Prisma.Decimal(1), discountAmount: new Prisma.Decimal(0), netAmount: new Prisma.Decimal(1), transactionReference: "SECRET" }]); expect(csv).toContain("'=BOOK"); expect(csv).not.toContain("SECRET"); expect(csv).not.toContain("createdByUserId"); });
  it("prints a clearly separated black-and-white book receipt", () => { const source = readFileSync("app/books/sales/[id]/print/page.tsx", "utf8"); expect(source).toContain("Books / Academic Materials Receipt"); expect(source).toContain("not a school-fee receipt"); expect(source).toContain("cancelled-watermark"); });
  it("creates the current backup with every books-finance array and no password hash", () => { const backup = createBackupDocument({ generatedAt: new Date("2026-07-15"), generatedBy: "QA", students: [], feeStructures: [], payments: [], paymentAudits: [], users: [{ id: "u", passwordHash: "secret" }], bookCatalogItems: [], bookCatalogRates: [], bookSaleReceipts: [], bookSaleReceiptLines: [], bookCashSettlements: [] }); expect(backup.metadata.backupVersion).toBe(45); for (const key of ["bookCatalogItems", "bookCatalogRates", "bookSaleReceipts", "bookSaleReceiptLines", "bookCashSettlements"] as const) expect(backup[key]).toEqual([]); expect(JSON.stringify(backup)).not.toContain("passwordHash"); });
  it("keeps version 17 backups compatible when books arrays are absent", () => { const backup: any = createBackupDocument({ generatedAt: new Date("2026-07-15"), generatedBy: "QA", students: [], feeStructures: [], payments: [], paymentAudits: [], users: [] }); backup.metadata.backupVersion = 17; for (const key of ["bookCatalogItems", "bookCatalogRates", "bookSaleReceipts", "bookSaleReceiptLines", "bookCashSettlements"]) { delete backup[key]; delete backup.metadata.counts[key]; } const parsed = parseAndValidateBackup(backup); expect(parsed.bookCatalogItems).toEqual([]); expect(parsed.bookCashSettlements).toEqual([]); });
  it("selects the first newly available catalog item for rate entry", () => { const source = readFileSync("components/books-finance-forms.tsx", "utf8"); expect(source).toContain("useEffect"); expect(source).toContain("if (!rate.itemId && items[0]?.id)"); expect(source).toContain("itemId: items[0].id"); });
  it("clears stale settlement errors before successful save and workflow retries", () => { const source = readFileSync("components/books-finance-forms.tsx", "utf8"); expect(source).toContain('async function save() { setError(""); try'); expect(source).toContain('async function workflow(action: string) { setError(""); try'); });
});
