import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createBackupDocument } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";

function fixture() {
  const now = "2026-07-15T00:00:00.000Z";
  const allocation = { id: "allocation-1", budgetPlanId: "budget-1", categoryId: "category-1", departmentId: "department-1", allocationKey: "category-1|department-1", allocatedAmount: "1000.00", warningThresholdPercent: 80, criticalThresholdPercent: 100, notes: "Annual power", createdAt: now, updatedAt: now };
  return createBackupDocument({ generatedAt: new Date(now), generatedBy: "Director", academicYear: "2026-27", students: [], feeStructures: [], payments: [], paymentAudits: [], users: [{ id: "user-1", username: "director", passwordHash: "must-not-export" }], expenseCategories: [{ id: "category-1", name: "Electricity", code: "ELEC", status: "ACTIVE", createdAt: now, updatedAt: now }], expenseDepartments: [{ id: "department-1", name: "Administration", code: "ADMIN", status: "ACTIVE", createdAt: now, updatedAt: now }], budgetPlans: [{ id: "budget-1", budgetNumber: "BUD-20260715-ABC123", academicYear: "2026-27", title: "Annual Budget", status: "LOCKED", totalAllocatedAmount: "1000.00", warningThresholdPercent: 80, criticalThresholdPercent: 100, createdByUserId: "user-1", submittedByUserId: "user-1", approvedByUserId: "user-1", lockedByUserId: "user-1", submittedAt: now, approvedAt: now, lockedAt: now, createdAt: now, updatedAt: now }], budgetAllocations: [allocation], budgetRevisions: [{ id: "revision-1", budgetPlanId: "budget-1", revisionNumber: 1, reason: "Increase power provision", previousTotalAmount: "900.00", revisedTotalAmount: "1000.00", revisionData: JSON.stringify({ before: [{ ...allocation, allocatedAmount: "900.00" }], after: [allocation] }), status: "APPROVED", createdByUserId: "user-1", submittedByUserId: "user-1", approvedByUserId: "user-1", submittedAt: now, approvedAt: now, createdAt: now }] });
}

describe("budget backup and restore retained in v17", () => {
  it("includes plans, allocations, revisions, and no password hashes", () => { const backup = fixture(); expect(backup.metadata.backupVersion).toBe(45); expect(backup.budgetPlans).toHaveLength(1); expect(backup.budgetAllocations).toHaveLength(1); expect(backup.budgetRevisions).toHaveLength(1); expect(JSON.stringify(backup)).not.toContain("must-not-export"); expect(JSON.stringify(backup)).not.toContain("passwordHash"); });
  it("preserves statuses, thresholds, actor audit fields, and revision snapshots", () => { const parsed = parseAndValidateBackup(fixture()); expect(parsed.budgetPlans[0]).toMatchObject({ status: "LOCKED", warningThresholdPercent: 80, approvedByUserId: "user-1" }); expect(parsed.budgetRevisions[0]).toMatchObject({ status: "APPROVED", revisionNumber: 1 }); });
  it("remains compatible with v15 backups without budget arrays", () => { const backup: any = fixture(); for (const key of ["budgetPlans", "budgetAllocations", "budgetRevisions"]) { delete backup[key]; delete backup.metadata.counts[key]; } backup.metadata.backupVersion = 15; const parsed = parseAndValidateBackup(backup); expect(parsed.budgetPlans).toEqual([]); expect(parsed.budgetAllocations).toEqual([]); expect(parsed.budgetRevisions).toEqual([]); });
  it("rejects duplicate budget numbers and allocation combinations", () => { const plans: any = fixture(); plans.budgetPlans.push({ ...plans.budgetPlans[0], id: "budget-2" }); expect(() => parseAndValidateBackup(plans)).toThrow("budgetNumber is duplicated"); const allocations: any = fixture(); allocations.budgetAllocations.push({ ...allocations.budgetAllocations[0], id: "allocation-2" }); allocations.budgetPlans[0].totalAllocatedAmount = "2000"; expect(() => parseAndValidateBackup(allocations)).toThrow("duplicates a plan allocation combination"); });
  it("rejects unreconciled totals and invalid thresholds", () => { const total: any = fixture(); total.budgetPlans[0].totalAllocatedAmount = "999"; expect(() => parseAndValidateBackup(total)).toThrow("does not reconcile"); const threshold: any = fixture(); threshold.budgetPlans[0].warningThresholdPercent = 101; threshold.budgetPlans[0].criticalThresholdPercent = 100; expect(() => parseAndValidateBackup(threshold)).toThrow("invalid thresholds"); });
  it("validates plan, category, department, and revision links", () => { const plan: any = fixture(); plan.budgetAllocations[0].budgetPlanId = "missing"; expect(() => parseAndValidateBackup(plan)).toThrow("does not match a budget plan"); const category: any = fixture(); category.budgetAllocations[0].categoryId = "missing"; category.budgetAllocations[0].allocationKey = "missing|department-1"; expect(() => parseAndValidateBackup(category)).toThrow("does not match an expense category"); const revision: any = fixture(); revision.budgetRevisions[0].budgetPlanId = "missing"; expect(() => parseAndValidateBackup(revision)).toThrow("does not match a budget plan"); });
  it("rejects invalid academic years and impossible or reversed effective dates", () => { const year: any = fixture(); year.budgetPlans[0].academicYear = "2026"; expect(() => parseAndValidateBackup(year)).toThrow("YYYY-YY"); const impossible: any = fixture(); impossible.budgetPlans[0].effectiveFrom = "2026-02-31"; expect(() => parseAndValidateBackup(impossible)).toThrow("valid calendar date"); const reversed: any = fixture(); reversed.budgetPlans[0].effectiveFrom = "2026-07-16"; reversed.budgetPlans[0].effectiveTo = "2026-07-15"; expect(() => parseAndValidateBackup(reversed)).toThrow("on or after"); });
  it("validates revision snapshot money, combinations, totals, and effective thresholds", () => {
    const amount: any = fixture(); const amountData = JSON.parse(amount.budgetRevisions[0].revisionData); amountData.after[0].allocatedAmount = "1.001"; amount.budgetRevisions[0].revisionData = JSON.stringify(amountData); expect(() => parseAndValidateBackup(amount)).toThrow("at most two decimals");
    const total: any = fixture(); total.budgetRevisions[0].revisedTotalAmount = "999.00"; expect(() => parseAndValidateBackup(total)).toThrow("does not reconcile");
    const duplicate: any = fixture(); const duplicateData = JSON.parse(duplicate.budgetRevisions[0].revisionData); duplicateData.after.push({ ...duplicateData.after[0], id: "second" }); duplicate.budgetRevisions[0].revisionData = JSON.stringify(duplicateData); expect(() => parseAndValidateBackup(duplicate)).toThrow("duplicates a snapshot allocation combination");
    const threshold: any = fixture(); const thresholdData = JSON.parse(threshold.budgetRevisions[0].revisionData); thresholdData.after[0].warningThresholdPercent = 120; thresholdData.after[0].criticalThresholdPercent = null; threshold.budgetRevisions[0].revisionData = JSON.stringify(thresholdData); expect(() => parseAndValidateBackup(threshold)).toThrow("invalid effective thresholds");
  });
  it("rejects two official budgets for one academic year", () => { const backup: any = fixture(); backup.budgetPlans.push({ ...backup.budgetPlans[0], id: "budget-2", budgetNumber: "BUD-2" }); backup.budgetAllocations.push({ ...backup.budgetAllocations[0], id: "allocation-2", budgetPlanId: "budget-2" }); expect(() => parseAndValidateBackup(backup)).toThrow("duplicates the official budget"); });
  it("documents exact-identity collision isolation and local-newer preservation", () => { const source = readFileSync("lib/restore-database.ts", "utf8"); expect(source).toContain("different record identity; its backup allocations and revisions were not restored"); expect(source).toContain("kept because the local record is newer"); expect(source).toContain("planMap.get(backupPlanId)"); });
  it("never deletes local budget data during restore", () => { const source = readFileSync("lib/restore-database.ts", "utf8"); const budgetRestore = source.slice(source.indexOf("export async function restoreBudgetData"), source.indexOf("export async function restoreNoticesData")); expect(budgetRestore).not.toContain("deleteMany"); expect(budgetRestore).not.toContain("delete("); });
});
