import { readFileSync } from "node:fs";
import { Prisma } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { allocationKey, budgetCsv, buildBudgetMetrics, calculateBudgetAmounts, newBudgetNumber, serializeBudget, transitionBudget, validateBudgetAllocations, validateBudgetPlanInput, validateThresholds } from "../lib/budgets";
import { localDate } from "../lib/expenses";
import { moneyExact } from "../lib/format";
import { PERMISSIONS, RECOMMENDED_ROLE_PERMISSIONS } from "../lib/permissions";

const allocation = (overrides: Record<string, unknown> = {}) => ({ categoryId: "cat-1", departmentId: "dept-1", allocatedAmount: "1000", ...overrides });
const input = (overrides: Record<string, unknown> = {}) => ({ academicYear: "2026-27", title: "Annual Plan", warningThresholdPercent: 80, criticalThresholdPercent: 100, allocations: [allocation()], ...overrides });
const reportAllocation = (overrides: any = {}) => ({ id: "a-1", categoryId: "cat-1", departmentId: "dept-1", allocatedAmount: new Prisma.Decimal(1000), warningThresholdPercent: null, criticalThresholdPercent: null, category: { name: "Electricity" }, department: { name: "Admin" }, ...overrides });
const reportExpense = (overrides: any = {}) => ({ categoryId: "cat-1", departmentId: "dept-1", netAmount: new Prisma.Decimal(900), payments: [{ amount: new Prisma.Decimal(400) }], ...overrides });

function workflow(status = "DRAFT", allocations = [{}]) {
  let current = status; const plan: any = { id: "p-1", budgetNumber: "BUD-1", academicYear: "2026-27", status: current, totalAllocatedAmount: new Prisma.Decimal(1000), allocations };
  const budgetPlan = { findUnique: async () => ({ ...plan, status: current }), findFirst: async () => null, updateMany: async ({ where, data }: any) => { if (where.status !== current) return { count: 0 }; current = data.status; Object.assign(plan, data); return { count: 1 }; }, findUniqueOrThrow: async () => ({ ...plan, status: current, allocations: [], revisions: [] }) };
  return { client: { $transaction: async (fn: any) => fn({ budgetPlan }) }, state: () => current };
}

describe("budget plan validation and workflow", () => {
  it("creates a valid calculated draft payload", () => { const value = validateBudgetPlanInput(input()); expect(value.totalAllocatedAmount.toFixed(2)).toBe("1000.00"); expect(value.allocations[0].allocationKey).toBe("cat-1|dept-1"); });
  it("supports category-only, department-only, and combined keys", () => { expect(allocationKey("c", null)).toBe("c|*"); expect(allocationKey(null, "d")).toBe("*|d"); expect(allocationKey("c", "d")).toBe("c|d"); });
  it("requires category or department and a positive exact amount", () => { expect(() => validateBudgetAllocations([{ allocatedAmount: "10" }])).toThrow("category or department"); expect(() => validateBudgetAllocations([allocation({ allocatedAmount: "0" })])).toThrow("greater than zero"); expect(() => validateBudgetAllocations([allocation({ allocatedAmount: "1.001" })])).toThrow("two decimals"); });
  it("blocks duplicate allocation combinations", () => expect(() => validateBudgetAllocations([allocation(), allocation()])).toThrow("duplicates"));
  it("calculates totals from allocations as the authority", () => expect(validateBudgetAllocations([allocation({ allocatedAmount: "100.25" }), allocation({ categoryId: "cat-2", allocatedAmount: "200.75" })]).totalAllocatedAmount.toFixed(2)).toBe("301.00"));
  it("validates warning and critical thresholds", () => { expect(validateThresholds(80, 100)).toEqual({ warningThresholdPercent: 80, criticalThresholdPercent: 100 }); expect(() => validateThresholds(101, 100)).toThrow("lower than or equal"); expect(() => validateThresholds(0, 100)).toThrow("1 to 1000"); expect(() => validateThresholds(80, 1001)).toThrow("1 to 1000"); });
  it("validates per-allocation overrides against inherited plan thresholds", () => {
    expect(() => validateBudgetPlanInput(input({ allocations: [allocation({ warningThresholdPercent: 120 })] }))).toThrow("effective warning threshold");
    expect(() => validateBudgetPlanInput(input({ allocations: [allocation({ criticalThresholdPercent: 50 })] }))).toThrow("effective warning threshold");
    expect(validateBudgetPlanInput(input({ allocations: [allocation({ warningThresholdPercent: 70, criticalThresholdPercent: 90 })] })).allocations[0]).toMatchObject({ warningThresholdPercent: 70, criticalThresholdPercent: 90 });
  });
  it("validates academic year and effective date order", () => { expect(() => validateBudgetPlanInput(input({ academicYear: "2026", }))).toThrow("YYYY-YY"); expect(() => validateBudgetPlanInput(input({ effectiveFrom: "2026-07-02", effectiveTo: "2026-07-01" }))).toThrow("on or after"); });
  it("rejects impossible dates and preserves date-only values at UTC midnight", () => { expect(() => localDate("2026-02-31", "Effective date")).toThrow("invalid"); expect(localDate("2026-07-15").toISOString()).toBe("2026-07-15T00:00:00.000Z"); });
  it("generates unique India-local public budget numbers", () => { const first = newBudgetNumber(new Date("2026-07-14T20:00:00.000Z")); const second = newBudgetNumber(new Date("2026-07-14T20:00:00.000Z")); expect(first).toMatch(/^BUD-20260715-[A-F0-9]{6}$/); expect(second).not.toBe(first); });
  it("submits a non-empty draft and blocks a double submit", async () => { const mock = workflow(); await transitionBudget(mock.client as never, "p-1", "submit", { id: "u", name: "Director" }); expect(mock.state()).toBe("PENDING_APPROVAL"); await expect(transitionBudget(mock.client as never, "p-1", "submit", { id: "u", name: "Director" })).rejects.toThrow("Cannot submit"); });
  it("blocks submitting or approving a plan with no allocations", async () => { await expect(transitionBudget(workflow("DRAFT", []).client as never, "p-1", "submit", { id: "u", name: "Director" })).rejects.toThrow("at least one"); await expect(transitionBudget(workflow("PENDING_APPROVAL", []).client as never, "p-1", "approve", { id: "u", name: "Director" })).rejects.toThrow("no allocations"); });
  it("approves only pending plans and locks only approved plans", async () => { const pending = workflow("PENDING_APPROVAL"); await transitionBudget(pending.client as never, "p-1", "approve", { id: "u", name: "Director" }); expect(pending.state()).toBe("APPROVED"); const approved = workflow("APPROVED"); await transitionBudget(approved.client as never, "p-1", "lock", { id: "u", name: "Director" }); expect(approved.state()).toBe("LOCKED"); await expect(transitionBudget(workflow("DRAFT").client as never, "p-1", "lock", { id: "u", name: "Director" })).rejects.toThrow("Cannot lock"); });
  it("requires rejection and cancellation reasons", async () => { await expect(transitionBudget(workflow("PENDING_APPROVAL").client as never, "p-1", "reject", { id: "u", name: "Director" }, " ")).rejects.toThrow("Rejection reason"); await expect(transitionBudget(workflow("DRAFT").client as never, "p-1", "cancel", { id: "u", name: "Director" }, "")).rejects.toThrow("Cancellation reason"); });
  it("preserves rejected and cancelled statuses", async () => { const rejected = workflow("PENDING_APPROVAL"); await transitionBudget(rejected.client as never, "p-1", "reject", { id: "u", name: "Director" }, "Needs changes"); expect(rejected.state()).toBe("REJECTED"); const cancelled = workflow(); await transitionBudget(cancelled.client as never, "p-1", "cancel", { id: "u", name: "Director" }, "Duplicate"); expect(cancelled.state()).toBe("CANCELLED"); });
  it("does not expose a normal unlock or locked cancellation", async () => { await expect(transitionBudget(workflow("LOCKED").client as never, "p-1", "cancel", { id: "u", name: "Director" }, "No longer needed")).rejects.toThrow("locked budget"); expect(readFileSync("app/api/budgets/[id]/workflow/route.ts", "utf8")).not.toContain('action === "unlock"'); });
  it("guards concurrent transitions with conditional updateMany", () => expect(readFileSync("lib/budgets.ts", "utf8")).toContain("status changed before this action completed"));
  it("keeps approved and locked edits behind revisions", () => { const update = readFileSync("app/api/budgets/[id]/route.ts", "utf8"); expect(update).toContain('status: "DRAFT"'); expect(readFileSync("lib/budgets.ts", "utf8")).toContain("revisionData: JSON.stringify({ before:"); });
});

describe("budget spending calculation", () => {
  it("separates paid, committed, utilized, available, and over-budget", () => { const value = calculateBudgetAmounts(1000, 900, 400); expect(value.paid.toString()).toBe("400"); expect(value.committed.toString()).toBe("500"); expect(value.utilized.toString()).toBe("900"); expect(value.available.toString()).toBe("100"); expect(value.overBudget.toString()).toBe("0"); });
  it("handles partial payment and over-budget amounts", () => { const value = calculateBudgetAmounts(500, 900, 400); expect(value.committed.toString()).toBe("500"); expect(value.overBudget.toString()).toBe("400"); expect(value.utilizationPercent).toBe(180); });
  it("handles zero allocation safely", () => expect(calculateBudgetAmounts(0, 100, 20).utilizationPercent).toBeNull());
  it("keeps exact paise in calculations and consistent two-decimal budget display formatting", () => { const value = calculateBudgetAmounts("1000.25", "900.15", "400.05"); expect(value.committed.toFixed(2)).toBe("500.10"); expect(value.available.toFixed(2)).toBe("100.10"); expect(moneyExact(1000.25)).toContain("1,000.25"); expect(moneyExact(500.1)).toContain("500.10"); });
  it("counts an approved unpaid expense only as committed", () => { const value = calculateBudgetAmounts(1000, 625, 0); expect(value.paid.toString()).toBe("0"); expect(value.committed.toString()).toBe("625"); expect(value.utilized.toString()).toBe("625"); });
  it("uses payment rows for paid actual and net less paid for commitment", () => { const metrics = buildBudgetMetrics({ totalAllocatedAmount: new Prisma.Decimal(1000), warningThresholdPercent: 80, criticalThresholdPercent: 100, allocations: [reportAllocation()] }, [reportExpense()]); expect(metrics.totals.paid.toString()).toBe("400"); expect(metrics.totals.committed.toString()).toBe("500"); });
  it("marks warning at 80 percent and critical at 100 percent", () => { const base = { totalAllocatedAmount: new Prisma.Decimal(1000), warningThresholdPercent: 80, criticalThresholdPercent: 100, allocations: [reportAllocation()] }; expect(buildBudgetMetrics(base, [reportExpense({ netAmount: new Prisma.Decimal(800) })]).allocations[0].thresholdState).toBe("WARNING"); expect(buildBudgetMetrics(base, [reportExpense({ netAmount: new Prisma.Decimal(1000) })]).allocations[0].thresholdState).toBe("CRITICAL"); });
  it("shows available below zero separately from critical", () => { const metrics = buildBudgetMetrics({ totalAllocatedAmount: new Prisma.Decimal(500), warningThresholdPercent: 80, criticalThresholdPercent: 150, allocations: [reportAllocation({ allocatedAmount: new Prisma.Decimal(500), criticalThresholdPercent: 150 })] }, [reportExpense({ netAmount: new Prisma.Decimal(600) })]); expect(metrics.overBudgetCount).toBe(1); expect(metrics.allocations[0].thresholdState).toBe("WARNING"); });
  it("never double-counts an expense across overlapping allocations", () => { const metrics = buildBudgetMetrics({ totalAllocatedAmount: new Prisma.Decimal(2000), warningThresholdPercent: 80, criticalThresholdPercent: 100, allocations: [reportAllocation(), reportAllocation({ id: "a-2", departmentId: null, allocatedAmount: new Prisma.Decimal(1000) })] }, [reportExpense()]); expect(metrics.allocations.reduce((sum, row) => sum.add(row.utilized), new Prisma.Decimal(0)).toString()).toBe("900"); });
  it("matches combined, then category-only, then department-only regardless of row order", () => {
    const departmentOnly = reportAllocation({ id: "department", categoryId: null, departmentId: "dept-1" });
    const categoryOnly = reportAllocation({ id: "category", categoryId: "cat-1", departmentId: null });
    const combined = reportAllocation({ id: "combined", categoryId: "other", departmentId: "dept-1" });
    const metrics = buildBudgetMetrics({ totalAllocatedAmount: new Prisma.Decimal(3000), warningThresholdPercent: 80, criticalThresholdPercent: 100, allocations: [departmentOnly, categoryOnly, combined] }, [reportExpense()]);
    expect(metrics.allocations.find((row) => row.id === "category")?.utilized.toString()).toBe("900");
    expect(metrics.allocations.find((row) => row.id === "department")?.utilized.toString()).toBe("0");
  });
  it("tracks unmatched approved expense amounts in totals", () => { const metrics = buildBudgetMetrics({ totalAllocatedAmount: new Prisma.Decimal(1000), warningThresholdPercent: 80, criticalThresholdPercent: 100, allocations: [reportAllocation()] }, [reportExpense({ categoryId: "other" })]); expect(metrics.unallocatedUtilized.toString()).toBe("900"); expect(metrics.totals.utilized.toString()).toBe("900"); });
  it("queries approved expense records only and never student payments", () => { const source = readFileSync("lib/budgets.ts", "utf8"); expect(source).toContain('approvalStatus: "APPROVED"'); expect(source).toContain("client.expenseRecord.findMany"); expect(source).not.toContain("client.payment.findMany"); });
});

describe("budget permissions, reports, CSV, and API guards", () => {
  const can = (role: keyof typeof RECOMMENDED_ROLE_PERMISSIONS, permission: any) => RECOMMENDED_ROLE_PERMISSIONS[role].has(permission);
  it("registers every budget permission", () => { for (const permission of ["VIEW_BUDGETS", "MANAGE_BUDGETS", "APPROVE_BUDGETS", "LOCK_BUDGETS", "REVISE_BUDGETS", "VIEW_BUDGET_REPORTS", "EXPORT_BUDGET_REPORTS"]) expect(PERMISSIONS).toContain(permission); });
  it("gives Super Admin and Director full control", () => { for (const role of ["SUPER_ADMIN", "DIRECTOR"] as const) for (const permission of ["VIEW_BUDGETS", "MANAGE_BUDGETS", "APPROVE_BUDGETS", "LOCK_BUDGETS", "REVISE_BUDGETS"]) expect(can(role, permission)).toBe(true); });
  it("keeps Admin and Accountant draft-scoped without approve, lock, or revise", () => { for (const role of ["ADMIN", "ACCOUNTANT"] as const) { expect(can(role, "MANAGE_BUDGETS")).toBe(true); expect(can(role, "EXPORT_BUDGET_REPORTS")).toBe(true); expect(can(role, "APPROVE_BUDGETS")).toBe(false); expect(can(role, "LOCK_BUDGETS")).toBe(false); expect(can(role, "REVISE_BUDGETS")).toBe(false); } });
  it("keeps Principal and Viewer read-only and blocks Teacher and Parent", () => { for (const role of ["PRINCIPAL", "VIEWER"] as const) { expect(can(role, "VIEW_BUDGETS")).toBe(true); expect(can(role, "VIEW_BUDGET_REPORTS")).toBe(true); expect(can(role, "MANAGE_BUDGETS")).toBe(false); expect(can(role, "EXPORT_BUDGET_REPORTS")).toBe(false); } for (const role of ["TEACHER", "PARENT"] as const) expect(can(role, "VIEW_BUDGETS")).toBe(false); });
  it("guards all pages server-side", () => { for (const [file, permission] of [["app/budgets/page.tsx", "VIEW_BUDGETS"], ["app/budgets/new/page.tsx", "MANAGE_BUDGETS"], ["app/budgets/[id]/page.tsx", "VIEW_BUDGETS"], ["app/budgets/reports/page.tsx", "VIEW_BUDGET_REPORTS"]]) expect(readFileSync(file, "utf8")).toContain(`requirePermission("${permission}")`); });
  it("guards direct APIs by action", () => { const workflow = readFileSync("app/api/budgets/[id]/workflow/route.ts", "utf8"); for (const permission of ["MANAGE_BUDGETS", "APPROVE_BUDGETS", "LOCK_BUDGETS"]) expect(workflow).toContain(permission); expect(readFileSync("app/api/budgets/reports/export/route.ts", "utf8")).toContain('requireApiPermission("EXPORT_BUDGET_REPORTS")'); });
  it("keeps cancellation with budget approvers rather than draft managers", () => { const workflow = readFileSync("app/api/budgets/[id]/workflow/route.ts", "utf8"); expect(workflow).toContain('action === "approve" || action === "reject" || action === "cancel" ? "APPROVE_BUDGETS"'); const actions = readFileSync("components/budget-actions.tsx", "utf8"); expect(actions).toContain('includes(budget.status) && permissions.approve'); });
  it("does not expose a budget deletion endpoint", () => { expect(readFileSync("app/api/budgets/[id]/route.ts", "utf8")).not.toContain("export async function DELETE"); });
  it("keeps budget summary cards in a responsive grid and clears stale allocation feedback", () => { const css = readFileSync("app/globals.css", "utf8"); expect(css).toMatch(/\.stats\s*\{\s*display:\s*grid;\s*gap:\s*14px;/); const form = readFileSync("components/budget-form.tsx", "utf8"); expect(form).toContain('const clearFeedback = () => { setError(""); setMessage(""); };'); expect(form).toContain('onClick={() => { clearFeedback(); setPreview(true); }}'); });
  it("formula-protects every CSV cell and exports no raw actor IDs", () => { const csv = budgetCsv([{ "Budget Number": "=cmd", "Academic Year": "2026-27", Category: "+SUM(1)", Department: "@bad" }]); expect(csv).toContain("'=cmd"); expect(csv).toContain("'+SUM(1)"); expect(csv).toContain("'@bad"); expect(csv).not.toContain("approvedByUserId"); });
  it("serializes actor names without actor IDs or revision snapshots", () => { const safe: any = serializeBudget({ id: "p", budgetNumber: "B", academicYear: "2026-27", title: "T", description: null, status: "APPROVED", totalAllocatedAmount: new Prisma.Decimal(1), warningThresholdPercent: 80, criticalThresholdPercent: 100, createdByUserId: "secret", createdBy: { name: "Director" }, allocations: [], revisions: [{ id: "r", revisionNumber: 1, reason: "More", previousTotalAmount: new Prisma.Decimal(1), revisedTotalAmount: new Prisma.Decimal(2), revisionData: "SECRET", status: "APPROVED", createdBy: { name: "Director" } }] }); expect(safe.createdBy).toBe("Director"); expect(JSON.stringify(safe)).not.toContain("createdByUserId"); expect(JSON.stringify(safe)).not.toContain("SECRET"); });
  it("uses a partial unique database index for one official plan per year", () => expect(readFileSync("prisma/migration-archives/devops1b-legacy-chain/20260715_budget_spending_controls/migration.sql", "utf8")).toContain("BudgetPlan_one_official_per_year"));
});
