import { readFileSync } from "node:fs";
import { Prisma } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { assertOpeningBalanceProvenance, calculateCashSources, cashBookCsv, cashSourceSnapshot, hasSourceDrift, missingCashBookDateKeys, validateMovementInput } from "../lib/cash-book";
import { can, PERMISSIONS } from "../lib/permissions";

function db(data: any = {}) { return { payment: { findMany: async (args: any) => { data.paymentWhere = args.where; return data.fees ?? []; } }, miscIncomeReceipt: { findMany: async (args: any) => { data.miscWhere = args.where; return data.misc ?? []; } }, expensePayment: { findMany: async (args: any) => { data.expenseWhere = args.where; return data.expenses ?? []; } }, cashBookMovement: { findMany: async (args: any) => { data.movementWhere = args.where; return data.movements ?? []; } } } as any; }
const day = new Date("2026-07-15T00:00:00.000Z");
describe("daily cash book foundation", () => {
  it("calculates fee cash only and ignores UPI fee rows", async () => { const result = await calculateCashSources(db({ fees: [{ amountPaid: 100.25, paymentMode: "Cash" }, { amountPaid: 900, paymentMode: "UPI" }] }), day, new Prisma.Decimal(10)); expect(result.feeCash.toFixed(2)).toBe("100.25"); expect(result.expectedClosing.toFixed(2)).toBe("110.25"); });
  it("counts miscellaneous CASH and no non-cash rows by authoritative query", async () => { const state: any = { misc: [{ netAmount: new Prisma.Decimal("45.55") }] }; const result = await calculateCashSources(db(state), day, new Prisma.Decimal(0)); expect(result.miscIncomeCash.toFixed(2)).toBe("45.55"); expect(state.miscWhere).toMatchObject({ status: "ACTIVE", paymentMethod: "CASH" }); });
  it("counts every partial cash expense payment once", async () => { const result = await calculateCashSources(db({ expenses: [{ amount: new Prisma.Decimal(20), paymentMethod: "CASH" }, { amount: new Prisma.Decimal(30), paymentMethod: "cash" }, { amount: new Prisma.Decimal(100), paymentMethod: "UPI" }] }), day, new Prisma.Decimal(100)); expect(result.cashExpense.toFixed(2)).toBe("50.00"); expect(result.expectedClosing.toFixed(2)).toBe("50.00"); });
  it("counts only approved cash expenses through the authoritative relation filter", async () => { const state: any = {}; await calculateCashSources(db(state), day, new Prisma.Decimal(0)); expect(state.expenseWhere.expenseRecord.approvalStatus).toBe("APPROVED"); });
  it("supports bank deposit disposition", async () => { const result = await calculateCashSources(db({ movements: [{ amount: new Prisma.Decimal(60), movementType: "BANK_DEPOSIT" }] }), day, new Prisma.Decimal(100), "day-1"); expect(result.bankDeposit.toFixed(2)).toBe("60.00"); expect(result.expectedClosing.toFixed(2)).toBe("40.00"); });
  it("supports Director handover disposition", async () => { const result = await calculateCashSources(db({ movements: [{ amount: new Prisma.Decimal(25), movementType: "DIRECTOR_HANDOVER" }] }), day, new Prisma.Decimal(100), "day-1"); expect(result.directorHandover.toFixed(2)).toBe("25.00"); expect(result.expectedClosing.toFixed(2)).toBe("75.00"); });
  it("supports split deposit and Director handover", async () => { const result = await calculateCashSources(db({ movements: [{ amount: new Prisma.Decimal(40), movementType: "BANK_DEPOSIT" }, { amount: new Prisma.Decimal(30), movementType: "DIRECTOR_HANDOVER" }] }), day, new Prisma.Decimal(100), "day-1"); expect(result.expectedClosing.toFixed(2)).toBe("30.00"); });
  it("applies manual and adjustment inflows/outflows without recreating sources", async () => { const movements = [{ amount: new Prisma.Decimal(10), movementType: "MANUAL_INFLOW" }, { amount: new Prisma.Decimal(5), movementType: "ADJUSTMENT_IN" }, { amount: new Prisma.Decimal(3), movementType: "MANUAL_OUTFLOW" }, { amount: new Prisma.Decimal(2), movementType: "ADJUSTMENT_OUT" }]; const result = await calculateCashSources(db({ movements }), day, new Prisma.Decimal(0), "day-1"); expect(result.manualInflow.toFixed(2)).toBe("15.00"); expect(result.manualOutflow.toFixed(2)).toBe("5.00"); expect(result.expectedClosing.toFixed(2)).toBe("10.00"); });
  it("preserves exact paise across the full formula", async () => { const result = await calculateCashSources(db({ fees: [{ amountPaid: 10.11, paymentMode: "Cash" }], misc: [{ netAmount: new Prisma.Decimal("20.22") }], expenses: [{ amount: new Prisma.Decimal("3.03"), paymentMethod: "CASH" }] }), day, new Prisma.Decimal("0.01")); expect(result.expectedClosing.toFixed(2)).toBe("27.31"); });
  it("creates stable snapshots and detects source drift", async () => { const one = await calculateCashSources(db({ fees: [{ amountPaid: 10, paymentMode: "Cash" }] }), day, new Prisma.Decimal(0)); const snapshot = cashSourceSnapshot(one); expect(hasSourceDrift(snapshot, one)).toBe(false); const two = await calculateCashSources(db({ fees: [{ amountPaid: 11, paymentMode: "Cash" }] }), day, new Prisma.Decimal(0)); expect(hasSourceDrift(snapshot, two)).toBe(true); });
  it("requires positive movement amounts", () => { expect(() => validateMovementInput({ movementType: "BANK_DEPOSIT", amount: -1, movementDate: "2026-07-15", reason: "Deposit" }, day)).toThrow(/non-negative|greater than zero/); });
  it("requires movement date to match the India-local cash day", () => { expect(() => validateMovementInput({ movementType: "DIRECTOR_HANDOVER", amount: 1, movementDate: "2026-07-16", reason: "Handover" }, day)).toThrow(/must match/); });
  it("requires documented movement reasons", () => { expect(() => validateMovementInput({ movementType: "ADJUSTMENT_IN", amount: 1, movementDate: "2026-07-15", reason: "" }, day)).toThrow(/reason is required/); });
  it("enforces opening-balance provenance on both create and draft update paths", async () => {
    const noPrevious: any = { cashBookDay: { findFirst: async () => null } };
    await expect(assertOpeningBalanceProvenance(noPrevious, day, new Prisma.Decimal(10), null)).rejects.toThrow(/note is required/i);
    await expect(assertOpeningBalanceProvenance(noPrevious, day, new Prisma.Decimal(10), "Opening cash verified")).resolves.toBeNull();
    const previous: any = { cashBookDay: { findFirst: async () => ({ countedClosingBalance: new Prisma.Decimal(25), cashDate: new Date("2026-07-14") }) } };
    await expect(assertOpeningBalanceProvenance(previous, day, new Prisma.Decimal(10), null)).rejects.toThrow(/differs from the previous locked day/i);
    await expect(assertOpeningBalanceProvenance(previous, day, new Prisma.Decimal(25), null)).resolves.toMatchObject({ amount: new Prisma.Decimal(25) });
    const helper = readFileSync("lib/cash-book.ts", "utf8");
    expect(helper.match(/assertOpeningBalanceProvenance\(tx/g)).toHaveLength(2);
  });
  it("formula-protects cash-book CSV and uses requested wording", () => { const row: any = { cashDate: day, status: "LOCKED", openingBalance: new Prisma.Decimal(0), feeCashSnapshot: new Prisma.Decimal(0), miscIncomeCashSnapshot: new Prisma.Decimal(0), manualInflowSnapshot: new Prisma.Decimal(0), cashExpenseSnapshot: new Prisma.Decimal(0), manualOutflowSnapshot: new Prisma.Decimal(0), bankDepositSnapshot: new Prisma.Decimal(0), directorHandoverSnapshot: new Prisma.Decimal(0), calculatedClosingBalance: new Prisma.Decimal(0), countedClosingBalance: new Prisma.Decimal(0), varianceAmount: new Prisma.Decimal(0), sourceDrift: false }; const csv = cashBookCsv([{ ...row, status: "=LOCKED" }]); expect(csv).toContain("Deposited to School Current Account"); expect(csv).toContain("Handed to Director Sir"); expect(csv).toContain("'=LOCKED"); });
  it("exports live draft totals instead of zero snapshot placeholders", () => { const zero = new Prisma.Decimal(0); const row: any = { cashDate: day, status: "DRAFT", openingBalance: zero, feeCashSnapshot: zero, miscIncomeCashSnapshot: zero, manualInflowSnapshot: zero, cashExpenseSnapshot: zero, manualOutflowSnapshot: zero, bankDepositSnapshot: zero, directorHandoverSnapshot: zero, calculatedClosingBalance: new Prisma.Decimal("12.34"), countedClosingBalance: null, varianceAmount: null, sourceDrift: false, reportSources: { feeCash: new Prisma.Decimal("10.11"), miscIncomeCash: new Prisma.Decimal("2.22"), manualInflow: new Prisma.Decimal("0.01"), cashExpense: zero, manualOutflow: zero, bankDeposit: zero, directorHandover: zero, expectedClosing: new Prisma.Decimal("12.34") } }; expect(cashBookCsv([row])).toContain('"10.11","2.22","0.00","0.01"'); });
  it("adds complete permissions with leadership-only approval and lock defaults", () => { for (const permission of ["VIEW_CASH_BOOK", "MANAGE_CASH_BOOK", "SUBMIT_CASH_BOOK", "APPROVE_CASH_BOOK", "LOCK_CASH_BOOK", "CANCEL_CASH_BOOK", "VIEW_CASH_BOOK_REPORTS", "EXPORT_CASH_BOOK_REPORTS"]) expect(PERMISSIONS).toContain(permission); expect(can("DIRECTOR", "APPROVE_CASH_BOOK")).toBe(true); expect(can("DIRECTOR", "LOCK_CASH_BOOK")).toBe(true); expect(can("ACCOUNTANT", "SUBMIT_CASH_BOOK")).toBe(true); expect(can("ACCOUNTANT", "APPROVE_CASH_BOOK")).toBe(false); expect(can("ADMIN", "LOCK_CASH_BOOK")).toBe(false); });
  it("keeps Principal and Viewer read-only and blocks Teacher/Parent", () => { for (const role of ["PRINCIPAL", "VIEWER"] as const) { expect(can(role, "VIEW_CASH_BOOK_REPORTS")).toBe(true); expect(can(role, "MANAGE_CASH_BOOK")).toBe(false); } for (const role of ["TEACHER", "PARENT"] as const) expect(can(role, "VIEW_CASH_BOOK")).toBe(false); });
  it("guards all cash-book pages and direct workflow APIs", () => { expect(readFileSync("app/cash-book/page.tsx", "utf8")).toContain('requirePermission("VIEW_CASH_BOOK")'); expect(readFileSync("app/cash-book/reports/page.tsx", "utf8")).toContain('requirePermission("VIEW_CASH_BOOK_REPORTS")'); const workflow = readFileSync("app/api/cash-book/[date]/workflow/route.ts", "utf8"); for (const permission of ["SUBMIT_CASH_BOOK", "APPROVE_CASH_BOOK", "LOCK_CASH_BOOK", "CANCEL_CASH_BOOK"]) expect(workflow).toContain(permission); });
  it("serializes newly created cash days instead of exposing raw actor IDs", () => { const source = readFileSync("app/api/cash-book/route.ts", "utf8"); expect(source).toContain("cashBookView(prisma, row"); expect(source).not.toContain("NextResponse.json({ day: row }"); });
  it("uses compare-and-set transitions and has no casual unlock", () => { const source = readFileSync("lib/cash-book.ts", "utf8"); expect(source).toContain("updateMany"); expect(source).toContain("updatedAt: current.updatedAt"); expect(source).not.toContain('action === "unlock"'); expect(source).toContain("Locked or cancelled cash days cannot be cancelled"); });
  it("does not manually recreate fee, miscellaneous, or expense sources", () => { const source = readFileSync("lib/cash-book.ts", "utf8"); expect(source).toContain("client.payment.findMany"); expect(source).toContain("client.miscIncomeReceipt.findMany"); expect(source).toContain("client.expensePayment.findMany"); expect(source).not.toContain("client.payment.create"); });
  it("serializes India-local cash and movement dates as API-safe date keys", () => { const helper = readFileSync("lib/cash-book.ts", "utf8"); const form = readFileSync("components/cash-book-form.tsx", "utf8"); expect(helper).toContain("cashDate: row.cashDate.toISOString().slice(0, 10)"); expect(helper).toContain("movementDate: movement.movementDate.toISOString().slice(0, 10)"); expect(form).toContain("/^\\d{4}-\\d{2}-\\d{2}/"); });
  it("uses explicit in-page reason confirmations for destructive workflow actions", () => { const source = readFileSync("components/cash-book-form.tsx", "utf8"); expect(source).toContain("Reason confirmation"); expect(source).toContain("Confirm cancellation"); expect(source).not.toContain("window.prompt"); });
  it("renders a safe validation response for impossible cash-book dates", () => { const source = readFileSync("app/cash-book/[date]/page.tsx", "utf8"); expect(source).toContain("Invalid cash-book date"); expect(source).toContain("real India-local calendar date"); expect(source).toContain("try {"); expect(source).toContain('cashDate = localDate(date, "Cash date")'); });
  it("reports missing calendar dates without treating preserved days as missing", () => { expect(missingCashBookDateKeys([{ cashDate: new Date("2026-07-13T00:00:00.000Z") }, { cashDate: new Date("2026-07-15T00:00:00.000Z") }], "2026-07-15")).toEqual(["2026-07-14"]); });
  it("reports today when no cash-book history exists", () => { expect(missingCashBookDateKeys([], "2026-07-15")).toEqual(["2026-07-15"]); expect(readFileSync("app/cash-book/reports/page.tsx", "utf8")).toContain("Missing-day report"); });
});
