import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createBackupDocument } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";

function backupWithExpenses() {
  return createBackupDocument({ generatedAt: new Date("2026-07-15T00:00:00.000Z"), generatedBy: "Director", academicYear: "2026-27", students: [], feeStructures: [], payments: [], paymentAudits: [], users: [{ id: "user-1", username: "director", passwordHash: "must-not-export" }], vendors: [{ id: "vendor-1", vendorCode: "V001", name: "Vendor", status: "ACTIVE", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }], expenseCategories: [{ id: "category-1", name: "Electricity", code: "ELEC", status: "ACTIVE", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }], expenseDepartments: [{ id: "department-1", name: "General", code: "GEN", status: "ACTIVE", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }], expenseRecords: [{ id: "expense-1", expenseNumber: "EXP-20260715-ABC123", expenseDate: "2026-07-15T00:00:00.000Z", academicYear: "2026-27", vendorId: "vendor-1", categoryId: "category-1", departmentId: "department-1", description: "Bill", grossAmount: "100", taxAmount: "18", deductionAmount: "0", netAmount: "118", paymentMethod: "UPI", paymentStatus: "PAID", approvalStatus: "APPROVED", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }], expensePayments: [{ id: "pay-1", expenseRecordId: "expense-1", paymentDate: "2026-07-15T00:00:00.000Z", amount: "118", paymentMethod: "UPI", transactionReference: "UPI-1", createdAt: "2026-07-15T00:00:00.000Z" }], expenseAudits: [{ id: "audit-1", expenseRecordId: "expense-1", action: "PAYMENT_RECORDED", actorName: "Director", createdAt: "2026-07-15T00:00:00.000Z" }] });
}

describe("expense backup and restore retained in v17", () => {
  it("includes all expense entities and excludes password hashes", () => { const backup = backupWithExpenses(); expect(backup.metadata.backupVersion).toBe(40); expect(backup.vendors).toHaveLength(1); expect(backup.expenseCategories).toHaveLength(1); expect(backup.expenseDepartments).toHaveLength(1); expect(backup.expenseRecords).toHaveLength(1); expect(backup.expensePayments).toHaveLength(1); expect(backup.expenseAudits).toHaveLength(1); expect(JSON.stringify(backup)).not.toContain("must-not-export"); expect(JSON.stringify(backup)).not.toContain("passwordHash"); });
  it("validates v15 links, statuses, amounts, and audit fields", () => { const parsed = parseAndValidateBackup(backupWithExpenses()); expect(parsed.expenseRecords[0]).toMatchObject({ expenseNumber: "EXP-20260715-ABC123", netAmount: "118" }); expect(parsed.expensePayments[0]).toMatchObject({ transactionReference: "UPI-1" }); });
  it("rejects inconsistent restored money", () => { const backup = backupWithExpenses() as any; backup.expenseRecords[0].netAmount = "999"; expect(() => parseAndValidateBackup(backup)).toThrow("inconsistent amounts"); });
  it("rejects over-precision/exponent money and unsafe restored vendor banking fields", () => { const exponent = backupWithExpenses() as any; exponent.expenseRecords[0].grossAmount = "1e2"; expect(() => parseAndValidateBackup(exponent)).toThrow("at most two decimals"); const overPrecision = backupWithExpenses() as any; overPrecision.expensePayments[0].amount = "118.001"; expect(() => parseAndValidateBackup(overPrecision)).toThrow("at most two decimals"); const banking = backupWithExpenses() as any; banking.vendors[0].accountLastFour = "1234567890"; expect(() => parseAndValidateBackup(banking)).toThrow("accountLastFour"); });
  it("rejects impossible restored workflow status combinations", () => { const backup = backupWithExpenses() as any; backup.expenseRecords[0].approvalStatus = "REJECTED"; backup.expenseRecords[0].rejectionReason = "Invalid"; expect(() => parseAndValidateBackup(backup)).toThrow("cannot be paid before approval"); });
  it("remains compatible with older backups that omit expense arrays", () => { const backup: any = backupWithExpenses(); delete backup.vendors; delete backup.expenseCategories; delete backup.expenseDepartments; delete backup.expenseRecords; delete backup.expensePayments; delete backup.expenseAudits; backup.metadata.backupVersion = 14; for (const key of ["vendors", "expenseCategories", "expenseDepartments", "expenseRecords", "expensePayments", "expenseAudits"]) delete backup.metadata.counts[key]; const parsed = parseAndValidateBackup(backup); expect(parsed.expenseRecords).toEqual([]); expect(parsed.vendors).toEqual([]); });
  it("documents duplicate avoidance, collision isolation, and local-newer preservation in restore code", () => { const source = readFileSync("lib/restore-database.ts", "utf8"); expect(source).toContain("kept because the local record is newer"); expect(source).toContain("findUnique({ where: { expenseNumber } })"); expect(source).toContain("different record identity"); expect(source).toContain("expenseMap.set(backupId, existing.id)"); });
});
