import { readFileSync } from "node:fs";
import { Prisma } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { buildExpenseReports, csvCell, expenseCsv, localDate, moneyDecimal, newExpenseNumber, recordExpensePayment, serializeExpense, transitionExpense, validateActiveExpenseMasters, validateExpenseAmounts, validateExpenseInput, validatePaymentReference } from "../lib/expenses";
import { can, PERMISSIONS } from "../lib/permissions";

const valid = { expenseDate: "2026-07-15", academicYear: "2026-27", categoryId: "category-1", description: "Electricity bill", grossAmount: "1000.00", taxAmount: "180.00", deductionAmount: "20.00", netAmount: "1160.00", paymentMethod: "UPI" };
const reportRow = (overrides: Record<string, unknown> = {}) => ({ expenseNumber: "EXP-1", expenseDate: new Date("2026-07-15T00:00:00.000Z"), academicYear: "2026-27", vendor: { name: "Power Co" }, category: { name: "Electricity" }, department: { name: "Administration" }, description: "Bill", grossAmount: new Prisma.Decimal(100), taxAmount: new Prisma.Decimal(0), deductionAmount: new Prisma.Decimal(0), netAmount: new Prisma.Decimal(100), approvalStatus: "APPROVED", paymentStatus: "UNPAID", paymentMethod: "UPI", ...overrides });

function workflowClient(initial = "DRAFT") {
  let approvalStatus = initial; let paymentStatus = "UNPAID"; const audits: any[] = []; const payments: any[] = [];
  const expenseRecord = {
    findUnique: async () => ({ approvalStatus, paymentStatus, netAmount: new Prisma.Decimal(100), payments }),
    updateMany: async ({ where, data }: any) => { if (where.approvalStatus !== approvalStatus || (where.paymentStatus && where.paymentStatus !== paymentStatus)) return { count: 0 }; approvalStatus = data.approvalStatus ?? approvalStatus; paymentStatus = data.paymentStatus ?? paymentStatus; return { count: 1 }; },
    findUniqueOrThrow: async () => ({ id: "expense-1", approvalStatus, paymentStatus, netAmount: new Prisma.Decimal(100), payments: [], audits: [] })
  };
  const tx = { expenseRecord, expenseAudit: { create: async ({ data }: any) => { audits.push(data); } }, expensePayment: { create: async ({ data }: any) => { payments.push({ ...data, amount: new Prisma.Decimal(data.amount) }); } } };
  return { client: { $transaction: async (callback: any) => callback(tx) }, state: () => ({ approvalStatus, paymentStatus, audits, payments }) };
}

describe("expense validation and workflow", () => {
  it("uses Decimal money and accepts an exact gross plus tax minus deduction", () => { const result = validateExpenseAmounts(valid); expect(result.netAmount.toFixed(2)).toBe("1160.00"); });
  it("rejects inconsistent net amounts", () => expect(() => validateExpenseAmounts({ ...valid, netAmount: "1159.99" })).toThrow("must equal"));
  it("rejects negative or over-precision money without rounding numeric input", () => { expect(() => moneyDecimal("-1", "Amount")).toThrow(); expect(() => moneyDecimal("1.001", "Amount")).toThrow(); expect(() => moneyDecimal(1.005, "Amount")).toThrow(); });
  it("preserves valid calendar days and rejects normalized impossible dates", () => { expect(localDate("2026-07-15").toISOString()).toBe("2026-07-15T00:00:00.000Z"); expect(() => localDate("15/07/2026")).toThrow(); expect(() => localDate("2026-02-31")).toThrow("invalid"); });
  it("validates draft expense input and preserves its invoice day without silently recalculating", () => { const value = validateExpenseInput({ ...valid, invoiceDate: "2026-07-15" }); expect(value.netAmount.toFixed(2)).toBe("1160.00"); expect(value.paymentMethod).toBe("UPI"); expect(value.invoiceDate?.toISOString()).toBe("2026-07-15T00:00:00.000Z"); });
  it("requires references for final non-cash payments", () => expect(() => validatePaymentReference({ paymentMethod: "UPI" }, true)).toThrow("Transaction reference"));
  it("does not require a reference for cash", () => expect(validatePaymentReference({ paymentMethod: "CASH" }, true).transactionReference).toBeNull());
  it("requires cheque number and date together", () => expect(() => validatePaymentReference({ paymentMethod: "CHEQUE", chequeNumber: "123" }, true)).toThrow("Cheque number and cheque date"));
  it("clears reference fields that do not belong to the selected method", () => { expect(validatePaymentReference({ paymentMethod: "CASH", transactionReference: "SHOULD-CLEAR", chequeNumber: "123" }, false)).toMatchObject({ transactionReference: null, chequeNumber: null, chequeDate: null }); expect(validatePaymentReference({ paymentMethod: "UPI", transactionReference: "UPI-1", chequeNumber: "123", chequeDate: "2026-07-15" }, true)).toMatchObject({ transactionReference: "UPI-1", chequeNumber: null, chequeDate: null }); expect(validatePaymentReference({ paymentMethod: "CHEQUE", transactionReference: "SHOULD-CLEAR", chequeNumber: "123", chequeDate: "2026-07-15" }, true)).toMatchObject({ transactionReference: null, chequeNumber: "123" }); });
  it("requires every selected master to be active", async () => { const client = { vendor: { findFirst: async () => null }, expenseCategory: { findFirst: async () => ({ id: "category-1" }) }, expenseDepartment: { findFirst: async () => ({ id: "department-1" }) } }; await expect(validateActiveExpenseMasters(client as never, { vendorId: "vendor-1", categoryId: "category-1", departmentId: "department-1" })).rejects.toThrow("Vendor must be active"); await expect(validateActiveExpenseMasters({ ...client, vendor: { findFirst: async () => ({ id: "vendor-1" }) } } as never, { vendorId: "vendor-1", categoryId: "category-1", departmentId: "department-1" })).resolves.toBeUndefined(); });
  it("generates unique public expense numbers", () => { const first = newExpenseNumber(new Date("2026-07-15T12:00:00Z")); const second = newExpenseNumber(new Date("2026-07-15T12:00:00Z")); expect(first).toMatch(/^EXP-20260715-[A-F0-9]{6}$/); expect(second).not.toBe(first); });
  it("submits a draft transactionally with audit", async () => { const mock = workflowClient(); await transitionExpense(mock.client as never, "expense-1", "submit", { id: "user-1", name: "Director" }); expect(mock.state()).toMatchObject({ approvalStatus: "PENDING_APPROVAL" }); expect(mock.state().audits[0]).toMatchObject({ action: "SUBMIT", fromStatus: "DRAFT", toStatus: "PENDING_APPROVAL", actorName: "Director" }); });
  it("approves only pending records", async () => { const mock = workflowClient("PENDING_APPROVAL"); await transitionExpense(mock.client as never, "expense-1", "approve", { id: "user-1", name: "Director" }); expect(mock.state().approvalStatus).toBe("APPROVED"); const invalid = workflowClient("DRAFT"); await expect(transitionExpense(invalid.client as never, "expense-1", "approve", { id: "user-1", name: "Director" })).rejects.toThrow("Cannot approve"); });
  it("requires a rejection reason", async () => { const mock = workflowClient("PENDING_APPROVAL"); await expect(transitionExpense(mock.client as never, "expense-1", "reject", { id: "user-1", name: "Director" }, " ")).rejects.toThrow("Rejection reason"); });
  it("preserves rejected status and reason in audit", async () => { const mock = workflowClient("PENDING_APPROVAL"); await transitionExpense(mock.client as never, "expense-1", "reject", { id: "user-1", name: "Director" }, "Invoice mismatch"); expect(mock.state().approvalStatus).toBe("REJECTED"); expect(mock.state().audits[0].detailsJson).toContain("Invoice mismatch"); });
  it("requires cancellation reason and marks payment cancelled", async () => { const mock = workflowClient("APPROVED"); await expect(transitionExpense(mock.client as never, "expense-1", "cancel", { id: "user-1", name: "Director" }, "")).rejects.toThrow("Cancellation reason"); await transitionExpense(mock.client as never, "expense-1", "cancel", { id: "user-1", name: "Director" }, "Duplicate bill"); expect(mock.state()).toMatchObject({ approvalStatus: "CANCELLED", paymentStatus: "CANCELLED" }); });
  it("blocks double/concurrent transitions", async () => { const mock = workflowClient(); await transitionExpense(mock.client as never, "expense-1", "submit", { id: "user-1", name: "Director" }); await expect(transitionExpense(mock.client as never, "expense-1", "submit", { id: "user-1", name: "Director" })).rejects.toThrow("Cannot submit"); });
  it("records partial and final payments separately", async () => { const mock = workflowClient("APPROVED"); await recordExpensePayment(mock.client as never, "expense-1", { amount: "40", paymentDate: "2026-07-15", paymentMethod: "CASH" }, { id: "user-1", name: "Accountant" }); expect(mock.state().paymentStatus).toBe("PARTIALLY_PAID"); await recordExpensePayment(mock.client as never, "expense-1", { amount: "60", paymentDate: "2026-07-16", paymentMethod: "UPI", transactionReference: "UPI-1" }, { id: "user-1", name: "Accountant" }); expect(mock.state()).toMatchObject({ paymentStatus: "PAID" }); expect(mock.state().payments).toHaveLength(2); });
  it("blocks overpayment and paying non-approved records", async () => { const approved = workflowClient("APPROVED"); await expect(recordExpensePayment(approved.client as never, "expense-1", { amount: "101", paymentDate: "2026-07-15", paymentMethod: "CASH" }, { id: "u", name: "A" })).rejects.toThrow("exceeds"); const rejected = workflowClient("REJECTED"); await expect(recordExpensePayment(rejected.client as never, "expense-1", { amount: "10", paymentDate: "2026-07-15", paymentMethod: "CASH" }, { id: "u", name: "A" })).rejects.toThrow("Only an approved"); });
});

describe("expense reporting, CSV, permissions, and guards", () => {
  it("excludes cancelled totals from active spend", () => { const report = buildExpenseReports([reportRow(), reportRow({ expenseNumber: "EXP-2", netAmount: new Prisma.Decimal(500), approvalStatus: "CANCELLED", paymentStatus: "CANCELLED" })]); expect(report.total).toBe("100"); expect(report.cancelledCount).toBe(1); });
  it("builds date/vendor/category/department/payment/approval summaries", () => { const report = buildExpenseReports([reportRow()]); expect(report.vendorWise).toEqual([{ label: "Power Co", total: "100" }]); expect(report.categoryWise[0].label).toBe("Electricity"); expect(report.paymentStatus[0].label).toBe("UNPAID"); });
  it("protects every CSV cell from spreadsheet formulas", () => { for (const value of ["=cmd", "+SUM(1)", "-2+3", "@evil", "\tformula", "\rformula"]) expect(csvCell(value)).toMatch(/^"'/); });
  it("exports allowlisted columns without IDs or secrets", () => { const csv = expenseCsv([{ ...reportRow(), expenseDate: "2026-07-15", vendor: "=Power", category: "Electricity", department: "Admin", grossAmount: "100", taxAmount: "0", deductionAmount: "0", netAmount: "100" }]); expect(csv).toContain("Expense Number"); expect(csv).toContain("'=Power"); expect(csv).not.toContain("createdByUserId"); expect(csv).not.toContain("passwordHash"); });
  it("omits payment references, reasons, notes, and finance actors from restricted payloads", () => { const row = { id: "expense-1", ...reportRow(), vendor: { id: "v1", vendorCode: "V1", name: "Power Co" }, category: { id: "c1", name: "Electricity", code: "ELEC" }, department: null, invoiceNumber: null, invoiceDate: null, transactionReference: "UPI-SECRET", chequeNumber: null, chequeDate: null, paidDate: null, notes: "private", rejectionReason: "private", cancellationReason: "private", submittedAt: null, approvedAt: new Date(), paidAt: null, cancelledAt: null, createdAt: new Date(), updatedAt: new Date(), createdBy: { name: "Director" }, submittedBy: null, approvedBy: { name: "Director" }, paidBy: null, cancelledBy: null, payments: [{ id: "p1", paymentDate: new Date(), amount: new Prisma.Decimal(100), paymentMethod: "UPI", transactionReference: "PAY-SECRET", chequeNumber: null, notes: "private", recordedBy: { name: "Accountant" }, createdAt: new Date() }], audits: [{ action: "APPROVE", fromStatus: "PENDING_APPROVAL", toStatus: "APPROVED", detailsJson: '{"reason":"private"}', actorName: "Director", createdAt: new Date() }] }; const safe = serializeExpense(row, false) as any; expect(safe).not.toHaveProperty("transactionReference"); expect(safe).not.toHaveProperty("notes"); expect(safe).not.toHaveProperty("approvedBy"); expect(safe.payments[0]).not.toHaveProperty("transactionReference"); expect(safe.payments[0]).not.toHaveProperty("recordedBy"); expect(safe.audits[0]).not.toHaveProperty("actorName"); expect(safe.audits[0]).not.toHaveProperty("details"); });
  it("adds all requested permissions", () => { for (const permission of ["VIEW_VENDORS", "MANAGE_VENDORS", "VIEW_EXPENSES", "MANAGE_EXPENSES", "APPROVE_EXPENSES", "MARK_EXPENSE_PAID", "CANCEL_EXPENSES", "VIEW_EXPENSE_REPORTS", "EXPORT_EXPENSE_REPORTS"]) expect(PERMISSIONS).toContain(permission); });
  it("gives leadership/admin the chosen defaults", () => { for (const role of ["SUPER_ADMIN", "DIRECTOR", "ADMIN"] as const) expect(can(role, "APPROVE_EXPENSES")).toBe(true); expect(can("PRINCIPAL", "VIEW_EXPENSES")).toBe(true); expect(can("PRINCIPAL", "MANAGE_EXPENSES")).toBe(false); });
  it("scopes Accountant without approval or cancellation", () => { expect(can("ACCOUNTANT", "MANAGE_VENDORS")).toBe(true); expect(can("ACCOUNTANT", "MANAGE_EXPENSES")).toBe(true); expect(can("ACCOUNTANT", "MARK_EXPENSE_PAID")).toBe(true); expect(can("ACCOUNTANT", "APPROVE_EXPENSES")).toBe(false); expect(can("ACCOUNTANT", "CANCEL_EXPENSES")).toBe(false); });
  it("keeps Viewer read-only and blocks Parent/Teacher", () => { expect(can("VIEWER", "VIEW_EXPENSES")).toBe(true); expect(can("VIEWER", "VIEW_EXPENSE_REPORTS")).toBe(true); expect(can("VIEWER", "EXPORT_EXPENSE_REPORTS")).toBe(false); for (const role of ["PARENT", "TEACHER"] as const) { expect(can(role, "VIEW_EXPENSES")).toBe(false); expect(can(role, "VIEW_VENDORS")).toBe(false); } });
  it("guards all expense and vendor pages server-side", () => { const sources: Record<string, string> = { "app/vendors/page.tsx": "VIEW_VENDORS", "app/vendors/new/page.tsx": "MANAGE_VENDORS", "app/expenses/page.tsx": "VIEW_EXPENSES", "app/expenses/new/page.tsx": "MANAGE_EXPENSES", "app/expenses/reports/page.tsx": "VIEW_EXPENSE_REPORTS" }; for (const [file, permission] of Object.entries(sources)) expect(readFileSync(file, "utf8")).toContain(`requirePermission("${permission}")`); });
  it("guards direct APIs and separates action permissions", () => { expect(readFileSync("app/api/vendors/route.ts", "utf8")).toContain('requireApiPermission("VIEW_VENDORS")'); expect(readFileSync("app/api/vendors/route.ts", "utf8")).toContain('requireApiPermission("MANAGE_VENDORS")'); const workflow = readFileSync("app/api/expenses/[id]/workflow/route.ts", "utf8"); for (const permission of ["MANAGE_EXPENSES", "APPROVE_EXPENSES", "MARK_EXPENSE_PAID", "CANCEL_EXPENSES"]) expect(workflow).toContain(permission); });
  it("never merges expenses into student payments", () => { const schema = readFileSync("prisma/schema.prisma", "utf8"); expect(schema).toContain("model ExpenseRecord"); expect(schema).toContain("model ExpensePayment"); const migration = readFileSync("prisma/migrations/20260715_expense_vendor_foundation/migration.sql", "utf8"); expect(migration).not.toMatch(/ALTER TABLE "Payment"/); });
  it("makes approved/paid editing conditional on draft and prevents vendor hard delete", () => { expect(readFileSync("app/api/expenses/[id]/route.ts", "utf8")).toContain('approvalStatus: "DRAFT", paymentStatus: "UNPAID"'); expect(readFileSync("app/api/vendors/[id]/route.ts", "utf8")).toContain("cannot be hard deleted"); });
  it("enforces active masters and restricted expense payloads in direct APIs", () => { for (const file of ["app/api/expenses/route.ts", "app/api/expenses/[id]/route.ts"]) { const source = readFileSync(file, "utf8"); expect(source).toContain("validateActiveExpenseMasters"); expect(source).toContain("serializeExpense(row, sensitive)"); } const detail = readFileSync("app/expenses/[id]/page.tsx", "utf8"); expect(detail).toContain("sensitive && expense ? <ExpenseForm"); expect(detail).toContain(': "Restricted"'); });
  it("keeps rejection and cancellation reason inputs independent", () => { const source = readFileSync("components/expense-form.tsx", "utf8"); expect(source).toContain("rejectionReason, setRejectionReason"); expect(source).toContain("cancellationReason, setCancellationReason"); expect(source).toContain("reason: rejectionReason"); expect(source).toContain("reason: cancellationReason"); });
  it("shows exact paise on expense details and preserved payment rows", () => { const source = readFileSync("app/expenses/[id]/page.tsx", "utf8"); expect(source).toContain('import { displayDate, moneyExact, schoolDateKey }'); expect(source.match(/moneyExact\(Number\(/g)).toHaveLength(5); expect(source).not.toContain("money(Number("); });
});
