import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { archiveHomework, cancelHomework, correctPublishedHomework, newHomeworkAssignmentNumber, normalizeAssignmentNumber, publishHomework, safeResourceLink, updateHomeworkDraft, validateHomeworkInput } from "../lib/homework";
import { homeworkDueGroup, homeworkReportCsv, homeworkReportFilename } from "../lib/homework-reports";
import { RECOMMENDED_ROLE_PERMISSIONS } from "../lib/permissions";
import { homeworkError } from "../lib/homework-api";

const input = { academicYear: "2026-27", title: "QA Homework", instructions: "Complete exercises 1 to 5.", className: "1", section: "A", subjectName: "Mathematics", assignedDate: "2026-07-16", dueDate: "2026-07-17", priority: "NORMAL", resourceLink: "https://example.com/resource", publicNotes: "Bring the notebook.", teacherNotes: "Internal note" };

function workflowFixture(status = "DRAFT") {
  const row: any = { id: "h1", assignmentNumber: "HW-20260716-ABC123", ...validateHomeworkInput(input), status, createdAt: new Date("2026-07-16T00:00:00Z"), updatedAt: new Date("2026-07-16T01:00:00Z"), publishedAt: status === "PUBLISHED" ? new Date("2026-07-16T02:00:00Z") : null, title: "Old title", instructions: "Old public instructions", publicNotes: "Old public note", resourceLink: "https://example.com/old" };
  const events: any[] = [];
  const tx: any = {
    homeworkAssignment: {
      findUnique: async () => row,
      findUniqueOrThrow: async () => row,
      updateMany: async ({ where, data }: any) => { if (where.status !== row.status || (where.updatedAt && where.updatedAt.getTime() !== row.updatedAt.getTime())) return { count: 0 }; Object.assign(row, data); return { count: 1 }; }
    },
    homeworkAssignmentEvent: { create: async ({ data }: any) => { events.push(data); return data; } }
  };
  return { row, events, prisma: { $transaction: async (callback: any) => callback(tx) } as never };
}

describe("homework assignment validation and workflow", () => {
  it("normalizes human assignment numbers and generates unique India-local numbers", () => { expect(normalizeAssignmentNumber(" hw 2026-001 ")).toBe("HW-2026-001"); expect(newHomeworkAssignmentNumber(new Date("2026-07-15T20:00:00Z"))).toMatch(/^HW-20260716-[A-F0-9]{6}$/); });
  it("validates India-local dates and rejects due dates before assigned dates", () => { expect(validateHomeworkInput(input).dueDate?.toISOString()).toBe("2026-07-17T00:00:00.000Z"); expect(() => validateHomeworkInput({ ...input, dueDate: "2026-07-15" })).toThrow(/cannot be before/); expect(() => validateHomeworkInput({ ...input, assignedDate: "2026-02-31" })).toThrow(/invalid/); });
  it("accepts only safe HTTP or HTTPS resource links", () => { expect(safeResourceLink("https://example.com/a")).toBe("https://example.com/a"); expect(() => safeResourceLink("javascript:alert(1)")).toThrow(/safe HTTP/); expect(() => safeResourceLink("file:///C:/secret.txt")).toThrow(/safe HTTP/); expect(() => safeResourceLink("https://user:pass@example.com")).toThrow(/credentials/); });
  it("rejects HTML/script-shaped and control-character content", () => { expect(() => validateHomeworkInput({ ...input, instructions: "<script>alert(1)</script>" })).toThrow(/plain text/); expect(() => validateHomeworkInput({ ...input, title: "Bad\u0000Title" })).toThrow(/plain text/); });
  it("prevents draft update after publication", async () => { const f = workflowFixture("PUBLISHED"); await expect(updateHomeworkDraft(f.prisma, f.row.assignmentNumber, validateHomeworkInput(input), f.row.updatedAt, "u1")).rejects.toThrow(/Only draft/); });
  it("publishes once with compare-and-set and no duplicate event", async () => { const f = workflowFixture(); await publishHomework(f.prisma, f.row.assignmentNumber, f.row.updatedAt, "u1"); await publishHomework(f.prisma, f.row.assignmentNumber, new Date(0), "u1"); expect(f.row.status).toBe("PUBLISHED"); expect(f.events.filter((event) => event.eventType === "PUBLISHED")).toHaveLength(1); });
  it("preserves the previous public snapshot when correcting", async () => { const f = workflowFixture("PUBLISHED"); await correctPublishedHomework(f.prisma, f.row.assignmentNumber, validateHomeworkInput(input), "Typo in exercise number", f.row.updatedAt, "u1"); expect(f.events[0]).toMatchObject({ eventType: "CORRECTED", titleSnapshot: "Old title", instructionsSnapshot: "Old public instructions", reason: "Typo in exercise number" }); expect(f.row.status).toBe("PUBLISHED"); });
  it("blocks moving a published assignment to another audience", async () => { const f = workflowFixture("PUBLISHED"); await expect(correctPublishedHomework(f.prisma, f.row.assignmentNumber, validateHomeworkInput({ ...input, section: "B" }), "Move", f.row.updatedAt, "u1")).rejects.toThrow(/cannot be moved/); });
  it("requires cancellation reason and keeps the row", async () => { const f = workflowFixture("PUBLISHED"); await expect(cancelHomework(f.prisma, f.row.assignmentNumber, "", f.row.updatedAt, "u1")).rejects.toThrow(/required/); await cancelHomework(f.prisma, f.row.assignmentNumber, "School closed", f.row.updatedAt, "u1"); expect(f.row).toMatchObject({ status: "CANCELLED", cancellationReason: "School closed" }); expect(f.events[0].eventType).toBe("CANCELLED"); });
  it("archives published homework without deletion", async () => { const f = workflowFixture("PUBLISHED"); await archiveHomework(f.prisma, f.row.assignmentNumber, f.row.updatedAt, "u1"); expect(f.row.status).toBe("ARCHIVED"); expect(f.events[0].eventType).toBe("ARCHIVED"); });
  it("classifies due today, upcoming, overdue, and no-due rows", () => { const now = new Date("2026-07-16T10:00:00Z"); expect(homeworkDueGroup({ dueDate: new Date("2026-07-16"), status: "PUBLISHED" }, now)).toBe("DUE_TODAY"); expect(homeworkDueGroup({ dueDate: new Date("2026-07-17"), status: "PUBLISHED" }, now)).toBe("UPCOMING"); expect(homeworkDueGroup({ dueDate: new Date("2026-07-15"), status: "PUBLISHED" }, now)).toBe("OVERDUE"); expect(homeworkDueGroup({ dueDate: null, status: "PUBLISHED" }, now)).toBe("NO_DUE_DATE"); });
  it("produces formula-safe CSV and India-local filenames", () => { const csv = homeworkReportCsv([{ assignmentNumber: "=CMD", academicYear: "2026-27", className: "1", section: "A", subjectName: "Math", title: "+Title", assignedDate: new Date("2026-07-16"), dueDate: null, priority: "NORMAL", status: "PUBLISHED", createdBy: { name: "@Actor" } }]); expect(csv).toContain("'=CMD"); expect(csv).toContain("'+Title"); expect(csv).toContain("'@Actor"); expect(homeworkReportFilename(new Date("2026-07-15T20:00:00Z"))).toBe("homework-report-2026-07-16.csv"); });
  it("applies recommended role defaults", () => { for (const permission of ["VIEW_HOMEWORK", "MANAGE_HOMEWORK", "PUBLISH_HOMEWORK", "VIEW_HOMEWORK_REPORTS"] as const) expect(RECOMMENDED_ROLE_PERMISSIONS.TEACHER.has(permission)).toBe(true); expect(RECOMMENDED_ROLE_PERMISSIONS.TEACHER.has("ARCHIVE_HOMEWORK")).toBe(false); expect(RECOMMENDED_ROLE_PERMISSIONS.ACCOUNTANT.has("VIEW_HOMEWORK")).toBe(false); expect(RECOMMENDED_ROLE_PERMISSIONS.VIEWER.has("EXPORT_HOMEWORK_REPORTS")).toBe(false); expect(RECOMMENDED_ROLE_PERMISSIONS.PARENT.has("VIEW_OWN_HOMEWORK_PORTAL")).toBe(true); });
  it("has no hard-delete or native-dialog homework implementation", () => { const helper = readFileSync("lib/homework.ts", "utf8"), editor = readFileSync("components/homework-editor.tsx", "utf8"), css = readFileSync("app/globals.css", "utf8"); expect(helper).not.toContain("homeworkAssignment.delete"); expect(helper).not.toContain("homeworkAssignmentEvent.update"); expect(helper).not.toContain("homeworkAssignmentEvent.delete"); expect(editor).not.toMatch(/window\.(alert|confirm|prompt)/); expect(editor).toContain('role="dialog"'); expect(editor).toContain('aria-modal="true"'); expect(css).toMatch(/\.homework-editor-page summary[\s\S]*?min-height: 44px/); expect(css).toMatch(/\.top-actions select,[\s\S]*?\.user-menu summary \{ min-height: 44px; \}/); });
  it("returns a friendly conflict for duplicate assignment numbers", () => { expect(homeworkError({ code: "P2002" })).toEqual({ error: "Assignment number already exists. Use a different assignment number.", status: 409 }); });
});
