import { describe, expect, it } from "vitest";
import { homeworkScopeWhere, homeworkVisibleWhere, requireHomeworkTarget, resolveHomeworkScope } from "../lib/homework-scope";

const assignment = { academicYear: "2026-27", subjectId: "sub-1", classSection: { className: "1", section: "A", isActive: true }, subject: { name: "Mathematics", isActive: true } };
function client(staff: any) { return { staffMember: { findUnique: async () => staff } } as never; }

describe("homework Teacher scope", () => {
  it("resolves exact StaffMember timetable assignment scope", async () => { const scope = await resolveHomeworkScope(client({ status: "ACTIVE", fullName: "Teacher One", displayName: null, timetableTeacher: { isActive: true, assignments: [assignment] } }), { id: "u", role: "TEACHER" }, "2026-27"); expect(scope.scopes).toEqual([{ academicYear: "2026-27", className: "1", section: "A", subjectName: "Mathematics", timetableSubjectId: "sub-1" }]); });
  it("blocks class, section, subject, and year payload tampering", async () => { const scope = await resolveHomeworkScope(client({ status: "ACTIVE", fullName: "Teacher One", timetableTeacher: { isActive: true, assignments: [assignment] } }), { id: "u", role: "TEACHER" }); for (const target of [{ academicYear: "2026-27", className: "2", section: "A", subjectName: "Mathematics" }, { academicYear: "2026-27", className: "1", section: "B", subjectName: "Mathematics" }, { academicYear: "2026-27", className: "1", section: "A", subjectName: "Science" }, { academicYear: "2027-28", className: "1", section: "A", subjectName: "Mathematics" }]) expect(() => requireHomeworkTarget(scope, target)).toThrow(/outside|No authorised/); });
  it("does not grant broad access for incomplete timetable links", async () => { const scope = await resolveHomeworkScope(client({ status: "ACTIVE", fullName: "Teacher One", timetableTeacher: null }), { id: "u", role: "TEACHER" }); expect(scope.broad).toBe(false); expect(scope.scopes).toHaveLength(0); expect(homeworkScopeWhere(scope)).toMatchObject({ assignmentNumber: "__NO_AUTHORISED_HOMEWORK_SCOPE__" }); });
  it("returns a friendly state for an unlinked Teacher", async () => { const scope = await resolveHomeworkScope(client(null), { id: "u", role: "TEACHER" }); expect(scope.reason).toMatch(/No active StaffMember/); });
  it("allows explicit leadership permission paths to use broad scope", async () => { const scope = await resolveHomeworkScope(client(null), { id: "u", role: "PRINCIPAL" }); expect(scope).toMatchObject({ broad: true, reason: null }); });
  it("hides another Teacher's never-published drafts while retaining published scope visibility", async () => { const scope = await resolveHomeworkScope(client({ status: "ACTIVE", fullName: "Teacher One", timetableTeacher: { isActive: true, assignments: [assignment] } }), { id: "teacher-1", role: "TEACHER" }); expect(homeworkVisibleWhere(scope, { id: "teacher-1", role: "TEACHER" })).toMatchObject({ AND: [homeworkScopeWhere(scope), { OR: [{ createdByUserId: "teacher-1" }, { publishedAt: { not: null } }] }] }); expect(homeworkVisibleWhere(scope, { id: "principal", role: "PRINCIPAL" })).toEqual(homeworkScopeWhere(scope)); });
});
