import { describe, expect, it } from "vitest";
import { getParentHomeworkData, getParentHomeworkDetail, HomeworkPortalAccessError } from "../lib/homework-portals";

const rows = [
  { assignmentNumber: "HW-CLASS", academicYear: "2026-27", className: "1", section: null, subjectName: "Math", title: "Class wide", instructions: "All sections", assignedDate: new Date("2026-07-16"), dueDate: new Date("2026-07-16"), priority: "NORMAL", publicNotes: null, resourceLink: null, status: "PUBLISHED", publishedAt: new Date(), teacherNotes: "secret", createdByUserId: "raw" },
  { assignmentNumber: "HW-A", academicYear: "2026-27", className: "1", section: "A", subjectName: "English", title: "Section A", instructions: "A only", assignedDate: new Date("2026-07-16"), dueDate: new Date("2026-07-17"), priority: "IMPORTANT", publicNotes: "Public", resourceLink: "https://example.com/", status: "PUBLISHED", publishedAt: new Date() },
  { assignmentNumber: "HW-B", academicYear: "2026-27", className: "1", section: "B", subjectName: "English", title: "Section B", instructions: "B only", assignedDate: new Date("2026-07-16"), dueDate: null, priority: "NORMAL", publicNotes: null, resourceLink: null, status: "PUBLISHED", publishedAt: new Date() },
  { assignmentNumber: "HW-DRAFT", academicYear: "2026-27", className: "1", section: "A", subjectName: "Math", title: "Draft", instructions: "Hidden", assignedDate: new Date(), dueDate: null, priority: "NORMAL", publicNotes: null, resourceLink: null, status: "DRAFT", publishedAt: null }
  ,{ assignmentNumber: "HW-CANCELLED-DRAFT", academicYear: "2026-27", className: "1", section: "A", subjectName: "Math", title: "Never published cancellation", instructions: "Internal draft", assignedDate: new Date(), dueDate: null, priority: "NORMAL", publicNotes: null, resourceLink: null, status: "CANCELLED", publishedAt: null }
  ,{ assignmentNumber: "HW-ARCHIVED-DRAFT", academicYear: "2026-27", className: "1", section: "A", subjectName: "Math", title: "Never published archive", instructions: "Internal draft", assignedDate: new Date(), dueDate: null, priority: "NORMAL", publicNotes: null, resourceLink: null, status: "ARCHIVED", publishedAt: null }
];
function fake() { const client: any = { user: { findUnique: async () => ({ role: "PARENT", guardianId: "g1" }) }, studentGuardian: { findMany: async () => [{ student: { studentName: "Child A", academicYearEnrollments: [{ className: "1", section: "A" }] } }, { student: { studentName: "Child B", academicYearEnrollments: [{ className: "1", section: "B" }] } }] }, homeworkAssignment: { findMany: async ({ where }: any) => { const selectedSection = where.AND[0].OR[1].section; return rows.filter((row) => row.academicYear === where.academicYear && row.className === where.className && (row.section === null || row.section === selectedSection) && where.status.in.includes(row.status) && (!where.publishedAt || row.publishedAt)); }, findFirst: async ({ where }: any) => rows.find((row) => row.assignmentNumber === where.assignmentNumber && row.academicYear === where.academicYear && row.className === where.className && (row.section === null || row.section === where.OR[1].section) && where.status.in.includes(row.status) && (!where.publishedAt || row.publishedAt)) ?? null } }; return client; }

describe("Parent homework portal", () => {
  it("shows class-wide plus only the selected child section", async () => { const data = await getParentHomeworkData(fake(), "u1", "2026-27", 0); expect(data.assignments.map((row) => row.title)).toEqual(["Class wide", "Section A"]); });
  it("supports sibling switching without admission-number input", async () => { const data = await getParentHomeworkData(fake(), "u1", "2026-27", 1); expect(data.selectedChild?.studentName).toBe("Child B"); expect(data.assignments.map((row) => row.title)).toEqual(["Class wide", "Section B"]); });
  it("blocks an unrelated child index", async () => { await expect(getParentHomeworkData(fake(), "u1", "2026-27", 4)).rejects.toBeInstanceOf(HomeworkPortalAccessError); });
  it("returns only Parent-safe fields and no internal notes, actor IDs, or assignment identifiers", async () => { const data = await getParentHomeworkData(fake(), "u1", "2026-27", 0); const json = JSON.stringify(data.assignments); expect(json).not.toContain("teacherNotes"); expect(json).not.toContain("createdByUserId"); expect(json).not.toContain("assignmentNumber"); expect(json).not.toContain("secret"); expect(Object.keys(data.assignments[0]).sort()).toEqual(["assignedDate","dueDate","instructions","priority","publicNotes","resourceLink","status","subjectName","title"].sort()); });
  it("requires a linked Parent account", async () => { const client: any = fake(); client.user.findUnique = async () => ({ role: "PARENT", guardianId: null }); await expect(getParentHomeworkData(client, "u1", "2026-27", 0)).rejects.toThrow(/linked Parent/); });
  it("never exposes cancelled or archived homework that was never published", async () => { const history = await getParentHomeworkData(fake(), "u1", "2026-27", 0, true); expect(history.assignments.map((row) => row.title)).not.toEqual(expect.arrayContaining(["Never published cancellation", "Never published archive"])); await expect(getParentHomeworkDetail(fake(), "u1", "2026-27", 0, "HW-CANCELLED-DRAFT")).rejects.toMatchObject({ status: 404 }); await expect(getParentHomeworkDetail(fake(), "u1", "2026-27", 0, "HW-ARCHIVED-DRAFT")).rejects.toMatchObject({ status: 404 }); });
});
