import { describe, expect, it } from "vitest";
import { createBackupDocument } from "@/lib/backup";
import { parseAndValidateBackup } from "@/lib/restore";

const at="2026-07-16T00:00:00.000Z";
function fixture(){return createBackupDocument({generatedAt:new Date(at),generatedBy:"QA",students:[],feeStructures:[],payments:[],paymentAudits:[],users:[{id:"u",username:"qa",passwordHash:"secret"}],libraryTitles:[{id:"t",titleCode:"T-1",title:"Title",authors:"Author",status:"ACTIVE",createdAt:at,updatedAt:at}],libraryCopies:[{id:"c",titleId:"t",accessionNumber:"ACC-1",barcodeValue:"BC-1",acquisitionType:"OTHER",condition:"GOOD",status:"AVAILABLE",createdAt:at,updatedAt:at}],libraryCopyEvents:[{id:"ce",copyId:"c",eventType:"ACCESSIONED",eventDate:at,newStatus:"AVAILABLE",createdAt:at}],libraryStockVerificationSessions:[{id:"s",sessionNumber:"LSV-1",title:"Annual",academicYear:"2026-27",verificationDate:at,scopeType:"ALL_ACTIVE_COPIES",status:"LOCKED",expectedCopyCount:1,verifiedCopyCount:1,presentCount:1,issuedOffsiteCount:0,knownRepairCount:0,missingCount:0,misShelvedCount:0,damagedCount:0,unexpectedCount:0,unresolvedCount:0,lockedAt:at,createdAt:at,updatedAt:at}],libraryStockVerificationRecords:[{id:"r",sessionId:"s",copyId:"c",expectedAccessionNumberSnapshot:"ACC-1",expectedBarcodeSnapshot:"BC-1",expectedTitleSnapshot:"T-1 - Title",expectedShelfCodeSnapshot:"A",expectedStatusSnapshot:"AVAILABLE",expectedConditionSnapshot:"GOOD",observationStatus:"PRESENT",resolutionStatus:"NOT_REQUIRED",createdAt:at,updatedAt:at}],libraryStockVerificationScanEvents:[{id:"se",sessionId:"s",recordId:"r",normalizedInput:"BC-1",scanMethod:"BARCODE",resultType:"MATCHED_EXPECTED",scannedAt:at,createdAt:at}],libraryStockVerificationEvents:[{id:"we",sessionId:"s",eventType:"LOCKED",eventDate:at,createdAt:at}]});}

describe("Library stock-verification backup v22",()=>{
  it("includes all four arrays and excludes password hashes",()=>{const b=fixture();expect(b.metadata.backupVersion).toBe(42);for(const key of ["libraryStockVerificationSessions","libraryStockVerificationRecords","libraryStockVerificationScanEvents","libraryStockVerificationEvents"] as const)expect(b[key]).toHaveLength(1);expect(JSON.stringify(b)).not.toContain("passwordHash");expect(JSON.stringify(b)).not.toContain("secret");});
  it("preserves immutable snapshot and locked workflow state",()=>{const b=parseAndValidateBackup(fixture());expect(b.libraryStockVerificationRecords[0]).toMatchObject({expectedAccessionNumberSnapshot:"ACC-1",expectedStatusSnapshot:"AVAILABLE"});expect(b.libraryStockVerificationSessions[0]).toMatchObject({status:"LOCKED",lockedAt:at});});
  it("remains compatible with v21 backups missing stock arrays",()=>{const b:any=fixture();b.metadata.backupVersion=21;for(const key of ["libraryStockVerificationSessions","libraryStockVerificationRecords","libraryStockVerificationScanEvents","libraryStockVerificationEvents"]){delete b[key];delete b.metadata.counts[key];}const parsed=parseAndValidateBackup(b);expect(parsed.libraryStockVerificationSessions).toEqual([]);expect(parsed.libraryStockVerificationRecords).toEqual([]);});
  it("rejects duplicate normalized session numbers",()=>{const b:any=fixture();b.libraryStockVerificationSessions.push({...b.libraryStockVerificationSessions[0],id:"s2"});b.metadata.counts.libraryStockVerificationSessions=2;expect(()=>parseAndValidateBackup(b)).toThrow(/duplicates a stock session identity/);});
  it("rejects duplicate session plus copy records",()=>{const b:any=fixture();b.libraryStockVerificationRecords.push({...b.libraryStockVerificationRecords[0],id:"r2"});b.metadata.counts.libraryStockVerificationRecords=2;expect(()=>parseAndValidateBackup(b)).toThrow(/session\+copy/);});
  it("rejects record links to an unrelated copy",()=>{const b:any=fixture();b.libraryStockVerificationRecords[0].copyId="unrelated";expect(()=>parseAndValidateBackup(b)).toThrow(/exact backup session and copy/);});
  it("rejects scan links to an unrelated record",()=>{const b:any=fixture();b.libraryStockVerificationScanEvents[0].recordId="unrelated";expect(()=>parseAndValidateBackup(b)).toThrow(/does not match a backup stock record/);});
  it("rejects locked sessions without lockedAt",()=>{const b:any=fixture();delete b.libraryStockVerificationSessions[0].lockedAt;expect(()=>parseAndValidateBackup(b)).toThrow(/lockedAt is required/);});
  it("rejects APPLIED without exactly one copy event link",()=>{const b:any=fixture();b.libraryStockVerificationRecords[0].resolutionStatus="APPLIED";expect(()=>parseAndValidateBackup(b)).toThrow(/appliedCopyEventId is required/);});
  it("accepts a linked applied append-only copy event exactly once",()=>{const b:any=fixture();b.libraryStockVerificationRecords[0].resolutionStatus="APPLIED";b.libraryStockVerificationRecords[0].appliedCopyEventId="ce";expect(parseAndValidateBackup(b).libraryStockVerificationRecords[0].appliedCopyEventId).toBe("ce");});
  it("rejects an applied event that belongs to a different Library copy",()=>{const b:any=fixture();b.libraryCopies.push({...b.libraryCopies[0],id:"c2",accessionNumber:"ACC-2",barcodeValue:"BC-2"});b.libraryCopyEvents.push({...b.libraryCopyEvents[0],id:"ce2",copyId:"c2"});b.metadata.counts.libraryCopies=2;b.metadata.counts.libraryCopyEvents=2;b.libraryStockVerificationRecords[0].resolutionStatus="APPLIED";b.libraryStockVerificationRecords[0].appliedCopyEventId="ce2";expect(()=>parseAndValidateBackup(b)).toThrow(/same copy/);});
});
