import { describe, expect, it } from "vitest";
import { createBackupDocument } from "@/lib/backup";
import { parseAndValidateBackup } from "@/lib/restore";

function fixture() { return createBackupDocument({ generatedAt: new Date("2026-07-15T12:00:00Z"), generatedBy: "QA", students: [], feeStructures: [], payments: [], paymentAudits: [], users: [{ id: "u", username: "qa", passwordHash: "must-not-export" }], libraryTitles: [{ id: "t1", titleCode: "LIB-T1", title: "Title", authors: "Author", isbn: "9788112345678", status: "ACTIVE", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }], libraryCopies: [{ id: "c1", titleId: "t1", accessionNumber: "LIB-2026-00001", barcodeValue: "BC1", acquisitionDate: "2026-07-15T00:00:00.000Z", acquisitionType: "PURCHASED", acquisitionCost: "100.00", condition: "GOOD", status: "WITHDRAWN", shelfCode: "A1", withdrawnDate: "2026-07-15T00:00:00.000Z", withdrawalReason: "Damaged beyond repair", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }], libraryCopyEvents: [{ id: "e1", copyId: "c1", eventType: "ACCESSIONED", eventDate: "2026-07-15T00:00:00.000Z", newStatus: "AVAILABLE", newCondition: "GOOD", newShelfCode: "A1", createdAt: "2026-07-15T00:00:00.000Z" }, { id: "e2", copyId: "c1", eventType: "WITHDRAWN", eventDate: "2026-07-15T01:00:00.000Z", previousStatus: "AVAILABLE", newStatus: "WITHDRAWN", reason: "Damaged beyond repair", createdAt: "2026-07-15T01:00:00.000Z" }] }); }

describe("library backup and restore v19", () => {
  it("includes titles, copies, append-only events, and no password hashes", () => { const backup = fixture(); expect(backup.metadata.backupVersion).toBe(44); expect(backup.libraryTitles).toHaveLength(1); expect(backup.libraryCopies[0]).toMatchObject({ status: "WITHDRAWN", accessionNumber: "LIB-2026-00001" }); expect(backup.libraryCopyEvents).toHaveLength(2); expect(JSON.stringify(backup)).not.toContain("passwordHash"); expect(JSON.stringify(backup)).not.toContain("must-not-export"); });
  it("validates library links and historical withdrawn records", () => { const parsed = parseAndValidateBackup(fixture()); expect(parsed.libraryCopies[0].titleId).toBe("t1"); expect(parsed.libraryCopyEvents.map((e) => e.eventType)).toEqual(["ACCESSIONED", "WITHDRAWN"]); });
  it("keeps version 18 backups compatible when library arrays are absent", () => { const old: any = fixture(); old.metadata.backupVersion = 18; for (const key of ["libraryTitles", "libraryCopies", "libraryCopyEvents"]) { delete old[key]; delete old.metadata.counts[key]; } const parsed = parseAndValidateBackup(old); expect(parsed.libraryTitles).toEqual([]); expect(parsed.libraryCopies).toEqual([]); expect(parsed.libraryCopyEvents).toEqual([]); });
  it("blocks duplicate accession and barcode identities", () => { const backup: any = fixture(); backup.libraryCopies.push({ ...backup.libraryCopies[0], id: "c2", titleId: "t1" }); backup.libraryCopyEvents.push({ ...backup.libraryCopyEvents[0], id: "e3", copyId: "c2" }); backup.metadata.counts.libraryCopies = 2; backup.metadata.counts.libraryCopyEvents = 3; expect(() => parseAndValidateBackup(backup)).toThrow(/duplicates a copy identity or accession number|barcodeValue is duplicated/); });
  it("rejects non-canonical title, accession, and barcode identities before restore", () => { const title: any = fixture(); title.libraryTitles[0].titleCode = "lib t1"; expect(() => parseAndValidateBackup(title)).toThrow("normalized"); const accession: any = fixture(); accession.libraryCopies[0].accessionNumber = "lib 2026 00001"; expect(() => parseAndValidateBackup(accession)).toThrow("normalized"); const barcode: any = fixture(); barcode.libraryCopies[0].barcodeValue = " bc1 "; expect(() => parseAndValidateBackup(barcode)).toThrow("normalized"); });
  it("rejects a library Vendor/Expense pair that belongs to different Vendors", () => { const backup: any = fixture(); backup.vendors = [{ id: "v1", vendorCode: "V001", name: "One", status: "ACTIVE", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }, { id: "v2", vendorCode: "V002", name: "Two", status: "ACTIVE", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }]; backup.expenseCategories = [{ id: "cat", name: "General", code: "GEN", status: "ACTIVE", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }]; backup.expenseDepartments = [{ id: "dep", name: "General", code: "GEN", status: "ACTIVE", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }]; backup.expenseRecords = [{ id: "exp", expenseNumber: "EXP-20260715-QA", expenseDate: "2026-07-15T00:00:00.000Z", academicYear: "2026-27", vendorId: "v2", categoryId: "cat", departmentId: "dep", description: "QA", grossAmount: "100", taxAmount: "0", deductionAmount: "0", netAmount: "100", paymentMethod: "CASH", paymentStatus: "UNPAID", approvalStatus: "APPROVED", createdAt: "2026-07-15T00:00:00.000Z", updatedAt: "2026-07-15T00:00:00.000Z" }]; backup.libraryCopies[0].vendorId = "v1"; backup.libraryCopies[0].expenseRecordId = "exp"; Object.assign(backup.metadata.counts, { vendors: 2, expenseCategories: 1, expenseDepartments: 1, expenseRecords: 1 }); expect(() => parseAndValidateBackup(backup)).toThrow("same Vendor"); });
  it("blocks copies and events whose exact parent IDs are unrelated", () => { const copyBroken: any = fixture(); copyBroken.libraryCopies[0].titleId = "unrelated"; expect(() => parseAndValidateBackup(copyBroken)).toThrow("does not match a backup LibraryTitle"); const eventBroken: any = fixture(); eventBroken.libraryCopyEvents[0].copyId = "unrelated"; expect(() => parseAndValidateBackup(eventBroken)).toThrow("does not match a backup LibraryCopy"); });
  it("requires every restored copy to retain an ACCESSIONED event", () => { const backup: any = fixture(); backup.libraryCopyEvents = backup.libraryCopyEvents.filter((e: any) => e.eventType !== "ACCESSIONED"); backup.metadata.counts.libraryCopyEvents = 1; expect(() => parseAndValidateBackup(backup)).toThrow("missing its ACCESSIONED event"); });
});
