import { describe, expect, it } from "vitest";
import { addCalendarDays, deriveOverdue, previewLibraryIssue } from "@/lib/library-circulation";
import { circulationReportCsv } from "@/lib/library-circulation-reports";
import { publicLibraryLoan, publicLibraryMember } from "@/lib/library-api";
import { effectiveMemberStatus, normalizeMemberCode, parseLibraryDate } from "@/lib/library-members";
import { resolveLibraryPolicy, validateLibraryPolicy } from "@/lib/library-policies";

describe("library membership and policy foundation", () => {
  it("normalizes member codes and rejects unsafe identities", () => { expect(normalizeMemberCode(" lib s 001 ")).toBe("LIB-S-001"); expect(() => normalizeMemberCode("x")).toThrow(/3-40/); });
  it("validates India-local calendar dates", () => { expect(parseLibraryDate("2026-07-15").toISOString()).toBe("2026-07-15T00:00:00.000Z"); expect(() => parseLibraryDate("2026-02-31")).toThrow(/valid calendar/); });
  it("calculates expired suspension eligibility without rewriting status", () => { const member = { status: "SUSPENDED", suspendedUntil: new Date("2026-07-14T00:00:00Z") }; expect(effectiveMemberStatus(member, new Date("2026-07-15T12:00:00Z"))).toBe("ACTIVE"); expect(member.status).toBe("SUSPENDED"); });
  it("validates positive limits, non-negative renewals and calendar-day periods", () => { const policy = validateLibraryPolicy({ policyCode: "stu-general", name: "Student", memberType: "STUDENT", maxActiveLoans: 2, loanPeriodDays: 14, maxRenewals: 1, renewalPeriodDays: 7, reservationLimit: 1, priority: 0 }); expect(policy).toMatchObject({ policyCode: "STU-GENERAL", loanPeriodDays: 14 }); expect(() => validateLibraryPolicy({ ...policy, maxActiveLoans: 0 })).toThrow(/maxActiveLoans/); expect(() => validateLibraryPolicy({ ...policy, staffType: "TEACHING" })).toThrow(/cannot have a staff type/); });
  it("resolves exact Student class before general policy", async () => { const client: any = { libraryMember: { findUnique: async () => ({ id: "m", memberType: "STUDENT", student: { className: "5", academicYearEnrollments: [{ className: "6" }] } }) }, libraryPolicy: { findMany: async () => [{ policyCode: "S6", className: "6", staffType: null, priority: 0 }, { policyCode: "SG", className: null, staffType: null, priority: 99 }] } }; expect((await resolveLibraryPolicy(client, "m")).policy.policyCode).toBe("S6"); });
  it("resolves exact Staff type before general policy", async () => { const client: any = { libraryMember: { findUnique: async () => ({ id: "m", memberType: "STAFF", staffMember: { staffType: "TEACHING", designation: "Teacher" } }) }, libraryPolicy: { findMany: async () => [{ policyCode: "ST", className: null, staffType: "TEACHING", priority: 0 }, { policyCode: "SG", className: null, staffType: null, priority: 99 }] } }; expect((await resolveLibraryPolicy(client, "m")).policy.policyCode).toBe("ST"); });
  it("blocks issue when policy is missing", async () => { const client: any = { libraryMember: { findUnique: async () => ({ id: "m", memberType: "STAFF", staffMember: { staffType: "TEACHING" } }) }, libraryPolicy: { findMany: async () => [] } }; await expect(resolveLibraryPolicy(client, "m")).rejects.toThrow(/No active STAFF/); });
});

describe("library circulation rules", () => {
  it("uses calendar-day due dates", () => { expect(addCalendarDays(new Date("2026-07-31T00:00:00Z"), 14).toISOString().slice(0, 10)).toBe("2026-08-14"); });
  it("derives overdue only for open issued loans", () => { expect(deriveOverdue({ status: "ISSUED", dueDate: new Date("2026-07-10") }, new Date("2026-07-15T12:00:00Z"))).toEqual({ overdue: true, overdueDays: 5 }); expect(deriveOverdue({ status: "RETURNED", dueDate: new Date("2026-07-10") }, new Date("2026-07-15"))).toEqual({ overdue: false, overdueDays: 0 }); });
  it("treats due today as current across the India-local midnight boundary", () => { const loan = { status: "ISSUED", dueDate: new Date("2026-07-14T00:00:00.000Z") }; expect(deriveOverdue(loan, new Date("2026-07-14T18:29:59.000Z"))).toEqual({ overdue: false, overdueDays: 0 }); expect(deriveOverdue(loan, new Date("2026-07-14T18:30:00.000Z"))).toEqual({ overdue: true, overdueDays: 1 }); expect(deriveOverdue({ ...loan, status: "CANCELLED" }, new Date("2026-07-15T00:00:00.000Z"))).toEqual({ overdue: false, overdueDays: 0 }); });
  function previewClient(overrides: any = {}) { const member = { id: "m1", memberType: "STUDENT", status: "ACTIVE", suspendedUntil: null, student: { status: "Active", deletedAt: null, className: "6", academicYearEnrollments: [{ className: "6" }] }, staffMember: null, _count: { loans: 0 } }; const copy = { id: "c1", titleId: "t1", accessionNumber: "A1", status: "AVAILABLE", condition: "GOOD", title: { title: "Book" }, loans: [] }; const policy = { policyCode: "S6", memberType: "STUDENT", className: "6", staffType: null, maxActiveLoans: 2, loanPeriodDays: 14, maxRenewals: 1, renewalPeriodDays: 7, reservationLimit: 1, priority: 0 }; return { libraryMember: { findUnique: async () => ({ ...member, ...overrides.member }) }, libraryCopy: { findUnique: async () => ({ ...copy, ...overrides.copy }) }, libraryPolicy: { findMany: async () => [policy] }, libraryReservation: { findMany: async () => overrides.queue ?? [] } } as any; }
  it("previews due date and policy snapshot inputs", async () => { const result = await previewLibraryIssue(previewClient(), "m1", "c1", "2026-07-15"); expect(result.dueDate.toISOString().slice(0, 10)).toBe("2026-07-29"); expect(result.policy.policyCode).toBe("S6"); });
  it("blocks inactive membership and linked inactive Student", async () => { await expect(previewLibraryIssue(previewClient({ member: { status: "INACTIVE" } }), "m1", "c1", "2026-07-15")).rejects.toThrow(/not currently eligible/); await expect(previewLibraryIssue(previewClient({ member: { student: { status: "Inactive", deletedAt: null, className: "6", academicYearEnrollments: [] } } }), "m1", "c1", "2026-07-15")).rejects.toThrow(/linked Student/); });
  it("blocks physical status conflicts and double issue", async () => { await expect(previewLibraryIssue(previewClient({ copy: { status: "MISSING" } }), "m1", "c1", "2026-07-15")).rejects.toThrow(/physical status/); await expect(previewLibraryIssue(previewClient({ copy: { loans: [{ id: "existing" }] } }), "m1", "c1", "2026-07-15")).rejects.toThrow(/active loan/); });
  it("enforces member loan limit", async () => { await expect(previewLibraryIssue(previewClient({ member: { _count: { loans: 2 } } }), "m1", "c1", "2026-07-15")).rejects.toThrow(/2-loan limit/); });
  it("enforces earliest reservation priority", async () => { await expect(previewLibraryIssue(previewClient({ queue: [{ id: "r", memberId: "other", reservationNumber: "RSV-1" }] }), "m1", "c1", "2026-07-15")).rejects.toThrow(/priority belongs/); const own = await previewLibraryIssue(previewClient({ queue: [{ id: "r", memberId: "m1", reservationNumber: "RSV-1" }] }), "m1", "c1", "2026-07-15"); expect(own.priorityReservation?.reservationNumber).toBe("RSV-1"); });
  it("makes CSV formula-safe and excludes finance fields", () => { const report: any = { range: { todayKey: "2026-07-15", dueCutoffKey: "2026-07-22", dueWithinDays: 7 }, loans: [{ loanNumber: "=CMD", borrower: "+Borrower", memberType: "STUDENT", classOrStaffType: "6", titleCode: "T", title: "Book", accessionNumber: "A", status: "ISSUED", issueDate: "2026-07-15", dueDate: "2026-07-29", returnedDate: "", renewCount: 0, overdue: false, overdueDays: 0 }], reservations: [], renewals: [], memberUsage: [], titleWise: [], copyAvailability: [] }; const csv = circulationReportCsv(report, "active-loans"); expect(csv).toContain("'=CMD"); expect(csv).toContain("'+Borrower"); expect(csv).not.toMatch(/fine|payment|charge/i); });
  it("exports due-soon separately from due-today and includes policy limit capacity", () => { const base = { borrower: "Member", memberType: "STUDENT", classOrStaffType: "6", titleCode: "T", title: "Book", accessionNumber: "A", status: "ISSUED", issueDate: "2026-07-01", returnedDate: "", renewCount: 0, overdue: false, overdueDays: 0 }; const report: any = { range: { todayKey: "2026-07-15", dueCutoffKey: "2026-07-22", dueWithinDays: 7 }, loans: [{ ...base, loanNumber: "TODAY", dueDate: "2026-07-15" }, { ...base, loanNumber: "SOON", dueDate: "2026-07-20" }, { ...base, loanNumber: "LATER", dueDate: "2026-07-23" }], reservations: [], renewals: [], memberUsage: [{ memberCode: "MEM-1", borrower: "Member", memberType: "STUDENT", status: "ACTIVE", policyCode: "STU-6", maxActiveLoans: 2, activeLoans: 1, remainingLoans: 1, waitingReservations: 0 }], titleWise: [], copyAvailability: [] }; const dueSoon = circulationReportCsv(report, "due-soon"); expect(dueSoon).toContain("SOON"); expect(dueSoon).not.toContain("TODAY"); expect(dueSoon).not.toContain("LATER"); const usage = circulationReportCsv(report, "member-limit-usage"); expect(usage).toContain("Maximum Active Loans"); expect(usage).toContain("STU-6"); });
  it("allowlists circulation payloads without raw IDs or private linked-person data", () => { const member: any = { id: "raw-member", memberCode: "MEM-1", memberType: "STUDENT", status: "ACTIVE", joinedDate: new Date("2026-07-15"), notes: "private note", suspensionReason: "private reason", student: { id: "raw-student", studentName: "Student", admissionNo: "A1", className: "6", section: "A", phone1: "999", address: "private", passwordHash: "secret" } }; const serializedMember = JSON.stringify(publicLibraryMember(member)); expect(serializedMember).not.toMatch(/raw-member|raw-student|private note|private reason|999|private|secret/); const serializedLoan = JSON.stringify(publicLibraryLoan({ id: "raw-loan", loanNumber: "LN-1", status: "ISSUED", issueDate: new Date("2026-07-15"), dueDate: new Date("2026-07-29"), returnedDate: null, renewCount: 0, policyCodeSnapshot: "STU-6", loanPeriodDaysSnapshot: 14, maxRenewalsSnapshot: 1, renewalPeriodDaysSnapshot: 7, issueConditionSnapshot: "GOOD", member, issuedByUserId: "raw-actor" })); expect(serializedLoan).not.toMatch(/raw-loan|raw-actor|passwordHash|address|phone1/); });
});
