import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { applyLibraryCopyImport, buildLibraryCopyImportPreview, buildLibraryTitleImportPreview, libraryImportTemplate } from "@/lib/library-import";
import { libraryReportCsv, libraryReportFilename, loadLibraryReports, serializeLibraryReportPayload } from "@/lib/library-reports";

function titleClient(existing: Record<string, any> = {}) { return { vendor: { findUnique: vi.fn(async ({ where }) => existing[`vendor:${where.vendorCode}`] ?? null) }, libraryTitle: { findUnique: vi.fn(async ({ where }) => existing[`code:${where.titleCode}`] ?? existing[`isbn:${where.isbn}`] ?? null) }, libraryCopy: { findUnique: vi.fn() }, expenseRecord: { findUnique: vi.fn() }, libraryCopyEvent: {} }; }

describe("library preview-first imports and non-circulation reports", () => {
  it("previews title rows without writing", async () => { const client = titleClient(); const preview = await buildLibraryTitleImportPreview(client as never, [{ titleCode: "L 1", title: "Title", authors: "Author", status: "ACTIVE" }]); expect(preview.counts).toMatchObject({ total: 1, ready: 1, errors: 0 }); expect((client.libraryTitle as any).create).toBeUndefined(); });
  it("blocks duplicate normalized title codes inside one file", async () => { const preview = await buildLibraryTitleImportPreview(titleClient() as never, [{ titleCode: "L 1", title: "One", authors: "A" }, { titleCode: "l-1", title: "Two", authors: "B" }]); expect(preview.rows[1].action).toBe("ERROR"); expect(preview.rows[1].errors.join(" ")).toContain("Duplicate normalized title code"); });
  it("does exact title-code matching only for copy imports", async () => { const client = { ...titleClient(), libraryTitle: { findUnique: vi.fn(async () => null) }, vendor: { findUnique: vi.fn(async () => null) }, expenseRecord: { findUnique: vi.fn(async () => null) }, libraryCopy: { findUnique: vi.fn(async () => null) } }; const preview = await buildLibraryCopyImportPreview(client as never, [{ accessionNumber: "A-1", titleCode: "Almost The Title", acquisitionType: "OTHER", condition: "GOOD", status: "AVAILABLE" }]); expect(preview.rows[0].action).toBe("ERROR"); expect(preview.rows[0].errors.join(" ")).toContain("Exact title code ALMOST-THE-TITLE was not found"); });
  it("blocks copy imports against an inactive exact title", async () => { const client = { ...titleClient(), libraryTitle: { findUnique: vi.fn(async () => ({ id: "t", status: "INACTIVE" })) }, vendor: { findUnique: vi.fn(async () => null) }, expenseRecord: { findUnique: vi.fn(async () => null) }, libraryCopy: { findUnique: vi.fn(async () => null) } }; const preview = await buildLibraryCopyImportPreview(client as never, [{ accessionNumber: "A-0", titleCode: "T-1", acquisitionType: "OTHER", condition: "GOOD", status: "AVAILABLE" }]); expect(preview.rows[0].action).toBe("ERROR"); expect(preview.rows[0].errors.join(" ")).toContain("inactive"); });
  it("skips an existing accession on rerun instead of duplicating or overwriting", async () => { const client = { ...titleClient(), libraryTitle: { findUnique: vi.fn(async () => ({ id: "t", status: "ACTIVE" })) }, vendor: { findUnique: vi.fn(async () => null) }, expenseRecord: { findUnique: vi.fn(async () => null) }, libraryCopy: { findUnique: vi.fn(async ({ where }) => where.accessionNumber ? { id: "c", barcodeValue: null } : null) } }; const preview = await buildLibraryCopyImportPreview(client as never, [{ accessionNumber: "A-1", titleCode: "T-1", acquisitionType: "OTHER", condition: "GOOD", status: "AVAILABLE" }]); expect(preview.rows[0].action).toBe("SKIP"); expect(preview.rows[0].warnings.join(" ")).toContain("never reused or overwritten"); });
  it("validates exact Vendor and Expense identity", async () => { const client = { ...titleClient(), libraryTitle: { findUnique: vi.fn(async () => ({ id: "t", status: "ACTIVE" })) }, vendor: { findUnique: vi.fn(async () => ({ id: "v1", status: "ACTIVE" })) }, expenseRecord: { findUnique: vi.fn(async () => ({ id: "e", vendorId: "v2" })) }, libraryCopy: { findUnique: vi.fn(async () => null) } }; const preview = await buildLibraryCopyImportPreview(client as never, [{ accessionNumber: "A-2", titleCode: "T-1", vendorCode: "V1", expenseNumber: "EXP-1", acquisitionType: "PURCHASED", condition: "GOOD", status: "AVAILABLE" }]); expect(preview.rows[0].errors.join(" ")).toContain("do not belong to the same Vendor"); });
  it("propagates an apply failure through the route transaction boundary", async () => { const client = { libraryTitle: { findUnique: vi.fn(async () => ({ id: "t", status: "ACTIVE" })) }, vendor: { findFirst: vi.fn() }, expenseRecord: { findUnique: vi.fn() }, libraryCopy: { create: vi.fn(async () => { throw new Error("simulated database failure"); }) }, libraryCopyEvent: { create: vi.fn() } }; const checked = { kind: "copies" as const, counts: { total: 1, ready: 1, skipped: 0, errors: 0, warnings: 0 }, rows: [{ rowNumber: 2, action: "CREATE" as const, normalized: { titleId: "t", accessionNumber: "A-9", acquisitionType: "OTHER", condition: "GOOD", status: "AVAILABLE" }, errors: [], warnings: [] }] }; await expect(applyLibraryCopyImport(client as never, checked, "u")).rejects.toThrow("simulated database failure"); expect(client.libraryCopyEvent.create).not.toHaveBeenCalled(); expect(readFileSync("app/api/library/import/[kind]/route.ts", "utf8")).toContain("prisma.$transaction"); });
  it("provides separate, formula-safe templates", () => { const titles = libraryImportTemplate("titles"), copies = libraryImportTemplate("copies"); expect(titles).toContain("titleCode"); expect(titles).not.toContain("accessionNumber"); expect(copies).toContain("accessionNumber"); expect(copies).toContain("expenseNumber"); expect(copies).not.toContain("issueDate"); });
  it("builds accurate catalog/accession summaries", async () => { const title = { titleCode: "T1", title: "=Formula title", authors: "Author", isbn: null, status: "ACTIVE", language: "English", subject: "Science", category: null, publisherName: "Pub", publisherVendor: null, copies: [{ id: "c", status: "AVAILABLE" }] }; const copy = { accessionNumber: "A1", title: { titleCode: "T1", title: "=Formula title", language: "English", subject: "Science", category: null, publisherName: "Pub" }, barcodeValue: null, acquisitionDate: null, acquisitionType: "DONATED", acquisitionCost: null, vendorId: null, vendor: null, expenseRecordId: null, expenseRecord: null, donorName: "Donor", invoiceNumberSnapshot: null, condition: "GOOD", status: "AVAILABLE", shelfCode: null, withdrawnDate: null, withdrawalReason: null }; const client = { libraryTitle: { findMany: vi.fn(async () => [title]) }, libraryCopy: { findMany: vi.fn(async () => [copy]) }, libraryCopyEvent: { findMany: vi.fn(async () => []) } }; const report = await loadLibraryReports(client as never); expect(report.summary).toMatchObject({ titles: 1, copies: 1, available: 1, withdrawn: 0, titleMetadataGaps: 1, copyMetadataGaps: 1 }); const csv = libraryReportCsv(report, "accession-register"); expect(csv).toContain("'=Formula title"); expect(csv).not.toContain("passwordHash"); expect(csv).not.toContain("transactionReference"); });
  it("masks Viewer report payload provenance and private acquisition detail", () => { const report = { accessionRegister: [{ accessionNumber: "A1", vendor: "Private Vendor", vendorCode: "V-SECRET", expenseNumber: "EXP-SECRET", donorName: "Private donor", invoiceNumber: "INV-SECRET" }] } as any; const safe = serializeLibraryReportPayload(report, true); expect(safe.accessionRegister[0]).toMatchObject({ vendorLink: "Linked", expenseLink: "Linked" }); const json = JSON.stringify(safe); for (const secret of ["Private Vendor", "V-SECRET", "EXP-SECRET", "Private donor", "INV-SECRET"]) expect(json).not.toContain(secret); });
  it("uses the India-local calendar date in report filenames", () => { expect(libraryReportFilename("accession-register", new Date("2026-07-15T20:30:00.000Z"))).toBe("library-accession-register-2026-07-16.csv"); });
});
