import { readFileSync } from "node:fs";
import { Prisma } from "@prisma/client";
import { describe, expect, it, vi } from "vitest";
import { overdueSuggestion, resolveLibraryChargeRule, validateLibraryChargeRule } from "@/lib/library-charge-rules";
import { deriveOverdue } from "@/lib/library-circulation";
import { collectLibraryCharge, LIBRARY_STAFF_ITEM, LIBRARY_STUDENT_ITEM, waiveLibraryCharge } from "@/lib/library-charges";
import { RECOMMENDED_ROLE_PERMISSIONS } from "@/lib/permissions";
import { DEFAULT_MISC_INCOME_ITEMS } from "@/lib/misc-income";

describe("Library incident, charge, waiver, and collection foundation", () => {
  it("keeps due-today out of derived overdue and calculates India-local overdue days", () => { expect(deriveOverdue({status:"ISSUED",dueDate:new Date("2026-07-16T00:00:00Z")},new Date("2026-07-16T12:00:00Z"))).toEqual({overdue:false,overdueDays:0}); expect(deriveOverdue({status:"ISSUED",dueDate:new Date("2026-07-14T00:00:00Z")},new Date("2026-07-16T12:00:00Z"))).toEqual({overdue:true,overdueDays:2}); });
  it("validates exact-paise charge rules", () => { const row=validateLibraryChargeRule({ruleCode:"stu-6",name:"Class 6",memberType:"STUDENT",className:"6",graceDays:2,overdueAmountPerDay:"1.25",maximumOverdueAmount:"20.50",lostChargeBasis:"FIXED_AMOUNT",fixedLostAmount:"500.25",damagedChargeBasis:"MANUAL",priority:5}); expect(row.ruleCode).toBe("STU-6"); expect(row.overdueAmountPerDay.toFixed(2)).toBe("1.25"); });
  it("rejects negative grace days",()=>expect(()=>validateLibraryChargeRule({ruleCode:"X-1",name:"X",memberType:"STUDENT",graceDays:-1,overdueAmountPerDay:1,lostChargeBasis:"MANUAL",damagedChargeBasis:"MANUAL",priority:0})).toThrow(/non-negative/));
  it("requires positive fixed lost amounts",()=>expect(()=>validateLibraryChargeRule({ruleCode:"X-1",name:"X",memberType:"STUDENT",graceDays:0,overdueAmountPerDay:1,lostChargeBasis:"FIXED_AMOUNT",fixedLostAmount:0,damagedChargeBasis:"MANUAL",priority:0})).toThrow(/positive fixed lost/));
  it("rejects cross-member scopes",()=>expect(()=>validateLibraryChargeRule({ruleCode:"X-1",name:"X",memberType:"STAFF",className:"6",graceDays:0,overdueAmountPerDay:1,lostChargeBasis:"MANUAL",damagedChargeBasis:"MANUAL",priority:0})).toThrow(/cannot have a class/));
  it("applies grace and maximum cap exactly",()=>{const result=overdueSuggestion({graceDays:2,overdueAmountPerDay:new Prisma.Decimal("3.25"),maximumOverdueAmount:new Prisma.Decimal("10.00")},10)!;expect(result.chargeableDays).toBe(8);expect(result.amount.toFixed(2)).toBe("10.00");});
  it("returns no automatic suggestion without a rule",()=>expect(overdueSuggestion(null,10)).toBeNull());
  it("resolves exact Student class before general",async()=>{const rules=[{ruleCode:"CLASS",className:"6",staffType:null,priority:1},{ruleCode:"GENERAL",className:null,staffType:null,priority:99}];const client={libraryMember:{findUnique:async()=>({memberType:"STUDENT",student:{className:"6",academicYearEnrollments:[]},staffMember:null})},libraryChargeRule:{findMany:async()=>rules}} as any;expect((await resolveLibraryChargeRule(client,"m")).rule?.ruleCode).toBe("CLASS");});
  it("requires manual assessment when no rule matches",async()=>{const client={libraryMember:{findUnique:async()=>({memberType:"STAFF",student:null,staffMember:{staffType:"TEACHING",designation:"Teacher"}})},libraryChargeRule:{findMany:async()=>[]}} as any;expect((await resolveLibraryChargeRule(client,"m")).warning).toMatch(/manual amount/);});
  it("guards concurrent full waiver and preserves an append-only event",async()=>{const row:any={id:"c",status:"APPROVED",incidentId:null,originalAmount:new Prisma.Decimal("100"),waivedAmount:new Prisma.Decimal("0"),payableAmount:new Prisma.Decimal("100"),activeOverdueLoanKey:"l",miscIncomeReceiptId:null};const updateMany=vi.fn(async(_arg:any)=>({count:1}));const create=vi.fn(async(_arg:any)=>({}));const client={$transaction:async(fn:any)=>fn({libraryCharge:{findUnique:async()=>row,updateMany,findUniqueOrThrow:async()=>({...row,status:"WAIVED"})},libraryChargeEvent:{create}})} as any;const result=await waiveLibraryCharge(client,"c","100","Leadership waiver","u");expect(result.status).toBe("WAIVED");expect((updateMany.mock.calls as any)[0][0].where).toMatchObject({status:"APPROVED",miscIncomeReceiptId:null});expect((create.mock.calls as any)[0][0].data.eventType).toBe("CHARGE_WAIVED");});
  it("keeps partial waiver approved with exact payable",async()=>{const row:any={id:"c",status:"APPROVED",incidentId:null,originalAmount:new Prisma.Decimal("100.25"),waivedAmount:new Prisma.Decimal("0"),payableAmount:new Prisma.Decimal("100.25"),activeOverdueLoanKey:"l",miscIncomeReceiptId:null};let update:any;const client={$transaction:async(fn:any)=>fn({libraryCharge:{findUnique:async()=>row,updateMany:async(arg:any)=>(update=arg,{count:1}),findUniqueOrThrow:async()=>({...row,status:"APPROVED"})},libraryChargeEvent:{create:async()=>({})}})} as any;await waiveLibraryCharge(client,"c","25.20","Partial waiver","u");expect(update.data.payableAmount.toFixed(2)).toBe("75.05");expect(update.data.status).toBe("APPROVED");});
  it("blocks waiver above the original amount",async()=>{const row:any={status:"APPROVED",originalAmount:new Prisma.Decimal("10"),waivedAmount:new Prisma.Decimal("0"),payableAmount:new Prisma.Decimal("10"),miscIncomeReceiptId:null};const client={$transaction:async(fn:any)=>fn({libraryCharge:{findUnique:async()=>row}})} as any;await expect(waiveLibraryCharge(client,"c","10.01","Too much","u")).rejects.toThrow(/cannot exceed/);});
  it("collects one authoritative Miscellaneous Income line and never touches fee Payment",async()=>{const row:any={id:"c",chargeNumber:"LCH-1",chargeType:"OVERDUE",status:"APPROVED",incidentId:null,studentId:"s",staffMemberId:null,originalAmount:new Prisma.Decimal("50"),waivedAmount:new Prisma.Decimal("10"),payableAmount:new Prisma.Decimal("40"),miscIncomeReceiptId:null,member:{studentId:"s",staffMemberId:null,student:{studentName:"Child"},staffMember:null}};const receiptCreate=vi.fn(async(arg:any)=>({id:"r",receiptNumber:"MISC-1",...arg.data}));const updateMany=vi.fn(async(_arg:any)=>({count:1}));const tx:any={libraryCharge:{findUnique:async()=>row,updateMany,findUniqueOrThrow:async()=>({...row,status:"PAID"})},miscIncomeItem:{upsert:async()=>({id:"item",...LIBRARY_STUDENT_ITEM,status:"ACTIVE"})},miscIncomeReceipt:{create:receiptCreate},libraryChargeEvent:{create:async()=>({})},payment:{create:vi.fn(()=>{throw new Error("fee Payment must not be called")})}};const client={$transaction:async(fn:any)=>fn(tx)} as any;const result=await collectLibraryCharge(client,"c",{receiptDate:"2026-07-16",academicYear:"2026-27",paymentMethod:"CASH"},"u");expect(result.charge.status).toBe("PAID");expect(receiptCreate).toHaveBeenCalledTimes(1);expect((receiptCreate.mock.calls as any)[0][0].data.lines.create.lineTotal.toFixed(2)).toBe("40.00");expect(tx.payment.create).not.toHaveBeenCalled();expect((updateMany.mock.calls as any)[0][0].where).toMatchObject({status:"APPROVED",miscIncomeReceiptId:null});});
  it("uses distinct stable Student and Staff income items without hard-coded rates",()=>{expect(LIBRARY_STUDENT_ITEM).toMatchObject({itemCode:"LIB-STUDENT-CHARGE",studentLinkPolicy:"REQUIRED"});expect(LIBRARY_STAFF_ITEM).toMatchObject({itemCode:"LIB-STAFF-CHARGE",studentLinkPolicy:"NOT_REQUIRED"});expect(DEFAULT_MISC_INCOME_ITEMS.some((row)=>row.itemCode===LIBRARY_STUDENT_ITEM.itemCode)).toBe(true);expect(DEFAULT_MISC_INCOME_ITEMS.some((row)=>"amount" in row)).toBe(false);});
  it("documents unique database guards for incident, overdue charge, and receipt links",()=>{const migration=readFileSync("prisma/migrations/20260716_library_incident_charge_portal_foundation/migration.sql","utf8");for(const key of ["LibraryIncident_activeCaseKey_key","LibraryCharge_activeOverdueLoanKey_key","LibraryCharge_miscIncomeReceiptId_key"])expect(migration).toContain(key);});
  it("assigns safe defaults across leadership, finance, Viewer, Parent, and Teacher",()=>{expect(RECOMMENDED_ROLE_PERMISSIONS.DIRECTOR.has("WAIVE_LIBRARY_CHARGES")).toBe(true);expect(RECOMMENDED_ROLE_PERMISSIONS.ADMIN.has("WAIVE_LIBRARY_CHARGES")).toBe(false);expect(RECOMMENDED_ROLE_PERMISSIONS.PRINCIPAL.has("COLLECT_LIBRARY_CHARGES")).toBe(false);expect(RECOMMENDED_ROLE_PERMISSIONS.ACCOUNTANT.has("COLLECT_LIBRARY_CHARGES")).toBe(true);expect(RECOMMENDED_ROLE_PERMISSIONS.VIEWER.has("VIEW_LIBRARY_CHARGE_REPORTS")).toBe(true);expect(RECOMMENDED_ROLE_PERMISSIONS.VIEWER.has("EXPORT_LIBRARY_CHARGE_REPORTS")).toBe(false);expect(RECOMMENDED_ROLE_PERMISSIONS.PARENT.has("VIEW_OWN_LIBRARY_PORTAL")).toBe(true);expect(RECOMMENDED_ROLE_PERMISSIONS.TEACHER.has("VIEW_OWN_LIBRARY_PORTAL")).toBe(true);});
});
