import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { PERMISSIONS, RECOMMENDED_ROLE_PERMISSIONS } from "@/lib/permissions";
const circulation = ["VIEW_LIBRARY_CIRCULATION", "MANAGE_LIBRARY_MEMBERS", "MANAGE_LIBRARY_POLICIES", "ISSUE_LIBRARY_BOOKS", "RETURN_LIBRARY_BOOKS", "RENEW_LIBRARY_BOOKS", "MANAGE_LIBRARY_RESERVATIONS", "VIEW_LIBRARY_CIRCULATION_REPORTS", "EXPORT_LIBRARY_CIRCULATION_REPORTS"] as const;
describe("library circulation permission defaults", () => {
  it("registers every permission and grants all to Super Admin and Director", () => { for (const permission of circulation) { expect(PERMISSIONS).toContain(permission); expect(RECOMMENDED_ROLE_PERMISSIONS.SUPER_ADMIN.has(permission)).toBe(true); expect(RECOMMENDED_ROLE_PERMISSIONS.DIRECTOR.has(permission)).toBe(true); } });
  it("gives Admin operational circulation and export", () => { for (const permission of circulation) expect(RECOMMENDED_ROLE_PERMISSIONS.ADMIN.has(permission)).toBe(true); });
  it("keeps Principal read-only", () => { expect(RECOMMENDED_ROLE_PERMISSIONS.PRINCIPAL.has("VIEW_LIBRARY_CIRCULATION")).toBe(true); expect(RECOMMENDED_ROLE_PERMISSIONS.PRINCIPAL.has("VIEW_LIBRARY_CIRCULATION_REPORTS")).toBe(true); expect(RECOMMENDED_ROLE_PERMISSIONS.PRINCIPAL.has("ISSUE_LIBRARY_BOOKS")).toBe(false); });
  it("lets circulation viewers open policies while keeping policy controls permission-gated", () => { const page = readFileSync("app/library/policies/page.tsx", "utf8"); const nav = readFileSync("components/library-nav.tsx", "utf8"); expect(page).toContain('requirePermission("VIEW_LIBRARY_CIRCULATION")'); expect(page).toContain('hasUserPermission(user, "MANAGE_LIBRARY_POLICIES")'); expect(page).toContain("canManage ? <LibraryPolicyForm"); expect(nav).toContain("canCirculate || canManagePolicies"); });
  it("limits Viewer/Auditor to masked reports without export", () => { expect(RECOMMENDED_ROLE_PERMISSIONS.VIEWER.has("VIEW_LIBRARY_CIRCULATION_REPORTS")).toBe(true); expect(RECOMMENDED_ROLE_PERMISSIONS.VIEWER.has("VIEW_LIBRARY_CIRCULATION")).toBe(false); expect(RECOMMENDED_ROLE_PERMISSIONS.VIEWER.has("EXPORT_LIBRARY_CIRCULATION_REPORTS")).toBe(false); });
  it("blocks Accountant, Teacher, and Parent", () => { for (const role of ["ACCOUNTANT", "TEACHER", "PARENT"] as const) for (const permission of circulation) expect(RECOMMENDED_ROLE_PERMISSIONS[role].has(permission)).toBe(false); });
});
