import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { createLibraryCopyInTransaction, normalizeAccessionNumber, normalizeLibraryBarcode, serializeLibraryCopy, transitionLibraryCopy, updateLibraryCopyDetails, validateLibraryCopyInput, validateLibraryCopyLinks } from "@/lib/library-accession";

describe("library physical accession register", () => {
  it("normalizes permanent accession and optional barcode identifiers", () => { expect(normalizeAccessionNumber(" lib 2026 / 0001 ")).toBe("LIB-2026/0001"); expect(normalizeLibraryBarcode(" bc 00-1 ")).toBe("BC00-1"); });
  it("validates exact Decimal cost, local date, enums, and withdrawn reason", () => { expect(validateLibraryCopyInput({ titleId: "t", accessionNumber: "A-1", acquisitionDate: "2026-07-15", acquisitionType: "purchased", acquisitionCost: "125.50", condition: "good", status: "available" }).acquisitionCost?.toFixed(2)).toBe("125.50"); expect(() => validateLibraryCopyInput({ titleId: "t", accessionNumber: "A-2", acquisitionType: "other", condition: "good", status: "withdrawn" })).toThrow("Withdrawal reason"); });
  it("rejects invalid dates, money precision, enums, and overlength copy metadata", () => { const valid = { titleId: "t", accessionNumber: "A-1", acquisitionType: "OTHER", condition: "GOOD", status: "AVAILABLE" }; expect(() => validateLibraryCopyInput({ ...valid, acquisitionDate: "2026-02-31" })).toThrow("Acquisition date is invalid"); expect(() => validateLibraryCopyInput({ ...valid, acquisitionCost: "1.234" })).toThrow("at most two decimals"); expect(() => validateLibraryCopyInput({ ...valid, acquisitionType: "BUY" })).toThrow("Acquisition type is not supported"); expect(() => validateLibraryCopyInput({ ...valid, condition: "PERFECT" })).toThrow("Copy condition is not supported"); expect(() => validateLibraryCopyInput({ ...valid, shelfCode: "X".repeat(81) })).toThrow("Shelf code must be at most 80 characters"); });
  it("creates the copy and ACCESSIONED event in one transaction client", async () => { const eventCreate = vi.fn(async ({ data }) => ({ id: "e", ...data })); const copy = { id: "c", titleId: "t", accessionNumber: "A-1", barcodeValue: null, acquisitionDate: null, acquisitionType: "OTHER", acquisitionCost: null, vendorId: null, expenseRecordId: null, donorName: null, invoiceNumberSnapshot: null, condition: "GOOD", status: "AVAILABLE", shelfCode: "A", notes: null, withdrawnDate: null, withdrawalReason: null }; const client = { libraryTitle: { findUnique: vi.fn(async () => ({ id: "t", status: "ACTIVE" })) }, vendor: { findFirst: vi.fn() }, expenseRecord: { findUnique: vi.fn() }, libraryCopy: { create: vi.fn(async () => copy), findUniqueOrThrow: vi.fn(async () => ({ ...copy, title: { id: "t", titleCode: "T", title: "Title", authors: "Author", isbn: null }, vendor: null, expenseRecord: null, events: [] })) }, libraryCopyEvent: { create: eventCreate } }; await createLibraryCopyInTransaction(client as never, { titleId: "t", accessionNumber: "a-1", acquisitionType: "other", condition: "good", status: "available", shelfCode: "a" }, "u"); expect(eventCreate).toHaveBeenCalledWith({ data: expect.objectContaining({ copyId: "c", eventType: "ACCESSIONED", newStatus: "AVAILABLE", newCondition: "GOOD", recordedByUserId: "u" }) }); });
  it("blocks direct accession or correction against an inactive title", async () => { const client = { libraryTitle: { findUnique: vi.fn(async () => ({ id: "t", status: "INACTIVE" })) }, vendor: { findFirst: vi.fn() }, expenseRecord: { findUnique: vi.fn() } }; await expect(validateLibraryCopyLinks(client as never, { titleId: "t", vendorId: null, expenseRecordId: null })).rejects.toThrow("active library title"); });
  it("blocks silent accession-number edits before any database write", async () => { await expect(updateLibraryCopyDetails({} as never, "c", { accessionNumber: "NEW" }, "u")).rejects.toThrow("permanent"); });
  it("requires a withdrawal reason before a transaction starts", async () => { await expect(transitionLibraryCopy({} as never, "c", "withdraw", "u", "")).rejects.toThrow("Reason is required"); });
  it("masks Vendor/Expense identity and private notes for Viewer payloads", () => { const safe = serializeLibraryCopy({ id: "c", title: { id: "t", titleCode: "T", title: "Title", authors: "A", isbn: null }, accessionNumber: "A", barcodeValue: null, acquisitionCost: { toString: () => "10.00" }, vendor: { id: "v", vendorCode: "V1", name: "Vendor", gstin: "secret" }, expenseRecord: { id: "e", expenseNumber: "EXP-1", approvalStatus: "APPROVED", transactionReference: "secret" }, notes: "private", invoiceNumberSnapshot: "INV", events: [] }, true); expect(safe.vendor).toEqual({ linked: true, label: "Linked Vendor" }); expect(safe.expenseRecord).toEqual({ linked: true, label: "Linked Expense" }); expect(safe.notes).toBeNull(); expect(safe.invoiceNumberSnapshot).toBe("Recorded"); expect(JSON.stringify(safe)).not.toContain("EXP-1"); });
  it("defines no hard-delete or circulation actions", () => { const source = readFileSync("lib/library-accession.ts", "utf8"); expect(source).not.toMatch(/libraryCopy\.delete/); expect(source).not.toMatch(/libraryCopyEvent\.(update|delete)/); for (const action of ["issueLibraryCopy", "returnLibraryCopy", "renewLibraryLoan", "createLibraryReservation", "calculateLibraryOverdue", "createLibraryFine"]) expect(source).not.toContain(action); });
  it("keeps schema deletion restrictive for title, copy, and event history", () => { const migration = readFileSync("prisma/migrations/20260715_library_catalog_accession_foundation/migration.sql", "utf8"); expect(migration).not.toContain("ON DELETE CASCADE"); expect(migration).not.toMatch(/ALTER TABLE "Payment"/); expect(migration).not.toMatch(/ALTER TABLE "BookCatalogItem"/); });
});
