import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createBackupDocument } from "@/lib/backup";
import { parseAndValidateBackup } from "@/lib/restore";

function fixture() { const at = "2026-07-15T00:00:00.000Z"; return createBackupDocument({ generatedAt: new Date(at), generatedBy: "QA", students: [{ id: "s1", admissionNo: "A1", studentName: "Student", fatherName: "Parent", className: "6", phone1: "000", status: "Active", createdAt: at, updatedAt: at }], feeStructures: [], payments: [], paymentAudits: [], users: [{ id: "u1", username: "qa", passwordHash: "must-not-export" }], libraryTitles: [{ id: "t1", titleCode: "T1", title: "Title", authors: "Author", status: "ACTIVE", createdAt: at, updatedAt: at }], libraryCopies: [{ id: "c1", titleId: "t1", accessionNumber: "ACC-1", acquisitionType: "OTHER", condition: "GOOD", status: "AVAILABLE", createdAt: at, updatedAt: at }], libraryCopyEvents: [{ id: "ce1", copyId: "c1", eventType: "ACCESSIONED", eventDate: at, createdAt: at }], libraryMembers: [{ id: "m1", memberCode: "MEM-1", memberType: "STUDENT", studentId: "s1", staffMemberId: null, status: "ACTIVE", joinedDate: at, createdAt: at, updatedAt: at }], libraryPolicies: [{ id: "p1", policyCode: "STU-GEN", name: "Student general", memberType: "STUDENT", className: null, staffType: null, maxActiveLoans: 2, loanPeriodDays: 14, maxRenewals: 1, renewalPeriodDays: 7, reservationLimit: 1, status: "ACTIVE", priority: 0, createdAt: at, updatedAt: at }], libraryLoans: [{ id: "l1", loanNumber: "LN-1", copyId: "c1", memberId: "m1", status: "ISSUED", activeCopyKey: "c1", issueDate: at, dueDate: "2026-07-29T00:00:00.000Z", returnedDate: null, renewCount: 0, policyCodeSnapshot: "STU-GEN", loanPeriodDaysSnapshot: 14, maxRenewalsSnapshot: 1, renewalPeriodDaysSnapshot: 7, issueConditionSnapshot: "GOOD", createdAt: at, updatedAt: at }], libraryReservations: [{ id: "r1", reservationNumber: "RSV-1", titleId: "t1", memberId: "m1", status: "FULFILLED", activeMemberTitleKey: null, requestedDate: at, fulfilledLoanId: "l1", fulfilledAt: at, createdAt: at, updatedAt: at }], libraryLoanEvents: [{ id: "le1", loanId: "l1", reservationId: null, memberId: "m1", copyId: "c1", titleId: "t1", eventType: "ISSUED", eventDate: at, newDueDate: "2026-07-29T00:00:00.000Z", createdAt: at }, { id: "le2", loanId: "l1", reservationId: "r1", memberId: "m1", copyId: "c1", titleId: "t1", eventType: "RESERVATION_FULFILLED", eventDate: at, createdAt: at }] }); }

describe("library circulation backup version 20", () => {
  it("includes all circulation arrays and excludes password hashes", () => { const backup = fixture(); expect(backup.metadata.backupVersion).toBe(37); for (const key of ["libraryMembers", "libraryPolicies", "libraryLoans", "libraryReservations", "libraryLoanEvents"] as const) expect(backup[key].length).toBeGreaterThan(0); expect(JSON.stringify(backup)).not.toContain("passwordHash"); expect(JSON.stringify(backup)).not.toContain("must-not-export"); });
  it("preserves policy snapshots, active-copy identity, fulfilment, and events", () => { const parsed = parseAndValidateBackup(fixture()); expect(parsed.libraryLoans[0]).toMatchObject({ activeCopyKey: "c1", policyCodeSnapshot: "STU-GEN", renewalPeriodDaysSnapshot: 7 }); expect(parsed.libraryReservations[0]).toMatchObject({ fulfilledLoanId: "l1" }); expect(parsed.libraryLoanEvents.map((row) => row.eventType)).toEqual(["ISSUED", "RESERVATION_FULFILLED"]); });
  it("keeps version 19 backups compatible without circulation arrays", () => { const old: any = fixture(); old.metadata.backupVersion = 19; for (const key of ["libraryMembers", "libraryPolicies", "libraryLoans", "libraryReservations", "libraryLoanEvents"]) { delete old[key]; delete old.metadata.counts[key]; } const parsed = parseAndValidateBackup(old); expect(parsed.libraryMembers).toEqual([]); expect(parsed.libraryLoans).toEqual([]); });
  it("rejects invalid membership XOR/type links", () => { const backup: any = fixture(); backup.libraryMembers[0].staffMemberId = "staff"; expect(() => parseAndValidateBackup(backup)).toThrow(/exactly one/); const mismatch: any = fixture(); mismatch.libraryMembers[0].memberType = "STAFF"; expect(() => parseAndValidateBackup(mismatch)).toThrow(/does not match/); });
  it("rejects two active restored loans for one copy", () => { const backup: any = fixture(); backup.libraryLoans.push({ ...backup.libraryLoans[0], id: "l2", loanNumber: "LN-2" }); backup.metadata.counts.libraryLoans = 2; expect(() => parseAndValidateBackup(backup)).toThrow(/active-copy uniqueness/); });
  it("rejects duplicate waiting reservation member/title and bad fulfilment links", () => { const waiting: any = fixture(); waiting.libraryReservations[0] = { ...waiting.libraryReservations[0], status: "WAITING", activeMemberTitleKey: "m1:t1", fulfilledLoanId: null, fulfilledAt: null }; waiting.libraryReservations.push({ ...waiting.libraryReservations[0], id: "r2", reservationNumber: "RSV-2" }); waiting.metadata.counts.libraryReservations = 2; expect(() => parseAndValidateBackup(waiting)).toThrow(/reservation uniqueness/); const bad: any = fixture(); bad.libraryReservations[0].fulfilledLoanId = "missing"; expect(() => parseAndValidateBackup(bad)).toThrow(/does not link exactly one/); });
  it("rejects circulation events that contradict or omit their canonical links", () => { const mismatch: any = fixture(); mismatch.libraryLoanEvents[0].memberId = "missing-member"; expect(() => parseAndValidateBackup(mismatch)).toThrow(/invalid member link/); const wrongCopy: any = fixture(); wrongCopy.libraryCopies.push({ ...wrongCopy.libraryCopies[0], id: "c2", accessionNumber: "ACC-2" }); wrongCopy.libraryCopyEvents.push({ ...wrongCopy.libraryCopyEvents[0], id: "ce2", copyId: "c2" }); wrongCopy.metadata.counts.libraryCopies = 2; wrongCopy.metadata.counts.libraryCopyEvents = 2; wrongCopy.libraryLoanEvents[0].copyId = "c2"; expect(() => parseAndValidateBackup(wrongCopy)).toThrow(/does not match its linked loan/); const missingLoan: any = fixture(); missingLoan.libraryLoanEvents[0].loanId = null; expect(() => parseAndValidateBackup(missingLoan)).toThrow(/loanId is required for ISSUED/); const badFulfilment: any = fixture(); badFulfilment.libraryLoanEvents[1].loanId = null; expect(() => parseAndValidateBackup(badFulfilment)).toThrow(/requires matching fulfilled reservation and loan links/); });
  it("contains database CHECK and unique-key constraints", () => { const sql = readFileSync("prisma/migration-archives/devops1b-legacy-chain/20260715_library_membership_circulation_foundation/migration.sql", "utf8"); expect(sql).toContain("LibraryMember_exactly_one_link_check"); expect(sql).toContain("LibraryLoan_activeCopyKey_key"); expect(sql).toContain("LibraryReservation_activeMemberTitleKey_key"); });
});

