import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { getParentLibraryData,getTeacherLibraryData } from "@/lib/library-portals";
function member(){return {memberCode:"MEM-1",memberType:"STUDENT",status:"ACTIVE",joinedDate:new Date("2026-01-01Z"),loans:[],reservations:[],incidents:[],charges:[]};}
describe("Library Parent and Teacher ownership portals",()=>{
 it("returns linked Parent children by public admission number only",async()=>{const client={user:{findUnique:async()=>({role:"PARENT",guardianId:"g"})},studentGuardian:{findMany:async()=>[{student:{id:"secret",admissionNo:"A1",studentName:"One",className:"6",section:"A",libraryMember:member()}}]}} as any;const data=await getParentLibraryData(client,"u","A1");expect(data.selectedChild).toEqual({admissionNo:"A1",studentName:"One",className:"6",section:"A"});expect(JSON.stringify(data)).not.toContain("secret");});
 it("rejects selection of another child",async()=>{const client={user:{findUnique:async()=>({role:"PARENT",guardianId:"g"})},studentGuardian:{findMany:async()=>[{student:{id:"s",admissionNo:"A1",studentName:"One",className:"6",section:null,libraryMember:null}}]}} as any;await expect(getParentLibraryData(client,"u","A2")).rejects.toThrow(/not found/);});
 it("rejects non-Parent accounts at the helper boundary",async()=>{const client={user:{findUnique:async()=>({role:"ADMIN",guardianId:"g"})}} as any;await expect(getParentLibraryData(client,"u")).rejects.toMatchObject({status:403});});
 it("uses the Teacher login's own StaffMember only",async()=>{const client={user:{findUnique:async()=>({role:"TEACHER",staffMember:{fullName:"Teacher One",displayName:null,staffCode:"T1",libraryMember:{...member(),memberType:"STAFF"}}})}} as any;const data=await getTeacherLibraryData(client,"u");expect(data.staff).toEqual({name:"Teacher One",staffCode:"T1"});expect(data.membership?.memberType).toBe("STAFF");});
 it("returns a friendly unlinked Teacher state",async()=>{const client={user:{findUnique:async()=>({role:"TEACHER",staffMember:null})}} as any;const data=await getTeacherLibraryData(client,"u");expect(data).toMatchObject({staff:null,membership:null,loans:[],charges:[]});});
 it("renders serialized Decimal amounts without calling Decimal-only methods in the client",()=>{const source=readFileSync("components/library-accountability-forms.tsx","utf8");expect(source).toContain("Number(charge.payableAmount).toFixed(2)");expect(source).not.toContain("charge.payableAmount.toFixed(2)");});
 it("falls back safely when a Parent requests an unlinked child",()=>{const source=readFileSync("app/parent/library/page.tsx","utf8");expect(source).toContain("That child is not linked to this Parent account");expect(source).toContain("data = await getParentLibraryData(prisma, user.id)");});
});
