import {describe,it,expect} from "vitest";
import {readFileSync} from "node:fs";
import {materialFixture} from "./helpers/material-roundtrip-fixture";
import {verifyPreparation,lockedPackages} from "../scripts/portable/material-source";
import {verifyMaterialManifest} from "../scripts/portable/product-materials";
import {runProductBuildScan} from "../scripts/portable/product-build-scan";
import {publicMaterialAddress,materialDownloadURL} from "../scripts/portable/material-download";
import {acquisitionPreparation} from "../scripts/portable/material-acquisition";

describe('HARNESS_ONLY material provenance roundtrip',()=>{
 it('rejects substituted signed plan before selecting any download/preparation',()=>{const s=materialFixture();try{const expected=s.f.put(s.plan),tampered=Buffer.from(JSON.stringify({...s.plan,preparation:'0'.repeat(64)}));let selected=0;expect(()=>acquisitionPreparation(tampered,expected,s.f.d,id=>{selected++;return s.f.get(id);})).toThrow('MATERIAL_ACQUISITION_PLAN_SUBSTITUTED');expect(selected).toBe(0);expect(acquisitionPreparation(s.f.get(expected),expected,s.f.d,s.f.get).source).toBe(s.f.d.source);}finally{s.f.dispose();}});
 it('connects acquisition caller through collector and manifest packaging without product admission',async()=>{const s=materialFixture();try{const h=s.harness(),original=h.command;h.command=(command,root)=>{if(command.stage!=='build')return original(command,root);expect(command.args).toContain('force-network-mode=none');expect(command.args).toContain('add-hosts=registry.npmjs.org=127.0.0.1,cdn.sheetjs.com=127.0.0.1');return {stage:'build',tool:s.f.python,args:['-B','-c',`import sys,json,tarfile\nfrom pathlib import Path\na,b=map(Path,sys.argv[1:]);layout=a/'product-oci'\nwith tarfile.open(b/'product.oci.tar','w') as t:\n for f in layout.rglob('*'):\n  if f.is_file():t.add(f,arcname=f.relative_to(layout).as_posix(),recursive=False)\nidx=json.loads((layout/'index.json').read_bytes());m=json.loads((layout/'blobs/sha256'/idx['manifests'][0]['digest'][7:]).read_bytes());(b/'build-metadata.json').write_text(json.dumps({'containerimage.config.digest':m['config']['digest'],'containerimage.digest':idx['manifests'][0]['digest']}))`,s.collectorRoot,root]};};s.save('product-oci/oci-layout',Buffer.from(JSON.stringify({imageLayoutVersion:'1.0.0'})));const out=await runProductBuildScan(s.f.workspace,s.f.verified(),s.f.get,h,undefined,undefined,s.verify());expect(out.failures).toEqual([]);expect(out.complete).toBe(true);expect(out.materialQualification.classification).toBe('UNSIGNED_MATERIAL_QUALIFICATION_CANDIDATE');expect(out.product).toBe('NOT_BUILT');expect(out.states).toContain('material-collect');expect(out.admitted).toBe(false);}finally{s.f.dispose();}});
 it('collects actual OCI bytes, serializes existing manifest and reaches clean offline consuming caller',async()=>{const s=materialFixture();try{const result=await s.pack();s.f.d.images.dependencies=result.image;s.f.d.materials=result.sha256;const verified=s.f.verified();expect(verified.materials?.recipe.toString()).not.toMatch(/apt-get|corepack|pnpm install/);const out=await runProductBuildScan(s.f.workspace,verified,s.f.get,s.harness());expect(out.failures).toEqual([]);expect(out.complete).toBe(true);expect(out.states).toContain('material-consume');expect(out.states).toContain('material-debian-installed');expect(out.classification).toBe('HARNESS_ONLY');expect(out.admitted).toBe(false);}finally{s.f.dispose();}});
 it('accepts reordered descriptor properties without losing hash bindings',()=>{const s=materialFixture();try{s.prep.downloads=s.prep.downloads.map(e=>({bytes:e.bytes,sha256:e.sha256,url:e.url}));const h=s.f.put(s.prep);expect(verifyPreparation(s.f.get(h),h,s.f.d,s.f.get).origins.length).toBe(5);}finally{s.f.dispose();}});
 it('parses the actual pinned source lock without network or installation',()=>expect(lockedPackages(readFileSync('pnpm-lock.yaml')).length).toBeGreaterThan(100));
 it.each(['omit','duplicate','substitute','platform','role','truncated'] as const)('refuses %s source material',kind=>{const s=materialFixture();try{if(kind==='omit')s.prep.tarballs.pop();if(kind==='duplicate')s.prep.downloads.push(s.prep.downloads[0]);if(kind==='substitute')s.f.blobs.set(s.prep.tarballs[0].sha256,Buffer.from('substituted'));if(kind==='platform')s.prep.architecture='arm64';if(kind==='role')s.prep.origins[0].role='sharp';if(kind==='truncated')s.f.blobs.set(s.prep.downloads[0].sha256,s.f.get(s.prep.downloads[0].sha256).subarray(0,3));const h=s.f.put(s.prep);expect(()=>verifyPreparation(s.f.get(h),h,s.f.d,s.f.get)).toThrow();}finally{s.f.dispose();}});
 it.each(['omitted','duplicate'] as const)('consumer rejects %s native member inventory',async kind=>{const s=materialFixture();try{const result=await s.pack(),m=JSON.parse(s.f.get(result.sha256).toString()),n=JSON.parse(s.f.get(m.acquisition.nativeInventory).toString());if(kind==='omitted')n.files.pop();else n.files.push(n.files[0]);m.acquisition.nativeInventory=s.f.put(n);const h=s.f.put(m);expect(()=>verifyMaterialManifest(s.f.get(h),h,s.f.d,s.f.get)).toThrow('MATERIAL_NATIVE_CLOSURE_MISSING');}finally{s.f.dispose();}});
 it.each(['extra-native','missing-native','wrong-platform','failed-install','replay-substitution','opaque-whiteout'])('collector refuses %s',kind=>{const s=materialFixture();try{if(kind==='extra-native')s.files['app/node_modules/undeclared.node']=s.files['app/node_modules/sharp.node'];if(kind==='missing-native')delete s.files['app/node_modules/sharp.node'];if(kind==='wrong-platform'){s.files['app/node_modules/sharp.node']=Buffer.from(s.files['app/node_modules/sharp.node']);s.files['app/node_modules/sharp.node'].writeUInt16LE(183,18);}if(kind==='failed-install'){const p='opt/nalanda-materials/receipts/install.json',r=JSON.parse(s.files[p].toString());r.exit=7;s.files[p]=Buffer.from(JSON.stringify(r));}if(kind==='replay-substitution')s.files['opt/nalanda-materials/receipts/replay.json']=Buffer.from(JSON.stringify({requests:[{url:'https://unapproved.invalid/a',sha256:'0'.repeat(64)}],denied:0}));if(kind==='opaque-whiteout')s.files['app/.wh..wh..opq']=Buffer.alloc(0);s.layout();expect(s.collect).toThrow();}finally{s.f.dispose();}});
 it('plan cannot substitute engine bytes or package versions after preparation',()=>{const s=materialFixture();try{s.plan.packages[0].version='2';expect(s.verify).toThrow('MATERIAL_PLAN_INVENTORY_MISMATCH');}finally{s.f.dispose();}});
 it.each(['inventory','origins','tarballs'])('verified preparation refuses later %s mutation',field=>{const s=materialFixture();try{const a=s.verify();if(field==='inventory')a.preparation!.inventory='0'.repeat(64);else a.preparation![field as 'origins'|'tarballs'].pop();expect(a.guard).toThrow('MATERIAL_ACQUISITION_MUTATED');}finally{s.f.dispose();}});
});
describe('finite downloader socket targets',()=>{
 it.each(['127.0.0.1','10.1.2.3','169.254.169.254','172.16.0.2','192.168.1.1','100.100.100.200','198.19.0.1','224.0.0.1','::1','::ffff:127.0.0.1'])('refuses %s',a=>expect(publicMaterialAddress(a)).toBe(false));
 it('accepts public IPv4 and exact official HTTPS route',()=>{expect(publicMaterialAddress('104.16.31.34')).toBe(true);expect(materialDownloadURL('https://registry.npmjs.org/a').hostname).toBe('registry.npmjs.org');});
 it('refuses credentials on an otherwise approved URL',()=>{const url=new URL('https://registry.npmjs.org/a');url.username='fixture';url.password='fixture';expect(()=>materialDownloadURL(url.href)).toThrow();});
 it.each(['http://registry.npmjs.org/a','https://registry.npmjs.org.evil.invalid/a','https://registry.npmjs.org/a?secret=x','https://127.0.0.1/a'])('refuses noncanonical or unapproved URL',url=>expect(()=>materialDownloadURL(url)).toThrow());
});
