import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createBackupDocument } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";

const now = "2026-07-15T00:00:00.000Z";
function fixture() { return createBackupDocument({ generatedAt: new Date(now), generatedBy: "Director", students: [{ id: "student-1", academicYear: "2026-27", admissionNo: "NPS1", studentName: "Student", fatherName: "Father", className: "I", phone1: "9000000000", status: "Active", studentType: "Normal", discountPercent: 0, startMonth: "June", createdAt: now, updatedAt: now }], feeStructures: [], payments: [], paymentAudits: [], users: [{ id: "user-1", username: "director", passwordHash: "must-not-export" }], miscIncomeItems: [{ id: "item-1", itemCode: "BELT", name: "Belt", category: "UNIFORM_ACCESSORY", studentLinkPolicy: "OPTIONAL", status: "ACTIVE", createdAt: now, updatedAt: now }], miscIncomeRates: [{ id: "rate-1", itemId: "item-1", academicYear: "2026-27", amount: "100.25", status: "ACTIVE", createdAt: now, updatedAt: now }], miscIncomeReceipts: [{ id: "receipt-1", receiptNumber: "MISC-20260715-ABC123", receiptDate: now, academicYear: "2026-27", studentId: "student-1", payerName: "Parent", paymentMethod: "CASH", receivedAccount: "CASH_COUNTER", grossAmount: "200.50", discountAmount: "0.50", netAmount: "200.00", status: "ACTIVE", createdByUserId: "user-1", createdAt: now, updatedAt: now }], miscIncomeReceiptLines: [{ id: "line-1", receiptId: "receipt-1", itemId: "item-1", itemNameSnapshot: "Belt", rateId: "rate-1", quantity: 2, unitAmount: "100.25", discountAmount: "0.50", lineTotal: "200.00", createdAt: now }], cashBookDays: [{ id: "day-1", cashDate: now, academicYear: "2026-27", openingBalance: "10.00", status: "LOCKED", feeCashSnapshot: "20.00", miscIncomeCashSnapshot: "200.00", cashExpenseSnapshot: "5.00", manualInflowSnapshot: "0.00", manualOutflowSnapshot: "0.00", bankDepositSnapshot: "100.00", directorHandoverSnapshot: "50.00", calculatedClosingBalance: "75.00", countedClosingBalance: "75.00", varianceAmount: "0.00", sourceSummarySnapshot: "{}", notes: "Reconciled", createdByUserId: "user-1", submittedByUserId: "user-1", approvedByUserId: "user-1", lockedByUserId: "user-1", submittedAt: now, approvedAt: now, lockedAt: now, createdAt: now, updatedAt: now }], cashBookMovements: [{ id: "movement-1", cashBookDayId: "day-1", movementType: "BANK_DEPOSIT", amount: "100.00", movementDate: now, referenceNumber: "QA-BANK", reason: "Deposited to school current account", status: "ACTIVE", recordedByUserId: "user-1", createdAt: now, updatedAt: now }] }); }

describe("miscellaneous income and cash-book backup restore v17", () => {
  it("includes all six entity arrays and excludes password hashes", () => { const backup = fixture(); expect(backup.metadata.backupVersion).toBe(42); for (const key of ["miscIncomeItems", "miscIncomeRates", "miscIncomeReceipts", "miscIncomeReceiptLines", "cashBookDays", "cashBookMovements"] as const) expect(backup[key]).toHaveLength(1); expect(JSON.stringify(backup)).not.toContain("passwordHash"); expect(JSON.stringify(backup)).not.toContain("must-not-export"); });
  it("preserves receipt snapshots and locked cash snapshots", () => { const parsed = parseAndValidateBackup(fixture()); expect(parsed.miscIncomeReceiptLines[0]).toMatchObject({ itemNameSnapshot: "Belt", unitAmount: "100.25", lineTotal: "200.00" }); expect(parsed.cashBookDays[0]).toMatchObject({ status: "LOCKED", feeCashSnapshot: "20.00", sourceSummarySnapshot: "{}" }); });
  it("remains compatible with version 16 backups that omit the arrays", () => { const backup: any = fixture(); for (const key of ["miscIncomeItems", "miscIncomeRates", "miscIncomeReceipts", "miscIncomeReceiptLines", "cashBookDays", "cashBookMovements"]) { delete backup[key]; delete backup.metadata.counts[key]; } backup.metadata.backupVersion = 16; const parsed = parseAndValidateBackup(backup); expect(parsed.miscIncomeItems).toEqual([]); expect(parsed.cashBookDays).toEqual([]); });
  it("rejects invalid student, item, rate, receipt, and movement links", () => { const student: any = fixture(); student.miscIncomeReceipts[0].studentId = "missing"; expect(() => parseAndValidateBackup(student)).toThrow(/studentId/); const item: any = fixture(); item.miscIncomeRates[0].itemId = "missing"; expect(() => parseAndValidateBackup(item)).toThrow(/itemId/); const rate: any = fixture(); rate.miscIncomeReceiptLines[0].rateId = "missing"; expect(() => parseAndValidateBackup(rate)).toThrow(/rateId/); const receipt: any = fixture(); receipt.miscIncomeReceiptLines[0].receiptId = "missing"; expect(() => parseAndValidateBackup(receipt)).toThrow(/receiptId/); const movement: any = fixture(); movement.cashBookMovements[0].cashBookDayId = "missing"; expect(() => parseAndValidateBackup(movement)).toThrow(/cashBookDayId/); });
  it("rejects a receipt line whose rate belongs to a different item", () => { const backup: any = fixture(); backup.miscIncomeItems.push({ ...backup.miscIncomeItems[0], id: "item-2", itemCode: "TIE", name: "Tie" }); backup.miscIncomeReceiptLines[0].itemId = "item-2"; expect(() => parseAndValidateBackup(backup)).toThrow(/rateId.*same item/); });
  it("rejects overlapping restored active rates", () => { const backup: any = fixture(); backup.miscIncomeRates.push({ ...backup.miscIncomeRates[0], id: "rate-2", effectiveFrom: "2026-07-01T00:00:00.000Z" }); expect(() => parseAndValidateBackup(backup)).toThrow(/overlaps an active rate/); });
  it("revalidates student-link and physical-cash account policies during restore", () => { const student: any = fixture(); student.miscIncomeItems[0].studentLinkPolicy = "REQUIRED"; student.miscIncomeReceipts[0].studentId = null; expect(() => parseAndValidateBackup(student)).toThrow(/requires a student-linked receipt/); const cash: any = fixture(); cash.miscIncomeReceipts[0].receivedAccount = "DIRECTOR_GPAY"; expect(() => parseAndValidateBackup(cash)).toThrow(/CASH_COUNTER/); });
  it("rejects a movement dated outside its linked cash day", () => { const backup: any = fixture(); backup.cashBookMovements[0].movementDate = "2026-07-16T00:00:00.000Z"; expect(() => parseAndValidateBackup(backup)).toThrow(/movementDate.*cash day/); });
  it("rejects inconsistent closing and variance snapshots", () => { const closing: any = fixture(); closing.cashBookDays[0].calculatedClosingBalance = "74.99"; expect(() => parseAndValidateBackup(closing)).toThrow(/calculatedClosingBalance.*formula/); const variance: any = fixture(); variance.cashBookDays[0].varianceAmount = "0.01"; expect(() => parseAndValidateBackup(variance)).toThrow(/varianceAmount.*counted closing/); });
  it("rejects duplicate receipt numbers and cash dates", () => { const receipt: any = fixture(); receipt.miscIncomeReceipts.push({ ...receipt.miscIncomeReceipts[0], id: "receipt-2" }); expect(() => parseAndValidateBackup(receipt)).toThrow(/duplicates a receipt/); const day: any = fixture(); day.cashBookDays.push({ ...day.cashBookDays[0], id: "day-2" }); expect(() => parseAndValidateBackup(day)).toThrow(/duplicates a cash day/); });
  it("rejects unreconciled receipt header and line totals", () => { const header: any = fixture(); header.miscIncomeReceipts[0].netAmount = "199.00"; expect(() => parseAndValidateBackup(header)).toThrow(/inconsistent totals/); const line: any = fixture(); line.miscIncomeReceiptLines[0].lineTotal = "199.00"; expect(() => parseAndValidateBackup(line)).toThrow(/inconsistent totals/); });
  it("rejects negative receipt, quantity, and movement amounts", () => { const receipt: any = fixture(); receipt.miscIncomeReceipts[0].grossAmount = "-1"; expect(() => parseAndValidateBackup(receipt)).toThrow(/non-negative/); const quantity: any = fixture(); quantity.miscIncomeReceiptLines[0].quantity = 0; expect(() => parseAndValidateBackup(quantity)).toThrow(/positive integer/); const movement: any = fixture(); movement.cashBookMovements[0].amount = "-1"; expect(() => parseAndValidateBackup(movement)).toThrow(/non-negative/); });
  it("allows reconciled signed expected closing and variance snapshots", () => { const backup: any = fixture(); backup.cashBookDays[0].bankDepositSnapshot = "176.25"; backup.cashBookDays[0].calculatedClosingBalance = "-1.25"; backup.cashBookDays[0].varianceAmount = "76.25"; expect(parseAndValidateBackup(backup).cashBookDays[0].calculatedClosingBalance).toBe("-1.25"); });
  it("documents exact-identity collision isolation and local-newer preservation", () => { const source = readFileSync("lib/restore-database.ts", "utf8"); expect(source).toContain("different identity; its backup lines were not attached"); expect(source).toContain("different identity; backup movements were isolated"); expect(source).toContain("kept because the local record is newer"); expect(source).toContain("protectedReceipts"); expect(source).toContain("protectedDays"); });
  it("is idempotent and never deletes local finance-control data", () => { const source = readFileSync("lib/restore-database.ts", "utf8"); const section = source.slice(source.indexOf("export async function restoreMiscIncomeAndCashBookData"), source.indexOf("export async function restoreNoticesData")); expect(section).toContain("findUnique"); expect(section).toContain("skipped++"); expect(section).not.toContain("deleteMany"); expect(section).not.toContain("delete("); });
});
