import { readFileSync } from "node:fs";
import { Prisma } from "@prisma/client";
import { describe, expect, it } from "vitest";
import { can, PERMISSIONS } from "../lib/permissions";
import { assertNoActiveRateOverlap, DEFAULT_MISC_INCOME_ITEMS, miscIncomeCsv, miscIncomeItemWriteError, miscIncomeReport, serializeMiscReceipt, validateMiscItemInput, validateMiscRateInput, validateMiscReceiptInput } from "../lib/misc-income";

const rate = { id: "rate-1", academicYear: "2026-27", amount: new Prisma.Decimal("100.25"), effectiveFrom: null, effectiveTo: null, updatedAt: new Date("2026-07-01T00:00:00.000Z") };
const items = [{ id: "belt", itemCode: "BELT", name: "Belt", studentLinkPolicy: "OPTIONAL", status: "ACTIVE", rates: [rate] }];
function client(overrides: any = {}) { return { miscIncomeItem: { findMany: async () => overrides.items ?? items }, student: { findFirst: async () => overrides.student ?? { id: "student-1" } } } as any; }
function receipt(overrides: any = {}) { return { receiptDate: "2026-07-15", academicYear: "2026-27", studentId: "student-1", payerName: "QA Payer", paymentMethod: "CASH", receivedAccount: "CASH_COUNTER", lines: [{ itemId: "belt", quantity: 2, discountAmount: "0" }], ...overrides }; }

describe("miscellaneous income foundation", () => {
  it("seeds configurable items without hard-coded prices", () => { expect(DEFAULT_MISC_INCOME_ITEMS.map((row) => row.name)).toEqual(["Belt", "Tie", "Bonafide Certificate", "Transfer Certificate", "Class X Certificate / Migration Service", "Student Library Charge", "Staff Library Charge", "Other"]); expect(DEFAULT_MISC_INCOME_ITEMS.some((row) => "amount" in row)).toBe(false); });
  it("validates item categories and student link policies", () => { expect(validateMiscItemInput({ itemCode: "TC", name: "Transfer Certificate", category: "STUDENT_DOCUMENT", studentLinkPolicy: "REQUIRED" })).toMatchObject({ status: "ACTIVE", studentLinkPolicy: "REQUIRED" }); expect(() => validateMiscItemInput({ itemCode: "X", name: "X", category: "BAD", studentLinkPolicy: "OPTIONAL" })).toThrow(/not supported/); });
  it("normalizes item codes so case variants cannot bypass uniqueness", () => { expect(validateMiscItemInput({ itemCode: " belt ", name: "Belt", category: "UNIFORM_ACCESSORY", studentLinkPolicy: "OPTIONAL" }).itemCode).toBe("BELT"); });
  it("does not expose raw database details for duplicate item codes", () => { expect(miscIncomeItemWriteError({ code: "P2002", meta: { target: "itemCode" } }, "Unable to create income item")).toBe("Item code already exists"); });
  it("accepts exact paise and dated academic-year rates", () => { expect(validateMiscRateInput({ itemId: "belt", academicYear: "2026-27", amount: "99.95", effectiveFrom: "2026-07-01", effectiveTo: "2026-07-31" }).amount.toFixed(2)).toBe("99.95"); });
  it("rejects reversed rate dates", () => { expect(() => validateMiscRateInput({ itemId: "belt", academicYear: "2026-27", amount: 10, effectiveFrom: "2026-08-01", effectiveTo: "2026-07-01" })).toThrow(/cannot be before/); });
  it("prevents ambiguous active-rate overlap", async () => { const db = { miscIncomeRate: { findMany: async () => [{ effectiveFrom: new Date("2026-07-01Z"), effectiveTo: new Date("2026-07-31Z") }] } } as any; await expect(assertNoActiveRateOverlap(db, validateMiscRateInput({ itemId: "belt", academicYear: "2026-27", amount: 10, effectiveFrom: "2026-07-15", effectiveTo: "2026-08-01" }))).rejects.toThrow(/overlapping/); });
  it("allows non-overlapping historical rates", async () => { const db = { miscIncomeRate: { findMany: async () => [{ effectiveFrom: new Date("2026-06-01Z"), effectiveTo: new Date("2026-06-30Z") }] } } as any; await expect(assertNoActiveRateOverlap(db, validateMiscRateInput({ itemId: "belt", academicYear: "2026-27", amount: 10, effectiveFrom: "2026-07-01" }))).resolves.toBeUndefined(); });
  it("calculates multiple-line totals on the server", async () => { const data = await validateMiscReceiptInput(client(), receipt({ lines: [{ itemId: "belt", quantity: 2, discountAmount: "0.25" }, { itemId: "belt", quantity: 1, discountAmount: "0" }] })); expect(data.grossAmount.toFixed(2)).toBe("300.75"); expect(data.discountAmount.toFixed(2)).toBe("0.25"); expect(data.netAmount.toFixed(2)).toBe("300.50"); expect(data.lines[0]).toMatchObject({ itemNameSnapshot: "Belt", rateId: "rate-1" }); });
  it("requires positive whole quantities", async () => { await expect(validateMiscReceiptInput(client(), receipt({ lines: [{ itemId: "belt", quantity: 1.5, discountAmount: 0 }] }))).rejects.toThrow(/positive whole number/); });
  it("does not allow a discount above line gross", async () => { await expect(validateMiscReceiptInput(client(), receipt({ lines: [{ itemId: "belt", quantity: 1, discountAmount: "101" }] }))).rejects.toThrow(/cannot exceed/); });
  it("enforces required student links", async () => { const required = [{ ...items[0], id: "tc", name: "Transfer Certificate", studentLinkPolicy: "REQUIRED" }]; await expect(validateMiscReceiptInput(client({ items: required }), receipt({ studentId: null, lines: [{ itemId: "tc", quantity: 1, discountAmount: 0 }] }))).rejects.toThrow(/student is required/i); });
  it("enforces NOT_REQUIRED student links", async () => { const unlinked = [{ ...items[0], studentLinkPolicy: "NOT_REQUIRED" }]; await expect(validateMiscReceiptInput(client({ items: unlinked }), receipt())).rejects.toThrow(/not requiring a student/i); });
  it("blocks mixed student-linked receipts containing a NOT_REQUIRED item", async () => { const mixed = [{ ...items[0], id: "tc", studentLinkPolicy: "REQUIRED" }, { ...items[0], id: "other", studentLinkPolicy: "NOT_REQUIRED" }]; await expect(validateMiscReceiptInput(client({ items: mixed }), receipt({ lines: [{ itemId: "tc", quantity: 1, discountAmount: 0 }, { itemId: "other", quantity: 1, discountAmount: 0 }] }))).rejects.toThrow(/not requiring a student/i); });
  it("requires a matching academic-year rate", async () => { const noRate = [{ ...items[0], rates: [{ ...rate, academicYear: "2025-26" }] }]; await expect(validateMiscReceiptInput(client({ items: noRate }), receipt())).rejects.toThrow(/exactly one active/); });
  it("binds offline receipts to the exact cached rate identity and version", async () => {
    const line = { itemId: "belt", expectedRateId: rate.id, expectedRateVersion: rate.updatedAt.toISOString(), quantity: 1, discountAmount: 0 };
    await expect(validateMiscReceiptInput(client(), receipt({ lines: [line] }), { requireExpectedRate: true })).resolves.toMatchObject({ lines: [{ rateId: rate.id }] });
    await expect(validateMiscReceiptInput(client(), receipt({ lines: [{ ...line, expectedRateVersion: new Date("2026-07-02T00:00:00.000Z").toISOString() }] }), { requireExpectedRate: true })).rejects.toThrow("MISC_INCOME_RATE_CHANGED");
    await expect(validateMiscReceiptInput(client(), receipt({ lines: [{ itemId: "belt", quantity: 1, discountAmount: 0 }] }), { requireExpectedRate: true })).rejects.toThrow("MISC_INCOME_RATE_PROOF_REQUIRED");
  });
  it("keeps online miscellaneous-income receipts backward compatible without offline rate proof", async () => {
    await expect(validateMiscReceiptInput(client(), receipt())).resolves.toMatchObject({ lines: [{ rateId: rate.id }] });
  });
  it("keeps cash free of transaction references", async () => { const data = await validateMiscReceiptInput(client(), receipt({ transactionReference: "SHOULD-DROP" })); expect(data.transactionReference).toBeNull(); expect(data.receivedAccount).toBe("CASH_COUNTER"); });
  it("always records physical cash against the cash counter", async () => { const data = await validateMiscReceiptInput(client(), receipt({ receivedAccount: "DIRECTOR_GPAY" })); expect(data.receivedAccount).toBe("CASH_COUNTER"); });
  it("requires references for UPI and bank modes", async () => { await expect(validateMiscReceiptInput(client(), receipt({ paymentMethod: "UPI", receivedAccount: "DIRECTOR_GPAY", transactionReference: "" }))).rejects.toThrow(/reference is required/); const data = await validateMiscReceiptInput(client(), receipt({ paymentMethod: "BANK_TRANSFER", receivedAccount: "NPS_CURRENT_ACCOUNT", transactionReference: "BANK-1" })); expect(data.transactionReference).toBe("BANK-1"); });
  it("submits received-account enum values rather than display labels", () => { const source = readFileSync("components/misc-income-form.tsx", "utf8"); expect(source).toContain('<option key={value} value={value}>{value.replaceAll("_", " ")}</option>'); });
  it("requires cheque details consistently", async () => { await expect(validateMiscReceiptInput(client(), receipt({ paymentMethod: "CHEQUE", receivedAccount: "NPS_CURRENT_ACCOUNT", chequeNumber: "" }))).rejects.toThrow(/Cheque number/); });
  it("excludes cancelled receipts from active report totals", () => { const rows: any[] = [{ receiptDate: new Date("2026-07-15Z"), status: "ACTIVE", paymentMethod: "CASH", receivedAccount: "CASH_COUNTER", netAmount: new Prisma.Decimal(100), student: null, lines: [{ itemNameSnapshot: "Belt", lineTotal: new Prisma.Decimal(100) }] }, { receiptDate: new Date("2026-07-15Z"), status: "CANCELLED", paymentMethod: "CASH", receivedAccount: "CASH_COUNTER", netAmount: new Prisma.Decimal(50), student: null, lines: [] }]; expect(miscIncomeReport(rows)).toMatchObject({ total: "100.00", cash: "100.00", nonCash: "0.00", cancelled: "50.00" }); });
  it("formula-protects exported CSV", () => { const csv = miscIncomeCsv([{ receiptNumber: "=cmd", receiptDate: new Date("2026-07-15Z"), status: "ACTIVE", student: null, payerName: "+payer", paymentMethod: "CASH", receivedAccount: "CASH_COUNTER", lines: [{ itemNameSnapshot: "@item" }], grossAmount: new Prisma.Decimal(1), discountAmount: new Prisma.Decimal(0), netAmount: new Prisma.Decimal(1) }]); expect(csv).toContain("'=cmd"); expect(csv).toContain("'+payer"); });
  it("hides sensitive references and actors from read-only serialization", () => { const row: any = { id: "r", receiptNumber: "MISC-1", receiptDate: new Date(), academicYear: "2026-27", student: null, payerName: "P", paymentMethod: "UPI", receivedAccount: "DIRECTOR_GPAY", transactionReference: "SECRET", grossAmount: new Prisma.Decimal(1), discountAmount: new Prisma.Decimal(0), netAmount: new Prisma.Decimal(1), status: "ACTIVE", cancelledAt: null, createdAt: new Date(), lines: [], createdBy: { name: "Actor" } }; const safe = serializeMiscReceipt(row, false); expect(safe).not.toHaveProperty("transactionReference"); expect(safe).not.toHaveProperty("createdBy"); });
  it("uses separate receipt numbering and models from fee Payment", () => { const schema = readFileSync("prisma/schema.prisma", "utf8"); expect(schema).toContain("model MiscIncomeReceipt"); expect(schema).toContain("receiptNumber"); expect(readFileSync("lib/misc-income.ts", "utf8")).toContain("MISC-"); expect(readFileSync("lib/misc-income.ts", "utf8")).not.toContain("client.payment.create"); });
  it("adds the complete conservative permission matrix", () => { for (const permission of ["VIEW_MISC_INCOME", "MANAGE_MISC_INCOME", "CANCEL_MISC_INCOME", "MANAGE_MISC_INCOME_ITEMS", "VIEW_MISC_INCOME_REPORTS", "EXPORT_MISC_INCOME_REPORTS"]) expect(PERMISSIONS).toContain(permission); expect(can("ACCOUNTANT", "MANAGE_MISC_INCOME")).toBe(true); expect(can("ACCOUNTANT", "CANCEL_MISC_INCOME")).toBe(false); expect(can("VIEWER", "VIEW_MISC_INCOME_REPORTS")).toBe(true); expect(can("TEACHER", "VIEW_MISC_INCOME")).toBe(false); expect(can("PARENT", "VIEW_MISC_INCOME")).toBe(false); });
  it("guards pages and direct APIs server-side", () => { expect(readFileSync("app/misc-income/page.tsx", "utf8")).toContain('requirePermission("VIEW_MISC_INCOME")'); expect(readFileSync("app/misc-income/new/page.tsx", "utf8")).toContain('requirePermission("MANAGE_MISC_INCOME")'); expect(readFileSync("app/api/misc-income/route.ts", "utf8")).toContain('requireApiPermission("MANAGE_MISC_INCOME")'); expect(readFileSync("app/api/misc-income/[id]/cancel/route.ts", "utf8")).toContain('requireApiPermission("CANCEL_MISC_INCOME")'); });
  it("does not return raw item creator IDs from the item API", () => { const source = readFileSync("app/api/misc-income/items/route.ts", "utf8"); expect(source).toContain("serializeMiscIncomeItem"); expect(source).not.toContain("NextResponse.json({ item: await prisma.miscIncomeItem"); });
  it("prints a public-safe, fee-separated receipt", () => { const source = readFileSync("app/misc-income/[id]/print/page.tsx", "utf8"); expect(source).toContain("Miscellaneous-Income Receipt"); expect(source).toContain("not part of the student fee ledger"); expect(source).not.toContain("createdByUserId"); });
  it("uses an explicit preserved-receipt cancellation confirmation", () => { const source = readFileSync("components/misc-receipt-actions.tsx", "utf8"); expect(source).toContain("Cancellation reason"); expect(source).toContain("Confirm cancellation"); expect(source).not.toContain("window.prompt"); });
});
