import { describe, expect, it } from "vitest";
import { PDFDocument } from "pdf-lib";
import { createBackupDocument } from "@/lib/backup";
import { validatePayrollBackupRows } from "@/lib/payroll-backup";
import { generatePayslipPdf } from "@/lib/payroll-pdf";
import { parseAndValidateBackup } from "@/lib/restore";

const snapshot={schema:"NALANDA_PAYSLIP_V1",school:{name:"Nalanda School",address:"School Road",city:"Hyderabad"},staff:{name:"PAY23I Employee With A Deliberately Long Name For Layout Verification",designation:"Teacher",department:"Academics"},payrollMonth:"2026-07",earnings:Array.from({length:28},(_,i)=>({code:`EARN_${i}`,name:`Governed earning component ${i+1}`,amountPaise:10_000+i})),deductions:[{code:"ADVANCE_RECOVERY",name:"Salary advance recovery",amountPaise:25_000}],reimbursements:[{code:"REIMBURSEMENT",name:"Approved reimbursement",amountPaise:5_000}],totals:{grossPaise:300_000,deductionPaise:25_000,reimbursementPaise:5_000,netPaise:280_000},attendance:{lockedInputRows:22,statuses:{PRESENT:21,ON_LEAVE:1}},issue:{version:1,issueDate:"2026-08-08",runReference:"PAY-2026-07-01"}};
describe("Prompt 23I payslips and backup",()=>{
  it("renders multi-page colour and monochrome private A4 PDFs",async()=>{for(const monochrome of [false,true]){const bytes=await generatePayslipPdf(snapshot,"PAYSLIP-2026-07-0001",monochrome),pdf=await PDFDocument.load(bytes);expect(Buffer.from(bytes).subarray(0,4).toString()).toBe("%PDF");expect(pdf.getPages().length).toBeGreaterThan(1);expect(pdf.getPages()[0].getSize()).toEqual(expect.objectContaining({width:expect.closeTo(595.28,1),height:expect.closeTo(841.89,1)}));}});
  it("includes all payroll entities in backup version 43",()=>{const backup=createBackupDocument({generatedAt:new Date("2026-08-08T00:00:00Z"),generatedBy:"PAY23I",students:[],feeStructures:[],payments:[],paymentAudits:[],users:[],payrollPolicyVersions:[{id:"policy-1"}],salaryStructureVersions:[{id:"structure-1",policyVersionId:"policy-1"}],salaryComponentDefinitions:[{id:"component-1",structureVersionId:"structure-1",componentCode:"BASIC",calculationMode:"FIXED",statutoryTreatment:"NOT_STATUTORY"}]});expect(backup.metadata.backupVersion).toBe(43);expect(backup.metadata.counts.payrollPolicyVersions).toBe(1);const parsed=parseAndValidateBackup(backup);expect(parsed.salaryStructureVersions).toHaveLength(1);expect(parsed.payslipVersions).toEqual([]);});
  it("refuses unapproved statutory rules and credential fields in payroll backup",()=>{const input:any={generatedAt:new Date(),generatedBy:"PAY23I",students:[],feeStructures:[],payments:[],paymentAudits:[],users:[],payrollPolicyVersions:[{id:"policy-1"}],salaryStructureVersions:[{id:"structure-1",policyVersionId:"policy-1"}],salaryComponentDefinitions:[{id:"component-1",structureVersionId:"structure-1",componentCode:"EPF",calculationMode:"PERCENTAGE",statutoryTreatment:"NOT_STATUTORY"}]};expect(()=>createBackupDocument(input)).toThrow(/statutory-looking/i);input.salaryComponentDefinitions[0]={id:"component-1",structureVersionId:"structure-1",componentCode:"BASIC",calculationMode:"FIXED",statutoryTreatment:"NOT_STATUTORY",bankAccount:"forbidden"};expect(()=>createBackupDocument(input)).toThrow(/prohibited/i);});
  it("validates optional history links and refuses a dangling recovery result",()=>{const input:any={payrollPolicyVersions:[{id:"policy-1"}],salaryStructureVersions:[{id:"structure-1",policyVersionId:"policy-1"}],salaryComponentDefinitions:[{id:"component-1",structureVersionId:"structure-1",componentCode:"BASIC",calculationMode:"FIXED",statutoryTreatment:"NOT_STATUTORY"}],staffCompensationAssignments:[{id:"assignment-1",structureVersionId:"structure-1"}],salaryRevisions:[{id:"revision-1",previousAssignmentId:null,newAssignmentId:"assignment-1"}],payrollPeriods:[{id:"period-1"}],payrollRuns:[{id:"run-1",periodId:"period-1",policyVersionId:"policy-1",sourceRunId:null}],employeePayrollResults:[{id:"result-1",payrollRunId:"run-1",compensationAssignmentId:"assignment-1",salaryRevisionId:null}],payrollComponentResults:[],salaryAdvances:[{id:"advance-1"}],advanceRecoverySchedules:[{id:"recovery-1",salaryAdvanceId:"advance-1",payrollPeriodId:null,employeePayrollResultId:"missing-result"}],payslipVersions:[],payrollEvents:[]};expect(()=>validatePayrollBackupRows(input)).toThrow(/employeePayrollResultId relationship/);input.advanceRecoverySchedules[0].employeePayrollResultId="result-1";expect(()=>validatePayrollBackupRows(input)).not.toThrow();});
});
