import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { RECOMMENDED_ROLE_PERMISSIONS } from "@/lib/permissions";
import { financePostingBoundary, payrollReports } from "@/lib/payroll";
const source=(file:string)=>readFileSync(path.join(process.cwd(),file),"utf8");
describe("Prompt 23I payroll governance and privacy",()=>{
  it("grants exact preparation and own-record boundaries",()=>{expect(RECOMMENDED_ROLE_PERMISSIONS.ACCOUNTANT.has("CALCULATE_PAYROLL")).toBe(true);expect(RECOMMENDED_ROLE_PERMISSIONS.ACCOUNTANT.has("APPROVE_PAYROLL")).toBe(false);expect(RECOMMENDED_ROLE_PERMISSIONS.PRINCIPAL.has("VIEW_PAYROLL")).toBe(false);expect(RECOMMENDED_ROLE_PERMISSIONS.ADMIN.has("VIEW_PAYROLL")).toBe(false);expect(RECOMMENDED_ROLE_PERMISSIONS.COMPUTER_OPERATOR.has("VIEW_PAYROLL")).toBe(false);expect(RECOMMENDED_ROLE_PERMISSIONS.TEACHER.has("VIEW_OWN_PAYROLL")).toBe(true);expect(RECOMMENDED_ROLE_PERMISSIONS.PARENT.has("VIEW_OWN_PAYROLL")).toBe(false);expect(RECOMMENDED_ROLE_PERMISSIONS.VIEWER.has("VIEW_PAYROLL_AGGREGATES")).toBe(false);});
  it("keeps finance and disbursement fail-closed",()=>{expect(financePostingBoundary()).toEqual(expect.objectContaining({postingAllowed:false,createsPayment:false,createsReceipt:false,createsExpense:false,createsCashMovement:false,createsBankTransfer:false}));expect(source("lib/payroll.ts")).not.toMatch(/\.payment\.(create|update)|\.cashBookMovement\.(create|update)|bank transfer provider|stripe/i);});
  it("uses private authorization and state-changing routes",()=>{for(const file of ["app/api/payroll/route.ts","app/api/payroll/runs/[publicKey]/calculate/route.ts","app/api/payroll/runs/[publicKey]/workflow/route.ts","app/api/payroll/advances/[publicKey]/workflow/route.ts","app/api/my-payroll/route.ts"])expect(source(file)).not.toContain("export async function DELETE");expect(source("lib/payroll-api.ts")).toContain("PAYROLL_PRIVATE_HEADERS");expect(source("lib/payroll.ts")).toContain('private, no-store');expect(source("app/api/my-payroll/payslips/[reference]/download/route.ts")).toContain("ownUserId: auth.user.id");expect(source("lib/payroll.ts")).toContain("staffMember.userId !== options.ownUserId");});
  it("has no public payroll route, PWA cache or AI transmission",()=>{expect(source("lib/access-rules.ts")).toContain('href: "/my-payroll"');expect(source("lib/permissions.ts")).not.toMatch(/PARENT[^\n]+VIEW_OWN_PAYROLL/);expect(source("lib/payroll.ts")).not.toMatch(/fetch\(|openai|anthropic|gemini/i);expect(source("lib/pwa-service-worker.ts")).not.toMatch(/payroll|payslip|salary/i);});
  it("suppresses every small-group monetary aggregate by unique Staff contributor",async()=>{const result=(id:string)=>({componentCode:"BASIC",componentName:"Basic salary",classification:"EARNING",amountPaise:100_000,employeePayrollResultId:id,employeePayrollResult:{staffMemberId:"staff-1",staffMember:{department:"Tiny Department"},payrollRun:{publicKey:"run-key",runNumber:"PAY-PRIVATE",status:"LOCKED"}}});const client:any={payrollRun:{findMany:async()=>[{publicKey:"run-key",runNumber:"PAY-PRIVATE",status:"LOCKED",employeeCount:1,exceptionCount:0,totalGrossPaise:100_000,totalDeductionPaise:5_000,totalReimbursementPaise:0,totalNetPaise:95_000,financePostingStatus:"DISABLED",period:{payrollMonth:"2026-07"},createdAt:new Date()}]},payrollComponentResult:{findMany:async()=>[result("result-1"),result("result-2"),result("result-3")]},salaryAdvance:{findMany:async()=>[{staffMemberId:"staff-1",status:"APPROVED",approvedAmountPaise:20_000,remainingBalancePaise:20_000},{staffMemberId:"staff-1",status:"APPROVED",approvedAmountPaise:10_000,remainingBalancePaise:10_000},{staffMemberId:"staff-1",status:"APPROVED",approvedAmountPaise:5_000,remainingBalancePaise:5_000},{staffMemberId:"staff-2",status:"CANCELLED",approvedAmountPaise:99_900,remainingBalancePaise:99_900}]},payslipVersion:{count:async()=>1},salaryRevision:{findMany:async()=>[]}};const full:any=await payrollReports(client);expect(full.advanceTotals.approvedAmount).toBe("₹350.00");expect(full.advanceTotals.remainingBalance).toBe("₹350.00");expect(full.advanceTotals.contributorCount).toBe(1);const report:any=await payrollReports(client,{aggregateOnly:true});expect(report.runs[0]).not.toHaveProperty("key");expect(report.runs[0]).not.toHaveProperty("number");expect(report.runs[0].net).toBe("Suppressed");expect(report.componentTotals[0].employeeCount).toBe(1);expect(report.componentTotals[0].amount).toBe("Suppressed");expect(report.departmentAggregates[0].employeeCount).toBe(1);expect(report.departmentAggregates[0].netAmount).toBe("Suppressed");expect(report.advanceTotals.approvedAmount).toBe("Suppressed");expect(report.revisionHistory).toEqual([]);expect(source("app/api/payroll/reports/route.ts")).toContain('auth.user?.role === "VIEWER"');});
  it("locks approved history with database triggers and CAS",()=>{const migration=source("prisma/migrations/20260808054148_payroll_payslips_employee_self_service/migration.sql");for(const trigger of ["SalaryStructureVersion_no_approved_update","SalaryRevision_no_update","EmployeePayrollResult_no_approved_update","PayrollComponentResult_no_approved_delete","PayslipVersion_no_update","PayrollEvent_no_delete"])expect(migration).toContain(trigger);expect(source("lib/payroll.ts")).toContain("version: run.version, status: run.status");expect(source("lib/payroll.ts")).toContain("Concurrent payroll workflow change was refused");});
});
