import { describe, expect, it } from "vitest";
import { calculateEmployeePayroll, PayrollCalculationError, roundPayrollAmount, type EmployeeCalculationInput, type PayrollComponentInput } from "@/lib/payroll-calculation";

const components: PayrollComponentInput[] = [
  { id:"basic-v1",componentCode:"BASIC",name:"Basic salary",classification:"EARNING",calculationMode:"FIXED",calculationRule:"STANDARD",defaultAmountPaise:3_100_000,prorationRule:"PRORATE_ELIGIBILITY",roundingRule:"NEAREST_PAISE",versionNumber:1 },
  { id:"allow-v1",componentCode:"ALLOWANCE",name:"Fixed allowance",classification:"EARNING",calculationMode:"FIXED",calculationRule:"STANDARD",defaultAmountPaise:620_000,prorationRule:"PRORATE_ELIGIBILITY",roundingRule:"NEAREST_PAISE",versionNumber:1 },
  { id:"bonus-v1",componentCode:"BONUS",name:"Percentage allowance",classification:"EARNING",calculationMode:"PERCENTAGE",calculationRule:"STANDARD",percentageBasisPoints:1_000,percentageBaseCode:"BASIC",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",versionNumber:1 },
  { id:"leave-v1",componentCode:"UNPAID_LEAVE",name:"Approved unpaid leave",classification:"DEDUCTION",calculationMode:"CALCULATED",calculationRule:"UNPAID_LEAVE_DEDUCTION",percentageBaseCode:"BASIC",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",versionNumber:1 },
  { id:"arrears-v1",componentCode:"ARREARS",name:"Approved arrears",classification:"EARNING",calculationMode:"MANUAL",calculationRule:"STANDARD",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",versionNumber:1 },
  { id:"advance-v1",componentCode:"ADVANCE_RECOVERY",name:"Salary advance recovery",classification:"DEDUCTION",calculationMode:"CALCULATED",calculationRule:"ADVANCE_RECOVERY",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",versionNumber:1 }
];
const base: EmployeeCalculationInput = { periodStart:new Date("2026-07-01T00:00:00Z"),periodEnd:new Date("2026-07-31T00:00:00Z"),eligibleFrom:new Date("2026-07-01T00:00:00Z"),eligibleTo:null,unpaidLeaveUnits:0,attendanceHalfDayUnits:0,halfDayRule:"NOT_CONFIGURED",components,manualAdjustments:[{componentCode:"ARREARS",amountPaise:50_000,reason:"Approved prior-period arrears",approvalReference:"PAY23I-ARREARS-1"}],advanceRecoveryPaise:25_000,structureReference:"STANDARD-v1",policyReference:"GENERAL-v1" };

describe("Prompt 23I deterministic payroll calculation",()=>{
  it("hand-calculates fixed, percentage, arrears and recovery totals",()=>{const result=calculateEmployeePayroll(base);expect(result.grossPaise).toBe(4_080_000);expect(result.deductionPaise).toBe(25_000);expect(result.netPaise).toBe(4_055_000);expect(result.formulaPreview.total).toBe("4080000 + 0 - 25000 = 4055000 paise");});
  it("prorates mid-month joining without overwriting the monthly structure",()=>{const result=calculateEmployeePayroll({...base,eligibleFrom:new Date("2026-07-16T00:00:00Z"),manualAdjustments:[],advanceRecoveryPaise:0});expect(result.eligibleDays).toBe(16);expect(result.components.find(x=>x.componentCode==="BASIC")?.amountPaise).toBe(1_600_000);expect(result.components.find(x=>x.componentCode==="ALLOWANCE")?.amountPaise).toBe(320_000);expect(result.grossPaise).toBe(2_080_000);});
  it("applies only approved unpaid-leave units with deterministic paise rounding",()=>{const result=calculateEmployeePayroll({...base,unpaidLeaveUnits:3,manualAdjustments:[],advanceRecoveryPaise:0});expect(result.components.find(x=>x.componentCode==="UNPAID_LEAVE")?.amountPaise).toBe(150_000);expect(result.netPaise).toBe(3_880_000);});
  it("refuses a half-day deduction when no approved rule exists",()=>{expect(()=>calculateEmployeePayroll({...base,attendanceHalfDayUnits:1})).toThrowError(expect.objectContaining({code:"HALF_DAY_RULE_MISSING"}));});
  it("applies a half-day deduction only when the approved policy configures it",()=>{const result=calculateEmployeePayroll({...base,halfDayRule:"HALF_DAY_AS_0_5",attendanceHalfDayUnits:1,components:[components[0],{componentCode:"ATTENDANCE_DEDUCTION",name:"Approved half-day deduction",classification:"DEDUCTION",calculationMode:"CALCULATED",calculationRule:"ATTENDANCE_DEDUCTION",percentageBaseCode:"BASIC",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE"}],manualAdjustments:[],advanceRecoveryPaise:0});expect(result.deductionPaise).toBe(50_000);expect(result.netPaise).toBe(3_050_000);});
  it("preserves explicit zero values without inventing earnings or deductions",()=>{const result=calculateEmployeePayroll({...base,components:[{componentCode:"BASIC",name:"Basic salary",classification:"EARNING",calculationMode:"FIXED",defaultAmountPaise:0}],manualAdjustments:[],advanceRecoveryPaise:0});expect(result.grossPaise).toBe(0);expect(result.deductionPaise).toBe(0);expect(result.netPaise).toBe(0);});
  it("blocks silently invented statutory formulas",()=>{expect(()=>calculateEmployeePayroll({...base,components:[{componentCode:"EPF",name:"EPF deduction",classification:"DEDUCTION",calculationMode:"PERCENTAGE",percentageBasisPoints:1200,percentageBaseCode:"BASIC"}]})).toThrowError(expect.objectContaining({code:"STATUTORY_RULE_BLOCKED"}));expect(()=>calculateEmployeePayroll({...base,components:[components[0],{componentCode:"EPF",name:"EPF deduction",classification:"DEDUCTION",calculationMode:"MANUAL",statutoryTreatment:"MANUAL_OR_EXTERNALLY_APPROVED"}],manualAdjustments:[{componentCode:"EPF",amountPaise:1_000,reason:"Externally approved manual value",approvalReference:"LEGAL-REVIEW-1"}]})).not.toThrow();});
  it("refuses unapproved adjustment codes, over-deduction and invalid rounding",()=>{expect(()=>calculateEmployeePayroll({...base,manualAdjustments:[{componentCode:"RANKING_BONUS",amountPaise:1,reason:"Marks",approvalReference:"NO"}]})).toThrow(/not an approved component/i);expect(()=>calculateEmployeePayroll({...base,advanceRecoveryPaise:9_000_000})).toThrowError(expect.objectContaining({code:"NEGATIVE_NET_PAY"}));expect(roundPayrollAmount(149,"NEAREST_RUPEE")).toBe(100);expect(roundPayrollAmount(151,"CEIL_RUPEE")).toBe(200);expect(()=>roundPayrollAmount(-1,"NEAREST_PAISE")).toThrow(PayrollCalculationError);});
});
