import {it,expect,vi,describe} from "vitest";
import {Readable} from "node:stream";
import {financeBrowser,financeUiResponse,financeDownload,interruptFinanceResponse,assertFinancePrint} from "../scripts/portable/finance-browser";
import {financeProbeScope,financeUsername} from "../scripts/portable/finance-browser-probe";
import {assertSale,assertFinanceScope,assertFinanceDecision,assertFinanceUnchanged,assertFinanceRead,assertIncomePrivacy,assertFinanceCsv,type FinanceState} from "../scripts/portable/finance-browser-assertions";

const base=():FinanceState=>({scope:"synthetic-fb-test",studentId:"s",academicYear:"2026-27",students:[{id:"s",admissionNo:"synthetic-fb-test",studentName:"SYNTHETIC",className:"VI",section:"A",discountPercent:10}],enrollments:[],fees:[{id:"fee",termAmount:1000}],currentYear:{annual:"3600.00",paid:"100.00",remaining:"3500.00"},payments:[{id:"p",studentId:"s",amountPaid:100,feeType:"Current Year Fee"}],receipts:[],liabilities:[],cases:[],events:[],attributions:[],income:[],cash:[],cashDays:[],rates:[],balances:[]});
const saleExpected={actor:"a",studentId:"s",itemId:"i",rateId:"r",rate:"10.25",quantity:3,total:"30.75",date:"2026-05-01"};
function sold(){const b=base();return {...b,receipts:[{id:"receipt",studentId:"s",createdByUserId:"a",academicYear:"2026-27",status:"ACTIVE",paymentMethod:"CASH",receivedAccount:"CASH_COUNTER",receiptDate:"2026-05-01T00:00:00.000Z",grossAmount:"30.75",netAmount:"30.75",discountAmount:"0",lines:[{itemId:"i",rateId:"r",quantity:3,unitAmount:"10.25",lineTotal:"30.75",discountAmount:"0"}],studentSnapshot:{studentId:"s",academicYear:"2026-27",admissionNo:b.scope,studentName:"SYNTHETIC",className:"VI",section:"A",linesJson:JSON.stringify([{itemId:"i",rateId:"r",quantity:3,unitAmount:"10.25",amount:"30.75"}])}}]};}
describe("UNIT_OR_DRIVER_CONTRACT: private finance assertions, no rendered ERP",()=>{
 it("accepts a real-shaped sale and rejects wrong actor/Student/year/quantity/rate/total and duplicate effects",()=>{
  const b=base(),a=sold();expect(()=>assertSale(b,a,saleExpected)).not.toThrow();
  for(const patch of [{createdByUserId:"wrong"},{studentId:"wrong"},{academicYear:"2025-26"},{netAmount:"37.50"},{status:"CANCELLED"}])expect(()=>assertSale(b,{...a,receipts:[{...a.receipts[0],...patch}]},saleExpected)).toThrow();
  for(const patch of [{quantity:4},{rateId:"other"},{unitAmount:"12.50"},{lineTotal:"37.50"}])expect(()=>assertSale(b,{...a,receipts:[{...a.receipts[0],lines:[{...a.receipts[0].lines[0],...patch}]}]},saleExpected)).toThrow();
  expect(()=>assertSale(b,{...a,receipts:[...a.receipts,{...a.receipts[0],id:"duplicate"}]},saleExpected)).toThrow();expect(()=>assertSale(b,b,saleExpected)).toThrow();
 });
 it("rejects current-year fee/payment/Student-discount changes and altered frozen receipt",()=>{
  const b=base(),a=sold();for(const patch of [{fees:[]},{payments:[]},{students:[{...a.students[0],discountPercent:100}]}])expect(()=>assertSale(b,{...a,...patch},saleExpected)).toThrow();expect(()=>assertFinanceUnchanged(a,{...a,receipts:[{...a.receipts[0],netAmount:"37.5"}]})).toThrow();
 });
 it("requires a scoped actor/target/action audit with version transition, never unrelated global events",()=>{
  const b=base();b.liabilities=[{id:"l",studentId:"s",operatingYear:"2026-27",sourceYear:"2025-26"}];b.cases=[{id:"c",liabilityId:"l",preparerId:"prep",status:"SUBMITTED",version:2}];
  const event={id:"e",actorId:"review",caseId:"c",liabilityId:"l",requestKey:"key",requestHash:"a".repeat(64),eventType:"CASE_UNDER_REVIEW",previousState:"SUBMITTED",newState:"UNDER_REVIEW"};const a={...b,cases:[{...b.cases[0],status:"UNDER_REVIEW",version:3,reviewerId:"review"}],events:[event]};const run=(v:FinanceState)=>assertFinanceDecision(b,v,"REVIEW","review",{action:"REVIEW",caseId:"c",expectedVersion:2,requestKey:"key"},{eventId:"e"});expect(()=>run(a)).not.toThrow();
  for(const patch of [{actorId:"wrong"},{caseId:"other"},{liabilityId:"other"},{eventType:"CASE_APPROVED"},{requestKey:"other"}])expect(()=>run({...a,events:[{...event,...patch}]})).toThrow();
  expect(()=>run({...a,events:[]})).toThrow();expect(()=>run({...a,cases:[{...a.cases[0],version:2}]})).toThrow();
 });
 it("reversal must link the sole original application and restore the exact amount",()=>{
  const b=base();b.liabilities=[{id:"l",studentId:"s",sourceYear:"2025-26",operatingYear:"2026-27",version:3}];b.cases=[{id:"c",liabilityId:"l",status:"APPLIED",version:5,approvedAmount:"300"}];b.events=[{id:"applied",caseId:"c",liabilityId:"l",eventType:"RELIEF_APPLIED",amount:"300"}];b.balances=[{liabilityId:"l",status:"VERIFIED",remaining:"450"}];
  const event={id:"reverse",caseId:"c",liabilityId:"l",actorId:"a",requestKey:"k",requestHash:"b".repeat(64),eventType:"RELIEF_REVERSED",previousState:"APPLIED",newState:"REVERSED",amount:"300",reversesEventId:"applied"};const a={...b,liabilities:[{...b.liabilities[0],version:4}],cases:[{...b.cases[0],status:"REVERSED",version:6}],events:[...b.events,event],balances:[{liabilityId:"l",status:"VERIFIED",remaining:"750"}]};
  const run=(s:FinanceState)=>assertFinanceDecision(b,s,"REVERSE","a",{action:"REVERSE",caseId:"c",expectedVersion:5,requestKey:"k"},{eventId:"reverse"});expect(()=>run(a)).not.toThrow();expect(()=>run({...a,events:[...b.events,{...event,reversesEventId:"foreign"}]})).toThrow();expect(()=>run({...a,balances:[{...a.balances[0],remaining:"700"}]})).toThrow();
 });
 it("read audits distinguish exact/general/export and reject extra business writes or private disclosure",()=>{
  const b=base();b.liabilities=[{id:"l",studentId:"s",operatingYear:"2026-27",sourceYear:"2025-26"}];b.cases=[{id:"c",liabilityId:"l"}];const a={...b,events:[{id:"e",caseId:"c",liabilityId:"l",actorId:"a",eventType:"INCOME_VIEWED",previousState:null,newState:null}]};expect(()=>assertFinanceRead(b,a,"a","c",["INCOME_VIEWED"])).not.toThrow();expect(()=>assertFinanceRead(b,a,"a","c",["EXACT_INCOME_VIEWED"])).toThrow();expect(()=>assertFinanceRead(b,{...a,cash:[{id:"unexpected"}]},"a","c",["INCOME_VIEWED"])).toThrow();expect(()=>assertIncomePrivacy("SYNTHETIC_PRIVATE_VALUE",["SYNTHETIC_PRIVATE_VALUE"])).toThrow();
 });
 it.each(["source","runId","attempt"])("rejects changed %s and wrong readback target",key=>{const cap={source:"a".repeat(40),runId:"123",attempt:"1"},input={...cap,iteration:"12345678-1234-1234-1234-123456789012"};expect(financeProbeScope(input,cap)).toMatch(/^synthetic-fb-/);expect(()=>financeProbeScope({...input,[key]:"wrong"},cap)).toThrow();expect(()=>assertFinanceScope(base(),"wrong","s")).toThrow();expect(financeUsername(base().scope,"preparer")).toMatch(/^[a-z0-9._-]{3,64}$/);});
});
it("UNIT_OR_DRIVER_CONTRACT: listens before UI click; exact denial fails on wrong reason,500,success,rate limit",async()=>{
 const order:string[]=[],make=(status:number,error:string)=>({url:()=>"https://portable-staging.localhost:8443/api/prior-year-concessions",status:()=>status,request:()=>({method:()=>"POST",postDataJSON:()=>({action:"REVIEW"})}),headers:()=>({"content-type":"application/json"}),body:async()=>Buffer.from(JSON.stringify({error}))});let response=make(403,"PRIOR_YEAR_PERMISSION_DENIED");const page={waitForResponse:async(fn:any)=>{order.push("listen");expect(fn(response)).toBe(true);return response;}};await financeUiResponse(page,"/api/prior-year-concessions",async()=>{order.push("click");},403,"PRIOR_YEAR_PERMISSION_DENIED");expect(order).toEqual(["listen","click"]);
 for(const [status,error] of [[200,"ok"],[400,"malformed"],[409,"CASE_VERSION_CHANGED"],[500,"failure"],[429,"limit"],[403,"wrong"]] as const){response=make(status,error);await expect(financeUiResponse(page,"/api/prior-year-concessions",async()=>{},403,"PRIOR_YEAR_PERMISSION_DENIED")).rejects.toThrow();}
});
it("UNIT_OR_DRIVER_CONTRACT: failed download still deletes owned temporary bytes",async()=>{const order:string[]=[],download={suggestedFilename:()=>"previous-year-case-review.csv",createReadStream:async()=>Readable.from([Buffer.from("SYNTHETIC")]),failure:async()=>"interrupted",delete:async()=>{order.push("delete");}};const page={waitForEvent:async()=>{order.push("listen");return download;}};await expect(financeDownload(page,{click:async()=>{order.push("click");}})).rejects.toThrow();expect(order).toEqual(["listen","click","delete"]);});
it("UNIT_OR_DRIVER_CONTRACT: response interruption requires actual200 exact case; always releases CDP",async()=>{
 let handler:any;const calls:string[]=[],cdp={on:(_name:string,fn:any)=>{handler=fn;},send:async(name:string)=>{calls.push(name);},detach:async()=>{calls.push("detach");}},page={context:()=>({newCDPSession:async()=>cdp})};const request={action:"APPLY",caseId:"c",requestKey:"private-key"};
 const action=async()=>{await handler({requestId:"id",request:{url:"https://portable-staging.localhost:8443/api/prior-year-concessions",method:"POST",postData:JSON.stringify(request)},responseStatusCode:200});};expect(await interruptFinanceResponse(page,"c",action)).toEqual(request);expect(calls).toEqual(["Fetch.enable","Fetch.failRequest","Fetch.disable","detach"]);
 calls.length=0;await expect(interruptFinanceResponse(page,"wrong",action)).rejects.toThrow("INTERRUPTION_REFUSED");expect(calls).toEqual(["Fetch.enable","Fetch.disable","detach"]);
});
it("UNIT_OR_DRIVER_CONTRACT: missing rendered control closes owned context and cannot report pass",async()=>{
 const close=vi.fn(),context={on:()=>{},route:async()=>{},addInitScript:async()=>{},newPage:async()=>({on:()=>{},goto:async()=>{},getByLabel:()=>{throw Error("MISSING_CONTROL");}}),close};const browser={newContext:async()=>context};const b=base();b.payments.push({...b.payments[0],id:"prior",feeType:"Old Due"});
 await expect(financeBrowser(browser,{origin:"https://portable-staging.localhost:8443",password:"HARNESS_FIXTURE_ONLY",source:"a".repeat(40),runId:"123",attempt:"1",bind:()=>{},probe:async(input:any)=>input.operation==="prepare"?{scope:b.scope,studentId:"s",actors:{preparer:{username:"synthetic"}}}:b})).rejects.toThrow("MISSING_CONTROL");expect(close).toHaveBeenCalledTimes(1);
 close.mockRejectedValueOnce(Error("close failed"));await expect(financeBrowser(browser,{origin:"https://portable-staging.localhost:8443",password:"HARNESS_FIXTURE_ONLY",source:"a".repeat(40),runId:"123",attempt:"1",bind:()=>{},probe:async(input:any)=>input.operation==="prepare"?{scope:b.scope,studentId:"s",actors:{preparer:{username:"synthetic"}}}:b})).rejects.toThrow("CLEANUP_FAILED");
});
it("UNIT_OR_DRIVER_CONTRACT: print refuses substituted font and missing platform-font facility",async()=>{
 const h={waitFor:async()=>{},evaluate:async()=>true},p={content:async()=>"<html>SYNTHETIC</html>",locator:()=>({waitFor:async()=>{},innerText:async()=>"R SYNTHETIC 10.25 30.75 This is a non-fee school-income receipt",count:async()=>1,locator:()=>({allInnerTexts:async()=>["SYNTHETIC item","3","₹10.25","₹0.00","₹30.75"]})}),getByRole:()=>h,context:()=>({newCDPSession:async()=>{throw Error("CDP_FONT_TOOL_MISSING");}})};
 await expect(assertFinancePrint(p,{receiptNumber:"R",studentName:"SYNTHETIC",itemName:"SYNTHETIC item",rate:"10.25",total:"30.75",incomeCanary:"PRIVATE"})).rejects.toThrow("CDP_FONT_TOOL_MISSING");h.evaluate=async()=>false;await expect(assertFinancePrint(p,{receiptNumber:"R",studentName:"SYNTHETIC",itemName:"SYNTHETIC item",rate:"10.25",total:"30.75",incomeCanary:"PRIVATE"})).rejects.toThrow("FONT_STYLE");
});
it("UNIT_OR_DRIVER_CONTRACT: downloaded CSV must have exact columns, scoped row and values",()=>{
 const raw="Case,Student reference,Source year,Operating year,Status,Requested,Approved,Previous-year remaining\r\nc,s,2025-26,2026-27,DRAFT,300.00,,750.00\r\n",expected={caseId:"c",studentId:"s",status:"DRAFT",requested:"300.00",approved:"",remaining:"750.00",includeIncome:false,incomeCanary:"PRIVATE_INCOME"};expect(()=>assertFinanceCsv(Buffer.from(raw),expected)).not.toThrow();
 for(const changed of [raw.replace("750.00","450.00"),raw.replace("c,s,","c,wrong,"),raw.replace("2025-26","2024-25"),raw+"c,s,2025-26,2026-27,DRAFT,300.00,,750.00\r\n",raw.replace("remaining","remaining,Exact annual INR"),raw+"PRIVATE_INCOME"])expect(()=>assertFinanceCsv(Buffer.from(changed),expected)).toThrow();
});
it("UNIT_OR_DRIVER_CONTRACT: independent liability verifier and approval actor cannot be substituted",()=>{
 const b=base();b.liabilities=[{id:"l",studentId:"s",operatingYear:"2026-27",sourceYear:"2025-26",status:"SOURCE_YEAR_UNVERIFIED",version:1,preparerId:"prep"}];const event={id:"e",liabilityId:"l",caseId:null,eventType:"ATTRIBUTION_VERIFIED",actorId:"review",requestKey:"k",requestHash:"a".repeat(64),previousState:null,newState:"VERIFIED"};const a={...b,liabilities:[{...b.liabilities[0],status:"VERIFIED",version:2,verifierId:"review",verifiedAt:"2026-05-01"}],events:[event]};const run=(s:FinanceState)=>assertFinanceDecision(b,s,"VERIFY","review",{action:"VERIFY",liabilityId:"l",requestKey:"k",paymentIds:[]},{eventId:"e"});expect(()=>run(a)).not.toThrow();expect(()=>run({...a,liabilities:[{...a.liabilities[0],verifierId:"prep"}]})).toThrow();expect(()=>run({...a,liabilities:[{...a.liabilities[0],verifiedAt:null}]})).toThrow();
 const prior={...a,cases:[{id:"c",liabilityId:"l",status:"UNDER_REVIEW",version:3,preparerId:"prep",reviewerId:"review",requestedAmount:"300"}]};const approved={...prior,cases:[{...prior.cases[0],status:"APPROVED",version:4,approverId:"review",approvedAmount:"300"}],events:[...prior.events,{id:"approve",liabilityId:"l",caseId:"c",eventType:"CASE_APPROVED",actorId:"review",requestKey:"a",requestHash:"b".repeat(64),previousState:"UNDER_REVIEW",newState:"APPROVED",amount:"300"}]};expect(()=>assertFinanceDecision(prior,approved,"APPROVE","review",{action:"APPROVE",caseId:"c",expectedVersion:3,requestKey:"a",approvedAmount:"300"},{eventId:"approve"})).toThrow("APPROVAL_ACTOR");
});
