import {beforeAll,afterAll,it,expect,vi} from "vitest";
import {PrismaClient} from "@prisma/client";
import {randomUUID} from "node:crypto";
import {mkdtempSync,rmSync,readFileSync,readdirSync,lstatSync,existsSync} from "node:fs";
import {DatabaseSync,backup} from "node:sqlite";
import {tmpdir} from "node:os";
import path from "node:path";
import {execFileSync} from "node:child_process";
import {financeBrowserProbe} from "../scripts/portable/finance-browser-probe";
import {defaultPermissionMatrix} from "../lib/role-permissions";
import {mutatePriorYear,readPriorYearIncome} from "../lib/prior-year-concessions";
import {createMiscReceipt} from "../lib/misc-income";
import {assertSale,assertFinanceDecision,assertFinanceUnchanged,assertFinanceRead} from "../scripts/portable/finance-browser-assertions";

// ISOLATED_SERVICE only: no server, artifact admission, or Browser authentication.
// Actual IAM grants are evaluated. Only runtime admission/MFA/step-up adapters
// are simulated; a harness proof cannot grant real application admission.
vi.mock("../scripts/portable/acceptance-http",()=>({assertSyntheticServingTarget:()=>{},provisionSyntheticMfa:async()=>{},nextTotp:async()=>{throw Error("HARNESS_HAS_NO_LOGIN");}}));
vi.mock("../lib/portable-runtime/synthetic-capability",()=>({syntheticFeatureCapability:()=>({source:"a".repeat(40),runId:"123",attempt:"1",features:["student-linked-items-1a","prior-year-concessions-1a"].map(key=>({key,version:1,environment:"PRODUCTION",activationRole:"SUPER_ADMIN"}))})}));
vi.mock("../lib/real-user-access/step-up",()=>({consumeStepUpGrant:async(_db:unknown,input:any)=>input.stepUpToken==="HARNESS_FIXTURE_ONLY"}));
vi.mock("../config/prior-year-concession-policy.json",()=>({default:{contract:"NALANDA_PRIOR_YEAR_CONCESSIONS_1A",version:1,academicYears:[2024,2025,2026,2027].map((y,i)=>({id:`${y}-${String(y+1).slice(-2)}`,sequence:i+1,startsOn:`${y}-04-01`,endsOn:`${y+1}-03-31`})),incomeBands:[{id:"SYNTHETIC_ONLY",label:"Synthetic acceptance band"}],incomeRetentionDays:30,scholarshipsEnabled:false}}));
const root=mkdtempSync(path.join(tmpdir(),"nalanda-finance-browser-service-")),identity=lstatSync(root),schema=`fb_${randomUUID().replaceAll("-","")}`,postgres=process.env.DATABASE_PROVIDER==="postgresql";let db:PrismaClient;
const bound={source:"a".repeat(40),runId:"123",attempt:"1",iteration:randomUUID()};
beforeAll(async()=>{
 let url="file:"+path.join(root,"synthetic.db").replaceAll("\\","/");
 if(postgres){expect(process.env.CI).toBe("true");expect(process.env.POSTGRES_READINESS_SYNTHETIC_QA).toBe("1");const target=new URL(process.env.DATABASE_URL!);target.searchParams.set("schema",schema);url=target.toString();execFileSync(process.execPath,["node_modules/prisma/build/index.js","migrate","deploy","--schema","prisma/postgresql/schema.prisma"],{env:{...process.env,DATABASE_URL:url,DIRECT_URL:url},stdio:"pipe"});}
 else{const sql=new DatabaseSync(":memory:");try{for(const migration of readdirSync("prisma/migrations",{withFileTypes:true}).filter(e=>e.isDirectory()).map(e=>e.name).sort())sql.exec(readFileSync(path.join("prisma/migrations",migration,"migration.sql"),"utf8"));expect(sql.prepare("PRAGMA foreign_key_check").all()).toEqual([]);expect(Object.values(sql.prepare("PRAGMA integrity_check").get()!)).toEqual(["ok"]);expect(existsSync(path.join(root,"synthetic.db"))).toBe(false);await backup(sql,path.join(root,"synthetic.db"));}finally{sql.close();}}
 db=new PrismaClient({datasourceUrl:url});vi.stubEnv("DATABASE_URL",url);vi.stubEnv("NODE_ENV","test");vi.stubEnv("AUTH_SECRET","SYNTHETIC-finance-contract-secret-only-000000");vi.stubEnv("AUTH_MFA_KEYRING_JSON",JSON.stringify({active:"SYNTHETIC",keys:{SYNTHETIC:Buffer.alloc(32,7).toString("base64")}}));vi.stubEnv("RELEASE_FEATURE_FLAGS_QA_MODE","SYNTHETIC_COPY_ONLY");vi.stubEnv("RELEASE_FEATURE_FLAGS_QA_ENABLED","student-linked-items-1a,prior-year-concessions-1a");
 await db.rolePermission.createMany({data:Object.entries(defaultPermissionMatrix()).flatMap(([role,entries])=>Object.entries(entries).map(([permission,enabled])=>({role,permission,enabled})))});
 await db.schoolSettings.create({data:{id:"school",schoolName:"NALANDA PUBLIC SCHOOL",academicYear:"2026-27",addressLine1:"SYNTHETIC",city:"SYNTHETIC",phone:"SYNTHETIC-NO-CONTACT"}});
},60_000);
afterAll(async()=>{if(db){if(postgres)await db.$executeRawUnsafe(`DROP SCHEMA "${schema}" CASCADE`);await db.$disconnect();}const current=lstatSync(root);expect(current.isSymbolicLink()).toBe(false);expect(current.ino).toBe(identity.ino);expect(current.dev).toBe(identity.dev);expect(path.dirname(path.resolve(root))).toBe(path.resolve(tmpdir()));rmSync(root,{recursive:true});expect(existsSync(root)).toBe(false);vi.unstubAllEnvs();});
it("ISOLATED_SERVICE: actual source-bound fixtures, item receipts, scoped waiver/reversal, income and stale authority",async()=>{
 const probe=(operation:string,extra:any={})=>financeBrowserProbe(db,{...bound,operation,...extra}),f:any=await probe("prepare",{password:"HARNESS_FIXTURE_ONLY_"+randomUUID()+randomUUID(),matrixIndex:0});
 const read=async()=>JSON.parse(JSON.stringify(await probe("snapshot"))),initial=await read();expect(initial.payments).toHaveLength(2);expect(initial.receipts).toEqual([]);expect(initial.cases).toEqual([]);await expect(probe("prepare",{password:"x".repeat(60),matrixIndex:0})).rejects.toThrow("FIXTURE_REUSE");
 const actors:Record<string,any>={};for(const [name,user] of Object.entries(f.actors) as [string,any][]){const session=await db.authSession.create({data:{userId:user.id,activeRoleAssignmentId:user.assignmentId,tokenHash:"HARNESS_"+randomUUID(),credentialVersion:1,authorizationVersion:1,expiresAt:new Date(Date.now()+3600000),deviceSummary:"HARNESS",browserSummary:"HARNESS",networkEvidenceMasked:"HARNESS"}});actors[name]={userId:user.id,roleAssignmentId:user.assignmentId,sessionId:session.id};}
 const sale={receiptDate:f.firstDate,academicYear:f.academicYear,studentId:f.studentId,paymentMethod:"CASH",lines:[{itemId:f.itemId,quantity:3}]};let b=await read();await createMiscReceipt(db,sale,f.actors.preparer.id);assertSale(b,await read(),{actor:f.actors.preparer.id,studentId:f.studentId,itemId:f.itemId,rateId:f.firstRateId,rate:"10.25",quantity:3,total:"30.75",date:f.firstDate});
 const rate=await db.miscIncomeRate.create({data:{itemId:f.itemId,academicYear:f.academicYear,amount:"12.50",effectiveFrom:new Date(f.secondDate),effectiveTo:new Date(f.secondDate),notes:f.scope}});b=await read();await createMiscReceipt(db,{...sale,receiptDate:f.secondDate},f.actors.preparer.id);assertSale(b,await read(),{actor:f.actors.preparer.id,studentId:f.studentId,itemId:f.itemId,rateId:rate.id,rate:"12.50",quantity:3,total:"37.50",date:f.secondDate});
 for(const quantity of [0,-1,1.5,10001]){b=await read();await expect(createMiscReceipt(db,{...sale,lines:[{itemId:f.itemId,quantity}]},f.actors.preparer.id)).rejects.toThrow("positive whole number");assertFinanceUnchanged(b,await read());}
 const perform=async(name:string,action:string,extra:any={})=>{const request={action,requestKey:randomUUID(),reason:"SYNTHETIC governed service acceptance",stepUpToken:"HARNESS_FIXTURE_ONLY",...extra},before=await read(),result=await mutatePriorYear(db,actors[name],request);assertFinanceDecision(before,await read(),action,f.actors[name].id,request,result);return {request,result};};
 const source={liabilityId:"",studentId:f.studentId,operatingYear:f.academicYear,sourceYear:f.sourceYear,sourceEnrollmentId:f.sourceEnrollmentId,identityVerified:true,openingAmount:"1000",existingCredits:"50",sourceReferences:["SYNTHETIC source"],provenance:"SYNTHETIC independently reviewed"};
 for(const sourceYear of ["UNKNOWN","2026-27","2027-28","2024-25"]){b=await read();await expect(mutatePriorYear(db,actors.preparer,{...source,sourceYear,action:"PREPARE_LIABILITY",requestKey:randomUUID(),reason:"SYNTHETIC"})).rejects.toThrow();assertFinanceUnchanged(b,await read());}
 const liability=(await perform("preparer","PREPARE_LIABILITY",source)).result.liabilityId;await perform("reviewer","VERIFY",{liabilityId:liability,expectedVersion:1,identityVerified:true,balanceVerified:true,paymentIds:[f.priorPaymentId]});expect((await read()).balances[0].remaining).toBe("750.00");
 const details={liabilityId:liability,kind:"SCHOOL_WAIVER",requestedAmount:"300",applicantReference:"SYNTHETIC",validFrom:new Date(Date.now()-86400000).toISOString().slice(0,10),validTo:new Date(Date.now()+86400000*7).toISOString().slice(0,10)};
 const caseId=(await perform("preparer","PREPARE",details)).result.caseId!;const version=async(id=caseId)=>(await db.priorYearConcessionCase.findUniqueOrThrow({where:{id}})).version;
 for(const [status,amount] of [["UNKNOWN",null],["NOT_PROVIDED",null],["DECLINED",null],["PROVIDED","0.00"],["PROVIDED",f.incomeCanary]])await perform("preparer","INCOME",{caseId,expectedVersion:await version(),income:status==="PROVIDED"?{status,exactAnnualAmount:amount,period:"ANNUAL",currency:"INR"}:{status}});
 b=await read();expect((await readPriorYearIncome(db,actors.general,caseId)).exactAnnualAmount).toBeNull();assertFinanceRead(b,await read(),f.actors.general.id,caseId,["INCOME_VIEWED"]);b=await read();await expect(readPriorYearIncome(db,actors.general,caseId,true)).rejects.toThrow("PERMISSION_DENIED");assertFinanceUnchanged(b,await read());
 await perform("preparer","SUBMIT",{caseId,expectedVersion:await version()});await perform("reviewer","REVIEW",{caseId,expectedVersion:await version()});let balance=(await read()).balances[0];const approval={caseId,expectedVersion:await version(),balanceHash:balance.hash,balanceVersion:balance.version,approvedAmount:"300"};b=await read();await expect(mutatePriorYear(db,actors.preparer,{...approval,action:"APPROVE",requestKey:randomUUID(),reason:"SYNTHETIC",stepUpToken:"HARNESS_FIXTURE_ONLY"})).rejects.toThrow("NO_SELF_APPROVAL");assertFinanceUnchanged(b,await read());
 await perform("approver","APPROVE",approval);const applied=await perform("applier","APPLY",{caseId,expectedVersion:await version()});b=await read();expect(b.balances[0].remaining).toBe("450.00");expect(await mutatePriorYear(db,actors.applier,applied.request)).toEqual(applied.result);assertFinanceUnchanged(b,await read());balance=b.balances[0];await perform("reviewer","REVIEW_REVERSAL",{caseId,expectedVersion:await version(),balanceHash:balance.hash,balanceVersion:balance.version});await perform("approver","REVERSE",{caseId,expectedVersion:await version()});expect((await read()).balances[0].remaining).toBe("750.00");
 const promise=(await perform("preparer","PREPARE",{...details,kind:"SPONSORSHIP_PROMISE"})).result.caseId!;await perform("preparer","SUBMIT",{caseId:promise,expectedVersion:1});await perform("reviewer","REVIEW",{caseId:promise,expectedVersion:2});balance=(await read()).balances[0];await perform("approver","APPROVE",{caseId:promise,expectedVersion:3,approvedAmount:"300",balanceHash:balance.hash,balanceVersion:balance.version});b=await read();await expect(mutatePriorYear(db,actors.applier,{caseId:promise,expectedVersion:4,action:"APPLY",reason:"SYNTHETIC",requestKey:randomUUID(),stepUpToken:"HARNESS_FIXTURE_ONLY"})).rejects.toThrow("SPONSORSHIP_PROMISE_IS_NOT_MONEY_OR_WAIVER");assertFinanceUnchanged(b,await read());
 const stale=(await perform("preparer","PREPARE",details)).result.caseId!;await perform("preparer","SUBMIT",{caseId:stale,expectedVersion:1});await perform("reviewer","REVIEW",{caseId:stale,expectedVersion:2});balance=(await read()).balances[0];await perform("approver","APPROVE",{caseId:stale,expectedVersion:3,approvedAmount:"300",balanceHash:balance.hash,balanceVersion:balance.version});const received:any=await probe("received-payment-precondition");const proposal=(await perform("preparer","PROPOSE_PAYMENT",{liabilityId:liability,paymentId:received.paymentId,sourceYear:f.sourceYear,sourceEnrollmentId:f.sourceEnrollmentId,identityVerified:true})).result.eventId;balance=(await read()).liabilities[0];await perform("reviewer","VERIFY_PAYMENT",{liabilityId:liability,proposalEventId:proposal,sourceYear:f.sourceYear,sourceEnrollmentId:f.sourceEnrollmentId,identityVerified:true,expectedLiabilityVersion:balance.version});b=await read();await expect(mutatePriorYear(db,actors.applier,{caseId:stale,expectedVersion:4,action:"APPLY",reason:"SYNTHETIC",requestKey:randomUUID(),stepUpToken:"HARNESS_FIXTURE_ONLY"})).rejects.toThrow("STALE_APPROVAL");assertFinanceUnchanged(b,await read());expect(b.balances[0].remaining).toBe("725.00");
 const denied=(await perform("preparer","PREPARE",details)).result.caseId!;await perform("preparer","SUBMIT",{caseId:denied,expectedVersion:1});await probe("revoke-reviewer");b=await read();await expect(mutatePriorYear(db,actors.reviewer,{caseId:denied,expectedVersion:2,action:"REVIEW",requestKey:randomUUID(),reason:"SYNTHETIC valid request"})).rejects.toThrow("PERMISSION_DENIED");assertFinanceUnchanged(b,await read());expect(b.fees).toEqual(initial.fees);expect(b.students).toEqual(initial.students);expect(b.cash).toEqual([]);expect(b.receipts).toHaveLength(2);
},30_000);
