import {describe,it,expect} from "vitest";
import {existsSync,writeFileSync,readFileSync,unlinkSync} from "node:fs";
import path from "node:path";
import {pathToFileURL} from "node:url";
import {execFileSync} from "node:child_process";
import {generateKeyPairSync} from "node:crypto";
import {fixture} from "./helpers/product-contract-fixture";
import {verifyInputs,verifyProductionInputs,boundedJson} from "../scripts/portable/product-input-contract";
import {runProductBuildScan} from "../scripts/portable/product-build-scan";
import {startProductDaemon} from "../scripts/portable/producer-process";
import {hashBytes} from "../scripts/portable/artifact-handoff";

describe("HARNESS_ONLY authenticated draft contract and connected child/file caller",()=>{
 it.each([{recipeTail:"RUN corepack prepare pnpm@11.21.0 --activate\n"},{badNodeLayer:true},{badToolArchive:true}])("refuses unqualified recipe or false static byte association before build: %j",async options=>{const f=fixture(options);try{const r=await runProductBuildScan(f.workspace,f.verified(),f.get,f.harness());expect(r.complete).toBe(false);expect(r.processes.some(p=>p.stage==="build")).toBe(false);expect(r.inputDecision).toBe("REFUSED");}finally{f.dispose();}});
 it("runs the complete connected path exactly once, binds product reports and cleans its owned root",async()=>{
  const f=fixture();try{
   // The real Python adapter requires the same native identity as its Node caller.
   const resolved=JSON.parse(execFileSync(f.python,["-c","import json,sys;from pathlib import Path;print(json.dumps([str(Path(p).resolve()) for p in sys.argv[1:]]))",f.root,f.workspace],{encoding:"utf8",windowsHide:true}));
   expect(resolved).toEqual([f.root,f.workspace]);
   const result=await runProductBuildScan(f.workspace,f.verified(),f.get,f.harness());expect(result.failures).toEqual([]);expect(result.cleanupFailures).toEqual([]);expect(result.complete).toBe(true);expect(result.classification).toBe("HARNESS_ONLY");expect(result.inputDecision).toBe("INPUTS_VERIFIED_FOR_BUILD");expect(result.productDecision).toBe("BUILD_SCAN_ONLY_NOT_ADMITTED");expect(result.admitted).toBe(false);expect(result.runtimeAdmission).toBe("EXTERNAL_RUNTIME_BLOCKED");expect(result.cleanupComplete).toBe(true);for(const name of ["build","syft","trivy","grype"])expect(result.processes.filter(p=>p.stage===name)).toHaveLength(1);expect(Object.keys(result.reportHashes)).toHaveLength(4);expect(result.output?.configDigest).not.toBe(f.d.images.runtime.subject);expect(JSON.stringify(result)).not.toContain(f.root);}finally{f.dispose();}
 });
 it("production refuses a complete signed positive fixture before any child, regardless of environment strings",()=>{const f=fixture();try{const raw=f.envelope();expect(()=>verifyProductionInputs(raw,f.get)).toThrow("PRODUCTION_INPUT_TRUST_UNREGISTERED");let failure:any;try{execFileSync(process.execPath,["--import",pathToFileURL(path.resolve("node_modules/tsx/dist/loader.mjs")).href,path.resolve("scripts/portable/product-build-scan.ts")],{cwd:f.root,env:{...process.env,TSX_TSCONFIG_PATH:path.resolve("tsconfig.json"),PRODUCT_TEST_TRUST:f.policy.publicKey,PRODUCT_HARNESS:"true"},stdio:"pipe"});}catch(error){failure=error;}expect(failure).toBeTruthy();if(!existsSync(path.join(f.root,"backend-build-scan-result.json")))throw Error("HARNESS_CLI_RECEIPT_MISSING");const result=JSON.parse(readFileSync(path.join(f.root,"backend-build-scan-result.json"),"utf8"));expect(result.failure).toBe("PRODUCTION_INPUT_TRUST_UNREGISTERED");expect(result.processes).toEqual([]);}finally{f.dispose();}});
 it.each(["build-fail","startup","timeout","missing-output","malformed-output","disk","scanner-startup","wrong-platform","wrong-descriptor","unrelated","scanner-fail","malformed","missing-report","report-subject","finding"])("retains required failure for actual child/file scenario %s",async scenario=>{const f=fixture();try{const result=await runProductBuildScan(f.workspace,f.verified(),f.get,f.harness(scenario));expect(result.complete).toBe(false);expect(result.failures.length).toBeGreaterThan(0);expect(result.productDecision).toBe("FAILED");if(["scanner-fail","malformed","missing-report","report-subject","finding"].includes(scenario)){expect(result.reportHashes["grype.json"]).toMatch(/^[a-f0-9]{64}$/);expect(result.processes.find(p=>p.stage==="grype")?.exit).toBe(0);}if(scenario==="timeout"){expect(result.processes.find(p=>p.stage==="build")?.timedOut).toBe(true);if(process.platform==="win32")expect(result.cleanupComplete).toBe(false);}if(scenario==="scanner-startup")expect(result.reportHashes["trivy.json"]).toMatch(/^[a-f0-9]{64}$/);if(scenario==="malformed-output")expect(result.partialOutput["product.oci.tar"].sha256).toMatch(/^[a-f0-9]{64}$/);if(scenario==="startup")expect(result.processes.find(p=>p.stage==="build")?.startupFailed).toBe(true);}finally{f.dispose();}});
 it.each(["schema","unknown","bad-type","bad-hash","source","tree","architecture","attempt","run","job","subject","signer","runtime-node","builder-node","frontend","tool","threshold","stale-db","unresolved-node","scanner-nonzero","suppressed"])("refuses strict contract case %s before build",kind=>{const f=fixture();try{const d=f.d as any;
  const update=(id:string,fn:(x:any)=>void)=>{const x=JSON.parse(f.get(id).toString());fn(x);return f.put(x);};
  if(kind==="schema")d.contract="unknown";if(kind==="unknown")d.pass=true;if(kind==="bad-type")d.runId=123;if(kind==="bad-hash")d.tools.trivy.sha256="xyz";
  if(["source","tree","architecture","attempt","run","job"].includes(kind))d[kind==="run"?"runId":kind]=kind==="architecture"?"arm64":"wrong";
  if(kind==="runtime-node")d.images.runtime.node=null;if(kind==="builder-node")d.images.builder.node=d.images.runtime.node;if(kind==="frontend")delete d.images.frontend;if(kind==="tool")delete d.tools.buildctl;
  if(kind==="threshold")d.images.runtime.security.metadata=update(d.images.runtime.security.metadata,m=>m.trivy.severityThreshold="CRITICAL");
  if(kind==="stale-db")d.databases.grype.updatedAt="2000-01-01T00:00:00Z";
  if(kind==="unresolved-node")d.images.runtime.node=update(d.images.runtime.node,n=>{n.libraries[0].evidence=update(n.libraries[0].evidence,e=>e.unresolved=["CVE-2026-5435"]);});
  if(kind==="scanner-nonzero")d.images.runtime.security.processes=update(d.images.runtime.security.processes,p=>p.outcomes.trivy.exit=1);
  if(kind==="suppressed")d.images.runtime.security.grype=update(d.images.runtime.security.grype,g=>g.ignoredMatches=[{vulnerability:{severity:"High"}}]);
  const raw=f.envelope();if(kind==="subject")f.policy.subjectSha256="0".repeat(64);if(kind==="signer")f.policy.publicKey=generateKeyPairSync("ed25519").publicKey.export({format:"pem",type:"spki"}).toString();
  expect(()=>verifyInputs(raw,f.get,f.policy)).toThrow();expect(existsSync(path.join(f.workspace,"tmp"))).toBe(false);
 }finally{f.dispose();}});
 it("rejects duplicate keys, excessive depth/size and malformed JSON",()=>{for(const raw of ['{"x":1,"x":2}','{"x":{"y":1,"y":2}}','{"x":NaN}','{"x":1 2}','{"x":t rue}',"[".repeat(30)+"0"+"]".repeat(30)])expect(()=>boundedJson(Buffer.from(raw))).toThrow();expect(()=>boundedJson(Buffer.alloc(100),8)).toThrow();});
 it("rejects invalid UTF-8 and non-JSON whitespace without normalizing it",()=>{expect(()=>boundedJson(Buffer.from([123,34,120,34,58,34,255,34,125]))).toThrow();expect(()=>boundedJson(Buffer.from('{\u00a0"x":1}'))).toThrow();expect(boundedJson(Buffer.from(' {\n "x": 1\n} '))).toEqual({x:1});});
 it.each(["database-binding","missing-stdout","node-tool-binary","archive-binding","workflow","custody","unfixed","missing-report","db-metadata-missing","db-metadata-schema","db-file-duplicate","tool-policy","known-production-pin"])("rejects authenticated but insufficient evidence: %s",kind=>{const f=fixture();try{const d=f.d;const update=(id:string,fn:(x:any)=>void)=>{const x=JSON.parse(f.get(id).toString());fn(x);return f.put(x);};if(kind==="known-production-pin"){d.classification="HOSTED_PREBUILD_INPUTS";f.policy.classification="HOSTED_PREBUILD_INPUTS";for(const c of [...Object.values(d.images),...Object.values(d.tools)])c.security.processes=update(c.security.processes,p=>p.classification="HOSTED_PREBUILD_INPUTS");}if(kind==="tool-policy")f.policy.toolPins.buildctl.archiveSha256="a".repeat(64);if(kind==="db-metadata-missing")d.databases.trivy.files.pop();if(kind==="db-file-duplicate")d.databases.grype.files[1]=d.databases.grype.files[0];if(kind==="db-metadata-schema"){const row=d.databases.trivy.files[1];row.sha256=update(row.sha256,m=>m.Version=999);row.bytes=f.get(row.sha256).length;}if(kind==="database-binding")d.images.runtime.security.metadata=update(d.images.runtime.security.metadata,m=>m.trivy.databaseSha256="a".repeat(64));if(kind==="missing-stdout")f.blobs.delete(hashBytes(""));if(kind==="node-tool-binary")d.tools.node.node=update(d.tools.node.node!,n=>n.binarySha256=f.put("other node binary"));if(kind==="archive-binding")d.tools.buildctl.archive=update(d.tools.buildctl.archive,a=>a.executableSha256="a".repeat(64));if(kind==="workflow")d.workflow=".github/workflows/untrusted.yml";if(kind==="custody")d.custody.attempt="2";if(kind==="unfixed")d.images.runtime.security.trivy=update(d.images.runtime.security.trivy,t=>t.Results[0].Vulnerabilities=[{Severity:"HIGH",FixedVersion:""}]);if(kind==="missing-report")f.blobs.delete(d.images.runtime.security.grype);expect(()=>f.verified()).toThrow(kind==="known-production-pin"?"INPUT_EXISTING_BUILDKIT_PIN_MISMATCH":undefined);}finally{f.dispose();}});
 it.each(["clean-stop","early-exit","startup","timeout"])("captures a real harmless daemon process: %s",async kind=>{const f=fixture();try{const command={stage:"rootless-daemon",tool:kind==="startup"?path.join(f.root,"missing"):f.python,args:["-u","-c",kind==="early-exit"?"import sys;print('HARNESS_ONLY daemon diagnostic',file=sys.stderr);sys.exit(9)":"import time;print('HARNESS_ONLY daemon started',flush=True);time.sleep(30)"],timeoutMs:kind==="timeout"?200:10000};const daemon=await startProductDaemon(command,f.root,1);if(kind==="startup")await expect(daemon.ready).rejects.toThrow("PRODUCT_DAEMON_STARTUP_FAILED");else await daemon.ready;if(kind==="clean-stop"){await new Promise(r=>setTimeout(r,300));daemon.child.kill();}const receipt=await daemon.finish(kind==="clean-stop");expect(receipt.stage).toBe("rootless-daemon");expect(receipt.intentionalShutdown).toBe(kind==="clean-stop");expect(receipt.durationMs).toBeGreaterThanOrEqual(0);expect(receipt.stderrSha256).toMatch(/^[a-f0-9]{64}$/);if(kind==="early-exit"){expect(receipt.exit).toBe(9);expect(receipt.stderrBytes).toBeGreaterThan(0);}if(kind==="startup")expect(receipt.startupFailed).toBe(true);if(kind==="timeout")expect(receipt.timedOut).toBe(true);}finally{f.dispose();}});
 it("captures interruption and retains uncertain child resources",async()=>{const f=fixture();try{const h=f.harness("interrupt"),map=h.command,controller=new AbortController();h.signal=controller.signal;h.command=(command,root)=>{if(command.stage==="build")setTimeout(()=>controller.abort(),300);return map(command,root);};const r=await runProductBuildScan(f.workspace,f.verified(),f.get,h);expect(r.complete).toBe(false);expect(r.processes.find(p=>p.stage==="build")?.interrupted).toBe(true);if(process.platform==="win32")expect(r.cleanupFailures).toContain("PRODUCT_UNSETTLED_CHILD_ROOT_RETAINED");}finally{f.dispose();}});
 it("refuses a report replaced by a later scanner, retaining its original process hash",async()=>{const f=fixture();try{const h=f.harness(),map=h.command;h.command=(c,r)=>{if(c.stage==="grype"){const p=path.join(r,"trivy.json");writeFileSync(p,readFileSync(p,"utf8").replaceAll("HARNESS_ONLY","SUBSTITUTED"));}return map(c,r);};const r=await runProductBuildScan(f.workspace,f.verified(),f.get,h);expect(r.failures).toContain("PRODUCT_REPORT_SUBSTITUTED");expect(r.complete).toBe(false);expect(r.reportHashes["grype.json"]).toMatch(/^[a-f0-9]{64}$/);}finally{f.dispose();}});
 it("binds local OCI inputs and a deny-by-default source policy into the actual build command",async()=>{const f=fixture();try{const h=f.harness(),map=h.command;let seen=false;h.command=(c,r)=>{if(c.stage==="build"){seen=true;expect(c.args).toContain("force-network-mode=none");expect(c.args.filter(a=>a==="--oci-layout")).toHaveLength(3);expect(c.args).toContain("--source-policy-file");const p=JSON.parse(readFileSync(path.join(r,"source-policy.json"),"utf8"));expect(p.rules[0]).toEqual({action:"DENY",selector:{identifier:"*"}});expect(p.rules.filter((x:any)=>x.action==="ALLOW").every((x:any)=>/^(local|oci-layout):/.test(x.selector.identifier))).toBe(true);}return map(c,r);};const r=await runProductBuildScan(f.workspace,f.verified(),f.get,h);expect(seen).toBe(true);expect(r.complete).toBe(true);}finally{f.dispose();}});
 it.each(["evidence","source","context","output","scanner-bins","database","owner-missing","owner-foreign"])("refuses mutation or uncertain ownership: %s",async kind=>{const f=fixture();try{const verified=f.verified();if(kind==="evidence")f.blobs.set(f.d.images.runtime.config,Buffer.from("tampered"));if(kind==="source")writeFileSync(path.join(f.workspace,"package.json"),"tampered");const harness=f.harness();const map=harness.command;let changed=false;harness.command=(command,root)=>{if(!changed&&((kind==="context"&&command.stage==="build")||(["output","scanner-bins","database","owner-missing","owner-foreign"].includes(kind)&&command.stage==="syft"))){changed=true;if(kind==="context")writeFileSync(path.join(root,"context/package.json"),"tampered");if(kind==="scanner-bins")writeFileSync(path.join(root,"scanner-bins.json"),JSON.stringify({trivy:"untrusted",grype:"untrusted"}));if(kind==="database")writeFileSync(path.join(root,f.d.databases.trivy.file),"substituted");if(kind==="output")writeFileSync(path.join(root,"product.oci.tar"),"tampered");if(kind==="owner-missing")unlinkSync(path.join(root,"owner.json"));if(kind==="owner-foreign")writeFileSync(path.join(root,"owner.json"),"{}");}return map(command,root);};if(["evidence","source"].includes(kind)){await expect(runProductBuildScan(f.workspace,verified,f.get,harness)).rejects.toThrow();}else{const result=await runProductBuildScan(f.workspace,verified,f.get,harness);expect(result.complete).toBe(false);if(kind.startsWith("owner"))expect(result.cleanupComplete).toBe(false);}}finally{f.dispose();}});
});
