import { describe, expect, it } from "vitest";
import { can } from "@/lib/permissions";
import { resolveReportCardScope, requireReportCardTarget } from "@/lib/report-card-scope";
import { createBackupDocument } from "@/lib/backup";
import { parseAndValidateBackup } from "@/lib/restore";
import { validateReportCardBackupRows } from "@/lib/report-card-backup";

const emptyBackup=()=>createBackupDocument({generatedAt:new Date("2026-07-16T10:00:00Z"),generatedBy:"QA17C",students:[],feeStructures:[],payments:[],paymentAudits:[],users:[]});
function reportRows(){const definition={schemaVersion:1,type:"MARK_BASED",denominatorPolicy:"PRESENT_AND_ABSENT",includeAttendance:true,includeGuardianNames:true,approvalRoles:["CLASS_TEACHER","PRINCIPAL"],sections:["STUDENT_PROFILE","SUBJECT_RESULTS","TOTALS","ATTENDANCE","COMMENTS","APPROVALS"]};const snapshot={templateCode:"QA17C-T",name:"QA",reportType:"MARK_BASED",versionNumber:1,definition,printSettings:null,gradingScheme:{schemeCode:"QA17C-S",name:"QA",bands:[{gradeCode:"A",label:"A",minimumPercentage:"0",maximumPercentage:"100",displayOrder:1,remarks:null}]}};return{gradingSchemes:[{id:"s1",schemeCode:"QA17C-S",name:"QA",reportType:"MARK_BASED",status:"ACTIVE"}],gradeBands:[{id:"g1",gradingSchemeId:"s1",gradeCode:"A",label:"A",minimumPercentage:"0",maximumPercentage:"100",displayOrder:1}],reportCardTemplates:[{id:"t1",templateCode:"QA17C-T",name:"QA",reportType:"MARK_BASED",gradingSchemeId:"s1",status:"ACTIVE",templateDefinitionJson:JSON.stringify(definition),versionNumber:1}],reportCardBatches:[{id:"b1",batchNumber:"QA17C-B",academicYear:"2026-27",reportType:"MARK_BASED",templateId:"t1",className:"Class 5",section:"A",title:"QA",status:"ISSUED",templateSnapshotJson:JSON.stringify(snapshot)}],reportCardBatchExamSources:[{id:"x1",batchId:"b1",examCycleId:"e1",displayOrder:1}],studentReportCards:[{id:"c1",reportCardNumber:"QA17C-B-STU",batchId:"b1",studentId:"stu",academicYear:"2026-27",className:"Class 5",section:"A",reportType:"MARK_BASED",status:"ISSUED",currentVersionNumber:1,draftDataJson:JSON.stringify({kind:"MARK_BASED",calculation:{rows:[],blockingGaps:[]}})}],studentReportCardVersions:[{id:"v1",reportCardId:"c1",versionNumber:1,versionType:"ORIGINAL",snapshotJson:JSON.stringify({status:"ISSUED",versionNumber:1,reportType:"MARK_BASED",reportCardNumber:"QA17C-B-STU"}),issuedAt:"2026-07-16T10:00:00Z"}],studentReportCardEvents:[{id:"ev1",reportCardId:"c1",versionId:"v1",eventType:"ISSUED",eventDate:"2026-07-16T10:00:00Z"}]};}

describe("report-card permissions and exact Teacher scope",()=>{
  it("gives Director the full report-card permission set",()=>expect(can("DIRECTOR","CORRECT_ISSUED_REPORT_CARDS")).toBe(true));
  it("lets Principal approve and issue",()=>{expect(can("PRINCIPAL","APPROVE_REPORT_CARDS")).toBe(true);expect(can("PRINCIPAL","ISSUE_REPORT_CARDS")).toBe(true);});
  it("does not give Admin issue by default",()=>expect(can("ADMIN","ISSUE_REPORT_CARDS")).toBe(false));
  it("keeps Teacher entry and submit scoped without approval",()=>{expect(can("TEACHER","ENTER_REPORT_CARD_DATA")).toBe(true);expect(can("TEACHER","SUBMIT_REPORT_CARDS")).toBe(true);expect(can("TEACHER","APPROVE_REPORT_CARDS")).toBe(false);});
  it("gives Viewer masked reports but no export",()=>{expect(can("VIEWER","VIEW_REPORT_CARD_REPORTS")).toBe(true);expect(can("VIEWER","EXPORT_REPORT_CARD_REPORTS")).toBe(false);});
  it("blocks Accountant from report cards",()=>expect(can("ACCOUNTANT","VIEW_REPORT_CARDS")).toBe(false));
  it("gives Parent own-only access",()=>{expect(can("PARENT","VIEW_OWN_REPORT_CARDS")).toBe(true);expect(can("PARENT","VIEW_REPORT_CARDS")).toBe(false);});
  it("resolves exact timetable class and section targets",async()=>{const client:any={staffMember:{findUnique:async()=>({status:"ACTIVE",displayName:"Teacher",timetableTeacher:{isActive:true,assignments:[{academicYear:"2026-27",classSection:{isActive:true,className:"LKG",section:"A"},subject:{isActive:true,name:"English"},subjectId:"sub1"}]}})}};const scope=await resolveReportCardScope(client,{id:"u",role:"TEACHER"},"2026-27");expect(scope.targets[0]).toMatchObject({className:"LKG",section:"A",subjectNames:["English"]});expect(()=>requireReportCardTarget(scope,{academicYear:"2026-27",className:"LKG",section:"B"})).toThrow(/outside/);});
  it("grants no broad scope to an unlinked Teacher",async()=>{const scope=await resolveReportCardScope({staffMember:{findUnique:async()=>null}} as any,{id:"u",role:"TEACHER"});expect(scope).toMatchObject({broad:false,targets:[]});});
});

describe("backup version 26 and restore validation",()=>{
  it("writes backup version 38 and all report-card arrays",()=>{const b=emptyBackup();expect(b.metadata.backupVersion).toBe(38);expect(b).toMatchObject({gradingSchemes:[],gradeBands:[],reportCardTemplates:[],reportCardBatches:[],studentReportCards:[],studentReportCardVersions:[],studentReportCardEvents:[]});});
  it("continues excluding password hashes",()=>{const b=createBackupDocument({generatedAt:new Date(),generatedBy:"QA",students:[],feeStructures:[],payments:[],paymentAudits:[],users:[{id:"u",name:"User",passwordHash:"secret"}]});expect(JSON.stringify(b)).not.toContain("passwordHash");expect(JSON.stringify(b)).not.toContain("secret");});
  it("supports older backups without report-card arrays",()=>{const b:any=emptyBackup();for(const key of Object.keys(reportRows()))delete b[key];b.metadata.backupVersion=24;expect(parseAndValidateBackup(b).studentReportCards).toEqual([]);});
  it("validates exact report-card links and immutable versions",()=>expect(()=>validateReportCardBackupRows(reportRows() as any,{studentIds:new Set(["stu"]),examIds:new Set(["e1"]),progressionIds:new Set()})).not.toThrow());
  it("rejects a same-card duplicate version number",()=>{const rows:any=reportRows();rows.studentReportCardVersions.push({...rows.studentReportCardVersions[0],id:"v2"});expect(()=>validateReportCardBackupRows(rows,{studentIds:new Set(["stu"]),examIds:new Set(["e1"]),progressionIds:new Set()})).toThrow(/duplicate identity/);});
  it("rejects a report card attached to an unrelated Student",()=>expect(()=>validateReportCardBackupRows(reportRows() as any,{studentIds:new Set(["other"]),examIds:new Set(["e1"]),progressionIds:new Set()})).toThrow(/invalid batch or Student link/));
  it("rejects an invalid progression reference without mutating progression",()=>{const rows:any=reportRows();rows.studentReportCards[0].progressionDecisionId="p1";expect(()=>validateReportCardBackupRows(rows,{studentIds:new Set(["stu"]),examIds:new Set(["e1"]),progressionIds:new Set()})).toThrow(/progression reference/);});
  it("rejects mark batches without exactly one locked source identity",()=>{const rows:any=reportRows();rows.reportCardBatchExamSources=[];expect(()=>validateReportCardBackupRows(rows,{studentIds:new Set(["stu"]),examIds:new Set(["e1"]),progressionIds:new Set()})).toThrow(/exactly one exam source/);});
  it("requires every correction to supersede the immediately prior version",()=>{const rows:any=reportRows();rows.studentReportCards[0].currentVersionNumber=2;rows.studentReportCardVersions.push({id:"v2",reportCardId:"c1",versionNumber:2,versionType:"CORRECTION",correctionReason:"Fix",supersedesVersionId:"wrong",snapshotJson:JSON.stringify({status:"ISSUED",versionNumber:2,reportType:"MARK_BASED",reportCardNumber:"QA17C-B-STU"}),issuedAt:"2026-07-17T10:00:00Z"});expect(()=>validateReportCardBackupRows(rows,{studentIds:new Set(["stu"]),examIds:new Set(["e1"]),progressionIds:new Set()})).toThrow(/superseded-version link/);});
  it("rejects an event linked to another card's version",()=>{const rows:any=reportRows();rows.studentReportCards.push({...rows.studentReportCards[0],id:"c2",reportCardNumber:"QA17C-B-STU2",studentId:"stu2"});rows.studentReportCards[1].currentVersionNumber=1;rows.studentReportCardVersions.push({...rows.studentReportCardVersions[0],id:"v2",reportCardId:"c2",snapshotJson:JSON.stringify({status:"ISSUED",versionNumber:1,reportType:"MARK_BASED",reportCardNumber:"QA17C-B-STU2"})});rows.studentReportCardEvents[0].reportCardId="c2";expect(()=>validateReportCardBackupRows(rows,{studentIds:new Set(["stu","stu2"]),examIds:new Set(["e1"]),progressionIds:new Set()})).toThrow(/invalid card or version link/);});
  it("rejects an overlapping grading-scheme snapshot",()=>{const rows:any=reportRows();const snap=JSON.parse(rows.reportCardBatches[0].templateSnapshotJson);snap.gradingScheme.bands.push({gradeCode:"B",label:"B",minimumPercentage:"50",maximumPercentage:"90",displayOrder:2});rows.reportCardBatches[0].templateSnapshotJson=JSON.stringify(snap);expect(()=>validateReportCardBackupRows(rows,{studentIds:new Set(["stu"]),examIds:new Set(["e1"]),progressionIds:new Set()})).toThrow(/overlap/);});
});

