import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { can, PERMISSIONS } from "../lib/permissions";
import { leaveDate, localLeaveDateText, overlappingLeaveWarning, staffLeaveReportCsv, staffLeaveReportData, validateStaffLeaveInput } from "../lib/staff-leave";

const valid = { staffMemberId: "staff-1", leaveType: "CASUAL", startDate: "2026-07-01", endDate: "2026-07-03", reason: "Family work" };
describe("staff leave foundation", () => {
  it("creates valid draft and submitted values with inclusive days", () => { expect(validateStaffLeaveInput({ ...valid, reason: "" })).toMatchObject({ totalDays: 3, reason: "" }); expect(validateStaffLeaveInput(valid, { submitting: true })).toMatchObject({ leaveType: "CASUAL", totalDays: 3, reason: "Family work" }); });
  it("rejects invalid dates, blank submitted reasons, and multi-day half leave", () => { expect(() => validateStaffLeaveInput({ ...valid, endDate: "2026-06-30" })).toThrow("before start"); expect(() => validateStaffLeaveInput({ ...valid, reason: "" }, { submitting: true })).toThrow("Reason is required"); expect(() => validateStaffLeaveInput({ ...valid, leaveType: "HALF_DAY", halfDaySession: "FORENOON" })).toThrow("same date"); const half = validateStaffLeaveInput({ ...valid, leaveType: "HALF_DAY", startDate: "2026-07-01", endDate: "2026-07-01", halfDaySession: "AFTERNOON" }, { submitting: true }); expect(half.totalDays).toBe(0.5); });
  it("keeps school calendar dates stable without a previous-day UTC shift", () => { expect(leaveDate("2026-07-01").toISOString().slice(0,10)).toBe("2026-07-01"); expect(localLeaveDateText(new Date(2026, 6, 1, 0, 5))).toBe("2026-07-01"); });
  it("returns a clear overlapping leave warning without blocking", async () => { const warning = await overlappingLeaveWarning({ staffLeaveRequest: { count: async () => 2 } } as never, { staffMemberId: "staff-1", startDate: new Date(), endDate: new Date() }); expect(warning).toContain("2 pending or approved"); });
  it("uses requested role defaults", () => { for (const permission of ["VIEW_STAFF_LEAVE", "APPLY_STAFF_LEAVE", "MANAGE_STAFF_LEAVE", "APPROVE_STAFF_LEAVE", "VIEW_STAFF_LEAVE_REPORTS"]) expect(PERMISSIONS).toContain(permission); for (const role of ["SUPER_ADMIN", "DIRECTOR", "PRINCIPAL", "ADMIN"] as const) { expect(can(role, "VIEW_STAFF_LEAVE")).toBe(true); expect(can(role, "APPROVE_STAFF_LEAVE")).toBe(true); } expect(can("TEACHER", "VIEW_STAFF_LEAVE")).toBe(true); expect(can("TEACHER", "APPLY_STAFF_LEAVE")).toBe(true); expect(can("TEACHER", "MANAGE_STAFF_LEAVE")).toBe(false); expect(can("ACCOUNTANT", "VIEW_STAFF_LEAVE")).toBe(false); expect(can("PARENT", "VIEW_STAFF_LEAVE")).toBe(false); expect(can("VIEWER", "VIEW_STAFF_LEAVE_REPORTS")).toBe(true); expect(can("VIEWER", "VIEW_STAFF_LEAVE")).toBe(false); });
  it("enforces own-only teacher access and immutable approval workflow in API source", () => { const list=readFileSync("app/api/leave/staff/route.ts","utf8"); const detail=readFileSync("app/api/leave/staff/[id]/route.ts","utf8"); expect(list).toContain('ownStaffMemberId: manager ? null : linked?.id ?? "__unlinked__"'); expect(list).toContain("source.staffMemberId = linked.id"); expect(detail).toContain("You can only view your own leave requests"); expect(detail).toContain('existing.status !== "PENDING"'); expect(detail).toContain('existing.status !== "DRAFT"'); expect(detail).toContain("Rejection reason is required"); expect(detail).toContain("Cancellation reason is required"); expect(detail).toContain('["DRAFT", "PENDING"]'); });
  it("protects pages and export from parent/accountant defaults", () => { expect(readFileSync("app/leave/staff/page.tsx","utf8")).toContain('requirePermission("VIEW_STAFF_LEAVE")'); expect(readFileSync("app/leave/staff/reports/page.tsx","utf8")).toContain('requirePermission("VIEW_STAFF_LEAVE_REPORTS")'); expect(readFileSync("app/api/leave/staff/reports/export/route.ts","utf8")).toContain('requireApiPermission("VIEW_STAFF_LEAVE_REPORTS")'); });
  it("builds pending and approved reports and safe CSV", async () => { const rows=[{id:"1",staffMemberId:"s",requestedByUserId:null,leaveType:"SICK",startDate:new Date("2026-07-01"),endDate:new Date("2026-07-01"),halfDaySession:null,totalDays:1,reason:"=unsafe",status:"PENDING",substituteRequired:false,substituteNotes:null,approverUserId:null,approvedAt:null,rejectedAt:null,rejectionReason:null,cancelledByUserId:null,cancelledAt:null,cancellationReason:null,notes:null,createdAt:new Date(),updatedAt:new Date(),staffMember:{id:"s",staffCode:"T1",fullName:"Asha",displayName:null,designation:"Teacher"},requestedBy:null,approver:null,cancelledBy:null},{id:"2",staffMemberId:"s",requestedByUserId:null,leaveType:"CASUAL",startDate:new Date("2026-07-02"),endDate:new Date("2026-07-03"),halfDaySession:null,totalDays:2,reason:"Trip",status:"APPROVED",substituteRequired:true,substituteNotes:null,approverUserId:null,approvedAt:new Date(),rejectedAt:null,rejectionReason:null,cancelledByUserId:null,cancelledAt:null,cancellationReason:null,notes:null,createdAt:new Date(),updatedAt:new Date(),staffMember:{id:"s",staffCode:"T1",fullName:"Asha",displayName:null,designation:"Teacher"},requestedBy:null,approver:null,cancelledBy:null}]; const data=await staffLeaveReportData({staffLeaveRequest:{findMany:async()=>rows}} as never,{from:new Date("2026-07-01"),to:new Date("2026-07-31")}); expect(data.pending).toHaveLength(1);expect(data.approved).toHaveLength(1);expect(data.byType.SICK).toBe(1);expect(staffLeaveReportCsv(rows)).toContain("'=unsafe"); });
  it("adds My Leave without exposing all staff leave in the teacher portal", () => { const source=readFileSync("app/teacher/page.tsx","utf8");expect(source).toContain("My Leave");expect(source).toContain("You cannot see other staff leave");expect(source).toContain("No staff profile is linked"); });
  it("hides inaccessible management navigation from reports-only viewers and confirms final actions", () => { const reports=readFileSync("app/leave/staff/reports/page.tsx","utf8");expect(reports).toContain('permissionSetCan(permissions, "VIEW_STAFF_LEAVE")');expect(reports).toContain('canViewRequests ? <Link href="/leave/staff"');const form=readFileSync("components/staff-leave-form.tsx","utf8");expect(form).toContain('role="dialog"');expect(form).toContain('aria-modal="true"');expect(form).toContain('confirmAction("approve")');expect(form).toContain('confirmAction("reject")');expect(form).toContain('confirmAction("cancel")'); });
  it("blocks the new-request page for a custom view-only leave role", () => { const page=readFileSync("app/leave/staff/new/page.tsx","utf8");expect(page).toContain('if (!canManage && !canApply) redirect("/unauthorized")'); });
});
