import { readFileSync } from "node:fs"; import { describe, expect, it } from "vitest";
import { activeStaffMembers, localDateText, staffAttendanceReportCsv, staffAttendanceReportData, staffAttendanceTotals, validateStaffAttendanceRecords } from "../lib/staff-attendance";
describe("staff attendance foundation",()=>{
  it("supports every manual status, times, late minutes, and duplicate protection",()=>{const rows=validateStaffAttendanceRecords([{staffMemberId:"1",status:"PRESENT",checkInTime:"08:15",checkOutTime:"15:30"},{staffMemberId:"2",status:"ABSENT"},{staffMemberId:"3",status:"LATE",lateMinutes:"12"},{staffMemberId:"4",status:"HALF_DAY"},{staffMemberId:"5",status:"ON_LEAVE"},{staffMemberId:"6",status:"EXCUSED"}]);expect(staffAttendanceTotals(rows)).toEqual({PRESENT:1,ABSENT:1,LATE:1,HALF_DAY:1,ON_LEAVE:1,EXCUSED:1,total:6});expect(rows[0]).toMatchObject({checkInTime:"08:15",checkOutTime:"15:30",source:"MANUAL"});expect(rows[2].lateMinutes).toBe(12);expect(()=>validateStaffAttendanceRecords([{staffMemberId:"1",status:"PRESENT"},{staffMemberId:"1",status:"ABSENT"}])).toThrow("more than once");expect(()=>validateStaffAttendanceRecords([{staffMemberId:"1",status:"LATE",lateMinutes:-1}])).toThrow("Late minutes");expect(()=>validateStaffAttendanceRecords([{staffMemberId:"1",status:"LATE",checkInTime:"25:00"}])).toThrow("HH:MM");});
  it("keeps the selected local calendar day at midnight instead of shifting through UTC",()=>{expect(localDateText(new Date(2026,5,28,0,5))).toBe("2026-06-28");});
  it("loads active staff only",async()=>{let where:any;const rows=await activeStaffMembers({staffMember:{findMany:async(args:any)=>{where=args.where;return[]}}} as never);expect(rows).toEqual([]);expect(where).toEqual({status:"ACTIVE"});});
  it("calculates official report totals and monthly summaries while excluding drafts",async()=>{let query:any;const client={staffAttendanceSession:{findMany:async(args:any)=>{query=args;return[{id:"s",attendanceDate:new Date("2026-06-28"),status:"SUBMITTED",records:[{staffMemberId:"1",staffCode:"T1",status:"ABSENT",checkInTime:null,checkOutTime:null,lateMinutes:null,remarks:null,source:"MANUAL",staffMember:{fullName:"Asha",designation:"Teacher"}},{staffMemberId:"2",staffCode:"T2",status:"LATE",checkInTime:"08:30",checkOutTime:null,lateMinutes:15,remarks:"Traffic",source:"MANUAL",staffMember:{fullName:"Bilal",designation:"Teacher"}}]}]}}};const data=await staffAttendanceReportData(client as never,{from:new Date("2026-06-01"),to:new Date("2026-06-30")});expect(query.where.status).toEqual({in:["SUBMITTED","LOCKED"]});expect(data.totals).toMatchObject({total:2,ABSENT:1,LATE:1});expect(data.byStaff).toEqual([expect.objectContaining({fullName:"Asha",absent:1}),expect.objectContaining({fullName:"Bilal",late:1})]);});
  it("handles no data and neutralizes CSV formulas",async()=>{const data=await staffAttendanceReportData({staffAttendanceSession:{findMany:async()=>[]}} as never,{from:new Date("2026-06-01"),to:new Date("2026-06-30")});expect(data).toMatchObject({sessions:[],rows:[],byStaff:[],totals:{total:0}});const csv=staffAttendanceReportCsv([{attendanceDate:new Date("2026-06-28"),staffCode:"=BAD",fullName:"+Asha",designation:"Teacher",status:"LATE",checkInTime:"08:30",checkOutTime:null,lateMinutes:15,remarks:"@unsafe",source:"MANUAL"}]);expect(csv).toContain("' =BAD".replace(" ",""));expect(csv).toContain("'+Asha");expect(csv).toContain("'@unsafe");});
  it("enforces create, duplicate-safe upsert, save, submit, lock, inactive filtering, and permissions in API source",()=>{const api=readFileSync("app/api/attendance/staff/route.ts","utf8");expect(api).toContain("staffAttendanceSession.upsert");expect(api).toContain('action === "clear"');expect(api).toContain('action === "submit"');expect(api).toContain('action === "lock"');expect(api).toContain('session.status !== "DRAFT"');expect(api).toContain("Mark every active staff member");expect(api).toContain("inactive, left, or unavailable");for(const permission of ["VIEW_STAFF_ATTENDANCE","MANAGE_STAFF_ATTENDANCE","SUBMIT_STAFF_ATTENDANCE","LOCK_STAFF_ATTENDANCE"])expect(api).toContain(permission);});
  it("guards pages and export without exposing staff attendance to parent or teacher defaults",()=>{expect(readFileSync("app/attendance/staff/page.tsx","utf8")).toContain('requirePermission("VIEW_STAFF_ATTENDANCE")');const reports=readFileSync("app/attendance/staff/reports/page.tsx","utf8");expect(reports).toContain('requirePermission("VIEW_STAFF_ATTENDANCE_REPORTS")');expect(reports).toContain('permissionSetCan(permissions, "VIEW_STAFF_ATTENDANCE")');expect(reports).toContain('canViewEntry ? <Link href="/attendance/staff"');expect(readFileSync("app/api/attendance/staff/reports/export/route.ts","utf8")).toContain('requireApiPermission("VIEW_STAFF_ATTENDANCE_REPORTS")');});
  it("uses an accessible irreversible lock confirmation and treats blank report dates as defaults",()=>{const entry=readFileSync("components/staff-attendance-entry.tsx","utf8");expect(entry).toContain('role="dialog"');expect(entry).toContain('aria-modal="true"');expect(entry).toContain("It cannot be edited or unlocked in the app.");expect(entry).toContain("Lock permanently");expect(entry).not.toContain('action==="lock"&&!confirm');const reports=readFileSync("app/attendance/staff/reports/page.tsx","utf8");expect(reports).toContain("sp.from ||");expect(reports).toContain("sp.to ||");});
});
