import { readFileSync } from "node:fs";import { describe,expect,it } from"vitest";import{createBackupDocument}from"@/lib/backup";import{validateCertificateBackupRows}from"@/lib/certificate-backup";import{publicCertificateRequest}from"@/lib/certificate-scope";
const source=(p:string)=>readFileSync(p,"utf8");
function rows(){return{certificateNumberSeries:[{id:"s1",seriesCode:"QA18A-BON",certificateType:"BONAFIDE",nextNumber:2}],certificateTemplates:[{id:"t1",templateCode:"QA18A-T",certificateType:"BONAFIDE",templateDefinitionJson:JSON.stringify({heading:"Bonafide",body:"Safe"})}],studentCertificateRequests:[{id:"r1",requestNumber:"QA18A-R",studentId:"stu",applicantGuardianId:"g"}],studentCertificates:[{id:"c1",studentId:"stu",templateId:"t1",requestId:"r1",certificateNumber:"BON-0001",draftDataJson:"{}"}],studentCertificateVersions:[{id:"v1",certificateId:"c1",versionNumber:1,snapshotJson:"{}"}],studentCertificateEvents:[{id:"e1",requestId:"r1",certificateId:"c1",versionId:"v1"}]};}
describe("certificate backup version 27",()=>{
 it("includes all six arrays and excludes actor fields/passwords",()=>{const r=rows(),b=createBackupDocument({generatedAt:new Date("2026-07-17"),generatedBy:"QA18A",students:[],feeStructures:[],payments:[],paymentAudits:[],users:[{passwordHash:"secret"}],...r,studentCertificateRequests:[{...r.studentCertificateRequests[0],createdByUserId:"actor"}]});expect(b.metadata.backupVersion).toBe(41);for(const key of Object.keys(r))expect((b as any)[key]).toHaveLength(1);expect(JSON.stringify(b)).not.toContain("passwordHash");expect(JSON.stringify(b)).not.toContain("createdByUserId");});
 it("accepts exact links",()=>expect(()=>validateCertificateBackupRows(rows(),{studentIds:new Set(["stu"]),guardianIds:new Set(["g"])})).not.toThrow());
 it("keeps older backups compatible with missing arrays",()=>expect(validateCertificateBackupRows({}, {studentIds:new Set(),guardianIds:new Set()}).studentCertificates).toEqual([]));
 it("rejects duplicate number-series codes",()=>{const r=rows();r.certificateNumberSeries.push({...r.certificateNumberSeries[0],id:"s2"});expect(()=>validateCertificateBackupRows(r,{studentIds:new Set(["stu"]),guardianIds:new Set(["g"])})).toThrow(/duplicate/);});
 it("rejects duplicate issued certificate numbers",()=>{const r=rows();r.studentCertificates.push({...r.studentCertificates[0],id:"c2"});expect(()=>validateCertificateBackupRows(r,{studentIds:new Set(["stu"]),guardianIds:new Set(["g"])})).toThrow(/duplicate/);});
 it("rejects unrelated Student and Guardian links",()=>{expect(()=>validateCertificateBackupRows(rows(),{studentIds:new Set(["other"]),guardianIds:new Set(["g"])})).toThrow(/Student/);expect(()=>validateCertificateBackupRows(rows(),{studentIds:new Set(["stu"]),guardianIds:new Set(["other"])})).toThrow(/Guardian/);});
 it("rejects broken version/event links",()=>{const r=rows();r.studentCertificateVersions[0].certificateId="missing";expect(()=>validateCertificateBackupRows(r,{studentIds:new Set(["stu"]),guardianIds:new Set(["g"])})).toThrow(/certificate link/);});
});
describe("certificate direct guards and UI safety",()=>{
 it("guards staff and Parent APIs with the intended permissions",()=>{const guards:Record<string,string>={"app/api/certificates/route.ts":"CREATE_CERTIFICATES","app/api/certificates/requests/route.ts":"MANAGE_CERTIFICATE_REQUESTS","app/api/certificates/reports/export/route.ts":"EXPORT_CERTIFICATE_REPORTS","app/api/parent/certificates/route.ts":"VIEW_OWN_CHILD_CERTIFICATES"};for(const[file,p]of Object.entries(guards))expect(source(file),file).toContain(p);});
 it("uses accessible dialogs and no native dialogs",()=>{const ui=source("components/certificate-forms.tsx");expect(ui).toContain('role="dialog"');expect(ui).toContain('aria-modal="true"');expect(ui).toContain("autoFocus");expect(ui).not.toMatch(/\b(window\.)?(alert|confirm|prompt)\s*\(/);});
 it("contains every required accessible workflow dialog label",()=>{const ui=source("components/certificate-forms.tsx");for(const label of["Submit Certificate Request","Start Certificate Review","Approve Certificate Request","Reject Certificate Request","Cancel Certificate Request","Submit Certificate for Approval","Approve Certificate","Issue Certificate","Issue Corrected Certificate","Reissue Certificate","Cancel Issued Certificate"])expect(ui).toContain(label);});
 it("removes internal Student and actor identifiers from Parent request rows",()=>{const row=publicCertificateRequest({requestNumber:"R",studentId:"internal-student-id",createdByUserId:"actor",academicYear:"2026-27",certificateType:"BONAFIDE",purpose:"Use",requestedCopies:1,urgency:"NORMAL",status:"SUBMITTED"});expect(row).not.toHaveProperty("studentId");expect(JSON.stringify(row)).not.toContain("actor");});
 it("keeps certificate tables inside table-wrap",()=>{for(const file of["app/certificates/page.tsx","app/certificates/requests/page.tsx","app/certificates/[id]/page.tsx","app/certificates/templates/page.tsx","app/certificates/reports/page.tsx","app/parent/certificates/page.tsx"]){const text=source(file),tables=text.match(/<table>/g)?.length??0,wraps=text.match(/table-wrap/g)?.length??0;expect(wraps,file).toBeGreaterThanOrEqual(tables);}});
 it("documents A4 monochrome print and no digital signature claim in source",()=>{const print=source("app/certificates/[id]/print/page.tsx"),css=source("app/globals.css");expect(css).toContain("@page { size: A4");expect(print).toContain("not digital signatures");expect(print).not.toContain("Aadhaar");});
});
