import { readFileSync } from "node:fs";
import { describe,expect,it } from "vitest";
import { can,PERMISSIONS } from "../lib/permissions";
import { createBackupDocument } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";
import { localSubstituteDateText,periodsConflict,rankSuggestionCandidates,substituteReportCsv,substituteReportData,validateSubstituteInput,validateSubstituteLinks } from "../lib/substitutes";

const source=(path:string)=>readFileSync(path,"utf8");
const valid={assignmentDate:"2026-06-28",absentStaffMemberId:"staff-a",substituteStaffMemberId:"staff-b",className:"VI",section:"A",subject:"Math",reason:"APPROVED_LEAVE",priority:"NORMAL",periodLabel:"Period III",periodStartTime:"10:30",periodEndTime:"11:10"};

describe("substitute teacher foundation",()=>{
 it("adds the requested permissions and leadership defaults",()=>{for(const permission of ["VIEW_SUBSTITUTES","MANAGE_SUBSTITUTES","ASSIGN_SUBSTITUTES","CONFIRM_SUBSTITUTES","VIEW_SUBSTITUTE_REPORTS"])expect(PERMISSIONS).toContain(permission);for(const role of ["SUPER_ADMIN","DIRECTOR","PRINCIPAL","ADMIN"] as const)expect(can(role,"ASSIGN_SUBSTITUTES")).toBe(true);});
 it("keeps accountant and parent blocked",()=>{for(const role of ["ACCOUNTANT","PARENT"] as const){expect(can(role,"VIEW_SUBSTITUTES")).toBe(false);expect(can(role,"VIEW_SUBSTITUTE_REPORTS")).toBe(false);}});
 it("gives teachers own-view only and viewers reports only",()=>{expect(can("TEACHER","VIEW_SUBSTITUTES")).toBe(true);expect(can("TEACHER","MANAGE_SUBSTITUTES")).toBe(false);expect(can("VIEWER","VIEW_SUBSTITUTE_REPORTS")).toBe(true);expect(can("VIEWER","VIEW_SUBSTITUTES")).toBe(false);});
 it("validates a substitute draft input",()=>{expect(validateSubstituteInput(valid)).toMatchObject({absentStaffMemberId:"staff-a",substituteStaffMemberId:"staff-b",reason:"APPROVED_LEAVE",priority:"NORMAL"});});
 it("blocks absent and substitute being the same staff",()=>{expect(()=>validateSubstituteInput({...valid,substituteStaffMemberId:"staff-a"})).toThrow("must be different");});
 it("blocks invalid period times",()=>{expect(()=>validateSubstituteInput({...valid,periodStartTime:"12:00",periodEndTime:"11:00"})).toThrow("after the start");});
 it("requires understandable manual class, subject, and period details",()=>{expect(()=>validateSubstituteInput({...valid,className:""})).toThrow("Enter the class");expect(()=>validateSubstituteInput({...valid,subject:""})).toThrow("Enter the subject");expect(()=>validateSubstituteInput({...valid,periodLabel:"",periodStartTime:"",periodEndTime:""})).toThrow("period label");});
 it("uses the local calendar date rather than slicing UTC",()=>{const local=new Date(2026,0,2,1,0,0);expect(localSubstituteDateText(local)).toBe("2026-01-02");});
 it("detects exact period label conflicts",()=>{expect(periodsConflict({periodLabel:"Period III"},{periodLabel:"period iii"})).toBe(true);});
 it("detects overlapping clock-time conflicts",()=>{expect(periodsConflict({periodStartTime:"10:30",periodEndTime:"11:10"},{periodStartTime:"11:00",periodEndTime:"11:40"})).toBe(true);expect(periodsConflict({periodStartTime:"10:30",periodEndTime:"11:10"},{periodStartTime:"11:10",periodEndTime:"11:40"})).toBe(false);});
 it("ranks same-subject candidates before lower duty counts",()=>{const ranked=rankSuggestionCandidates([{id:"1",staffCode:null,fullName:"Few",displayName:null,designation:"Teacher",department:"Science",primarySubject:"English",dutyCount:0,reasons:[]},{id:"2",staffCode:null,fullName:"Match",displayName:null,designation:"Teacher",department:"Languages",primarySubject:"Math",dutyCount:2,reasons:[]}],{subject:"Math",department:"Science"});expect(ranked[0].id).toBe("2");});
 it("protects CSV cells from spreadsheet formula injection",()=>{const csv=substituteReportCsv([{assignmentDate:new Date("2026-06-28T00:00:00Z"),className:"=CMD()",section:"A",subject:"Math",periodLabel:"I",reason:"MANUAL",priority:"NORMAL",status:"ASSIGNED",absentStaffMember:{staffCode:"A",fullName:"Absent"},substituteStaffMember:{staffCode:"S",fullName:"Sub"}}]);expect(csv).toContain("'=CMD()");});
 it("guards pages and APIs with substitute permissions",()=>{expect(source("app/substitutes/page.tsx")).toContain('requirePermission("VIEW_SUBSTITUTES")');expect(source("app/substitutes/new/page.tsx")).toContain('requirePermission("MANAGE_SUBSTITUTES")');expect(source("app/substitutes/reports/page.tsx")).toContain('requirePermission("VIEW_SUBSTITUTE_REPORTS")');expect(source("app/api/substitutes/reports/export/route.ts")).toContain('requireApiPermission("VIEW_SUBSTITUTE_REPORTS")');});
 it("enforces the manual workflow and cancellation reason",()=>{const api=source("app/api/substitutes/[id]/route.ts");for(const status of ["ASSIGNED","CONFIRMED","COMPLETED","CANCELLED"])expect(api).toContain(status);expect(api).toContain("Cancellation reason is required");expect(api).toContain("Teachers can view their own duties but cannot manage");});
 it("blocks inactive, leave, attendance, and same-period substitute conflicts",()=>{const helper=source("lib/substitutes.ts");expect(helper).toContain('substitute.status !== "ACTIVE"');expect(helper).toContain("on approved leave");expect(helper).toContain('status: { in: ["ABSENT", "ON_LEAVE"] }');expect(helper).toContain("already has another duty");});
 it("blocks inactive absent staff and duplicate absent-teacher coverage",async()=>{const client={staffMember:{findUnique:async({where}:{where:{id:string}})=>({id:where.id,status:where.id==="inactive"?"LEFT":"ACTIVE"})},staffLeaveRequest:{findUnique:async()=>null,count:async()=>0},staffAttendanceRecord:{findFirst:async()=>null},substituteAssignment:{findMany:async({where}:{where:{absentStaffMemberId?:string}})=>where.absentStaffMemberId?[{periodLabel:"Period III",periodStartTime:"10:30",periodEndTime:"11:10"}]:[]}};await expect(validateSubstituteLinks(client as never,validateSubstituteInput({...valid,absentStaffMemberId:"inactive",substituteStaffMemberId:""}))).rejects.toThrow("active absent staff");await expect(validateSubstituteLinks(client as never,validateSubstituteInput({...valid,substituteStaffMemberId:""}))).rejects.toThrow("Coverage already exists");});
 it("planner shows approved leave, substitute-required highlights, and timetable fallback",()=>{const planner=source("app/substitutes/planner/page.tsx");expect(planner).toContain('status: "APPROVED"');expect(planner).toContain("Substitute required");expect(planner).toContain("No linked active timetable periods");expect(planner).toContain("Nothing is auto-assigned");});
 it("teacher portal links only to own substitute duties",()=>{const teacher=source("app/teacher/page.tsx");const list=source("app/substitutes/page.tsx");expect(teacher).toContain("My Substitute Duties");expect(list).toContain("ownSubstituteStaffMemberId");expect(list).toContain("My Substitute Duties");});
 it("reports include pending coverage and CSV export",()=>{const reports=source("app/substitutes/reports/page.tsx");expect(reports).toContain("Pending / unassigned");expect(reports).toContain("Duties by Substitute Teacher");expect(reports).toContain("Most Substituted Staff");expect(reports).toContain("Export CSV");});
 it("calculates active, pending, substitute-use, and absent-coverage totals accurately",async()=>{const rows=[{id:"1",status:"COMPLETED",substituteStaffMemberId:"s1",absentStaffMemberId:"a1",substituteStaffMember:{fullName:"Sub One",displayName:null},absentStaffMember:{fullName:"Absent One",displayName:null}},{id:"2",status:"DRAFT",substituteStaffMemberId:null,absentStaffMemberId:"a1",substituteStaffMember:null,absentStaffMember:{fullName:"Absent One",displayName:null}},{id:"3",status:"CANCELLED",substituteStaffMemberId:"s1",absentStaffMemberId:"a2",substituteStaffMember:{fullName:"Sub One",displayName:null},absentStaffMember:{fullName:"Absent Two",displayName:null}}];const report=await substituteReportData({substituteAssignment:{findMany:async()=>rows}} as never,{from:new Date("2026-06-01"),to:new Date("2026-06-30")});expect(report.assignments).toHaveLength(3);expect(report.active).toHaveLength(2);expect(report.pending.map(row=>row.id)).toEqual(["2"]);expect(report.bySubstitute).toEqual([{id:"s1",name:"Sub One",count:1}]);expect(report.byAbsent).toEqual([{id:"a1",name:"Absent One",count:2}]);});
 it("backup version 39 retains substitute assignments and excludes password hashes",()=>{const backup=createBackupDocument({generatedAt:new Date("2026-06-28T00:00:00Z"),generatedBy:"QA",students:[],feeStructures:[],payments:[],paymentAudits:[],users:[{id:"u",passwordHash:"secret"}],substituteAssignments:[{id:"sub-1",assignmentDate:"2026-06-28T00:00:00.000Z",absentStaffMemberId:"a",reason:"MANUAL",status:"DRAFT",priority:"NORMAL"}]});expect(backup.metadata.backupVersion).toBe(39);expect(backup.substituteAssignments).toHaveLength(1);expect(backup.users[0]).not.toHaveProperty("passwordHash");});
 it("keeps version 11 backups without substitutes compatible",()=>{const backup=createBackupDocument({generatedAt:new Date(),generatedBy:"QA",students:[],feeStructures:[],payments:[],paymentAudits:[],users:[]});const old:any={...backup,metadata:{...backup.metadata,backupVersion:11,counts:{...backup.metadata.counts}}};delete old.substituteAssignments;delete old.metadata.counts.substituteAssignments;expect(parseAndValidateBackup(old).substituteAssignments).toEqual([]);});
 it("restore validates substitute records and link-safe restore source",()=>{const restore=source("lib/restore-database.ts");expect(restore).toContain("restoreSubstituteAssignmentData");expect(restore).toContain("leave link was omitted");expect(restore).toContain("timetable link was omitted");expect(restore).toContain("could not be matched safely");});
});
