import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { SUPPORT_CATEGORIES, SUPPORT_CONFIDENTIALITY, SUPPORT_SOURCES, SUPPORT_STATUSES, validateAuthenticatedSupportInput, validateManualSupportInput, validatePublicSupportInput } from "@/lib/support";

describe("SUPPORT-1A governed intake and scope declarations",()=>{
  it("keeps the complete bounded lifecycle, source and confidentiality vocabulary",()=>{expect(SUPPORT_STATUSES).toEqual(["DRAFT","SUBMITTED","ACKNOWLEDGED","TRIAGED","ASSIGNED","IN_PROGRESS","WAITING_FOR_REQUESTER","WAITING_FOR_INTERNAL_ACTION","ESCALATED","RESOLVED","CLOSED","REOPENED","REJECTED_AS_INVALID","CANCELLED","ARCHIVED"]);expect(SUPPORT_SOURCES).toContain("AUTHENTICATED_PARENT_PORTAL");expect(SUPPORT_SOURCES).toContain("PAPER_FORM_RECORDED_BY_STAFF");expect(SUPPORT_CONFIDENTIALITY).toEqual(["STANDARD","RESTRICTED","SAFEGUARDING","LEADERSHIP_ONLY"]);expect(SUPPORT_CATEGORIES).toContain("SAFETY_OR_BULLYING");});
  it("requires unchecked explicit public consent at acceptance while preserving neutral form shape",()=>{const base={requesterName:"Synthetic Requester",requesterType:"PARENT",requesterIdentifier:"SUPPORT1A-UNKNOWN",contactChannel:"EMAIL",contactValue:"synthetic@example.test",category:"LOGIN_SUPPORT",message:"Synthetic login support message for governed testing only.",submissionKey:"SUPPORT1A-public-0001",honeypot:""};expect(validatePublicSupportInput({...base,consent:false}).consent).toBe(false);expect(validatePublicSupportInput({...base,consent:true}).category).toBe("LOGIN_SUPPORT");expect(()=>validatePublicSupportInput({...base,consent:true,message:"short"})).toThrow(/between 20 and 2000/);expect(()=>validatePublicSupportInput({...base,consent:true,category:"OTHER",message:"This explanation is not long enough."})).toThrow(/at least 40/);});
  it("accepts only opaque Parent child handles and separates Staff/manual intake",()=>{const parent=validateAuthenticatedSupportInput({category:"ATTENDANCE",subject:"Synthetic attendance question",description:"Please review this synthetic attendance question only.",childHandles:["A".repeat(43)],contextVersion:2,submissionKey:"SUPPORT1A-parent-0001",consent:true});expect(parent.childHandles).toEqual(["A".repeat(43)]);const manual=validateManualSupportInput({source:"IN_PERSON",requesterName:"Synthetic Parent",requesterType:"PARENT",category:"SUGGESTION",subject:"Synthetic office suggestion",statement:"A synthetic statement recorded without identity verification.",identityVerified:false,submissionKey:"SUPPORT1A-manual-0001",consentRecorded:true});expect(manual.identityVerified).toBe(false);expect(manual.source).toBe("IN_PERSON");});
  it("contains no state-changing GET and preserves the dedicated payslip boundary",()=>{const route=readFileSync("app/api/support/[requestKey]/workflow/route.ts","utf8"),core=readFileSync("lib/support.ts","utf8"),publicRoute=readFileSync("app/api/public/support/requests/route.ts","utf8");expect(route).not.toMatch(/export async function GET/);expect(core).toMatch(/dedicated Payslip Requests module/);expect(core).toMatch(/INTERNAL_NOTE/);expect(publicRoute).toMatch(/Your support request has been received/);expect(publicRoute).not.toMatch(/password|reset token|security answer/i);});
});
