import {it,expect} from "vitest";
import {runWindowsAuthentication,type NativeIdentity,type WindowsFixture} from "../scripts/portable/windows-auth-lifecycle";
import {windowsTarget} from "./fixtures/windows-auth";

/** Deliberately a process/Page double. Nothing here runs Windows, authenticates
 * a server or constitutes artifact admission. The assertions test ordering. */
function harness(fault=""){
 const t=windowsTarget(),events:string[]=[],fixture:WindowsFixture={username:"synthetic-windows",password:"s".repeat(48),pin:"31415926",wrongPin:"27182818",canaries:["SYNTHETIC-PRIVATE"],expectedStudents:["SYNTHETIC-1"],userId:"synthetic-user",databaseIdentitySha256:"d".repeat(64)};
 let locked=true,badPin=false,enteredPin="",request=0,approved=false,revoked=false,renewed=false,rotations=1,restarting=false;
 const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
 const app:any={body:async()=>locked?"Welcome back Unlock app"+(badPin?" App PIN was not accepted.":""):"Workspace Security "+(request>=3?"compatibility READY Current server reference data is encrypted on this device and ready for offline drafts.":"")+(revoked&&!renewed?" NATIVE_ACCESS_INVALID_OR_EXPIRED":""),waitText:async(text:string)=>{if(!(await app.body()).includes(text))throw Error("HARNESS_UI_STATE_MISSING");},fill:async(_css:string,value:string)=>{enteredPin=value;},element:async()=>"owned-lock",command:async(_method:string,route:string)=>{if(route.endsWith("/click")){locked=true;return;}if(route==="/execute/sync")return fault==="wrong-references"?["FOREIGN"]:fixture.expectedStudents;},clickText:async(text:string)=>{
  events.push("ui:"+text);if(text==="Unlock app"){if(enteredPin===fixture.pin){locked=false;badPin=false;}else badPin=true;}
  if(text==="Connect through system browser"){request++;locked=true;}
  if(text==="Refresh encrypted reference data"&&restarting){rotations++;restarting=false;}
 }};
 app.observeLockedPrivacy=async()=>events.push("privacy-start");app.closeLockedPrivacy=async()=>{events.push("privacy-close");if(fault==="private-flash")throw Error("PRIVATE_FLASH");};
 const browser:any={command:async()=>{},fill:async()=>{},clickText:async(text:string)=>{events.push("browser:"+text);},waitText:async()=>{}};
 let instance={pid:77,created:"first",executable:t.executable,sha256:t.artifactSha256,userSid:t.userSid};
 const identity=(requestId:string):NativeIdentity=>({source:t.source,runId:t.runId,attempt:t.attempt,databaseIdentitySha256:fixture.databaseIdentitySha256,userId:fixture.userId,deviceId:"device",publicDeviceId:id(50),sessionId:requestId===id(4)?id(101):id(100),requestId,requestStatus:requestId===id(1)?"PENDING_BROWSER_AUTH":requestId===id(2)?"DEVICE_APPROVAL_REQUIRED":"CONSUMED",deviceStatus:approved?"ACTIVE":"PENDING_APPROVAL",sessionRevoked:revoked&&requestId!==id(4),activeSessions:requestId===id(1)||requestId===id(2)||revoked&&requestId!==id(4)?0:1,role:"ACCOUNTANT",mfaUsed:true,referenceStudents:fixture.expectedStudents,referenceVersion:"private-version",tokenVersion:requestId===id(4)?1:rotations,rotatedTokenVersions:requestId===id(4)?[]:Array.from({length:rotations-1},(_,i)=>i+1)});
 const host:any={admit:async()=>{events.push("admit");return t;},launch:async()=>{events.push("launch");return {app,browser,instance};},bind:async()=>{events.push("bind");},observeOriginalAuthorization:async()=>t.origin+"/native/authorize?request="+id(request)+"&state="+"s".repeat(43)+"&challenge="+"c".repeat(43)+"&proof="+"p".repeat(86),totp:async()=>"000000",read:async(requestId:string)=>{events.push("read");const result=identity(requestId);return fault==="wrong-actor"&&request>=3?{...result,userId:"foreign"}:fault==="revocation-accepted"&&revoked?{...result,activeSessions:1,sessionRevoked:false}:result;},approvePendingDevice:async()=>{events.push("approve");approved=true;},observeCallback:async(_instance:any,_id:string)=>{events.push("callback");if(fault==="wrong-instance")throw Error("CALLBACK_WRONG_INSTANCE");if(request===4)renewed=true;},assertProfilePreserved:async()=>{events.push("profile");if(fault==="profile-replaced")throw Error("PROFILE_CHANGED");},restart:async()=>{events.push("restart");locked=true;restarting=true;instance={...instance,pid:instance.pid+1,created:"restart"};return {app,instance};},background:async()=>{events.push("background");locked=true;},foreground:async()=>events.push("foreground"),revokeSession:async()=>{events.push("revoke");revoked=true;},cleanup:async()=>{events.push("cleanup");if(fault==="cleanup")throw Error("FOREIGN_PROCESS");}};
 return {host,fixture,events};
}
it("executes all five orchestration groups using labelled harness inputs only",async()=>{
 const h=harness(),result=await runWindowsAuthentication(h.host,h.fixture);expect(result.scenarios).toEqual(["WD1","WD2","WD3","WD4","WD5"]);expect(result.evidenceClass).toContain("CONTRACT");expect(result.ownerDeviceCertification).toBe(false);expect(h.events[0]).toBe("admit");expect(h.events.at(-1)).toBe("cleanup");expect(h.events.indexOf("approve")).toBeLessThan(h.events.indexOf("callback"));expect(h.events.filter(e=>e==="restart")).toHaveLength(2);expect(h.events.filter(e=>e==="browser:Confirm this device")).toHaveLength(3);
});
it.each(["wrong-actor","wrong-references","wrong-instance","profile-replaced","revocation-accepted","private-flash"])("rejects %s and cleans owned partial state without leaking details",async fault=>{const h=harness(fault);await expect(runWindowsAuthentication(h.host,h.fixture)).rejects.toThrow("WINDOWS_AUTH_LIFECYCLE_FAILED_PRIVATE_DETAILS_WITHHELD");expect(h.events.at(-1)).toBe("cleanup");});
it("reports cleanup refusal even after a successful harness journey",async()=>{const h=harness("cleanup");await expect(runWindowsAuthentication(h.host,h.fixture)).rejects.toThrow("WINDOWS_AUTH_CLEANUP_FAILED_RESIDUE_REQUIRES_RECONCILIATION");});
