import Link from "next/link";
import { PageHeader } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { supportReport } from "@/lib/support";
import { supportActor } from "@/lib/support-api";
export const dynamic = "force-dynamic";
export default async function Page() { const user = await requirePermission("VIEW_SUPPORT_REPORTS"), report = await supportReport(prisma, await supportActor(user)); return <div className="page support-page"><PageHeader title="Support Oversight" description="Permission-scoped service reporting with low-count suppression and no Staff league tables, complaint text, internal notes or attachment paths." action={<div className="page-actions"><Link className="button secondary" href="/support">Open queues</Link><a className="button" href="/api/support/reports/export">Export aggregate CSV</a></div>} /><div className="notice">Response and resolution targets are configurable school policy targets, not statutory or legal guarantees.</div><div className="stats"><Metric label="Open" value={report.open}/><Metric label="Urgent or escalated" value={report.urgentOrEscalated}/><Metric label="Overdue acknowledgment" value={report.overdueAcknowledgment}/><Metric label="Overdue response" value={report.overdueResponse}/><Metric label="Overdue resolution" value={report.overdueResolution}/><Metric label="Reopened" value={report.reopened}/></div><div className="report-grid"><section className="card card-pad"><h2>Category totals</h2>{report.categories.length ? <ul className="support-report-list">{report.categories.map((row) => <li key={row.category}><span>{row.label}</span><strong>{row.count}</strong></li>)}</ul> : <p>No visible request data.</p>}</section><section className="card card-pad"><h2>Service times</h2><dl className="detail-grid"><div><dt>First response average</dt><dd>{minutes(report.firstResponse.averageMinutes)}</dd></div><div><dt>First response median</dt><dd>{minutes(report.firstResponse.medianMinutes)}</dd></div><div><dt>Resolution average</dt><dd>{minutes(report.resolution.averageMinutes)}</dd></div><div><dt>Resolution median</dt><dd>{minutes(report.resolution.medianMinutes)}</dd></div></dl></section><section className="card card-pad"><h2>Satisfaction</h2><p>{"suppressed" in report.satisfaction && report.satisfaction.suppressed ? "Suppressed because the permitted group is too small." : `${report.satisfaction.count} response(s); average ${report.satisfaction.average ?? "not available"}.`}</p><p>No individual employee ranking is produced.</p></section></div></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="card stat"><span>{label}</span><strong>{value}</strong></div>; }
function minutes(value: number | null) { return value == null ? "Not available" : `${value} minutes`; }
