import { NextRequest, NextResponse } from "next/server";
import { requireApiPermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getEffectivePermissions, permissionSetCan } from "@/lib/role-permissions";
import { linkedStaffMember } from "@/lib/staff-leave";
import { friendlySubstituteError, substituteInclude, validateSubstituteInput, validateSubstituteLinks } from "@/lib/substitutes";

async function access(id:string,user:{id:string;role:Parameters<typeof getEffectivePermissions>[1]}) { const [assignment,permissions,linked]=await Promise.all([prisma.substituteAssignment.findUnique({where:{id},include:substituteInclude}),getEffectivePermissions(prisma,user.role),linkedStaffMember(prisma,user.id)]); if(!assignment)return {response:NextResponse.json({error:"Substitute assignment not found"},{status:404})}; const manager=permissionSetCan(permissions,"MANAGE_SUBSTITUTES"); if(!manager&&assignment.substituteStaffMemberId!==linked?.id)return {response:NextResponse.json({error:"You can only view your own substitute duties"},{status:403})}; return {assignment,permissions,manager,response:null}; }

export async function GET(_request:NextRequest,context:{params:Promise<{id:string}>}) { const auth=await requireApiPermission("VIEW_SUBSTITUTES");if(auth.response)return auth.response;const {id}=await context.params;const result=await access(id,auth.user);if(result.response)return result.response;return NextResponse.json({assignment:result.assignment}); }

export async function PATCH(request:NextRequest,context:{params:Promise<{id:string}>}) { const auth=await requireApiPermission("VIEW_SUBSTITUTES");if(auth.response)return auth.response; const {id}=await context.params; const result=await access(id,auth.user);if(result.response)return result.response; if(!result.manager)return NextResponse.json({error:"Teachers can view their own duties but cannot manage substitute assignments"},{status:403}); const existing=result.assignment!;const permissions=result.permissions!;const source=await request.json().catch(()=>({}));const action=String(source.action??"edit");
  try {
    if(action==="confirm"){if(!permissionSetCan(permissions,"CONFIRM_SUBSTITUTES"))return NextResponse.json({error:"You do not have permission to confirm substitutes"},{status:403});if(existing.status!=="ASSIGNED")throw new Error("Only assigned substitute duties can be confirmed");const assignment=await prisma.substituteAssignment.update({where:{id},data:{status:"CONFIRMED",confirmedByUserId:auth.user.id,confirmedAt:new Date()},include:substituteInclude});return NextResponse.json({assignment});}
    if(action==="complete"){if(!permissionSetCan(permissions,"CONFIRM_SUBSTITUTES"))return NextResponse.json({error:"You do not have permission to complete substitutes"},{status:403});if(existing.status!=="CONFIRMED")throw new Error("Only confirmed substitute duties can be completed");const assignment=await prisma.substituteAssignment.update({where:{id},data:{status:"COMPLETED",completedByUserId:auth.user.id,completedAt:new Date()},include:substituteInclude});return NextResponse.json({assignment});}
    if(action==="cancel"){if(!permissionSetCan(permissions,"MANAGE_SUBSTITUTES"))return NextResponse.json({error:"You do not have permission to cancel substitutes"},{status:403});if(["COMPLETED","CANCELLED"].includes(existing.status))throw new Error("Completed or cancelled substitute duties cannot be cancelled again");const cancellationReason=String(source.cancellationReason??"").trim();if(!cancellationReason)throw new Error("Cancellation reason is required");const assignment=await prisma.substituteAssignment.update({where:{id},data:{status:"CANCELLED",cancelledByUserId:auth.user.id,cancelledAt:new Date(),cancellationReason},include:substituteInclude});return NextResponse.json({assignment});}
    if(!["DRAFT","ASSIGNED"].includes(existing.status))throw new Error("Only draft or assigned substitute duties can be edited");if(!permissionSetCan(permissions,"MANAGE_SUBSTITUTES"))return NextResponse.json({error:"You do not have permission to manage substitutes"},{status:403});if(!["edit","assign"].includes(action))throw new Error("Unknown substitute workflow action");if(action==="assign"&&!permissionSetCan(permissions,"ASSIGN_SUBSTITUTES"))return NextResponse.json({error:"You do not have permission to assign substitutes"},{status:403});const input=validateSubstituteInput({...existing,...source});await validateSubstituteLinks(prisma,input,{requireSubstitute:action==="assign",excludeId:id});const assignment=await prisma.substituteAssignment.update({where:{id},data:{...input,status:action==="assign"?"ASSIGNED":existing.status,assignedByUserId:action==="assign"?auth.user.id:existing.assignedByUserId,assignedAt:action==="assign"?new Date():existing.assignedAt},include:substituteInclude});return NextResponse.json({assignment});
  } catch(error){return NextResponse.json({error:friendlySubstituteError(error)},{status:400});}
}
