import Link from "next/link";
import { Prisma } from "@prisma/client";
import { requirePermission, hasUserPermission } from "@/lib/auth";
import { budgetDetailInclude, buildBudgetMetrics } from "@/lib/budgets";
import { moneyExact } from "@/lib/format";
import { prisma } from "@/lib/prisma";

import { PageHeader, PageShell, StatusBadge } from "@/components/ui";

export default async function BudgetsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requirePermission("VIEW_BUDGETS"); const params = await searchParams; const academicYear = typeof params.academicYear === "string" ? params.academicYear : ""; const status = typeof params.status === "string" ? params.status : ""; const canManage = await hasUserPermission(user, "MANAGE_BUDGETS");
  const plans = await prisma.budgetPlan.findMany({ where: { ...(academicYear ? { academicYear } : {}), ...(status ? { status } : {}) }, include: budgetDetailInclude, orderBy: [{ academicYear: "desc" }, { createdAt: "desc" }] });
  const years = [...new Set(plans.map((plan) => plan.academicYear))]; const expenses = years.length ? await prisma.expenseRecord.findMany({ where: { academicYear: { in: years }, approvalStatus: "APPROVED" }, select: { academicYear: true, categoryId: true, departmentId: true, netAmount: true, payments: { select: { amount: true } } } }) : [];
  const rows = plans.map((plan) => ({ plan, metrics: buildBudgetMetrics(plan, expenses.filter((expense) => expense.academicYear === plan.academicYear)) })); const official = rows.filter(({ plan }) => ["APPROVED", "LOCKED"].includes(plan.status)); const sum = (field: "allocated" | "paid" | "committed" | "available") => official.reduce((total, row) => total.add(row.metrics.totals[field]), new Prisma.Decimal(0));
  return <PageShell><PageHeader title="Budgets" description="Annual allocation plans and warning-only spending controls. Student payments remain separate." action={<div className="page-actions"><Link className="button secondary" href="/budgets/reports">Budget Reports</Link>{canManage ? <Link className="button" href="/budgets/new">Create Budget</Link> : null}</div>} />
    <form className="card filter-grid" method="get"><label>Academic Year<input name="academicYear" defaultValue={academicYear} placeholder="2026-27" /></label><label>Status<select name="status" defaultValue={status}><option value="">All statuses</option>{["DRAFT", "PENDING_APPROVAL", "APPROVED", "LOCKED", "REJECTED", "CANCELLED"].map((value) => <option key={value}>{value}</option>)}</select></label><button type="submit">Apply Filters</button><Link className="button secondary" href="/budgets">Clear</Link></form>
    <div className="stats"><div className="card stat"><span>Total allocated</span><strong>{moneyExact(Number(sum("allocated")))}</strong></div><div className="card stat"><span>Paid actual</span><strong>{moneyExact(Number(sum("paid")))}</strong></div><div className="card stat"><span>Committed</span><strong>{moneyExact(Number(sum("committed")))}</strong></div><div className="card stat"><span>Available</span><strong>{moneyExact(Number(sum("available")))}</strong></div><div className="card stat"><span>Over-budget allocations</span><strong>{official.reduce((count, row) => count + row.metrics.overBudgetCount, 0)}</strong></div><div className="card stat"><span>At warning threshold</span><strong>{official.reduce((count, row) => count + row.metrics.warningCount, 0)}</strong></div></div>
    <div className="table-wrap"><table><thead><tr><th>Budget</th><th>Academic Year</th><th>Status</th><th>Allocated</th><th>Paid</th><th>Committed</th><th>Available</th><th>Warnings</th></tr></thead><tbody>{rows.map(({ plan, metrics }) => <tr key={plan.id}><td><Link href={`/budgets/${plan.id}`}><strong>{plan.budgetNumber}</strong></Link><br /><span className="muted-text">{plan.title}</span></td><td>{plan.academicYear}</td><td><StatusBadge status={plan.status} /></td><td>{moneyExact(Number(metrics.totals.allocated))}</td><td>{moneyExact(Number(metrics.totals.paid))}</td><td>{moneyExact(Number(metrics.totals.committed))}</td><td className={metrics.totals.available.lt(0) ? "danger-text" : ""}>{moneyExact(Number(metrics.totals.available))}</td><td>{metrics.warningCount + metrics.criticalCount}</td></tr>)}</tbody></table>{!rows.length ? <p className="empty-state">No budget plans match these filters.</p> : null}</div>
  </PageShell>;
}
