import Link from "next/link";
import { PageHeader, StatusBadge } from "@/components/ui";
import { requirePermission, getCurrentUserEffectivePermissions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { effectiveIdentityCardStatus } from "@/lib/identity-cards";
import { permissionSetCan } from "@/lib/role-permissions";
import { displayDate } from "@/lib/format";

export default async function IdentityCardsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const user = await requirePermission("VIEW_ID_CARDS"), q = await searchParams, permissions = await getCurrentUserEffectivePermissions();
  const source = await prisma.identityCard.findMany({ where: { ...(q.type ? { cardType: q.type } : {}), ...(q.academicYear ? { academicYear: q.academicYear } : {}), ...(q.status ? { status: q.status } : {}), ...(q.className || q.section ? { student: { is: { ...(q.className ? { className: q.className } : {}), ...(q.section ? { section: q.section } : {}) } } } : {}), ...(q.designation ? { staffMember: { is: { designation: q.designation } } } : {}) }, include: { student: { select: { studentName: true, admissionNo: true, className: true, section: true } }, staffMember: { select: { fullName: true, staffCode: true, designation: true } } }, orderBy: { createdAt: "desc" } });
  const rows = source.filter((card) => !q.effectiveStatus || effectiveIdentityCardStatus(card) === q.effectiveStatus);
  return <div className="page identity-card-page"><PageHeader title="Virtual Student and Teacher ID Cards" description="Privacy-safe operational school ID cards with immutable issued versions and transaction-safe numbering." action={permissionSetCan(permissions, "CREATE_ID_CARDS") ? <Link className="button" href="/id-cards/new">Create Individual Card</Link> : undefined}/>
    <div className="page-actions">{permissionSetCan(permissions, "MANAGE_ID_CARD_BATCHES") ? <Link className="button secondary" href="/id-cards/batches">Batches</Link> : null}<Link className="button secondary" href="/id-cards/templates">Templates & Series</Link>{permissionSetCan(permissions, "USE_ID_CARD_LOOKUP") ? <Link className="button secondary" href="/id-cards/lookup">Internal Lookup</Link> : null}{permissionSetCan(permissions, "VIEW_ID_CARD_REPORTS") ? <Link className="button secondary" href="/id-cards/reports">Reports</Link> : null}</div>
    <section className="notice"><strong>Operational identity only.</strong> These cards are not government identity documents. Card numbers and Code 39 barcodes are identifiers, not authentication.</section>
    <div className="stats"><div className="card stat"><span>Total</span><strong>{rows.length}</strong></div><div className="card stat"><span>Active</span><strong>{rows.filter((row) => effectiveIdentityCardStatus(row) === "ACTIVE").length}</strong></div><div className="card stat"><span>Awaiting issue</span><strong>{rows.filter((row) => row.status === "APPROVED").length}</strong></div><div className="card stat"><span>Revoked</span><strong>{rows.filter((row) => row.status === "REVOKED").length}</strong></div></div>
    <form className="card filter-grid"><label>Type<select name="type" defaultValue={q.type ?? ""}><option value="">All</option><option>STUDENT</option><option>STAFF</option></select></label><label>Academic year<input name="academicYear" defaultValue={q.academicYear ?? ""}/></label><label>Stored status<input name="status" defaultValue={q.status ?? ""}/></label><label>Effective status<select name="effectiveStatus" defaultValue={q.effectiveStatus ?? ""}><option value="">All</option>{["DRAFT", "APPROVED", "ACTIVE", "EXPIRED", "REVOKED", "CANCELLED", "SUPERSEDED"].map((status) => <option key={status}>{status}</option>)}</select></label><label>Class<input name="className" defaultValue={q.className ?? ""}/></label><label>Section<input name="section" defaultValue={q.section ?? ""}/></label><label>Staff designation<input name="designation" defaultValue={q.designation ?? ""}/></label><button>Apply Filters</button></form>
    <section className="card"><div className="table-wrap"><table><thead><tr><th>Card number</th><th>Person</th><th>Type</th><th>Year</th><th>Stored / effective</th><th>Valid until</th><th>Version</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link href={`/id-cards/${row.id}`}>{row.cardNumber ?? "Allocated only at issue"}</Link></td><td>{row.student?.studentName ?? row.staffMember?.fullName}<br/><small>{row.student?.admissionNo ?? row.staffMember?.staffCode ?? "School code unavailable"}</small></td><td>{row.cardType}</td><td>{row.academicYear ?? "All years"}</td><td><StatusBadge status={row.status}/><br/><small>{effectiveIdentityCardStatus(row)}</small></td><td>{displayDate(row.validUntil)}</td><td>{row.currentVersionNumber || "-"}</td></tr>)}{!rows.length ? <tr><td colSpan={7}>No ID cards match these filters.</td></tr> : null}</tbody></table></div></section>
  </div>;
}
