import Link from "next/link";
import { PageHeader, StatCard } from "@/components/ui";
import { getCurrentUserEffectivePermissions, requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { buildTeacherAnalyticsReport } from "@/lib/teacher-analytics-reports";
import { permissionSetCan } from "@/lib/role-permissions";

export default async function TeacherAnalyticsReportsPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const user = await requirePermission("VIEW_TEACHER_ANALYTICS_REPORTS"); const q = await searchParams;
  const [report, permissions, cycles] = await Promise.all([buildTeacherAnalyticsReport(prisma, q.cycleId, user.role === "VIEWER"), getCurrentUserEffectivePermissions(), prisma.teacherAnalyticsReviewCycle.findMany({ select: { id:true,cycleCode:true,title:true }, orderBy:{periodStart:"desc"} })]);
  return <div className="page teacher-analytics-page"><PageHeader title="Teacher Analytics Aggregate Reports" description="Review completion and source coverage. No leaderboard, rank, composite score, Student identity, or raw marks." action={permissionSetCan(permissions,"EXPORT_TEACHER_ANALYTICS_REPORTS") ? <Link className="button" href={`/api/teacher-analytics/reports/export${q.cycleId?`?cycleId=${encodeURIComponent(q.cycleId)}`:""}`}>Export Safe CSV</Link> : undefined}/>{user.role === "VIEWER" ? <p className="notice">Viewer/Auditor mode shows one school-level aggregate row per cycle. Teacher identities, review notes, teacher-level rows, and export are unavailable.</p> : null}<div className="grid four"><StatCard label="Snapshots" value={String(report.summary.snapshots)}/><StatCard label="Complete Source States" value={String(report.summary.completeSourceStates)}/><StatCard label="Insufficient / Missing" value={String(report.summary.insufficientSourceStates)}/><StatCard label="Reviews Finalised" value={String(report.summary.reviewsFinalised)}/></div><form className="card filter-grid"><label>Cycle<select name="cycleId" defaultValue={q.cycleId ?? ""}><option value="">All cycles</option>{cycles.map((cycle)=><option key={cycle.id} value={cycle.id}>{cycle.cycleCode} — {cycle.title}</option>)}</select></label><button>Apply Filter</button></form><section className="card"><div className="table-wrap"><table><thead><tr>{!report.aggregateOnly?<><th>Teacher</th><th>Staff Code</th></>:null}<th>Academic Year</th><th>Timetable</th><th>Attendance</th><th>Homework</th><th>Assessment</th><th>Report Cards</th><th>Cohort Evidence</th><th>Review</th></tr></thead><tbody>{report.rows.map((row,index)=><tr key={index}>{!report.aggregateOnly?<><td>{row.teacherName}</td><td>{row.staffCode}</td></>:null}<td>{row.academicYear}</td><td>{row.timetableCoverage}</td><td>{row.attendanceSource}</td><td>{row.homeworkSource}</td><td>{row.assessmentSource}</td><td>{row.reportCardSource}</td><td>{row.studentCohortThreshold}</td><td>{row.reviewStatus}</td></tr>)}</tbody></table></div></section></div>;
}
