import Link from "next/link";
import { notFound } from "next/navigation";
import { BookReceiptActions } from "@/components/books-finance-forms";
import { PageHeader, PageShell, StatusBadge } from "@/components/ui";
import { requirePermission, hasUserPermission } from "@/lib/auth";
import { bookReceiptInclude, publicBookAccountLabel } from "@/lib/books-finance";
import { displayDate, moneyExact } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function BookSaleDetailPage({ params }: { params: Promise<{ id: string }> }) { const user = await requirePermission("VIEW_BOOKS_FINANCE"); const row = await prisma.bookSaleReceipt.findUnique({ where: { id: (await params).id }, include: bookReceiptInclude }); if (!row) notFound(); const [canCancel, sensitive] = await Promise.all([hasUserPermission(user, "CANCEL_BOOK_SALES"), hasUserPermission(user, "MANAGE_BOOK_SALES")]); return <PageShell><PageHeader title={`Book Receipt ${row.receiptNumber}`} description="Books / Academic Materials Receipt — not a school-fee receipt." action={<div className="page-actions"><Link className="button secondary" href="/books/sales">Back</Link><Link className="button" href={`/books/sales/${row.id}/print`}>Print receipt</Link></div>} /><div className="stats"><div className="card stat"><span>Date</span><strong>{displayDate(row.receiptDate)}</strong></div><div className="card stat"><span>Net</span><strong>{moneyExact(Number(row.netAmount))}</strong></div><div className="card stat"><span>Status</span><StatusBadge status={row.status} /></div></div><section className="card"><p><strong>Student / payer:</strong> {row.student ? `${row.student.studentName} (${row.student.admissionNo})` : row.payerName ?? "Walk-in payer"}</p><p><strong>Payment:</strong> {row.paymentMethod.replaceAll("_", " ")} — {publicBookAccountLabel(row.receivedAccount)}</p>{sensitive && row.transactionReference ? <p><strong>Reference:</strong> {row.transactionReference}</p> : null}<div className="table-wrap"><table><thead><tr><th>Code</th><th>Item</th><th>Class</th><th>Publisher</th><th>Qty</th><th>Rate</th><th>Discount</th><th>Total</th></tr></thead><tbody>{row.lines.map((line) => <tr key={line.id}><td>{line.itemCodeSnapshot}</td><td>{line.itemTitleSnapshot}</td><td>{line.classNameSnapshot ?? "—"}</td><td>{line.publisherNameSnapshot ?? "—"}</td><td>{line.quantity}</td><td>{moneyExact(Number(line.unitAmount))}</td><td>{moneyExact(Number(line.discountAmount))}</td><td>{moneyExact(Number(line.lineTotal))}</td></tr>)}</tbody></table></div>{row.status === "CANCELLED" ? <div className="alert warning"><strong>Cancelled:</strong> {sensitive ? row.cancellationReason : "Reason hidden for this read-only role."}</div> : null}</section>{row.status === "ACTIVE" ? <BookReceiptActions id={row.id} canCancel={canCancel} /> : null}</PageShell>; }
