import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {BROWSER_MATRIX} from "./integrated-acceptance";
import {downloadBytes} from "./integrated-browser";
import {ownedCertificateContexts,certificateModalReflow} from "./certificate-browser";
import {assertDenial} from "./http-assertions";
import {FINANCE_BROWSER_SCENARIOS,assertFinanceScope,assertFinanceUnchanged,assertSale,assertFinanceDecision,assertFinanceRead,assertIncomePrivacy,assertFinanceCsv,financeSame,cents,type FinanceState} from "./finance-browser-assertions";
import type {FinanceActor} from "./finance-browser-probe";

type Input={origin:string;password:string;source:string;runId:string;attempt:string;bind:()=>unknown;probe:(input:unknown)=>Promise<any>};
const endpoint="/api/prior-year-concessions",origin="https://portable-staging.localhost:8443";
const privileged=new Set(["VERIFY","APPROVE","APPLY","REVERSE","REVIEW_REVERSAL","VERIFY_PAYMENT"]);
const denialResponses=new WeakMap<object,Set<string>>();
/** A listener for the real UI request, not an HTTP action adapter. */
export async function financeUiResponse(page:any,path:string,action:()=>Promise<unknown>,status=200,error?:string,method="POST"){
 const waiting=page.waitForResponse((r:any)=>{const u=new URL(r.url());return u.origin===origin&&u.pathname+u.search===path&&r.request().method()===method;});
 const [r]=await Promise.all([waiting,action()]);
 if(error){const set=denialResponses.get(page)??new Set<string>();set.add(`${r.url()}|${status}`);denialResponses.set(page,set);await assertDenial(new Response(await r.body(),{status:r.status(),headers:r.headers()}),status as 403,{error});}
 else assert(r.status()===status,"FINANCE_UI_RESPONSE_REFUSED");
 const raw=await r.body();assert(raw.length<=128*1024,"FINANCE_RESPONSE_BOUND");
 return {request:method==="POST"?r.request().postDataJSON():null,result:JSON.parse(raw.toString()),status:r.status()};
}
export async function financeDownload(page:any,control:any){const waiting=page.waitForEvent("download");const [download]=await Promise.all([waiting,control.click()]);try{assert(download.suggestedFilename()==="previous-year-case-review.csv","FINANCE_DOWNLOAD_NAME");return await downloadBytes(download);}finally{await download.delete();}}
/** Chromium response-stage failure: the application really commits and emits
 * 200, then this owned transport drops that response. No fabricated response,
 * cookie or request is supplied. Only the named case/APPLY may be interrupted. */
export async function interruptFinanceResponse(page:any,caseId:string,action:()=>Promise<void>){
 const cdp=await page.context().newCDPSession(page);let timer:ReturnType<typeof setTimeout>|undefined;
 try{
  let used=false;
  const intercepted=new Promise<any>((resolve,reject)=>{
   timer=setTimeout(()=>reject(Error("FINANCE_INTERRUPTION_NOT_OBSERVED")),20_000);
   cdp.on("Fetch.requestPaused",async(e:any)=>{try{
    const u=new URL(e.request.url);assert(u.origin===origin&&u.pathname===endpoint,"FINANCE_INTERRUPTION_TARGET");
    const request=JSON.parse(e.request.postData??"null");assert(!used&&e.request.method==="POST"&&request?.action==="APPLY"&&request.caseId===caseId&&e.responseStatusCode===200,"FINANCE_INTERRUPTION_NOT_COMMITTED_RESPONSE");used=true;
    await cdp.send("Fetch.failRequest",{requestId:e.requestId,errorReason:"Aborted"});resolve(request);
   }catch{reject(Error("FINANCE_INTERRUPTION_REFUSED"));}});
  });
  await cdp.send("Fetch.enable",{patterns:[{urlPattern:origin+endpoint,requestStage:"Response"}]});
  const [request]=await Promise.all([intercepted,action()]);return request;
 }finally{if(timer)clearTimeout(timer);try{await cdp.send("Fetch.disable");}finally{await cdp.detach();}}
}
export async function assertFinancePrint(page:any,expected:{receiptNumber:string;studentName:string;rate:string;total:string;incomeCanary:string;itemName?:string}){
 await page.locator(".misc-receipt-print").waitFor();const text=await page.locator(".misc-receipt-print").innerText();
 assert(text.includes(expected.receiptNumber)&&text.includes(expected.studentName)&&text.includes(expected.rate)&&text.includes(expected.total)&&text.includes("This is a non-fee school-income receipt"),"FINANCE_PRINT_CONTENT");assertIncomePrivacy(text,[expected.incomeCanary]);
 assert((await page.content()).length<=1024*1024,"FINANCE_PRINT_HTML_BOUND");const rows=page.locator(".misc-receipt-print tbody tr");assert(await rows.count()===1,"FINANCE_PRINT_LINE_COUNT");const cells=await rows.locator("td").allInnerTexts();assert(cells.length===5&&cells[0]===expected.itemName&&cells[1]==="3"&&cells[2].replace(/[₹,\s]/g,"")===expected.rate&&cells[3].replace(/[₹,\s]/g,"")==="0.00"&&cells[4].replace(/[₹,\s]/g,"")===expected.total,"FINANCE_PRINT_LINE_VALUES");
 const header=page.getByRole("heading",{name:"NALANDA PUBLIC SCHOOL",exact:true});await header.waitFor();assert(await header.evaluate((e:HTMLElement)=>getComputedStyle(e).fontWeight==="700"&&getComputedStyle(e).fontFamily.split(",")[0].replaceAll('"',"").trim()==="Georgia"),"FINANCE_PRINT_FONT_STYLE");
 // CSS alone does not prove which font rendered. No font file is distributed.
 const cdp=await page.context().newCDPSession(page);try{await cdp.send("DOM.enable");await cdp.send("CSS.enable");const {root}=await cdp.send("DOM.getDocument"),{nodeId}=await cdp.send("DOM.querySelector",{nodeId:root.nodeId,selector:".misc-receipt-print h1"});const {fonts}=await cdp.send("CSS.getPlatformFontsForNode",{nodeId});assert(fonts.length>0&&fonts.every((f:any)=>f.glyphCount>0&&f.familyName==="Georgia"&&/Georgia.*Bold/i.test(f.postScriptName)),"FINANCE_GENUINE_GEORGIA_BOLD_REQUIRED");}finally{await cdp.detach();}
}
export async function financeBrowser(browser:any,input:Input){
 assert(input.origin===origin,"FINANCE_BROWSER_ORIGIN_REFUSED");input.bind();const results=[];
 for(const [matrixIndex,matrix] of BROWSER_MATRIX.entries()){
  const iteration=randomUUID(),bound={source:input.source,runId:input.runId,attempt:input.attempt,iteration};
  const probe=async(operation:string,extra:any={})=>{input.bind();const value=await input.probe({...bound,operation,...extra});input.bind();return value;};
  const fixture=await probe("prepare",{password:input.password,matrixIndex}),read=async()=>{const s=await probe("snapshot") as FinanceState;assertFinanceScope(s,fixture.scope,fixture.studentId);return s;};
  const initial=await read();assert(initial.receipts.length===0&&initial.cases.length===0&&initial.liabilities.length===0&&initial.payments.length===2&&initial.fees.length===1,"FINANCE_FRESH_NONEMPTY_PRECONDITIONS");
  const reducedMotion=matrix.colorScheme==="dark"?"reduce":"no-preference";
  await ownedCertificateContexts(async open=>{
   const pages:Partial<Record<FinanceActor,any>>={},errors:string[]=[],pendingReads:Promise<void>[]=[];let injectedAbort=false;
   const expectedErrors=(page:any,url:string,text:string)=>{const m=/^Failed to load resource: the server responded with a status of (400|401|403|409) \(.*\)$/.exec(text);return !!m&&!!denialResponses.get(page)?.has(`${url}|${m[1]}`);};
   const consoleErrors:{page:any;url:string;text:string}[]=[];
   const contextPage=async(canaries:string[]=[])=>{
    const context=await open({viewport:matrix.viewport,colorScheme:matrix.colorScheme,reducedMotion,acceptDownloads:true,ignoreHTTPSErrors:false,serviceWorkers:"block"});
    await context.route("**/*",async(r:any)=>{const u=new URL(r.request().url());if(u.origin!==origin||u.username||u.password){errors.push("FOREIGN_NETWORK");await r.abort("blockedbyclient");}else await r.continue();});
    await context.addInitScript((values:string[])=>{
     const inspect=()=>{const dom=document.documentElement;if(!dom)return;const text=dom.textContent??"";if(values.some(v=>text.includes(v)||Array.from(document.querySelectorAll("input,textarea")).some(e=>(e as HTMLInputElement).value.includes(v))))sessionStorage.setItem("finance-private-flash","true");};
     new MutationObserver(inspect).observe(document,{subtree:true,childList:true,characterData:true,attributes:true});document.addEventListener("input",inspect,true);document.addEventListener("change",inspect,true);inspect();
    },canaries);
    const watch=(page:any)=>{page.on("pageerror",()=>errors.push("PAGE_ERROR"));page.on("console",(m:any)=>{if(m.type()==="error")consoleErrors.push({page,url:m.location().url,text:m.text()});});
    page.on("response",(r:any)=>{if(!canaries.length||!new URL(r.url()).pathname.startsWith("/api/prior-year-concessions"))return;pendingReads.push((async()=>{const b=await r.body();assert(b.length<128*1024,"FINANCE_RESPONSE_BOUND");assertIncomePrivacy(b.toString(),canaries);})().catch(()=>{errors.push("PRIVATE_RESPONSE");}));});};context.on("page",watch);return context.newPage();
   };
   const login=async(name:FinanceActor,canaries:string[]=[])=>{
    const page=await contextPage(canaries);await page.goto(origin+"/login");await page.getByLabel("Username or verified login identifier").fill(fixture.actors[name].username);await page.locator('input[name="password"]').fill(input.password);await page.getByRole("button",{name:"Sign in",exact:true}).click();await page.getByLabel("Six-digit authenticator code").waitFor();await page.getByLabel("Six-digit authenticator code").fill((await probe("totp",{actor:name})).token);await page.getByRole("button",{name:"Verify and sign in",exact:true}).click();await page.waitForURL((u:URL)=>u.pathname!=="/login");assert((await probe("login-evidence",{actor:name})).userId===fixture.actors[name].id,"FINANCE_REAL_LOGIN");pages[name]=page;return page;
   };
   const health=async(page:any)=>{
    assert(await page.locator("nextjs-portal").count()===0,"FINANCE_FRAMEWORK_OVERLAY");assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),"FINANCE_PAGE_OVERFLOW");
    assert(await page.evaluate(()=>sessionStorage.getItem("finance-private-flash")!=="true"&&sessionStorage.getItem("finance-selection-private-flash")!=="true"),"FINANCE_PRIVATE_FLASH");assert(await page.evaluate(()=>document.documentElement.classList.contains("dark"))===(matrix.colorScheme==="dark"),"FINANCE_RENDERED_THEME");assert(await page.evaluate(()=>matchMedia("(prefers-reduced-motion: reduce)").matches)===(reducedMotion==="reduce"),"FINANCE_MOTION_MODE");
    if(reducedMotion==="reduce")assert(await page.locator(".app-shell button").evaluateAll((buttons:HTMLElement[])=>buttons.every(b=>[getComputedStyle(b).animationDuration,getComputedStyle(b).transitionDuration].every(value=>value.split(",").every(v=>parseFloat(v)<=0.001)))),"FINANCE_REDUCED_MOTION");
   };
   const section=(p:any,name:string)=>p.locator("section").filter({has:p.getByRole("heading",{name,exact:true})});
   const workspace=async(name:FinanceActor,caseId?:string)=>{
    const p=pages[name]??await login(name,name==="general"?[fixture.incomeCanary]:[]);const loaded=p.waitForResponse((r:any)=>new URL(r.url()).pathname===endpoint&&r.request().method()==="GET");await p.goto(origin+"/prior-year-concessions");await loaded;await p.getByRole("heading",{name:"Previous-year outstanding",exact:true}).first().waitFor();
    if(caseId){const refreshed=p.waitForResponse((r:any)=>new URL(r.url()).pathname===endpoint&&new URL(r.url()).searchParams.get("id")===caseId);await p.locator(`[data-case-id="${caseId}"]`).click();await refreshed;await section(p,"Identity and source evidence").waitFor();await currentFees(p);}return p;
   };
   const currentFees=async(p:any)=>{const current=(await read()).currentYear;financeSame(current,{annual:"3600.00",paid:"100.00",remaining:"3500.00"});const panel=section(p,"Current-year fees");for(const value of ["INR 3600.00","INR 100.00","INR 3500.00"])await panel.getByText(value,{exact:true}).waitFor();};
   const prep=await login("preparer");
   const saleForm=async(studentId=fixture.studentId,date=fixture.firstDate)=>{
    await prep.goto(origin+"/misc-income");await prep.getByRole("link",{name:"Create receipt",exact:true}).click();await prep.getByRole("heading",{name:"Issue Miscellaneous-Income Receipt",exact:true}).waitFor();await prep.getByLabel("Item",{exact:true}).selectOption(fixture.itemId);await prep.getByLabel(/^Student /).selectOption(studentId);await prep.getByLabel("Receipt date",{exact:true}).fill(date);await prep.getByLabel("Quantity",{exact:true}).fill("3");return prep.getByRole("button",{name:"Save and issue receipt",exact:true});
   };
   let save=await saleForm();assert(await prep.getByLabel("Academic year",{exact:true}).inputValue()==="2026-27","FINANCE_VISIBLE_YEAR");assert(await prep.getByLabel("Rate",{exact:true}).inputValue()==="10.25"&&await prep.getByLabel("Line total",{exact:true}).inputValue()==="30.75","FINANCE_VISIBLE_QUOTE");
   for(const quantity of ["0","-1","1.5","10001"]){const b=await read();await prep.getByLabel("Quantity",{exact:true}).fill(quantity);await save.click();assert(await prep.getByLabel("Quantity",{exact:true}).evaluate((e:HTMLInputElement)=>!e.validity.valid),"FINANCE_QUANTITY_VALIDATION");assertFinanceUnchanged(b,await read());}
   await prep.getByLabel("Quantity",{exact:true}).fill("3");await prep.getByLabel(/^Student /).selectOption("");await save.click();assert(await prep.getByLabel(/^Student /).evaluate((e:HTMLSelectElement)=>e.validity.valueMissing),"FINANCE_STUDENT_REQUIRED");assertFinanceUnchanged(initial,await read());
   const refusedSale=async(studentId:string,date:string,error:string)=>{const button=await saleForm(studentId,date),b=await read();await financeUiResponse(prep,"/api/misc-income",()=>button.click(),400,error);await prep.getByText(error,{exact:true}).waitFor();assertFinanceUnchanged(b,await read());await health(prep);};
   await refusedSale(fixture.wrongStudentId,fixture.firstDate,"Student is not eligible in the selected academic year");await refusedSale(fixture.studentId,fixture.missingDate,"Line 1 must resolve to exactly one active academic-year rate");
   save=await saleForm(fixture.staleStudentId);await probe("stale-enrollment");let b=await read();await financeUiResponse(prep,"/api/misc-income",()=>save.click(),400,"Student is not eligible in the selected academic year");assertFinanceUnchanged(b,await read());
   save=await saleForm();b=await read();await prep.goBack();assertFinanceUnchanged(b,await read());save=await saleForm();b=await read();await financeUiResponse(prep,"/api/misc-income",()=>save.click(),201);let state=await read();const first=assertSale(b,state,{actor:fixture.actors.preparer.id,studentId:fixture.studentId,itemId:fixture.itemId,rateId:fixture.firstRateId,rate:"10.25",quantity:3,total:"30.75",date:fixture.firstDate});await prep.waitForURL(origin+`/misc-income/${first.id}`);await health(prep);
   const printReceipt=async(receipt:any,rate:string,total:string,page=prep)=>{
    await page.goto(origin+`/misc-income/${receipt.id}`);await page.getByRole("heading",{name:`Receipt ${receipt.receiptNumber}`,exact:true}).waitFor();const before=await read(),waiting=page.waitForEvent("popup");const [print]=await Promise.all([waiting,page.getByRole("link",{name:"Print receipt",exact:true}).click()]);
    try{await assertFinancePrint(print,{receiptNumber:receipt.receiptNumber,studentName:fixture.studentName,itemName:receipt.lines[0].itemNameSnapshot,rate,total,incomeCanary:fixture.incomeCanary});await health(print);await print.reload();await assertFinancePrint(print,{receiptNumber:receipt.receiptNumber,studentName:fixture.studentName,itemName:receipt.lines[0].itemNameSnapshot,rate,total,incomeCanary:fixture.incomeCanary});assertFinanceUnchanged(before,await read());await health(print);}finally{await print.close();}
    await page.reload();assertFinanceUnchanged(before,await read());
   };
   await printReceipt(first,"10.25","30.75");await prep.getByRole("button",{name:"Cancel receipt",exact:true}).click();await prep.getByLabel("Cancellation reason",{exact:true}).fill("SYNTHETIC abandoned cancellation");b=await read();await prep.getByRole("button",{name:"Keep receipt",exact:true}).click();assertFinanceUnchanged(b,await read());
   await prep.goto(origin+"/misc-income");await prep.getByRole("link",{name:"Items & rates",exact:true}).click();const rateForm=prep.locator("form").filter({has:prep.getByRole("heading",{name:"Add academic-year rate",exact:true})});await rateForm.getByLabel("Item",{exact:true}).selectOption(fixture.itemId);await rateForm.getByLabel("Amount",{exact:true}).fill("12.50");await rateForm.getByLabel("Effective from").fill(fixture.secondDate);await rateForm.getByLabel("Effective to").fill(fixture.secondDate);await rateForm.getByLabel("Notes",{exact:true}).fill(fixture.scope);b=await read();await financeUiResponse(prep,"/api/misc-income/rates",()=>rateForm.getByRole("button",{name:"Add rate",exact:true}).click(),201);state=await read();financeSame(state.receipts,b.receipts);const later=state.rates.filter(r=>!b.rates.some(old=>old.id===r.id));assert(later.length===1&&cents(later[0].amount)===1250n&&later[0].itemId===fixture.itemId&&later[0].academicYear===fixture.academicYear&&later[0].status==="ACTIVE","FINANCE_RATE_CONFIGURATION");
   save=await saleForm(fixture.studentId,fixture.secondDate);assert(await prep.getByLabel("Rate",{exact:true}).inputValue()==="12.50"&&await prep.getByLabel("Line total",{exact:true}).inputValue()==="37.50","FINANCE_LATER_QUOTE");b=await read();await financeUiResponse(prep,"/api/misc-income",()=>save.click(),201);const second=assertSale(b,await read(),{actor:fixture.actors.preparer.id,studentId:fixture.studentId,itemId:fixture.itemId,rateId:later[0].id,rate:"12.50",quantity:3,total:"37.50",date:fixture.secondDate});await prep.waitForURL(origin+`/misc-income/${second.id}`);await printReceipt(second,"12.50","37.50");await printReceipt(first,"10.25","30.75");
   // Every subsequent mutation is a concession UI operation. Fixture setup
   // supplied only received payments, fees/enrollments and the first item rate.
   const decision=async(name:FinanceActor,action:string,click:()=>Promise<unknown>,error?:string)=>{
    const p=pages[name],before=await read();let response:any;
    if(privileged.has(action)){
     const trigger=p.getByRole("button",{name:["VERIFY","VERIFY_PAYMENT"].includes(action)?"Submit for the selected office action":action==="APPLY"?"Apply approved relief":action==="REVERSE"?"Reverse with compensating entry":action.replaceAll("_"," ").toLowerCase(),exact:true});await click();const d=p.getByRole("dialog",{name:"Verify this financial decision",exact:true});await d.waitFor();assert(await d.evaluate((e:HTMLElement)=>e.contains(document.activeElement)),"FINANCE_MODAL_FOCUS");await certificateModalReflow(d);

     for(let i=0;i<6;i++){await p.keyboard.press("Tab");assert(await d.evaluate((e:HTMLElement)=>e.contains(document.activeElement)),"FINANCE_MODAL_FOCUS_ESCAPE");}
     await p.keyboard.press("Escape");await d.waitFor({state:"hidden"});assert(await trigger.evaluate((e:HTMLElement)=>document.activeElement===e),"FINANCE_MODAL_FOCUS_RETURN");assertFinanceUnchanged(before,await read());
     await click();await d.waitFor();await d.getByLabel("Six-digit authenticator code").fill((await probe("totp",{actor:name})).token);
     response=await financeUiResponse(p,endpoint,()=>d.getByRole("button",{name:"Verify and continue",exact:true}).click(),error?409:200,error);
    }else response=await financeUiResponse(p,endpoint,click,error?409:200,error);
    const after=await read();if(error){assertFinanceUnchanged(before,after);await p.getByRole("alert").filter({hasText:error}).first().waitFor();}else{assertFinanceDecision(before,after,action,fixture.actors[name].id,response.request,response.result);const id=response.request.caseId??response.result.caseId;if(id){const c=after.cases.find(c=>c.id===id);assert(c,"FINANCE_VISIBLE_CASE_TARGET");await p.locator(`[data-case-id="${id}"]`).getByText(`2025-26 · ${c.status.replaceAll("_"," ")}`,{exact:true}).waitFor();}}await health(p);return response;
   };
   const office=async(name:FinanceActor,action:string,values:Record<string,string>,error?:string)=>{
    const p=await workspace(name),form=section(p,"Prepare and verify office evidence");await form.getByLabel("Office action",{exact:true}).selectOption(action);
    for(const [label,value] of Object.entries(values)){const control=form.getByLabel(label,{exact:true});if(label==="Previous-year liability"||label==="Financial meaning")await control.selectOption(value);else if(value==="CHECK")await control.check();else await control.fill(value);}
    return decision(name,action,()=>form.getByRole("button",{name:"Submit for the selected office action",exact:true}).click(),error);
   };
   const sourceValues={"Exact Student reference":fixture.studentId,"Operating academic year":"2026-27","Eligible source academic year":"2025-26","Exact source-year enrollment reference":fixture.sourceEnrollmentId,"Opening verified fee liability":"1000","Existing approved credits (enter reviewed zero explicitly)":"50","Fee-head / term evidence references, one per line":"SYNTHETIC_TERM_REVIEW","Source and existing-credit provenance":fixture.longReason,"I verified the exact Student and source-year enrollment.":"CHECK","Reason (exclude private income details)":fixture.longReason};
   for(const year of ["UNKNOWN","2026-27","2027-28","2024-25"])await office("preparer","PREPARE_LIABILITY",{...sourceValues,"Eligible source academic year":year},year==="UNKNOWN"?"ACADEMIC_YEAR_CONFIGURATION_REQUIRED":"ONLY_CONFIGURED_PREVIOUS_YEAR_IS_ELIGIBLE");
   await office("preparer","PREPARE_LIABILITY",{...sourceValues,"Exact Student reference":fixture.wrongStudentId},"EXACT_REVIEWED_STUDENT_ENROLLMENT_REQUIRED");await office("preparer","PREPARE_LIABILITY",{...sourceValues,"Existing approved credits (enter reviewed zero explicitly)":"1001"},"PREVIOUS_YEAR_RECONCILIATION_REQUIRED");
   const liability=(await office("preparer","PREPARE_LIABILITY",sourceValues)).result.liabilityId;
   const caseValues={"Previous-year liability":liability,"Financial meaning":"SCHOOL_WAIVER","Requested relief":"300","Applicant reference":"SYNTHETIC applicant","Valid from":new Date(Date.now()-86400000).toISOString().slice(0,10),"Valid through":new Date(Date.now()+7*86400000).toISOString().slice(0,10),"Reason (exclude private income details)":fixture.longReason};
   await office("preparer","PREPARE",caseValues,"SOURCE_YEAR_UNVERIFIED");
   await office("reviewer","VERIFY",{"Previous-year liability":liability,"Received payment references, comma separated (leave empty only after verifying none)":fixture.priorPaymentId,"I independently verified identity and source year.":"CHECK","I reviewed the opening, payments, existing credits and blank-cell meanings.":"CHECK","Reason (exclude private income details)":fixture.longReason});
   const balance=()=>read().then(s=>s.balances.find(b=>b.liabilityId===liability));assert((await balance()).remaining==="750.00","FINANCE_OPENING_RECONCILIATION");await office("preparer","PREPARE",{...caseValues,"Requested relief":"751"},"RELIEF_EXCEEDS_REMAINING_LIABILITY");
   const caseId=(await office("preparer","PREPARE",caseValues)).result.caseId;
   const selectCase=async(name:FinanceActor,id:string)=>workspace(name,id);
   const decisionButton=(p:any,action:string)=>section(p,"Review and decision").getByRole("button",{name:action==="APPLY"?"Apply approved relief":action==="REVERSE"?"Reverse with compensating entry":action.replaceAll("_"," ").toLowerCase(),exact:true});
   const act=async(name:FinanceActor,id:string,action:string,error?:string)=>{const p=await selectCase(name,id);await p.getByLabel("Decision reason (exclude private income details)").fill(fixture.longReason);if(action==="APPROVE")await p.getByLabel("Approved relief amount").fill("300");return decision(name,action,()=>decisionButton(p,action).click(),error);};
   // Optional statuses and exact support are created through the actual form.
   for(const [status,exactAmount] of [["UNKNOWN",null],["NOT_PROVIDED",null],["DECLINED",null],["PROVIDED","0.00"],["PROVIDED",fixture.incomeCanary]]){await selectCase("preparer",caseId);const support=section(prep,"Restricted income support");await support.getByLabel("Income information status").selectOption(status);if(status==="PROVIDED"){await support.getByLabel("Configured annual household band").selectOption("SYNTHETIC_ONLY");await support.getByLabel("Optional exact annual household income (INR; separately restricted)").fill(exactAmount!);}await decision("preparer","INCOME",()=>support.getByRole("button",{name:"Save permitted support",exact:true}).click());}
   const readIncome=async(name:FinanceActor,exact:boolean,denied=false)=>{const p=await selectCase(name,caseId),before=await read(),path=`${endpoint}/${caseId}/income${exact?"?exact=true":""}`;const r=await financeUiResponse(p,path,()=>p.getByRole("button",{name:exact?"View separately permitted exact amount":"View permitted support",exact:true}).click(),denied?403:200,denied?"Restricted support unavailable":undefined,"GET");if(denied)assertFinanceUnchanged(before,await read());else{assertFinanceRead(before,await read(),fixture.actors[name].id,caseId,[exact?"EXACT_INCOME_VIEWED":"INCOME_VIEWED"]);assert(Object.keys(r.result).sort().join() === "bandId,exactAnnualAmount,status"&&r.result.status==="PROVIDED"&&r.result.exactAnnualAmount===(exact?fixture.incomeCanary:null),"FINANCE_INCOME_RESPONSE");}await health(p);};
   await readIncome("preparer",true);await readIncome("general",false);await readIncome("general",true,true);
   const another=(await office("preparer","PREPARE",{...caseValues,"Requested relief":"100"})).result.caseId;
   await readIncome("preparer",true);
   await prep.evaluate(({caseId,canary}:{caseId:string;canary:string})=>{const check=()=>{if(!document.querySelector(`[data-case-id="${caseId}"][aria-pressed="true"]`))return;const panel=Array.from(document.querySelectorAll("section")).find(e=>e.querySelector("h2")?.textContent==="Restricted income support");if(panel?.textContent?.includes(canary))sessionStorage.setItem("finance-selection-private-flash","true");};new MutationObserver(check).observe(document,{subtree:true,childList:true,attributes:true,characterData:true});}, {caseId:another,canary:fixture.incomeCanary});
   const selected=prep.locator(`[data-case-id="${another}"]`),selectedResponse=prep.waitForResponse((r:any)=>new URL(r.url()).pathname===endpoint&&new URL(r.url()).searchParams.get("id")===another&&r.request().method()==="GET");await selected.click();const loadedSelection=await selectedResponse;assert(loadedSelection.status()===200,"FINANCE_SELECTED_CASE_RESPONSE");await loadedSelection.finished();const preparedEvent=(await read()).events.find((e:any)=>e.caseId===another&&e.eventType==="CASE_PREPARED");assert(preparedEvent,"FINANCE_SELECTED_CASE_EVENT");await prep.getByText(`Event reference: ${preparedEvent.id}`,{exact:true}).waitFor();assert(await selected.getAttribute("aria-pressed")==="true","FINANCE_CASE_SELECTION");assert(!await section(prep,"Restricted income support").innerText().then((v:string)=>v.includes(fixture.incomeCanary)),"FINANCE_PRIOR_INCOME_NOT_CLEARED");assert(await prep.evaluate(()=>sessionStorage.getItem("finance-selection-private-flash")!=="true"),"FINANCE_SELECTION_PRIVATE_FLASH");await health(prep);
   const exportCase=async(name:FinanceActor,include:boolean,denied=false)=>{
    const p=await selectCase(name,caseId),before=await read(),control=p.getByRole("button",{name:include?"Export with separately permitted income band":"Export selected case",exact:true});
    if(denied){await financeUiResponse(p,endpoint+"/export",()=>control.click(),403,"Export is not permitted or a case requires reconciliation.");assertFinanceUnchanged(before,await read());}
    else{const bytes=await financeDownload(p,control);assertFinanceCsv(bytes,{caseId,studentId:fixture.studentId,status:"DRAFT",requested:"300.00",approved:"",remaining:"750.00",includeIncome:include,incomeCanary:fixture.incomeCanary});assertFinanceRead(before,await read(),fixture.actors[name].id,caseId,include?["INCOME_VIEWED","RESTRICTED_INCOME_EXPORTED"]:["FINANCE_CASE_EXPORTED"]);}
    await health(p);
   };
   await exportCase("general",false);await exportCase("general",true,true);await exportCase("preparer",true);
   const offline=await selectCase("preparer",caseId);await offline.getByLabel("Decision reason (exclude private income details)").fill(fixture.longReason);b=await read();
   const offlineStorage=async()=>offline.evaluate(async()=>({local:{...localStorage},databases:await indexedDB.databases()}));const storageBefore=await offlineStorage();assert(storageBefore.databases.every((d:any)=>d.name!=="nps-offline-finance-v1"),"FINANCE_OFFLINE_CONTEXT_NOT_FRESH");let offlinePosts=0;const countPost=(r:any)=>{if(r.method()==="POST"&&new URL(r.url()).pathname===endpoint)offlinePosts++;};offline.on("request",countPost);
   try{await offline.context().setOffline(true);await decisionButton(offline,"SUBMIT").click();await offline.getByRole("alert").getByText("Previous-year decisions require an online connection. Nothing was queued.",{exact:true}).waitFor();financeSame(await offlineStorage(),storageBefore);assert(offlinePosts===0,"FINANCE_OFFLINE_MUTATION_SENT");}finally{await offline.context().setOffline(false);offline.off("request",countPost);}assertFinanceUnchanged(b,await read());await health(offline);
   await act("preparer",caseId,"SUBMIT");await act("reviewer",caseId,"REVIEW");await act("preparer",caseId,"APPROVE","INDEPENDENT_REVIEW_AND_NO_SELF_APPROVAL_REQUIRED");
   // Two genuine tabs retain the same valid case version; no malformed body.
   const approver=await selectCase("approver",caseId);await approver.getByLabel("Decision reason (exclude private income details)").fill(fixture.longReason);await approver.getByLabel("Approved relief amount").fill("300");
   const staleTab=await approver.context().newPage();await staleTab.goto(origin+"/prior-year-concessions");await staleTab.locator(`[data-case-id="${caseId}"]`).click();await staleTab.getByLabel("Decision reason (exclude private income details)").fill(fixture.longReason);await staleTab.getByLabel("Approved relief amount").fill("300");
   await decision("approver","APPROVE",()=>decisionButton(approver,"APPROVE").click());pages.approver=staleTab;await decision("approver","APPROVE",()=>decisionButton(staleTab,"APPROVE").click(),"CASE_VERSION_CHANGED");await staleTab.getByRole("dialog").waitFor({state:"hidden"});await staleTab.locator(`[data-case-id="${caseId}"]`).getByText("2025-26 · APPROVED",{exact:true}).waitFor();assert(await decisionButton(staleTab,"APPROVE").count()===0,"FINANCE_STALE_APPROVAL_CONTROL_RETAINED");pages.approver=approver;await staleTab.close();
   const applier=await selectCase("applier",caseId);await applier.getByLabel("Decision reason (exclude private income details)").fill(fixture.longReason);await decisionButton(applier,"APPLY").click();const modal=applier.getByRole("dialog",{name:"Verify this financial decision",exact:true});await modal.getByLabel("Six-digit authenticator code").fill((await probe("totp",{actor:"applier"})).token);b=await read();
   const interrupted=await interruptFinanceResponse(applier,caseId,()=>modal.getByRole("button",{name:"Verify and continue",exact:true}).click());injectedAbort=true;await modal.getByRole("button",{name:"Recover original decision",exact:true}).waitFor();state=await read();const committed=state.events.find(e=>e.requestKey===interrupted.requestKey);assert(committed,"FINANCE_INTERRUPTED_COMMIT_MISSING");assertFinanceDecision(b,state,"APPLY",fixture.actors.applier.id,interrupted,{eventId:committed.id});assert((await balance()).remaining==="450.00","FINANCE_APPLIED_BALANCE");
   const retry=await financeUiResponse(applier,endpoint,()=>modal.getByRole("button",{name:"Recover original decision",exact:true}).click());financeSame(retry.request,interrupted);assert(retry.result.eventId===committed.id,"FINANCE_RETRY_IDENTITY");assertFinanceUnchanged(state,await read());await modal.waitFor({state:"hidden"});await selectCase("applier",caseId);
   await act("reviewer",caseId,"REVIEW_REVERSAL");await act("approver",caseId,"REVERSE");await selectCase("approver",caseId);assert((await balance()).remaining==="750.00","FINANCE_REVERSED_BALANCE");
   const promise=(await office("preparer","PREPARE",{...caseValues,"Financial meaning":"SPONSORSHIP_PROMISE"})).result.caseId;await act("preparer",promise,"SUBMIT");await act("reviewer",promise,"REVIEW");await act("approver",promise,"APPROVE");await act("applier",promise,"APPLY","SPONSORSHIP_PROMISE_IS_NOT_MONEY_OR_WAIVER");
   // A second legitimate received-payment PRECONDITION is independently
   // attributed through the UI. Its new hash invalidates the earlier approval.
   const staleCase=(await office("preparer","PREPARE",caseValues)).result.caseId;await act("preparer",staleCase,"SUBMIT");await act("reviewer",staleCase,"REVIEW");await act("approver",staleCase,"APPROVE");const received=await probe("received-payment-precondition");
   const attribution={"Previous-year liability":liability,"Verified payment source academic year":"2025-26","Exact source-year enrollment reference":fixture.sourceEnrollmentId,"I verified the payment identity and source-year evidence.":"CHECK","Reason (exclude private income details)":fixture.longReason};
   const proposal=(await office("preparer","PROPOSE_PAYMENT",{...attribution,"Existing Payment reference":received.paymentId})).result.eventId;await office("reviewer","VERIFY_PAYMENT",{...attribution,"Attribution proposal event reference":proposal});await act("applier",staleCase,"APPLY","STALE_APPROVAL_REVALIDATION_AND_REAPPROVAL_REQUIRED");assert((await balance()).remaining==="725.00","FINANCE_PAYMENT_ATTRIBUTION_BALANCE");
   // Valid SUBMITTED target, positive REVIEW already proven with this actor.
   await act("preparer",another,"SUBMIT");const rev=await selectCase("reviewer",another);await rev.getByLabel("Decision reason (exclude private income details)").fill(fixture.longReason);b=await read();await probe("revoke-reviewer");await financeUiResponse(rev,endpoint,()=>decisionButton(rev,"REVIEW").click(),401,"Authentication required");assertFinanceUnchanged(b,await read());
   for(const name of ["parent","teacher","viewer"] as const){const p=await login(name,[fixture.incomeCanary,fixture.longReason]);await p.goto(origin+"/prior-year-concessions");await p.waitForURL("**/unauthorized");await health(p);if(name==="viewer"){await printReceipt(first,"10.25","30.75",p);await p.goto(origin+"/misc-income/new");await p.waitForURL("**/unauthorized");await health(p);}}
   const anonymous=await contextPage([fixture.incomeCanary,fixture.longReason]);await anonymous.goto(origin+"/prior-year-concessions");await anonymous.waitForURL("**/login**");await health(anonymous);
   const final=await read();financeSame(final.receipts,[first,second].sort((a,b)=>a.id.localeCompare(b.id)));financeSame(final.currentYear,initial.currentYear);assert(final.receipts.length===2&&final.events.filter(e=>e.eventType==="RELIEF_APPLIED").length===1&&final.events.filter(e=>e.eventType==="RELIEF_REVERSED").length===1,"FINANCE_FINAL_EFFECTS");financeSame(final.students,initial.students);financeSame(final.fees,initial.fees);financeSame(final.payments.filter(p=>p.feeType!=="Old Due"),initial.payments.filter(p=>p.feeType!=="Old Due"));assert(final.cash.length===0&&final.cashDays.length===0,"FINANCE_WAIVER_CASH_EFFECT");assert(final.payments.length===3,"FINANCE_UNEXPECTED_PAYMENT");
   await Promise.all(pendingReads);assert(errors.length===0,"FINANCE_BROWSER_PRIVATE_OR_FRAMEWORK_ERROR");assert(consoleErrors.every(e=>expectedErrors(e.page,e.url,e.text)||(injectedAbort&&e.page===applier&&e.url===origin+endpoint&&e.text==="Failed to load resource: net::ERR_ABORTED")),"FINANCE_BROWSER_CONSOLE_ERROR");input.bind();
  },browser);
  results.push({viewport:matrix.viewport,theme:matrix.colorScheme,reducedMotion,scenarios:FINANCE_BROWSER_SCENARIOS,classification:"RENDERED_ADMITTED_APPLICATION",state:"PASSED",receiptOutput:"HTML_PRINT",trueBrowserZoom:"NOT_EXECUTED",publicPrivateArtifacts:false});
 }
 return results;
}
