import type {PrismaClient} from "@prisma/client";
import {createHash} from "node:crypto";
const sha=(s:string)=>createHash("sha256").update(s).digest("hex");
/** Explicit historical PRECONDITIONS, never the import or export under test.
 * Adapted from the existing publication-v3 fixture contract. No copied DB,
 * operational fixture wrapper, private phone number or issued PDF is used. */
export async function prepareMarksHistory(db:PrismaClient,input:{scope:string;className:string;actorId:string;subjectId:string;students:{id:string;admissionNo:string;studentName:string}[]}){
 const {scope,className,actorId,subjectId}=input,code=sha(scope).slice(0,12).toUpperCase(),examCode=`MBH-${code}`;
 const template=await db.reportCardTemplate.create({data:{templateCode:scope,name:"SYNTHETIC historical reporting template",reportType:"MARK_BASED",status:"ACTIVE",templateDefinitionJson:"{}",createdByUserId:actorId}});
 const result=[];
 for(const [index,year,section] of [[0,"2025-26","A"],[1,"2025-26","B"],[2,"2024-25","A"]] as const){
  const calendar=year.slice(0,4),when=new Date(`${calendar}-09-05T12:00:00Z`),start=`${calendar}-09-01`,end=`${calendar}-09-05`;
  const student=input.students[index];await db.academicYearEnrollment.create({data:{studentId:student.id,academicYear:year,className,section,status:"ACTIVE"}});
  const cls=await db.timetableClassSection.create({data:{academicYear:year,className,section,displayName:`SYNTHETIC ${code} ${index}`,groupName:"Synthetic",isActive:true}});
  const examination=await db.examination.upsert({where:{examCode:index===2?examCode+"-OLD":examCode},update:{},create:{examCode:index===2?examCode+"-OLD":examCode,academicYear:year,name:`SYNTHETIC published ${code}`,examType:"TERM",startDate:new Date(start),endDate:when,status:"ACTIVE",createdByUserId:actorId,activatedByUserId:actorId,activatedAt:when}});
  const c=await db.examinationClassScope.create({data:{examinationId:examination.id,academicYear:year,className,section,timetableClassSectionId:cls.id,status:"ACTIVE",createdByUserId:actorId}}),paper=await db.examSubjectPaper.create({data:{examinationId:examination.id,classScopeId:c.id,academicYear:year,className,section,timetableSubjectId:subjectId,subjectNameSnapshot:"Synthetic Maths",paperCode:"MATH",paperName:"Synthetic Maths",displayOrder:1,status:"ACTIVE",createdByUserId:actorId}}),scheme=await db.examinationSchemeVersion.create({data:{examinationId:examination.id,classScopeId:c.id,subjectPaperId:paper.id,academicYear:year,className,section,scopeKey:"MATH",versionNumber:1,calculationMode:"RAW_SUM",markDecimalPlaces:2,roundingPolicyVersion:"RC05_V1_DECIMAL6_HALF_UP2",status:"ACTIVE",frozenAt:when,activatedAt:when,createdByUserId:actorId,activatedByUserId:actorId}});
  const snapshot=await db.studentResultSnapshot.create({data:{calculationRunId:`${scope}-${index}`,inputFingerprint:sha(`${scope}:${index}`),runNumber:1,runStatus:"LOCKED",examinationId:examination.id,classScopeId:c.id,studentId:student.id,schemeVersionId:scheme.id,snapshotVersion:1,totalObtained:7.5,totalMaximum:10,percentage:75,gradeCode:"A",passResult:"PASS",formulaVersion:"EXAM_RESULT_V1",roundingPolicyVersion:"RC05_V1_DECIMAL6_HALF_UP2",warningsJson:"[]",sourceSheetVersionsJson:"[]",sourceSchemeVersionsJson:JSON.stringify([scheme.id]),snapshotJson:JSON.stringify({source:"SYNTHETIC_HISTORICAL_PRECONDITION",state:"PRESENT",obtained:"7.5",maximum:"10"}),calculatedByUserId:actorId,calculatedAt:when,lockedByUserId:actorId,lockedAt:when}});
  const batch=await db.reportCardBatch.create({data:{batchNumber:`${scope}-${index}`,academicYear:year,reportType:"MARK_BASED",templateId:template.id,className,section,title:examination.name,reportingPeriod:"SYNTHETIC historical term",status:"ISSUED",templateSnapshotJson:JSON.stringify({publicationSchemaVersion:3}),createdByUserId:actorId,issuedByUserId:actorId,issuedAt:when}}),card=await db.studentReportCard.create({data:{reportCardNumber:`${scope}-${index}`,batchId:batch.id,studentId:student.id,academicYear:year,className,section,reportType:"MARK_BASED",status:"ISSUED",currentVersionNumber:1,draftDataJson:JSON.stringify({publicationSchemaVersion:3}),finalGrade:"A",createdByUserId:actorId,issuedByUserId:actorId,issuedAt:when}});
  const published={schemaVersion:3,status:"ISSUED",reportType:"MARK_BASED",templateFamily:"SECONDARY_10_40_GROUPED",publicationReference:`MBPUB-${code}-${index}`,reportCardNumber:card.reportCardNumber,versionNumber:1,issueDate:when.toISOString(),title:examination.name,reportingPeriod:"SYNTHETIC historical term",academicYear:year,school:{name:"NALANDA PUBLIC SCHOOL",address:"SYNTHETIC",city:"SYNTHETIC",phone:null,logoPath:null},student:{name:student.studentName,admissionNumber:student.admissionNo,rollNumber:null,className,section,dateOfBirth:null},examination:{code:examination.examCode,name:examination.name,periodStart:start,periodEnd:end},content:{papers:[{code:"MATH",subjectName:"Synthetic Maths",paperName:"Synthetic Maths",calculationMode:"RAW_SUM",components:[{code:"THEORY",name:"Theory",state:"PRESENT",obtained:"7.50",maximum:"10.00",contributionWeight:null,contribution:"7.50"}],obtained:"7.50",maximum:"10.00",percentage:"75.00",excluded:false}],groups:[],combinedResults:[],totalObtained:"7.50",totalMaximum:"10.00",percentage:"75.00",grade:{code:"A",label:"Published grade",point:null},passResult:"PASS",rank:null,cohortAverage:null,cohortHighest:null,attendance:{policy:"LOCKED_EXAMINATION_DATE_RANGE_ONLY",periodStart:start,periodEnd:end,totalLockedDays:5,recordedDays:5,presentEquivalentDays:5},skills:[],personality:[],developmentalSections:[],remarks:{classTeacher:null,principal:null,general:null},legends:[{code:"PRESENT",label:"Present"}],warnings:[]},signatures:[{role:"PRINCIPAL",label:"Principal"}],template:{code:scope,name:"SYNTHETIC",version:1,bindingVersion:1,definition:{},printSettings:{orientation:"PORTRAIT",pageSize:"A4",minimumFontSizePt:10,marginMm:12}},governance:{calculationRunReference:`${scope}-${index}`,resultSnapshotVersion:1,formulaVersion:snapshot.formulaVersion,roundingPolicyVersion:snapshot.roundingPolicyVersion,sourceLockedAt:when.toISOString(),templateFrozenAt:when.toISOString(),previewFingerprint:sha(snapshot.id),publishedByLabel:"Principal",internal:{resultSnapshotId:snapshot.id,calculationRunId:snapshot.calculationRunId,templateBindingId:`${scope}-binding`}}};
  const version=await db.studentReportCardVersion.create({data:{reportCardId:card.id,versionNumber:1,versionType:"ORIGINAL",snapshotJson:JSON.stringify(published),calendarBasisVersionKey:`${scope}-attendance`,calendarBasisSnapshotJson:JSON.stringify({locked:true}),issuedAt:when,issuedByUserId:actorId}});result.push({snapshotId:snapshot.id,versionId:version.id,examinationCode:examination.examCode,academicYear:year,className,section,studentId:student.id});
 }
 return {examCode,academicYear:"2025-26",className,section:"A",sources:result};
}
