import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import * as XLSX from "xlsx";
import {BROWSER_MATRIX} from "./integrated-acceptance";
import {downloadBytes} from "./integrated-browser";
import {ownedCertificateContexts,certificateModalReflow} from "./certificate-browser";
import {assertDenial} from "./http-assertions";
import {parseCsv,GOVERNED_IMPORT_COLUMNS,MARKS_IMPORT_COLUMNS} from "../../lib/marks-import-csv";
import {assertMarksExportAudit,MARKS_BROWSER_SCENARIOS,assertMarksBound,assertMarksTemplate,completeMarksTemplate,assertMarksRows,assertMarksEvent,assertMarksUnchanged,assertMarksPrivacy,assertMarksExport,marksCsv,marksSame,type MarksContext} from "./marks-browser-assertions";
import type {MarksActor} from "./marks-browser-probe";
import {inspectMarksReportPdf} from "./marks-browser-document";

const origin="https://portable-staging.localhost:8443";
type Input={origin:string;password:string;source:string;runId:string;attempt:string;bind:()=>unknown;probe:(input:unknown)=>Promise<any>};
function observeMarksCanaries(values:string[]){const check=()=>{if(values.some(v=>(document.documentElement?.textContent??"").includes(v)))sessionStorage.setItem("marks-private-flash","true");};new MutationObserver(check).observe(document,{subtree:true,childList:true,characterData:true,attributes:true});check();}
const observedDenials=new WeakMap<object,Set<string>>();
const expectedNetwork=new WeakMap<object,Set<string>>();
export async function interruptMarksResponse(page:any,path:string,action:()=>Promise<void>){
 const cdp=await page.context().newCDPSession(page);let timer:ReturnType<typeof setTimeout>|undefined;
 try{let used=false;const intercepted=new Promise<any>((resolve,reject)=>{timer=setTimeout(()=>reject(Error("MARKS_COMMIT_RESPONSE_NOT_OBSERVED")),20000);cdp.on("Fetch.requestPaused",async(e:any)=>{try{const request=JSON.parse(e.request.postData??"null");assert(!used&&e.request.url===origin+path&&e.request.method==="POST"&&request.action==="confirm"&&e.responseStatusCode===200,"MARKS_INTERRUPTION_TARGET");used=true;const expected=expectedNetwork.get(page)??new Set<string>();expected.add(origin+path);expectedNetwork.set(page,expected);await cdp.send("Fetch.failRequest",{requestId:e.requestId,errorReason:"Aborted"});resolve(request);}catch{reject(Error("MARKS_INTERRUPTION_REFUSED"));}});});await cdp.send("Fetch.enable",{patterns:[{urlPattern:origin+path,requestStage:"Response"}]});const [request]=await Promise.all([intercepted,action()]);return request;}
 finally{if(timer)clearTimeout(timer);try{await cdp.send("Fetch.disable");}finally{await cdp.detach();}}
}
/** Real expiry deadline from the received opaque receipt. No host-clock change
 * and no shorter production lifetime. Only one journey incurs this wait. */
export async function waitMarksReceiptExpiry(receipt:string,now=()=>Date.now(),wait:(ms:number)=>Promise<void>=ms=>new Promise(resolve=>setTimeout(resolve,ms))){
 let expires:number;try{expires=JSON.parse(Buffer.from(receipt.split(".")[0],"base64url").toString()).expires;}catch{throw Error("MARKS_EXPIRY_RECEIPT");}assert(Number.isSafeInteger(expires)&&expires>now()&&expires-now()<=15*60000,"MARKS_EXPIRY_DEADLINE");await wait(expires-now()+50);assert(now()>expires,"MARKS_EXPIRY_NOT_ELAPSED");
}
export async function delayedMarksNavigation(page:any,path:string,preview:()=>Promise<void>,navigate:()=>Promise<void>){
 const cdp=await page.context().newCDPSession(page);let timer:ReturnType<typeof setTimeout>|undefined,failed=false;const onFailed=(r:any)=>{if(r.url()===origin+path&&r.method()==="POST")failed=true;};page.on("requestfailed",onFailed);
 try{const paused=new Promise<string>((resolve,reject)=>{timer=setTimeout(()=>reject(Error("MARKS_DELAY_NOT_OBSERVED")),20000);cdp.on("Fetch.requestPaused",(e:any)=>{try{assert(e.request.url===origin+path&&e.request.method==="POST"&&JSON.parse(e.request.postData).action==="preview"&&e.responseStatusCode===200,"MARKS_DELAY_TARGET");resolve(e.requestId);}catch{reject(Error("MARKS_DELAY_REFUSED"));}});});await cdp.send("Fetch.enable",{patterns:[{urlPattern:origin+path,requestStage:"Response"}]});const [requestId]=await Promise.all([paused,preview()]);await navigate();try{await cdp.send("Fetch.continueResponse",{requestId});}catch{assert(failed,"MARKS_DELAY_UNEXPLAINED_CANCELLATION");}}
 finally{if(timer)clearTimeout(timer);page.off("requestfailed",onFailed);try{await cdp.send("Fetch.disable");}finally{await cdp.detach();}}
}
/** Observes a rendered control's real request. Never supplies a request body. */
export async function marksUiResponse(page:any,path:string,action:()=>Promise<unknown>,expected:{status:number;error?:string;code?:string}={status:200},method="POST"){
 const wait=page.waitForResponse((r:any)=>{const u=new URL(r.url());return u.origin===origin&&u.pathname+u.search===path&&r.request().method()===method;});
 const [r]=await Promise.all([wait,action()]);const bytes=await r.body();assert(bytes.length<=400000,"MARKS_RESPONSE_BOUND");
 if(expected.error){await assertDenial(new Response(bytes,{status:r.status(),headers:r.headers()}),expected.status as 403,{error:expected.error,...(expected.code?{code:expected.code}:{})});const set=observedDenials.get(page)??new Set<string>();set.add(`${r.url()}|${r.status()}`);observedDenials.set(page,set);}
 else assert(r.status()===expected.status,"MARKS_UI_OPERATION_REFUSED");
 return {body:JSON.parse(bytes.toString()),request:method==="POST"?r.request().postDataJSON():null};
}
export async function marksDownload(page:any,control:any,extension:"csv"|"xlsx"|"pdf"){
 const waiting=page.waitForEvent("download");const [d]=await Promise.all([waiting,control.click()]);try{assert(d.suggestedFilename().endsWith("."+extension),"MARKS_DOWNLOAD_FORMAT");const bytes=await downloadBytes(d);assert(bytes.length<=(extension==="xlsx"?400000:extension==="pdf"?16*1024*1024:2_000_000),"MARKS_DOWNLOAD_BOUND");return bytes;}finally{await d.delete();}
}
export function marksWorkbook(bytes:Buffer,context:MarksContext,entries:{state:string;marks:string;remarks:string}[]){
 const book=XLSX.read(bytes,{type:"buffer",raw:true,cellFormula:true});assert(book.SheetNames.length===1&&book.SheetNames[0]==="Governed Draft","MARKS_WORKBOOK_SHEET");
 const rows=XLSX.utils.sheet_to_json<string[]>(book.Sheets[book.SheetNames[0]],{header:1,raw:false,defval:""});
 const completed=parseCsv(completeMarksTemplate(marksCsv(rows),context,entries).toString());
 const sheet=book.Sheets[book.SheetNames[0]];
 // Preserve the actual downloaded workbook and all signed context cells.
 for(let r=1;r<completed.length;r++)for(const c of [7,8,9])sheet[XLSX.utils.encode_cell({r,c})]={t:"s",v:completed[r][c]};
 return Buffer.from(XLSX.write(book,{type:"buffer",bookType:"xlsx",compression:true}));
}
export async function marksDialog(page:any,panel:any,unchanged:()=>Promise<void>){
 const trigger=panel.getByRole("button",{name:"Review and confirm draft import",exact:true});await trigger.click();const d=page.getByRole("dialog",{name:"Confirm exact marks draft",exact:true});await d.waitFor();
 assert(await d.evaluate((e:HTMLElement)=>e.contains(document.activeElement)),"MARKS_DIALOG_INITIAL_FOCUS");await certificateModalReflow(d);
 let reachedConfirm=false;for(let i=0;i<5;i++){await page.keyboard.press("Tab");assert(await d.evaluate((e:HTMLElement)=>e.contains(document.activeElement)),"MARKS_DIALOG_FOCUS_ESCAPE");reachedConfirm||=await d.getByRole("button",{name:"Confirm draft import",exact:true}).evaluate((e:HTMLElement)=>document.activeElement===e);}assert(reachedConfirm,"MARKS_CONFIRM_KEYBOARD_UNREACHABLE");
 await page.keyboard.press("Escape");await d.waitFor({state:"hidden"});assert(await trigger.evaluate((e:HTMLElement)=>document.activeElement===e),"MARKS_DIALOG_FOCUS_RETURN");await unchanged();await trigger.click();await d.waitFor();return d;
}
const inputs=(governed:boolean)=>[{state:"PRESENT",marks:"7.25",remarks:"SYNTHETIC reviewed draft"},{state:"PRESENT",marks:"0",remarks:""},{state:"ABSENT",marks:"",remarks:""},{state:"EXEMPT",marks:"",remarks:""},{state:"NOT_APPLICABLE",marks:"",remarks:""},{state:governed?"NOT_ENTERED":"PRESENT",marks:governed?"":"10",remarks:""}];
export function assertImportedMarks(before:any,after:any,f:any,model:"legacy"|"governed",actor:MarksActor,expectedInputs=inputs(model==="governed")){
 assertMarksBound(after,{scope:f.scope,source:f.source,runId:f.runId,attempt:f.attempt});
 if(model==="legacy"){
  const rows=after.marks.filter((r:any)=>r.assessmentId===f.assessmentId);assert(rows.every((r:any)=>r.academicYear===f.academicYear&&r.enteredByUserId===f.actors[actor].id),"MARKS_LEGACY_ACTOR_YEAR");
  assertMarksUnchanged(before.marks.filter((r:any)=>r.assessmentId!==f.assessmentId),after.marks.filter((r:any)=>r.assessmentId!==f.assessmentId));assertMarksUnchanged(before.assessments.filter((r:any)=>r.id!==f.assessmentId),after.assessments.filter((r:any)=>r.id!==f.assessmentId));
  for(const [i,s] of f.students.entries())assert((rows.find((r:any)=>r.studentId===s.id)?.remarks??"")===expectedInputs[i].remarks,"MARKS_REMARKS");
  assertMarksRows(rows.map((r:any)=>({studentId:r.studentId,state:r.entryStatus,marks:r.marksObtained,version:1})),f.students.map((s:any,i:number)=>({studentId:s.id,state:expectedInputs[i].state,marks:expectedInputs[i].marks||null,version:1})));
  const added=after.legacyEvents.filter((e:any)=>!before.legacyEvents.some((p:any)=>p.id===e.id));assert(added.length===6,"MARKS_LEGACY_EFFECT_COUNT");for(const row of rows)assertMarksEvent([],added.filter((e:any)=>e.studentMarkId===row.id),{assessmentId:f.assessmentId,studentMarkId:row.id,eventType:"MARK_CREATED",actorLabel:`SYNTHETIC marks ${actor}`,newEntryStatus:row.entryStatus,newMarks:row.marksObtained});
  for(const key of ["sheets","entries","audits","results"])assertMarksUnchanged(before[key],after[key]);
  assert(after.assessments.find((a:any)=>a.id===f.assessmentId)?.entryStatus==="OPEN","MARKS_LEGACY_NOT_DRAFT");
 }else{
  const sheets=after.sheets.filter((s:any)=>s.primaryAssignmentId===f.assignmentId);assert(sheets.length===1,"MARKS_GOVERNED_SHEET_COUNT");const sheet=sheets[0];assert(sheet.status==="DRAFT"&&sheet.optimisticVersion===2&&sheet.versionNumber===1&&sheet.createdByUserId===f.actors[actor].id&&!sheet.submittedAt&&!sheet.moderatedAt&&!sheet.lockedAt,"MARKS_GOVERNED_DRAFT_VERSION");
  assertMarksUnchanged(before.sheets.filter((s:any)=>s.primaryAssignmentId!==f.assignmentId),after.sheets.filter((s:any)=>s.primaryAssignmentId!==f.assignmentId));assertMarksUnchanged(before.entries.filter((e:any)=>e.sheetId!==sheet.id),after.entries.filter((e:any)=>e.sheetId!==sheet.id));for(const [i,s] of f.students.entries())assert((after.entries.find((r:any)=>r.sheetId===sheet.id&&r.studentId===s.id)?.remarks??"")===expectedInputs[i].remarks,"MARKS_REMARKS");
  assertMarksRows(after.entries.filter((r:any)=>r.sheetId===sheet.id).map((r:any)=>({studentId:r.studentId,state:r.entryState,marks:r.marksObtained,version:r.rowVersion})),f.students.map((s:any,i:number)=>({studentId:s.id,state:expectedInputs[i].state,marks:expectedInputs[i].marks||null,version:i===5?1:2})));
  assert(after.entries.filter((r:any)=>r.sheetId===sheet.id&&r.entryState!=="NOT_ENTERED").every((r:any)=>r.enteredByUserId===f.actors[actor].id),"MARKS_GOVERNED_ACTOR");
  assertMarksEvent(before.audits,after.audits,{eventType:"DRAFT_SAVED",actorUserId:f.actors[actor].id,assignmentId:f.assignmentId,targetId:sheet.id,newStatus:"DRAFT"});
  for(const key of ["marks","legacyEvents","assessments","results"])assertMarksUnchanged(before[key],after[key]);
 }
 if(before.history)assertMarksUnchanged(before.history,after.history);
}

export async function marksBrowser(browser:any,input:Input){
 assert(input.origin===origin,"MARKS_BROWSER_ORIGIN");input.bind();const results=[];
 for(const [index,matrix] of BROWSER_MATRIX.entries()){
  const bound={source:input.source,runId:input.runId,attempt:input.attempt,iteration:randomUUID()},probe=async(operation:string,extra:any={})=>{input.bind();const result=await input.probe({...bound,operation,...extra});input.bind();return result;};
  const f=await probe("prepare",{password:input.password}),read=async()=>{const s=await probe("snapshot");assertMarksBound(s,{scope:f.scope,source:input.source,runId:input.runId,attempt:input.attempt});return s;},initial=await read();assert(initial.marks.length===0&&initial.sheets.length===0,"MARKS_FRESH_IMPORT_PRECONDITIONS");
  await ownedCertificateContexts(async open=>{
   const privacyPolicies=new WeakMap<object,string[]>(),pages:Partial<Record<MarksActor,any>>={},errors:string[]=[],consoleErrors:{page:any;url:string;text:string}[]=[],privacyReads:Promise<void>[]=[];
   const motion=matrix.colorScheme==="dark"?"reduce":"no-preference";
   const newPage=async(canaries:string[]=[])=>{
    const context=await open({viewport:matrix.viewport,colorScheme:matrix.colorScheme,reducedMotion:motion,acceptDownloads:true,ignoreHTTPSErrors:false,serviceWorkers:"block"});
    await context.route("**/*",async(r:any)=>{const u=new URL(r.request().url());if(u.origin!==origin||u.username||u.password){errors.push("MARKS_FOREIGN_NETWORK");await r.abort("blockedbyclient");}else await r.continue();});
    await context.addInitScript(observeMarksCanaries,canaries);
    const p=await context.newPage();privacyPolicies.set(p,canaries);p.on("pageerror",()=>errors.push("MARKS_PAGE_ERROR"));p.on("console",(m:any)=>{if(m.type()==="error")consoleErrors.push({page:p,url:m.location().url,text:m.text()});});p.on("response",(r:any)=>{const u=new URL(r.url());if(canaries.length&&(u.pathname.startsWith("/marks")||u.pathname.startsWith("/api/marks")||u.pathname.startsWith("/api/exam-marks")))privacyReads.push((async()=>{if(r.status()>=300&&r.status()<400){const target=new URL(r.headers().location,r.url());assert(target.origin===origin&&["/login","/unauthorized"].includes(target.pathname),"MARKS_DENIAL_REDIRECT");return;}const b=await r.body();assert(b.length<=4*1024*1024,"MARKS_PRIVACY_RESPONSE_BOUND");assertMarksPrivacy(b.toString(),canaries);})().catch(()=>{errors.push("MARKS_PRIVATE_RESPONSE");}));});return p;
   };
   const login=async(name:MarksActor,privateView=false)=>{const p=await newPage(privateView?f.students.map((s:any)=>s.studentName):[]);await p.goto(origin+"/login");await p.getByLabel("Username or verified login identifier").fill(f.actors[name].username);await p.locator('input[name="password"]').fill(input.password);await p.getByRole("button",{name:"Sign in",exact:true}).click();await p.getByLabel("Six-digit authenticator code").waitFor();await p.getByLabel("Six-digit authenticator code").fill((await probe("totp",{actor:name})).token);await p.getByRole("button",{name:"Verify and sign in",exact:true}).click();await p.waitForURL((u:URL)=>u.pathname!=="/login");assert((await probe("login-evidence",{actor:name})).userId===f.actors[name].id,"MARKS_LOGIN_EVIDENCE");pages[name]=p;return p;};
   const health=async(p:any)=>{assert(await p.locator("nextjs-portal").count()===0,"MARKS_FRAMEWORK_OVERLAY");assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),"MARKS_PAGE_OVERFLOW");assert(await p.evaluate(()=>sessionStorage.getItem("marks-private-flash")!=="true"),"MARKS_PRIVATE_FLASH");assert(await p.evaluate(()=>document.documentElement.classList.contains("dark"))===(matrix.colorScheme==="dark"),"MARKS_THEME");assert(await p.evaluate(()=>matchMedia("(prefers-reduced-motion: reduce)").matches)===(motion==="reduce"),"MARKS_MOTION");if(motion==="reduce")assert(await p.locator(".app-shell button").evaluateAll((buttons:HTMLElement[])=>buttons.every(b=>[getComputedStyle(b).animationDuration,getComputedStyle(b).transitionDuration].every(value=>value.split(",").every(v=>parseFloat(v)<=0.001)))),"MARKS_REDUCED_MOTION_BEHAVIOUR");};
   const select=async(p:any,model:"legacy"|"governed")=>{await p.goto(origin+(model==="legacy"?"/marks/import":`/marks/governed?assignmentId=${f.assignmentId}`));const panel=p.locator("section").filter({has:p.getByRole("heading",{name:model==="legacy"?"Legacy assessment CSV import":"Governed component draft CSV import",exact:true})});await panel.getByLabel("Exact context",{exact:true}).selectOption(model==="legacy"?f.assessmentId:f.assignmentId);await panel.getByText("Preview available / Import available under current authority",{exact:true}).waitFor();const selected=await panel.getByLabel("Exact context",{exact:true}).locator("option:checked").innerText();assert(selected.includes(f.academicYear)&&selected.includes(f.examCode)&&selected.includes(f.className+"-A")&&selected.includes("Theory")&&selected.includes(model==="legacy"?f.subjectName:"Synthetic Maths")&&(model==="legacy"||selected.includes("scheme v1")),"MARKS_VISIBLE_CONTEXT");await panel.getByText(`Maximum 10; precision ${model==="legacy"?4:2} decimal places.`,{exact:false}).waitFor();await health(p);return panel;};
   const upload=async(panel:any,bytes:Buffer,model:"legacy"|"governed",xlsx=false)=>{await panel.getByLabel(model==="legacy"?"Completed CSV":"Completed CSV / XLSX",{exact:true}).setInputFiles({name:xlsx?"synthetic.xlsx":"synthetic.csv",mimeType:xlsx?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"text/csv",buffer:bytes});await panel.getByText(xlsx?"Governed workbook exact fields reconstructed locally. No upload yet.":"Exact columns validated and reconstructed locally. Server preview is a separate action.",{exact:true}).waitFor();};
   const preview=async(p:any,panel:any,model:"legacy"|"governed")=>{const before=await read(),path=model==="legacy"?"/api/marks/import":`/api/exam-marks/sheets/${f.assignmentId}`;const response=await marksUiResponse(p,path,()=>panel.getByRole("button",{name:"Server validation / preview",exact:true}).click());assertMarksUnchanged(before,await read());return response;};
   const principal=await login("principal"),delegate=await login("delegate");
   for(const model of ["legacy","governed"] as const){
    const p=model==="legacy"?principal:delegate,panel=await select(p,model),context:MarksContext={...f,model},path=model==="legacy"?"/api/marks/import":`/api/exam-marks/sheets/${f.assignmentId}`;
    const beforeDownload=await read(),downloaded=await marksDownload(p,panel.getByRole("link",{name:"Download selected-context CSV template",exact:true}),"csv");assertMarksTemplate(downloaded,context);assertMarksUnchanged(beforeDownload,await read());
    const entries=inputs(model==="governed"),completed=completeMarksTemplate(downloaded,context,entries);let workbook:Buffer|undefined;
    if(model==="governed"){const bytes=await marksDownload(p,panel.getByRole("link",{name:"Download selected-context XLSX template",exact:true}),"xlsx");workbook=marksWorkbook(bytes,context,entries);}
    if(workbook){for(const unsafe of ["formula","extra-sheet"]){const book=XLSX.read(workbook,{type:"buffer"});if(unsafe==="formula")book.Sheets[book.SheetNames[0]].H2={t:"n",f:"1+1",v:2};else XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([["SYNTHETIC"]]),"Unexpected");const b=await read();await panel.getByLabel("Completed CSV / XLSX",{exact:true}).setInputFiles({name:"synthetic.xlsx",mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",buffer:Buffer.from(XLSX.write(book,{type:"buffer",bookType:"xlsx",compression:true}))});await panel.getByText("Workbook refused locally. Use the exact safe governed template.",{exact:true}).waitFor();assert(await panel.getByRole("button",{name:"Server validation / preview",exact:true}).isDisabled(),"MARKS_UNSAFE_WORKBOOK_ENABLED");assertMarksUnchanged(b,await read());}}
    // Local rejection never uploads rows. These cases use the actual file input.
    for(const bad of [Buffer.from(completed.toString().replace("remarks","privateColumn")),Buffer.from((model==="legacy"?GOVERNED_IMPORT_COLUMNS:MARKS_IMPORT_COLUMNS).join(",")+"\r\n")]){
     const before=await read(),requests:any[]=[];const observe=(r:any)=>{if(r.method()==="POST"&&new URL(r.url()).pathname===path)requests.push(r);};p.on("request",observe);
     try{await panel.getByLabel(model==="legacy"?"Completed CSV":"Completed CSV / XLSX",{exact:true}).setInputFiles({name:"synthetic.csv",mimeType:"text/csv",buffer:bad});await panel.getByText("File refused locally: use the exact model template and limits. No source rows were uploaded.",{exact:true}).waitFor();assert(requests.length===0,"MARKS_LOCAL_REJECTION_UPLOADED");assert(await panel.getByRole("button",{name:"Server validation / preview",exact:true}).isDisabled(),"MARKS_INVALID_FILE_ENABLED");assertMarksUnchanged(before,await read());}finally{p.off("request",observe);}
    }
    // Server validation remains independent of exact-column reconstruction.
    const invalidRows=parseCsv(completed.toString());invalidRows[1][model==="legacy"?6:7]="10.12345";await upload(panel,marksCsv(invalidRows),model);
    if(model==="legacy"){const result=await preview(p,panel,model);assert(result.body.preview.errorRows===1&&result.body.preview.validRows===5,"MARKS_LEGACY_PREVIEW_ERRORS");assert(await panel.getByRole("button",{name:"Review and confirm draft import",exact:true}).isDisabled(),"MARKS_INVALID_CONFIRMATION");await panel.getByText("Row 2",{exact:false}).first().click();await health(p);}
    else{const before=await read();await marksUiResponse(p,path,()=>panel.getByRole("button",{name:"Server validation / preview",exact:true}).click(),{status:400,error:"Marks must be between 0 and 10." ,code:"EXAM_MARKS_REQUEST_REJECTED"});assertMarksUnchanged(before,await read());}
    const invalidCases=model==="legacy"?["blank","precision","duplicate","wrong-year","wrong-section","inactive","context"]:["blank","precision","duplicate","context"];
    for(const kind of invalidCases){const rows=parseCsv(completed.toString()),valueIndex=model==="legacy"?6:7;let expectedError="",code:string|undefined;
     if(kind==="blank"){rows[1][valueIndex]="";expectedError="A Present entry requires marks. Numeric zero is valid; a blank is not zero.";}
     if(kind==="precision"){rows[1][valueIndex]=model==="legacy"?"7.12345":"7.123";expectedError="Marks allow at most 2 decimal places.";}
     if(kind==="duplicate"){rows.push([...rows[1]]);expectedError="Duplicate or ineligible roster reference.";}
     if(["wrong-year","wrong-section","inactive"].includes(kind))rows[1][5]=f.excluded[["wrong-year","wrong-section","inactive"].indexOf(kind)].admissionNo;
     if(kind==="context"){if(model==="legacy"){rows[1][4]="Other";expectedError="CSV does not match the selected legacy assessment context.";}else{rows[1][3]="99";expectedError="Import content, context or versions changed, or preview expired. Validate again.";}}
     await upload(panel,marksCsv(rows),model);const b=await read();
     if(model==="legacy"&&kind!=="context"){const r=await preview(p,panel,model);assert(r.body.preview.errorRows===1&&r.body.preview.validRows===(kind==="duplicate"?6:5),"MARKS_INVALID_ROW_CLASSIFICATION");assert(await panel.getByRole("button",{name:"Review and confirm draft import",exact:true}).isDisabled(),"MARKS_INVALID_ROW_CONFIRMATION");await panel.locator("details").first().locator("summary").click();await health(p);}
     else{if(model==="governed"&&kind!=="context")code="EXAM_MARKS_REQUEST_REJECTED";await marksUiResponse(p,path,()=>panel.getByRole("button",{name:"Server validation / preview",exact:true}).click(),{status:400,error:expectedError,code});assertMarksUnchanged(b,await read());}
    }
    await upload(panel,workbook&&index%2===1?workbook:completed,model,!!workbook&&index%2===1);const result=await preview(p,panel,model);assert(result.body.preview.totalRows===6&&result.body.preview.validRows===6&&result.body.preview.errorRows===0,"MARKS_PREVIEW_COUNTS");
    await panel.getByText("Reviewed marks",{exact:true}).click();for(const s of f.students)assert((await panel.innerText()).includes(model==="legacy"?s.admissionNo:s.id),"MARKS_VISIBLE_REVIEW_ROSTER");
    const before=await read(),dialog=await marksDialog(p,panel,async()=>assertMarksUnchanged(before,await read()));await marksUiResponse(p,path,()=>dialog.getByRole("button",{name:"Confirm draft import",exact:true}).click());await dialog.waitFor({state:"hidden"});const after=await read();assertImportedMarks(before,after,f,model,model==="legacy"?"principal":"delegate");
    await p.reload();assertMarksUnchanged(after,await read());
    if(model==="governed"){for(const [i,s] of f.students.entries()){const control=p.getByLabel(`${s.studentName} Theory entry state`,{exact:true});assert(await control.inputValue()===entries[i].state,"MARKS_RENDERED_GRID_STATE");if(entries[i].state==="PRESENT")assert(await p.getByLabel(`${s.studentName} Theory marks`,{exact:true}).inputValue()===entries[i].marks,"MARKS_RENDERED_GRID_VALUE");}}
    await health(p);
   }
   // MB4: stale preview is invalidated by actual file/context controls.
   let panel=await select(delegate,"governed");const gpath=`/api/exam-marks/sheets/${f.assignmentId}`,gcontext:MarksContext={...f,model:"governed"};
   const currentTemplate=async()=>marksDownload(delegate,panel.getByRole("link",{name:"Download selected-context CSV template",exact:true}),"csv");
   let bytes=await currentTemplate(),changed=inputs(true);changed[0].marks="7.5";let completed=completeMarksTemplate(bytes,gcontext,changed);await upload(panel,completed,"governed");await preview(delegate,panel,"governed");
   const unchanged=await read();await panel.getByLabel("Completed CSV / XLSX",{exact:true}).setInputFiles([]);assert(await panel.getByRole("button",{name:"Review and confirm draft import",exact:true}).count()===0,"MARKS_EMPTY_SELECTION_STALE_PREVIEW");assertMarksUnchanged(unchanged,await read());
   await upload(panel,completed,"governed");await preview(delegate,panel,"governed");await panel.getByLabel("Exact context",{exact:true}).selectOption("");assert(await panel.getByRole("button",{name:"Review and confirm draft import",exact:true}).count()===0,"MARKS_CONTEXT_STALE_PREVIEW");assertMarksUnchanged(unchanged,await read());
   panel=await select(delegate,"governed");await upload(panel,completed,"governed");await preview(delegate,panel,"governed");await upload(panel,completed,"governed");assert(await panel.getByRole("button",{name:"Review and confirm draft import",exact:true}).count()===0,"MARKS_SAME_FILE_STALE_PREVIEW");
   if(index===0){const beforeDelayed=await read();await delayedMarksNavigation(delegate,gpath,()=>panel.getByRole("button",{name:"Server validation / preview",exact:true}).click(),async()=>{assert(await panel.getByLabel("Exact context",{exact:true}).isDisabled()&&await panel.getByLabel("Completed CSV / XLSX",{exact:true}).isDisabled(),"MARKS_PENDING_CONTEXT_NOT_LOCKED");await delegate.goto(origin+"/marks/import");await delegate.getByRole("heading",{name:"Legacy assessment CSV import",exact:true}).waitFor();});assert(await delegate.getByRole("button",{name:"Review and confirm draft import",exact:true}).count()===0,"MARKS_LATE_WRONG_MODEL_CONFIRMATION");assertMarksUnchanged(beforeDelayed,await read());panel=await select(delegate,"governed");await upload(panel,completed,"governed");}
   await preview(delegate,panel,"governed");let before=await read(),dialog=await marksDialog(delegate,panel,async()=>assertMarksUnchanged(before,await read()));
   const interruptedRequest=await interruptMarksResponse(delegate,gpath,()=>dialog.getByRole("button",{name:"Confirm draft import",exact:true}).click());await panel.getByText("Failed to fetch",{exact:true}).waitFor();
   let committed=await read(),sheet=committed.sheets.find((s:any)=>s.primaryAssignmentId===f.assignmentId);assert(sheet.optimisticVersion===3,"MARKS_INTERRUPTED_VERSION");assertMarksEvent(before.audits,committed.audits,{eventType:"DRAFT_SAVED",actorUserId:f.actors.delegate.id,assignmentId:f.assignmentId,targetId:sheet.id});assert(committed.entries.find((e:any)=>e.sheetId===sheet.id&&e.studentId===f.students[0].id)?.marksObtained==="7.5","MARKS_INTERRUPTED_AUTHORITATIVE_VALUE");
   // Reconciliation above proves the real commit before the same actor retries.
   const retry=await marksUiResponse(delegate,gpath,()=>dialog.getByRole("button",{name:"Confirm draft import",exact:true}).click());marksSame(retry.request,interruptedRequest,"MARKS_RETRY_IDENTITY");assertMarksUnchanged(committed,await read());
   panel=await select(delegate,"governed");bytes=await currentTemplate();changed[0].marks="8";completed=completeMarksTemplate(bytes,gcontext,changed);await upload(panel,completed,"governed");await preview(delegate,panel,"governed");
   // Concurrent positive control uses the real grid, whose autosave PUT is
   // observed, not generated by this harness. Stale import remains open.
   const concurrent=await login("concurrent");await select(concurrent,"governed");before=await read();await marksUiResponse(concurrent,gpath,()=>concurrent.getByLabel(`${f.students[0].studentName} Theory marks`,{exact:true}).fill("8.5"),{status:200},"PUT");await concurrent.getByText("Draft autosaved.",{exact:true}).waitFor();committed=await read();sheet=committed.sheets.find((s:any)=>s.primaryAssignmentId===f.assignmentId);assert(sheet.optimisticVersion===4&&committed.entries.find((e:any)=>e.sheetId===sheet.id&&e.studentId===f.students[0].id)?.marksObtained==="8.5","MARKS_CONCURRENT_CONTROL");assertMarksEvent(before.audits,committed.audits,{eventType:"DRAFT_SAVED",actorUserId:f.actors.concurrent.id,assignmentId:f.assignmentId,targetId:sheet.id});
   dialog=await marksDialog(delegate,panel,async()=>assertMarksUnchanged(committed,await read()));await marksUiResponse(delegate,gpath,()=>dialog.getByRole("button",{name:"Confirm draft import",exact:true}).click(),{status:409,error:"This mark sheet changed in another session. Reload it before saving.",code:"EXPECTED_VERSION_CONFLICT"});assertMarksUnchanged(committed,await read());
   if(index===0){panel=await select(delegate,"governed");bytes=await currentTemplate();completed=completeMarksTemplate(bytes,gcontext,changed);await upload(panel,completed,"governed");const pending=await preview(delegate,panel,"governed");before=await read();await waitMarksReceiptExpiry(pending.body.receipt);dialog=await marksDialog(delegate,panel,async()=>assertMarksUnchanged(before,await read()));const expired={status:400,error:"Import content, context or versions changed, or preview expired. Validate again."};await marksUiResponse(delegate,gpath,()=>dialog.getByRole("button",{name:"Confirm draft import",exact:true}).click(),expired);assertMarksUnchanged(before,await read());await marksUiResponse(delegate,gpath,()=>panel.getByRole("button",{name:"Server validation / preview",exact:true}).click(),expired);assertMarksUnchanged(before,await read());}
   panel=await select(delegate,"governed");bytes=await currentTemplate();completed=completeMarksTemplate(bytes,gcontext,changed);await upload(panel,completed,"governed");await preview(delegate,panel,"governed");before=await read();dialog=await marksDialog(delegate,panel,async()=>assertMarksUnchanged(before,await read()));
   const storage=()=>delegate.evaluate(async()=>({local:{...localStorage},databases:await indexedDB.databases()})),storedBefore=await storage();let attempts=0;const countAttempt=(r:any)=>{if(r.method()==="POST"&&r.url()===origin+gpath)attempts++;};delegate.on("request",countAttempt);const expectedOffline=expectedNetwork.get(delegate)??new Set<string>();expectedOffline.add(origin+gpath);expectedNetwork.set(delegate,expectedOffline);
   try{await delegate.context().setOffline(true);await dialog.getByRole("button",{name:"Confirm draft import",exact:true}).click();await dialog.getByRole("alert").getByText("Failed to fetch",{exact:true}).waitFor();assert(attempts===1,"MARKS_OFFLINE_REQUEST_CLASSIFICATION");assertMarksUnchanged(before,await read());marksSame(await storage(),storedBefore,"MARKS_OFFLINE_QUEUE_CREATED");}
   finally{await delegate.context().setOffline(false);}
   await delegate.reload();assertMarksUnchanged(before,await read());assert(attempts===1,"MARKS_OFFLINE_REPLAY");delegate.off("request",countAttempt);await health(delegate);
   // MB6 legacy reports are internal raw assessment analytics, not published
   // governed result snapshots. Independent literal expectations below.
   await principal.goto(origin+"/marks/reports");await principal.getByLabel("Academic year",{exact:true}).fill(f.academicYear);await principal.getByLabel("Exam code",{exact:true}).fill(f.examCode);await principal.getByRole("button",{name:"Apply Filters",exact:true}).click();await principal.waitForURL((u:URL)=>u.searchParams.get("examCode")===f.examCode);
   const headers=["Exam Code","Exam Name","Academic Year","Class","Section","Subject","Component","Assessment Type","Exam Status","Sheet Status","Maximum Marks","Pass Marks","Eligible","Entered","Missing","Present","Absent","Exempt","Not Applicable","Average","Highest","Lowest","Derived Pass","Derived Fail","Corrections"];
   const prefix=[f.examCode,"'"+f.examName,f.academicYear,f.className,"A",f.subjectName],exportBefore=await read();const report=await marksDownload(principal,principal.getByRole("link",{name:"Export Formula-Safe CSV",exact:true}),"csv");
   assertMarksExport(report,[headers,[...prefix,"Other","WRITTEN","OPEN_FOR_ENTRY","OPEN","10","4","6","0","6","0","0","0","0","","","","0","0","0"],[...prefix,"Theory","WRITTEN","OPEN_FOR_ENTRY","OPEN","10","4","6","6","0","3","1","1","1","5.75","10","0","2","1","0"]]);assertMarksUnchanged(exportBefore,await read());
   await principal.getByLabel("Academic year",{exact:true}).fill("2024-25");await principal.getByRole("button",{name:"Apply Filters",exact:true}).click();await principal.waitForURL((u:URL)=>u.searchParams.get("academicYear")==="2024-25");await principal.getByText("No authorised assessment data matches these filters.",{exact:true}).waitFor();assertMarksExport(await marksDownload(principal,principal.getByRole("link",{name:"Export Formula-Safe CSV",exact:true}),"csv"),[headers]);assertMarksUnchanged(exportBefore,await read());
   const reporter=await login("reporter"),reportUrl=origin+`/marks/reports?academicYear=${f.academicYear}&examCode=${f.examCode}`;await reporter.goto(reportUrl);const exportControl=reporter.getByRole("link",{name:"Export Formula-Safe CSV",exact:true});assertMarksExport(await marksDownload(reporter,exportControl,"csv"),parseCsv(report.toString()));await probe("deny-export");const exportPath=await exportControl.getAttribute("href");assert(exportPath?.startsWith("/api/marks/reports/export?"),"MARKS_EXPORT_CONTROL_TARGET");let deniedDownloads=0;const deniedDownload=()=>{deniedDownloads++;};reporter.on("download",deniedDownload);try{await marksUiResponse(reporter,exportPath,()=>exportControl.click(),{status:403,error:"You do not have permission for this action"},"GET");assert(deniedDownloads===0,"MARKS_DENIED_EXPORT_BYTES");}finally{reporter.off("download",deniedDownload);}assertMarksUnchanged(exportBefore,await read());await probe("restore-export");await reporter.goto(reportUrl);assertMarksExport(await marksDownload(reporter,reporter.getByRole("link",{name:"Export Formula-Safe CSV",exact:true}),"csv"),parseCsv(report.toString()));await health(reporter);
   // The existing governed reporting screen consumes only the separate,
   // nonempty LOCKED/ISSUED historical precondition, never imported drafts.
   await principal.goto(origin+"/academic-reports");await principal.getByRole("heading",{name:"Consolidated Academic Reporting",exact:true}).waitFor();await principal.getByLabel("Report family",{exact:true}).selectOption("OUTCOME_DISTRIBUTION");await principal.getByLabel("Academic year",{exact:true}).selectOption(f.history.academicYear);await principal.getByLabel("Class",{exact:true}).selectOption(f.className);await principal.getByLabel("Section",{exact:true}).selectOption("A");
   const published=principal.getByRole("group",{name:"Published examinations (maximum 12)",exact:true});for(const checkbox of await published.getByRole("checkbox").all())await checkbox.uncheck();await published.getByLabel(new RegExp(`\\(${f.history.examCode}\\)$`)).check();
   let reports=await probe("report-evidence");assert(reports.length===0,"MARKS_FRESH_REPORT_PRECONDITION");const generated=await marksUiResponse(principal,"/api/academic-reports/runs",()=>principal.getByRole("button",{name:"Generate governed report",exact:true}).click());
   marksSame(generated.request,{family:"OUTCOME_DISTRIBUTION",academicYear:f.history.academicYear,examinationCodes:[f.history.examCode],className:f.className,section:"A",subjectCode:null,normalizationRule:"NONE",includeAverageHighest:false,approvalReference:null},"MARKS_GOVERNED_REPORT_FILTERS");
   reports=await probe("report-evidence");assert(reports.length===1&&reports[0].sources.length===1,"MARKS_REPORT_SOURCE_COUNT");const reportRun=reports[0];assert(reportRun.createdByUserId===f.actors.principal.id&&reportRun.sources[0].resultSnapshotId===f.history.sources[0].snapshotId&&reportRun.sources[0].reportCardVersionId===f.history.sources[0].versionId,"MARKS_REPORT_EXACT_HISTORICAL_SOURCE");assertMarksEvent([],reportRun.auditEvents,{eventType:"RUN_GENERATED",actorUserId:f.actors.principal.id,reportRunId:reportRun.id});
   const outcomeRows=[["Grade","A","1"],["Pass result","PASS","1"],["Entry state","ABSENT","0"],["Entry state","EXEMPT","0"],["Entry state","N/A","0"],["Entry state","NOT_ENTERED","0"],["Entry state","ZERO","0"]],title="Grade, pass and entry-state distribution",sourceStatement="Generated only from immutable issued report-card versions backed by locked governed result snapshots. No raw marks or examination formula were recalculated.";
   const stored=JSON.parse(reportRun.immutableSummaryJson);marksSame(stored.sections[0].columns,["Distribution","Outcome","Count"],"MARKS_REPORT_COLUMNS");marksSame(stored.sections[0].rows.map((r:any)=>[r.Distribution,r.Outcome,String(r.Count)]),outcomeRows,"MARKS_REPORT_INDEPENDENT_VALUES");assert(stored.sections.length===1&&stored.parameters.academicYear===f.history.academicYear,"MARKS_REPORT_SECTION_SCOPE");
   for(const [format,mode,label] of [["CSV","MONOCHROME","Safe CSV"],["PDF","COLOUR","Colour PDF"],["PDF","MONOCHROME","Monochrome PDF"]] as const){
    const beforeReports=await probe("report-evidence"),path=`/api/academic-reports/runs/${reportRun.publicKey}/export`,response=principal.waitForResponse((r:any)=>new URL(r.url()).pathname===path&&r.request().method()==="POST");const downloaded=await marksDownload(principal,principal.getByRole("button",{name:label,exact:true}),format==="CSV"?"csv":"pdf"),r=await response;
    assert(r.status()===200&&r.headers()["cache-control"]==="private, no-store"&&r.headers()["x-content-type-options"]==="nosniff","MARKS_EXPORT_PRIVATE_HEADERS");marksSame(r.request().postDataJSON(),{format,mode},"MARKS_EXPORT_MODE");
    if(format==="CSV")assertMarksExport(downloaded,[["Report",title],["Generated at",stored.generatedAt],["Source",sourceStatement],[title],["Distribution","Outcome","Count"],...outcomeRows]);else await inspectMarksReportPdf(downloaded,[title,"Grade | A | 1","Pass result | PASS | 1","NOT_ENTERED | 0"],mode);
    const afterReports=await probe("report-evidence");assert(afterReports.length===1,"MARKS_EXPORT_DUPLICATE_RUN");assertMarksExportAudit(beforeReports[0].auditEvents,afterReports[0].auditEvents,f.actors.principal.id,reportRun.id,format,mode);marksSame(afterReports[0].immutableSummaryJson,reportRun.immutableSummaryJson,"MARKS_REPORT_SNAPSHOT_CHANGED");assertMarksUnchanged(exportBefore,await read());await health(principal);
   }
   const reportBeforeRetry=await probe("report-evidence");await marksUiResponse(principal,"/api/academic-reports/runs",()=>principal.getByRole("button",{name:"Generate governed report",exact:true}).click());assertMarksUnchanged(reportBeforeRetry,await probe("report-evidence"));
   // Changing filters invalidates old output immediately, including late
   // responses. A nonmatching paper is a real, syntactically valid empty scope.
   await principal.getByLabel("Assigned subject/paper code",{exact:true}).fill("NO_SUCH_PAPER");assert(await principal.getByRole("button",{name:"Safe CSV",exact:true}).count()===0,"MARKS_STALE_REPORT_EXPORT");await marksUiResponse(principal,"/api/academic-reports/runs",()=>principal.getByRole("button",{name:"Generate governed report",exact:true}).click(),{status:404,error:"No issued report versions matched the governed scope.",code:"ISSUED_SOURCE_MISSING"});assertMarksUnchanged(reportBeforeRetry,await probe("report-evidence"));assertMarksUnchanged(exportBefore,await read());await health(principal);
   // Existing authority stays valid until this explicit, labelled preparation.
   for(const [name,operation,status,error,code] of [["revoked","revoke",401,"Authentication required",undefined],["expired","expire",403,"You do not have permission for this action",undefined],["family","link-child",403,"Delegated operators cannot edit marks for their own linked child.","ACADEMIC_INTEGRITY_FAMILY_CONFLICT"]] as const){
    const p=await login(name),panel=await select(p,"governed"),context:MarksContext={...f,model:"governed"},bytes=await marksDownload(p,panel.getByRole("link",{name:"Download selected-context CSV template",exact:true}),"csv"),values=inputs(true);values[0].marks="8";await upload(panel,completeMarksTemplate(bytes,context,values),"governed");await preview(p,panel,"governed");const before=await read(),d=await marksDialog(p,panel,async()=>assertMarksUnchanged(before,await read()));const securityBefore=name==="family"?await probe("security-evidence",{actor:name}):[];await probe(operation);await marksUiResponse(p,`/api/exam-marks/sheets/${f.assignmentId}`,()=>d.getByRole("button",{name:"Confirm draft import",exact:true}).click(),{status,error,code});assertMarksUnchanged(before,await read());if(name==="family")assertMarksEvent(securityBefore,await probe("security-evidence",{actor:name}),{eventType:"MARKS_DELEGATION_FAMILY_CONFLICT_DENIED",actorUserId:f.actors.family.id,subjectType:"STUDENT_MARK_SCOPE",subjectId:f.students[0].id});await d.waitFor({state:"hidden"});if(name!=="family"){const canaries=privacyPolicies.get(p)!;canaries.push(...f.students.map((s:any)=>s.studentName));await p.context().addInitScript(observeMarksCanaries,canaries);await p.goto(origin+"/marks/governed");await p.waitForURL((u:URL)=>["/login","/unauthorized"].includes(u.pathname));}await health(p);
   }
   // Separate controlled read-only transition AFTER all import/authority
   // assertions. The import itself has already been proven draft-only.
   panel=await select(delegate,"governed");bytes=await currentTemplate();completed=completeMarksTemplate(bytes,gcontext,changed);await upload(panel,completed,"governed");await preview(delegate,panel,"governed");
   await select(concurrent,"governed");await marksUiResponse(concurrent,gpath,async()=>{await concurrent.getByLabel(`${f.students[5].studentName} Theory entry state`,{exact:true}).selectOption("PRESENT");await concurrent.getByLabel(`${f.students[5].studentName} Theory marks`,{exact:true}).fill("1");},{status:200},"PUT");await concurrent.getByText("Draft autosaved.",{exact:true}).waitFor();before=await read();
   await concurrent.getByRole("button",{name:"Final submit",exact:true}).click();const submit=concurrent.getByRole("dialog",{name:"Final submission",exact:true});await submit.waitFor();const submitted=await marksUiResponse(concurrent,gpath+"/submit",()=>submit.getByRole("button",{name:"Submit final",exact:true}).click());assert(submitted.body.submitted===true&&submitted.body.status==="SUBMITTED","MARKS_CONTROLLED_SUBMISSION_PRECONDITION");const locked=await read();sheet=locked.sheets.find((s:any)=>s.primaryAssignmentId===f.assignmentId);assert(sheet.status==="SUBMITTED"&&sheet.submittedByUserId===f.actors.concurrent.id,"MARKS_READ_ONLY_TARGET");assertMarksEvent(before.audits,locked.audits,{eventType:"SHEET_SUBMITTED",actorUserId:f.actors.concurrent.id,assignmentId:f.assignmentId,targetId:sheet.id});assertMarksUnchanged(initial.history,locked.history);assert(locked.results.length===0,"MARKS_CONTROLLED_SUBMIT_PUBLISHED");
   dialog=await marksDialog(delegate,panel,async()=>assertMarksUnchanged(locked,await read()));await marksUiResponse(delegate,gpath,()=>dialog.getByRole("button",{name:"Confirm draft import",exact:true}).click(),{status:400,error:"Governed sheet is read-only.",code:"EXAM_MARKS_REQUEST_REJECTED"});assertMarksUnchanged(locked,await read());
   // The other assignment is valid for leadership, absent from the delegate's
   // exact list. Direct page navigation must also return an empty workspace.
   await principal.goto(origin+`/marks/governed?assignmentId=${f.otherAssignmentId}`);await principal.getByLabel("Authorised assignment",{exact:true}).selectOption(f.otherAssignmentId);await principal.getByRole("heading",{name:"Governed Marks Entry",exact:true}).waitFor();const scopeBefore=await read();await delegate.goto(origin+`/marks/governed?assignmentId=${f.otherAssignmentId}`);await delegate.getByText("No exact active examination marks assignment is available.",{exact:true}).waitFor();assert(await delegate.getByLabel("Exact context",{exact:true}).locator("option").count()===1,"MARKS_WRONG_SCOPE_VISIBLE");assertMarksUnchanged(scopeBefore,await read());await health(delegate);
   for(const name of ["teacher","parent","viewer","operator"] as const){const p=await login(name,true),before=await read();for(const path of ["/marks/import","/marks/governed","/marks/reports"]){await p.goto(origin+path);await p.waitForURL((u:URL)=>u.pathname==="/unauthorized"||u.pathname==="/login");await health(p);}assertMarksUnchanged(before,await read());}
   const anonymous=await newPage(f.students.map((s:any)=>s.studentName));for(const path of ["/marks/import","/marks/governed","/marks/reports"]){await anonymous.goto(origin+path);await anonymous.waitForURL((u:URL)=>u.pathname==="/login");await health(anonymous);}assertMarksUnchanged(scopeBefore,await read());
   await Promise.all(privacyReads);assert(errors.length===0,"MARKS_BROWSER_PRIVATE_OR_FRAMEWORK_FAILURE");for(const e of consoleErrors){const status=/^Failed to load resource: the server responded with a status of (400|401|403|404|409) \(.*\)$/.exec(e.text);assert((status&&observedDenials.get(e.page)?.has(`${e.url}|${status[1]}`))||(/^Failed to load resource: net::ERR_(ABORTED|INTERNET_DISCONNECTED)$/.test(e.text)&&expectedNetwork.get(e.page)?.has(e.url)),"MARKS_UNEXPECTED_CONSOLE_ERROR");}
  },browser);
  results.push({viewport:matrix.viewport,theme:matrix.colorScheme,evidenceClass:"RENDERED_APPLICATION",coverage:"MARKS_SLICE_COMPLETE",scenarios:MARKS_BROWSER_SCENARIOS,zoom:"VIEWPORT_REFLOW_ONLY"});
 }
 return {classification:"AUTHENTICATED_SYNTHETIC_TEST_IMAGE_BROWSER",source:input.source,results,mandatoryCoverage:"PARTIAL"};
}
