import {
  PERMISSIONS,
  RECOMMENDED_ROLE_PERMISSIONS,
  normalizePermission,
  type CanonicalPermission,
  type Role
} from "@/lib/permissions";

export type PermissionDelegability =
  | "ORDINARY_DELEGABLE"
  | "LEADERSHIP_RESTRICTED"
  | "SUPER_ADMIN_ONLY_NON_DELEGABLE"
  | "OBJECT_SCOPED";

export const SUPER_ADMIN_ONLY_PERMISSIONS = new Set<CanonicalPermission>([
  "GRANT_SUPER_ADMIN",
  "MANAGE_ROLE_PERMISSIONS",
  "FIRST_RUN_SETUP",
  "RUN_RESTORE",
  "ACTIVATE_LIVE_CLOUD_BACKUP",
  "CHANGE_CLOUD_BACKUP_KEY_VERSION",
  "PURGE_CLOUD_BACKUPS"
  ,"VIEW_RELEASE_OPERATIONS"
  ,"EXECUTE_RELEASE"
  ,"ROLLBACK_RELEASE"
  ,"MANAGE_RELEASE_FEATURE_FLAGS"
]);

export const CRITICAL_SUPER_ADMIN_PERMISSIONS = new Set<CanonicalPermission>([
  ...SUPER_ADMIN_ONLY_PERMISSIONS,
  "VIEW_IAM_ACCESS",
  "MANAGE_IAM_USERS",
  "MANAGE_PERMISSION_PROFILES",
  "ASSIGN_PERMISSION_PROFILES",
  "MANAGE_USER_PERMISSION_OVERRIDES",
  "VIEW_IAM_AUDIT",
  "DELEGATE_IAM_ACCESS"
]);

export const LEADERSHIP_RESTRICTED_PERMISSIONS = new Set<CanonicalPermission>([
  "MANAGE_IAM_USERS",
  "MANAGE_PERMISSION_PROFILES",
  "ASSIGN_PERMISSION_PROFILES",
  "MANAGE_USER_PERMISSION_OVERRIDES",
  "DELEGATE_IAM_ACCESS",
  "RESET_USER_PASSWORDS",
  "APPROVE_STUDENT_PROGRESSION",
  "FINALIZE_STUDENT_PROGRESSION",
  "APPROVE_EXPENSES",
  "LOCK_BUDGETS",
  "APPROVE_CASH_BOOK",
  "LOCK_CASH_BOOK",
  "APPROVE_MARKS",
  "LOCK_EXAMS",
  "MANAGE_EXAM_TIMETABLE",
  "PUBLISH_EXAM_TIMETABLE",
  "MANAGE_ACADEMIC_CALENDAR",
  "REVIEW_ACADEMIC_CALENDAR",
  "PUBLISH_ACADEMIC_CALENDAR",
  "PUBLISH_EMERGENCY_CLOSURE",
  "MANAGE_SCHOOL_EVENTS",
  "REVIEW_SCHOOL_EVENTS",
  "PUBLISH_SCHOOL_EVENTS",
  "EXPORT_ACADEMIC_CALENDAR",
  "INTERVENE_EXAM_SCHEMES",
  "INTERVENE_EXAM_MARKS",
  "MANAGE_SALARY_STRUCTURES",
  "ASSIGN_COMPENSATION",
  "APPROVE_PAYROLL",
  "LOCK_PAYROLL",
  "REVERSE_PAYROLL",
  "APPROVE_SALARY_ADVANCES"
  ,"MANAGE_PARENT_MEETINGS"
  ,"EXPORT_PARENT_MEETING_REPORTS"
  ,"APPROVE_STUDENT_DEPARTURE"
  ,"EMERGENCY_OVERRIDE_STUDENT_DEPARTURE"
  ,"RECORD_UNAUTHORISED_EXIT"
  ,"VIEW_DEPARTURE_AUDIT"
  ,"MANAGE_STANDING_EXIT_PERMISSION"
  ,"CORRECT_STUDENT_EXIT_RECORD"
  ,"VIEW_RELEASE_OPERATIONS_SUMMARY"
  ,"APPROVE_RELEASE_CANDIDATE"
]);

export const RELEASE_OPERATIONS_PERMISSIONS = new Set<CanonicalPermission>([
  "VIEW_RELEASE_OPERATIONS_SUMMARY", "VIEW_RELEASE_OPERATIONS", "APPROVE_RELEASE_CANDIDATE",
  "EXECUTE_RELEASE", "ROLLBACK_RELEASE", "MANAGE_RELEASE_FEATURE_FLAGS"
]);

export const OBJECT_SCOPED_PERMISSIONS = new Set<CanonicalPermission>([
  ...PERMISSIONS.filter((permission) => permission.includes("_OWN_") || permission.startsWith("VIEW_OWN_")),
  ...PERMISSIONS.filter((permission) => /STUDENT|GUARDIAN|STAFF|ATTENDANCE|HOMEWORK|CLASSWORK|EXAM|MARKS|REPORT_CARD|CERTIFICATE|CLASS_X|ID_CARD|PAYMENT|LEDGER|RECEIPT|DAILY_COLLECTION|PENDING_DUES|VENDOR|EXPENSE|BUDGET|MISC_INCOME|CASH_BOOK|BOOKS_FINANCE|LIBRARY|TEACHER_ANALYTICS/.test(permission)),
  ...PERMISSIONS.filter((permission) => /DEPARTURE|GATE_PASS|CAMPUS_ROSTER|UNAUTHORISED_EXIT/.test(permission)),
  "REQUEST_OWN_CHILD_CERTIFICATES",
  "VIEW_OWN_CHILD_CERTIFICATES",
  "REQUEST_OWN_CHILD_CLASS_X_PACKAGE",
  "VIEW_OWN_CHILD_CLASS_X_PACKAGE",
  "ENTER_ASSIGNED_EXAM_MARKS",
  "SUBMIT_ASSIGNED_EXAM_MARKS",
  "REQUEST_EXAM_MARK_CORRECTION",
  "VIEW_EXAMS",
  "ENTER_MARKS",
  "SUBMIT_MARKS",
  "VIEW_EXAM_REPORTS",
  "EXPORT_EXAM_REPORTS",
  "VIEW_REPORT_CARDS",
  "ENTER_REPORT_CARD_DATA",
  "SUBMIT_REPORT_CARDS",
  "VIEW_REPORT_CARD_REPORTS",
  "EXPORT_REPORT_CARD_REPORTS",
  "VIEW_STUDENT_ATTENDANCE",
  "MANAGE_STUDENT_ATTENDANCE",
  "SUBMIT_STUDENT_ATTENDANCE",
  "LOCK_STUDENT_ATTENDANCE",
  "VIEW_STUDENT_ATTENDANCE_REPORTS",
  "VIEW_HOMEWORK",
  "MANAGE_HOMEWORK",
  "PUBLISH_HOMEWORK",
  "ARCHIVE_HOMEWORK",
  "VIEW_HOMEWORK_REPORTS",
  "EXPORT_HOMEWORK_REPORTS",
  "VIEW_STAFF_LEAVE",
  "APPLY_STAFF_LEAVE",
  "MANAGE_STAFF_LEAVE",
  "APPROVE_STAFF_LEAVE",
  "VIEW_STAFF_LEAVE_REPORTS",
  "VIEW_SUBSTITUTES",
  "MANAGE_SUBSTITUTES",
  "ASSIGN_SUBSTITUTES",
  "CONFIRM_SUBSTITUTES",
  "VIEW_SUBSTITUTE_REPORTS",
  "CREATE_SCOPED_NOTIFICATIONS",
  "PROPOSE_SCHOOL_EVENTS",
  "VIEW_STAFF_CALENDAR",
  "VIEW_OWN_CALENDAR",
  "VIEW_PAYMENTS",
  "EDIT_PAYMENTS",
  "CANCEL_PAYMENTS",
  "RESTORE_PAYMENTS",
  "VIEW_LEDGER"
]);

export const ACADEMIC_INTEGRITY_MARKS_WRITE_PERMISSIONS = new Set<CanonicalPermission>([
  "ENTER_MARKS", "SUBMIT_MARKS", "APPROVE_MARKS", "LOCK_EXAMS", "CORRECT_APPROVED_MARKS",
  "ENTER_ASSIGNED_EXAM_MARKS", "SUBMIT_ASSIGNED_EXAM_MARKS", "REQUEST_EXAM_MARK_CORRECTION",
  "MODERATE_EXAM_MARKS", "REOPEN_EXAM_MARK_SHEETS", "RUN_EXAM_CALCULATIONS",
  "LOCK_EXAM_CALCULATIONS", "INTERVENE_EXAM_MARKS", "ENTER_REPORT_CARD_DATA", "SUBMIT_REPORT_CARDS"
]);

const VIEWER_IMMUTABLE_DENIALS = new Set<CanonicalPermission>([
  "VIEW_LIBRARY_STOCK_VERIFICATION",
  "VIEW_UDISE_MASKED_ROWS",
  "VIEW_LEDGER",
  "PRINT_LEDGER",
  ...PERMISSIONS.filter((permission) => permission.startsWith("EXPORT_"))
]);

const COMPUTER_OPERATOR_IMMUTABLE_DENIALS = new Set<CanonicalPermission>([
  "MANAGE_ROLE_PERMISSIONS",
  "GRANT_SUPER_ADMIN",
  "DELEGATE_IAM_ACCESS",
  "MANAGE_PERMISSION_PROFILES",
  "ASSIGN_PERMISSION_PROFILES",
  "MANAGE_USER_PERMISSION_OVERRIDES",
  "RUN_RESTORE",
  "MANAGE_SCHOOL_SETTINGS",
  ...PERMISSIONS.filter((permission) => /PAYMENT|EXPENSE|BUDGET|CASH_BOOK|BOOKS_FINANCE|MISC_INCOME|PAYROLL|SALARY|PAYSLIP|COMPENSATION/.test(permission))
]);

export function permissionDelegability(permission: CanonicalPermission): PermissionDelegability {
  if (SUPER_ADMIN_ONLY_PERMISSIONS.has(permission)) return "SUPER_ADMIN_ONLY_NON_DELEGABLE";
  if (OBJECT_SCOPED_PERMISSIONS.has(permission)) return "OBJECT_SCOPED";
  if (LEADERSHIP_RESTRICTED_PERMISSIONS.has(permission)) return "LEADERSHIP_RESTRICTED";
  return "ORDINARY_DELEGABLE";
}

export function immutablePermissionDenial(role: Role, rawPermission: string) {
  const permission = normalizePermission(rawPermission);
  if (!permission) return "Unknown permissions always default to deny.";
  if (role === "TEACHER" && ACADEMIC_INTEGRITY_MARKS_WRITE_PERMISSIONS.has(permission)) {
    return "Academic Integrity v1.1 permanently denies marks-write authority to every Teacher role context.";
  }
  if (role !== "SUPER_ADMIN" && SUPER_ADMIN_ONLY_PERMISSIONS.has(permission)) {
    return "This security invariant is reserved to the Super Admin context and cannot be delegated.";
  }
  if (!(["SUPER_ADMIN", "DIRECTOR"] as Role[]).includes(role) && RELEASE_OPERATIONS_PERMISSIONS.has(permission)) {
    return "Release Operations access is restricted to governed Super Admin and Director contexts and cannot be delegated.";
  }
  if (role === "VIEWER" && VIEWER_IMMUTABLE_DENIALS.has(permission)) {
    return "Viewer access is permanently restricted for this permission.";
  }
  if (role === "COMPUTER_OPERATOR" && COMPUTER_OPERATOR_IMMUTABLE_DENIALS.has(permission)) {
    return "Computer Operator access cannot be expanded into unrestricted administration or finance authority.";
  }
  return null;
}

export function roleSupportsObjectScopedPermission(role: Role, permission: CanonicalPermission) {
  if (
    ["ENTER_MARKS", "SUBMIT_MARKS", "VIEW_EXAM_REPORTS", "VIEW_OWN_EXAM_MARKS", "ENTER_ASSIGNED_EXAM_MARKS", "SUBMIT_ASSIGNED_EXAM_MARKS", "REQUEST_EXAM_MARK_CORRECTION"].includes(permission) &&
    ["ADMIN", "ACCOUNTANT", "COMPUTER_OPERATOR", "VIEWER"].includes(role)
  ) return true;
  return !OBJECT_SCOPED_PERMISSIONS.has(permission) || RECOMMENDED_ROLE_PERMISSIONS[role].has(permission);
}

export function permissionCanAppearInProfile(permission: CanonicalPermission) {
  return !SUPER_ADMIN_ONLY_PERMISSIONS.has(permission) && !ACADEMIC_INTEGRITY_MARKS_WRITE_PERMISSIONS.has(permission);
}

export function permissionCanBeDelegatedByProfile(permission: CanonicalPermission) {
  return permissionCanAppearInProfile(permission);
}
