"use client";
import { useMemo, useState } from "react";
import Link from "next/link";

export function AdmissionsPublicEnquiryForm() {
  const requestKey = useMemo(() => crypto.randomUUID(), []); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const formElement = event.currentTarget; const form = new FormData(formElement); const body = { guardianName: form.get("guardianName"), contactMethod: form.get("contactMethod"), contactValue: form.get("contactValue"), desiredAcademicYear: form.get("desiredAcademicYear"), desiredClass: form.get("desiredClass"), childName: form.get("childName"), enquirySource: form.get("enquirySource"), message: form.get("message"), privacyNoticeVersion: "ADMISSIONS-PRIVACY-DRAFT-V1", consentVersion: "ADMISSIONS-CONSENT-V1", consent: form.get("consent") === "on", honeypot: form.get("website"), requestKey }; try { await fetch("/api/public/admissions/enquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body), cache: "no-store" }); setMessage("Thank you. If appropriate, the school admissions team will follow up using the contact provided."); formElement.reset(); } catch { setMessage("Thank you. Your request has been received for review."); } finally { setBusy(false); } }
  return <section className="public-section admissions-public-section" aria-labelledby="admissions-enquiry-title"><div className="public-section-heading"><span>Optional enquiry</span><h2 id="admissions-enquiry-title">Share only the minimum needed to contact you</h2><p>No Student, Guardian, User or enrollment record is created from this form. Do not enter an address, ID number, medical detail, payment detail or document.</p></div><form className="admissions-public-form" onSubmit={submit}><label>Parent or Guardian name<input name="guardianName" autoComplete="name" maxLength={100} required /></label><label>Contact method<select name="contactMethod" defaultValue="PHONE"><option value="PHONE">Phone</option><option value="EMAIL">Email</option></select></label><label>Phone or email<input name="contactValue" autoComplete="tel" maxLength={254} required /></label><label>Desired academic year<input name="desiredAcademicYear" defaultValue="2026-27" pattern="20[0-9]{2}-[0-9]{2}" required /></label><label>Desired class<input name="desiredClass" maxLength={40} required /></label><label>Child name <span>(optional)</span><input name="childName" maxLength={100} /></label><label>How you heard about the school<select name="enquirySource" defaultValue="WEBSITE"><option value="WEBSITE">Website</option><option value="REFERRAL">Referral</option><option value="PHONE">Phone</option><option value="WALK_IN">Walk-in</option><option value="OTHER">Other</option></select></label><label className="wide">Short message <span>(optional, no sensitive details)</span><textarea name="message" maxLength={800} rows={4} /></label><label className="admissions-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><label className="admissions-consent wide"><input name="consent" type="checkbox" required /><span>I have read the <Link href="/privacy">privacy notice</Link> and agree that the school may use these minimum details to respond to this enquiry. This box is intentionally unchecked.</span></label><button className="public-primary-button wide" disabled={busy}>{busy ? "Sending…" : "Send minimal enquiry"}</button><p className="admissions-live wide" role="status" aria-live="polite">{message}</p></form><p className="admissions-application-link">Already invited? <Link href="/admissions/apply">Open the invitation-only application</Link>.</p></section>;
}
