"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
type Target = { academicYear: string; className: string; section: string; subjectName: string; timetableSubjectId: string };
export function AssessmentForm({ examId, academicYear, targets }: { examId: string; academicYear: string; targets: Target[] }) {
  const router = useRouter(); const [form, setForm] = useState({ academicYear, className: "", section: "", subjectName: "", timetableSubjectId: "", componentName: "", assessmentType: "THEORY", maxMarks: "100", passMarks: "", weightagePercent: "", instructions: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const selected = `${form.academicYear}|${form.className}|${form.section}|${form.timetableSubjectId}`;
  function choose(key: string) { const target = targets.find((item) => `${item.academicYear}|${item.className}|${item.section}|${item.timetableSubjectId}` === key); if (target) setForm((value) => ({ ...value, ...target })); }
  const field = (key: keyof typeof form) => ({ value: form[key], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setForm((value) => ({ ...value, [key]: event.target.value })) });
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(`/api/exams/${encodeURIComponent(examId)}/assessments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to create assessment"); router.push(`/exams/${encodeURIComponent(examId)}/assessments`); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create assessment"); } finally { setBusy(false); } }
  return <form className="card card-pad form-grid exam-form" onSubmit={save}><label className="full">Class, section, and subject<select required aria-label="Assessment timetable target" value={selected} onChange={(event) => choose(event.target.value)}><option value="|||">Choose exact timetable target</option>{targets.map((item) => { const key = `${item.academicYear}|${item.className}|${item.section}|${item.timetableSubjectId}`; return <option key={key} value={key}>{item.className}-{item.section || "Class-wide"} — {item.subjectName}</option>; })}</select></label><label>Component (optional)<input maxLength={80} placeholder="Theory" {...field("componentName")} /></label><label>Assessment type<select {...field("assessmentType")}>{["THEORY", "PRACTICAL", "ORAL", "PROJECT", "INTERNAL", "OTHER"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Maximum marks<input required min="0.0001" step="0.0001" type="number" {...field("maxMarks")} /></label><label>Pass marks (optional)<input min="0" step="0.0001" type="number" {...field("passMarks")} /></label><label>Weightage % (optional)<input min="0" max="100" step="0.0001" type="number" {...field("weightagePercent")} /></label><label className="full">Instructions (optional)<textarea rows={3} maxLength={2000} {...field("instructions")} /></label><div className="full page-actions"><button type="submit" disabled={busy || !form.timetableSubjectId}>Add Assessment</button></div>{!targets.length ? <div className="full notice">No active timetable assignment targets exist for this academic year.</div> : null}{error ? <div className="full notice danger" role="alert">{error}</div> : null}</form>;
}
