"use client";

import { FormEvent, useMemo, useState } from "react";

type WorkspaceProps = { initialData: any; capabilities: Record<string, boolean> };

async function postAction(action: string, payload: Record<string, unknown>) {
  const response = await fetch("/api/attendance/staff/biometric", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.code || body.error || "Biometric attendance action failed");
  return body;
}

function values(event: FormEvent<HTMLFormElement>) { return Object.fromEntries(new FormData(event.currentTarget).entries()); }
function dateTime(value: unknown) { return value ? new Date(String(value)).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }) : "-"; }

export function BiometricAttendanceWorkspace({ initialData, capabilities }: WorkspaceProps) {
  const [data, setData] = useState(initialData), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const refresh = async () => { const response = await fetch("/api/attendance/staff/biometric", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.code || body.error); setData(body); };
  const run = async (action: string, payload: Record<string, unknown>) => { setBusy(true); setMessage(""); try { await postAction(action, payload); await refresh(); setMessage(`${action.replaceAll("_", " ")} completed.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed"); } finally { setBusy(false); } };
  const submit = (action: string) => async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); await run(action, values(event)); };
  const exceptions = data.punches.filter((row: any) => row.reconciliationStatus !== "RECONCILED"), backlog = data.reconciliations.filter((row: any) => row.status !== "APPROVED");
  const monthly = useMemo(() => {
    const rows = new Map<string, { month: string; staff: string; present: number; late: number; exceptions: number; total: number }>();
    for (const row of data.reconciliations) { const month = String(row.attendanceDate).slice(0, 7), key = `${month}:${row.staffMemberId}`, current = rows.get(key) ?? { month, staff: row.staffMember?.fullName ?? row.staffMemberId, present: 0, late: 0, exceptions: 0, total: 0 }; current.total++; if (["PRESENT", "EARLY_DEPARTURE"].includes(row.outcome)) current.present++; if (["LATE", "LATE_AND_EARLY"].includes(row.outcome)) current.late++; if (row.status === "EXCEPTION") current.exceptions++; rows.set(key, current); }
    return [...rows.values()].slice(0, 200);
  }, [data.reconciliations]);

  return <div className="stack">
    <section className="card"><div className="section-title"><div><h3>Privacy and activation boundary</h3><p className="muted-text">Normalized attendance evidence only. No fingerprint image/template, facial image/template, vendor biometric database, card secret or device administrator password is accepted or stored. The feature is default OFF; simulator clearance is not K30 Pro certification and has no automatic payroll consequence.</p></div></div>{message ? <p role="status" className="notice">{message}</p> : null}</section>

    <section className="card"><div className="section-title"><div><h3>Device registry and bridge governance</h3><p className="muted-text">Devices are private-LAN endpoints behind a registered bridge. Vendor adapters remain blocked until official protocol proof.</p></div></div>
      {capabilities.devices ? <div className="grid two">
        <form className="form-grid" onSubmit={submit("CREATE_BRIDGE")}><h4>Register bridge public credential</h4><label>Bridge label<input name="label" required maxLength={100}/></label><label className="full-width">Ed25519 or P-256 public JWK<textarea name="publicSigningKey" required rows={4}/></label><button className="button" disabled={busy}>Prepare bridge</button></form>
        <form className="form-grid" onSubmit={submit("REGISTER_DEVICE")}><h4>Register allow-listed device</h4><label>Bridge<select name="bridgeId" required>{data.bridges.filter((row:any)=>row.status==="ACTIVE").map((row:any)=><option value={row.id} key={row.id}>{row.label}</option>)}</select></label><label>Vendor<input name="vendor" required defaultValue="eSSL"/></label><label>Model<input name="model" required defaultValue="K30 Pro"/></label><label>Firmware<input name="firmware"/></label><label>Serial reference<input name="serialReference" placeholder="Stored masked"/></label><label>Campus<input name="campus" required/></label><label>Location<input name="location" required/></label><label>Protocol<select name="protocolProfile" defaultValue="SIMULATOR"><option>SIMULATOR</option><option>GENERIC_CSV_IMPORT</option><option>ESSL_K30_PRO_PUSH</option><option>ESSL_ZK_LAN_SDK</option><option>ZK_ADMS_PUSH</option></select></label><button className="button" disabled={busy}>Prepare device</button></form>
      </div> : null}
      <div className="table-wrap"><table><thead><tr><th>Bridge</th><th>Status</th><th>Key</th><th>Last sync</th><th>Action</th></tr></thead><tbody>{data.bridges.map((row:any)=><tr key={row.id}><td>{row.label}<small className="muted-text"> {row.publicBridgeId}</small></td><td>{row.status}</td><td>{row.keyAlgorithm} v{row.keyVersion}</td><td>{dateTime(row.lastSyncAt)}</td><td>{capabilities.devices&&row.status==="PENDING_APPROVAL"?<button className="button secondary" disabled={busy} onClick={()=>run("APPROVE_BRIDGE",{id:row.id})}>Approve</button>:null}{capabilities.devices&&row.status==="ACTIVE"?<button className="button danger" disabled={busy} onClick={()=>run("REVOKE_BRIDGE",{id:row.id,reason:"Governed operator revocation"})}>Revoke</button>:null}</td></tr>)}{!data.bridges.length?<tr><td colSpan={5}>No bridge registered.</td></tr>:null}</tbody></table></div>
      <div className="table-wrap"><table><thead><tr><th>Device</th><th>Location</th><th>Profile / proof</th><th>Health</th><th>Clock drift</th><th>Last event</th><th>Action</th></tr></thead><tbody>{data.devices.map((row:any)=><tr key={row.id}><td>{row.vendor} {row.model}<small className="muted-text"> {row.serialReferenceMasked??""}</small></td><td>{row.campus} · {row.location}</td><td>{row.protocolProfile}<small className="muted-text"> {row.protocolProofStatus}</small></td><td>{row.status} · {row.healthStatus}</td><td>{row.clockDriftStatus} · {row.clockDriftSeconds==null?"unknown":`${row.clockDriftSeconds}s`}</td><td>{dateTime(row.lastEventAt)}</td><td>{capabilities.devices&&row.status==="PENDING_APPROVAL"?<button className="button secondary" disabled={busy||!row.profileStatus.ingestionAllowed} onClick={()=>run("APPROVE_DEVICE",{id:row.id})}>Approve</button>:null}{capabilities.devices&&row.status==="ACTIVE"?<button className="button danger" disabled={busy} onClick={()=>run("REVOKE_DEVICE",{id:row.id,reason:"Governed device revocation"})}>Revoke</button>:null}</td></tr>)}{!data.devices.length?<tr><td colSpan={7}>No device registered.</td></tr>:null}</tbody></table></div>
    </section>

    <section className="card"><div className="section-title"><div><h3>Staff mapping queue</h3><p className="muted-text">Opaque device user IDs are never name-matched. A second authorised person must approve each mapping.</p></div></div>
      {capabilities.prepareMapping?<form className="form-grid" onSubmit={submit("PREPARE_MAPPING")}><label>Active device<select name="deviceId" required>{data.devices.filter((row:any)=>row.status==="ACTIVE").map((row:any)=><option value={row.id} key={row.id}>{row.model} · {row.location}</option>)}</select></label><label>Opaque device user ID<input name="opaqueDeviceUserId" required maxLength={128}/></label><label>Active Staff<select name="staffMemberId" required>{data.activeStaff.map((row:any)=><option value={row.id} key={row.id}>{row.fullName} · {row.staffCode??"no code"}</option>)}</select></label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>Effective to<input name="effectiveTo" type="date"/></label><label>Reason<input name="reason" required maxLength={500}/></label><button className="button" disabled={busy}>Prepare mapping</button></form>:null}
      <div className="table-wrap"><table><thead><tr><th>Device user</th><th>Device</th><th>Staff</th><th>Effective</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.mappings.map((row:any)=><tr key={row.id}><td>{row.opaqueDeviceUserId}</td><td>{row.device.model} · {row.device.campus}</td><td>{row.staffMember.fullName}<small className="muted-text"> {row.staffMember.status}</small></td><td>{String(row.effectiveFrom).slice(0,10)} to {row.effectiveTo?String(row.effectiveTo).slice(0,10):"open"}</td><td>{row.status}</td><td>{capabilities.approveMapping&&row.status==="PENDING_APPROVAL"?<button className="button secondary" disabled={busy} onClick={()=>run("APPROVE_MAPPING",{id:row.id})}>Approve</button>:null}{capabilities.approveMapping&&row.status==="ACTIVE"?<button className="button danger" disabled={busy} onClick={()=>run("REVOKE_MAPPING",{id:row.id,reason:"Governed mapping revocation"})}>Revoke</button>:null}</td></tr>)}{!data.mappings.length?<tr><td colSpan={6}>No mapping prepared.</td></tr>:null}</tbody></table></div>
    </section>

    <section className="card"><div className="section-title"><div><h3>Shift policy and reconciliation queue</h3><p className="muted-text">Published operational calendar and approved Staff leave are applied before first-IN/last-OUT rules. Overnight shifts remain a later configured gate.</p></div></div>
      {capabilities.devices?<form className="form-grid" onSubmit={submit("CREATE_POLICY")}><label>Policy name<input name="name" required/></label><label>Campus<input name="campus" required/></label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>Effective to<input name="effectiveTo" type="date"/></label><label>Shift start<input name="shiftStartTime" type="time" required/></label><label>Shift end<input name="shiftEndTime" type="time" required/></label><label>Grace minutes<input name="graceMinutes" type="number" min="0" max="240" defaultValue="10"/></label><label>Early grace<input name="earlyDepartureGraceMinutes" type="number" min="0" max="240" defaultValue="10"/></label><label>Half-day minutes<input name="halfDayThresholdMinutes" type="number" min="1" max="1440" defaultValue="240"/></label><button className="button" disabled={busy}>Prepare policy</button></form>:null}
      <div className="table-wrap"><table><thead><tr><th>Policy</th><th>Campus</th><th>Shift</th><th>Effective</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.policies.map((row:any)=><tr key={row.id}><td>{row.name}</td><td>{row.campus}</td><td>{row.shiftStartTime}–{row.shiftEndTime}</td><td>{String(row.effectiveFrom).slice(0,10)}</td><td>{row.status}</td><td>{capabilities.devices&&row.status==="DRAFT"?<button className="button secondary" disabled={busy} onClick={()=>run("APPROVE_POLICY",{id:row.id})}>Approve</button>:null}</td></tr>)}</tbody></table></div>
      {capabilities.reconcile?<form className="toolbar" onSubmit={submit("RECONCILE_DATE")}><label>Attendance date<input type="date" name="attendanceDate" required/></label><button className="button" disabled={busy}>Run deterministic reconciliation</button></form>:null}
      <div className="stats"><div className="stat"><span>Backlog</span><strong>{backlog.length}</strong></div><div className="stat"><span>Raw exceptions</span><strong>{exceptions.length}</strong></div><div className="stat"><span>Open sequence gaps</span><strong>{data.gaps.filter((row:any)=>row.status==="OPEN").length}</strong></div></div>
      <div className="table-wrap"><table><thead><tr><th>Date</th><th>Staff</th><th>Outcome</th><th>IN / OUT</th><th>Punches</th><th>Status</th><th>Exception</th><th>Action</th></tr></thead><tbody>{data.reconciliations.map((row:any)=><tr key={row.id}><td>{String(row.attendanceDate).slice(0,10)}</td><td>{row.staffMember.fullName}<small className="muted-text"> {row.staffMember.staffCode??""}</small></td><td>{row.outcome}</td><td>{row.checkInTime??"-"} / {row.checkOutTime??"-"}</td><td>{row.punchCount}</td><td>{row.status}</td><td>{row.exceptionCode??"-"}</td><td>{capabilities.approveAttendance&&row.status==="READY_FOR_APPROVAL"?<button className="button secondary" disabled={busy} onClick={()=>run("APPROVE_RECONCILIATION",{id:row.id})}>Approve</button>:null}</td></tr>)}{!data.reconciliations.length?<tr><td colSpan={8}>No reconciliation run yet.</td></tr>:null}</tbody></table></div>
    </section>

    <section className="card"><div className="section-title"><div><h3>Recent normalized punches and exceptions</h3><p className="muted-text">Raw evidence is immutable and remains visible after reconciliation. Out-of-order and late arrivals are sorted by event time and received time.</p></div></div><div className="table-wrap"><table><thead><tr><th>Punch time</th><th>Received</th><th>Device</th><th>Opaque user</th><th>Staff</th><th>Method</th><th>Code</th><th>Sequence</th><th>Reconciliation</th></tr></thead><tbody>{data.punches.map((row:any)=><tr key={row.id}><td>{dateTime(row.punchTimestamp)}</td><td>{dateTime(row.receivedTimestamp)}</td><td>{row.device.model} · {row.device.location}</td><td>{row.opaqueDeviceUserId}</td><td>{row.staffMember?.fullName??"Unknown"}</td><td>{row.verificationMethod}</td><td>{row.punchCode}</td><td>{row.sequenceEpoch}:{row.sequenceNumber??"-"}</td><td>{row.reconciliationStatus}</td></tr>)}{!data.punches.length?<tr><td colSpan={9}>No normalized punch evidence received.</td></tr>:null}</tbody></table></div></section>

    <section className="card"><div className="section-title"><div><h3>Correction approval and immutable history</h3><p className="muted-text">Every correction retains original punch references, before/after, reason, requester, approver and timestamps.</p></div></div><div className="table-wrap"><table><thead><tr><th>Submitted</th><th>Staff</th><th>Reason</th><th>Status</th><th>Before / after</th><th>Action</th></tr></thead><tbody>{data.corrections.map((row:any)=><tr key={row.id}><td>{dateTime(row.submittedAt)}</td><td>{row.reconciliation.staffMember.fullName}</td><td>{row.reason}</td><td>{row.status}</td><td><small>{row.beforeJson}<br/>{row.afterJson}</small></td><td>{capabilities.approveAttendance&&row.status==="SUBMITTED"?<><button className="button secondary" disabled={busy} onClick={()=>run("APPROVE_CORRECTION",{id:row.id})}>Approve</button><button className="button danger" disabled={busy} onClick={()=>run("REJECT_CORRECTION",{id:row.id,reason:"Correction evidence not approved"})}>Reject</button></>:null}</td></tr>)}{!data.corrections.length?<tr><td colSpan={6}>No correction request.</td></tr>:null}</tbody></table></div><h4>Approval history</h4><div className="table-wrap"><table><thead><tr><th>Time</th><th>Entity</th><th>Event</th><th>Safe metadata</th></tr></thead><tbody>{data.auditEvents.map((row:any)=><tr key={row.id}><td>{dateTime(row.occurredAt)}</td><td>{row.entityType}</td><td>{row.eventType}</td><td>{row.safeMetadataJson??"-"}</td></tr>)}</tbody></table></div></section>

    <section className="card"><div className="section-title"><div><h3>Daily and monthly reports</h3><p className="muted-text">Exports are bounded to 366 days / 10,000 rows, private/no-store and formula-safe.</p></div></div>{capabilities.exportReports?<form className="toolbar" action="/api/attendance/staff/biometric/reports/export" method="get"><label>From<input name="from" type="date" required/></label><label>To<input name="to" type="date" required/></label><button className="button">Download private CSV</button></form>:null}<div className="table-wrap"><table><thead><tr><th>Month</th><th>Staff</th><th>Days</th><th>Present</th><th>Late</th><th>Exceptions</th></tr></thead><tbody>{monthly.map((row:any)=><tr key={`${row.month}-${row.staff}`}><td>{row.month}</td><td>{row.staff}</td><td>{row.total}</td><td>{row.present}</td><td>{row.late}</td><td>{row.exceptions}</td></tr>)}{!monthly.length?<tr><td colSpan={6}>No monthly rows.</td></tr>:null}</tbody></table></div></section>
  </div>;
}

export function OwnBiometricAttendance({ initialData }: { initialData: any }) {
  const [data, setData] = useState(initialData), [message, setMessage] = useState(""), [selected, setSelected] = useState(initialData.reconciliations[0]?.id ?? "");
  const refresh = async () => { const response = await fetch("/api/attendance/staff/biometric/own", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.code || body.error); setData(body); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(""); const source = values(event); const response = await fetch("/api/attendance/staff/biometric/own", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reconciliationId: selected, reason: source.reason, after: { outcome: source.outcome, checkInTime: source.checkInTime, checkOutTime: source.checkOutTime, lateMinutes: source.lateMinutes, earlyDepartureMinutes: source.earlyDepartureMinutes } }) }); const body = await response.json().catch(()=>({})); if (!response.ok) { setMessage(body.code || body.error); return; } await refresh(); setMessage("Correction request submitted for independent approval."); };
  return <div className="stack"><section className="card"><div className="section-title"><div><h3>{data.staff.fullName}</h3><p className="muted-text">Own attendance only. Raw punch evidence cannot be edited, and an approved correction never deducts salary automatically.</p></div></div>{message?<p role="status" className="notice">{message}</p>:null}<div className="table-wrap"><table><thead><tr><th>Date</th><th>Outcome</th><th>IN</th><th>OUT</th><th>Late</th><th>Early</th><th>Exception</th><th>Status</th><th>Corrections</th></tr></thead><tbody>{data.reconciliations.map((row:any)=><tr key={row.id}><td>{String(row.attendanceDate).slice(0,10)}</td><td>{row.outcome}</td><td>{row.checkInTime??"-"}</td><td>{row.checkOutTime??"-"}</td><td>{row.lateMinutes??0}</td><td>{row.earlyDepartureMinutes??0}</td><td>{row.exceptionCode??"-"}</td><td>{row.status}</td><td>{row.corrections.map((item:any)=>item.status).join(", ")||"-"}</td></tr>)}</tbody></table></div></section><section className="card"><h3>Request a correction</h3><form className="form-grid" onSubmit={submit}><label>Attendance day<select value={selected} onChange={(event)=>setSelected(event.target.value)} required>{data.reconciliations.map((row:any)=><option value={row.id} key={row.id}>{String(row.attendanceDate).slice(0,10)} · {row.outcome}</option>)}</select></label><label>Requested outcome<select name="outcome"><option>PRESENT</option><option>LATE</option><option>EARLY_DEPARTURE</option><option>LATE_AND_EARLY</option><option>HALF_DAY</option><option>ON_APPROVED_LEAVE</option><option>NON_WORKING_DAY</option></select></label><label>Check in<input name="checkInTime" type="time"/></label><label>Check out<input name="checkOutTime" type="time"/></label><label>Late minutes<input name="lateMinutes" type="number" min="0" max="1440"/></label><label>Early departure minutes<input name="earlyDepartureMinutes" type="number" min="0" max="1440"/></label><label className="full-width">Reason<textarea name="reason" required maxLength={1000}/></label><button className="button" disabled={!selected}>Submit correction request</button></form></section></div>;
}
