"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Pending = { kind: "plan" | "revision"; action: string; revisionId?: string; title: string; warning: string };
export function BudgetActions({ budget, permissions }: { budget: any; permissions: { manage: boolean; approve: boolean; lock: boolean; revise: boolean } }) {
  const router = useRouter(); const [pending, setPending] = useState<Pending | null>(null); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const prompt = (item: Pending) => { setError(""); setReason(""); setPending(item); };
  async function confirm() { if (!pending) return; setBusy(true); setError(""); try { const url = pending.kind === "plan" ? `/api/budgets/${budget.id}/workflow` : `/api/budgets/${budget.id}/revisions/${pending.revisionId}/workflow`; const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: pending.action, reason }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to complete action"); setPending(null); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to complete action"); } finally { setBusy(false); } }
  const actions: Pending[] = [];
  if (budget.status === "DRAFT" && permissions.manage) actions.push({ kind: "plan", action: "submit", title: "Submit for Approval", warning: "The draft becomes read-only while pending approval." });
  if (budget.status === "PENDING_APPROVAL" && permissions.approve) actions.push({ kind: "plan", action: "approve", title: "Approve Budget", warning: "This makes the plan the official budget for its academic year. Existing official plans block this action." }, { kind: "plan", action: "reject", title: "Reject Budget", warning: "A rejection reason is required and the rejected plan remains preserved." });
  if (budget.status === "APPROVED" && permissions.lock) actions.push({ kind: "plan", action: "lock", title: "Lock Budget", warning: "Locking is a separate, irreversible normal workflow action. There is no normal unlock." });
  if (["DRAFT", "PENDING_APPROVAL", "APPROVED"].includes(budget.status) && permissions.approve) actions.push({ kind: "plan", action: "cancel", title: "Cancel Budget", warning: "A cancellation reason is required. The plan remains preserved and is excluded from active summaries." });
  for (const revision of budget.revisions ?? []) { if (revision.status === "DRAFT" && permissions.revise) actions.push({ kind: "revision", revisionId: revision.id, action: "submit", title: `Submit Revision ${revision.revisionNumber}`, warning: "The revision becomes read-only while pending approval." }); if (revision.status === "PENDING_APPROVAL" && permissions.approve) actions.push({ kind: "revision", revisionId: revision.id, action: "approve", title: `Approve Revision ${revision.revisionNumber}`, warning: "This transaction applies the revised allocation snapshot and preserves the previous approved figures." }, { kind: "revision", revisionId: revision.id, action: "reject", title: `Reject Revision ${revision.revisionNumber}`, warning: "A rejection reason is required and the revision remains preserved." }); }
  return <section className="card card-pad"><h3>Workflow Actions</h3><div className="page-actions">{actions.map((item) => <button type="button" className={item.action === "reject" || item.action === "cancel" ? "danger" : undefined} key={`${item.kind}-${item.revisionId ?? "plan"}-${item.action}`} onClick={() => prompt(item)}>{item.title}</button>)}</div>{!actions.length ? <p className="muted-text">No workflow actions are available for your permissions and this status.</p> : null}{error && !pending ? <div className="notice danger">{error}</div> : null}
  {pending ? <div className="modal-backdrop" role="presentation"><div className="card modal-card" role="dialog" aria-modal="true" aria-labelledby="budget-confirm-title"><h3 id="budget-confirm-title">{pending.title}</h3><p>{pending.warning}</p>{["reject", "cancel"].includes(pending.action) ? <label>{pending.action === "reject" ? "Rejection" : "Cancellation"} Reason (required)<textarea autoFocus aria-label="Workflow Reason" value={reason} onChange={(e) => setReason(e.target.value)} /></label> : null}{error ? <div className="notice danger" role="alert">{error}</div> : null}<div className="page-actions"><button type="button" className="secondary" disabled={busy} onClick={() => setPending(null)}>Go Back</button><button type="button" className={pending.action === "reject" || pending.action === "cancel" ? "danger" : undefined} disabled={busy} onClick={confirm}>Confirm {pending.title}</button></div></div></div> : null}</section>;
}
