"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Option = { id: string; name: string; code?: string | null };
type Allocation = { rowKey: string; categoryId: string; departmentId: string; allocatedAmount: string; warningThresholdPercent: string; criticalThresholdPercent: string; notes: string };
const blank = (): Allocation => ({ rowKey: crypto.randomUUID(), categoryId: "", departmentId: "", allocatedAmount: "", warningThresholdPercent: "", criticalThresholdPercent: "", notes: "" });
const dateValue = (value?: string | Date | null) => value ? new Date(value).toISOString().slice(0, 10) : "";

export function BudgetForm({ budget, categories, departments }: { budget?: any; categories: Option[]; departments: Option[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [preview, setPreview] = useState(false);
  const [form, setForm] = useState({ academicYear: budget?.academicYear ?? "2026-27", title: budget?.title ?? "", description: budget?.description ?? "", warningThresholdPercent: String(budget?.warningThresholdPercent ?? 80), criticalThresholdPercent: String(budget?.criticalThresholdPercent ?? 100), effectiveFrom: dateValue(budget?.effectiveFrom), effectiveTo: dateValue(budget?.effectiveTo) });
  const [allocations, setAllocations] = useState<Allocation[]>(budget?.allocations?.length ? budget.allocations.map((row: any) => ({ rowKey: row.id ?? crypto.randomUUID(), categoryId: row.categoryId ?? "", departmentId: row.departmentId ?? "", allocatedAmount: String(row.allocatedAmount), warningThresholdPercent: row.warningThresholdPercent == null ? "" : String(row.warningThresholdPercent), criticalThresholdPercent: row.criticalThresholdPercent == null ? "" : String(row.criticalThresholdPercent), notes: row.notes ?? "" })) : [blank()]);
  const total = useMemo(() => allocations.reduce((sum, row) => sum + (Number(row.allocatedAmount) || 0), 0), [allocations]);
  const clearFeedback = () => { setError(""); setMessage(""); };
  const update = (key: string, value: string) => { clearFeedback(); setPreview(false); setForm((old) => ({ ...old, [key]: value })); };
  const updateRow = (rowKey: string, key: keyof Allocation, value: string) => { clearFeedback(); setPreview(false); setAllocations((old) => old.map((row) => row.rowKey === rowKey ? { ...row, [key]: value } : row)); };
  const payload = { ...form, allocations: allocations.map(({ rowKey: _rowKey, ...row }) => row) };
  async function save(submit: boolean) { setBusy(true); setError(""); setMessage(""); try { if (submit && !preview) throw new Error("Preview the allocation summary before submission"); const response = await fetch(budget?.id ? `/api/budgets/${budget.id}` : "/api/budgets", { method: budget?.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to save budget"); const id = budget?.id ?? data.budget.id; if (submit) { const workflow = await fetch(`/api/budgets/${id}/workflow`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "submit" }) }); const result = await workflow.json(); if (!workflow.ok) throw new Error(result.error ?? "Unable to submit budget"); router.push(`/budgets/${id}`); router.refresh(); } else if (!budget?.id) router.push(`/budgets/${id}`); else { setMessage("Draft budget updated."); router.refresh(); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to save budget"); } finally { setBusy(false); } }
  return <div className="budget-stack"><section className="card card-pad"><div className="form-grid expense-form-grid">
    <label>Academic Year<input aria-label="Academic Year" value={form.academicYear} onChange={(e) => update("academicYear", e.target.value)} /></label><label>Budget Title<input aria-label="Budget Title" value={form.title} onChange={(e) => update("title", e.target.value)} /></label>
    <label>Warning Threshold (%)<input aria-label="Warning Threshold" type="number" min="1" max="1000" value={form.warningThresholdPercent} onChange={(e) => update("warningThresholdPercent", e.target.value)} /></label><label>Critical Threshold (%)<input aria-label="Critical Threshold" type="number" min="1" max="1000" value={form.criticalThresholdPercent} onChange={(e) => update("criticalThresholdPercent", e.target.value)} /></label>
    <label>Effective From <span className="muted-text">(optional)</span><input aria-label="Effective From" type="date" value={form.effectiveFrom} onChange={(e) => update("effectiveFrom", e.target.value)} /></label><label>Effective To <span className="muted-text">(optional)</span><input aria-label="Effective To" type="date" value={form.effectiveTo} onChange={(e) => update("effectiveTo", e.target.value)} /></label>
    <label className="wide">Description <span className="muted-text">(optional)</span><textarea aria-label="Budget Description" value={form.description} onChange={(e) => update("description", e.target.value)} /></label>
  </div></section><AllocationEditor allocations={allocations} categories={categories} departments={departments} updateRow={updateRow} add={() => { clearFeedback(); setPreview(false); setAllocations((old) => [...old, blank()]); }} remove={(key) => { clearFeedback(); setPreview(false); setAllocations((old) => old.length === 1 ? old : old.filter((row) => row.rowKey !== key)); }} />
  <section className="card card-pad"><div className="page-actions"><strong>Calculated total: ₹{total.toLocaleString("en-IN", { minimumFractionDigits: 2 })}</strong><button type="button" className="secondary" onClick={() => { clearFeedback(); setPreview(true); }}>Preview Allocations</button><button type="button" className="secondary" disabled={busy} onClick={() => save(false)}>Save Draft</button><button type="button" disabled={busy || !preview} onClick={() => save(true)}>Submit for Approval</button></div>{preview ? <div className="notice success" role="status"><strong>Submission preview ready.</strong> {allocations.length} allocation(s), total ₹{total.toLocaleString("en-IN", { minimumFractionDigits: 2 })}. Submission makes this plan read-only until approved, rejected, or cancelled.</div> : <p className="muted-text">Preview is required before submission.</p>}</section>
  {message ? <div className="notice success" role="status">{message}</div> : null}{error ? <div className="notice danger" role="alert">{error}</div> : null}</div>;
}

function AllocationEditor({ allocations, categories, departments, updateRow, add, remove }: { allocations: Allocation[]; categories: Option[]; departments: Option[]; updateRow: (key: string, field: keyof Allocation, value: string) => void; add: () => void; remove: (key: string) => void }) {
  return <section className="card card-pad"><div className="section-heading"><div><h3>Allocation Builder</h3><p className="muted-text">Choose a category, a department, or both. Exact duplicates are blocked.</p></div><button type="button" className="secondary" onClick={add}>Add Allocation</button></div><div className="allocation-list">{allocations.map((row, index) => <div className="allocation-row" key={row.rowKey}><strong>Allocation {index + 1}</strong><label>Category<select aria-label={`Allocation ${index + 1} Category`} value={row.categoryId} onChange={(e) => updateRow(row.rowKey, "categoryId", e.target.value)}><option value="">All / no category</option>{categories.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label>Department<select aria-label={`Allocation ${index + 1} Department`} value={row.departmentId} onChange={(e) => updateRow(row.rowKey, "departmentId", e.target.value)}><option value="">All / no department</option>{departments.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label>Allocated Amount<input aria-label={`Allocation ${index + 1} Amount`} type="number" min="0.01" step="0.01" value={row.allocatedAmount} onChange={(e) => updateRow(row.rowKey, "allocatedAmount", e.target.value)} /></label><label>Warning % <span className="muted-text">(optional)</span><input aria-label={`Allocation ${index + 1} Warning`} type="number" min="1" max="1000" value={row.warningThresholdPercent} onChange={(e) => updateRow(row.rowKey, "warningThresholdPercent", e.target.value)} /></label><label>Critical % <span className="muted-text">(optional)</span><input aria-label={`Allocation ${index + 1} Critical`} type="number" min="1" max="1000" value={row.criticalThresholdPercent} onChange={(e) => updateRow(row.rowKey, "criticalThresholdPercent", e.target.value)} /></label><label className="wide">Notes <span className="muted-text">(optional)</span><input aria-label={`Allocation ${index + 1} Notes`} value={row.notes} onChange={(e) => updateRow(row.rowKey, "notes", e.target.value)} /></label><button type="button" className="danger secondary" disabled={allocations.length === 1} onClick={() => remove(row.rowKey)}>Remove</button></div>)}</div></section>;
}

export function BudgetRevisionForm({ budget, categories, departments }: { budget: any; categories: Option[]; departments: Option[] }) {
  const router = useRouter(); const [reason, setReason] = useState(""); const [allocations, setAllocations] = useState<Allocation[]>(budget.allocations.map((row: any) => ({ rowKey: crypto.randomUUID(), categoryId: row.categoryId ?? "", departmentId: row.departmentId ?? "", allocatedAmount: String(row.allocatedAmount), warningThresholdPercent: row.warningThresholdPercent == null ? "" : String(row.warningThresholdPercent), criticalThresholdPercent: row.criticalThresholdPercent == null ? "" : String(row.criticalThresholdPercent), notes: row.notes ?? "" }))); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const updateRow = (key: string, field: keyof Allocation, value: string) => setAllocations((old) => old.map((row) => row.rowKey === key ? { ...row, [field]: value } : row));
  async function create() { setBusy(true); setError(""); try { const response = await fetch(`/api/budgets/${budget.id}/revisions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason, allocations: allocations.map(({ rowKey: _rowKey, ...row }) => row) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to create revision"); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create revision"); } finally { setBusy(false); } }
  return <details className="card card-pad"><summary><strong>Create Preserved Revision</strong></summary><p className="muted-text">The approved figures remain in the revision snapshot. Changes apply only after separate submission and approval.</p><label>Revision Reason (required)<textarea aria-label="Revision Reason" value={reason} onChange={(e) => setReason(e.target.value)} /></label><AllocationEditor allocations={allocations} categories={categories} departments={departments} updateRow={updateRow} add={() => setAllocations((old) => [...old, blank()])} remove={(key) => setAllocations((old) => old.length === 1 ? old : old.filter((row) => row.rowKey !== key))} /><button type="button" disabled={busy} onClick={create}>Create Draft Revision</button>{error ? <div className="notice danger" role="alert">{error}</div> : null}</details>;
}
