"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { GRADUATION_DISCLAIMER, defaultTemplateDefinition } from "@/lib/certificate-templates";
import { CertificateRequestActions, CertificateWorkflowActions } from "@/components/certificate-forms";
import styles from "@/components/certificate-graduation-workspace.module.css";

export function CertificateGraduationWorkspace({ data, permissions }: { data: any; permissions: string[] }) {
  const router = useRouter(), allowed = (p: string) => permissions.includes(p);
  const [studentId, setStudentId] = useState(""), [academicYear, setYear] = useState(""), [requestId, setRequest] = useState(""), [templateId, setTemplate] = useState("");
  const [issueDate, setIssueDate] = useState(""), [issuePlace, setIssuePlace] = useState("");
  const [readiness, setReadiness] = useState<any>(null), [charge, setCharge] = useState<any>(null), [batch, setBatch] = useState<any>(null), [selected, setSelected] = useState<number[]>([]);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  const requestKey = useRef<string | null>(null), notice = useRef<HTMLParagraphElement>(null);
  const request = data.requests.find((r: any) => r.id === requestId), template = data.templates.find((t: any) => t.id === templateId);
  async function api(url: string, body?: any, method = "POST") {
    const response = await fetch(url, body === undefined ? {} : { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Operation failed."); return result;
  }
  async function run(work: () => Promise<void>, refresh = false) {
    setBusy(true); setError(""); setMessage("");
    try { await work(); if (refresh) router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Operation failed."); setTimeout(() => notice.current?.focus(), 0); } finally { setBusy(false); }
  }
  async function refreshBatch(id: string) { const result = await api(`/api/certificates/bulk/${id}`); setBatch(result); return result; }
  async function preview(id: string) {
    const response = await fetch(`/api/certificates/${id}/pdf`, { method: "POST" });
    if (!response.ok) throw new Error((await response.json()).error);
    const url = URL.createObjectURL(await response.blob()), link = document.createElement("a"); link.href = url; link.download = "DRAFT-NOT-OFFICIAL.pdf"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <div className={styles.workspace} aria-busy={busy}>
    <section className="card"><h2>School-issued recognition</h2><p>{GRADUATION_DISCLAIMER}</p><p>Board documents, Transfer Certificate eligibility and Student status remain separate. A charge here applies only to this optional recognition.</p></section>
    <p ref={notice} tabIndex={-1} role={error ? "alert" : "status"}>{busy ? "Working…" : error || message}</p>
    <section className="card"><h2>1. Student and readiness</h2><div className="form-grid">
      <label>Student<select aria-label="Student" value={studentId} onChange={e => { setStudentId(e.target.value); setReadiness(null); requestKey.current = null; }}><option value="">Select an exact Student</option>{data.students.map((s: any) => <option key={s.id} value={s.id}>{s.studentName} · {s.admissionNo}</option>)}</select></label>
      <label>Academic year<input aria-label="Certificate academic year" value={academicYear} placeholder="YYYY-YY" pattern="[0-9]{4}-[0-9]{2}" onChange={e => { setYear(e.target.value); setReadiness(null); requestKey.current = null; }} /></label>
      <label>Type<input readOnly value="Graduation — school recognition" /></label><label>Reviewed issue date<input type="date" value={issueDate} onChange={e => setIssueDate(e.target.value)} /></label><label>Issue place<input value={issuePlace} maxLength={150} placeholder="School setting unless specified" onChange={e => setIssuePlace(e.target.value)} /></label>
      {allowed("CREATE_CERTIFICATES") && <button disabled={busy || !studentId || !academicYear} onClick={() => run(async () => setReadiness(await api(`/api/certificates/readiness?studentId=${encodeURIComponent(studentId)}&academicYear=${encodeURIComponent(academicYear)}`)), false)}>Check readiness</button>}
    </div>{readiness && <div role="status"><p>{readiness.ready ? "School-completion evidence is ready for review." : "Evidence needs correction before issue."}</p><ul>{readiness.errors.map((e: string) => <li key={e}>{e}</li>)}<li>Board-pass wording: unavailable; no claim will be printed.</li><li>Names and dates come from authoritative records.</li></ul></div>}
      {allowed("MANAGE_CERTIFICATE_REQUESTS") && <button disabled={busy || !readiness?.ready} onClick={() => run(async () => { requestKey.current ??= crypto.randomUUID(); const r = await api("/api/certificates/requests", { studentId, academicYear, certificateType: "GRADUATION", purpose: "School-issued Class X completion recognition", idempotencyKey: requestKey.current }); setRequest(r.request.id); setMessage("Request created. Review and approval remain separate."); router.refresh(); })}>Create recognition request</button>}
    </section>
    <section className="card"><h2>2. Request, charge and draft</h2><div className="form-grid"><label>Request<select value={requestId} onChange={e => { setRequest(e.target.value); setCharge(null); }}><option value="">Select a request</option>{data.requests.map((r: any) => <option key={r.id} value={r.id}>{r.requestNumber} · {r.academicYear} · {r.status}</option>)}</select></label><label>Approved template<select value={templateId} onChange={e => setTemplate(e.target.value)}><option value="">Select a version</option>{data.templates.map((t: any) => <option key={t.id} value={t.id}>{t.name} · v{t.versionNumber} · {t.status}</option>)}</select></label></div>
      {request && <><CertificateRequestActions id={request.id} status={request.status} updatedAt={request.updatedAt} permissions={permissions} /><div className="page-actions"><button disabled={busy} onClick={() => run(async () => setCharge((await api(`/api/certificates/requests/${requestId}/charge`)).charge), false)}>Inspect charge</button>{allowed("MANAGE_MISC_INCOME") && <button disabled={busy} onClick={() => run(async () => setCharge((await api(`/api/certificates/requests/${requestId}/charge`, { action: "prepare" })).charge))}>Prepare configured charge</button>}</div>
        <p>Charge: {charge ? `${charge.status} · INR ${JSON.parse(charge.snapshotJson).amount}${charge.receiptId ? " · receipt linked" : ""}` : "Not inspected. Unconfigured does not mean free."}</p>
        {charge?.status === "PENDING_APPROVAL" && allowed("MANAGE_MISC_INCOME_ITEMS") && <form className="form-grid" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(async () => setCharge((await api(`/api/certificates/requests/${requestId}/charge`, { action: "approve", expectedUpdatedAt: charge.updatedAt, ...(f.get("waiver") ? { waiverReason: f.get("waiver") } : {}) })).charge)); }}><label>Waiver reason (leave empty to approve the configured rate)<input name="waiver" maxLength={500} /></label><button disabled={busy}>Approve charge or explicit waiver</button></form>}
        {charge?.status === "APPROVED" && allowed("MANAGE_MISC_INCOME") && <form className="form-grid" onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); void run(async () => setCharge((await api(`/api/certificates/requests/${requestId}/charge`, { ...f, action: "collect" })).charge)); }}><label>Receipt date<input required name="receiptDate" type="date" /></label><label>Payment method<select name="paymentMethod"><option>CASH</option><option>UPI</option><option>BANK_TRANSFER</option></select></label><label>Received account<select name="receivedAccount"><option>CASH_COUNTER</option><option>NPS_CURRENT_ACCOUNT</option><option>DIRECTOR_GPAY</option></select></label><label>Transaction reference (required for non-cash)<input name="transactionReference" maxLength={120} /></label><button disabled={busy}>Collect approved amount once</button></form>}
        {allowed("CREATE_CERTIFICATES") && <button disabled={busy || request.status !== "APPROVED" || template?.status !== "ACTIVE"} onClick={() => run(async () => { const result = await api("/api/certificates", { studentId: request.studentId, academicYear: request.academicYear, requestId, templateId, certificateType: "GRADUATION", issueDate: issueDate || undefined, issuePlace: issuePlace || undefined, purpose: request.purpose }); setMessage("Draft prepared. Preview, submit, approve, then issue from history."); router.refresh(); })}>Prepare draft</button>}</>}
    </section>
    <section className="card"><h2>3. Review and issue history</h2><div className="table-wrap"><table><thead><tr><th>Issue / draft</th><th>Year / version</th><th>Status</th><th>Documents and actions</th></tr></thead><tbody>{data.certificates.map((c: any) => <tr key={c.id}><td><Link href={`/certificates/${c.id}`}>{c.certificateNumber ?? "Unnumbered draft"}</Link></td><td>{c.academicYear} · v{c.currentVersionNumber}</td><td>{c.status === "CANCELLED" ? "VOID — history retained" : c.status}</td><td>{allowed("CREATE_CERTIFICATES") && <button disabled={busy} onClick={() => run(() => preview(c.id))}>Preview DRAFT PDF</button>}{c.status === "ISSUED" && <a className="button secondary" href={`/api/certificates/${c.id}/pdf`}>Reprint saved PDF</a>}<CertificateWorkflowActions id={c.id} status={c.status} updatedAt={c.updatedAt} type={c.certificateType} permissions={permissions} /></td></tr>)}{!data.certificates.length && <tr><td colSpan={4}>No Graduation certificates yet. Create and review a request first.</td></tr>}</tbody></table></div></section>
    <section className="card"><h2>4. Reviewed XLSX bulk issue</h2><p>Use approved Graduation requests only. Match exact names, admissions, academic years and classes. Maximum 100 rows; successful rows are retained on retry.</p><div className="page-actions"><a className="button secondary" href="/api/certificates/bulk">Download XLSX template</a><label>Resume an existing batch<select defaultValue="" onChange={e => e.target.value && run(async () => { await refreshBatch(e.target.value); setSelected([]); })}><option value="">Choose a batch</option>{data.batches.map((b: any) => <option key={b.id} value={b.id}>{b.createdAt.slice(0, 16)} · {b.status}</option>)}</select></label></div>
      {allowed("CREATE_CERTIFICATES") && <label>Upload completed XLSX<input type="file" accept=".xlsx" disabled={busy || template?.status !== "ACTIVE"} onChange={e => { const file = e.target.files?.[0]; if (!file) return; void run(async () => { if (file.size > 1024 * 1024) throw new Error("Workbook exceeds 1 MB."); const form = new FormData(); form.set("templateId", templateId); form.set("workbook", file); const response = await fetch("/api/certificates/bulk", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Workbook upload failed."); await refreshBatch(result.batch.id); setSelected([]); }); }} /></label>}
      {batch && <><p role="status">Batch: {batch.status}. Review every selected row before approval.</p><div className="table-wrap"><table><thead><tr><th>Select</th><th>Row</th><th>Student / year</th><th>Validation / result</th></tr></thead><tbody>{batch.rows.map((r: any) => <tr key={r.number}><td><input type="checkbox" aria-label={`Select row ${r.number}`} disabled={busy || r.errors.length > 0 || batch.status !== "VALIDATED"} checked={selected.includes(r.number)} onChange={e => setSelected(e.target.checked ? [...selected, r.number] : selected.filter(n => n !== r.number))} /></td><td>{r.number}</td><td>{r.values[2]} · {r.values[3]}</td><td>{r.errors.join(" ") || r.result}</td></tr>)}</tbody></table></div>
        <div className="page-actions">{batch.status === "APPROVED" && allowed("EXPORT_CERTIFICATE_REPORTS") && <a className="button secondary" href={`/api/certificates/bulk/${batch.id}/pdf`}>Download reviewed bulk PDF / print</a>}{allowed("APPROVE_CERTIFICATES") && <button disabled={busy || batch.status !== "VALIDATED" || !selected.length} onClick={() => run(async () => { await api(`/api/certificates/bulk/${batch.id}`, { action: "approve", selected, expectedUpdatedAt: batch.updatedAt, uploadDigest: batch.uploadDigest }); await refreshBatch(batch.id); })}>Approve selected valid rows</button>}{allowed("ISSUE_CERTIFICATES") && <button disabled={busy || batch.status !== "APPROVED"} onClick={() => run(async () => { const approved = JSON.parse(batch.approvalJson).selected; let failed = 0; for (const number of approved) { setMessage(`Processing row ${number}…`); try { await api(`/api/certificates/bulk/${batch.id}`, { action: "process", number }); } catch { failed++; } await refreshBatch(batch.id); } setMessage(`Processing finished. ${failed} rows failed; successful issues are retained.`); })}>Generate / resume approved rows</button>}</div>
      </>}
    </section>
    {allowed("MANAGE_CERTIFICATE_TEMPLATES") && <section className="card"><h2>Template wording and number series</h2><p>Editing an approved template creates a draft version. Another authorized reviewer activates Graduation templates.</p><form key={templateId} className="form-grid" onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); const definition = { ...defaultTemplateDefinition("GRADUATION"), heading: f.heading, body: f.body, disclaimer: f.disclaimer, signatories: [{ name: "", role: f.role }] }; void run(async () => { const result = template ? await api(`/api/certificates/templates/${templateId}`, { name: f.name, definition, expectedUpdatedAt: template.updatedAt }, "PATCH") : await api("/api/certificates/templates", { templateCode: f.code, certificateType: "GRADUATION", academicYear, name: f.name, definition }); setTemplate(result.template.id); setMessage("Template draft saved for review."); router.refresh(); }); }}><label>Template code<input name="code" required={!template} defaultValue={template?.templateCode ?? ""} readOnly={!!template} /></label><label>Name<input name="name" required maxLength={120} defaultValue={template?.name ?? "Graduation recognition"} /></label><label>Heading<input name="heading" required maxLength={120} defaultValue={template ? JSON.parse(template.templateDefinitionJson).heading : "GRADUATION CERTIFICATE"} /></label><label>Authorized signatory role<input name="role" required maxLength={100} defaultValue={template ? JSON.parse(template.templateDefinitionJson).signatories?.[0]?.role : "Principal"} /></label><label>Reviewed wording<textarea name="body" required maxLength={4000} defaultValue={template ? JSON.parse(template.templateDefinitionJson).body : defaultTemplateDefinition("GRADUATION").body} /></label><label>Mandatory distinction and approved supplemental wording<textarea name="disclaimer" required maxLength={2000} defaultValue={template ? JSON.parse(template.templateDefinitionJson).disclaimer : GRADUATION_DISCLAIMER} /></label><button disabled={busy}>Save template draft / new version</button></form>{template?.status === "DRAFT" && <button disabled={busy} onClick={() => run(async () => { await api(`/api/certificates/templates/${templateId}`, { status: "ACTIVE", expectedUpdatedAt: template.updatedAt }, "PATCH"); setMessage("Template activated by reviewer."); router.refresh(); })}>Approve and activate selected template</button>}
      <form className="form-grid" onSubmit={e => { e.preventDefault(); const f = Object.fromEntries(new FormData(e.currentTarget)); void run(async () => { await api("/api/certificates/number-series", { ...f, certificateType: "GRADUATION", academicYear, nextNumber: 1, paddingLength: 5 }); setMessage("Number series configured. Resolve any duplicate defaults before issue."); }); }}><label>Number series code<input name="seriesCode" required /></label><label>Number prefix<input name="prefix" required maxLength={30} /></label><button disabled={busy || !academicYear}>Create year number series</button></form>
    </section>}
  </div>;
}
