"use client";
import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";

const TYPES = ["BONAFIDE","STUDY","CONDUCT","TRANSFER"];
function useSubmit(){const router=useRouter();const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function send(url:string,body:any,method="POST"){setBusy(true);setError("");try{const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error??"Operation failed.");router.refresh();return data;}catch(e){setError(e instanceof Error?e.message:"Operation failed.");throw e;}finally{setBusy(false);}}return{send,error,busy,setError,router};}

export function CertificateRequestForm({students,parent=false,academicYear="2026-27"}:{students:Array<{id:string;studentName:string;admissionNo:string}>;parent?:boolean;academicYear?:string}){
 const api=useSubmit(),formRef=useRef<HTMLFormElement>(null),[pending,setPending]=useState<Record<string,unknown>|null>(null);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setPending({studentId:f.get("studentId"),academicYear,certificateType:f.get("certificateType"),purpose:f.get("purpose"),requestedCopies:Number(f.get("requestedCopies")),urgency:f.get("urgency")});}
 async function submitConfirmedRequest(){if(!pending)return;try{await api.send(parent?"/api/parent/certificates":"/api/certificates/requests",pending);setPending(null);formRef.current?.reset();}catch{}}
 return <><form ref={formRef} className="card form-grid certificate-form" onSubmit={submit}><label>Student<select name="studentId" required>{students.map(s=><option key={s.id} value={s.id}>{s.studentName} · {s.admissionNo}</option>)}</select></label><label>Certificate type<select name="certificateType" required>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Urgency<select name="urgency"><option>NORMAL</option><option>URGENT</option></select></label><label>Requested copies<select name="requestedCopies" defaultValue="1"><option>1</option><option>2</option><option>3</option></select></label><label className="field-span">Purpose<textarea name="purpose" required maxLength={500}/></label>{api.error?<p className="error field-span" role="alert">{api.error}</p>:null}<button disabled={api.busy} type="submit">{parent?"Submit Certificate Request":"Create Internal Request"}</button></form>{pending?<div className="dialog-backdrop" role="presentation"><section className="dialog-card" role="dialog" aria-modal="true" aria-labelledby="request-submit-dialog-title"><h3 id="request-submit-dialog-title">Submit Certificate Request</h3><p>Confirm this {parent?"Parent":"internal"} request. Certificate facts remain subject to staff review.</p><div className="page-actions"><button className="secondary" onClick={()=>setPending(null)}>Go Back</button><button autoFocus disabled={api.busy} onClick={submitConfirmedRequest}>Submit Certificate Request</button></div></section></div>:null}</>;
}

export function CertificateDraftForm({students,templates,requests,academicYear="2026-27"}:{students:any[];templates:any[];requests:any[];academicYear?:string}){
 const api=useSubmit();async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await api.send("/api/certificates",{studentId:f.get("studentId"),academicYear,certificateType:f.get("certificateType"),templateId:f.get("templateId"),requestId:f.get("requestId"),issuePurpose:f.get("purpose")});api.router.push(`/certificates/${data.certificate.id}`);}catch{}}
 return <form className="card form-grid certificate-form" onSubmit={submit}><label>Student<select name="studentId" required>{students.map(s=><option key={s.id} value={s.id}>{s.studentName} · {s.admissionNo}</option>)}</select></label><label>Certificate type<select name="certificateType">{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Active template<select name="templateId" required>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · {t.certificateType}</option>)}</select></label><label>Approved request (optional)<select name="requestId"><option value="">No linked request</option>{requests.map(r=><option key={r.id} value={r.id}>{r.requestNumber} · {r.certificateType}</option>)}</select></label><label className="field-span">Issue purpose<textarea name="purpose" required maxLength={500}/></label>{api.error?<p className="error field-span" role="alert">{api.error}</p>:null}<button disabled={api.busy}>Create Certificate Draft</button></form>;
}

export function CertificateWorkflowActions({id,status,updatedAt,type,permissions}:{id:string;status:string;updatedAt:string;type:string;permissions:string[]}){
 const api=useSubmit();const[dialog,setDialog]=useState<string|null>(null);const[reason,setReason]=useState("");const labels:Record<string,string>={submit:"Submit Certificate for Approval",approve:"Approve Certificate",issue:"Issue Certificate",correct:"Issue Corrected Certificate",reissue:"Reissue Certificate",cancel:"Cancel Issued Certificate"};
 const allowed=[...(status==="DRAFT"&&permissions.includes("REVIEW_CERTIFICATES")?["submit"]:[]),...(status==="READY_FOR_REVIEW"&&permissions.includes("APPROVE_CERTIFICATES")?["approve"]:[]),...(status==="APPROVED"&&permissions.includes("ISSUE_CERTIFICATES")?["issue"]:[]),...(status==="ISSUED"&&permissions.includes("CORRECT_ISSUED_CERTIFICATES")?["correct","reissue"]:[]),...(status==="ISSUED"&&permissions.includes("CANCEL_ISSUED_CERTIFICATES")?["cancel"]:[])];
 async function act(){if(!dialog)return;try{await api.send(`/api/certificates/${id}/workflow`,{action:dialog,expectedUpdatedAt:updatedAt,reason,activeEnrollmentReason:type==="TRANSFER"&&dialog==="issue"?reason:undefined});setDialog(null);setReason("");}catch{}}
 return <section className="card certificate-actions"><h3>Certificate Workflow</h3><div className="page-actions">{allowed.map(a=><button key={a} className={a==="cancel"?"danger":""} onClick={()=>setDialog(a)}>{labels[a]}</button>)}</div>{api.error?<p role="alert" className="error">{api.error}</p>:null}{dialog?<div className="dialog-backdrop" role="presentation"><section className="dialog-card" role="dialog" aria-modal="true" aria-labelledby="certificate-dialog-title"><h3 id="certificate-dialog-title">{labels[dialog]}</h3><p>This action is permission checked and preserves the workflow history.</p>{["correct","reissue","cancel"].includes(dialog)||type==="TRANSFER"&&dialog==="issue"?<label>{type==="TRANSFER"&&dialog==="issue"?"Active-enrollment issue reason":"Reason"}<textarea autoFocus value={reason} onChange={e=>setReason(e.target.value)} required maxLength={1000}/></label>:null}<div className="page-actions"><button className="secondary" onClick={()=>setDialog(null)}>Go Back</button><button className={dialog==="cancel"?"danger":""} disabled={api.busy||((["correct","reissue","cancel"].includes(dialog)||type==="TRANSFER"&&dialog==="issue")&&!reason.trim())} onClick={act}>{labels[dialog]}</button></div></section></div>:null}</section>;
}

export function CertificateRequestActions({id,status,updatedAt,permissions}:{id:string;status:string;updatedAt:string;permissions:string[]}){
 const api=useSubmit();const[dialog,setDialog]=useState<string|null>(null);const[reason,setReason]=useState("");const labels:Record<string,string>={review:"Start Certificate Review",approve:"Approve Certificate Request",reject:"Reject Certificate Request",cancel:"Cancel Certificate Request"};
 const actions=[...(status==="SUBMITTED"&&permissions.includes("REVIEW_CERTIFICATES")?["review"]:[]),...(status==="UNDER_REVIEW"&&permissions.includes("APPROVE_CERTIFICATES")?["approve"]:[]),...(["SUBMITTED","UNDER_REVIEW"].includes(status)&&permissions.includes("MANAGE_CERTIFICATE_REQUESTS")?["reject"]:[]),...(!["COMPLETED","REJECTED","CANCELLED"].includes(status)&&permissions.includes("MANAGE_CERTIFICATE_REQUESTS")?["cancel"]:[])];
 async function act(){if(!dialog)return;try{await api.send(`/api/certificates/requests/${id}/workflow`,{action:dialog,expectedUpdatedAt:updatedAt,reason});setDialog(null);setReason("");}catch{}}
 return <section className="card certificate-actions"><h3>Request Workflow</h3><div className="page-actions">{actions.map(a=><button key={a} className={["reject","cancel"].includes(a)?"danger":""} onClick={()=>setDialog(a)}>{labels[a]}</button>)}</div>{api.error?<p role="alert" className="error">{api.error}</p>:null}{dialog?<div className="dialog-backdrop"><section className="dialog-card" role="dialog" aria-modal="true" aria-labelledby="request-dialog-title"><h3 id="request-dialog-title">{labels[dialog]}</h3>{["reject","cancel"].includes(dialog)?<label>Reason<textarea autoFocus value={reason} onChange={e=>setReason(e.target.value)} required/></label>:<p>This transition uses a concurrency check and is recorded.</p>}<div className="page-actions"><button className="secondary" onClick={()=>setDialog(null)}>Go Back</button><button disabled={api.busy||(["reject","cancel"].includes(dialog)&&!reason.trim())} onClick={act}>{labels[dialog]}</button></div></section></div>:null}</section>;
}

export function CertificateConfigurationForms({academicYear}:{academicYear:string}){const api=useSubmit();async function series(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api.send("/api/certificates/number-series",Object.fromEntries(f));e.currentTarget.reset();}catch{}}async function template(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),type=String(f.get("certificateType"));try{await api.send("/api/certificates/templates",{templateCode:f.get("templateCode"),certificateType:type,name:f.get("name"),academicYear,status:"ACTIVE",definition:{heading:f.get("heading"),body:f.get("body"),enabledFields:["studentName","admissionNumber","className","academicYear","purpose"],...(type==="CONDUCT"?{conductStatement:"GOOD"}:{})}});e.currentTarget.reset();}catch{}}
 return <div className="two-column"><form className="card form-grid" onSubmit={series}><h3 className="field-span">Create Number Series</h3><label>Series code<input name="seriesCode" required/></label><label>Type<select name="certificateType">{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Academic year<input name="academicYear" defaultValue={academicYear}/></label><label>Prefix<input name="prefix" placeholder="BON/2026-27/"/></label><label>Next number<input name="nextNumber" type="number" min="1" defaultValue="1"/></label><label>Padding<input name="paddingLength" type="number" min="1" max="10" defaultValue="4"/></label><button>Create Series</button></form><form className="card form-grid" onSubmit={template}><h3 className="field-span">Create Active Validated Template</h3><label>Template code<input name="templateCode" required/></label><label>Type<select name="certificateType">{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Name<input name="name" required/></label><label>Heading<input name="heading" required/></label><label className="field-span">Reviewed body text<textarea name="body" required maxLength={4000}/></label><button>Create and Activate Template</button></form>{api.error?<p className="error" role="alert">{api.error}</p>:null}</div>}
