"use client";

import { useEffect, useState } from "react";
import { isoDateInput, monthKey, money } from "@/lib/format";
import Link from "next/link";
import { PrintButton } from "@/components/print-button";
import type { SchoolSettingsValue } from "@/lib/school-settings";

type Report = {
  totalCash: number;
  totalDirectorGPay: number;
  totalNpsUpi: number;
  totalBank: number;
  totalCheque: number;
  totalOther: number;
  grandTotal: number;
  receipts: string[];
  byClass: Record<string, number>;
  byStudent: Record<string, number>;
  byTerm: Record<string, number>;
  payments: any[];
};

export function CollectionReport({
  generatedBy,
  canPrint,
  canPrintReceipt,
  settings
}: {
  generatedBy: string;
  canPrint: boolean;
  canPrintReceipt: boolean;
  settings: SchoolSettingsValue;
}) {
  const [date, setDate] = useState(isoDateInput());
  const [month, setMonth] = useState(monthKey());
  const [mode, setMode] = useState<"date" | "month">("date");
  const [report, setReport] = useState<Report | null>(null);
  const [generatedAt, setGeneratedAt] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);

  async function load() {
    setLoading(true);
    setMessage("");
    const query = mode === "date" ? `date=${date}` : `month=${month}`;
    try {
      const response = await fetch(`/api/reports/collection?${query}`);
      const json = await response.json();
      if (!response.ok) throw new Error(json.error || "Unable to load collection report");
      setReport(json);
      setGeneratedAt(new Date().toLocaleString("en-IN"));
    } catch (error) {
      setReport(null);
      setMessage(error instanceof Error ? error.message : "Unable to load collection report");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mode]);

  return (
    <div className="grid">
      <style>{`@media print { @page { size: ${settings.defaultPrintSize} portrait; margin: 10mm; } }`}</style>
      <form className="card card-pad filters no-print" onSubmit={(event) => { event.preventDefault(); load(); }}>
        <label>Report Type<select value={mode} onChange={(e) => setMode(e.target.value as "date" | "month")}><option value="date">Daily</option><option value="month">Monthly</option></select></label>
        {mode === "date" ? <label>Date<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label> : <label>Month<input type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></label>}
        <button disabled={loading}>{loading ? "Loading..." : "Load Report"}</button>
        {mode === "date" ? <a className="button secondary" href={`/api/export/daily-collection?date=${date}`}>Export Daily CSV</a> : null}
        {canPrint && mode === "date" && report ? <PrintButton label="Print Daily Collection" /> : null}
      </form>
      {message ? <div className="error" role="alert">{message}</div> : null}
      {report ? (
        <div className="print-document daily-collection-document">
          <header className="daily-print-header">
            <div>
              <div className="daily-school-print print-only">
                <h2>{settings.schoolName}</h2>
                {settings.showSchoolAddress ? <p>{settings.addressLine1}, {settings.city}</p> : null}
                {settings.showSchoolPhone ? <p>Tel: {settings.phone}</p> : null}
              </div>
              <h2>{mode === "date" ? "Daily Collection Report" : "Monthly Collection Report"}</h2>
              <p>{mode === "date" ? `Date: ${date}` : `Month: ${month}`}</p>
            </div>
            <div>
              <p>Generated by: {generatedBy}</p>
              <p>Generated: {generatedAt}</p>
            </div>
          </header>
          <div className="grid stats">
            <div className="card stat"><span>Cash</span><strong>{money(report.totalCash)}</strong></div>
            <div className="card stat"><span>Director Sir GPay</span><strong>{money(report.totalDirectorGPay)}</strong></div>
            <div className="card stat"><span>NPS Current Account UPI</span><strong>{money(report.totalNpsUpi)}</strong></div>
            <div className="card stat"><span>NPS Bank Account</span><strong>{money(report.totalBank)}</strong></div>
            <div className="card stat"><span>Cheque</span><strong>{money(report.totalCheque)}</strong></div>
            <div className="card stat"><span>Other</span><strong>{money(report.totalOther)}</strong></div>
            <div className="card stat"><span>Grand Total</span><strong>{money(report.grandTotal)}</strong></div>
            <div className="card stat"><span>Receipts Used</span><strong>{String(report.receipts.length)}</strong></div>
          </div>
          <div className="grid two">
            <Breakup title="Class-wise Collection" rows={report.byClass} />
            <Breakup
              title="Term-wise Collection Estimate"
              rows={report.byTerm}
              helperText="Auto allocation means the software allocated the amount by fee rules."
            />
          </div>
          <section className="card">
            <div className="section-title"><h3>Receipt List</h3></div>
            <div className="card-pad receipt-link-list">
              {report.receipts.length ? report.receipts.map((receipt) =>
                canPrintReceipt ? <Link key={receipt} href={`/receipts/${encodeURIComponent(receipt)}/print`} target="_blank">{receipt}</Link> : <span key={receipt}>{receipt}</span>
              ) : "No receipts"}
            </div>
          </section>
          <section className="card">
            <div className="section-title"><h3>Student-wise Collection</h3></div>
            <div className="table-wrap">
              <table>
                <thead><tr><th>Student</th><th>Total</th></tr></thead>
                <tbody>
                  {Object.entries(report.byStudent).map(([name, total]) => <tr key={name}><td>{name}</td><td>{money(total)}</td></tr>)}
                  {!Object.keys(report.byStudent).length ? <tr><td colSpan={2}>No student collections found.</td></tr> : null}
                </tbody>
              </table>
            </div>
          </section>
        </div>
      ) : null}
    </div>
  );
}

function Breakup({ title, rows, helperText }: { title: string; rows: Record<string, number>; helperText?: string }) {
  return (
    <section className="card">
      <div className="section-title">
        <div>
          <h3>{title}</h3>
          {helperText ? <p className="muted-text">{helperText}</p> : null}
        </div>
      </div>
      <div className="table-wrap">
        <table>
          <thead><tr><th>Name</th><th>Total</th></tr></thead>
          <tbody>
            {Object.entries(rows).map(([name, total]) => <tr key={name}><td>{name}</td><td>{money(total)}</td></tr>)}
            {!Object.keys(rows).length ? <tr><td colSpan={2}>No collection data found.</td></tr> : null}
          </tbody>
        </table>
      </div>
    </section>
  );
}
