"use client";
import { FormEvent, useEffect, useState } from "react";
export function EmployeePayrollSelfService() {
  const [data,setData]=useState<any>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[amount,setAmount]=useState(""),[reason,setReason]=useState("");
  async function load(){setError("");try{const response=await fetch("/api/my-payroll",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Your payroll records could not be loaded.");setData(body);}catch(caught){setError(caught instanceof Error?caught.message:"Your payroll records could not be loaded.");}}
  useEffect(()=>{void load();},[]);
  async function requestAdvance(event:FormEvent){event.preventDefault();setError("");setMessage("");try{const response=await fetch("/api/my-payroll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestedAmount:amount,requestedReason:reason})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Advance request was refused.");setAmount("");setReason("");setMessage("Advance request recorded. This does not create a disbursement.");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Advance request was refused.");}}
  if(error&&!data)return <div className="form-error" role="alert">{error}</div>; if(!data)return <p>Loading your private payroll records…</p>; if(!data.linked)return <div className="empty-state">{data.message}</div>;
  return <div className="payroll-workspace employee-payroll"><div className="callout"><strong>Private self-service.</strong> These records belong only to your linked Staff profile. Switch out of Parent context before access.</div><div role="status" aria-live="polite">{message}</div>{error&&<div className="form-error" role="alert">{error}</div>}<section className="card"><h2>Current salary structure</h2>{data.currentSalaryStructure?<><h3>{data.currentSalaryStructure.structure.name} v{data.currentSalaryStructure.structure.version}</h3><p>Effective {data.currentSalaryStructure.effectiveFrom}; estimated gross {data.currentSalaryStructure.estimatedGross}.</p><ul>{data.currentSalaryStructure.components.map((c:any)=><li key={c.code}>{c.name}: {c.configuredAmount||c.percentage||c.mode}</li>)}</ul></>:<p>No current compensation assignment.</p>}</section><section><h2>Issued payslips</h2><div className="payroll-card-grid">{data.payslips.map((p:any)=><article className="card" key={p.reference}><h3>{p.payrollMonth}</h3><p>Version {p.version} · issued {p.issueDate}</p><div className="action-row"><a className="button primary" href={p.downloadUrl}>Download colour PDF</a><a className="button" href={`${p.downloadUrl}?mode=monochrome`}>Printer-safe PDF</a></div></article>)}</div></section><section><h2>Payroll calculations and approved inputs</h2>{data.payrollResults.map((r:any)=><details className="card" key={r.key}><summary>{r.month}: {r.net} net</summary><p>Gross {r.gross}; deductions {r.deductions}; reimbursements {r.reimbursements}.</p>{r.components.map((c:any)=><div key={c.code}><strong>{c.name}: {c.amount}</strong><small>{c.formula} · {c.sourceVersion}</small></div>)}</details>)}</section><section><h2>Salary revision history</h2>{data.revisions.map((r:any)=><article className="card" key={r.key}><strong>{r.effectiveDate}: {r.oldGross} → {r.newGross}</strong><p>{r.reason}</p></article>)}</section><section><h2>Advance balance and recovery schedule</h2><form className="card form-stack compact-form" onSubmit={requestAdvance}><label>Requested amount (INR)<input value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} required/></label><button className="button primary">Request salary advance</button><small>No payment or disbursement is created by this request.</small></form>{data.advances.map((a:any)=><article className="card" key={a.key}><h3>{a.number} · {a.status}</h3><p>Remaining balance {a.remainingBalance}</p><ol>{a.schedule.map((s:any)=><li key={s.key}>{s.period?.month}: {s.scheduledAmount} — {s.status}</li>)}</ol></article>)}</section><p className="field-hint">{data.explanation}</p></div>;
}
