"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
type Action = "open" | "close" | "approve" | "lock" | "cancel";
export function ExamWorkflowActions({ exam, canManage, canApprove, canLock }: { exam: { id: string; name: string; status: string; updatedAt: string }; canManage: boolean; canApprove: boolean; canLock: boolean }) {
  const router = useRouter(); const [pending, setPending] = useState<Action | null>(null); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const allowed: Record<string, Action[]> = { DRAFT: ["open", "cancel"], OPEN_FOR_ENTRY: ["close", "cancel"], ENTRY_CLOSED: ["approve", "cancel"], APPROVED: ["lock", "cancel"], LOCKED: [], CANCELLED: [] };
  const labels: Record<Action, string> = { open: "Open Marks Entry", close: "Close Entry", approve: "Approve Exam", lock: "Lock Exam", cancel: "Cancel Exam" };
  async function confirm() { if (!pending) return; if (pending === "cancel" && !reason.trim()) { setError("Cancellation reason is required."); return; } setBusy(true); setError(""); try { const response = await fetch(`/api/exams/${encodeURIComponent(exam.id)}/workflow`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: pending, reason, expectedUpdatedAt: exam.updatedAt }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to update exam"); setPending(null); setReason(""); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update exam"); } finally { setBusy(false); } }
  const actions = (allowed[exam.status] ?? []).filter((action) => action === "approve" ? canApprove : action === "lock" ? canLock : canManage);
  return <div className="exam-actions"><div className="page-actions">{actions.map((action) => <button type="button" key={action} className={action === "cancel" ? "danger" : action === "lock" ? undefined : "secondary"} onClick={() => { setError(""); setPending(action); }}>{labels[action]}</button>)}</div>{error ? <div className="notice danger" role="alert">{error}</div> : null}{pending ? <div className="confirmation-overlay" role="presentation"><section className="card confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="exam-action-title" aria-describedby="exam-action-description"><h3 id="exam-action-title">{labels[pending]}</h3><p id="exam-action-description">{pending === "open" ? "Assessment configuration will be protected and authorised marks-entry operators can enter marks." : pending === "close" ? "All active sheets must already be submitted. Ordinary mark editing will stop." : pending === "approve" ? "All active sheets must already be approved. Approval does not lock the exam." : pending === "lock" ? "All active sheets must already be locked. The raw-mark snapshot will become immutable." : "The exam and its history will be preserved as Cancelled."}</p>{pending === "cancel" ? <label>Cancellation reason (required)<textarea autoFocus rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></label> : null}<div className="page-actions"><button type="button" className="secondary" disabled={busy} onClick={() => setPending(null)}>Go Back</button><button type="button" className={pending === "cancel" ? "danger" : undefined} disabled={busy} onClick={confirm}>Confirm {labels[pending]}</button></div></section></div> : null}</div>;
}
