"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function ExamForm({ academicYear, examId, initial }: { academicYear: string; examId?: string; initial?: { examCode: string; academicYear: string; name: string; examType: string; startDate: string; endDate: string; description: string; updatedAt: string } }) {
  const router = useRouter(); const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const [form, setForm] = useState(initial ? { examCode: initial.examCode, academicYear: initial.academicYear, name: initial.name, examType: initial.examType, startDate: initial.startDate, endDate: initial.endDate, description: initial.description } : { examCode: "", academicYear, name: "", examType: "TERM", startDate: today, endDate: today, description: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const field = (key: keyof typeof form) => ({ value: form[key], onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setForm((value) => ({ ...value, [key]: event.target.value })) });
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { const response = await fetch(examId ? `/api/exams/${encodeURIComponent(examId)}` : "/api/exams", { method: examId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, expectedUpdatedAt: initial?.updatedAt }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to save exam"); if (examId) { setMessage("Draft exam updated."); router.refresh(); } else { router.push(`/exams/${encodeURIComponent(data.exam.id)}`); router.refresh(); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to save exam"); } finally { setBusy(false); } }
  return <form className="card card-pad form-grid exam-form" onSubmit={save}><label>Exam code<input required maxLength={40} placeholder="TERM-1-2026" {...field("examCode")} /></label><label>Academic year<input required pattern="\d{4}-\d{2}" {...field("academicYear")} /></label><label className="wide">Exam name<input required maxLength={160} {...field("name")} /></label><label>Exam type<select {...field("examType")}>{["UNIT_TEST", "FORMATIVE", "SUMMATIVE", "TERM", "PRACTICAL", "OTHER"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Start date<input required type="date" {...field("startDate")} /></label><label>End date<input required type="date" {...field("endDate")} /></label><label className="full">Description (optional)<textarea rows={4} maxLength={2000} {...field("description")} /></label><div className="full page-actions"><button disabled={busy} type="submit">{examId ? "Save Draft Changes" : "Create Draft Exam"}</button></div>{message ? <div className="full notice success" role="status">{message}</div> : null}{error ? <div className="full notice danger" role="alert">{error}</div> : null}</form>;
}
