"use client";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { useSecurityDialog } from "@/components/security-dialog-provider";

type Option = { id: string; name: string; code?: string | null; vendorCode?: string };
type Expense = any;
function dateInput(value?: string | Date | null) { if (!value) return ""; return new Date(value).toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" }); }

export function ExpenseForm({ expense, masters, permissions }: { expense?: Expense; masters: { vendors: Option[]; categories: Option[]; departments: Option[] }; permissions: { manage: boolean; approve: boolean; pay: boolean; cancel: boolean } }) {
  const router = useRouter(); const isDraft = !expense || expense.approvalStatus === "DRAFT"; const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [rejectionReason, setRejectionReason] = useState(""); const [cancellationReason, setCancellationReason] = useState("");
  const requestDialog = useSecurityDialog();
  const [form, setForm] = useState({ expenseDate: dateInput(expense?.expenseDate) || dateInput(new Date()), academicYear: expense?.academicYear ?? "2026-27", vendorId: expense?.vendor?.id ?? "", categoryId: expense?.category?.id ?? "", departmentId: expense?.department?.id ?? "", description: expense?.description ?? "", invoiceNumber: expense?.invoiceNumber ?? "", invoiceDate: dateInput(expense?.invoiceDate), grossAmount: expense?.grossAmount ?? "", taxAmount: expense?.taxAmount ?? "0", deductionAmount: expense?.deductionAmount ?? "0", netAmount: expense?.netAmount ?? "", paymentMethod: expense?.paymentMethod ?? "CASH", transactionReference: expense?.transactionReference ?? "", chequeNumber: expense?.chequeNumber ?? "", chequeDate: dateInput(expense?.chequeDate), notes: expense?.notes ?? "" });
  const calculatedNet = useMemo(() => { const value = Number(form.grossAmount || 0) + Number(form.taxAmount || 0) - Number(form.deductionAmount || 0); return Number.isFinite(value) ? value.toFixed(2) : ""; }, [form.grossAmount, form.taxAmount, form.deductionAmount]);
  const update = (key: string, value: string) => setForm((old) => ({ ...old, [key]: value }));
  async function save(submit = false) { setBusy(true); setError(""); setMessage(""); try { const payload = { ...form, netAmount: form.netAmount || calculatedNet }; const response = await fetch(expense?.id ? `/api/expenses/${expense.id}` : "/api/expenses", { method: expense?.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to save expense"); const id = expense?.id ?? data.expense.id; if (submit) { if (!await requestDialog({ title: "Submit expense?", message: "It cannot be edited while pending.", confirmLabel: "Submit expense" })) return; await workflow(id, "submit", {}, false); } else { setMessage(expense?.id ? "Draft expense updated." : "Draft expense created."); if (!expense?.id) router.push(`/expenses/${id}`); else router.refresh(); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to save expense"); } finally { setBusy(false); } }
  async function workflow(id: string, action: string, extra: Record<string, unknown> = {}, needsConfirmation = true) { if (needsConfirmation) { const warning = action === "approve" ? "Approved amounts cannot be silently edited." : action === "pay" ? "The payment becomes part of the audit record." : action === "reject" ? "Reject this expense with the entered reason?" : action === "cancel" ? "It will remain in audit reports and cannot be deleted." : "Continue with this action?"; if (!await requestDialog({ title: `${action[0].toUpperCase()}${action.slice(1)} expense?`, message: warning, confirmLabel: `${action[0].toUpperCase()}${action.slice(1)} expense` })) return; } setBusy(true); setError(""); try { const response = await fetch(`/api/expenses/${id}/workflow`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...extra }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to update expense"); setMessage(action === "submit" ? "Expense submitted for approval." : action === "approve" ? "Expense approved." : action === "pay" ? "Payment recorded." : action === "reject" ? "Expense rejected and preserved." : "Expense cancelled and preserved."); router.refresh(); if (action === "submit" && !expense?.id) router.push(`/expenses/${id}`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update expense"); } finally { setBusy(false); } }
  const editable = permissions.manage && isDraft;
  return <div className="expense-stack">
    {editable ? <section className="card card-pad"><div className="form-grid expense-form-grid">
      <label>Expense Date<input aria-label="Expense Date" type="date" value={form.expenseDate} onChange={(e) => update("expenseDate", e.target.value)} /></label><label>Academic Year<input aria-label="Academic Year" value={form.academicYear} onChange={(e) => update("academicYear", e.target.value)} /></label>
      <label>Category<select aria-label="Category" value={form.categoryId} onChange={(e) => update("categoryId", e.target.value)}><option value="">Choose category</option>{masters.categories.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
      <label>Vendor <span className="muted-text">(optional)</span><select aria-label="Vendor" value={form.vendorId} onChange={(e) => update("vendorId", e.target.value)}><option value="">No vendor</option>{masters.vendors.map((row) => <option key={row.id} value={row.id}>{row.name} ({row.vendorCode})</option>)}</select></label>
      <label>Department <span className="muted-text">(optional)</span><select aria-label="Department" value={form.departmentId} onChange={(e) => update("departmentId", e.target.value)}><option value="">No department</option>{masters.departments.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
      <label className="wide">Description<textarea aria-label="Expense Description" value={form.description} onChange={(e) => update("description", e.target.value)} /></label>
      <label>Invoice Number <span className="muted-text">(optional)</span><input aria-label="Invoice Number" value={form.invoiceNumber} onChange={(e) => update("invoiceNumber", e.target.value)} /></label><label>Invoice Date <span className="muted-text">(optional)</span><input aria-label="Invoice Date" type="date" value={form.invoiceDate} onChange={(e) => update("invoiceDate", e.target.value)} /></label>
      <label>Gross Amount<input aria-label="Gross Amount" type="number" min="0" step="0.01" value={form.grossAmount} onChange={(e) => update("grossAmount", e.target.value)} /></label><label>Tax Amount<input aria-label="Tax Amount" type="number" min="0" step="0.01" value={form.taxAmount} onChange={(e) => update("taxAmount", e.target.value)} /></label><label>Deduction Amount<input aria-label="Deduction Amount" type="number" min="0" step="0.01" value={form.deductionAmount} onChange={(e) => update("deductionAmount", e.target.value)} /></label><label>Net Amount<input aria-label="Net Amount" type="number" min="0" step="0.01" placeholder={calculatedNet} value={form.netAmount} onChange={(e) => update("netAmount", e.target.value)} /><small>Gross + tax - deduction = {calculatedNet}</small></label>
      <label>Expected Payment Method<select aria-label="Payment Method" value={form.paymentMethod} onChange={(e) => update("paymentMethod", e.target.value)}>{["CASH", "UPI", "BANK_TRANSFER", "NEFT", "RTGS", "IMPS", "CHEQUE", "OTHER"].map((value) => <option key={value}>{value}</option>)}</select></label>
      {form.paymentMethod !== "CASH" ? <label>Reference <span className="muted-text">(required when paid)</span><input aria-label="Transaction Reference" value={form.transactionReference} onChange={(e) => update("transactionReference", e.target.value)} /></label> : null}
      {form.paymentMethod === "CHEQUE" ? <><label>Cheque Number<input aria-label="Cheque Number" value={form.chequeNumber} onChange={(e) => update("chequeNumber", e.target.value)} /></label><label>Cheque Date<input aria-label="Cheque Date" type="date" value={form.chequeDate} onChange={(e) => update("chequeDate", e.target.value)} /></label></> : null}
      <label className="wide">Notes <span className="muted-text">(optional)</span><textarea aria-label="Expense Notes" value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label>
      <div className="full page-actions"><button type="button" className="secondary" disabled={busy} onClick={() => save(false)}>Save Draft</button><button type="button" disabled={busy} onClick={() => save(true)}>Save and Submit</button></div>
    </div></section> : null}
    {expense ? <section className="card card-pad workflow-panel"><h3>Workflow Actions</h3>{expense.approvalStatus === "DRAFT" && permissions.manage ? <button disabled={busy} onClick={() => workflow(expense.id, "submit")}>Submit for Approval</button> : null}{expense.approvalStatus === "PENDING_APPROVAL" && permissions.approve ? <><button disabled={busy} onClick={() => workflow(expense.id, "approve")}>Approve Expense</button><label>Rejection Reason (required)<textarea aria-label="Rejection Reason" value={rejectionReason} onChange={(e) => setRejectionReason(e.target.value)} /></label><button className="danger" disabled={busy} onClick={() => workflow(expense.id, "reject", { reason: rejectionReason })}>Reject Expense</button></> : null}{expense.approvalStatus === "APPROVED" && expense.paymentStatus !== "PAID" && permissions.pay ? <PaymentAction expense={expense} busy={busy} onPay={(values) => workflow(expense.id, "pay", values)} /> : null}{expense.approvalStatus !== "CANCELLED" && permissions.cancel ? <><label>Cancellation Reason (required)<textarea aria-label="Cancellation Reason" value={cancellationReason} onChange={(e) => setCancellationReason(e.target.value)} /></label><button className="danger" disabled={busy} onClick={() => workflow(expense.id, "cancel", { reason: cancellationReason })}>Cancel Expense</button></> : null}</section> : null}
    {message ? <div className="notice success" role="status">{message}</div> : null}{error ? <div className="notice danger" role="alert">{error}</div> : null}
  </div>;
}

function PaymentAction({ expense, busy, onPay }: { expense: Expense; busy: boolean; onPay: (values: Record<string, unknown>) => void }) {
  const paid = (expense.payments ?? []).reduce((sum: number, row: any) => sum + Number(row.amount), 0); const remaining = Math.max(0, Number(expense.netAmount) - paid); const [values, setValues] = useState({ amount: remaining.toFixed(2), paymentDate: dateInput(new Date()), paymentMethod: expense.paymentMethod ?? "CASH", transactionReference: expense.transactionReference ?? "", chequeNumber: expense.chequeNumber ?? "", chequeDate: dateInput(expense.chequeDate), notes: "" }); const update = (key: string, value: string) => setValues((old) => ({ ...old, [key]: value }));
  return <div className="payment-action"><p><strong>Remaining: ₹{remaining.toFixed(2)}</strong>. Partial payments are recorded separately.</p><div className="form-grid"><label>Payment Amount<input aria-label="Payment Amount" type="number" min="0.01" step="0.01" max={remaining} value={values.amount} onChange={(e) => update("amount", e.target.value)} /></label><label>Payment Date<input aria-label="Payment Date" type="date" value={values.paymentDate} onChange={(e) => update("paymentDate", e.target.value)} /></label><label>Payment Method<select aria-label="Final Payment Method" value={values.paymentMethod} onChange={(e) => update("paymentMethod", e.target.value)}>{["CASH", "UPI", "BANK_TRANSFER", "NEFT", "RTGS", "IMPS", "CHEQUE", "OTHER"].map((value) => <option key={value}>{value}</option>)}</select></label>{values.paymentMethod !== "CASH" && values.paymentMethod !== "CHEQUE" ? <label>Transaction Reference<input aria-label="Final Transaction Reference" value={values.transactionReference} onChange={(e) => update("transactionReference", e.target.value)} /></label> : null}{values.paymentMethod === "CHEQUE" ? <><label>Cheque Number<input aria-label="Final Cheque Number" value={values.chequeNumber} onChange={(e) => update("chequeNumber", e.target.value)} /></label><label>Cheque Date<input aria-label="Final Cheque Date" type="date" value={values.chequeDate} onChange={(e) => update("chequeDate", e.target.value)} /></label></> : null}</div><button disabled={busy} onClick={() => onPay(values)}>Record Payment</button></div>;
}
