"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type TargetOption = { academicYear: string; className: string; section: string | null; subjectName: string };
type Assignment = { assignmentNumber: string; academicYear: string; title: string; instructions: string; className: string; section: string | null; subjectName: string; assignedDate: string; dueDate: string | null; status: string; priority: string; resourceLink: string | null; teacherNotes?: string | null; publicNotes: string | null; updatedAt: string };
type PendingAction = { action: "publish" | "correct" | "archive" | "cancel"; title: string; description: string; reasonRequired: boolean };

export function HomeworkEditor({ assignment, targetOptions, academicYear, canManage, canPublish, canArchive }: { assignment?: Assignment | null; targetOptions: TargetOption[]; academicYear: string; canManage: boolean; canPublish: boolean; canArchive: boolean }) {
  const router = useRouter(); const first = targetOptions[0];
  const [form, setForm] = useState({ academicYear: assignment?.academicYear ?? first?.academicYear ?? academicYear, className: assignment?.className ?? first?.className ?? "", section: assignment?.section ?? first?.section ?? "", subjectName: assignment?.subjectName ?? first?.subjectName ?? "", title: assignment?.title ?? "", instructions: assignment?.instructions ?? "", assignedDate: assignment?.assignedDate ?? todayInput(), dueDate: assignment?.dueDate ?? "", priority: assignment?.priority ?? "NORMAL", resourceLink: assignment?.resourceLink ?? "", publicNotes: assignment?.publicNotes ?? "", teacherNotes: assignment?.teacherNotes ?? "" });
  const [preview, setPreview] = useState<Record<string, unknown> | null>(null); const [pending, setPending] = useState<PendingAction | null>(null); const [reason, setReason] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const selectedKey = `${form.academicYear}|${form.className}|${form.section}|${form.subjectName}`;
  const options = useMemo(() => [...new Map(targetOptions.map((item) => [`${item.academicYear}|${item.className}|${item.section ?? ""}|${item.subjectName}`, item])).values()], [targetOptions]);
  const editableDraft = !assignment || assignment.status === "DRAFT"; const correctable = assignment?.status === "PUBLISHED" && canPublish; const fieldsDisabled = Boolean(assignment && !editableDraft && !correctable);

  function chooseTarget(value: string) { const target = options.find((item) => `${item.academicYear}|${item.className}|${item.section ?? ""}|${item.subjectName}` === value); if (target) setForm((current) => ({ ...current, academicYear: target.academicYear, className: target.className, section: target.section ?? "", subjectName: target.subjectName })); }
  async function request(url: string, method: string, body: unknown) { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to save homework"); return data; }
  async function previewHomework() { setBusy(true); setError(""); try { const data = await request("/api/homework/preview", "POST", form); setPreview(data.preview); setMessage("Preview validated. Nothing has been published."); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function saveDraft() { setBusy(true); setError(""); setMessage(""); try { const data = assignment ? await request(`/api/homework/${encodeURIComponent(assignment.assignmentNumber)}`, "PATCH", { ...form, expectedUpdatedAt: assignment.updatedAt }) : await request("/api/homework", "POST", { ...form, publish: false }); setMessage(assignment ? "Draft homework updated." : "Draft homework saved."); router.push(`/homework/${encodeURIComponent(data.assignment.assignmentNumber)}`); router.refresh(); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function confirmAction() { if (!pending) return; if (pending.reasonRequired && !reason.trim()) { setError(`${pending.action === "correct" ? "Correction" : "Cancellation"} reason is required.`); return; } setBusy(true); setError(""); try { if (!assignment && pending.action === "publish") { const data = await request("/api/homework", "POST", { ...form, publish: true }); router.push(`/homework/${encodeURIComponent(data.assignment.assignmentNumber)}`); } else if (assignment) { const payload = pending.action === "correct" ? { ...form, reason, expectedUpdatedAt: assignment.updatedAt } : { reason, expectedUpdatedAt: assignment.updatedAt }; await request(`/api/homework/${encodeURIComponent(assignment.assignmentNumber)}/${pending.action}`, "POST", payload); router.refresh(); } setMessage(pending.action === "publish" ? "Homework published to matching linked children." : pending.action === "correct" ? "Published homework corrected with its previous snapshot preserved." : pending.action === "archive" ? "Homework archived and preserved." : "Homework cancelled and preserved."); setPending(null); setReason(""); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  function open(action: PendingAction["action"]) { const details: Record<PendingAction["action"], Omit<PendingAction, "action">> = { publish: { title: "Publish homework", description: "Matching linked parents will be able to see this homework. Published content can change only through an audited correction.", reasonRequired: false }, correct: { title: "Correct published homework", description: "The previous public content will be preserved in append-only history.", reasonRequired: true }, archive: { title: "Archive homework", description: "This preserves the assignment and removes it from the current Parent list. It remains available in history.", reasonRequired: false }, cancel: { title: "Cancel homework", description: "This preserves the assignment. Previously published homework remains visible as Cancelled in Parent history.", reasonRequired: true } }; setError(""); setReason(""); setPending({ action, ...details[action] }); }

  return <div className="homework-editor-stack">{targetOptions.length===0&&!assignment?<div className="notice">No authorised class/subject assignments found. An authorised administrator must complete the StaffMember and timetable links.</div>:null}<section className="card card-pad"><div className="form-grid homework-form-grid">
    <label className="wide">Class, section, and subject<select aria-label="Authorised homework target" value={selectedKey} disabled={fieldsDisabled||Boolean(assignment&&assignment.status!=="DRAFT")||options.length===0} onChange={(e)=>chooseTarget(e.target.value)}><option value="">Choose authorised target</option>{options.map((item)=>{const key=`${item.academicYear}|${item.className}|${item.section??""}|${item.subjectName}`;return <option key={key} value={key}>{item.academicYear} - {item.className}{item.section?`-${item.section}`:" (all sections)"} - {item.subjectName}</option>})}</select></label>
    <label className="wide">Title<input required maxLength={180} disabled={fieldsDisabled} value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></label><label className="wide">Instructions<textarea required rows={7} disabled={fieldsDisabled} value={form.instructions} onChange={(e)=>setForm({...form,instructions:e.target.value})}/></label>
    <label>Assigned date<input type="date" required disabled={fieldsDisabled} value={form.assignedDate} onChange={(e)=>setForm({...form,assignedDate:e.target.value})}/></label><label>Due date <span className="muted-text">(optional)</span><input type="date" disabled={fieldsDisabled} value={form.dueDate} onChange={(e)=>setForm({...form,dueDate:e.target.value})}/></label><label>Priority<select disabled={fieldsDisabled} value={form.priority} onChange={(e)=>setForm({...form,priority:e.target.value})}><option value="NORMAL">Normal</option><option value="IMPORTANT">Important</option></select></label>
    <label className="wide">Safe resource link <span className="muted-text">(optional HTTP/HTTPS)</span><input type="url" disabled={fieldsDisabled} value={form.resourceLink} onChange={(e)=>setForm({...form,resourceLink:e.target.value})}/></label><label className="wide">Public notes <span className="muted-text">(visible to parents)</span><textarea rows={3} disabled={fieldsDisabled} value={form.publicNotes} onChange={(e)=>setForm({...form,publicNotes:e.target.value})}/></label><label className="wide">Teacher notes <span className="muted-text">(internal only)</span><textarea rows={3} disabled={fieldsDisabled} value={form.teacherNotes} onChange={(e)=>setForm({...form,teacherNotes:e.target.value})}/></label>
    <div className="full page-actions">{editableDraft&&canManage?<><button type="button" className="secondary" disabled={busy||options.length===0} onClick={previewHomework}>Preview</button><button type="button" disabled={busy||options.length===0} onClick={saveDraft}>{assignment?"Save Draft Changes":"Save Draft"}</button></>:null}{canPublish&&editableDraft?<button type="button" disabled={busy||options.length===0} onClick={()=>open("publish")}>{assignment?"Publish Saved Draft":"Publish"}</button>:null}{correctable?<button type="button" disabled={busy} onClick={()=>open("correct")}>Correct Published Homework</button>:null}{canArchive&&assignment?.status==="PUBLISHED"?<><button type="button" className="secondary" disabled={busy} onClick={()=>open("archive")}>Archive</button><button type="button" className="danger" disabled={busy} onClick={()=>open("cancel")}>Cancel Homework</button></>:null}</div>
  </div></section>{preview?<section className="card card-pad" aria-label="Homework preview"><h3>Parent Preview</h3><p className="muted-text">This preview does not publish or claim external delivery.</p><h4>{String(preview.title)}</h4><p>{String(preview.instructions)}</p><dl className="detail-list"><div><dt>Target</dt><dd>{String(preview.className)}{preview.section?`-${String(preview.section)}`:" - All sections"} - {String(preview.subjectName)}</dd></div><div><dt>Due date</dt><dd>{preview.dueDate?String(preview.dueDate):"No due date"}</dd></div></dl></section>:null}{message?<div className="notice success" role="status">{message}</div>:null}{error?<div className="notice danger" role="alert">{error}</div>:null}
  {pending?<div className="confirmation-overlay" role="presentation"><section className="card confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="homework-action-title" aria-describedby="homework-action-description"><h3 id="homework-action-title">{pending.title}</h3><p id="homework-action-description">{pending.description}</p>{pending.reasonRequired?<label>{pending.action==="correct"?"Correction reason":"Cancellation reason"} (required)<textarea autoFocus rows={3} value={reason} onChange={(e)=>setReason(e.target.value)}/></label>:null}<div className="page-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setPending(null)}>Go Back</button><button type="button" className={pending.action==="cancel"?"danger":undefined} disabled={busy} onClick={confirmAction}>Confirm {pending.title}</button></div></section></div>:null}</div>;
}
function todayInput(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());} function errorText(error:unknown){return error instanceof Error?error.message:"Unable to process homework";}
