"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Attachment = { publicKey: string; safeDisplayName: string; mediaType: string; byteSize: number; recoveryStatus: string };
type Feedback = { sequenceNumber: number; feedbackType: string; body: string; createdAt: string; createdByRole: string };
type Submission = { publicKey: string; status: string; rowVersion: number; versionNumber: number; textBody: string; attachments: Attachment[]; feedback: Feedback[] };
type Item = { publicKey: string; kind: string; subjectName: string; status: string; versionNumber: number | null; title: string; instructions: string; dueAt: string | null; dueState: string; attachments: Attachment[]; submission: Submission | null };
type LearnerData = { context: { studentLabel: string; academicYear: string; className: string; section: string; childHandle: string | null; contextVersion: number | null }; items: Item[] };

export function LearnerClasswork({ data }: { data: LearnerData }) {
  const router = useRouter(); const [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState(""); const [pending, setPending] = useState<Item | null>(null);
  const context = { childContext: data.context.childHandle, contextVersion: data.context.contextVersion };
  async function json(url: string, body: unknown) { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "The classwork request failed."); return result; }
  async function save(event: FormEvent<HTMLFormElement>, item: Item) { event.preventDefault(); setBusy(true); setError(""); try { const form = new FormData(event.currentTarget); await json(`/api/my-classwork/${item.publicKey}/draft`, { ...context, expectedVersion: item.submission?.rowVersion ?? null, textBody: form.get("textBody") }); setMessage("Private draft saved. It has not been submitted."); router.refresh(); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } }
  async function upload(event: FormEvent<HTMLFormElement>, item: Item) { event.preventDefault(); setBusy(true); setError(""); try { const form = new FormData(event.currentTarget); if (context.childContext) form.set("childContext", context.childContext); if (context.contextVersion) form.set("contextVersion", String(context.contextVersion)); const response = await fetch(`/api/my-classwork/${item.publicKey}/attachments`, { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Upload failed."); setMessage("Private attachment accepted. Submission stays blocked until encrypted recovery is verified."); router.refresh(); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } }
  async function submit() { if (!pending?.submission) return; setBusy(true); setError(""); try { await json(`/api/my-classwork/${pending.publicKey}/submit`, { ...context, expectedVersion: pending.submission.rowVersion, requestKey: crypto.randomUUID().replaceAll("-", "") }); setMessage("Submission recorded once with immutable version history."); setPending(null); router.refresh(); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } }
  const attachmentUrl = (file: Attachment) => `/api/classwork/attachments/${file.publicKey}?${new URLSearchParams(context.childContext ? { childContext: context.childContext, contextVersion: String(context.contextVersion ?? "") } : {}).toString()}`;
  return <div className="classwork-stack">{message ? <div className="notice success" role="status">{message}</div> : null}{error ? <div className="notice danger" role="alert">{error}</div> : null}<div className="notice"><strong>{data.context.studentLabel}</strong> · {data.context.academicYear} · {data.context.className}-{data.context.section}</div>
    {data.items.map((item) => { const editable = item.status === "PUBLISHED" && (!item.submission || ["DRAFT", "RETURNED"].includes(item.submission.status)); return <article className="card card-pad learner-classwork-card" key={item.publicKey}><div className="section-title section-title-plain"><div><h3>{item.title}</h3><p>{item.kind} · {item.subjectName} · instruction version {item.versionNumber}</p></div><span className="badge">{item.dueState}</span></div><p className="preserve-lines">{item.instructions}</p><p><strong>Due:</strong> {item.dueAt ? new Date(item.dueAt).toLocaleString("en-IN") : "No due date"}</p>{item.attachments.map((file) => <a className="button secondary" href={attachmentUrl(file)} target="_blank" rel="noreferrer" key={file.publicKey}>Open {file.safeDisplayName}</a>)}{item.submission ? <p><strong>Submission:</strong> <span className="badge">{item.submission.status}</span> · version {item.submission.versionNumber}</p> : <p>No submission draft yet.</p>}{editable ? <><form className="form-grid" onSubmit={(event) => save(event, item)}><label className="wide">Private text draft<textarea name="textBody" rows={5} maxLength={20000} defaultValue={item.submission?.textBody ?? ""} /></label><button disabled={busy}>Save private draft</button></form>{item.submission ? <form className="form-grid" onSubmit={(event) => upload(event, item)}><label className="wide">Private PDF, PNG, JPEG or still WebP<input type="file" name="file" required accept=".pdf,.png,.jpg,.jpeg,.webp,application/pdf,image/png,image/jpeg,image/webp" /></label><button disabled={busy}>Upload privately</button></form> : <div className="notice">Save a text draft before adding an attachment.</div>}{item.submission?.attachments.map((file) => <a className="button secondary" href={attachmentUrl(file)} target="_blank" rel="noreferrer" key={file.publicKey}>Preview {file.safeDisplayName} · {file.recoveryStatus}</a>)}{item.submission ? <button type="button" disabled={busy} onClick={() => setPending(item)}>{item.submission.versionNumber > 1 || item.submission.status === "RETURNED" ? "Resubmit work" : "Submit final work"}</button> : null}</> : null}{item.submission?.feedback.length ? <section className="classwork-feedback" aria-label="Teacher feedback"><h4>Teacher feedback</h4>{item.submission.feedback.map((feedback) => <blockquote key={feedback.sequenceNumber}><strong>{feedback.feedbackType}</strong><br />{feedback.body}</blockquote>)}</section> : null}</article>; })}{!data.items.length ? <section className="card card-pad"><h3>No classwork available</h3><p>There are no published items for this exact class and section.</p></section> : null}
    {pending ? <div className="confirmation-overlay"><section className="card confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="learner-submit-title"><h3 id="learner-submit-title">Submit immutable work</h3><p>Your current text and verified attachments become an immutable submission version. A revision is possible only after Teacher return.</p><div className="page-actions"><button type="button" className="secondary" onClick={() => setPending(null)}>Go back</button><button type="button" disabled={busy} onClick={submit}>Confirm submission</button></div></section></div> : null}
  </div>;
}

function errorText(cause: unknown) { return cause instanceof Error ? cause.message : "The classwork request failed."; }
