"use client";

import { useEffect, useRef, useState } from "react";

async function send(url: string, method = "POST", body?: unknown) {
  const response = await fetch(url, { method, headers: body === undefined ? undefined : { "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  const json = await response.json();
  if (!response.ok) throw new Error(json.error ?? "Request failed");
  return json;
}

export function BarcodeAssignForm({ copies }: { copies: Array<{ id: string; accessionNumber: string; barcodeValue: string | null; title: { title: string } }> }) {
  const [preview, setPreview] = useState<any>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  function review(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const copy = copies.find((item) => item.id === data.copyId); setPreview({ ...data, barcodeValue: String(data.barcodeValue ?? "").trim().toUpperCase(), copy }); setMessage("Preview ready. No barcode has been assigned."); }
  async function confirm() { if (!preview) return; setBusy(true); try { await send("/api/library/barcodes/assign", "POST", preview); setMessage("Barcode assignment saved with an append-only copy event."); setTimeout(() => location.reload(), 350); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to assign barcode"); } finally { setBusy(false); } }
  return <><form className="card card-pad form-grid" onSubmit={review}><label className="wide">Exact physical copy<select name="copyId" required defaultValue=""><option value="">Select copy</option>{copies.map((copy) => <option key={copy.id} value={copy.id}>{copy.accessionNumber} — {copy.title.title}{copy.barcodeValue ? ` (currently ${copy.barcodeValue})` : ""}</option>)}</select></label><label>Barcode value<input name="barcodeValue" required maxLength={80} /></label><label>Mode<select name="correction" defaultValue="false"><option value="false">New assignment</option><option value="true">Explicit correction</option></select></label><label className="wide">Correction reason (required only when replacing an assigned barcode)<textarea name="reason" maxLength={1000} /></label><div className="wide page-actions"><button>Preview assignment</button><span role="status">{message}</span></div></form>{preview ? <section className="card card-pad"><h3>Confirm barcode {preview.correction === "true" ? "correction" : "assignment"}</h3><p><strong>{preview.copy?.accessionNumber}</strong> → <code>{preview.barcodeValue}</code></p><p className="muted">Code 39 only. This does not alter the immutable accession number.</p><button disabled={busy} onClick={confirm}>{busy ? "Saving…" : "Confirm barcode"}</button></section> : null}</>;
}

export function BarcodeBulkForm({ copies }: { copies: Array<{ id: string; accessionNumber: string; barcodeValue: string | null }> }) {
  const [rows, setRows] = useState<any[]>([]); const [message, setMessage] = useState(""); const missing = copies.filter((c) => !c.barcodeValue); const ids = missing.map((c) => c.id);
  async function preview() { try { const json = await send("/api/library/barcodes/bulk", "POST", { copyIds: ids, action: "preview" }); setRows(json.rows); setMessage("Preview created. No records were written."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to preview bulk assignment"); } }
  async function confirm() { try { const json = await send("/api/library/barcodes/bulk", "POST", { copyIds: ids, action: "confirm" }); setRows(json.rows); setMessage("Bulk confirmation completed. Re-running skips assigned rows."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to confirm bulk assignment"); } }
  return <section className="card card-pad"><h3>Generate from accession number</h3><p>Format: <code>NPS-LIB-&#123;NORMALIZED_ACCESSION&#125;</code>. Only copies missing barcodes are considered.</p><div className="page-actions"><button onClick={preview}>Preview {missing.length} missing copies</button>{rows.length ? <button className="secondary" onClick={confirm}>Confirm valid rows</button> : null}<span role="status">{message}</span></div>{rows.length ? <div className="table-wrap"><table><thead><tr><th>Accession</th><th>Proposed barcode</th><th>Result</th></tr></thead><tbody>{rows.map((row) => <tr key={row.copyId}><td>{row.accessionNumber}</td><td>{row.barcodeValue}</td><td>{row.status} — {row.message}</td></tr>)}</tbody></table></div> : null}</section>;
}

export function LabelPrintClient({ accessions }: { accessions: string[] }) {
  const [labels, setLabels] = useState<any[]>([]); const [message, setMessage] = useState("");
  async function load() { try { const query = accessions.map((v) => `accession=${encodeURIComponent(v)}`).join("&"); const json = await send(`/api/library/barcodes/labels?${query}`, "GET"); setLabels(json.labels); setMessage(`${json.labels.length} valid black-and-white Code 39 labels ready.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to prepare labels"); } }
  useEffect(() => { void load(); }, []);
  return <section className="card card-pad"><div className="page-actions"><button onClick={() => window.print()}>Print selected labels</button><button className="secondary" onClick={load}>Refresh preview</button><span role="status">{message}</span></div><div className="barcode-label-sheet">{labels.map((label) => <article className="barcode-label" key={label.accessionNumber}><strong>NPS</strong><div dangerouslySetInnerHTML={{ __html: label.svg }} /><small>{label.accessionNumber} · {label.title.slice(0, 48)}</small>{label.shelfCode ? <small>Shelf {label.shelfCode}</small> : null}</article>)}</div></section>;
}

export function ScannerAssist() {
  const [mode, setMode] = useState("copy"); const [value, setValue] = useState(""); const [memberCode, setMemberCode] = useState(""); const [result, setResult] = useState<any>(null); const [message, setMessage] = useState(""); const [fallback, setFallback] = useState(false); const [returnCondition, setReturnCondition] = useState("GOOD"); const [returnNotes, setReturnNotes] = useState(""); const last = useRef({ value: "", at: 0 }); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { input.current?.focus(); }, [mode]);
  function reset() { setValue(""); setResult(null); setMessage(""); last.current = { value: "", at: 0 }; input.current?.focus(); }
  async function lookup(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const normalized = value.trim().toUpperCase(); if (!normalized) return; if (last.current.value === normalized && Date.now() - last.current.at < 1500) { setMessage("Duplicate scanner transmission ignored. Use Reset to deliberately rescan."); return; } last.current = { value: normalized, at: Date.now() }; try { let json; if (mode === "member") json = await send(`/api/library/scanner/member?memberCode=${encodeURIComponent(normalized)}`, "GET"); else if (mode === "copy") json = await send(`/api/library/scanner/copy?value=${encodeURIComponent(normalized)}&accessionFallback=${fallback}`, "GET"); else if (mode === "issue") { if (!memberCode) { setMemberCode(normalized); setValue(""); setMessage("Member captured. Scan the copy barcode next."); return; } json = await send("/api/library/scanner/issue", "POST", { action: "preview", memberCode, barcodeValue: normalized, issueDate: new Date().toISOString().slice(0, 10) }); } else json = await send("/api/library/scanner/return", "POST", { action: "preview", barcodeValue: normalized }); setResult(json); setMessage("Exact lookup complete. Review before any action."); } catch (error) { setResult(null); setMessage(error instanceof Error ? error.message : "Lookup failed"); } }
  async function confirm() { try { if (mode === "issue") await send("/api/library/scanner/issue", "POST", { action: "confirm", memberCode, barcodeValue: value, issueDate: new Date().toISOString().slice(0, 10) }); if (mode === "return") await send("/api/library/scanner/return", "POST", { action: "confirm", barcodeValue: value, returnedDate: new Date().toISOString().slice(0, 10), returnCondition, returnNotes }); setMessage(`${mode === "issue" ? "Issue" : "Return"} confirmed through the existing transactional helper.`); setResult(null); setValue(""); if (mode === "issue") setMemberCode(""); input.current?.focus(); } catch (error) { setMessage(error instanceof Error ? error.message : "Confirmation failed"); } }
  const ready = mode === "issue" ? result?.preview : mode === "return" ? result?.preview : null; const scannerLabel = mode === "issue" && !memberCode ? "Scan or type member code" : mode === "member" ? "Scan or type member code" : "Scan or type barcode";
  return <section className="card card-pad"><div className="form-grid"><label>Operational mode<select value={mode} onChange={(e) => { setMode(e.target.value); reset(); setMemberCode(""); }}><option value="copy">Copy lookup</option><option value="issue">Issue assist</option><option value="return">Return assist</option><option value="member">Member lookup</option></select></label>{mode === "copy" ? <label><input type="checkbox" checked={fallback} onChange={(e) => setFallback(e.target.checked)} /> Enable exact accession fallback</label> : null}</div><form className="form-grid" onSubmit={lookup}><label className="wide">{scannerLabel}<div className="page-actions"><input ref={input} value={value} onChange={(e) => setValue(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); e.currentTarget.form?.requestSubmit(); } }} aria-label="Scanner input" autoComplete="off" /><button>Lookup</button><button type="button" className="secondary" onClick={reset}>Reset / rescan</button></div></label></form>{memberCode ? <p>Issue member captured: <strong>{memberCode}</strong>. Scan an exact copy barcode.</p> : null}<p role="status">{message}</p>{result ? <pre className="scanner-result">{JSON.stringify(result, null, 2)}</pre> : null}{ready && mode === "return" ? <div className="form-grid"><label>Return condition<select value={returnCondition} onChange={(e) => setReturnCondition(e.target.value)}><option value="GOOD">Good</option><option value="DAMAGED">Damaged</option><option value="LOST">Lost</option></select></label><label className="wide">Return notes<textarea value={returnNotes} maxLength={1000} onChange={(e) => setReturnNotes(e.target.value)} /></label></div> : null}{ready ? <div className="page-actions"><button onClick={confirm}>Confirm {mode === "issue" ? "Issue" : "Return"}</button><span className="muted">No action occurs on scan or preview.</span></div> : null}</section>;
}
