"use client";

import { useState } from "react";
import { readSpreadsheetRows } from "@/lib/client-spreadsheet";

type VendorOption = { id: string; vendorCode: string; name: string };

async function send(url: string, method: string, body: unknown) {
  const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Request failed"); return json;
}

export function LibraryTitleForm({ title, vendors = [] }: { title?: any; vendors?: VendorOption[] }) {
  const [message, setMessage] = useState(""); const [working, setWorking] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setWorking(true); setMessage(""); try { const data = Object.fromEntries(new FormData(form)); await send(title ? `/api/library/titles/${title.id}` : "/api/library/titles", title ? "PATCH" : "POST", data); setMessage(title ? "Bibliographic title updated." : "Bibliographic title created."); if (!title) form.reset(); setTimeout(() => location.assign(title ? `/library/catalog/${title.id}` : "/library/catalog"), 350); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save title"); } finally { setWorking(false); } }
  return <form className="card card-pad form-grid library-form" onSubmit={submit}>
    <label>Title code<input name="titleCode" required maxLength={50} defaultValue={title?.titleCode ?? ""} /></label>
    <label>Title<input name="title" required maxLength={240} defaultValue={title?.title ?? ""} /></label>
    <label className="wide">Subtitle<input name="subtitle" maxLength={240} defaultValue={title?.subtitle ?? ""} /></label>
    <label className="wide">Authors<input name="authors" required maxLength={500} defaultValue={title?.authors ?? ""} /></label>
    <label>ISBN<input name="isbn" maxLength={24} defaultValue={title?.isbn ?? ""} /></label>
    <label>Edition<input name="edition" maxLength={80} defaultValue={title?.edition ?? ""} /></label>
    <label>Publisher name<input name="publisherName" maxLength={180} defaultValue={title?.publisherName ?? ""} /></label>
    <label>Optional Publisher Vendor<select name="publisherVendorId" defaultValue={title?.publisherVendorId ?? ""}><option value="">No Vendor link</option>{vendors.map((v) => <option key={v.id} value={v.id}>{v.vendorCode} - {v.name}</option>)}</select></label>
    <label>Publication year<input name="publicationYear" inputMode="numeric" maxLength={4} defaultValue={title?.publicationYear ?? ""} /></label>
    <label>Language<input name="language" maxLength={80} defaultValue={title?.language ?? ""} /></label>
    <label>Subject<input name="subject" maxLength={120} defaultValue={title?.subject ?? ""} /></label>
    <label>Category<input name="category" maxLength={120} defaultValue={title?.category ?? ""} /></label>
    <label>Classification number<input name="classificationNumber" maxLength={80} defaultValue={title?.classificationNumber ?? ""} /></label>
    <label>Default shelf code<input name="defaultShelfCode" maxLength={80} defaultValue={title?.defaultShelfCode ?? ""} /></label>
    <label>Status<select name="status" defaultValue={title?.status ?? "ACTIVE"}><option>ACTIVE</option><option>INACTIVE</option></select></label>
    <label className="wide">Description<textarea name="description" maxLength={2000} defaultValue={title?.description ?? ""} /></label>
    <div className="wide page-actions"><button disabled={working}>{working ? "Saving..." : title ? "Save title" : "Create title"}</button><span className="muted" role="status">{message}</span></div>
  </form>;
}

export function LibraryCopyForm({ titles, vendors, expenses }: { titles: Array<{ id: string; titleCode: string; title: string; defaultShelfCode: string | null }>; vendors: VendorOption[]; expenses: Array<{ id: string; expenseNumber: string; vendorId: string | null }> }) {
  const [preview, setPreview] = useState<Record<string, string> | null>(null); const [message, setMessage] = useState(""); const [working, setWorking] = useState(false);
  const previewEntries = preview ? Object.entries(preview).filter(([, value]) => value).map(([key, value]) => {
    if (key === "titleId") { const item = titles.find((title) => title.id === value); return ["title", item ? `${item.titleCode} - ${item.title}` : "Selected title"]; }
    if (key === "vendorId") { const item = vendors.find((vendor) => vendor.id === value); return ["vendor reference", item ? `${item.vendorCode} - ${item.name}` : "Selected Vendor"]; }
    if (key === "expenseRecordId") { const item = expenses.find((expense) => expense.id === value); return ["expense reference", item?.expenseNumber ?? "Selected Expense"]; }
    return [key.replace(/([A-Z])/g, " $1"), value];
  }) : [];
  function review(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPreview(Object.fromEntries(new FormData(event.currentTarget)) as Record<string, string>); setMessage("Preview ready. No copy has been accessioned yet."); }
  async function confirm() { if (!preview) return; setWorking(true); try { const json = await send("/api/library/copies", "POST", preview); setMessage("Physical copy accessioned with an ACCESSIONED event."); setTimeout(() => location.assign(`/library/copies/${json.copy.id}`), 350); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to accession copy"); } finally { setWorking(false); } }
  return <><form className="card card-pad form-grid library-form" onSubmit={review}>
    <label className="wide">Existing bibliographic title<select name="titleId" required defaultValue=""><option value="" disabled>Select title</option>{titles.map((t) => <option key={t.id} value={t.id}>{t.titleCode} - {t.title}</option>)}</select></label>
    <label>Accession number<input name="accessionNumber" required maxLength={60} /></label><label>Optional barcode<input name="barcodeValue" maxLength={100} /></label>
    <label>Acquisition date<input name="acquisitionDate" type="date" /></label><label>Acquisition type<select name="acquisitionType" defaultValue="OTHER"><option>PURCHASED</option><option>DONATED</option><option>TRANSFERRED</option><option>OTHER</option></select></label>
    <label>Informational acquisition cost<input name="acquisitionCost" inputMode="decimal" placeholder="0.00" /></label><label>Condition<select name="condition" defaultValue="GOOD"><option>NEW</option><option>GOOD</option><option>FAIR</option><option>POOR</option><option>DAMAGED</option></select></label>
    <label>Status<select name="status" defaultValue="AVAILABLE"><option>AVAILABLE</option><option>UNDER_REPAIR</option><option>MISSING</option><option>WITHDRAWN</option></select></label><label>Shelf code<input name="shelfCode" maxLength={80} /></label>
    <label>Optional Vendor reference<select name="vendorId" defaultValue=""><option value="">No Vendor link</option>{vendors.map((v) => <option key={v.id} value={v.id}>{v.vendorCode} - {v.name}</option>)}</select></label>
    <label>Optional Expense reference<select name="expenseRecordId" defaultValue=""><option value="">No Expense link</option>{expenses.map((e) => <option key={e.id} value={e.id}>{e.expenseNumber}</option>)}</select></label>
    <label>Donor name<input name="donorName" maxLength={180} /></label><label>Invoice number snapshot<input name="invoiceNumberSnapshot" maxLength={120} /></label>
    <label className="wide">Notes<textarea name="notes" maxLength={2000} /></label><label className="wide">Withdrawal reason (required only for historical withdrawn copy)<textarea name="withdrawalReason" maxLength={1000} /></label>
    <div className="wide page-actions"><button type="submit">Preview before save</button><span className="muted" role="status">{message}</span></div>
  </form>{preview ? <section className="card card-pad"><h3>Review physical-copy accession</h3><dl className="detail-grid">{previewEntries.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="muted">Saving creates one physical copy and one append-only ACCESSIONED event. No accounting entry is created.</p><button disabled={working} onClick={confirm}>{working ? "Accessioning..." : "Confirm accession"}</button></section> : null}</>;
}

export function LibraryCopyActions({ copy }: { copy: any }) {
  const [message, setMessage] = useState(""); const [working, setWorking] = useState(false); const [withdrawReady, setWithdrawReady] = useState(false);
  async function act(url: string, body: unknown) { setWorking(true); try { await send(url, "POST", body); setMessage("Copy history updated. Refreshing..."); setTimeout(() => location.reload(), 300); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update copy"); } finally { setWorking(false); } }
  if (copy.status === "WITHDRAWN") return <section className="card card-pad"><h3>Copy controls</h3><p>This copy is withdrawn and preserved. No further state actions are allowed.</p></section>;
  return <section className="card card-pad library-actions"><h3>Audited copy actions</h3><p className="muted">Every condition, shelf, status, or withdrawal action appends an event. Withdrawal is blocked while an active loan exists.</p>
    <div className="form-grid"><label>Condition<select id="library-condition" defaultValue={copy.condition}>{["NEW", "GOOD", "FAIR", "POOR", "DAMAGED"].map((v) => <option key={v}>{v}</option>)}</select></label><label>Reason<input id="library-condition-reason" maxLength={1000} /></label><button disabled={working} onClick={() => act(`/api/library/copies/${copy.id}/condition`, { condition: (document.getElementById("library-condition") as HTMLSelectElement).value, reason: (document.getElementById("library-condition-reason") as HTMLInputElement).value })}>Record condition</button>
    <label>Shelf code<input id="library-shelf" defaultValue={copy.shelfCode ?? ""} maxLength={80} /></label><label>Reason<input id="library-shelf-reason" maxLength={1000} /></label><button disabled={working} onClick={() => act(`/api/library/copies/${copy.id}/shelf`, { shelfCode: (document.getElementById("library-shelf") as HTMLInputElement).value, reason: (document.getElementById("library-shelf-reason") as HTMLInputElement).value })}>Record shelf move</button></div>
    <div className="page-actions"><button disabled={working} onClick={() => act(`/api/library/copies/${copy.id}/status`, { action: "missing", reason: "Recorded from copy detail" })}>Mark missing</button><button disabled={working} onClick={() => act(`/api/library/copies/${copy.id}/status`, { action: "repair", reason: "Sent for repair from copy detail" })}>Send for repair</button><button disabled={working} onClick={() => act(`/api/library/copies/${copy.id}/status`, { action: "available", reason: "Restored after repair or missing-state review" })}>Restore available status</button></div>
    <div className="danger-zone"><label>Withdrawal reason<input id="library-withdraw-reason" maxLength={1000} onChange={() => setWithdrawReady(false)} /></label>{withdrawReady ? <><p><strong>Final confirmation:</strong> this copy will be withdrawn permanently, while its accession and complete history remain preserved.</p><button className="danger" disabled={working} onClick={() => act(`/api/library/copies/${copy.id}/withdraw`, { reason: (document.getElementById("library-withdraw-reason") as HTMLInputElement).value })}>Confirm permanent withdrawal</button><button className="secondary" disabled={working} onClick={() => setWithdrawReady(false)}>Cancel withdrawal</button></> : <button className="danger" disabled={working} onClick={() => { const reason = (document.getElementById("library-withdraw-reason") as HTMLInputElement).value.trim(); if (!reason) { setMessage("Withdrawal reason is required."); return; } setMessage(""); setWithdrawReady(true); }}>Review withdrawal</button>}</div><p role="status">{message}</p>
  </section>;
}

export function LibraryCopyCorrectionForm({ copy }: { copy: any }) {
  const [message, setMessage] = useState(""); const [working, setWorking] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setWorking(true); try { await send(`/api/library/copies/${copy.id}`, "PATCH", Object.fromEntries(new FormData(event.currentTarget))); setMessage("Correction saved with an append-only CORRECTION event."); setTimeout(() => location.reload(), 350); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to correct copy details"); } finally { setWorking(false); } }
  return <form className="card card-pad form-grid" onSubmit={submit}><h3 className="wide">Correct safe copy details</h3><label>Accession number<input value={copy.accessionNumber} disabled aria-label="Immutable accession number" /></label><label>Barcode<input value={copy.barcodeValue ?? "Not assigned"} disabled aria-label="Barcode managed in Barcode and Scanner" /></label><p className="wide muted">Barcode changes require the dedicated Barcode &amp; Scanner correction workflow and its separate permission.</p><label>Donor name<input name="donorName" defaultValue={copy.donorName ?? ""} /></label><label>Invoice snapshot<input name="invoiceNumberSnapshot" defaultValue={copy.invoiceNumberSnapshot ?? ""} /></label><label className="wide">Notes<textarea name="notes" defaultValue={copy.notes ?? ""} /></label><label className="wide">Correction reason<textarea name="correctionReason" required maxLength={1000} /></label><div className="wide page-actions"><button disabled={working}>{working ? "Saving..." : "Save audited correction"}</button><span role="status">{message}</span></div></form>;
}

export function LibraryImportPanel() {
  const [kind, setKind] = useState<"titles" | "copies">("titles"); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [fileName, setFileName] = useState(""); const [preview, setPreview] = useState<any>(null); const [confirmed, setConfirmed] = useState(false); const [message, setMessage] = useState(""); const [working, setWorking] = useState(false);
  async function fileChanged(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; setPreview(null); setConfirmed(false); if (!file) return; setWorking(true); try { const parsed = await readSpreadsheetRows<Record<string, unknown>>(file); if (!parsed.length) throw new Error("The selected file has no data rows"); setRows(parsed); setFileName(file.name); const json = await send(`/api/library/import/${kind}`, "POST", { action: "preview", rows: parsed, fileName: file.name }); setPreview(json.preview); setMessage(json.message); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to preview file"); } finally { setWorking(false); } }
  async function apply() { if (!confirmed) return; setWorking(true); try { const json = await send(`/api/library/import/${kind}`, "POST", { action: "confirm", confirmed: true, rows, fileName }); setMessage(json.message); setPreview(null); setConfirmed(false); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to confirm import"); } finally { setWorking(false); } }
  return <section className="card card-pad library-import"><div className="section-title"><div><h3>Preview-first library import</h3><p>No fuzzy matching and no silent overwrite.</p></div><div className="page-actions"><a className="button secondary" href={`/api/library/import/template/${kind}`}>Download {kind} template</a></div></div><div className="form-grid"><label>Import type<select value={kind} onChange={(e) => { setKind(e.target.value as typeof kind); setPreview(null); setRows([]); setConfirmed(false); }}><option value="titles">Bibliographic titles</option><option value="copies">Physical copies / accessions</option></select></label><label>Select CSV or spreadsheet<input type="file" accept=".csv,.xlsx,.xls" onChange={fileChanged} /></label></div><p role="status">{working ? "Working..." : message}</p>{preview ? <><div className="stats"><div className="stat"><span>Total</span><strong>{preview.counts.total}</strong></div><div className="stat"><span>Ready</span><strong>{preview.counts.ready}</strong></div><div className="stat"><span>Skipped</span><strong>{preview.counts.skipped}</strong></div><div className="stat"><span>Errors</span><strong>{preview.counts.errors}</strong></div></div><div className="table-wrap"><table><thead><tr><th>CSV Row</th><th>Action</th><th>Key</th><th>Errors</th><th>Warnings</th></tr></thead><tbody>{preview.rows.map((row: any) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.action}</td><td>{row.normalized.titleCode ?? row.normalized.accessionNumber ?? "—"}</td><td>{row.errors.join("; ") || "—"}</td><td>{row.warnings.join("; ") || "—"}</td></tr>)}</tbody></table></div><label className="review-checkbox"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /> I reviewed the row-level preview and want to apply ready rows.</label><button disabled={!confirmed || working || preview.counts.ready === 0} onClick={apply}>Confirm import</button></> : null}</section>;
}
