"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Item = { id: string; itemCode: string; name: string; studentLinkPolicy: string; rates: Array<{ id: string; academicYear: string; amount: string; effectiveFrom: string | null; effectiveTo: string | null }> };
type Student = { id: string; admissionNo: string; studentName: string; className: string; section: string | null };
type Line = { itemId: string; quantity: number; discountAmount: string; notes: string };
export function MiscIncomeForm({ items, students, academicYear, today }: { items: Item[]; students: Student[]; academicYear: string; today: string }) {
  const router = useRouter(); const [lines, setLines] = useState<Line[]>([{ itemId: items[0]?.id ?? "", quantity: 1, discountAmount: "0", notes: "" }]); const [studentId, setStudentId] = useState(""); const [payerName, setPayerName] = useState(""); const [receiptDate, setReceiptDate] = useState(today); const [paymentMethod, setPaymentMethod] = useState("CASH"); const [receivedAccount, setReceivedAccount] = useState("CASH_COUNTER"); const [transactionReference, setTransactionReference] = useState(""); const [chequeNumber, setChequeNumber] = useState(""); const [chequeDate, setChequeDate] = useState(""); const [remarks, setRemarks] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const item = (id: string) => items.find((row) => row.id === id); const rate = (line: Line) => item(line.itemId)?.rates.find((row) => row.academicYear === academicYear && (!row.effectiveFrom || row.effectiveFrom.slice(0, 10) <= receiptDate) && (!row.effectiveTo || row.effectiveTo.slice(0, 10) >= receiptDate));
  const totals = useMemo(() => lines.reduce((result, line) => { const gross = Number(rate(line)?.amount ?? 0) * Number(line.quantity || 0); const discount = Number(line.discountAmount || 0); return { gross: result.gross + gross, discount: result.discount + discount, net: result.net + gross - discount }; }, { gross: 0, discount: 0, net: 0 }), [lines, receiptDate]);
  const requiresStudent = lines.some((line) => item(line.itemId)?.studentLinkPolicy === "REQUIRED");
  const update = (index: number, patch: Partial<Line>) => setLines((rows) => rows.map((line, i) => i === index ? { ...line, ...patch } : line));
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/misc-income", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ receiptDate, academicYear, studentId: studentId || null, payerName, paymentMethod, receivedAccount, transactionReference, chequeNumber, chequeDate, remarks, lines }) }); const body = await response.json(); setSaving(false); if (!response.ok) return setError(body.error ?? "Unable to issue receipt"); router.push(`/misc-income/${body.receipt.id}`); router.refresh(); }
  return <form className="card form-grid misc-income-form" onSubmit={submit}>
    {error ? <p className="form-error full-span">{error}</p> : null}
    <label>Receipt date<input type="date" value={receiptDate} onChange={(event) => setReceiptDate(event.target.value)} required /></label><label>Academic year<input value={academicYear} readOnly /></label>
    <label className="full-span">Student {requiresStudent ? <strong>(required by selected item)</strong> : <span className="muted-text">(optional unless item policy requires)</span>}<select value={studentId} onChange={(event) => setStudentId(event.target.value)} required={requiresStudent}><option value="">No student linked</option>{students.map((student) => <option key={student.id} value={student.id}>{student.admissionNo} — {student.studentName} — {student.className}{student.section ? ` ${student.section}` : ""}</option>)}</select></label><label className="full-span">Payer name<input value={payerName} onChange={(event) => setPayerName(event.target.value)} maxLength={120} /></label>
    <fieldset className="full-span receipt-lines"><legend>Receipt items</legend>{lines.map((line, index) => { const selectedRate = rate(line); const gross = Number(selectedRate?.amount ?? 0) * line.quantity; return <div className="receipt-line" key={index}><label>Item<select value={line.itemId} onChange={(event) => update(index, { itemId: event.target.value })} required>{items.map((row) => <option key={row.id} value={row.id}>{row.itemCode} — {row.name}</option>)}</select></label><label>Quantity<input type="number" min="1" step="1" value={line.quantity} onChange={(event) => update(index, { quantity: Number(event.target.value) })} required /></label><label>Rate<input value={selectedRate ? Number(selectedRate.amount).toFixed(2) : "No active rate"} readOnly /></label><label>Discount<input type="number" min="0" step="0.01" max={gross} value={line.discountAmount} onChange={(event) => update(index, { discountAmount: event.target.value })} required /></label><label>Line total<input value={(gross - Number(line.discountAmount || 0)).toFixed(2)} readOnly /></label><label>Notes<input value={line.notes} onChange={(event) => update(index, { notes: event.target.value })} /></label>{lines.length > 1 ? <button type="button" className="button danger" onClick={() => setLines((rows) => rows.filter((_, i) => i !== index))}>Remove</button> : null}</div>; })}<button type="button" className="button secondary" onClick={() => setLines((rows) => [...rows, { itemId: items[0]?.id ?? "", quantity: 1, discountAmount: "0", notes: "" }])}>Add another item</button></fieldset>
    <label>Payment method<select value={paymentMethod} onChange={(event) => { setPaymentMethod(event.target.value); setReceivedAccount(event.target.value === "CASH" ? "CASH_COUNTER" : receivedAccount === "CASH_COUNTER" ? "NPS_CURRENT_ACCOUNT" : receivedAccount); }}>{["CASH", "UPI", "BANK_TRANSFER", "NEFT", "RTGS", "IMPS", "CHEQUE", "OTHER"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Received account<select value={receivedAccount} onChange={(event) => setReceivedAccount(event.target.value)}>{["CASH_COUNTER", "DIRECTOR_GPAY", "NPS_CURRENT_ACCOUNT", "OTHER"].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>
    {paymentMethod !== "CASH" && paymentMethod !== "CHEQUE" ? <label className="full-span">Transaction reference<input value={transactionReference} onChange={(event) => setTransactionReference(event.target.value)} required /></label> : null}{paymentMethod === "CHEQUE" ? <><label>Cheque number<input value={chequeNumber} onChange={(event) => setChequeNumber(event.target.value)} required /></label><label>Cheque date<input type="date" value={chequeDate} onChange={(event) => setChequeDate(event.target.value)} required /></label></> : null}
    <label className="full-span">Remarks<textarea value={remarks} onChange={(event) => setRemarks(event.target.value)} /></label><div className="receipt-total full-span"><span>Gross <strong>₹{totals.gross.toFixed(2)}</strong></span><span>Discount <strong>₹{totals.discount.toFixed(2)}</strong></span><span>Net amount <strong>₹{totals.net.toFixed(2)}</strong></span></div><button type="submit" disabled={saving || !items.length}>{saving ? "Issuing receipt…" : "Save and issue receipt"}</button>
  </form>;
}
