"use client";
import { FormEvent, useMemo, useState } from "react";

type Bundle = "STUDENT_GUARDIAN" | "STAFF" | "COMBINED";
type Batch = { batchReference: string; bundleType: Bundle; status: string; version: number; workbookHash: string; templateVersion: string; schemaVersion: string; planHash?: string | null; planVersion?: number; planExpiresAt?: string | null; approvedAt?: string | null; executedAt?: string | null; rolledBackAt?: string | null; createdAt: string; plan?: any; result?: any; issues?: any[]; resolutions?: Record<string, any> };
type Props = { initialBatches: Batch[]; role: string; permissions: { upload: boolean; validate: boolean; resolve: boolean; approve: boolean; execute: boolean; audit: boolean; rollback: boolean } };
const steps = ["Select bundle", "Download template", "Upload workbook", "Validate", "Review issues", "Download error workbook", "Resolve conflicts", "Review dry run", "Approve", "Execute", "Reconcile", "Safe rollback", "Batch history"];

export function OnboardingCentre({ initialBatches, role, permissions }: Props) {
  const [bundle, setBundle] = useState<Bundle>("STUDENT_GUARDIAN"), [batches, setBatches] = useState(initialBatches), [selected, setSelected] = useState<Batch | null>(initialBatches[0] ?? null), [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState(""), [resolutions, setResolutions] = useState<Record<string, { decision: string; reason: string }>>({}), [dialog, setDialog] = useState<"approve"|"execute"|"rollback"|null>(null), [reason, setReason] = useState(""), [password, setPassword] = useState(""), [rollbackPreview, setRollbackPreview] = useState<any>(null);
  const plan = selected?.plan ?? selected?.result ?? null, issues = (selected?.issues ?? plan?.issues ?? []) as any[];
  const progress = useMemo(() => statusProgress(selected?.status), [selected?.status]);
  function replaceBatch(batch: Batch) { setSelected(batch); setBatches((current) => [batch, ...current.filter((r) => r.batchReference !== batch.batchReference)]); }
  async function request(url: string, init?: RequestInit) { setBusy(true); setError(""); setMessage(""); try { const response = await fetch(url, { credentials: "same-origin", ...init }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "The action failed safely."); return json; } catch (e) { setError(e instanceof Error ? e.message : "The action failed safely."); throw e; } finally { setBusy(false); } }
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) return; const data = new FormData(); data.set("bundle", bundle); data.set("workbook", file); try { const json = await request("/api/onboarding/batches", { method: "POST", body: data }); replaceBatch(json.batch); setMessage(json.duplicateUpload ? "This exact workbook already has a governed batch." : "Workbook stored privately. No business data changed."); } catch {} }
  async function validate() { if (!selected) return; try { const json = await request(`/api/onboarding/batches/${selected.batchReference}/validate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ resolutions }) }); replaceBatch(json.batch); setMessage("Validation completed. Review every issue and the dry-run totals."); } catch {} }
  async function critical(action: "approve"|"execute"|"rollback", executeRollback = false) { if (!selected) return; const payload: any = { reason, reauthPassword: password, planHash: selected.planHash, workbookHash: selected.workbookHash }; if (action === "execute") payload.idempotencyKey = globalThis.crypto?.randomUUID?.().replaceAll("-", "") ?? `${Date.now()}IMPORT1AKEY`; if (action === "rollback") payload.execute = executeRollback; try { const json = await request(`/api/onboarding/batches/${selected.batchReference}/${action}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (action === "rollback" && !executeRollback) { setRollbackPreview(json.rollback); setMessage(json.rollback.eligible ? "Rollback preview is eligible. Review counts before execution." : "Automatic rollback is blocked; use manual reconciliation."); } else { replaceBatch(json.batch ?? { ...selected, status: "ROLLED_BACK", rolledBackAt: new Date().toISOString() }); setDialog(null); setReason(""); setPassword(""); setMessage(action === "approve" ? "Batch approved. Execution remains a separate action." : action === "execute" ? "Batch executed exactly once. Reconciliation is available." : "Batch-owned creations were rolled back; audit was preserved."); } } catch {} }
  function setDecision(rowKey: string, field: "decision"|"reason", value: string) { setResolutions((current) => ({ ...current, [rowKey]: { decision: current[rowKey]?.decision ?? "", reason: current[rowKey]?.reason ?? "", [field]: value } })); }
  return <div className="onboarding-stack">
    <section className="card card-pad" aria-labelledby="onboarding-progress"><div className="section-title"><div><h2 id="onboarding-progress">Governed workflow</h2><p>{progress}% complete for the selected batch. Each gate is server-authorised.</p></div><span className="badge">{selected?.status?.replaceAll("_", " ") ?? "NO BATCH"}</span></div><div className="onboarding-progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><span style={{ width: `${progress}%` }} /></div><ol className="onboarding-steps">{steps.map((step, index) => <li key={step} className={index < Math.ceil(progress / 8) ? "done" : ""}>{index + 1}. {step}</li>)}</ol></section>
    {error ? <div className="notice danger" role="alert">{error}</div> : null}{message ? <div className="notice" role="status" aria-live="polite">{message}</div> : null}
    <div className="grid onboarding-grid">
      <section className="card card-pad"><h2>1-3. Template and private upload</h2><label>Import bundle<select value={bundle} onChange={(e) => setBundle(e.target.value as Bundle)}><option value="STUDENT_GUARDIAN">Student and Guardian</option><option value="STAFF">Staff</option><option value="COMBINED">Combined School</option></select></label><a className="button secondary onboarding-action" href={`/api/onboarding/templates?bundle=${bundle}`}>Download controlled XLSX template</a>{permissions.upload ? <form onSubmit={upload} className="form-grid"><label className="wide">Completed XLSX workbook<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><button disabled={busy || !file}>Upload privately</button></form> : <p>Your role can download templates but cannot upload workbooks.</p>}<p className="muted-text">Only .xlsx is accepted. Macros, formulas, external links, objects, hidden sheets, malformed ZIPs and oversized workbooks are refused.</p></section>
      <section className="card card-pad"><h2>Batch history</h2><div className="onboarding-history" role="list">{batches.map((batch) => <button type="button" key={batch.batchReference} className={selected?.batchReference === batch.batchReference ? "secondary active" : "secondary"} onClick={() => { setSelected(batch); setResolutions(batch.resolutions ?? batch.plan?.resolutions ?? {}); }}><strong>{batch.bundleType.replaceAll("_", " ")}</strong><span>{batch.status.replaceAll("_", " ")} · v{batch.version}</span><small>{batch.batchReference}</small></button>)}{!batches.length ? <p>No governed onboarding batches yet.</p> : null}</div></section>
    </div>
    {selected ? <><section className="card card-pad"><div className="section-title"><div><h2>4-8. Validate and review dry run</h2><p>Batch {selected.batchReference} · workbook SHA-256 {selected.workbookHash}</p></div>{permissions.validate ? <button disabled={busy} onClick={validate}>Validate current workbook</button> : null}</div>{plan ? <div className="stats onboarding-stats">{stat("Rows", totalRows(plan))}{stat("Creates", plan.createCount ?? resultTotal(selected.result))}{stat("Links", plan.linkCount ?? selected.result?.links ?? 0)}{stat("Enrollments", plan.enrollmentCount ?? selected.result?.enrollments ?? 0)}{stat("Warnings", plan.warningCount ?? 0)}{stat("Blocking", plan.blockingErrorCount ?? 0)}{stat("Duplicates", plan.duplicateCount ?? 0)}{stat("Account proposals", plan.accountProposalCount ?? selected.result?.accountProposals ?? 0)}</div> : <p>Validate the batch to create a current dry-run plan.</p>}{selected.planExpiresAt ? <p><strong>Plan expires:</strong> {formatOnboardingTimestamp(selected.planExpiresAt)}</p> : null}{issues.length ? <><div className="page-actions"><a className="button secondary" href={`/api/onboarding/batches/${selected.batchReference}/error-workbook`}>Download private error workbook</a></div><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Source</th><th>Issue</th><th>Correction</th>{permissions.resolve ? <th>Decision</th> : null}</tr></thead><tbody>{issues.map((issue, index) => <tr key={`${issue.code}-${issue.row}-${index}`}><td><span className={`badge ${issue.severity === "BLOCKING_ERROR" ? "danger" : "warn"}`}>{issue.severity.replaceAll("_", " ")}</span></td><td>{issue.sheet} row {issue.row}<br/><small>{issue.column}</small></td><td><strong>{issue.code}</strong><br/>{issue.message}</td><td>{issue.suggestion ?? "Correct the workbook and validate again."}</td>{permissions.resolve ? <td>{issue.severity === "REQUIRES_USER_DECISION" && issue.rowKey ? <div className="decision-cell"><select aria-label={`Decision for ${issue.rowKey}`} value={resolutions[issue.rowKey]?.decision ?? ""} onChange={(e) => setDecision(issue.rowKey, "decision", e.target.value)}><option value="">Select</option><option>CREATE_NEW</option><option>LINK_EXISTING</option><option>SKIP</option><option>REJECT_ROW</option></select><input aria-label={`Reason for ${issue.rowKey}`} placeholder="Reason required" value={resolutions[issue.rowKey]?.reason ?? ""} onChange={(e) => setDecision(issue.rowKey, "reason", e.target.value)} /></div> : "—"}</td> : null}</tr>)}</tbody></table></div></> : plan ? <div className="notice">No validation issues are recorded for this plan.</div> : null}</section>
    <section className="card card-pad"><h2>9-12. Approval, execution, reconciliation and rollback</h2><div className="page-actions">{permissions.approve && selected.status === "APPROVAL_REQUIRED" && (role !== "PRINCIPAL" || selected.bundleType === "STUDENT_GUARDIAN") ? <button onClick={() => setDialog("approve")}>Approve current plan</button> : null}{permissions.execute && selected.status === "APPROVED" ? <button onClick={() => setDialog("execute")}>Execute all or nothing</button> : null}{permissions.rollback && selected.status === "COMPLETED" ? <button className="secondary" onClick={() => { setRollbackPreview(null); setDialog("rollback"); }}>Preview safe rollback</button> : null}</div>{role === "PRINCIPAL" && selected.bundleType !== "STUDENT_GUARDIAN" ? <p className="muted-text">Principal approval is scoped to Student and Guardian onboarding. Staff and combined bundles require Director or Super Admin approval.</p> : null}{selected.result ? <div className="notice"><strong>Reconciliation</strong><pre className="onboarding-json">{JSON.stringify(selected.result, null, 2)}</pre></div> : null}<p>No Parent or Staff account is activated here. Account flags remain pending IAM proposals governed by AUTH-2B and IAM-1A.</p></section></> : null}
    {dialog ? <div className="confirmation-overlay"><section className="card confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="onboarding-critical-title"><h2 id="onboarding-critical-title">{dialog === "approve" ? "Approve Dry-run Plan" : dialog === "execute" ? "Execute Approved Batch" : "Safe Rollback"}</h2><p>{dialog === "execute" ? "This creates all approved records in one transaction. A failure creates none." : dialog === "rollback" ? "Rollback is allowed only for unchanged batch-owned creations with no dependent activity." : "Approval does not execute the workbook."}</p><label>Reason<textarea value={reason} onChange={(e) => setReason(e.target.value)} minLength={12} maxLength={500} rows={3} /></label><label>Re-authentication password<input type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{rollbackPreview ? <div className={`notice ${rollbackPreview.eligible ? "" : "danger"}`}><strong>{rollbackPreview.eligible ? "Eligible" : "Blocked"}</strong><pre className="onboarding-json">{JSON.stringify(rollbackPreview, null, 2)}</pre></div> : null}<div className="page-actions"><button type="button" className="secondary" onClick={() => setDialog(null)}>Go back</button>{dialog === "rollback" && !rollbackPreview ? <button disabled={busy || reason.length < 12 || !password} onClick={() => critical("rollback", false)}>Run rollback preview</button> : dialog === "rollback" ? <button disabled={busy || !rollbackPreview?.eligible} onClick={() => critical("rollback", true)}>Execute exact rollback</button> : <button disabled={busy || reason.length < 12 || !password} onClick={() => critical(dialog)}>{dialog === "approve" ? "Approve" : "Execute exactly once"}</button>}</div></section></div> : null}
  </div>;
}
function stat(label: string, value: number) { return <div className="card stat" key={label}><span>{label}</span><strong>{Number(value ?? 0).toLocaleString("en-IN")}</strong></div>; }
function totalRows(plan: any) { return Object.values(plan.sheetRows ?? {}).reduce((sum: number, value) => sum + Number(value ?? 0), 0); }
function resultTotal(result: any) { return ["students", "guardians", "staff"].reduce((sum, key) => sum + Number(result?.[key] ?? 0), 0); }
function formatOnboardingTimestamp(value: string) {
  return new Intl.DateTimeFormat("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Kolkata",
  }).format(new Date(value));
}
function statusProgress(status?: string) { return ({ UPLOADED: 25, VALIDATED: 45, APPROVAL_REQUIRED: 60, APPROVED: 75, EXECUTING: 82, COMPLETED: 92, ROLLED_BACK: 92 } as Record<string, number>)[status ?? ""] ?? 0; }
