"use client";

import { FormEvent, useEffect, useState } from "react";

type Permissions = Record<string, boolean>;

export function PayslipRequestManagement({ permissions }: { permissions: Permissions }) {
  const [data, setData] = useState<any>(null), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [availability, setAvailability] = useState({ staffKey: "", month: "", status: "AVAILABLE", reason: "" });
  async function load() { setError(""); try { const response = await fetch("/api/payslip-requests", { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error || "The request queue could not be loaded."); setData(body); } catch (caught) { setError(caught instanceof Error ? caught.message : "The request queue could not be loaded."); } }
  useEffect(() => { void load(); }, []);
  async function saveAvailability(event: FormEvent) { event.preventDefault(); try { const response = await fetch("/api/payslip-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(availability) }), body = await response.json(); if (!response.ok) throw new Error(body.error || "Month availability was refused."); setAvailability({ staffKey: "", month: "", status: "AVAILABLE", reason: "" }); setMessage("Historical month availability recorded without salary data."); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Month availability was refused."); } }
  if (error && !data) return <div className="form-error" role="alert">{error}</div>; if (!data) return <p>Loading the governed request queue…</p>;
  return <div className="payslip-request-workspace"><div className="callout"><strong>External preparation boundary.</strong> This queue does not calculate salary or create payroll, Cash Book, bank or statutory entries.</div><div role="status" aria-live="polite">{message}</div>{error ? <div className="form-error" role="alert">{error}</div> : null}
    {permissions.MANAGE_PAYSLIP_MONTH_AVAILABILITY ? <form className="card form-stack" onSubmit={saveAvailability}><h2>Historical record availability</h2><div className="form-grid"><label>Staff<select value={availability.staffKey} onChange={(event) => setAvailability({ ...availability, staffKey: event.target.value })} required><option value="">Choose Staff</option>{data.staff.map((staff: any) => <option key={staff.key} value={staff.key}>{staff.name} · {staff.designation}</option>)}</select></label><label>Salary month<input type="month" value={availability.month} onChange={(event) => setAvailability({ ...availability, month: event.target.value })} required/></label><label>Availability<select value={availability.status} onChange={(event) => setAvailability({ ...availability, status: event.target.value })}><option value="AVAILABLE">Available</option><option value="UNAVAILABLE">Unavailable</option><option value="UNKNOWN">Unknown</option><option value="RECORD_REVIEW_REQUIRED">Record review required</option></select></label></div><label>Authorisation reason<textarea value={availability.reason} onChange={(event) => setAvailability({ ...availability, reason: event.target.value })} minLength={3} maxLength={500} required/></label><button className="button primary">Record availability</button></form> : null}
    <section><h2>Request queue</h2><div className="payslip-request-grid">{data.requests.map((request: any) => <ManagementRequestCard key={request.key} request={request} preparers={data.preparers} permissions={permissions} reload={load} report={(value: string) => setMessage(value)} fail={(value: string) => setError(value)}/>)}</div></section>
  </div>;
}

function ManagementRequestCard({ request, preparers, permissions, reload, report, fail }: any) {
  const [preparerKey, setPreparerKey] = useState(""), [reason, setReason] = useState(""), [file, setFile] = useState<File | null>(null), [months, setMonths] = useState<string[]>(request.months.filter((item: any) => item.issueStatus === "PENDING").map((item: any) => item.month));
  const [reauth, setReauth] = useState(""), [replacementTarget, setReplacementTarget] = useState(""), [replacement, setReplacement] = useState(false), [independentReview, setIndependentReview] = useState(false);
  function toggleMonth(month: string) { setMonths((current) => current.includes(month) ? current.filter((value) => value !== month) : [...current, month]); }
  async function workflow(action: string) { try { const response = await fetch(`/api/payslip-requests/${request.key}/workflow`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, expectedVersion: request.version, preparerKey, reason }) }), body = await response.json(); if (!response.ok) throw new Error(body.error || "The workflow action was refused."); report(`Request moved to ${body.statusLabel}.`); await reload(); } catch (caught) { fail(caught instanceof Error ? caught.message : "The workflow action was refused."); } }
  async function upload(event: FormEvent) { event.preventDefault(); if (!file) return; try { const form = new FormData(); form.set("file", file); form.set("months", JSON.stringify(months)); form.set("expectedVersion", String(request.version)); form.set("replacement", String(replacement)); if (replacementTarget) form.set("supersedesDocumentKey", replacementTarget); if (reason) form.set("replacementReason", reason); const response = await fetch(`/api/payslip-requests/${request.key}/documents`, { method: "POST", body: form }), body = await response.json(); if (!response.ok) throw new Error(body.error || "The protected upload was refused."); setFile(null); report("PDF validated, protected and stored for final review."); await reload(); } catch (caught) { fail(caught instanceof Error ? caught.message : "The protected upload was refused."); } }
  async function documentWorkflow(document: any, action: string) { try { const response = await fetch(`/api/payslip-requests/documents/${document.key}/workflow`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, requestKey: request.key, documentKey: document.key, expectedVersion: request.version, requestVersion: request.version, reauthPassword: reauth, confirmIndependentReview: independentReview }) }), body = await response.json(); if (!response.ok) throw new Error(body.error || "The protected document action was refused."); setReauth(""); setIndependentReview(false); report(action === "ISSUE" ? "Protected document issued through the private Staff portal." : "Protected document approved for final issue."); await reload(); } catch (caught) { fail(caught instanceof Error ? caught.message : "The protected document action was refused."); } }
  return <article className="card"><div className="card-heading-row"><div><h3>{request.number}</h3><p>{request.staff.name} · {request.staff.designation}</p></div><span className={request.overdue ? "status-badge danger" : "status-badge"}>{request.overdue ? "Overdue" : request.statusLabel}</span></div><p>{request.purpose}{request.requiredByDate ? ` · required by ${request.requiredByDate}` : ""}</p><p>{request.months.map((item: any) => `${item.label} (${item.issueStatus.toLowerCase()})`).join(", ")}</p>
    {permissions.PREPARE_PAYSLIP_REQUEST && ["SUBMITTED", "UNDER_REVIEW"].includes(request.status) ? <div className="action-stack"><div className="action-row"><button className="button" onClick={() => void workflow("REVIEW")}>Start review</button><button className="button" onClick={() => void workflow("PREPARE")}>Prepare myself</button></div><label>Assign preparer<select value={preparerKey} onChange={(event) => setPreparerKey(event.target.value)}><option value="">Choose authorised user</option>{preparers.map((item: any) => <option key={item.key} value={item.key}>{item.name} · {item.role}</option>)}</select></label><button className="button" disabled={!preparerKey} onClick={() => void workflow("ASSIGN")}>Assign preparation</button></div> : null}
    {(permissions.UPLOAD_PAYSLIP_DOCUMENT || permissions.REPLACE_PAYSLIP_DOCUMENT) && ["PREPARATION_IN_PROGRESS", "READY_TO_ISSUE", "PARTIALLY_ISSUED", "ISSUED"].includes(request.status) ? <form className="form-stack protected-upload" onSubmit={upload}><h4>{replacement ? "Upload corrected replacement" : "Upload externally prepared PDF"}</h4><fieldset><legend>Covered requested months</legend><div className="month-choice-grid">{request.months.map((item: any) => <label className="choice-control" key={item.month}><input type="checkbox" checked={months.includes(item.month)} onChange={() => toggleMonth(item.month)}/><span>{item.label}</span></label>)}</div></fieldset><label>PDF only<input type="file" accept="application/pdf,.pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} required/></label>{permissions.REPLACE_PAYSLIP_DOCUMENT && request.documents.some((item: any) => item.status === "ACTIVE") ? <label className="choice-control"><input type="checkbox" checked={replacement} onChange={(event) => setReplacement(event.target.checked)}/><span>This is a correction/replacement</span></label> : null}{replacement ? <><label>Active version to replace<select value={replacementTarget} onChange={(event) => setReplacementTarget(event.target.value)} required><option value="">Choose active version</option>{request.documents.filter((item: any) => item.status === "ACTIVE").map((item: any) => <option key={item.key} value={item.key}>Version {item.version} · {item.months.join(", ")}</option>)}</select></label><label>Replacement reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} minLength={3} maxLength={500} required/></label></> : null}<button className="button primary" disabled={!file || !months.length}>Validate and protect PDF</button></form> : null}
    {permissions.ISSUE_PAYSLIP_DOCUMENT && request.documents.some((item: any) => item.status === "READY_TO_ISSUE") ? <div className="form-stack"><label>Current account password for approval/issue<input type="password" autoComplete="current-password" value={reauth} onChange={(event) => setReauth(event.target.value)}/></label><label className="choice-control"><input type="checkbox" checked={independentReview} onChange={(event) => setIndependentReview(event.target.checked)}/><span>I completed the final visible-content and month review</span></label>{request.documents.filter((item: any) => item.status === "READY_TO_ISSUE").map((document: any) => <div className="protected-document" key={document.key}><strong>Protected version {document.version} · {document.months.join(", ")}</strong><div className="action-row"><a className="button" href={`/api/payslip-requests/documents/${document.key}/source`} target="_blank" rel="noreferrer">Preview management source</a>{!document.approved ? <button className="button" disabled={!reauth || !independentReview} onClick={() => void documentWorkflow(document, "APPROVE")}>Approve</button> : <button className="button primary" disabled={!reauth} onClick={() => void documentWorkflow(document, "ISSUE")}>Final issue</button>}</div></div>)}</div> : null}
    {permissions.ISSUE_PAYSLIP_DOCUMENT && ["SUBMITTED", "UNDER_REVIEW", "PREPARATION_IN_PROGRESS", "READY_TO_ISSUE"].includes(request.status) ? <div className="form-stack"><label>Rejection reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} minLength={3} maxLength={500}/></label><button className="button danger" disabled={reason.length < 3} onClick={() => void workflow("REJECT")}>Reject request</button></div> : null}
    {permissions.VIEW_PAYSLIP_REQUEST_AUDIT && request.timeline ? <details><summary>Request and access audit</summary><ol className="timeline-list">{request.timeline.map((item: any, index: number) => <li key={`${item.at}-${index}`}><strong>{item.status || item.type}</strong><span>{new Date(item.at).toLocaleString("en-IN")}</span>{item.reason ? <p>{item.reason}</p> : null}</li>)}</ol></details> : null}
  </article>;
}
