"use client";

import { useState } from "react";

type Liability = { id: string; studentId: string; sourceYear: string; operatingYear: string; sourceEnrollmentId: string; status: string; version: number; openingAmount: string; existingCredits: string; provenance: string };
export function PriorYearCasePreparation({ liabilities, submit, busy }: { liabilities: Liability[]; submit: (input: Record<string, unknown>) => Promise<void>; busy: boolean }) {
  const [mode, setMode] = useState("PREPARE_LIABILITY");
  const [selected, setSelected] = useState("");
  const liability = liabilities.find((item) => item.id === selected);
  async function prepare(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const text = (key: string) => String(form.get(key) ?? "").trim();
    const input: Record<string, unknown> = { action: mode, reason: text("reason"), liabilityId: selected };
    if (mode === "PREPARE_LIABILITY") Object.assign(input, { studentId: text("studentId"), operatingYear: text("operatingYear"), sourceYear: text("sourceYear"), sourceEnrollmentId: text("sourceEnrollmentId"), openingAmount: text("openingAmount"), existingCredits: text("existingCredits"), sourceReferences: text("sourceReferences").split(/\r?\n/).filter(Boolean), provenance: text("provenance"), identityVerified: form.get("identityVerified") === "on" });
    if (mode === "VERIFY") Object.assign(input, { expectedVersion: liability?.version, paymentIds: text("paymentIds").split(/\s*,\s*/).filter(Boolean), identityVerified: form.get("identityVerified") === "on", balanceVerified: form.get("balanceVerified") === "on" });
    if (mode === "PREPARE") Object.assign(input, { kind: text("kind"), requestedAmount: text("requestedAmount"), applicantReference: text("applicantReference"), validFrom: text("validFrom"), validTo: text("validTo") });
    if (mode === "PROPOSE_PAYMENT" || mode === "VERIFY_PAYMENT") Object.assign(input, { paymentId: text("paymentId"), proposalEventId: text("proposalEventId"), sourceYear: text("sourceYear"), sourceEnrollmentId: text("sourceEnrollmentId"), identityVerified: form.get("identityVerified") === "on", expectedLiabilityVersion: liability?.version });
    await submit(input);
  }
  return <section className="card"><h2>Prepare and verify office evidence</h2><p>Use exact Student and enrollment references from the ERP. A name match or office-list membership cannot establish liability. Unknown amounts must be reviewed before submission.</p><form onSubmit={prepare}>
    <label>Office action<select value={mode} onChange={(event) => setMode(event.target.value)}><option value="PREPARE_LIABILITY">Prepare source-liability proposal</option><option value="VERIFY">Independently verify opening liability</option><option value="PREPARE">Prepare concession case</option><option value="PROPOSE_PAYMENT">Propose attribution of received payment</option><option value="VERIFY_PAYMENT">Independently verify payment attribution</option></select></label>
    {mode !== "PREPARE_LIABILITY" && <label>Previous-year liability<select required value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Select exact liability</option>{liabilities.map((item) => <option key={item.id} value={item.id}>{item.studentId} · {item.sourceYear} · {item.status}</option>)}</select></label>}
    {liability && <p>Reviewed opening ₹{liability.openingAmount}; existing credits ₹{liability.existingCredits}. Evidence: {liability.provenance}</p>}
    {mode === "PREPARE_LIABILITY" && <><label>Exact Student reference<input name="studentId" required maxLength={80} /></label><label>Operating academic year<input name="operatingYear" required maxLength={40} /></label><label>Eligible source academic year<input name="sourceYear" required maxLength={40} /></label><label>Exact source-year enrollment reference<input name="sourceEnrollmentId" required maxLength={80} /></label><label>Opening verified fee liability<input name="openingAmount" inputMode="decimal" required /></label><label>Existing approved credits (enter reviewed zero explicitly)<input name="existingCredits" inputMode="decimal" required /></label><label>Fee-head / term evidence references, one per line<textarea name="sourceReferences" required /></label><label>Source and existing-credit provenance<textarea name="provenance" required maxLength={1000} /></label><label><input type="checkbox" name="identityVerified" required />I verified the exact Student and source-year enrollment.</label></>}
    {mode === "VERIFY" && <><label>Received payment references, comma separated (leave empty only after verifying none)<textarea name="paymentIds" /></label><label><input type="checkbox" name="identityVerified" required />I independently verified identity and source year.</label><label><input type="checkbox" name="balanceVerified" required />I reviewed the opening, payments, existing credits and blank-cell meanings.</label></>}
    {mode === "PREPARE" && <><label>Financial meaning<select name="kind"><option value="SCHOOL_WAIVER">School waiver / concession</option><option value="SPONSORSHIP_PROMISE">Sponsorship promise — no money received</option></select></label><label>Requested relief<input name="requestedAmount" inputMode="decimal" required /></label><label>Applicant reference<input name="applicantReference" maxLength={120} required /></label><label>Valid from<input type="date" name="validFrom" required /></label><label>Valid through<input type="date" name="validTo" required /></label></>}
    {(mode === "PROPOSE_PAYMENT" || mode === "VERIFY_PAYMENT") && <><p>Record received funds through existing payment services first. This action only reviews source-year attribution; it never creates another payment.</p>{mode === "PROPOSE_PAYMENT" ? <label>Existing Payment reference<input name="paymentId" required /></label> : <label>Attribution proposal event reference<input name="proposalEventId" required /></label>}<label>Verified payment source academic year<input name="sourceYear" required /></label><label>Exact source-year enrollment reference<input name="sourceEnrollmentId" required /></label><label><input type="checkbox" name="identityVerified" required />I verified the payment identity and source-year evidence.</label></>}
    <label>Reason (exclude private income details)<textarea name="reason" required maxLength={1000} /></label><button disabled={busy}>Submit for the selected office action</button>
  </form></section>;
}
