"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { startAuthentication } from "@simplewebauthn/browser";
import type { PublicKeyCredentialRequestOptionsJSON } from "@simplewebauthn/browser";

type Dashboard={aggregates:Record<string,number>;requests:Array<{requestKey:string;name:string;personType:string;roles:string[];status:string;mfa:string[];mfaRequired:boolean;trainingRequired:number;trainingPending:number;warnings:string[];validUntil:string|null;reviewDueAt:string|null;accountState:{lifecycle:string;active:boolean}|null}>};
type Template={id:string;mfa:string;implementation:string;temporary:boolean}; type Person={handle:string;label:string};

export function RealUserAccessReadiness({initial,canManage,templates,people}:{initial:Dashboard;canManage:boolean;templates:Template[];people:{staff:Person[];guardians:Person[];students:Person[]}}){
  const router=useRouter(),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[personType,setPersonType]=useState("STAFF"),[roles,setRoles]=useState<string[]>([]),[protectedAction,setProtectedAction]=useState<{requestKey:string;action:"APPROVE"|"ISSUE_SYNTHETIC_INVITATION";challengeToken:string;factor:"TOTP"|"WEBAUTHN";webauthnOptions:PublicKeyCredentialRequestOptionsJSON|null}|null>(null),[oneTimeLink,setOneTimeLink]=useState("");
  const candidates=personType==="STAFF"?people.staff:personType==="GUARDIAN"?people.guardians:personType==="STUDENT"?people.students:[];
  async function prepare(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/user-access-readiness/requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({personType,personHandle:form.get("personHandle"),requestedName:form.get("requestedName"),username:form.get("username"),email:form.get("email"),roles,scopes:String(form.get("scopes")??"").split("\n").map(v=>v.trim()).filter(Boolean),reason:form.get("reason"),validUntil:form.get("validUntil")||null})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Preparation failed");setMessage(`Prepared ${data.request.requestKey}. The account is not active.`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Preparation failed");}finally{setBusy(false);}}
  async function workflow(requestKey:string,action:string,stepUpToken?:string){setBusy(true);setMessage("");try{const response=await fetch(`/api/user-access-readiness/requests/${encodeURIComponent(requestKey)}/workflow`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,stepUpToken,activationOrigin:location.origin})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Workflow action failed");if(data.result?.preview?.link)setOneTimeLink(data.result.preview.link);setMessage(`${action.replaceAll("_"," ")} completed.`);setProtectedAction(null);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Workflow action failed");}finally{setBusy(false);}}
  async function beginProtected(requestKey:string,action:"APPROVE"|"ISSUE_SYNTHETIC_INVITATION"){setBusy(true);try{const response=await fetch("/api/auth/step-up/challenge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:action==="APPROVE"?"ACCESS_REQUEST_APPROVE":"ACCESS_INVITATION_ISSUE"})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Verification unavailable");const factor=data.factorType==="WEBAUTHN"?"WEBAUTHN":"TOTP";setProtectedAction({requestKey,action,challengeToken:data.challengeToken,factor,webauthnOptions:factor==="WEBAUTHN"?data.webauthnOptions as PublicKeyCredentialRequestOptionsJSON:null});}catch(error){setMessage(error instanceof Error?error.message:"Verification unavailable");}finally{setBusy(false);}}
  async function completeProtected(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!protectedAction)return;setBusy(true);const form=new FormData(event.currentTarget),stepAction=protectedAction.action==="APPROVE"?"ACCESS_REQUEST_APPROVE":"ACCESS_INVITATION_ISSUE";try{const factorResponse=protectedAction.factor==="WEBAUTHN"&&protectedAction.webauthnOptions?await startAuthentication({optionsJSON:protectedAction.webauthnOptions}):form.get("totpToken");const response=await fetch("/api/auth/step-up/complete",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({challengeToken:protectedAction.challengeToken,action:stepAction,factor:protectedAction.factor,response:factorResponse})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Verification failed");await workflow(protectedAction.requestKey,protectedAction.action,data.stepUpToken);}catch(error){setMessage(error instanceof Error?error.message:"Verification failed");setBusy(false);}}
  function toggle(role:string){setRoles(current=>current.includes(role)?current.filter(item=>item!==role):[...current,role]);}
  const metrics=[["Prospective",initial.aggregates.prospective],["Pending approval",initial.aggregates.pendingApproval],["Invitation ready",initial.aggregates.invitationReady],["Activation pending",initial.aggregates.activationPending],["Active",initial.aggregates.active],["MFA ready",initial.aggregates.mfaReady],["Review due",initial.aggregates.reviewDue],["Expired temporary",initial.aggregates.expiredTemporary]];
  return <div className="access-readiness-workspace">
    <section className="access-readiness-boundary" role="status"><strong>SOFTWARE FOUNDATION · DEFAULT OFF OUTSIDE GOVERNED QA</strong><span>No real accounts, invitations, providers or rollout are activated by this workspace.</span></section>
    <section className="access-readiness-metrics" aria-label="Access readiness summary">{metrics.map(([label,value])=><div className="card" key={String(label)}><span>{label}</span><strong>{value??0}</strong></div>)}</section>
    {message?<div className="notice" role="status" aria-live="polite">{message}</div>:null}
    {canManage?<details className="card card-pad"><summary className="button">Prepare an access request</summary><form className="access-readiness-form" onSubmit={prepare}>
      <label>Person type<select value={personType} onChange={event=>{setPersonType(event.target.value);setRoles([]);}}><option>STAFF</option><option>GUARDIAN</option><option>STUDENT</option><option>OTHER</option></select></label>
      {personType==="OTHER"?<label>Reviewed display name<input name="requestedName" required maxLength={100}/></label>:<label>Exact governed person link<select name="personHandle" required><option value="">Select an unlinked active record</option>{candidates.map(row=><option key={row.handle} value={row.handle}>{row.label}</option>)}</select></label>}
      <label>Username<input name="username" required minLength={3} maxLength={64} autoCapitalize="none" spellCheck={false}/></label><label>Email candidate<input name="email" type="email" maxLength={254}/></label>
      <fieldset><legend>Role templates</legend><div className="access-template-grid">{templates.map(template=><label key={template.id}><input type="checkbox" checked={roles.includes(template.id)} onChange={()=>toggle(template.id)}/><span><strong>{template.id.replaceAll("_"," ")}</strong><small>{template.implementation.replaceAll("_"," ")} · MFA {template.mfa.toLowerCase()}{template.temporary?" · expiry required":""}</small></span></label>)}</div></fieldset>
      <label>Exact scopes, one per line<textarea name="scopes" maxLength={4000}/></label><label>Temporary access ends<input name="validUntil" type="datetime-local"/></label><label className="wide">Business reason<textarea name="reason" required minLength={12} maxLength={500}/></label><button disabled={busy||roles.length===0}>{busy?"Preparing…":"Preview and prepare inactive request"}</button>
    </form></details>:null}
    <section className="card"><div className="card-pad"><h2>Governed access requests</h2><p>Every status is explicit; colour is supplementary and never the only status signal.</p></div><div className="table-wrap"><table><thead><tr><th>Candidate</th><th>Access</th><th>Readiness</th><th>Status</th><th>Governed action</th></tr></thead><tbody>{initial.requests.map(row=><tr key={row.requestKey}><td><strong>{row.name}</strong><small>{row.personType}</small></td><td>{row.roles.join(" + ")}<small>{row.warnings.length?`${row.warnings.length} review warning(s)`:"No combination warning"}</small></td><td>MFA {row.mfaRequired?(row.mfa.length?"ready":"required"):"recommended"}<small>{row.trainingPending} of {row.trainingRequired} training item(s) pending</small></td><td><span className="status-pill">{row.status.replaceAll("_"," ")}</span></td><td><div className="access-row-actions">{row.status==="PREPARED"?<button disabled={busy} onClick={()=>void workflow(row.requestKey,"SUBMIT")}>Submit</button>:null}{row.status==="AWAITING_APPROVAL"?<><button className="secondary" disabled={busy} onClick={()=>void workflow(row.requestKey,"REVIEW")}>Review link</button><button disabled={busy} onClick={()=>void beginProtected(row.requestKey,"APPROVE")}>Approve</button></>:null}{row.status==="APPROVED_FOR_INVITATION"?<button disabled={busy} onClick={()=>void beginProtected(row.requestKey,"ISSUE_SYNTHETIC_INVITATION")}>Create local QA invitation</button>:null}</div></td></tr>)}</tbody></table></div></section>
    {protectedAction?<div className="dialog-backdrop" role="presentation"><section className="security-dialog" role="dialog" aria-modal="true" aria-labelledby="access-step-up-title"><h2 id="access-step-up-title">Additional verification required</h2><p>This action is bound to your current session and can be approved only once.</p><form onSubmit={completeProtected}>{protectedAction.factor==="WEBAUTHN"?<p>Use your registered passkey to authorize this action.</p>:<label>Six-digit authenticator code<input name="totpToken" inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" required autoFocus/></label>}<div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setProtectedAction(null)}>Cancel</button><button disabled={busy}>{busy?"Verifying…":protectedAction.factor==="WEBAUTHN"?"Use passkey and continue":"Verify and continue"}</button></div></form></section></div>:null}
    {oneTimeLink?<div className="dialog-backdrop" role="presentation"><section className="security-dialog" role="dialog" aria-modal="true" aria-labelledby="invitation-once-title"><h2 id="invitation-once-title">Synthetic invitation — one-time reveal</h2><p>Local QA only. Copy it now; closing this dialog removes it from the UI.</p><label>Activation link<input value={oneTimeLink} readOnly onFocus={event=>event.currentTarget.select()}/></label><div className="dialog-actions"><button onClick={()=>setOneTimeLink("")}>I stored the synthetic QA link safely</button></div></section></div>:null}
  </div>;
}
