"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { HALF_DAY_SESSIONS, STAFF_LEAVE_TYPES, leaveLabel } from "@/lib/staff-leave";

type StaffOption = { id: string; staffCode: string | null; fullName: string; displayName: string | null; designation: string };
type LeaveView = { id: string; staffMemberId: string; leaveType: string; startDate: string; endDate: string; halfDaySession: string | null; totalDays: number; reason: string; status: string; substituteRequired: boolean; substituteNotes: string | null; notes: string | null; approvedAt: string | null; rejectedAt: string | null; rejectionReason: string | null; cancelledAt: string | null; cancellationReason: string | null; approver: { name: string } | null; cancelledBy: { name: string } | null; staffMember: StaffOption };

export function StaffLeaveForm({ staff, fixedStaffId, request, canManage, canApprove, canApply }: { staff: StaffOption[]; fixedStaffId?: string; request?: LeaveView; canManage: boolean; canApprove: boolean; canApply: boolean }) {
  const router = useRouter();
  const [form, setForm] = useState({ staffMemberId: request?.staffMemberId ?? fixedStaffId ?? staff[0]?.id ?? "", leaveType: request?.leaveType ?? "CASUAL", startDate: request?.startDate.slice(0,10) ?? "", endDate: request?.endDate.slice(0,10) ?? "", halfDaySession: request?.halfDaySession ?? "", reason: request?.reason ?? "", substituteRequired: request?.substituteRequired ?? false, substituteNotes: request?.substituteNotes ?? "", notes: request?.notes ?? "" });
  const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [rejectionReason,setRejectionReason]=useState(""); const [cancellationReason,setCancellationReason]=useState("");
  const [confirmation,setConfirmation]=useState<{action:"approve"|"reject"|"cancel";title:string;description:string;extra:Record<string,string>}|null>(null);
  const editable = !request || request.status === "DRAFT";
  function update(key:string,value:string|boolean){setForm(current=>({...current,[key]:value}));}
  async function save(action:string, extra:Record<string,string>={}) { setConfirmation(null);setBusy(true);setMessage("");setError(""); try { const response=await fetch(request?`/api/leave/staff/${request.id}`:"/api/leave/staff",{method:request?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ ...form, action, ...extra })}); const data=await response.json(); if(!response.ok)throw new Error(data.error||"Unable to update leave request"); setMessage([data.warning, action==="draft"?"Draft leave request saved.":action==="submit"?"Leave request submitted for approval.":action==="approve"?"Leave request approved.":action==="reject"?"Leave request rejected.":action==="cancel"?"Leave request cancelled.":"Draft leave request updated."].filter(Boolean).join(" ")); if(!request&&data.leaveRequest?.id){router.push(`/leave/staff/${data.leaveRequest.id}`);return;} router.refresh(); } catch(e){setError(e instanceof Error?e.message:"Unable to update leave request");} finally{setBusy(false);} }
  function confirmAction(action:"approve"|"reject"|"cancel") { setError(""); if(action==="reject"&&!rejectionReason.trim())return setError("Enter a rejection reason before rejecting leave."); if(action==="cancel"&&!cancellationReason.trim())return setError("Enter a cancellation reason before cancelling leave."); const details:{title:string;description:string;extra:Record<string,string>}=action==="approve"?{title:"Approve this leave request?",description:"Approval is final in the current workflow. The request cannot be silently edited.",extra:{}}:action==="reject"?{title:"Reject this leave request?",description:"The request will be retained with the rejection reason and reviewer details.",extra:{rejectionReason}}:{title:"Cancel this leave request?",description:"The request will be retained as Cancelled with the cancellation reason.",extra:{cancellationReason}}; setConfirmation({action,...details}); }
  return <div className="leave-stack">
    {editable ? <section className="card card-pad"><div className="form-grid leave-form-grid">
      <label>Staff Member<select aria-label="Staff Member" disabled={!canManage||Boolean(fixedStaffId)||Boolean(request&&!canManage)} value={form.staffMemberId} onChange={e=>update("staffMemberId",e.target.value)}><option value="">Choose staff</option>{staff.map(member=><option key={member.id} value={member.id}>{member.displayName||member.fullName}{member.staffCode?` (${member.staffCode})`:""} - {member.designation}</option>)}</select></label>
      <label>Leave Type<select aria-label="Leave Type" value={form.leaveType} onChange={e=>setForm(current=>({...current,leaveType:e.target.value,halfDaySession:e.target.value==="HALF_DAY"?current.halfDaySession:""}))}>{STAFF_LEAVE_TYPES.map(type=><option key={type} value={type}>{leaveLabel(type)}</option>)}</select></label>
      <label>Start Date<input aria-label="Start Date" type="date" value={form.startDate} onChange={e=>update("startDate",e.target.value)} /></label>
      <label>End Date<input aria-label="End Date" type="date" value={form.endDate} onChange={e=>update("endDate",e.target.value)} /></label>
      {(form.leaveType==="HALF_DAY"||form.halfDaySession)?<label>Half-day Session<select aria-label="Half-day Session" value={form.halfDaySession} onChange={e=>update("halfDaySession",e.target.value)}><option value="">Choose session</option>{HALF_DAY_SESSIONS.map(value=><option key={value} value={value}>{leaveLabel(value)}</option>)}</select></label>:null}
      <label className="wide">Reason<textarea aria-label="Reason" rows={4} value={form.reason} onChange={e=>update("reason",e.target.value)} placeholder="Reason is required before submission" /></label>
      <label className="checkbox-label"><input type="checkbox" checked={form.substituteRequired} onChange={e=>update("substituteRequired",e.target.checked)} /> Substitute may be required</label>
      <label className="wide">Substitute Planning Notes <span className="muted-text">(advisory context only)</span><textarea aria-label="Substitute Planning Notes" value={form.substituteNotes} onChange={e=>update("substituteNotes",e.target.value)} placeholder="Approval does not assign a substitute automatically" /></label>
      <label className="wide">Internal Notes <span className="muted-text">(optional)</span><textarea aria-label="Internal Notes" value={form.notes} onChange={e=>update("notes",e.target.value)} /></label>
      <div className="full page-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>save(request?"edit":"draft")}>{request?"Save Draft Changes":"Save Draft"}</button>{(canApply||canManage)?<button type="button" disabled={busy} onClick={()=>save("submit")}>Submit Request</button>:null}</div>
    </div></section> : null}
    {request ? <section className="card card-pad leave-detail-actions"><h3>Workflow Actions</h3>{request.status==="PENDING"&&canApprove?<><p>Approving makes this request final in the current workflow.</p><div className="page-actions"><button disabled={busy} onClick={()=>confirmAction("approve")}>Approve Leave</button></div><label>Rejection Reason<textarea aria-label="Rejection Reason" value={rejectionReason} onChange={e=>setRejectionReason(e.target.value)} /></label><button className="danger" disabled={busy} onClick={()=>confirmAction("reject")}>Reject Leave</button></>:null}{["DRAFT","PENDING"].includes(request.status)&&(canManage||canApply)?<><label>Cancellation Reason (required)<textarea aria-label="Cancellation Reason" value={cancellationReason} onChange={e=>setCancellationReason(e.target.value)} /></label><button className="secondary" disabled={busy} onClick={()=>confirmAction("cancel")}>Cancel Request</button></>:null}{["APPROVED","REJECTED","CANCELLED"].includes(request.status)?<p>This request is final and cannot be silently edited. Create a new request if dates or details must change.</p>:null}</section> : null}
    {confirmation?<div className="confirmation-overlay" role="presentation"><section className="card confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="leave-confirm-title" aria-describedby="leave-confirm-description"><h3 id="leave-confirm-title">{confirmation.title}</h3><p id="leave-confirm-description">{confirmation.description}</p><div className="page-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setConfirmation(null)}>Go Back</button><button type="button" className={confirmation.action==="approve"?"":"danger"} disabled={busy} onClick={()=>save(confirmation.action,confirmation.extra)}>{confirmation.action==="approve"?"Approve Leave":confirmation.action==="reject"?"Reject Leave":"Cancel Request"}</button></div></section></div>:null}
    {message?<div className="notice success" role="status">{message}</div>:null}{error?<div className="notice danger" role="alert">{error}</div>:null}
  </div>;
}
