"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { STAFF_STATUSES, STAFF_TYPES } from "@/lib/staff";

type StaffValue = Record<string, unknown> & { id: string; fullName: string; designation: string; staffType: string; status: string; user: { username: string; role: string; isActive: boolean } | null; timetableTeacherId: string | null };
export function StaffDetail({ staff, canManage, canCreateLogin, timetableTeachers }: { staff: StaffValue; canManage: boolean; canCreateLogin: boolean; timetableTeachers: Array<{ id: string; name: string; shortName: string }> }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function request(path: string, body: Record<string, unknown>, method = "POST") { setSaving(true); setMessage(""); const response = await fetch(path, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json(); setSaving(false); if (!response.ok) { setMessage(json.error || "Unable to save changes"); return; } setMessage("Saved."); router.refresh(); }
  async function update(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); await request(`/api/staff/${staff.id}`, Object.fromEntries(new FormData(event.currentTarget)), "PUT"); }
  async function link(event: React.FormEvent<HTMLFormElement>, action: string) { event.preventDefault(); await request(`/api/staff/${staff.id}/links`, { action, ...Object.fromEntries(new FormData(event.currentTarget)) }); }
  const field = (key: string) => staff[key] == null ? "" : String(staff[key]);
  return <>
    <section className="notice"><strong>Teacher dashboard is not built yet.</strong> A linked Teacher login opens only the safe teacher placeholder unless another permission is explicitly granted.</section>
    <form className="card card-pad form-grid" onSubmit={update}>
      <h3 className="full">Staff Details</h3>
      <label>Staff Code<input name="staffCode" defaultValue={field("staffCode")} disabled={!canManage} /></label><label>Full Name<input name="fullName" defaultValue={staff.fullName} required disabled={!canManage} /></label><label>Display Name<input name="displayName" defaultValue={field("displayName")} disabled={!canManage} /></label>
      <label>Staff Type<select name="staffType" defaultValue={staff.staffType} disabled={!canManage}>{STAFF_TYPES.map((v) => <option key={v}>{v}</option>)}</select></label><label>Designation<input name="designation" defaultValue={staff.designation} required disabled={!canManage} /></label><label>Department<input name="department" defaultValue={field("department")} disabled={!canManage} /></label>
      <label>Primary Subject<input name="primarySubject" defaultValue={field("primarySubject")} disabled={!canManage} /></label><label>Additional Subjects<input name="additionalSubjects" defaultValue={field("additionalSubjects")} disabled={!canManage} /></label><label>Qualification<input name="qualification" defaultValue={field("qualification")} disabled={!canManage} /></label>
      <label>Experience Years<input name="experienceYears" type="number" min="0" step="0.5" defaultValue={field("experienceYears")} disabled={!canManage} /></label><label>Date of Joining<input name="dateOfJoining" type="date" defaultValue={field("dateOfJoining").slice(0,10)} disabled={!canManage} /></label><label>Status<select name="status" defaultValue={staff.status} disabled={!canManage}>{STAFF_STATUSES.map((v) => <option key={v}>{v}</option>)}</select></label>
      <label>Mobile<input name="mobile" defaultValue={field("mobile")} disabled={!canManage} /></label><label>Alternate Mobile<input name="alternateMobile" defaultValue={field("alternateMobile")} disabled={!canManage} /></label><label>Email<input name="email" type="email" defaultValue={field("email")} disabled={!canManage} /></label>
      <label className="wide">Address<textarea name="address" defaultValue={field("address")} disabled={!canManage} /></label><label>Emergency Contact Name<input name="emergencyContactName" defaultValue={field("emergencyContactName")} disabled={!canManage} /></label><label>Emergency Contact Mobile<input name="emergencyContactMobile" defaultValue={field("emergencyContactMobile")} disabled={!canManage} /></label><label className="full">Notes<textarea name="notes" defaultValue={field("notes")} disabled={!canManage} /></label>
      {canManage ? <div className="full"><button disabled={saving}>Save Staff Profile</button></div> : null}
    </form>
    <div className="grid two"><section className="card card-pad"><h3>Teacher Login</h3>{staff.user ? <><p><span className={`badge ${staff.user.isActive ? "success" : ""}`}>{staff.user.isActive ? "Active" : "Inactive"}</span> {staff.user.username} ({staff.user.role})</p>{canManage ? <button className="secondary" disabled={saving} onClick={() => request(`/api/staff/${staff.id}/links`, { action: "unlink-user" })}>Unlink Login</button> : null}</> : canManage ? <>{canCreateLogin ? <form className="form-grid compact-form" onSubmit={(e) => link(e, "create-login")}><label>New Teacher Username<input name="username" required /></label><label>Temporary Password<input name="password" type="password" minLength={12} maxLength={128} required /></label><div className="full"><button disabled={saving}>Create Teacher Login</button></div></form> : null}<form className="form-grid compact-form" onSubmit={(e) => link(e, "link-user")}><label className="wide">Existing Teacher Username<input name="username" required /></label><div className="full"><button className="secondary" disabled={saving}>Link Existing Teacher User</button></div></form></> : <p>No login linked.</p>}</section>
      <section className="card card-pad"><h3>Timetable Teacher Link</h3><p className="muted-text">Optional only. Existing timetable teacher records and assignments stay unchanged.</p><form className="form-grid" onSubmit={(e) => link(e, "link-timetable")}><label className="wide">Timetable Teacher<select name="timetableTeacherId" defaultValue={staff.timetableTeacherId ?? ""} disabled={!canManage}><option value="">Not linked</option>{timetableTeachers.map((t) => <option key={t.id} value={t.id}>{t.name} ({t.shortName})</option>)}</select></label>{canManage ? <div className="full"><button className="secondary" disabled={saving}>Save Timetable Link</button></div> : null}</form></section></div>
    {message ? <p className={message === "Saved." ? "notice" : "error"} role="status">{message}</p> : null}
  </>;
}
