"use client";
import { useState } from "react";
import { readSpreadsheetRows } from "@/lib/client-spreadsheet";

type Preview = { rows: Array<{ rowNumber: number; normalized: { staffCode: string | null; fullName: string; staffType: string; designation: string; email: string | null; mobile: string | null }; matchBy: string | null; action: string; errors: string[]; warnings: string[] }>; counts: { total: number; created: number; updated: number; errors: number; warnings: number } };
export function StaffImportPanel() {
  const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [preview, setPreview] = useState<Preview | null>(null); const [confirmed, setConfirmed] = useState(false); const [message, setMessage] = useState(""); const [working, setWorking] = useState(false); const [fileName, setFileName] = useState("");
  async function onFile(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; setPreview(null); setConfirmed(false); if (!file) return; setWorking(true); setFileName(file.name); try { const parsed = await readSpreadsheetRows<Record<string, unknown>>(file); if (!parsed.length) throw new Error("The selected file has no staff rows"); const response = await fetch("/api/import/staff", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "preview", rows: parsed }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error); setRows(parsed); setPreview(json.preview); setMessage("Preview ready. No staff records were changed."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to preview staff file"); } finally { setWorking(false); } }
  async function confirm() { if (!preview || !confirmed) return; setWorking(true); try { const response = await fetch("/api/import/staff", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "import", rows, confirmed: true, fileName }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error); setMessage(`Import completed: ${json.result.created} created, ${json.result.updated} updated, ${json.result.skipped} skipped, ${json.result.errors.length} errors.`); setConfirmed(false); } catch (error) { setMessage(error instanceof Error ? error.message : "Staff import failed"); } finally { setWorking(false); } }
  return <section className="card card-pad" id="staff-import"><div className="section-title inline-section-title"><div><h3>Staff Import</h3><p>Preview first. Existing staff match by staff code, or by email/mobile only when staff code is missing.</p></div><a className="button secondary" href="/api/import/staff/template">Download Template</a></div><label className="wide">Staff Excel / CSV File<input type="file" accept=".xlsx,.xls,.csv" onChange={onFile} disabled={working} /></label><p className="notice">Import never creates User login accounts. Login creation remains a separate intentional action on the staff profile.</p>
    {preview ? <><div className="grid four"><div><strong>{preview.counts.total}</strong><br/>Total</div><div><strong>{preview.counts.created}</strong><br/>Create</div><div><strong>{preview.counts.updated}</strong><br/>Update</div><div><strong>{preview.counts.errors}</strong><br/>Errors</div></div><div className="table-wrap"><table><thead><tr><th>CSV Row</th><th>Code</th><th>Name</th><th>Type</th><th>Designation</th><th>Action</th><th>Issues</th></tr></thead><tbody>{preview.rows.slice(0,50).map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.normalized.staffCode ?? "-"}</td><td>{row.normalized.fullName}</td><td>{row.normalized.staffType}</td><td>{row.normalized.designation}</td><td>{row.action}{row.matchBy ? ` by ${row.matchBy}` : ""}</td><td>{[...row.errors,...row.warnings].join("; ") || "-"}</td></tr>)}</tbody></table></div><label className="review-checkbox"><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /><span>I reviewed the preview, matches, warnings, and errors. Confirm the staff import.</span></label><button type="button" disabled={!confirmed || working} onClick={confirm}>{working ? "Importing..." : "Confirm Staff Import"}</button></> : null}{message ? <p className="notice" role="status">{message}</p> : null}</section>;
}
