"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { STAFF_STATUSES, STAFF_TYPES } from "@/lib/staff";

type StaffValue = Record<string, unknown> & { id: string; fullName: string; designation: string; staffType: string; status: string; user: { username: string; role: string; isActive: boolean } | null; timetableTeacherId: string | null };
export function StaffDetail({ staff, canManage, canCreateLogin, timetableTeachers }: { staff: StaffValue; canManage: boolean; canCreateLogin: boolean; timetableTeachers: Array<{ id: string; name: string; shortName: string }> }) {
  const router = useRouter(); const [message, setMessage] = useState<{ text: string; kind: "success" | "error" } | null>(null); const [saving, setSaving] = useState(false);
  async function request(path: string, body: Record<string, unknown>, method = "POST") { setSaving(true); setMessage(null); try { const response = await fetch(path, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const text = await response.text(); const json = text ? JSON.parse(text) as { error?: string } : {}; if (!response.ok) { setMessage({ kind: "error", text: json.error || "Unable to save changes. Review the fields and try again." }); return; } setMessage({ kind: "success", text: "Saved." }); router.refresh(); } catch { setMessage({ kind: "error", text: "Connection lost before the save was confirmed. Your entered values remain on this page; reconnect and try again." }); } finally { setSaving(false); } }
  async function update(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); await request(`/api/staff/${staff.id}`, Object.fromEntries(new FormData(event.currentTarget)), "PUT"); }
  async function link(event: React.FormEvent<HTMLFormElement>, action: string) { event.preventDefault(); await request(`/api/staff/${staff.id}/links`, { action, ...Object.fromEntries(new FormData(event.currentTarget)) }); }
  const field = (key: string) => staff[key] == null ? "" : String(staff[key]);
  return <>
    <section className="notice"><strong>Staff profile scope.</strong> Account, timetable, attendance, leave, document and payroll access remain separately permission checked.</section>
    <form className="card card-pad form-grid" onSubmit={update}>
      <h2 className="full">Staff Details</h2>
      <label>Staff Code<input name="staffCode" defaultValue={field("staffCode")} disabled={!canManage} /></label><label>Full Name<input name="fullName" defaultValue={staff.fullName} required disabled={!canManage} /></label><label>Display Name<input name="displayName" defaultValue={field("displayName")} disabled={!canManage} /></label>
      <label>Staff Type<select name="staffType" defaultValue={staff.staffType} disabled={!canManage}>{STAFF_TYPES.map((v) => <option key={v}>{v}</option>)}</select></label><label>Designation<input name="designation" defaultValue={staff.designation} required disabled={!canManage} /></label><label>Department<input name="department" defaultValue={field("department")} disabled={!canManage} /></label>
      <label>Primary Subject<input name="primarySubject" defaultValue={field("primarySubject")} disabled={!canManage} /></label><label>Additional Subjects<input name="additionalSubjects" defaultValue={field("additionalSubjects")} disabled={!canManage} /></label><label>Qualification<input name="qualification" defaultValue={field("qualification")} disabled={!canManage} /></label>
      <label>Experience Years<input name="experienceYears" type="number" min="0" step="0.5" defaultValue={field("experienceYears")} disabled={!canManage} /></label><label>Date of Joining<input name="dateOfJoining" type="date" defaultValue={field("dateOfJoining").slice(0,10)} disabled={!canManage} /></label><label>Status<select name="status" defaultValue={staff.status} disabled={!canManage}>{STAFF_STATUSES.map((v) => <option key={v}>{v}</option>)}</select></label>
      {canManage ? <><label>Mobile<input name="mobile" defaultValue={field("mobile")} /></label><label>Alternate Mobile<input name="alternateMobile" defaultValue={field("alternateMobile")} /></label><label>Email<input name="email" type="email" defaultValue={field("email")} /></label>
      <label className="wide">Address<textarea name="address" defaultValue={field("address")} /></label><label>Emergency Contact Name<input name="emergencyContactName" defaultValue={field("emergencyContactName")} /></label><label>Emergency Contact Mobile<input name="emergencyContactMobile" defaultValue={field("emergencyContactMobile")} /></label><label className="full">Notes<textarea name="notes" defaultValue={field("notes")} /></label></> : <p className="full workspace-privacy-note">Private contact, address, emergency-contact and HR notes require Staff management permission and are not sent to this view.</p>}
      {canManage ? <div className="full"><button disabled={saving}>Save Staff Profile</button></div> : null}
    </form>
    {canManage ? <div className="grid two"><section className="card card-pad"><h2>Teacher Login</h2>{staff.user ? <><p><span className={`badge ${staff.user.isActive ? "success" : ""}`}>{staff.user.isActive ? "Active" : "Inactive"}</span> {staff.user.username} ({staff.user.role})</p><button className="secondary" disabled={saving} onClick={() => request(`/api/staff/${staff.id}/links`, { action: "unlink-user" })}>Unlink Login</button></> : <>{canCreateLogin ? <form className="form-grid compact-form" onSubmit={(e) => link(e, "create-login")}><label>New Teacher Username<input name="username" required /></label><label>Temporary Password<input name="password" type="password" minLength={12} maxLength={128} required /></label><div className="full"><button disabled={saving}>Create Teacher Login</button></div></form> : null}<form className="form-grid compact-form" onSubmit={(e) => link(e, "link-user")}><label className="wide">Existing Teacher Username<input name="username" required /></label><div className="full"><button className="secondary" disabled={saving}>Link Existing Teacher User</button></div></form></>}</section>
      <section className="card card-pad"><h2>Timetable Teacher Link</h2><p className="muted-text">Optional only. Existing timetable teacher records and assignments stay unchanged.</p><form className="form-grid" onSubmit={(e) => link(e, "link-timetable")}><label className="wide">Timetable Teacher<select name="timetableTeacherId" defaultValue={staff.timetableTeacherId ?? ""}><option value="">Not linked</option>{timetableTeachers.map((t) => <option key={t.id} value={t.id}>{t.name} ({t.shortName})</option>)}</select></label><div className="full"><button className="secondary" disabled={saving}>Save Timetable Link</button></div></form></section></div> : null}
    {message ? <p className={message.kind === "success" ? "notice success" : "notice danger"} role={message.kind === "success" ? "status" : "alert"}>{message.text}</p> : null}
  </>;
}
