"use client";
import Link from "next/link";
import { useState } from "react";
import { localDateText, STAFF_ATTENDANCE_STATUSES, type StaffAttendanceStatus } from "@/lib/staff-attendance";
import { useSecurityDialog } from "@/components/security-dialog-provider";
type Staff = { id: string; staffCode: string | null; fullName: string; displayName: string | null; designation: string; department: string | null; staffType: string };
type Value = { status: string; checkInTime: string; checkOutTime: string; lateMinutes: string; remarks: string };
type Session = { id: string; status: string; records: Array<Value & { staffMemberId: string }> };
const labels: Record<StaffAttendanceStatus,string> = { PRESENT:"Present", ABSENT:"Absent", LATE:"Late", HALF_DAY:"Half Day", ON_LEAVE:"On Leave", EXCUSED:"Excused" };
const blank = (): Value => ({ status:"", checkInTime:"", checkOutTime:"", lateMinutes:"", remarks:"" });
export function StaffAttendanceEntry({ academicYear, canManage, canSubmit, canLock, canViewReports }: { academicYear:string; canManage:boolean; canSubmit:boolean; canLock:boolean; canViewReports:boolean }) {
  const requestDialog=useSecurityDialog();
  const [date,setDate]=useState(localDateText()); const [staff,setStaff]=useState<Staff[]>([]); const [session,setSession]=useState<Session|null>(null); const [values,setValues]=useState<Record<string,Value>>({}); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [loaded,setLoaded]=useState(false); const [confirmingLock,setConfirmingLock]=useState(false);
  function hydrate(nextStaff:Staff[], nextSession:Session|null) { setStaff(nextStaff); setSession(nextSession); setValues(Object.fromEntries(nextStaff.map(member=>{ const record=nextSession?.records.find(row=>row.staffMemberId===member.id); return [member.id, record ? { status:record.status, checkInTime:record.checkInTime??"", checkOutTime:record.checkOutTime??"", lateMinutes:record.lateMinutes==null?"":String(record.lateMinutes), remarks:record.remarks??"" } : blank()]; }))); }
  async function load(){setBusy(true);setMessage("");const r=await fetch(`/api/attendance/staff?attendanceDate=${date}`);const d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"Unable to load staff attendance");hydrate(d.staff,d.session);setLoaded(true);setMessage(d.session?`Loaded ${d.session.status.toLowerCase()} staff attendance.`:"No staff attendance session exists yet. Create a draft to begin.");}
  async function act(action:string){if(action==="clear"&&!await requestDialog({title:"Clear staff attendance draft?",message:"Every saved staff mark and remark in this draft will be cleared. This cannot be undone.",confirmLabel:"Clear draft"}))return;setBusy(true);setMessage("");const records=staff.flatMap(member=>values[member.id]?.status?[{staffMemberId:member.id,...values[member.id]}]:[]);const r=await fetch("/api/attendance/staff",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,attendanceDate:date,academicYear,records})});const d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.error||"Unable to update staff attendance");if(action==="clear")setValues(Object.fromEntries(staff.map(m=>[m.id,blank()])));await load();setMessage(action==="create"?"Draft staff attendance created.":action==="save"?"Draft staff attendance saved.":action==="submit"?"Staff attendance submitted.":action==="lock"?"Staff attendance locked. Normal edits are now blocked.":"Draft cleared.");}
  const editable=canManage&&(!session||session.status==="DRAFT"); function markAll(status:string){setValues(Object.fromEntries(staff.map(m=>[m.id,{...(values[m.id]??blank()),status}])));}
  function update(id:string,key:keyof Value,value:string){setValues(current=>({...current,[id]:{...(current[id]??blank()),[key]:value}}));}
  return <div className="attendance-stack"><section className="card card-pad attendance-scope"><label>Date<input type="date" value={date} onChange={e=>{setDate(e.target.value);hydrate([],null);setLoaded(false);setMessage("Date changed. Select Load Attendance before marking staff.");}} /></label><button onClick={load} disabled={busy}>{busy?"Working...":"Load Attendance"}</button>{canViewReports?<Link className="button secondary" href="/attendance/staff/reports">Open Reports</Link>:null}</section>
  {message?<p className="notice" role="status">{message}</p>:null}{loaded&&!session&&staff.length&&canManage?<section className="card card-pad"><button onClick={()=>act("create")} disabled={busy}>Create Draft Attendance</button></section>:null}
  {session?<section className="card card-pad attendance-state"><div><strong>Status: <span className={`badge ${session.status==="DRAFT"?"":"success"}`}>{session.status}</span></strong><p>{session.status==="DRAFT"?"Editable working copy. Save as often as needed, then submit when complete.":session.status==="SUBMITTED"?"Completed attendance. It cannot be edited; an authorized school leader may lock it.":"Final attendance. Normal edits are blocked."}</p></div>{session.status==="SUBMITTED"&&canLock?<button onClick={()=>setConfirmingLock(true)} disabled={busy}>Lock Attendance</button>:null}</section>:null}
  {staff.length?<section className="card attendance-entry-card"><div className="section-title attendance-toolbar"><div><h3>Daily Staff Attendance</h3><p>{staff.length} active staff member{staff.length===1?"":"s"}</p></div>{editable?<div className="page-actions"><button className="secondary" onClick={()=>markAll("PRESENT")}>Mark all Present</button><button className="secondary" onClick={()=>markAll("ABSENT")}>Mark all Absent</button><button className="danger" onClick={()=>act("clear")} disabled={!session||busy}>Clear draft</button></div>:null}</div><div className="table-wrap"><table className="attendance-table staff-attendance-table"><thead><tr><th>Staff</th><th>Designation</th><th>Status</th><th>Check In</th><th>Check Out</th><th>Late Min.</th><th>Remarks</th></tr></thead><tbody>{staff.map(member=><tr key={member.id}><td><strong>{member.displayName||member.fullName}</strong><small className="muted-text"> {member.staffCode||"No code"}</small></td><td>{member.designation}</td><td><select aria-label={`Attendance for ${member.fullName}`} disabled={!editable||busy} value={values[member.id]?.status||""} onChange={e=>update(member.id,"status",e.target.value)}><option value="">Not marked</option>{STAFF_ATTENDANCE_STATUSES.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></td><td><input aria-label={`Check in for ${member.fullName}`} type="time" disabled={!editable||busy} value={values[member.id]?.checkInTime||""} onChange={e=>update(member.id,"checkInTime",e.target.value)} /></td><td><input aria-label={`Check out for ${member.fullName}`} type="time" disabled={!editable||busy} value={values[member.id]?.checkOutTime||""} onChange={e=>update(member.id,"checkOutTime",e.target.value)} /></td><td><input aria-label={`Late minutes for ${member.fullName}`} type="number" min="0" max="1440" disabled={!editable||busy} value={values[member.id]?.lateMinutes||""} onChange={e=>update(member.id,"lateMinutes",e.target.value)} /></td><td><input aria-label={`Remarks for ${member.fullName}`} disabled={!editable||busy} value={values[member.id]?.remarks||""} onChange={e=>update(member.id,"remarks",e.target.value)} placeholder="Optional" /></td></tr>)}</tbody></table></div>{editable?<div className="attendance-savebar"><button onClick={()=>act("save")} disabled={busy}>{busy?"Saving...":"Save Draft"}</button>{canSubmit?<button onClick={()=>act("submit")} disabled={busy}>Submit Attendance</button>:null}</div>:null}</section>:loaded?<section className="card empty-state"><h3>No active staff found</h3><p>Inactive and left staff are excluded safely. Add or reactivate a staff profile before taking attendance.</p></section>:null}
  {confirmingLock?<div className="confirmation-overlay" role="presentation"><section className="card confirmation-dialog" role="dialog" aria-modal="true" aria-labelledby="staff-lock-title" aria-describedby="staff-lock-description"><h3 id="staff-lock-title">Lock staff attendance?</h3><p id="staff-lock-description">This makes attendance final. It cannot be edited or unlocked in the app.</p><div className="page-actions"><button className="secondary" onClick={()=>setConfirmingLock(false)} disabled={busy}>Cancel</button><button className="danger" onClick={async()=>{setConfirmingLock(false);await act("lock");}} disabled={busy}>Lock permanently</button></div></section></div>:null}</div>;
}
