"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { SUBSTITUTE_PRIORITIES,SUBSTITUTE_REASONS,substituteLabel } from "@/lib/substitutes";

type StaffOption={id:string;staffCode:string|null;fullName:string;displayName:string|null;designation:string;department:string|null;primarySubject:string|null};
type TimetableOption={id:string;teacherStaffMemberId:string|null;label:string;className:string;section:string;subject:string};
type AssignmentView={id:string;assignmentDate:string;academicYear:string|null;leaveRequestId:string|null;absentStaffMemberId:string;substituteStaffMemberId:string|null;timetableAssignmentId:string|null;className:string|null;section:string|null;subject:string|null;periodLabel:string|null;periodStartTime:string|null;periodEndTime:string|null;reason:string;status:string;priority:string;notes:string|null;cancellationReason:string|null};

export function SubstituteForm({staff,timetableAssignments,assignment,defaults,canAssign,canConfirm,canManage}:{staff:StaffOption[];timetableAssignments:TimetableOption[];assignment?:AssignmentView;defaults?:Partial<AssignmentView>;canAssign:boolean;canConfirm:boolean;canManage:boolean}){
 const router=useRouter();const initial={assignmentDate:assignment?.assignmentDate.slice(0,10)??defaults?.assignmentDate?.slice(0,10)??"",academicYear:assignment?.academicYear??defaults?.academicYear??"",leaveRequestId:assignment?.leaveRequestId??defaults?.leaveRequestId??"",absentStaffMemberId:assignment?.absentStaffMemberId??defaults?.absentStaffMemberId??"",substituteStaffMemberId:assignment?.substituteStaffMemberId??"",timetableAssignmentId:assignment?.timetableAssignmentId??defaults?.timetableAssignmentId??"",className:assignment?.className??defaults?.className??"",section:assignment?.section??defaults?.section??"",subject:assignment?.subject??defaults?.subject??"",periodLabel:assignment?.periodLabel??defaults?.periodLabel??"",periodStartTime:assignment?.periodStartTime??defaults?.periodStartTime??"",periodEndTime:assignment?.periodEndTime??defaults?.periodEndTime??"",reason:assignment?.reason??defaults?.reason??"MANUAL",priority:assignment?.priority??"NORMAL",notes:assignment?.notes??""};
 const [form,setForm]=useState(initial);const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [cancellationReason,setCancellationReason]=useState("");const [suggestions,setSuggestions]=useState<Array<StaffOption&{dutyCount:number;reasons:string[]}>>([]);const editable=canManage&&(!assignment||["DRAFT","ASSIGNED"].includes(assignment.status));
 function update(key:string,value:string){setForm(current=>({...current,[key]:value}));}
 function chooseTimetable(value:string){const selected=timetableAssignments.find(row=>row.id===value);setForm(current=>({...current,timetableAssignmentId:value,className:selected?.className??current.className,section:selected?.section??current.section,subject:selected?.subject??current.subject,absentStaffMemberId:selected?.teacherStaffMemberId??current.absentStaffMemberId}));}
 async function save(action:string){setBusy(true);setError("");setMessage("");try{const response=await fetch(assignment?`/api/substitutes/${assignment.id}`:"/api/substitutes",{method:assignment?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,action,cancellationReason})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to update substitute assignment");setMessage(action==="draft"||action==="edit"?"Substitute plan saved.":action==="assign"?"Substitute assigned after review.":action==="confirm"?"Substitute duty confirmed.":action==="complete"?"Substitute duty completed.":"Substitute duty cancelled.");if(!assignment&&data.assignment?.id){router.push(`/substitutes/${data.assignment.id}`);return;}router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to update substitute assignment");}finally{setBusy(false);}}
 async function loadSuggestions(){setBusy(true);setError("");try{const query=new URLSearchParams({assignmentDate:form.assignmentDate,absentStaffMemberId:form.absentStaffMemberId,subject:form.subject,periodLabel:form.periodLabel,periodStartTime:form.periodStartTime,periodEndTime:form.periodEndTime});if(assignment)query.set("excludeId",assignment.id);const absent=staff.find(row=>row.id===form.absentStaffMemberId);if(absent?.department)query.set("department",absent.department);const response=await fetch(`/api/substitutes/suggestions?${query}`);const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to load suggestions");setSuggestions(data.suggestions);if(!data.suggestions.length)setMessage("No available suggested staff matched this date and period. You can adjust the period or review staff availability.");}catch(e){setError(e instanceof Error?e.message:"Unable to load suggestions");}finally{setBusy(false);}}
 return <div className="substitute-stack">
  {editable?<section className="card card-pad"><div className="form-grid substitute-form-grid">
   <label>Date<input aria-label="Assignment Date" type="date" value={form.assignmentDate} onChange={e=>update("assignmentDate",e.target.value)}/></label><label>Academic Year<input aria-label="Academic Year" value={form.academicYear} onChange={e=>update("academicYear",e.target.value)}/></label>
   <label>Absent Staff Member<select aria-label="Absent Staff Member" value={form.absentStaffMemberId} onChange={e=>update("absentStaffMemberId",e.target.value)}><option value="">Choose absent staff</option>{staff.map(row=><option key={row.id} value={row.id}>{row.displayName||row.fullName}{row.staffCode?` (${row.staffCode})`:""} - {row.designation}</option>)}</select></label>
   <label>Approved Leave Link <span className="muted-text">(optional)</span><input aria-label="Approved Leave Link" value={form.leaveRequestId} readOnly placeholder="Use planner to link approved leave"/></label>
   <label className="wide">Timetable Assignment <span className="muted-text">(optional)</span><select aria-label="Timetable Assignment" value={form.timetableAssignmentId} onChange={e=>chooseTimetable(e.target.value)}><option value="">Manual class / subject / period</option>{timetableAssignments.map(row=><option key={row.id} value={row.id}>{row.label}</option>)}</select></label>
   <label>Class<input aria-label="Class" value={form.className} onChange={e=>update("className",e.target.value)}/></label><label>Section<input aria-label="Section" value={form.section} onChange={e=>update("section",e.target.value)}/></label><label>Subject<input aria-label="Subject" value={form.subject} onChange={e=>update("subject",e.target.value)}/></label><label>Period Label<input aria-label="Period Label" value={form.periodLabel} onChange={e=>update("periodLabel",e.target.value)} placeholder="Example: Period III"/></label><label>Start Time<input aria-label="Period Start Time" type="time" value={form.periodStartTime} onChange={e=>update("periodStartTime",e.target.value)}/></label><label>End Time<input aria-label="Period End Time" type="time" value={form.periodEndTime} onChange={e=>update("periodEndTime",e.target.value)}/></label>
   <label>Reason<select aria-label="Reason" value={form.reason} onChange={e=>update("reason",e.target.value)}>{SUBSTITUTE_REASONS.map(value=><option key={value} value={value}>{substituteLabel(value)}</option>)}</select></label><label>Priority<select aria-label="Priority" value={form.priority} onChange={e=>update("priority",e.target.value)}>{SUBSTITUTE_PRIORITIES.map(value=><option key={value} value={value}>{substituteLabel(value)}</option>)}</select></label>
   <label className="wide">Substitute Staff Member<select aria-label="Substitute Staff Member" value={form.substituteStaffMemberId} onChange={e=>update("substituteStaffMemberId",e.target.value)}><option value="">Unassigned</option>{staff.filter(row=>row.id!==form.absentStaffMemberId).map(row=><option key={row.id} value={row.id}>{row.displayName||row.fullName}{row.staffCode?` (${row.staffCode})`:""} - {row.designation}</option>)}</select></label>
   <div className="wide suggestion-panel"><div><strong>Suggested staff</strong><p>Advisory only. Suggestions never assign anyone automatically.</p></div><button type="button" className="secondary" disabled={busy} onClick={loadSuggestions}>Show Safe Suggestions</button>{suggestions.map(row=><button type="button" className="suggestion-card" key={row.id} onClick={()=>update("substituteStaffMemberId",row.id)}><strong>{row.displayName||row.fullName}</strong><span>{row.designation}</span><small>{row.reasons.join("; ")}</small></button>)}</div>
   <label className="wide">Notes <span className="muted-text">(optional)</span><textarea aria-label="Notes" value={form.notes} onChange={e=>update("notes",e.target.value)} /></label>
   <div className="full page-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>save(assignment?"edit":"draft")}>{assignment?"Save Changes":"Save as Draft"}</button>{canAssign?<button type="button" disabled={busy} onClick={()=>save("assign")}>Assign Substitute</button>:null}</div>
  </div></section>:null}
  {assignment&&canManage?<section className="card card-pad substitute-workflow"><h3>Workflow Actions</h3>{assignment.status==="ASSIGNED"&&canConfirm?<button type="button" disabled={busy} onClick={()=>save("confirm")}>Confirm Duty</button>:null}{assignment.status==="CONFIRMED"&&canConfirm?<button type="button" disabled={busy} onClick={()=>save("complete")}>Mark Completed</button>:null}{!["COMPLETED","CANCELLED"].includes(assignment.status)?<><label>Cancellation Reason (required)<textarea aria-label="Cancellation Reason" value={cancellationReason} onChange={e=>setCancellationReason(e.target.value)}/></label><button type="button" className="danger" disabled={busy} onClick={()=>save("cancel")}>Cancel Assignment</button></>:null}</section>:null}
  {message?<div className="notice success" role="status">{message}</div>:null}{error?<div className="notice danger" role="alert">{error}</div>:null}
 </div>;
}
