"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Managed = { publicKey: string; reference: string; category: string; categoryLabel: string; priority: string; confidentiality: string; subject: string; originalStatement: string; status: string; version: number; receivedAt: string; requester: { name: string; type: string; identityVerified: boolean; suppliedIdentifier: string | null; contactChannel: string | null; contactValue: string | null }; queue: { code: string; name: string }; messages: Array<{ publicKey: string; type: string; body: string; authorLabel: string; createdAt: string; restricted: boolean }>; events: Array<{ publicKey: string; type: string; occurredAt: string; reason: string | null }>; resolutions: Array<{ publicKey: string; version: number; category: string; requesterSummary: string; internalSummary?: string }>; assignments: Array<{ publicKey: string; status: string; assigneeUserId: string; reason: string }>; escalations: Array<{ publicKey: string; status: string; level: number; reason: string }>; };
const CATEGORIES = ["TECHNICAL_LOGIN","ACCOUNT_ACCESS","FEE_OR_RECEIPT","ATTENDANCE","HOMEWORK_OR_CLASSWORK","EXAM_OR_REPORT_CARD","ACADEMIC_SUPPORT","ADMISSION","DATA_CORRECTION","FACILITIES","STAFF_HR","SAFETY_OR_BULLYING","COMPLAINT_AGAINST_STAFF","COMPLAINT_AGAINST_SERVICE","PRIVACY_OR_DATA","SUGGESTION","APPRECIATION","OTHER"];
const RESOLUTIONS = ["INFORMATION_PROVIDED","TECHNICAL_FIX_COMPLETED","RECORD_CORRECTED","FINANCE_ACTION_COMPLETED","ACADEMIC_ACTION_COMPLETED","POLICY_EXPLAINED","REQUEST_NOT_VALID","DUPLICATE","REFERRED_FOR_FURTHER_ACTION","OTHER"];

export function SupportManagement() {
  const [rows, setRows] = useState<Managed[]>([]), [selectedKey, setSelectedKey] = useState(""), [assignees, setAssignees] = useState<Array<{ publicKey: string; name: string; role: string }>>([]), [message, setMessage] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const selected = useMemo(() => rows.find((row) => row.publicKey === selectedKey) ?? rows[0] ?? null, [rows, selectedKey]);
  async function load(preferred?: string) { const response = await fetch("/api/support", { cache: "no-store" }), body = await response.json(); if (!response.ok) throw new Error(body.error || "Support queues could not be loaded."); setRows(body.requests); if (preferred) setSelectedKey(preferred); else if (!selectedKey && body.requests[0]) setSelectedKey(body.requests[0].publicKey); }
  useEffect(() => { load().catch((caught) => setError(errorText(caught))); }, []);
  useEffect(() => { if (!selected) { setAssignees([]); return; } fetch(`/api/support/${selected.publicKey}/assignees`, { cache: "no-store" }).then(async (response) => ({ response, body: await response.json() })).then(({ response, body }) => setAssignees(response.ok ? body.assignees : [])).catch(() => setAssignees([])); }, [selected?.publicKey]);
  async function act(body: Record<string, unknown>, success: string) { if (!selected) return; setBusy(true); setError(""); setMessage(""); try { const response = await fetch(`/api/support/${selected.publicKey}/workflow`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, expectedVersion: selected.version }) }), result = await response.json(); if (!response.ok) throw new Error(result.error || "The support action was refused."); setMessage(success); await load(selected.publicKey); } catch (caught) { setError(errorText(caught)); } finally { setBusy(false); } }
  async function manual(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget, data = new FormData(form); setBusy(true); setError(""); try { const response = await fetch("/api/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source: data.get("source"), requesterName: data.get("requesterName"), requesterType: data.get("requesterType"), requesterIdentifier: data.get("requesterIdentifier") || null, contactChannel: data.get("contactChannel") || null, contactValue: data.get("contactValue") || null, category: data.get("category"), subject: data.get("subject"), statement: data.get("statement"), identityVerified: false, signedPaperReference: data.get("signedPaperReference") || null, consentRecorded: data.get("consentRecorded") === "on", submissionKey: crypto.randomUUID() }) }), body = await response.json(); if (!response.ok) throw new Error(body.error || "Manual intake was refused."); form.reset(); setMessage("In-person complaint recorded without treating a supplied identifier as verified."); await load(body.request.publicKey); } catch (caught) { setError(errorText(caught)); } finally { setBusy(false); } }
  async function submitAction(event: FormEvent<HTMLFormElement>, builder: (data: FormData) => Record<string, unknown>, success: string) { event.preventDefault(); const form = event.currentTarget; await act(builder(new FormData(form)), success); form.reset(); }
  return <div className="support-management-workspace">
    <div className="support-emergency" role="note"><strong>Emergency boundary</strong><span>Urgent physical danger or medical emergencies use the school&apos;s immediate emergency channel. The case system records follow-up; it is not emergency dispatch.</span></div>
    <div className="support-live" role="status" aria-live="polite">{message}</div>{error ? <div className="form-error" role="alert">{error}</div> : null}
    <details className="card support-manual-intake"><summary>Record in-person, phone or paper complaint</summary><form className="form-grid" onSubmit={manual}>
      <label>Original source<select name="source"><option value="IN_PERSON">In person</option><option value="PHONE_RECORDED_BY_STAFF">Phone recorded by Staff</option><option value="PAPER_FORM_RECORDED_BY_STAFF">Paper form recorded by Staff</option></select></label><label>Requester type<select name="requesterType"><option>PARENT</option><option>STAFF</option><option>APPLICANT</option><option>OTHER</option></select></label>
      <label>Requester name<input name="requesterName" minLength={2} maxLength={100} required /></label><label>Supplied identifier <span className="muted-text">(unverified)</span><input name="requesterIdentifier" maxLength={80} /></label><label>Contact channel<select name="contactChannel"><option value="">Not recorded</option><option>MOBILE</option><option>EMAIL</option></select></label><label>Contact<input name="contactValue" maxLength={254} /></label>
      <label>Category<select name="category">{CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label>Signed-paper reference<input name="signedPaperReference" maxLength={120} /></label><label className="wide">Subject<input name="subject" minLength={3} maxLength={160} required /></label><label className="wide">Original statement <span className="muted-text">(preserved exactly; corrections append)</span><textarea name="statement" minLength={20} maxLength={8000} required /></label><label className="wide checkbox-row"><input name="consentRecorded" type="checkbox" /> Consent/privacy notice acknowledged where applicable</label><button className="wide" disabled={busy}>Record governed intake</button>
    </form></details>
    <div className="support-case-layout"><nav className="card support-case-list" aria-label="Authorised support queue">{rows.map((row) => <button type="button" key={row.publicKey} className={row.publicKey === selected?.publicKey ? "active" : ""} onClick={() => setSelectedKey(row.publicKey)}><strong>{row.reference}</strong><span>{row.queue.name} · {label(row.status)}</span><small>{label(row.priority)} · {label(row.confidentiality)}</small></button>)}</nav>
      {selected ? <article key={selected.publicKey} className="card support-case-detail support-management-detail"><header><div><p className="eyebrow">{selected.reference} · {selected.queue.name}</p><h2>{selected.subject}</h2></div><div className="support-actions"><a className="button secondary" href={`/api/support/${selected.publicKey}/export`}>Export bounded case</a><span className="badge">{label(selected.status)}</span></div></header>
        <dl className="detail-grid"><div><dt>Requester</dt><dd>{selected.requester.name} ({selected.requester.type})</dd></div><div><dt>Identity</dt><dd>{selected.requester.identityVerified ? "Verified authenticated/office context" : "Unverified as supplied"}</dd></div><div><dt>Category</dt><dd>{selected.categoryLabel}</dd></div><div><dt>Confidentiality</dt><dd>{label(selected.confidentiality)}</dd></div></dl><section className="support-original-statement"><h3>Original requester statement</h3><p>{selected.originalStatement}</p></section>
        <div className="support-action-grid">
          <form className="form-stack" onSubmit={(event) => submitAction(event, (data) => ({ action: "TRIAGE", category: data.get("category"), priority: data.get("priority"), confidentiality: data.get("confidentiality"), reason: data.get("reason") }), "Triage recorded with a new request version.")}><h3>Triage</h3><label>Category<select name="category" defaultValue={selected.category}>{CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></label><label>Priority<select name="priority" defaultValue={selected.priority}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label>Confidentiality<select name="confidentiality" defaultValue={selected.confidentiality}><option>STANDARD</option><option>RESTRICTED</option><option>SAFEGUARDING</option><option>LEADERSHIP_ONLY</option></select></label><label>Reason<textarea name="reason" minLength={3} maxLength={1000} required /></label><button disabled={busy}>Record triage</button></form>
          <form className="form-stack" onSubmit={(event) => submitAction(event, (data) => ({ action: "ASSIGN", assigneeUserKey: data.get("assigneeUserKey"), reason: data.get("reason") }), "Assignment recorded with history.")}><h3>Assignment</h3><label>Authorised assignee<select name="assigneeUserKey" required defaultValue=""><option value="" disabled>Choose assignee</option>{assignees.map((row) => <option key={row.publicKey} value={row.publicKey}>{row.name} · {label(row.role)}</option>)}</select></label><label>Reason<textarea name="reason" minLength={3} maxLength={1000} required /></label><button disabled={busy || !assignees.length}>Assign</button></form>
          <form className="form-stack support-message-form" onSubmit={(event) => submitAction(event, (data) => ({ action: "MESSAGE", messageType: data.get("messageType"), informationRequested: data.get("informationRequested") === "on", body: data.get("body") }), "Message appended with its exact visibility.")}><h3>Message or note</h3><label>Visibility<select name="messageType"><option value="REQUESTER_VISIBLE">Requester-visible response</option><option value="INTERNAL_NOTE">INTERNAL NOTE — never shown to requester</option></select></label><label>Body<textarea name="body" minLength={1} maxLength={6000} required /></label><label className="checkbox-row"><input name="informationRequested" type="checkbox" /> Request information from requester</label><button disabled={busy}>Append message</button></form>
          <form className="form-stack" onSubmit={(event) => submitAction(event, (data) => ({ action: "RESOLVE", resolutionCategory: data.get("resolutionCategory"), requesterVisibleSummary: data.get("requesterVisibleSummary"), internalActionSummary: data.get("internalActionSummary"), linkedActionType: data.get("linkedActionType") || null, linkedActionReference: data.get("linkedActionReference") || null }), "Resolution preserved; corrective modules remain separate.")}><h3>Resolve</h3><label>Resolution category<select name="resolutionCategory">{RESOLUTIONS.map((item) => <option key={item}>{item}</option>)}</select></label><label>Requester-visible summary<textarea name="requesterVisibleSummary" minLength={10} maxLength={4000} required /></label><label>Internal action summary<textarea name="internalActionSummary" minLength={3} maxLength={4000} required /></label><label>Linked governed action type<input name="linkedActionType" maxLength={80} /></label><label>Safe action reference<input name="linkedActionReference" maxLength={120} /></label><button disabled={busy}>Resolve request</button></form>
        </div>
        <section><h3>Lifecycle actions</h3><div className="support-actions">{transitionActions(selected.status).map(([action, text]) => <button type="button" className="secondary" disabled={busy} key={action} onClick={() => void act({ action: "TRANSITION", transitionAction: action, reason: `${text} through governed management action` }, `${text} recorded.`)}>{text}</button>)}</div></section>
        <section><h3>Messages</h3>{selected.messages.length ? <ol className="support-message-list">{selected.messages.map((item) => <li className={item.type === "INTERNAL_NOTE" ? "internal" : "requester"} key={item.publicKey}><strong>{item.type === "INTERNAL_NOTE" ? "INTERNAL NOTE — NOT REQUESTER VISIBLE" : "REQUESTER-VISIBLE RESPONSE"}</strong><span>{item.authorLabel} · {format(item.createdAt)}</span><p>{item.body}</p></li>)}</ol> : <p>No message has been appended.</p>}</section>
        <section><h3>Append-only event history</h3><ol className="timeline-list">{selected.events.map((item) => <li key={item.publicKey}><strong>{label(item.type)}</strong><span>{format(item.occurredAt)}</span>{item.reason ? <p>{item.reason}</p> : null}</li>)}</ol></section>
      </article> : <p className="card card-pad">No support request is visible in this exact role and queue scope.</p>}</div>
  </div>;
}

function label(value: string) { return value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function format(value: string) { return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }).format(new Date(value)); }
function errorText(value: unknown) { return value instanceof Error ? value.message : "The support action failed safely."; }
function transitionActions(status: string): Array<[string,string]> { const map: Record<string,Array<[string,string]>> = { SUBMITTED: [["ACKNOWLEDGE","Acknowledge"]], ACKNOWLEDGED: [["START","Start work"],["ESCALATE","Escalate"]], TRIAGED: [["START","Start work"],["ESCALATE","Escalate"]], ASSIGNED: [["START","Start work"],["WAIT_FOR_INTERNAL","Wait for internal action"],["ESCALATE","Escalate"]], IN_PROGRESS: [["WAIT_FOR_INTERNAL","Wait for internal action"],["ESCALATE","Escalate"]], WAITING_FOR_REQUESTER: [["START","Resume work"],["ESCALATE","Escalate"]], WAITING_FOR_INTERNAL_ACTION: [["START","Resume work"],["ESCALATE","Escalate"]], ESCALATED: [["START","Resume work"]], RESOLVED: [["CLOSE","Close"]], CLOSED: [["ARCHIVE","Archive"]], CANCELLED: [["ARCHIVE","Archive"]], REJECTED_AS_INVALID: [["ARCHIVE","Archive"]] }; return map[status] ?? []; }
