"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Props={canVehicles:boolean;canRoutes:boolean;canAssignments:boolean;canReports:boolean};
type Data={vehicles:any[];routes:any[];stops:any[];assignments:any[];students:any[];staff:any[];policy:any};

export function TransportWorkspace({canVehicles,canRoutes,canAssignments,canReports}:Props){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{setError("");const response=await fetch("/api/operations/transport/workspace",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Unable to load Transport.");setData(body);},[]);
  useEffect(()=>{load().catch((value)=>setError(value.message));},[load]);
  async function submit(event:React.FormEvent<HTMLFormElement>,path:string,build:(form:FormData)=>unknown,method="POST"){event.preventDefault();setError("");setNotice("");const form=event.currentTarget;try{const response=await fetch(path,{method,headers:{"content-type":"application/json"},body:JSON.stringify(build(new FormData(form)))}),body=await response.json();if(!response.ok)throw new Error(body.error??"Transport action failed.");setNotice("Saved. The retained audit/history record is current.");form.reset();await load();}catch(value){setError(value instanceof Error?value.message:"Transport action failed.");}}
  if(!data&&!error)return <div className="card"><p>Loading Transport foundation…</p></div>;
  const routeStops=(direction:string)=>data?.routes.flatMap((route:any)=>route.routeStops.filter((stop:any)=>stop.direction===direction&&stop.active).map((stop:any)=>({route,stop})))??[];
  return <div className="optional-operations-workspace">
    <div className="card optional-operations-boundary" role="note"><strong>DEFAULT-OFF software foundation.</strong><p>No live GPS, home-address roster, automatic alert, finance posting, map provider or real service activation is included.</p></div>
    {error?<div className="alert error" role="alert">{error}</div>:null}{notice?<div className="alert success" role="status">{notice}</div>:null}
    <section className="card-grid optional-operations-summary" aria-label="Transport summary">
      <article className="card"><span className="muted">Vehicles</span><strong>{data?.vehicles.length??0}</strong></article>
      <article className="card"><span className="muted">Routes</span><strong>{data?.routes.length??0}</strong></article>
      <article className="card"><span className="muted">Active assignments</span><strong>{data?.assignments.filter((row:any)=>row.active).length??0}</strong></article>
      <article className="card"><span className="muted">Capacity policy</span><strong>Hard block</strong></article>
    </section>
    <div className="card-grid optional-operations-forms">
      {canVehicles?<form className="card form-grid" onSubmit={(event)=>submit(event,"/api/operations/transport/vehicles",(form)=>({registrationCode:form.get("registrationCode"),displayName:form.get("displayName"),capacity:Number(form.get("capacity"))}))}><h2>Add vehicle</h2><label>Registration code<input name="registrationCode" required maxLength={40}/></label><label>Display name<input name="displayName" required maxLength={80}/></label><label>Capacity<input name="capacity" type="number" min="1" max="200" required/></label><button className="button" type="submit">Save vehicle</button></form>:null}
      {canRoutes?<form className="card form-grid" onSubmit={(event)=>submit(event,"/api/operations/transport/stops",(form)=>({code:form.get("code"),name:form.get("name"),approvedReference:form.get("approvedReference")}))}><h2>Add approved stop</h2><label>Stop code<input name="code" required maxLength={40}/></label><label>Stop name<input name="name" required maxLength={100}/></label><label>Approved reference<input name="approvedReference" maxLength={160} placeholder="Landmark or approved reference only"/></label><button className="button" type="submit">Save stop</button></form>:null}
      {canRoutes?<form className="card form-grid" onSubmit={(event)=>submit(event,"/api/operations/transport/routes",(form)=>({code:form.get("code"),name:form.get("name"),vehicleKey:form.get("vehicleKey"),capacity:Number(form.get("capacity")),directionMode:"BOTH",driverStaffCode:form.get("driverStaffCode"),attendantStaffCode:form.get("attendantStaffCode")}))}><h2>Add route</h2><label>Route code<input name="code" required maxLength={40}/></label><label>Route name<input name="name" required maxLength={100}/></label><label>Vehicle<select name="vehicleKey" required><option value="">Select</option>{data?.vehicles.filter((row:any)=>row.status==="ACTIVE").map((row:any)=><option key={row.publicKey} value={row.publicKey}>{row.registrationCode} · {row.displayName}</option>)}</select></label><label>Route capacity<input name="capacity" type="number" min="1" max="200" required/></label><label>Driver reference<select name="driverStaffCode"><option value="">Not assigned</option>{data?.staff.map((row:any)=><option key={row.staffCode} value={row.staffCode}>{row.staffCode} · {row.fullName}</option>)}</select></label><label>Attendant reference<select name="attendantStaffCode"><option value="">Not assigned</option>{data?.staff.map((row:any)=><option key={row.staffCode} value={row.staffCode}>{row.staffCode} · {row.fullName}</option>)}</select></label><button className="button" type="submit">Save route</button></form>:null}
      {canRoutes?<form className="card form-grid" onSubmit={(event)=>submit(event,"/api/operations/transport/route-stops",(form)=>({routeKey:form.get("routeKey"),stopKey:form.get("stopKey"),direction:form.get("direction"),sequence:Number(form.get("sequence")),timingReference:form.get("timingReference")}))}><h2>Order route stop</h2><label>Route<select name="routeKey" required><option value="">Select</option>{data?.routes.filter((row:any)=>row.status==="ACTIVE").map((row:any)=><option key={row.publicKey} value={row.publicKey}>{row.code} · {row.name}</option>)}</select></label><label>Stop<select name="stopKey" required><option value="">Select</option>{data?.stops.filter((row:any)=>row.active).map((row:any)=><option key={row.publicKey} value={row.publicKey}>{row.code} · {row.name}</option>)}</select></label><label>Direction<select name="direction" required><option value="MORNING">Morning pickup</option><option value="EVENING">Evening drop</option></select></label><label>Order<input name="sequence" type="number" min="1" max="200" required/></label><label>Approved timing<input name="timingReference" maxLength={80} placeholder="Example: 07:35 approx."/></label><button className="button" type="submit">Add ordered stop</button></form>:null}
      {canAssignments?<form className="card form-grid" onSubmit={(event)=>submit(event,"/api/operations/transport/assignments",(form)=>{const admissionNo=String(form.get("admissionNo")??""),current=data?.assignments.find((row:any)=>row.student.admissionNo===admissionNo&&row.open);return {admissionNo,routeKey:form.get("routeKey"),pickupRouteStopKey:form.get("pickupRouteStopKey"),dropRouteStopKey:form.get("dropRouteStopKey"),effectiveFrom:form.get("effectiveFrom"),effectiveTo:form.get("effectiveTo"),changeReason:form.get("changeReason"),expectedCurrentAssignmentKey:current?.publicKey,expectedCurrentVersion:current?.version};})}><h2>Assign Student</h2><label>Student<select name="admissionNo" required><option value="">Select</option>{data?.students.map((row:any)=><option key={row.admissionNo} value={row.admissionNo}>{row.admissionNo} · {row.studentName}</option>)}</select></label><label>Route<select name="routeKey" required><option value="">Select</option>{data?.routes.filter((row:any)=>row.status==="ACTIVE").map((row:any)=><option key={row.publicKey} value={row.publicKey}>{row.code} · {row.name}</option>)}</select></label><label>Pickup stop<select name="pickupRouteStopKey" required><option value="">Select morning stop</option>{routeStops("MORNING").map(({route,stop}:any)=><option key={stop.publicKey} value={stop.publicKey}>{route.code} · {stop.sequence}. {stop.stop.name}</option>)}</select></label><label>Drop stop<select name="dropRouteStopKey" required><option value="">Select evening stop</option>{routeStops("EVENING").map(({route,stop}:any)=><option key={stop.publicKey} value={stop.publicKey}>{route.code} · {stop.sequence}. {stop.stop.name}</option>)}</select></label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>Effective to (optional)<input name="effectiveTo" type="date"/></label><label className="span-2">Reason<input name="changeReason" required minLength={5} maxLength={240}/></label><button className="button" type="submit">Save effective-dated assignment</button></form>:null}
    </div>
    <section className="card"><div className="section-heading"><div><h2>Transport roster</h2><p>No home address or Staff contact data.</p></div>{canReports?<Link className="button secondary" href="/api/operations/transport/reports/export">Export privacy-minimal CSV</Link>:null}</div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Route</th><th>Pickup</th><th>Drop</th><th>Dates</th><th>Status</th></tr></thead><tbody>{data?.assignments.map((row:any)=><tr key={row.publicKey}><td>{row.student.admissionNo} · {row.student.studentName}<br/><span className="muted">{row.student.className}{row.student.section?`-${row.student.section}`:""}</span></td><td>{row.route.code} · {row.route.name}</td><td>{row.pickupRouteStop.stop.name}</td><td>{row.dropRouteStop.stop.name}</td><td>{new Date(row.effectiveFrom).toISOString().slice(0,10)} → {row.effectiveTo?new Date(row.effectiveTo).toISOString().slice(0,10):"Open"}</td><td>{row.lifecycleStatus}</td></tr>)}{!data?.assignments.length?<tr><td colSpan={6}>No synthetic Transport assignments.</td></tr>:null}</tbody></table></div></section>
  </div>;
}
