import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { PrismaClient } from "@prisma/client";
import { unzipSync, zipSync } from "fflate";
import { decryptCloudBackup, encryptCloudBackup } from "@/lib/cloud-backup-container";
import { readAdmissionFile } from "@/lib/admissions-files";

const MANIFEST = "manifest.json";
const MAX_COUNT = 2_000;
const MAX_BYTES = 200 * 1024 * 1024;
type Manifest = { format: "NALANDA_ADMISSIONS_ASSETS_V1"; createdAt: string; assets: Array<{ publicKey: string; applicationKey: string; documentType: string; version: number; storageKey: string; mediaType: string; extension: string; byteSize: number; sha256: string; width: number | null; height: number | null; entry: string }> };
export class AdmissionsAssetBackupError extends Error {}

export async function createAndVerifyAdmissionsAssetBackup(client: PrismaClient, input: { artifactPath: string; key: Buffer; keyVersion: string; restoreRoots: [string, string]; documentPublicKeys?: string[]; createdAt?: Date }) {
  if (input.key.length !== 32) throw new AdmissionsAssetBackupError("Admission asset backup requires a 32-byte encryption key.");
  const requested = [...new Set(input.documentPublicKeys ?? [])]; if (requested.length > MAX_COUNT) throw new AdmissionsAssetBackupError("Admission asset backup exceeds the bounded file count.");
  const rows = await client.applicationDocument.findMany({ where: requested.length ? { publicKey: { in: requested } } : undefined, include: { application: { select: { publicKey: true } } }, orderBy: { publicKey: "asc" }, take: MAX_COUNT + 1 });
  if (rows.length > MAX_COUNT || (requested.length && rows.length !== requested.length)) throw new AdmissionsAssetBackupError("Admission asset backup selection is invalid or too large.");
  const createdAt = input.createdAt ?? new Date(); const entries: Record<string, Uint8Array> = {}; let totalBytes = 0;
  const manifest: Manifest = { format: "NALANDA_ADMISSIONS_ASSETS_V1", createdAt: createdAt.toISOString(), assets: [] };
  for (const row of rows) { const bytes = await readAdmissionFile(row.storageKey, row.sha256); totalBytes += bytes.length; if (totalBytes > MAX_BYTES) throw new AdmissionsAssetBackupError("Admission asset backup exceeds the bounded byte limit."); entries[row.storageKey] = bytes; manifest.assets.push({ publicKey: row.publicKey, applicationKey: row.application.publicKey, documentType: row.documentType, version: row.version, storageKey: row.storageKey, mediaType: row.mediaType, extension: row.extension, byteSize: row.byteSize, sha256: row.sha256, width: row.width, height: row.height, entry: row.storageKey }); }
  entries[MANIFEST] = Buffer.from(JSON.stringify(manifest), "utf8"); const plaintext = Buffer.from(zipSync(entries, { level: 9 })); const encrypted = await encryptCloudBackup(plaintext, { backupFormatVersion: 37, createdAt, encryptionKeyVersion: input.keyVersion, key: input.key });
  await mkdir(path.dirname(path.resolve(input.artifactPath)), { recursive: true }); await writeFile(input.artifactPath, encrypted.bytes, { flag: "wx", mode: 0o600 }); const persisted = await readFile(input.artifactPath); const artifactSha256 = sha256(persisted);
  const firstRestore = await restoreAdmissionsAssetBackup(persisted, { key: input.key, targetRoot: input.restoreRoots[0] }); const secondRestore = await restoreAdmissionsAssetBackup(persisted, { key: input.key, targetRoot: input.restoreRoots[1] });
  if (JSON.stringify(firstRestore) !== JSON.stringify(secondRestore) || firstRestore.assetCount !== rows.length) throw new AdmissionsAssetBackupError("The two isolated admission-document restores do not match.");
  await client.$transaction(async (tx) => { for (const row of rows) { const changed = await tx.applicationDocument.updateMany({ where: { id: row.id, sha256: row.sha256, byteSize: row.byteSize }, data: { recoveryStatus: "VERIFIED", backupArtifactSha256: artifactSha256, backupKeyVersion: input.keyVersion, backupVerifiedAt: createdAt } }); if (changed.count !== 1) throw new AdmissionsAssetBackupError("An admission document changed while recovery evidence was recorded."); } });
  return { artifactSha256, assetCount: rows.length, totalBytes, encryptedBytes: persisted.length, firstRestore, secondRestore };
}

export async function restoreAdmissionsAssetBackup(container: Buffer, input: { key: Buffer; targetRoot: string }) {
  const decrypted = await decryptCloudBackup(container, { key: input.key, maximumPlaintextBytes: MAX_BYTES + 10 * 1024 * 1024 }); let archive: Record<string, Uint8Array>; try { archive = unzipSync(decrypted.plaintext); } catch { throw new AdmissionsAssetBackupError("The decrypted admission asset archive is malformed."); }
  const manifestBytes = archive[MANIFEST]; if (!manifestBytes) throw new AdmissionsAssetBackupError("The admission asset manifest is missing."); let manifest: Manifest; try { manifest = JSON.parse(Buffer.from(manifestBytes).toString("utf8")); } catch { throw new AdmissionsAssetBackupError("The admission asset manifest is invalid."); } validateManifest(manifest, archive);
  const root = path.resolve(input.targetRoot); const stat = await lstat(root).catch(() => null); if (stat?.isSymbolicLink() || (stat && !stat.isDirectory())) throw new AdmissionsAssetBackupError("The admission restore target is unsafe."); await mkdir(root, { recursive: true }); const digest = createHash("sha256"); let idempotent = true;
  for (const asset of manifest.assets) { const target = safePath(root, asset.entry); const bytes = Buffer.from(archive[asset.entry]); if (bytes.length !== asset.byteSize || sha256(bytes) !== asset.sha256) throw new AdmissionsAssetBackupError("A restored admission document failed byte/hash verification."); await mkdir(path.dirname(target), { recursive: true }); const current = await readFile(target).catch(() => null); if (current) { if (current.length !== bytes.length || sha256(current) !== asset.sha256) throw new AdmissionsAssetBackupError("The admission restore target contains a conflicting document."); } else { await writeFile(target, bytes, { flag: "wx", mode: 0o600 }); idempotent = false; } digest.update(asset.publicKey).update(asset.applicationKey).update(asset.documentType).update(String(asset.version)).update(asset.sha256); }
  return { assetCount: manifest.assets.length, manifestSha256: sha256(manifestBytes), assetDigest: digest.digest("hex"), idempotent };
}

function validateManifest(manifest: Manifest, archive: Record<string, Uint8Array>) { if (!manifest || manifest.format !== "NALANDA_ADMISSIONS_ASSETS_V1" || !Array.isArray(manifest.assets) || manifest.assets.length > MAX_COUNT || new Date(manifest.createdAt).toISOString() !== manifest.createdAt) throw new AdmissionsAssetBackupError("The admission asset manifest is unsupported."); const expected = [MANIFEST, ...manifest.assets.map((row) => row.entry)].sort(), actual = Object.keys(archive).sort(); if (expected.length !== actual.length || expected.some((row, index) => row !== actual[index])) throw new AdmissionsAssetBackupError("The admission asset archive contains unexpected entries."); const publicKeys = new Set<string>(); let bytes = 0; for (const row of manifest.assets) { if (!validKey(row.publicKey) || !validKey(row.applicationKey) || publicKeys.has(row.publicKey) || !/^[A-Z_]{3,40}$/.test(row.documentType) || !Number.isInteger(row.version) || row.version < 1 || !/^[a-f0-9]{2}\/[a-f0-9]{2}\/[a-f0-9-]{36}\.(?:pdf|png|jpg|webp)$/.test(row.entry) || row.entry !== row.storageKey || !["application/pdf", "image/png", "image/jpeg", "image/webp"].includes(row.mediaType) || ![".pdf", ".png", ".jpg", ".webp"].includes(row.extension) || !/^[a-f0-9]{64}$/.test(row.sha256) || !Number.isInteger(row.byteSize) || row.byteSize < 1 || ((row.width === null) !== (row.height === null))) throw new AdmissionsAssetBackupError("The admission asset manifest contains an invalid entry."); publicKeys.add(row.publicKey); bytes += row.byteSize; } if (bytes > MAX_BYTES) throw new AdmissionsAssetBackupError("The admission asset manifest exceeds the byte limit."); }
function safePath(root: string, entry: string) { const target = path.resolve(root, ...entry.split("/")); if (!target.startsWith(`${root}${path.sep}`)) throw new AdmissionsAssetBackupError("The admission asset archive contains a traversal path."); return target; }
function validKey(value: unknown) { return typeof value === "string" && /^[A-Za-z0-9_-]{8,100}$/.test(value); }
function sha256(value: Uint8Array) { return createHash("sha256").update(value).digest("hex"); }
