type Row = Record<string, unknown>;
const arrays = ["certificateNumberSeries","certificateTemplates","studentCertificateRequests","studentCertificates","studentCertificateVersions","studentCertificateEvents"] as const;
function rows(root: Record<string, unknown>, key: typeof arrays[number]) { const value = root[key]; if (value == null) return [] as Row[]; if (!Array.isArray(value) || value.length > 100000 || value.some(r => !r || typeof r !== "object" || Array.isArray(r))) throw new Error(`${key} must be an array of objects`); return value as Row[]; }
function required(row: Row, key: string, label: string) { const value = String(row[key] ?? "").trim(); if (!value) throw new Error(`${label}.${key} is required`); return value; }
function unique(values: string[], label: string) { if (new Set(values).size !== values.length) throw new Error(`${label} contains duplicate identities`); }
export function validateCertificateBackupRows(root: Record<string, unknown>, context: { studentIds: Set<string>; guardianIds: Set<string> }) {
  const certificateNumberSeries=rows(root,"certificateNumberSeries"),certificateTemplates=rows(root,"certificateTemplates"),studentCertificateRequests=rows(root,"studentCertificateRequests"),studentCertificates=rows(root,"studentCertificates"),studentCertificateVersions=rows(root,"studentCertificateVersions"),studentCertificateEvents=rows(root,"studentCertificateEvents");
  const types=new Set(["BONAFIDE","STUDY","CONDUCT","TRANSFER"]);
  unique(certificateNumberSeries.map((r,i)=>required(r,"id",`certificateNumberSeries[${i}]`)),"Certificate series IDs");unique(certificateNumberSeries.map((r,i)=>required(r,"seriesCode",`certificateNumberSeries[${i}]`).toUpperCase()),"Certificate series codes");
  certificateNumberSeries.forEach((r,i)=>{if(!types.has(required(r,"certificateType",`certificateNumberSeries[${i}]`))||Number(r.nextNumber)<1)throw new Error(`certificateNumberSeries[${i}] is invalid`);});
  unique(certificateTemplates.map((r,i)=>required(r,"id",`certificateTemplates[${i}]`)),"Certificate template IDs");unique(certificateTemplates.map((r,i)=>required(r,"templateCode",`certificateTemplates[${i}]`).toUpperCase()),"Certificate template codes");
  const templateIds=new Set(certificateTemplates.map(r=>String(r.id)));certificateTemplates.forEach((r,i)=>{if(!types.has(required(r,"certificateType",`certificateTemplates[${i}]`)))throw new Error(`certificateTemplates[${i}].certificateType is invalid`);JSON.parse(required(r,"templateDefinitionJson",`certificateTemplates[${i}]`));});
  unique(studentCertificateRequests.map((r,i)=>required(r,"id",`studentCertificateRequests[${i}]`)),"Certificate request IDs");unique(studentCertificateRequests.map((r,i)=>required(r,"requestNumber",`studentCertificateRequests[${i}]`)),"Certificate request numbers");
  const requestIds=new Set(studentCertificateRequests.map(r=>String(r.id)));studentCertificateRequests.forEach((r,i)=>{if(!context.studentIds.has(required(r,"studentId",`studentCertificateRequests[${i}]`)))throw new Error(`studentCertificateRequests[${i}] has an invalid Student link`);if(r.applicantGuardianId&& !context.guardianIds.has(String(r.applicantGuardianId)))throw new Error(`studentCertificateRequests[${i}] has an invalid Guardian link`);});
  unique(studentCertificates.map((r,i)=>required(r,"id",`studentCertificates[${i}]`)),"Certificate IDs");const numbers=studentCertificates.map(r=>String(r.certificateNumber??"")).filter(Boolean);unique(numbers,"Issued certificate numbers");
  const certificateIds=new Set(studentCertificates.map(r=>String(r.id)));studentCertificates.forEach((r,i)=>{if(!context.studentIds.has(required(r,"studentId",`studentCertificates[${i}]`))||!templateIds.has(required(r,"templateId",`studentCertificates[${i}]`)))throw new Error(`studentCertificates[${i}] has an invalid Student or template link`);if(r.requestId&&!requestIds.has(String(r.requestId)))throw new Error(`studentCertificates[${i}] has an invalid request link`);JSON.parse(required(r,"draftDataJson",`studentCertificates[${i}]`));});
  unique(studentCertificateVersions.map((r,i)=>required(r,"id",`studentCertificateVersions[${i}]`)),"Certificate version IDs");const versionIds=new Set(studentCertificateVersions.map(r=>String(r.id))),versionKeys=studentCertificateVersions.map(r=>`${r.certificateId}|${r.versionNumber}`);unique(versionKeys,"Certificate version numbers");
  studentCertificateVersions.forEach((r,i)=>{if(!certificateIds.has(required(r,"certificateId",`studentCertificateVersions[${i}]`)))throw new Error(`studentCertificateVersions[${i}] has an invalid certificate link`);JSON.parse(required(r,"snapshotJson",`studentCertificateVersions[${i}]`));});
  unique(studentCertificateEvents.map((r,i)=>required(r,"id",`studentCertificateEvents[${i}]`)),"Certificate event IDs");studentCertificateEvents.forEach((r,i)=>{if(r.requestId&&!requestIds.has(String(r.requestId))||r.certificateId&&!certificateIds.has(String(r.certificateId))||r.versionId&&!versionIds.has(String(r.versionId)))throw new Error(`studentCertificateEvents[${i}] has an invalid link`);});
  return {certificateNumberSeries,certificateTemplates,studentCertificateRequests,studentCertificates,studentCertificateVersions,studentCertificateEvents};
}
