import { validateClassXTemplateDefinition, validateClassXTemplateSnapshot } from "@/lib/class-x-template-definition";

type Row = Record<string, unknown>;
const arrays = ["classXPackageTemplates", "classXDocumentPackages", "classXPackageDocumentItems", "classXPackageChargeRules", "classXPackageCharges", "classXPackageHandovers", "classXPackageEvents"] as const;
function rows(root: Record<string, unknown>, key: typeof arrays[number]) { const value = root[key]; if (value === undefined) return [] as Row[]; if (!Array.isArray(value) || value.some((row) => !row || typeof row !== "object" || Array.isArray(row))) throw new Error(`${key} must be an array of objects`); return value as Row[]; }
function required(row: Row, key: string, label: string) { const value = String(row[key] ?? "").trim(); if (!value) throw new Error(`${label}.${key} is required`); return value; }
function unique(values: string[], label: string) { if (new Set(values).size !== values.length) throw new Error(`${label} contain a duplicate`); }

export function validateClassXPackageBackupRows(root: Record<string, unknown>, context: { studentIds: Set<string>; guardianIds: Set<string>; certificateIds: Set<string>; certificateVersionIds: Set<string>; miscReceiptIds: Set<string> }) {
  const result = Object.fromEntries(arrays.map((key) => [key, rows(root, key)])) as Record<typeof arrays[number], Row[]>;
  const templates = result.classXPackageTemplates, packages = result.classXDocumentPackages, items = result.classXPackageDocumentItems, rules = result.classXPackageChargeRules, charges = result.classXPackageCharges, handovers = result.classXPackageHandovers, events = result.classXPackageEvents;
  unique(templates.map((row) => required(row, "id", "Class X template")), "Class X template IDs"); unique(templates.map((row) => required(row, "templateCode", "Class X template")), "Class X template codes");
  templates.forEach((row) => validateClassXTemplateDefinition(required(row, "documentDefinitionJson", "Class X template")));
  unique(rules.map((row) => required(row, "id", "Class X charge rule")), "Class X charge-rule IDs"); unique(rules.map((row) => required(row, "ruleCode", "Class X charge rule")), "Class X charge-rule codes");
  const templateIds = new Set(templates.map((row) => String(row.id))), ruleIds = new Set(rules.map((row) => String(row.id)));
  unique(packages.map((row) => required(row, "id", "Class X package")), "Class X package IDs"); unique(packages.map((row) => required(row, "packageNumber", "Class X package")), "Class X package numbers");
  const packageIds = new Set(packages.map((row) => String(row.id)));
  packages.forEach((row, index) => { if (!context.studentIds.has(required(row, "studentId", `classXDocumentPackages[${index}]`))) throw new Error(`classXDocumentPackages[${index}] has an invalid Student link`); if (!templateIds.has(required(row, "templateId", `classXDocumentPackages[${index}]`))) throw new Error(`classXDocumentPackages[${index}] has an invalid template link`); if (row.applicantGuardianId && !context.guardianIds.has(String(row.applicantGuardianId))) throw new Error(`classXDocumentPackages[${index}] has an invalid Guardian link`); validateClassXTemplateSnapshot(required(row, "templateSnapshotJson", `classXDocumentPackages[${index}]`)); JSON.parse(required(row, "eligibilitySnapshotJson", `classXDocumentPackages[${index}]`)); });
  unique(items.map((row) => required(row, "id", "Class X item")), "Class X item IDs"); unique(items.map((row) => `${required(row, "packageId", "Class X item")}|${required(row, "itemKey", "Class X item")}`), "Class X package/item keys");
  const itemIds = new Set(items.map((row) => String(row.id)));
  items.forEach((row, index) => { if (!packageIds.has(String(row.packageId))) throw new Error(`classXPackageDocumentItems[${index}] has an invalid package link`); if (row.linkedStudentCertificateId && !context.certificateIds.has(String(row.linkedStudentCertificateId))) throw new Error(`classXPackageDocumentItems[${index}] has an invalid Prompt 18A certificate link`); if (row.linkedStudentCertificateVersionId && !context.certificateVersionIds.has(String(row.linkedStudentCertificateVersionId))) throw new Error(`classXPackageDocumentItems[${index}] has an invalid Prompt 18A certificate-version link`); });
  unique(charges.map((row) => required(row, "id", "Class X charge")), "Class X charge IDs"); unique(charges.map((row) => required(row, "packageId", "Class X charge")), "Class X charge package links"); unique(charges.map((row) => required(row, "chargeCode", "Class X charge")), "Class X charge codes");
  const receiptLinks = charges.filter((row) => row.linkedMiscIncomeReceiptId).map((row) => String(row.linkedMiscIncomeReceiptId)); unique(receiptLinks, "Class X charge receipt links");
  const chargeIds = new Set(charges.map((row) => String(row.id)));
  charges.forEach((row, index) => { if (!packageIds.has(String(row.packageId))) throw new Error(`classXPackageCharges[${index}] has an invalid package link`); if (row.chargeRuleId && !ruleIds.has(String(row.chargeRuleId))) throw new Error(`classXPackageCharges[${index}] has an invalid rule link`); if (row.linkedMiscIncomeReceiptId && !context.miscReceiptIds.has(String(row.linkedMiscIncomeReceiptId))) throw new Error(`classXPackageCharges[${index}] has an invalid Miscellaneous Income receipt link`); if (row.status === "PAID" && !row.linkedMiscIncomeReceiptId) throw new Error(`classXPackageCharges[${index}] paid state requires one linked receipt`); });
  unique(handovers.map((row) => required(row, "id", "Class X handover")), "Class X handover IDs"); unique(handovers.map((row) => required(row, "handoverNumber", "Class X handover")), "Class X handover numbers");
  const handoverIds = new Set(handovers.map((row) => String(row.id)));
  handovers.forEach((row, index) => { if (!packageIds.has(String(row.packageId))) throw new Error(`classXPackageHandovers[${index}] has an invalid package link`); const snapshot = JSON.parse(required(row, "itemSnapshotJson", `classXPackageHandovers[${index}]`)); if (!Array.isArray(snapshot)) throw new Error(`classXPackageHandovers[${index}] item snapshot must be an array`); });
  unique(events.map((row) => required(row, "id", "Class X event")), "Class X event IDs");
  events.forEach((row, index) => { if (!packageIds.has(String(row.packageId))) throw new Error(`classXPackageEvents[${index}] has an invalid package link`); if (row.documentItemId && !itemIds.has(String(row.documentItemId)) || row.chargeId && !chargeIds.has(String(row.chargeId)) || row.handoverId && !handoverIds.has(String(row.handoverId))) throw new Error(`classXPackageEvents[${index}] has an invalid linked record`); });
  return result;
}
