type RestoreRecord = Record<string, unknown>;

const KEYS = {
  identityCardNumberSeries: new Set(["id","seriesCode","cardType","academicYear","prefix","nextNumber","paddingLength","suffix","resetPolicy","status","isDefault","createdByUserId","createdAt","updatedAt"]),
  identityCardTemplates: new Set(["id","templateCode","cardType","name","academicYear","status","versionNumber","frontDefinitionJson","backDefinitionJson","printSettingsJson","photoRequired","barcodeEnabled","createdByUserId","activatedByUserId","createdAt","updatedAt"]),
  identityCardBatches: new Set(["id","batchNumber","cardType","academicYear","templateId","scopeType","className","section","staffDesignation","validFrom","validUntil","status","expectedCount","eligibleCount","issuedCount","skippedCount","scopeSnapshotJson","resultSnapshotJson","notes","cancellationReason","createdByUserId","approvedByUserId","issuedByUserId","cancelledByUserId","approvedAt","issuedAt","cancelledAt","createdAt","updatedAt"]),
  identityCards: new Set(["id","cardType","batchId","templateId","numberSeriesId","studentId","staffMemberId","academicYear","cardNumber","validFrom","validUntil","status","currentVersionNumber","draftDataJson","templateSnapshotJson","issueReason","revocationReason","cancellationReason","replacesCardId","createdByUserId","approvedByUserId","issuedByUserId","revokedByUserId","cancelledByUserId","approvedAt","issuedAt","revokedAt","cancelledAt","createdAt","updatedAt"]),
  identityCardVersions: new Set(["id","identityCardId","versionNumber","versionType","cardNumber","snapshotJson","correctionReason","issuedAt","issuedByUserId","supersedesVersionId","snapshotHash","createdAt"]),
  identityCardEvents: new Set(["id","batchId","identityCardId","versionId","eventType","eventDate","previousStatus","newStatus","reason","notes","recordedByUserId","createdAt"])
};

function rows(value: unknown, label: keyof typeof KEYS) {
  if (value == null) return [] as RestoreRecord[];
  if (!Array.isArray(value) || value.length > 100_000) throw new Error(`${label} must be a safe array`);
  return value.map((item, index) => {
    if (!item || typeof item !== "object" || Array.isArray(item)) throw new Error(`${label}[${index}] must be an object`);
    const row = item as RestoreRecord, unknown = Object.keys(row).find((key) => !KEYS[label].has(key));
    if (unknown) throw new Error(`${label}[${index}] contains unknown field: ${unknown}`);
    return row;
  });
}
function text(value: unknown, label: string) { const out = String(value ?? "").trim(); if (!out) throw new Error(`${label} is required`); return out; }
function json(value: unknown, label: string) { const source = text(value, label); try { const parsed = JSON.parse(source); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); return parsed; } catch { throw new Error(`${label} must contain safe JSON`); } }
function jsonContainer(value: unknown, label: string) { const source = text(value, label); try { const parsed = JSON.parse(source); if (!parsed || typeof parsed !== "object") throw new Error(); return parsed; } catch { throw new Error(`${label} must contain safe JSON`); } }
function date(value: unknown, label: string) { const out = text(value, label); if (Number.isNaN(new Date(out).getTime())) throw new Error(`${label} must be a date`); return out; }
function unique(set: Set<string>, value: string, label: string) { if (set.has(value)) throw new Error(`${label} is duplicated`); set.add(value); }

export function validateIdentityCardBackupRows(root: Record<string, unknown>, context: { studentIds: Set<string>; staffMemberIds: Set<string> }) {
  const identityCardNumberSeries = rows(root.identityCardNumberSeries, "identityCardNumberSeries");
  const identityCardTemplates = rows(root.identityCardTemplates, "identityCardTemplates");
  const identityCardBatches = rows(root.identityCardBatches, "identityCardBatches");
  const identityCards = rows(root.identityCards, "identityCards");
  const identityCardVersions = rows(root.identityCardVersions, "identityCardVersions");
  const identityCardEvents = rows(root.identityCardEvents, "identityCardEvents");
  const seriesIds = new Set<string>(), seriesCodes = new Set<string>();
  identityCardNumberSeries.forEach((row, index) => { const p = `identityCardNumberSeries[${index}]`, id = text(row.id, `${p}.id`), code = text(row.seriesCode, `${p}.seriesCode`); unique(seriesIds, id, `${p}.id`); unique(seriesCodes, code, `${p}.seriesCode`); if (!["STUDENT","STAFF"].includes(text(row.cardType, `${p}.cardType`))) throw new Error(`${p}.cardType is unsupported`); if (!Number.isInteger(row.nextNumber) || Number(row.nextNumber) < 1) throw new Error(`${p}.nextNumber must be positive`); if (!Number.isInteger(row.paddingLength) || Number(row.paddingLength) < 1 || Number(row.paddingLength) > 10) throw new Error(`${p}.paddingLength is invalid`); });
  const templateIds = new Set<string>(), templateCodes = new Set<string>(), templateTypes = new Map<string,string>();
  identityCardTemplates.forEach((row, index) => { const p = `identityCardTemplates[${index}]`, id = text(row.id, `${p}.id`), code = text(row.templateCode, `${p}.templateCode`), type = text(row.cardType, `${p}.cardType`); unique(templateIds, id, `${p}.id`); unique(templateCodes, code, `${p}.templateCode`); if (!["STUDENT","STAFF"].includes(type)) throw new Error(`${p}.cardType is unsupported`); if (row.photoRequired === true) throw new Error(`${p}.photoRequired cannot be restored without a managed photo source`); json(row.frontDefinitionJson, `${p}.frontDefinitionJson`); json(row.backDefinitionJson, `${p}.backDefinitionJson`); templateTypes.set(id, type); });
  const batchIds = new Set<string>(), batchNumbers = new Set<string>(), batchTypes = new Map<string,string>();
  identityCardBatches.forEach((row, index) => { const p = `identityCardBatches[${index}]`, id = text(row.id, `${p}.id`), number = text(row.batchNumber, `${p}.batchNumber`), type = text(row.cardType, `${p}.cardType`), templateId = text(row.templateId, `${p}.templateId`); unique(batchIds, id, `${p}.id`); unique(batchNumbers, number, `${p}.batchNumber`); if (templateTypes.get(templateId) !== type) throw new Error(`${p} has an invalid type/template link`); if (date(row.validUntil, `${p}.validUntil`) < date(row.validFrom, `${p}.validFrom`)) throw new Error(`${p} has an invalid validity period`); if (row.scopeSnapshotJson) jsonContainer(row.scopeSnapshotJson, `${p}.scopeSnapshotJson`); batchTypes.set(id, type); });
  const cardIds = new Set<string>(), cardNumbers = new Set<string>(), cardPeople = new Map<string,string>(), cardTypes = new Map<string,string>();
  identityCards.forEach((row, index) => { const p = `identityCards[${index}]`, id = text(row.id, `${p}.id`), type = text(row.cardType, `${p}.cardType`), templateId = text(row.templateId, `${p}.templateId`), studentId = String(row.studentId ?? "").trim(), staffId = String(row.staffMemberId ?? "").trim(); unique(cardIds, id, `${p}.id`); if (templateTypes.get(templateId) !== type) throw new Error(`${p} has an invalid type/template link`); if (row.numberSeriesId && !seriesIds.has(String(row.numberSeriesId))) throw new Error(`${p} has an invalid number-series link`); if (type === "STUDENT" ? (!studentId || staffId || !context.studentIds.has(studentId)) : (!staffId || studentId || !context.staffMemberIds.has(staffId))) throw new Error(`${p} has an invalid Student/Staff ownership link`); if (row.batchId && (batchTypes.get(String(row.batchId)) !== type)) throw new Error(`${p} has an invalid batch link`); const number = String(row.cardNumber ?? "").trim(); if (number) unique(cardNumbers, number, `${p}.cardNumber`); if (date(row.validUntil, `${p}.validUntil`) < date(row.validFrom, `${p}.validFrom`)) throw new Error(`${p} has an invalid validity period`); const draft = json(row.draftDataJson, `${p}.draftDataJson`), template = json(row.templateSnapshotJson, `${p}.templateSnapshotJson`); if (/https?:\/\/|photo(path|url)/i.test(JSON.stringify({ draft, template }))) throw new Error(`${p} exposes an unsupported photo path or remote URL`); cardPeople.set(id, `${type}|${studentId || staffId}`); cardTypes.set(id, type); });
  identityCards.forEach((row, index) => { if (row.replacesCardId && cardPeople.get(String(row.replacesCardId)) !== cardPeople.get(String(row.id))) throw new Error(`identityCards[${index}].replacesCardId must reference the same person and card type`); });
  const versionIds = new Set<string>(), versionKeys = new Set<string>();
  identityCardVersions.forEach((row, index) => { const p = `identityCardVersions[${index}]`, id = text(row.id, `${p}.id`), cardId = text(row.identityCardId, `${p}.identityCardId`), version = Number(row.versionNumber), number = text(row.cardNumber, `${p}.cardNumber`); unique(versionIds, id, `${p}.id`); if (!cardIds.has(cardId) || !Number.isInteger(version) || version < 1) throw new Error(`${p} has an invalid card/version link`); unique(versionKeys, `${cardId}|${version}`, `${p} card/version`); if (String(identityCards.find((card) => card.id === cardId)?.cardNumber ?? "") !== number) throw new Error(`${p}.cardNumber does not match its card`); const snapshot = json(row.snapshotJson, `${p}.snapshotJson`); if (/https?:\/\/|photo(path|url)/i.test(JSON.stringify(snapshot))) throw new Error(`${p} exposes an unsupported photo path or remote URL`); if (version > 1 && !row.correctionReason) throw new Error(`${p}.correctionReason is required`); date(row.issuedAt, `${p}.issuedAt`); });
  identityCardVersions.forEach((row, index) => { if (row.supersedesVersionId && !versionIds.has(String(row.supersedesVersionId))) throw new Error(`identityCardVersions[${index}].supersedesVersionId is invalid`); });
  const eventIds = new Set<string>();
  identityCardEvents.forEach((row, index) => { const p = `identityCardEvents[${index}]`, id = text(row.id, `${p}.id`); unique(eventIds, id, `${p}.id`); if (row.batchId && !batchIds.has(String(row.batchId))) throw new Error(`${p}.batchId is invalid`); if (row.identityCardId && !cardIds.has(String(row.identityCardId))) throw new Error(`${p}.identityCardId is invalid`); if (row.versionId && !versionIds.has(String(row.versionId))) throw new Error(`${p}.versionId is invalid`); text(row.eventType, `${p}.eventType`); date(row.eventDate, `${p}.eventDate`); });
  return { identityCardNumberSeries, identityCardTemplates, identityCardBatches, identityCards, identityCardVersions, identityCardEvents };
}
