import { Prisma, type PrismaClient } from "@prisma/client";
import { csvCell } from "@/lib/expenses";
import { schoolDateKey } from "@/lib/format";
import { deriveOverdue } from "@/lib/library-circulation";
import { safeMemberLabel } from "@/lib/library-members";

export const LIBRARY_CHARGE_REPORT_TYPES = ["charges", "incidents", "overdue-unassessed", "receipt-reconciliation"] as const;
export async function loadLibraryChargeReports(client: PrismaClient, masked = false) {
  const [charges, incidents, loans] = await Promise.all([
    client.libraryCharge.findMany({ include: { member: { include: { student: { select: { studentName: true, className: true } }, staffMember: { select: { fullName: true, staffType: true } } } }, loan: { select: { loanNumber: true } }, incident: { select: { incidentNumber: true } }, miscIncomeReceipt: { select: { receiptNumber: true, status: true, netAmount: true } } }, orderBy: { assessedDate: "desc" } }),
    client.libraryIncident.findMany({ include: { member: { include: { student: { select: { studentName: true, className: true } }, staffMember: { select: { fullName: true, staffType: true } } } }, title: { select: { titleCode: true, title: true } }, copy: { select: { accessionNumber: true } }, replacementCopy: { select: { accessionNumber: true } }, charges: { select: { chargeNumber: true, status: true } } }, orderBy: { reportedDate: "desc" } }),
    client.libraryLoan.findMany({ where: { status: "ISSUED" }, include: { member: { include: { student: { select: { studentName: true, className: true } }, staffMember: { select: { fullName: true, staffType: true } } } }, copy: { include: { title: true } }, charges: { where: { chargeType: "OVERDUE", status: { not: "CANCELLED" } }, select: { id: true } } } })
  ]);
  const chargeRows = charges.map((row) => ({ chargeNumber: row.chargeNumber, borrower: safeMemberLabel(row.member, masked), memberType: row.member.memberType, classOrStaffType: row.member.student?.className ?? row.member.staffMember?.staffType ?? "", chargeType: row.chargeType, status: row.status, assessedDate: schoolDateKey(row.assessedDate), originalAmount: row.originalAmount.toFixed(2), waivedAmount: row.waivedAmount.toFixed(2), payableAmount: row.payableAmount.toFixed(2), loanNumber: row.loan?.loanNumber ?? "", incidentNumber: row.incident?.incidentNumber ?? "", receiptNumber: row.miscIncomeReceipt?.receiptNumber ?? "", receiptStatus: row.miscIncomeReceipt?.status ?? "", reconciliationWarning: row.status === "PAID" && row.miscIncomeReceipt?.status === "CANCELLED" ? "Linked receipt cancelled; compensating correction required" : "" }));
  const incidentRows = incidents.map((row) => ({ incidentNumber: row.incidentNumber, type: row.incidentType, status: row.status, borrower: safeMemberLabel(row.member, masked), memberType: row.member.memberType, titleCode: row.title.titleCode, title: row.title.title, accessionNumber: row.copy.accessionNumber, reportedDate: schoolDateKey(row.reportedDate), resolution: row.resolutionType ?? "", replacementAccession: row.replacementCopy?.accessionNumber ?? "", linkedCharges: row.charges.map((charge) => `${charge.chargeNumber} ${charge.status}`).join("; ") }));
  const overdueUnassessed = loans.filter((loan) => deriveOverdue(loan).overdue && loan.charges.length === 0).map((loan) => ({ loanNumber: loan.loanNumber, borrower: safeMemberLabel(loan.member, masked), memberType: loan.member.memberType, title: loan.copy.title.title, accessionNumber: loan.copy.accessionNumber, dueDate: schoolDateKey(loan.dueDate), overdueDays: deriveOverdue(loan).overdueDays }));
  const sum = (key: "originalAmount" | "waivedAmount" | "payableAmount", filter = (_: typeof chargeRows[number]) => true) => charges.filter((_, i) => filter(chargeRows[i])).reduce((total, row) => total.add(row[key]), new Prisma.Decimal(0)).toFixed(2);
  return { summary: { totalCharges: charges.length, originalAmount: sum("originalAmount"), fullWaivers: charges.filter((r) => r.status === "WAIVED").length, fullWaiverAmount: sum("waivedAmount", (r) => r.status === "WAIVED"), partialWaivers: charges.filter((r) => r.waivedAmount.gt(0) && r.status !== "WAIVED").length, partialWaiverAmount: sum("waivedAmount", (r) => Number(r.waivedAmount) > 0 && r.status !== "WAIVED"), payableAmount: sum("payableAmount"), paidAmount: sum("payableAmount", (r) => r.status === "PAID"), unpaidApprovedAmount: sum("payableAmount", (r) => r.status === "APPROVED"), studentCharges: charges.filter((r) => r.studentId).length, staffCharges: charges.filter((r) => r.staffMemberId).length, lostIncidents: incidents.filter((r) => r.incidentType === "LOST").length, damagedIncidents: incidents.filter((r) => r.incidentType === "DAMAGED").length, openIncidents: incidents.filter((r) => !['RESOLVED','CANCELLED'].includes(r.status)).length, receiptWarnings: chargeRows.filter((r) => r.reconciliationWarning).length, overdueUnassessed: overdueUnassessed.length }, charges: chargeRows, incidents: incidentRows, overdueUnassessed };
}

function csv(headers: string[], rows: unknown[][]) { return [headers, ...rows].map((row) => row.map(csvCell).join(",")).join("\r\n") + "\r\n"; }
export function libraryChargeReportCsv(report: Awaited<ReturnType<typeof loadLibraryChargeReports>>, type: typeof LIBRARY_CHARGE_REPORT_TYPES[number]) {
  if (type === "incidents") return csv(["Incident Number","Type","Status","Borrower","Member Type","Title Code","Title","Accession","Reported Date","Resolution","Replacement Accession","Linked Charges"], report.incidents.map(Object.values));
  if (type === "overdue-unassessed") return csv(["Loan Number","Borrower","Member Type","Title","Accession","Due Date","Overdue Days"], report.overdueUnassessed.map(Object.values));
  const rows = type === "receipt-reconciliation" ? report.charges.filter((row) => row.receiptNumber || row.status === "PAID") : report.charges;
  return csv(["Charge Number","Borrower","Member Type","Class or Staff Type","Charge Type","Status","Assessed Date","Original Amount","Waived Amount","Payable Amount","Loan Number","Incident Number","Receipt Number","Receipt Status","Reconciliation Warning"], rows.map(Object.values));
}
export function libraryChargeReportFilename(type: string, date = new Date()) { return `library-accountability-${type}-${schoolDateKey(date)}.csv`; }
