import * as XLSX from "xlsx";
import { strToU8, unzipSync, zipSync } from "fflate";
import {
  ENROLLMENT_HEADERS, GUARDIAN_HEADERS, LINK_HEADERS, ONBOARDING_SCHEMA_VERSION,
  ONBOARDING_SHEETS, ONBOARDING_TEMPLATE_VERSION, STAFF_HEADERS, STAFF_SHEET,
  STUDENT_HEADERS, type OnboardingBundle, type OnboardingWorkbookRows
} from "@/lib/onboarding-types";

const MAX_SHEETS = 14;
const MAX_ROWS_PER_SHEET = 5_000;
const MAX_COLUMNS = 64;
const MAX_CELL_LENGTH = 4_000;
const MAX_ZIP_ENTRIES = 160;
const MAX_UNCOMPRESSED_BYTES = 64 * 1024 * 1024;

export function generateOnboardingTemplate(input: {
  bundle: OnboardingBundle;
  generatedAt?: Date;
  academicYears?: string[];
  classes?: Array<{ academicYear: string; className: string; section: string; displayName?: string }>;
  departments?: string[];
  designations?: string[];
}) {
  const generatedAt = input.generatedAt ?? new Date();
  const wb = XLSX.utils.book_new();
  const includeStaff = input.bundle !== "STUDENT_GUARDIAN";
  const instructions = [
    ["NALANDA PUBLIC SCHOOL"],
    ["Governed Bulk Onboarding Workbook"],
    ["Privacy classification", "PRIVATE - authorised school operators only"],
    ["Mode", "CREATE_AND_LINK. Existing records are never silently overwritten."],
    ["Dates", "Use YYYY-MM-DD or DD/MM/YYYY. Phone numbers must be entered as text."],
    ["Examples", "Rows marked YES in Example Row are instructions only and are excluded from import."],
    ["Accounts", "Parent and Staff account flags create proposals only; no password or active account is created."],
    ["Prohibited data", "Do not add payments, balances, marks, attendance, payroll, Aadhaar, PAN, UAN, medical, bank, coordinates, transport or cafeteria data."],
    ["Languages", "Unicode names are supported, including English, Hindi, Urdu and Telugu."],
    ["Security", "Do not add formulas, macros, links, objects or hidden sheets."]
  ];
  const instructionSheet = XLSX.utils.aoa_to_sheet(instructions);
  instructionSheet.A1.s = { font: { name: "Georgia", bold: true, sz: 16 } };
  instructionSheet["!protect"] = { selectLockedCells: true, selectUnlockedCells: true };
  instructionSheet["!cols"] = [{ wch: 28 }, { wch: 110 }];
  XLSX.utils.book_append_sheet(wb, instructionSheet, "Instructions");

  appendRows(wb, "Template Metadata", [["Key", "Value"], ["Template Version", ONBOARDING_TEMPLATE_VERSION], ["Application Schema Version", ONBOARDING_SCHEMA_VERSION], ["Bundle Type", input.bundle], ["Generated Date", generatedAt.toISOString()], ["Import Mode", "CREATE_AND_LINK"], ["Privacy Classification", "PRIVATE"]], true);
  appendRows(wb, "Academic Years", [["Academic Year", "Status"], ...(input.academicYears ?? []).map((value) => [value, "ACTIVE"]), ["EXAMPLE-ONLY", "EXAMPLE"]], true);
  appendRows(wb, "Classes and Sections", [["Academic Year", "Class", "Section", "Display Name", "Status"], ...(input.classes ?? []).map((row) => [row.academicYear, row.className, row.section, row.displayName ?? `${row.className} ${row.section}`.trim(), "ACTIVE"]), ["EXAMPLE-ONLY", "I", "A", "Class I A", "EXAMPLE"]], true);
  appendEntrySheet(wb, "Students", STUDENT_HEADERS, ["STU-EXAMPLE-001", "NPS-EXAMPLE-001", "Example Student", "Example Guardian", "", "9876543210", "", "2015-01-31", "2026-27", "I", "A", "1", "ACTIVE", "Remove this example row", "YES"]);
  appendEntrySheet(wb, "Guardians", GUARDIAN_HEADERS, ["GUA-EXAMPLE-001", "Example Guardian", "Father", "9876543210", "", "example.invalid@example.invalid", "MOBILE", "NO", "YES"]);
  appendEntrySheet(wb, "Student-Guardian Links", LINK_HEADERS, ["LNK-EXAMPLE-001", "STU-EXAMPLE-001", "GUA-EXAMPLE-001", "Father", "YES", "YES", "YES", "YES"]);
  appendEntrySheet(wb, "Enrollments", ENROLLMENT_HEADERS, ["ENR-EXAMPLE-001", "STU-EXAMPLE-001", "2026-27", "I", "A", "1", "2026-06-01", "ACTIVE", "YES"]);
  if (includeStaff) appendEntrySheet(wb, STAFF_SHEET, STAFF_HEADERS, ["STF-EXAMPLE-001", "EMP-EXAMPLE-001", "Example Staff", "TEACHING", "Teacher", "Academics", "2026-06-01", "example.invalid@example.invalid", "", "9876543210", "TEACHER", "NO", "ACTIVE", "Remove this example row", "YES"]);
  appendRows(wb, "Code Lists", [["List", "Value"], ...codeRows(input)], true);
  appendRows(wb, "Validation Summary", [["Generated by ERP after validation"], ["Do not edit this placeholder."]], true);
  appendRows(wb, "Import Batch Reference", [["Assigned by ERP after upload"], ["Do not edit this placeholder."]], true);
  wb.Workbook = { ...(wb.Workbook ?? {}), WBProps: { ...(wb.Workbook?.WBProps ?? {}), CodeName: undefined } };
  const generated = Buffer.from(XLSX.write(wb, { type: "buffer", bookType: "xlsx", compression: true, cellStyles: true }));
  return hardenGeneratedTemplate(generated, input);
}

export function parseOnboardingWorkbook(bytes: Uint8Array, expectedBundle?: OnboardingBundle): OnboardingWorkbookRows {
  inspectXlsxContainer(bytes);
  const wb = XLSX.read(bytes, { type: "array", raw: true, cellDates: false, cellFormula: true, cellHTML: false, cellNF: false, cellStyles: false, dense: false, WTF: false });
  if (wb.SheetNames.length > MAX_SHEETS) throw new Error("TOO_MANY_SHEETS");
  const expected: string[] = [...ONBOARDING_SHEETS];
  if (expectedBundle && expectedBundle !== "STUDENT_GUARDIAN") expected.push(STAFF_SHEET);
  for (const name of expected) if (!wb.SheetNames.includes(name)) throw new Error(`MISSING_SHEET:${name}`);
  if (expectedBundle === "STUDENT_GUARDIAN" && wb.Sheets[STAFF_SHEET]) throw new Error(`UNEXPECTED_SHEET:${STAFF_SHEET}`);
  const unexpected = wb.SheetNames.filter((name) => ![...ONBOARDING_SHEETS, STAFF_SHEET].includes(name as never));
  if (unexpected.length) throw new Error("UNEXPECTED_SHEET");
  for (const [index, sheetMeta] of (wb.Workbook?.Sheets ?? []).entries()) if (sheetMeta.Hidden) throw new Error(`HIDDEN_SHEET:${wb.SheetNames[index]}`);
  for (const name of wb.SheetNames) assertSheetSafe(wb.Sheets[name], name);
  assertHeaders(wb, "Students", STUDENT_HEADERS);
  assertHeaders(wb, "Guardians", GUARDIAN_HEADERS);
  assertHeaders(wb, "Student-Guardian Links", LINK_HEADERS);
  assertHeaders(wb, "Enrollments", ENROLLMENT_HEADERS);
  if (wb.Sheets[STAFF_SHEET]) assertHeaders(wb, STAFF_SHEET, STAFF_HEADERS);
  const metadata = Object.fromEntries(rows(wb, "Template Metadata").map((row) => [String(row.Key ?? "").trim(), String(row.Value ?? "").trim()]));
  if (metadata["Template Version"] !== ONBOARDING_TEMPLATE_VERSION) throw new Error("TEMPLATE_VERSION_UNSUPPORTED");
  if (metadata["Application Schema Version"] !== ONBOARDING_SCHEMA_VERSION) throw new Error("SCHEMA_VERSION_UNSUPPORTED");
  if (expectedBundle && metadata["Bundle Type"] !== expectedBundle) throw new Error("BUNDLE_TYPE_MISMATCH");
  return {
    metadata,
    students: importRows(wb, "Students"), guardians: importRows(wb, "Guardians"),
    links: importRows(wb, "Student-Guardian Links"), enrollments: importRows(wb, "Enrollments"),
    staff: wb.Sheets[STAFF_SHEET] ? importRows(wb, STAFF_SHEET) : []
  };
}

export function inspectXlsxContainer(bytes: Uint8Array) {
  if (bytes.length < 4 || bytes[0] !== 0x50 || bytes[1] !== 0x4b || bytes[2] !== 0x03 || bytes[3] !== 0x04) throw new Error("XLSX_SIGNATURE_INVALID");
  const entries = centralDirectoryEntries(bytes);
  if (!entries.length || entries.length > MAX_ZIP_ENTRIES) throw new Error("XLSX_ENTRY_COUNT_REFUSED");
  let total = 0;
  for (const entry of entries) {
    if (entry.name.includes("..") || entry.name.startsWith("/") || entry.name.includes("\\")) throw new Error("XLSX_TRAVERSAL_REFUSED");
    total += entry.uncompressed;
    if (entry.uncompressed > MAX_UNCOMPRESSED_BYTES || total > MAX_UNCOMPRESSED_BYTES) throw new Error("XLSX_EXPANSION_REFUSED");
    if (entry.uncompressed > 1024 * 1024 && entry.uncompressed / Math.max(1, entry.compressed) > 100) throw new Error("XLSX_ZIP_BOMB_REFUSED");
    const lower = entry.name.toLowerCase();
    if (lower.endsWith(".bin") || /(?:vbaproject|activex|oleobjects|embeddings|externallinks|customui)/.test(lower)) throw new Error("XLSX_EXECUTABLE_OR_EXTERNAL_CONTENT_REFUSED");
    if (lower === "encryptedpackage" || lower.includes("encryptioninfo")) throw new Error("PASSWORD_PROTECTED_WORKBOOK_REFUSED");
  }
  const unpacked = unzipSync(bytes, { filter: (file) => file.name === "[Content_Types].xml" || file.name === "xl/workbook.xml" || file.name.endsWith(".rels") });
  const contentTypes = decode(unpacked["[Content_Types].xml"]);
  const workbookXml = decode(unpacked["xl/workbook.xml"]);
  if (!contentTypes.includes("spreadsheetml.sheet") || /<Override[^>]+(?:macroenabled|vbaProject)/i.test(contentTypes)) throw new Error("XLSX_CONTENT_TYPE_REFUSED");
  if (Object.entries(unpacked).some(([name, value]) => name.endsWith(".rels") && /TargetMode=["']External["']/i.test(decode(value)))) throw new Error("XLSX_EXTERNAL_LINK_REFUSED");
  const sheetNames = [...workbookXml.matchAll(/<sheet\b[^>]*\bname=(?:"([^"]+)"|'([^']+)')/gi)].map((match) => (match[1] ?? match[2] ?? "").trim().toLocaleLowerCase());
  if (sheetNames.length !== new Set(sheetNames).size) throw new Error("DUPLICATE_SHEET_NAME_REFUSED");
}

function hardenGeneratedTemplate(bytes: Buffer, input: { bundle: OnboardingBundle; departments?: string[]; designations?: string[] }) {
  const files = unzipSync(bytes);
  const contentTypesKey = "[Content_Types].xml";
  files[contentTypesKey] = strToU8(decode(files[contentTypesKey]).replace(/<Default Extension="bin" ContentType="[^"]+"\/>/i, ""));
  applyCoverStyle(files);
  const includeStaff = input.bundle !== "STUDENT_GUARDIAN";
  const codeListSheetNumber = includeStaff ? 10 : 9;
  const protectedSheets = new Set([1, 2, 3, 4, codeListSheetNumber, codeListSheetNumber + 1, codeListSheetNumber + 2]);
  const validations = new Map<number, DataValidation[]>([
    [5, [
      listValidation("I2:I5001", "'Academic Years'!$A$2:$A$501", "Select an approved academic year."),
      listValidation("J2:J5001", "'Classes and Sections'!$B$2:$B$501", "Select an approved class."),
      listValidation("K2:K5001", "'Classes and Sections'!$C$2:$C$501", "Select an approved section."),
      listValidation("M2:M5001", "'Code Lists'!$B$2:$B$3", "Select an approved Student status."),
      listValidation("O2:O5001", '"YES,NO"', "YES marks an example row that is excluded from import.")
    ]],
    [6, [
      listValidation("C2:C5001", "'Code Lists'!$B$8:$B$10", "Select the Guardian relationship."),
      listValidation("G2:G5001", '"MOBILE,EMAIL,WHATSAPP"', "Select the communication preference."),
      listValidation("H2:I5001", '"YES,NO"', "Select YES or NO.")
    ]],
    [7, [
      listValidation("D2:D5001", "'Code Lists'!$B$8:$B$10", "Select the relationship to the Student."),
      listValidation("E2:H5001", '"YES,NO"', "Select YES or NO.")
    ]],
    [8, [
      listValidation("C2:C5001", "'Academic Years'!$A$2:$A$501", "Select an approved academic year."),
      listValidation("D2:D5001", "'Classes and Sections'!$B$2:$B$501", "Select an approved class."),
      listValidation("E2:E5001", "'Classes and Sections'!$C$2:$C$501", "Select an approved section."),
      listValidation("H2:H5001", "'Code Lists'!$B$2:$B$3", "Select an approved enrollment status."),
      listValidation("I2:I5001", '"YES,NO"', "YES marks an example row that is excluded from import.")
    ]]
  ]);
  if (includeStaff) {
    const departmentStart = 13;
    const departmentEnd = Math.max(departmentStart, departmentStart + (input.departments?.length ?? 0) - 1);
    const designationStart = departmentStart + (input.departments?.length ?? 0);
    const designationEnd = Math.max(designationStart, designationStart + (input.designations?.length ?? 0) - 1);
    validations.set(9, [
      listValidation("D2:D5001", "'Code Lists'!$B$6:$B$7", "Select the approved Staff type."),
      ...(input.designations?.length ? [listValidation("E2:E5001", `'Code Lists'!$B$${designationStart}:$B$${designationEnd}`, "Select an approved designation.")] : []),
      ...(input.departments?.length ? [listValidation("F2:F5001", `'Code Lists'!$B$${departmentStart}:$B$${departmentEnd}`, "Select an approved department.")] : []),
      listValidation("K2:K5001", '"TEACHER,VIEWER,ACCOUNTANT,COMPUTER_OPERATOR"', "This is a proposal only; IAM approval remains separate."),
      listValidation("L2:L5001", '"YES,NO"', "Select whether to propose a portal account."),
      listValidation("M2:M5001", "'Code Lists'!$B$4:$B$5", "Select the employment status."),
      listValidation("O2:O5001", '"YES,NO"', "YES marks an example row that is excluded from import.")
    ]);
  }
  for (let sheetNumber = 1; sheetNumber <= codeListSheetNumber + 2; sheetNumber += 1) {
    const key = `xl/worksheets/sheet${sheetNumber}.xml`;
    if (!files[key]) throw new Error(`GENERATED_TEMPLATE_SHEET_MISSING:${sheetNumber}`);
    let xml = decode(files[key]);
    const protection = protectedSheets.has(sheetNumber) && !/<sheetProtection\b/i.test(xml)
      ? '<sheetProtection sheet="1" objects="1" scenarios="1" password="D1A7"/>'
      : "";
    const dataValidationXml = validationXml(validations.get(sheetNumber) ?? []);
    if (protection || dataValidationXml) xml = xml.replace("</sheetData>", `</sheetData>${protection}${dataValidationXml}`);
    files[key] = strToU8(xml);
  }
  return Buffer.from(zipSync(files, { level: 6 }));
}

function applyCoverStyle(files: Record<string, Uint8Array>) {
  const stylesKey = "xl/styles.xml";
  let styles = decode(files[stylesKey]);
  styles = styles.replace(/<fonts count="(\d+)">/, (_match, count) => `<fonts count="${Number(count) + 1}">`);
  styles = styles.replace("</fonts>", '<font><name val="Georgia"/><sz val="16"/><b/><family val="1"/></font></fonts>');
  styles = styles.replace(/<cellXfs count="(\d+)">/, (_match, count) => `<cellXfs count="${Number(count) + 1}">`);
  styles = styles.replace("</cellXfs>", '<xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs>');
  files[stylesKey] = strToU8(styles);
  const coverKey = "xl/worksheets/sheet1.xml";
  files[coverKey] = strToU8(decode(files[coverKey]).replace(/<c r="A1"(?: s="\d+")?/, '<c r="A1" s="1"'));
}

type DataValidation = { sqref: string; formula: string; prompt: string };
function listValidation(sqref: string, formula: string, prompt: string): DataValidation { return { sqref, formula, prompt }; }
function validationXml(items: DataValidation[]) {
  if (!items.length) return "";
  const body = items.map((item) => `<dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" errorStyle="stop" errorTitle="Invalid value" error="Select a value from the approved list." promptTitle="Governed onboarding" prompt="${escapeXml(item.prompt)}" sqref="${escapeXml(item.sqref)}"><formula1>${escapeXml(item.formula)}</formula1></dataValidation>`).join("");
  return `<dataValidations count="${items.length}">${body}</dataValidations>`;
}
function escapeXml(value: string) { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&apos;"); }

function centralDirectoryEntries(bytes: Uint8Array) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength); const entries: Array<{name:string;compressed:number;uncompressed:number}> = [];
  for (let offset = 0; offset + 46 <= bytes.length;) {
    const signature = view.getUint32(offset, true);
    if (signature === 0x02014b50) {
      const compressed = view.getUint32(offset + 20, true), uncompressed = view.getUint32(offset + 24, true);
      const nameLength = view.getUint16(offset + 28, true), extraLength = view.getUint16(offset + 30, true), commentLength = view.getUint16(offset + 32, true);
      const end = offset + 46 + nameLength + extraLength + commentLength; if (end > bytes.length) throw new Error("XLSX_CENTRAL_DIRECTORY_INVALID");
      entries.push({ name: new TextDecoder().decode(bytes.subarray(offset + 46, offset + 46 + nameLength)), compressed, uncompressed }); offset = end; continue;
    }
    offset += 1;
  }
  return entries;
}

function assertSheetSafe(sheet: XLSX.WorkSheet, name: string) {
  const range = sheet["!ref"] ? XLSX.utils.decode_range(sheet["!ref"]) : null;
  if (range && range.e.r - range.s.r > MAX_ROWS_PER_SHEET) throw new Error(`TOO_MANY_ROWS:${name}`);
  if (range && range.e.c - range.s.c + 1 > MAX_COLUMNS) throw new Error(`TOO_MANY_COLUMNS:${name}`);
  for (const [address, cell] of Object.entries(sheet)) {
    if (address.startsWith("!")) continue;
    const value = cell as XLSX.CellObject;
    if (value.f) throw new Error(`FORMULA_CELL_REFUSED:${name}:${address}`);
    const submitted = String(value.v ?? "");
    if (submitted.length > MAX_CELL_LENGTH) throw new Error(`CELL_TOO_LONG:${name}:${address}`);
    if (/^[\s\u0000-\u001f]*[=+\-@]/.test(submitted)) throw new Error(`FORMULA_INJECTION_REFUSED:${name}:${address}`);
  }
}
function assertHeaders(wb: XLSX.WorkBook, name: string, expected: string[]) {
  const first = XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[name], { header: 1, defval: "", raw: true, blankrows: false })[0] ?? [];
  const actual = first.map((value) => String(value ?? "").trim());
  if (actual.length !== expected.length || actual.some((value, index) => value !== expected[index])) throw new Error(`HEADER_SCHEMA_MISMATCH:${name}`);
}
function rows(wb: XLSX.WorkBook, name: string) { return XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets[name], { defval: "", raw: true }); }
function importRows(wb: XLSX.WorkBook, name: string) { return rows(wb, name).filter((row) => String(row["Example Row"] ?? "").trim().toUpperCase() !== "YES" && Object.values(row).some((value) => String(value ?? "").trim())); }
function appendRows(wb: XLSX.WorkBook, name: string, data: unknown[][], protect: boolean) { const sheet = XLSX.utils.aoa_to_sheet(data); sheet["!cols"] = data[0]?.map(() => ({ wch: 26 })) ?? []; if (protect) sheet["!protect"] = {}; XLSX.utils.book_append_sheet(wb, sheet, name); }
function appendEntrySheet(wb: XLSX.WorkBook, name: string, headers: string[], sample: unknown[]) { const sheet = XLSX.utils.aoa_to_sheet([headers, sample]); sheet["!cols"] = headers.map((header) => ({ wch: Math.min(32, Math.max(14, header.length + 3)) })); sheet["!autofilter"] = { ref: `A1:${XLSX.utils.encode_col(headers.length - 1)}1` }; XLSX.utils.book_append_sheet(wb, sheet, name); }
function codeRows(input: { departments?: string[]; designations?: string[] }) { return [["Student Status", "ACTIVE"], ["Student Status", "INACTIVE"], ["Employment Status", "ACTIVE"], ["Employment Status", "INACTIVE"], ["Staff Type", "TEACHING"], ["Staff Type", "NON_TEACHING"], ["Relationship", "Mother"], ["Relationship", "Father"], ["Relationship", "Guardian"], ["Boolean", "YES"], ["Boolean", "NO"], ...[...(input.departments ?? [])].map((v) => ["Department", v]), ...[...(input.designations ?? [])].map((v) => ["Designation", v])]; }
function decode(value?: Uint8Array) { return value ? new TextDecoder().decode(value) : ""; }
