import type { PrismaClient } from "@prisma/client";

export const OPTIONAL_OPERATIONS_BACKUP_KEYS = [
  "transportVehicles", "transportRoutes", "transportStops", "transportRouteStops", "transportStudentAssignments", "transportAuditEvents",
  "cafeteriaCatalogItems", "cafeteriaMenus", "cafeteriaMenuItems", "cafeteriaStudentEnrollments", "cafeteriaMealRecords", "cafeteriaAuditEvents"
] as const;
export type OptionalOperationsBackupKey = typeof OPTIONAL_OPERATIONS_BACKUP_KEYS[number];
export type OptionalOperationsBackup = Record<OptionalOperationsBackupKey, Record<string, unknown>[]>;
export type OptionalOperationsRestoreResult = Record<OptionalOperationsBackupKey,{created:number;updated:number;skipped:number;errors:string[]}>;

const ALLOWED:Record<OptionalOperationsBackupKey,ReadonlySet<string>>={
  transportVehicles:new Set(["id","publicKey","registrationCode","displayName","capacity","status","version","createdAt","updatedAt"]),
  transportRoutes:new Set(["id","publicKey","code","name","directionMode","vehicleId","driverStaffMemberId","attendantStaffMemberId","capacity","allocatedSeats","status","version","createdAt","updatedAt"]),
  transportStops:new Set(["id","publicKey","code","name","approvedReference","active","version","createdAt","updatedAt"]),
  transportRouteStops:new Set(["id","publicKey","routeId","stopId","direction","sequence","timingReference","active","version","createdAt","updatedAt"]),
  transportStudentAssignments:new Set(["id","publicKey","studentId","activeStudentId","routeId","pickupRouteStopId","dropRouteStopId","routeCodeSnapshot","routeNameSnapshot","pickupStopSnapshot","pickupTimingSnapshot","dropStopSnapshot","dropTimingSnapshot","effectiveFrom","effectiveTo","active","version","changeReason","replacesAssignmentId","createdByRole","createdAt","updatedAt"]),
  transportAuditEvents:new Set(["id","publicKey","eventType","entityType","entityPublicKey","actorRole","safeMetadataJson","occurredAt"]),
  cafeteriaCatalogItems:new Set(["id","publicKey","code","name","category","available","status","version","createdAt","updatedAt"]),
  cafeteriaMenus:new Set(["id","publicKey","menuDate","dayLabel","mealPlanName","status","version","createdAt","updatedAt"]),
  cafeteriaMenuItems:new Set(["id","publicKey","menuId","itemId","mealSlot","available","createdAt"]),
  cafeteriaStudentEnrollments:new Set(["id","publicKey","studentId","activeStudentId","mealPlanName","effectiveFrom","effectiveTo","active","version","changeReason","replacesEnrollmentId","createdByRole","createdAt","updatedAt"]),
  cafeteriaMealRecords:new Set(["id","publicKey","studentId","enrollmentId","menuItemId","serviceDateKey","mealSlot","recordType","status","idempotencyKey","recordedByRole","recordedAt","createdAt"]),
  cafeteriaAuditEvents:new Set(["id","publicKey","eventType","entityType","entityPublicKey","actorRole","safeMetadataJson","occurredAt"])
};
const REQUIRED:Record<OptionalOperationsBackupKey,readonly string[]>={
  transportVehicles:["publicKey","registrationCode","displayName","capacity","status"],transportRoutes:["publicKey","code","name","vehicleId","capacity","status"],transportStops:["publicKey","code","name"],transportRouteStops:["publicKey","routeId","stopId","direction","sequence"],transportStudentAssignments:["publicKey","studentId","routeId","pickupRouteStopId","dropRouteStopId","routeCodeSnapshot","routeNameSnapshot","pickupStopSnapshot","dropStopSnapshot","effectiveFrom","changeReason"],transportAuditEvents:["publicKey","eventType","entityType","entityPublicKey"],cafeteriaCatalogItems:["publicKey","code","name","category"],cafeteriaMenus:["publicKey","menuDate","dayLabel","mealPlanName"],cafeteriaMenuItems:["publicKey","menuId","itemId","mealSlot"],cafeteriaStudentEnrollments:["publicKey","studentId","effectiveFrom","changeReason"],cafeteriaMealRecords:["publicKey","studentId","enrollmentId","menuItemId","serviceDateKey","mealSlot","recordType","idempotencyKey"],cafeteriaAuditEvents:["publicKey","eventType","entityType","entityPublicKey"]
};

function safeRows(value:unknown,key:OptionalOperationsBackupKey){if(value==null)return[];if(!Array.isArray(value))throw new Error(`${key} must be an array`);return value.map((item,index)=>{if(!item||typeof item!=="object"||Array.isArray(item))throw new Error(`${key}[${index}] must be an object`);const row=item as Record<string,unknown>,unknown=Object.keys(row).filter((field)=>!ALLOWED[key].has(field));if(unknown.length)throw new Error(`${key}[${index}] contains unsupported fields: ${unknown.join(", ")}`);for(const field of REQUIRED[key])if(row[field]===undefined||row[field]===null||row[field]==="")throw new Error(`${key}[${index}].${field} is required`);return{...row};});}
export function emptyOptionalOperationsBackup():OptionalOperationsBackup{return Object.fromEntries(OPTIONAL_OPERATIONS_BACKUP_KEYS.map((key)=>[key,[]])) as unknown as OptionalOperationsBackup;}
export function validateOptionalOperationsBackupRows(root:Record<string,unknown>):OptionalOperationsBackup{return Object.fromEntries(OPTIONAL_OPERATIONS_BACKUP_KEYS.map((key)=>[key,safeRows(root[key],key)])) as unknown as OptionalOperationsBackup;}
export async function optionalOperationsSchemaAvailable(client:any){try{const rows=await client.$queryRawUnsafe("SELECT name FROM sqlite_master WHERE type='table' AND name='TransportVehicle'");return Array.isArray(rows)&&rows.length===1;}catch{return false;}}
export async function loadOptionalOperationsBackup(client:any):Promise<OptionalOperationsBackup>{if(!await optionalOperationsSchemaAvailable(client))return emptyOptionalOperationsBackup();const [transportVehicles,transportRoutes,transportStops,transportRouteStops,transportStudentAssignmentsRaw,transportAuditEventsRaw,cafeteriaCatalogItems,cafeteriaMenus,cafeteriaMenuItems,cafeteriaStudentEnrollmentsRaw,cafeteriaMealRecordsRaw,cafeteriaAuditEventsRaw]=await Promise.all([
  client.transportVehicle.findMany({orderBy:{createdAt:"asc"}}),client.transportRoute.findMany({orderBy:{createdAt:"asc"}}),client.transportStop.findMany({orderBy:{createdAt:"asc"}}),client.transportRouteStop.findMany({orderBy:{createdAt:"asc"}}),client.transportStudentAssignment.findMany({orderBy:{createdAt:"asc"}}),client.transportAuditEvent.findMany({orderBy:{occurredAt:"asc"}}),client.cafeteriaCatalogItem.findMany({orderBy:{createdAt:"asc"}}),client.cafeteriaMenu.findMany({orderBy:{createdAt:"asc"}}),client.cafeteriaMenuItem.findMany({orderBy:{createdAt:"asc"}}),client.cafeteriaStudentEnrollment.findMany({orderBy:{createdAt:"asc"}}),client.cafeteriaMealRecord.findMany({orderBy:{recordedAt:"asc"}}),client.cafeteriaAuditEvent.findMany({orderBy:{occurredAt:"asc"}})
]);const omit=(rows:any[],fields:string[])=>rows.map((row)=>Object.fromEntries(Object.entries(row).filter(([key])=>!fields.includes(key))));return validateOptionalOperationsBackupRows({transportVehicles,transportRoutes,transportStops,transportRouteStops,transportStudentAssignments:omit(transportStudentAssignmentsRaw,["createdByUserId"]),transportAuditEvents:omit(transportAuditEventsRaw,["actorUserId"]),cafeteriaCatalogItems,cafeteriaMenus,cafeteriaMenuItems,cafeteriaStudentEnrollments:omit(cafeteriaStudentEnrollmentsRaw,["createdByUserId"]),cafeteriaMealRecords:omit(cafeteriaMealRecordsRaw,["recordedByUserId"]),cafeteriaAuditEvents:omit(cafeteriaAuditEventsRaw,["actorUserId"])});}

const date=(value:unknown)=>new Date(String(value));const number=(value:unknown,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;const string=(value:unknown)=>String(value??"");const nullable=(value:unknown)=>value==null||value===""?null:String(value);
export async function restoreOptionalOperationsBackup(client:PrismaClient|any,backup:OptionalOperationsBackup&{students?:Record<string,unknown>[];staffMembers?:Record<string,unknown>[]},restoredBy:{id:string}):Promise<OptionalOperationsRestoreResult>{const result=Object.fromEntries(OPTIONAL_OPERATIONS_BACKUP_KEYS.map((key)=>[key,{created:0,updated:0,skipped:0,errors:[]}])) as unknown as OptionalOperationsRestoreResult;if(!await optionalOperationsSchemaAvailable(client)){for(const key of OPTIONAL_OPERATIONS_BACKUP_KEYS)if(backup[key].length)result[key].errors.push("Optional Operations schema is unavailable.");return result;}const create=async(key:OptionalOperationsBackupKey,rows:Record<string,unknown>[],fn:(row:Record<string,unknown>)=>Promise<boolean>)=>{for(const[index,row]of rows.entries())try{if(await fn(row))result[key].created++;else result[key].skipped++;}catch(error){result[key].errors.push(`${key}[${index}]: ${error instanceof Error?error.message:"restore failed"}`);}};
  const studentMap=new Map<string,string>();for(const row of backup.students??[]){const local=await client.student.findUnique({where:{admissionNo:string(row.admissionNo)},select:{id:true}});if(local&&row.id)studentMap.set(string(row.id),local.id);}const staffMap=new Map<string,string>();for(const row of backup.staffMembers??[]){if(!row.staffCode||!row.id)continue;const local=await client.staffMember.findUnique({where:{staffCode:string(row.staffCode)},select:{id:true}});if(local)staffMap.set(string(row.id),local.id);}
  const vehicleMap=new Map<string,string>();await create("transportVehicles",backup.transportVehicles,async row=>{const existing=await client.transportVehicle.findUnique({where:{registrationCode:string(row.registrationCode)}});if(existing){vehicleMap.set(string(row.id),existing.id);return false;}const created=await client.transportVehicle.create({data:{publicKey:string(row.publicKey),registrationCode:string(row.registrationCode),displayName:string(row.displayName),capacity:number(row.capacity,1),status:string(row.status),version:number(row.version,1),createdAt:date(row.createdAt)}});vehicleMap.set(string(row.id),created.id);return true;});
  const routeMap=new Map<string,string>();await create("transportRoutes",backup.transportRoutes,async row=>{const existing=await client.transportRoute.findUnique({where:{code:string(row.code)}});if(existing){routeMap.set(string(row.id),existing.id);return false;}const vehicleId=vehicleMap.get(string(row.vehicleId));if(!vehicleId)throw new Error("vehicle link unavailable");const created=await client.transportRoute.create({data:{publicKey:string(row.publicKey),code:string(row.code),name:string(row.name),directionMode:string(row.directionMode||"BOTH"),vehicleId,driverStaffMemberId:nullable(row.driverStaffMemberId)?staffMap.get(string(row.driverStaffMemberId))??null:null,attendantStaffMemberId:nullable(row.attendantStaffMemberId)?staffMap.get(string(row.attendantStaffMemberId))??null:null,capacity:number(row.capacity,1),allocatedSeats:number(row.allocatedSeats),status:string(row.status),version:number(row.version,1),createdAt:date(row.createdAt)}});routeMap.set(string(row.id),created.id);return true;});
  const stopMap=new Map<string,string>();await create("transportStops",backup.transportStops,async row=>{const existing=await client.transportStop.findUnique({where:{code:string(row.code)}});if(existing){stopMap.set(string(row.id),existing.id);return false;}const created=await client.transportStop.create({data:{publicKey:string(row.publicKey),code:string(row.code),name:string(row.name),approvedReference:nullable(row.approvedReference),active:row.active!==false,version:number(row.version,1),createdAt:date(row.createdAt)}});stopMap.set(string(row.id),created.id);return true;});
  const routeStopMap=new Map<string,string>();await create("transportRouteStops",backup.transportRouteStops,async row=>{const existing=await client.transportRouteStop.findUnique({where:{publicKey:string(row.publicKey)}});if(existing){routeStopMap.set(string(row.id),existing.id);return false;}const routeId=routeMap.get(string(row.routeId)),stopId=stopMap.get(string(row.stopId));if(!routeId||!stopId)throw new Error("route or stop link unavailable");const created=await client.transportRouteStop.create({data:{publicKey:string(row.publicKey),routeId,stopId,direction:string(row.direction),sequence:number(row.sequence,1),timingReference:nullable(row.timingReference),active:row.active!==false,version:number(row.version,1),createdAt:date(row.createdAt)}});routeStopMap.set(string(row.id),created.id);return true;});
  const assignmentMap=new Map<string,string>();await create("transportStudentAssignments",backup.transportStudentAssignments,async row=>{const existing=await client.transportStudentAssignment.findUnique({where:{publicKey:string(row.publicKey)}});if(existing){assignmentMap.set(string(row.id),existing.id);return false;}const studentId=studentMap.get(string(row.studentId)),routeId=routeMap.get(string(row.routeId)),pickupRouteStopId=routeStopMap.get(string(row.pickupRouteStopId)),dropRouteStopId=routeStopMap.get(string(row.dropRouteStopId));if(!studentId||!routeId||!pickupRouteStopId||!dropRouteStopId)throw new Error("Student, route or stop link unavailable");const[pickup,drop]=await Promise.all([client.transportRouteStop.findUnique({where:{id:pickupRouteStopId},select:{routeId:true,direction:true}}),client.transportRouteStop.findUnique({where:{id:dropRouteStopId},select:{routeId:true,direction:true}})]);if(!pickup||pickup.routeId!==routeId||pickup.direction!=="MORNING")throw new Error("pickup stop does not belong to the restored route and morning direction");if(!drop||drop.routeId!==routeId||drop.direction!=="EVENING")throw new Error("drop stop does not belong to the restored route and evening direction");const created=await client.transportStudentAssignment.create({data:{publicKey:string(row.publicKey),studentId,activeStudentId:row.active===false?null:studentId,routeId,pickupRouteStopId,dropRouteStopId,routeCodeSnapshot:string(row.routeCodeSnapshot),routeNameSnapshot:string(row.routeNameSnapshot),pickupStopSnapshot:string(row.pickupStopSnapshot),pickupTimingSnapshot:nullable(row.pickupTimingSnapshot),dropStopSnapshot:string(row.dropStopSnapshot),dropTimingSnapshot:nullable(row.dropTimingSnapshot),effectiveFrom:date(row.effectiveFrom),effectiveTo:row.effectiveTo?date(row.effectiveTo):null,active:row.active!==false,version:number(row.version,1),changeReason:string(row.changeReason),replacesAssignmentId:row.replacesAssignmentId?assignmentMap.get(string(row.replacesAssignmentId))??null:null,createdByUserId:restoredBy.id,createdByRole:string(row.createdByRole||"RESTORE"),createdAt:date(row.createdAt)}});assignmentMap.set(string(row.id),created.id);return true;});
  await create("transportAuditEvents",backup.transportAuditEvents,async row=>{if(await client.transportAuditEvent.findUnique({where:{publicKey:string(row.publicKey)}}))return false;await client.transportAuditEvent.create({data:{publicKey:string(row.publicKey),eventType:string(row.eventType),entityType:string(row.entityType),entityPublicKey:string(row.entityPublicKey),actorUserId:restoredBy.id,actorRole:string(row.actorRole||"RESTORE"),safeMetadataJson:nullable(row.safeMetadataJson),occurredAt:date(row.occurredAt)}});return true;});
  const catalogMap=new Map<string,string>();await create("cafeteriaCatalogItems",backup.cafeteriaCatalogItems,async row=>{const existing=await client.cafeteriaCatalogItem.findUnique({where:{code:string(row.code)}});if(existing){catalogMap.set(string(row.id),existing.id);return false;}const created=await client.cafeteriaCatalogItem.create({data:{publicKey:string(row.publicKey),code:string(row.code),name:string(row.name),category:string(row.category),available:row.available!==false,status:string(row.status||"ACTIVE"),version:number(row.version,1),createdAt:date(row.createdAt)}});catalogMap.set(string(row.id),created.id);return true;});
  const menuMap=new Map<string,string>();await create("cafeteriaMenus",backup.cafeteriaMenus,async row=>{const existing=await client.cafeteriaMenu.findUnique({where:{publicKey:string(row.publicKey)}});if(existing){menuMap.set(string(row.id),existing.id);return false;}const created=await client.cafeteriaMenu.create({data:{publicKey:string(row.publicKey),menuDate:date(row.menuDate),dayLabel:string(row.dayLabel),mealPlanName:string(row.mealPlanName||"STANDARD"),status:string(row.status||"ACTIVE"),version:number(row.version,1),createdAt:date(row.createdAt)}});menuMap.set(string(row.id),created.id);return true;});
  const menuItemMap=new Map<string,string>();await create("cafeteriaMenuItems",backup.cafeteriaMenuItems,async row=>{const existing=await client.cafeteriaMenuItem.findUnique({where:{publicKey:string(row.publicKey)}});if(existing){menuItemMap.set(string(row.id),existing.id);return false;}const menuId=menuMap.get(string(row.menuId)),itemId=catalogMap.get(string(row.itemId));if(!menuId||!itemId)throw new Error("menu or catalog link unavailable");const created=await client.cafeteriaMenuItem.create({data:{publicKey:string(row.publicKey),menuId,itemId,mealSlot:string(row.mealSlot),available:row.available!==false,createdAt:date(row.createdAt)}});menuItemMap.set(string(row.id),created.id);return true;});
  const enrollmentMap=new Map<string,string>();await create("cafeteriaStudentEnrollments",backup.cafeteriaStudentEnrollments,async row=>{const existing=await client.cafeteriaStudentEnrollment.findUnique({where:{publicKey:string(row.publicKey)}});if(existing){enrollmentMap.set(string(row.id),existing.id);return false;}const studentId=studentMap.get(string(row.studentId));if(!studentId)throw new Error("Student link unavailable");const created=await client.cafeteriaStudentEnrollment.create({data:{publicKey:string(row.publicKey),studentId,activeStudentId:row.active===false?null:studentId,mealPlanName:nullable(row.mealPlanName),effectiveFrom:date(row.effectiveFrom),effectiveTo:row.effectiveTo?date(row.effectiveTo):null,active:row.active!==false,version:number(row.version,1),changeReason:string(row.changeReason),replacesEnrollmentId:row.replacesEnrollmentId?enrollmentMap.get(string(row.replacesEnrollmentId))??null:null,createdByUserId:restoredBy.id,createdByRole:string(row.createdByRole||"RESTORE"),createdAt:date(row.createdAt)}});enrollmentMap.set(string(row.id),created.id);return true;});
  await create("cafeteriaMealRecords",backup.cafeteriaMealRecords,async row=>{if(await client.cafeteriaMealRecord.findUnique({where:{publicKey:string(row.publicKey)}}))return false;const studentId=studentMap.get(string(row.studentId)),enrollmentId=enrollmentMap.get(string(row.enrollmentId)),menuItemId=menuItemMap.get(string(row.menuItemId));if(!studentId||!enrollmentId||!menuItemId)throw new Error("Student, enrollment or menu link unavailable");const[enrollment,menuItem]=await Promise.all([client.cafeteriaStudentEnrollment.findUnique({where:{id:enrollmentId},select:{studentId:true,mealPlanName:true,effectiveFrom:true,effectiveTo:true}}),client.cafeteriaMenuItem.findUnique({where:{id:menuItemId},select:{mealSlot:true,menu:{select:{menuDate:true,mealPlanName:true}}}})]);const serviceDateKey=string(row.serviceDateKey),serviceDate=date(serviceDateKey);if(!enrollment||enrollment.studentId!==studentId||enrollment.effectiveFrom>serviceDate||enrollment.effectiveTo&&enrollment.effectiveTo<serviceDate)throw new Error("enrollment does not belong to the restored Student and service date");if(!menuItem||menuItem.mealSlot!==string(row.mealSlot)||menuItem.menu.menuDate.toISOString().slice(0,10)!==serviceDateKey||menuItem.menu.mealPlanName!==enrollment.mealPlanName)throw new Error("menu item does not match the restored date, slot and meal plan");await client.cafeteriaMealRecord.create({data:{publicKey:string(row.publicKey),studentId,enrollmentId,menuItemId,serviceDateKey,mealSlot:string(row.mealSlot),recordType:string(row.recordType),status:string(row.status||"RECORDED"),idempotencyKey:string(row.idempotencyKey),recordedByUserId:restoredBy.id,recordedByRole:string(row.recordedByRole||"RESTORE"),recordedAt:date(row.recordedAt),createdAt:date(row.createdAt)}});return true;});
  await create("cafeteriaAuditEvents",backup.cafeteriaAuditEvents,async row=>{if(await client.cafeteriaAuditEvent.findUnique({where:{publicKey:string(row.publicKey)}}))return false;await client.cafeteriaAuditEvent.create({data:{publicKey:string(row.publicKey),eventType:string(row.eventType),entityType:string(row.entityType),entityPublicKey:string(row.entityPublicKey),actorUserId:restoredBy.id,actorRole:string(row.actorRole||"RESTORE"),safeMetadataJson:nullable(row.safeMetadataJson),occurredAt:date(row.occurredAt)}});return true;});return result;}
