import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { PrismaClient } from "@prisma/client";
import { unzipSync, zipSync } from "fflate";
import { decryptCloudBackup, encryptCloudBackup } from "@/lib/cloud-backup-container";
import { PAYSLIP_PDF_MAX_BYTES } from "@/lib/payslip-request-pdf";
import { readPayslipStoredBackupBytes } from "@/lib/payslip-request-storage";

const MANIFEST_NAME = "manifest.json", MAX_DOCUMENTS = 5_000, MAX_TOTAL_BYTES = 500 * 1024 * 1024;
type AssetManifest = { format: "NALANDA_PAYSLIP_REQUEST_ASSETS_V1"; createdAt: string; documents: Array<{ documentPublicKey: string; requestPublicKey: string; versionNumber: number; sourceEntry: string; sourceCiphertextSha256: string; sourcePlainSha256: string; derivativeEntry: string; derivativeSha256: string; pageCount: number }> };
export class PayslipRequestAssetBackupError extends Error {}

export async function createAndVerifyPayslipRequestAssetBackup(client: PrismaClient, input: { artifactPath: string; key: Buffer; keyVersion: string; restoreRoots: [string, string]; documentPublicKeys?: string[]; createdAt?: Date }) {
  if (input.key.length !== 32) throw new PayslipRequestAssetBackupError("Payslip asset backup requires a 32-byte encryption key.");
  const requested = [...new Set(input.documentPublicKeys ?? [])]; if (requested.length > MAX_DOCUMENTS) throw new PayslipRequestAssetBackupError("Payslip asset backup exceeds the bounded document count.");
  const documents = await client.staffPayslipDocumentVersion.findMany({ where: requested.length ? { publicKey: { in: requested } } : undefined, include: { request: { select: { publicKey: true } } }, orderBy: { publicKey: "asc" }, take: MAX_DOCUMENTS + 1 });
  if (documents.length > MAX_DOCUMENTS || (requested.length && documents.length !== requested.length)) throw new PayslipRequestAssetBackupError("Payslip asset backup selection is invalid or incomplete.");
  const createdAt = input.createdAt ?? new Date(), entries: Record<string, Uint8Array> = {}, manifest: AssetManifest = { format: "NALANDA_PAYSLIP_REQUEST_ASSETS_V1", createdAt: createdAt.toISOString(), documents: [] }; let totalBytes = 0;
  for (const document of documents) { const [source, derivative] = await Promise.all([readPayslipStoredBackupBytes(document.sourceStorageKey, PAYSLIP_PDF_MAX_BYTES + 1024), readPayslipStoredBackupBytes(document.derivativeStorageKey, PAYSLIP_PDF_MAX_BYTES + 2 * 1024 * 1024)]); if (sha256(derivative) !== document.derivativeSha256) throw new PayslipRequestAssetBackupError("A protected payslip failed SHA-256 verification during backup."); totalBytes += source.length + derivative.length; if (totalBytes > MAX_TOTAL_BYTES) throw new PayslipRequestAssetBackupError("Payslip asset backup exceeds the bounded byte limit."); entries[document.sourceStorageKey] = source; entries[document.derivativeStorageKey] = derivative; manifest.documents.push({ documentPublicKey: document.publicKey, requestPublicKey: document.request.publicKey, versionNumber: document.versionNumber, sourceEntry: document.sourceStorageKey, sourceCiphertextSha256: sha256(source), sourcePlainSha256: document.sourceSha256, derivativeEntry: document.derivativeStorageKey, derivativeSha256: document.derivativeSha256, pageCount: document.pageCount }); }
  entries[MANIFEST_NAME] = Buffer.from(JSON.stringify(manifest), "utf8"); const encrypted = await encryptCloudBackup(Buffer.from(zipSync(entries, { level: 9 })), { backupFormatVersion: 37, createdAt, encryptionKeyVersion: input.keyVersion, key: input.key }); await mkdir(path.dirname(path.resolve(input.artifactPath)), { recursive: true }); await writeFile(input.artifactPath, encrypted.bytes, { flag: "wx", mode: 0o600 }); const persisted = await readFile(input.artifactPath);
  const firstRestore = await restorePayslipRequestAssetBackup(persisted, { key: input.key, targetRoot: input.restoreRoots[0] }), secondRestore = await restorePayslipRequestAssetBackup(persisted, { key: input.key, targetRoot: input.restoreRoots[1] });
  if (firstRestore.assetDigest !== secondRestore.assetDigest || firstRestore.linkDigest !== secondRestore.linkDigest || firstRestore.documentCount !== documents.length) throw new PayslipRequestAssetBackupError("The two isolated payslip-document restores do not match.");
  return { artifactSha256: sha256(persisted), documentCount: documents.length, totalBytes, encryptedBytes: persisted.length, firstRestore, secondRestore };
}

export async function restorePayslipRequestAssetBackup(container: Buffer, input: { key: Buffer; targetRoot: string }) {
  const decrypted = await decryptCloudBackup(container, { key: input.key, maximumPlaintextBytes: MAX_TOTAL_BYTES + 20 * 1024 * 1024 }); let archive: Record<string, Uint8Array>; try { archive = unzipSync(decrypted.plaintext); } catch { throw new PayslipRequestAssetBackupError("The decrypted payslip asset archive is malformed."); }
  const manifestBytes = archive[MANIFEST_NAME]; if (!manifestBytes) throw new PayslipRequestAssetBackupError("The encrypted payslip asset manifest is missing."); let manifest: AssetManifest; try { manifest = JSON.parse(Buffer.from(manifestBytes).toString("utf8")); } catch { throw new PayslipRequestAssetBackupError("The encrypted payslip asset manifest is invalid."); } validateManifest(manifest, archive);
  const root = path.resolve(input.targetRoot), stat = await lstat(root).catch(() => null); if (stat?.isSymbolicLink() || (stat && !stat.isDirectory())) throw new PayslipRequestAssetBackupError("The isolated payslip restore target is unsafe."); await mkdir(root, { recursive: true }); const assetDigest = createHash("sha256"), linkDigest = createHash("sha256"); let idempotent = true;
  for (const document of manifest.documents) { for (const [entry, expected] of [[document.sourceEntry, document.sourceCiphertextSha256], [document.derivativeEntry, document.derivativeSha256]] as const) { const bytes = Buffer.from(archive[entry]); if (sha256(bytes) !== expected) throw new PayslipRequestAssetBackupError("A restored payslip asset failed exact SHA-256 verification."); const target = safePath(root, entry); await mkdir(path.dirname(target), { recursive: true }); const current = await readFile(target).catch(() => null); if (current) { if (sha256(current) !== expected) throw new PayslipRequestAssetBackupError("The isolated payslip restore target contains a conflicting asset."); } else { await writeFile(target, bytes, { flag: "wx", mode: 0o600 }); idempotent = false; } assetDigest.update(entry).update(expected); } linkDigest.update(document.documentPublicKey).update(document.requestPublicKey).update(String(document.versionNumber)).update(document.sourcePlainSha256).update(document.derivativeSha256).update(String(document.pageCount)); }
  return { documentCount: manifest.documents.length, manifestSha256: sha256(manifestBytes), assetDigest: assetDigest.digest("hex"), linkDigest: linkDigest.digest("hex"), idempotent };
}

function validateManifest(manifest: AssetManifest, archive: Record<string, Uint8Array>) { if (!manifest || manifest.format !== "NALANDA_PAYSLIP_REQUEST_ASSETS_V1" || !Array.isArray(manifest.documents) || manifest.documents.length > MAX_DOCUMENTS || new Date(manifest.createdAt).toISOString() !== manifest.createdAt) throw new PayslipRequestAssetBackupError("The encrypted payslip asset manifest is unsupported."); const expected = [MANIFEST_NAME, ...manifest.documents.flatMap((row) => [row.sourceEntry, row.derivativeEntry])].sort(), actual = Object.keys(archive).sort(); if (expected.length !== actual.length || expected.some((value, index) => value !== actual[index])) throw new PayslipRequestAssetBackupError("The encrypted payslip asset archive contains unexpected entries."); const documents = new Set<string>(), entries = new Set<string>(); for (const row of manifest.documents) { if (!validOpaque(row.documentPublicKey) || !validOpaque(row.requestPublicKey) || documents.has(row.documentPublicKey) || !Number.isInteger(row.versionNumber) || row.versionNumber < 1 || !/^source\/[a-f0-9]{2}\/[a-f0-9]{2}\/[a-f0-9-]{36}\.enc$/.test(row.sourceEntry) || !/^delivery\/[a-f0-9]{2}\/[a-f0-9]{2}\/[a-f0-9-]{36}\.pdf$/.test(row.derivativeEntry) || ![row.sourceCiphertextSha256, row.sourcePlainSha256, row.derivativeSha256].every((value) => /^[a-f0-9]{64}$/.test(value)) || !Number.isInteger(row.pageCount) || row.pageCount < 1 || entries.has(row.sourceEntry) || entries.has(row.derivativeEntry)) throw new PayslipRequestAssetBackupError("The encrypted payslip asset manifest contains an invalid entry."); documents.add(row.documentPublicKey); entries.add(row.sourceEntry); entries.add(row.derivativeEntry); } }
function validOpaque(value: unknown) { return typeof value === "string" && /^[A-Za-z0-9_-]{8,100}$/.test(value); }
function safePath(root: string, entry: string) { const target = path.resolve(root, ...entry.split("/")); if (!target.startsWith(`${root}${path.sep}`)) throw new PayslipRequestAssetBackupError("The encrypted payslip asset archive contains a traversal path."); return target; }
function sha256(value: Uint8Array) { return createHash("sha256").update(value).digest("hex"); }
