import { normalizeKgDraft } from "@/lib/kg-report-card";
import { validateGradeBands, validateTemplateDefinition } from "@/lib/report-card-templates";

type Row = Record<string, unknown>;
const keys = {
  gradingSchemes: ["id","schemeCode","name","academicYear","reportType","status","description","createdByUserId","createdAt","updatedAt"],
  gradeBands: ["id","gradingSchemeId","gradeCode","label","minimumPercentage","maximumPercentage","displayOrder","remarks","createdAt","updatedAt"],
  reportCardTemplates: ["id","templateCode","name","reportType","academicYear","className","gradingSchemeId","status","templateDefinitionJson","printSettingsJson","versionNumber","createdByUserId","activatedByUserId","createdAt","updatedAt"],
  reportCardBatches: ["id","batchNumber","academicYear","reportType","templateId","className","section","title","reportingPeriod","status","templateSnapshotJson","cancellationReason","createdByUserId","openedByUserId","submittedByUserId","approvedByUserId","issuedByUserId","archivedByUserId","cancelledByUserId","openedAt","submittedAt","approvedAt","issuedAt","archivedAt","cancelledAt","createdAt","updatedAt"],
  reportCardBatchExamSources: ["id","batchId","examCycleId","weightagePercent","displayOrder","createdAt"],
  studentReportCards: ["id","reportCardNumber","batchId","studentId","academicYear","className","section","reportType","status","currentVersionNumber","draftDataJson","teacherOverallComment","principalComment","directorComment","finalGrade","progressionDecisionId","promotionDisplayText","cancellationReason","createdByUserId","submittedByUserId","approvedByUserId","issuedByUserId","cancelledByUserId","submittedAt","approvedAt","issuedAt","cancelledAt","createdAt","updatedAt"],
  studentReportCardVersions: ["id","reportCardId","versionNumber","versionType","snapshotJson","correctionReason","issuedAt","issuedByUserId","supersedesVersionId","createdAt"],
  studentReportCardEvents: ["id","reportCardId","versionId","eventType","eventDate","previousStatus","newStatus","reason","notes","recordedByUserId","actorLabel","createdAt"]
} as const;

export function validateReportCardBackupRows(root: Row, links: { studentIds: Set<string>; examIds: Set<string>; progressionIds: Set<string> }) {
  const result = Object.fromEntries(Object.entries(keys).map(([name, allowed]) => [name, rows(root[name], name, new Set(allowed))])) as Record<keyof typeof keys, Row[]>;
  const unique = (items: Row[], label: string, identity: (row: Row) => string) => { const found = new Set<string>(); for (const [index,row] of items.entries()) { const value=identity(row); if(!value||found.has(value)) throw new Error(`${label}[${index}] has a missing or duplicate identity`); found.add(value); } return found; };
  const schemeIds=unique(result.gradingSchemes,"gradingSchemes",row=>required(row.id));unique(result.gradingSchemes,"gradingSchemes",row=>required(row.schemeCode).toUpperCase());
  for(const [index,row] of result.gradingSchemes.entries()){enumValue(row.reportType,["MARK_BASED","KG_RUBRIC"],`gradingSchemes[${index}].reportType`);enumValue(row.status,["ACTIVE","INACTIVE"],`gradingSchemes[${index}].status`);year(row.academicYear,`gradingSchemes[${index}].academicYear`,false);}
  unique(result.gradeBands,"gradeBands",row=>required(row.id));for(const [index,row] of result.gradeBands.entries())if(!schemeIds.has(required(row.gradingSchemeId)))throw new Error(`gradeBands[${index}] has an invalid grading-scheme link`);
  for(const scheme of result.gradingSchemes){validateGradeBands(result.gradeBands.filter(b=>b.gradingSchemeId===scheme.id).map(b=>({gradeCode:b.gradeCode,label:b.label,minimumPercentage:b.minimumPercentage,maximumPercentage:b.maximumPercentage,displayOrder:b.displayOrder,remarks:b.remarks})));}
  const templateIds=unique(result.reportCardTemplates,"reportCardTemplates",row=>required(row.id));unique(result.reportCardTemplates,"reportCardTemplates",row=>required(row.templateCode).toUpperCase());
  for(const [index,row] of result.reportCardTemplates.entries()){const type=enumValue(row.reportType,["MARK_BASED","KG_RUBRIC"],`reportCardTemplates[${index}].reportType`);enumValue(row.status,["DRAFT","ACTIVE","INACTIVE"],`reportCardTemplates[${index}].status`);if(row.gradingSchemeId&&!schemeIds.has(String(row.gradingSchemeId)))throw new Error(`reportCardTemplates[${index}] has an invalid grading-scheme link`);validateTemplateDefinition(type,json(row.templateDefinitionJson,`reportCardTemplates[${index}].templateDefinitionJson`));year(row.academicYear,`reportCardTemplates[${index}].academicYear`,false);}
  const batchIds=unique(result.reportCardBatches,"reportCardBatches",row=>required(row.id));unique(result.reportCardBatches,"reportCardBatches",row=>required(row.batchNumber).toUpperCase());
  for(const [index,row] of result.reportCardBatches.entries()){if(!templateIds.has(required(row.templateId)))throw new Error(`reportCardBatches[${index}] has an invalid template link`);enumValue(row.reportType,["MARK_BASED","KG_RUBRIC"],`reportCardBatches[${index}].reportType`);enumValue(row.status,["DRAFT","OPEN_FOR_ENTRY","SUBMITTED","APPROVED","ISSUED","ARCHIVED","CANCELLED"],`reportCardBatches[${index}].status`);year(row.academicYear,`reportCardBatches[${index}].academicYear`,true);const snapshot=json(row.templateSnapshotJson,`reportCardBatches[${index}].templateSnapshotJson`) as any;if(snapshot.reportType!==row.reportType||!snapshot.definition)throw new Error(`reportCardBatches[${index}] template snapshot does not match its report type`);if(snapshot.publicationSchemaVersion!==3)validateTemplateDefinition(snapshot.reportType,snapshot.definition);else if(!snapshot.publication?.previewFingerprint||!snapshot.publication?.templateFamily)throw new Error(`reportCardBatches[${index}] has invalid governed publication metadata`);}
  for(const [index,row] of result.reportCardBatches.entries()){const snapshot=json(row.templateSnapshotJson,`reportCardBatches[${index}].templateSnapshotJson`) as any;if(!snapshot.gradingScheme||!Array.isArray(snapshot.gradingScheme.bands))throw new Error(`reportCardBatches[${index}] requires an immutable grading-scheme snapshot`);if(snapshot.publicationSchemaVersion!==3&&snapshot.gradingScheme.bands.length)validateGradeBands(snapshot.gradingScheme.bands);}
  unique(result.reportCardBatchExamSources,"reportCardBatchExamSources",row=>required(row.id));const sourceKeys=unique(result.reportCardBatchExamSources,"reportCardBatchExamSources",row=>`${required(row.batchId)}|${required(row.examCycleId)}`);
  void sourceKeys;for(const [index,row] of result.reportCardBatchExamSources.entries())if(!batchIds.has(required(row.batchId))||!links.examIds.has(required(row.examCycleId)))throw new Error(`reportCardBatchExamSources[${index}] has an invalid batch or exam link`);
  for(const batch of result.reportCardBatches){const count=result.reportCardBatchExamSources.filter(source=>source.batchId===batch.id).length;const snapshot=json(batch.templateSnapshotJson,`reportCardBatches.${batch.batchNumber}.templateSnapshotJson`) as any;if(snapshot.publicationSchemaVersion!==3&&batch.reportType==="MARK_BASED"&&count!==1)throw new Error(`Mark-based batch ${batch.batchNumber} must have exactly one exam source`);if(snapshot.publicationSchemaVersion!==3&&batch.reportType==="KG_RUBRIC"&&count)throw new Error(`KG batch ${batch.batchNumber} must not have an exam source`);}
  const cardIds=unique(result.studentReportCards,"studentReportCards",row=>required(row.id));unique(result.studentReportCards,"studentReportCards",row=>required(row.reportCardNumber).toUpperCase());unique(result.studentReportCards,"studentReportCards",row=>`${required(row.batchId)}|${required(row.studentId)}`);
  for(const [index,row] of result.studentReportCards.entries()){const batch=result.reportCardBatches.find(b=>b.id===row.batchId);if(!batch||!links.studentIds.has(required(row.studentId)))throw new Error(`studentReportCards[${index}] has an invalid batch or Student link`);if(row.academicYear!==batch.academicYear||row.className!==batch.className||row.reportType!==batch.reportType)throw new Error(`studentReportCards[${index}] does not match its batch scope`);enumValue(row.status,["DRAFT","READY_FOR_REVIEW","APPROVED","ISSUED","CANCELLED","SUPERSEDED","WITHDRAWN"],`studentReportCards[${index}].status`);if(row.progressionDecisionId&&!links.progressionIds.has(String(row.progressionDecisionId)))throw new Error(`studentReportCards[${index}] has an invalid progression reference`);const draft=json(row.draftDataJson,`studentReportCards[${index}].draftDataJson`) as any;if(draft?.publicationSchemaVersion===3){if(!draft.previewFingerprint)throw new Error(`studentReportCards[${index}] has invalid publication draft metadata`);}else if(row.reportType==="KG_RUBRIC")normalizeKgDraft(draft);else if(draft?.kind!=="MARK_BASED"||!draft.calculation||!Array.isArray(draft.calculation.rows))throw new Error(`studentReportCards[${index}] has invalid mark-based draft data`);}
  const versionIds=unique(result.studentReportCardVersions,"studentReportCardVersions",row=>required(row.id));unique(result.studentReportCardVersions,"studentReportCardVersions",row=>`${required(row.reportCardId)}|${Number(row.versionNumber)}`);
  for(const [index,row] of result.studentReportCardVersions.entries()){const card=result.studentReportCards.find(c=>c.id===row.reportCardId);if(!card||!Number.isInteger(Number(row.versionNumber))||Number(row.versionNumber)<1)throw new Error(`studentReportCardVersions[${index}] has an invalid card link or version number`);enumValue(row.versionType,["ORIGINAL","CORRECTION"],`studentReportCardVersions[${index}].versionType`);if(row.versionType==="CORRECTION"&&!String(row.correctionReason??"").trim())throw new Error(`studentReportCardVersions[${index}] correction requires a reason`);const snapshot=json(row.snapshotJson,`studentReportCardVersions[${index}].snapshotJson`) as any;if(snapshot.status!=="ISSUED"||Number(snapshot.versionNumber)!==Number(row.versionNumber)||snapshot.reportType!==card.reportType||snapshot.reportCardNumber!==card.reportCardNumber)throw new Error(`studentReportCardVersions[${index}] has an invalid immutable issued snapshot`);date(row.issuedAt,`studentReportCardVersions[${index}].issuedAt`);}
  for(const card of result.studentReportCards){const versions=result.studentReportCardVersions.filter(v=>v.reportCardId===card.id).sort((a,b)=>Number(a.versionNumber)-Number(b.versionNumber));const current=Number(card.currentVersionNumber);if(current!==versions.length||versions.some((v,index)=>Number(v.versionNumber)!==index+1))throw new Error(`Report card ${card.reportCardNumber} has a non-contiguous or inconsistent version history`);if(versions[0]&&(versions[0].versionType!=="ORIGINAL"||versions[0].supersedesVersionId))throw new Error(`Report card ${card.reportCardNumber} version 1 must be the original issue`);for(let index=1;index<versions.length;index++)if(versions[index].versionType!=="CORRECTION"||versions[index].supersedesVersionId!==versions[index-1].id)throw new Error(`Report card ${card.reportCardNumber} has an invalid superseded-version link`);if(["ISSUED","SUPERSEDED","WITHDRAWN"].includes(String(card.status))&&current<1)throw new Error(`Issued report card ${card.reportCardNumber} requires an immutable version`);}
  const versionsById=new Map(result.studentReportCardVersions.map(row=>[String(row.id),row]));
  unique(result.studentReportCardEvents,"studentReportCardEvents",row=>required(row.id));for(const [index,row] of result.studentReportCardEvents.entries()){const linkedVersion=row.versionId?versionsById.get(String(row.versionId)):null;if(!cardIds.has(required(row.reportCardId))||(row.versionId&&!linkedVersion)||linkedVersion&&linkedVersion.reportCardId!==row.reportCardId)throw new Error(`studentReportCardEvents[${index}] has an invalid card or version link`);enumValue(row.eventType,["CARD_CREATED","ENTRY_UPDATED","SUBMITTED","APPROVED","ISSUED","CORRECTION_REQUESTED","CORRECTION_ISSUED","PARENT_ACKNOWLEDGED","ARCHIVED","CANCELLED","PUBLICATION_ISSUED","PUBLICATION_WITHDRAWN","PUBLICATION_REPLACED","REPORT_PDF_GENERATED","REPORT_PDF_GENERATION_FAILED","REPORT_PDF_DOWNLOAD_AUTHORIZED","PARENT_VIEW_AUTHORIZED","PARENT_DOWNLOAD_AUTHORIZED"],`studentReportCardEvents[${index}].eventType`);date(row.eventDate,`studentReportCardEvents[${index}].eventDate`);}
  return result;
}

function rows(value:unknown,label:string,allowed:Set<string>){if(value===undefined)return[];if(!Array.isArray(value))throw new Error(`${label} must be an array`);if(value.length>100000)throw new Error(`${label} has too many rows`);return value.map((item,index)=>{if(!item||typeof item!=="object"||Array.isArray(item))throw new Error(`${label}[${index}] must be an object`);for(const key of Object.keys(item))if(!allowed.has(key))throw new Error(`${label}[${index}] contains unsupported field ${key}`);return item as Row;});}
function required(value:unknown){const text=String(value??"").trim();if(!text)throw new Error("A required report-card backup identity is missing");return text;}
function enumValue(value:unknown,values:string[],label:string){const text=required(value);if(!values.includes(text))throw new Error(`${label} is unsupported`);return text;}
function year(value:unknown,label:string,requiredValue:boolean){if(!value&&!requiredValue)return;if(!/^\d{4}-\d{2}$/.test(String(value)))throw new Error(`${label} must use YYYY-YY`);}
function date(value:unknown,label:string){if(!value||Number.isNaN(new Date(String(value)).getTime()))throw new Error(`${label} must be a valid date`);}
function json(value:unknown,label:string){if(typeof value!=="string"||value.length>2000000)throw new Error(`${label} must be bounded JSON text`);try{return JSON.parse(value);}catch{throw new Error(`${label} is invalid JSON`);}}
