import type { PrismaClient } from "@prisma/client";

export const SAFE_EXIT_BACKUP_KEYS = [
  "studentDepartureRequests","studentDepartureConsentEvidence","studentStandingDepartureAuthorizations",
  "studentGatePasses","studentDepartureHandovers","studentDepartureEvents","studentDepartureCorrectionEvents","studentCampusPresenceEvents",
  "studentDepartureIncidents","studentDepartureIncidentActions","studentDepartureNotificationOutbox",
  "studentDepartureFallbackTasks"
] as const;
export type SafeExitBackupKey=(typeof SAFE_EXIT_BACKUP_KEYS)[number];
export type SafeExitBackup=Record<SafeExitBackupKey,Record<string,unknown>[]>;
const DELEGATE:Record<SafeExitBackupKey,string>={studentDepartureRequests:"studentDepartureRequest",studentDepartureConsentEvidence:"studentDepartureConsentEvidence",studentStandingDepartureAuthorizations:"studentStandingDepartureAuthorization",studentGatePasses:"studentGatePass",studentDepartureHandovers:"studentDepartureHandover",studentDepartureEvents:"studentDepartureEvent",studentDepartureCorrectionEvents:"studentDepartureCorrectionEvent",studentCampusPresenceEvents:"studentCampusPresenceEvent",studentDepartureIncidents:"studentDepartureIncident",studentDepartureIncidentActions:"studentDepartureIncidentAction",studentDepartureNotificationOutbox:"studentDepartureNotificationOutbox",studentDepartureFallbackTasks:"studentDepartureFallbackTask"};
const FIELDS:Record<SafeExitBackupKey,readonly string[]>={
  studentDepartureRequests:["id","publicKey","requestNumber","submissionKey","source","studentId","academicYear","reasonCategory","reasonDetails","departureType","calendarBasisJson","attendancePolicySnapshotJson","attendanceReconciliationRequired","attendanceReconciliationStatus","intendedHandoverMethod","intendedDepartureAt","temporaryReturnRequired","expectedReturnAt","returnNotificationRequired","overdueEscalatedAt","status","consentState","version","approvedHandoverMethod","approvedRecipientName","approvedRelationship","approvedContactMasked","parentAuthorisationEvidence","verificationReference","approvedDepartureAt","approvalExpiresAt","activeCheckoutKey","emergencyOverride","restricted","requestedByUserId","requestedByRole","approvedByUserId","rejectedByUserId","cancelledByUserId","checkedOutByUserId","returnedByUserId","submittedAt","approvedAt","rejectedAt","cancelledAt","checkedOutAt","returnedAt","closedAt","expiresAt","createdAt","updatedAt"],
  studentDepartureConsentEvidence:["id","publicKey","requestId","outcome","method","guardianId","guardianLinkSnapshotHash","contactMasked","telephoneAttemptSummary","witnessUserId","supervisorUserId","privateDocumentReference","standingAuthorizationKey","recordedByUserId","recordedByRole","notes","recordedAt","createdAt"],
  studentStandingDepartureAuthorizations:["id","publicKey","seriesKey","versionNumber","studentId","guardianId","status","allowsSelfDeparture","eligibleClassSnapshot","allowedDaysJson","allowedStartMinute","allowedEndMinute","effectiveFrom","effectiveUntil","conditions","departurePattern","emergencyContactMasked","guardianApprovalMethod","guardianApprovedAt","approvedByUserId","approvedByRole","approvedAt","supersedesPublicKey","revocationReason","createdByUserId","createdByRole","createdAt"],
  studentGatePasses:["id","publicKey","requestId","tokenHash","manualCodeHash","manualCodeLastTwo","status","approvedSnapshotHash","issuedByUserId","issuedByRole","issuedAt","expiresAt","consumedAt","consumedByUserId","cancelledAt","cancelReason","createdAt","updatedAt"],
  studentDepartureHandovers:["id","publicKey","requestId","handoverMethod","recipientName","relationship","contactMasked","parentAuthorisationEvidence","verificationReference","verifiedByUserId","verifiedAt","createdAt"],
  studentDepartureEvents:["id","publicKey","requestId","eventType","actorUserId","actorRole","previousStatus","newStatus","entityVersion","reason","safeMetadataJson","idempotencyKey","occurredAt","createdAt"],
  studentDepartureCorrectionEvents:["id","publicKey","requestId","correctedFieldCode","priorValueSafe","correctedValueSafe","reason","recordedByUserId","recordedByRole","expectedRequestVersion","idempotencyKey","occurredAt","createdAt"],
  studentCampusPresenceEvents:["id","publicKey","studentId","requestId","eventType","schoolDateKey","locationLabel","handoverMethod","recordedByUserId","source","idempotencyKey","occurredAt","createdAt"],
  studentDepartureIncidents:["id","publicKey","incidentNumber","studentId","requestId","status","version","lastConfirmedLocation","lastConfirmedAt","locatedAt","restricted","linkedSupportRequestKey","reportedByUserId","confirmedByUserId","closedByUserId","reportedAt","confirmedAt","closedAt","createdAt","updatedAt"],
  studentDepartureIncidentActions:["id","publicKey","incidentId","actionType","summary","outcome","recordedByUserId","recordedByRole","idempotencyKey","occurredAt","createdAt"],
  studentDepartureNotificationOutbox:["id","publicKey","requestId","eventKey","eventType","recipientUserId","recipientGuardianId","channel","status","minimalMessageCode","retryCount","nextAttemptAt","claimedAt","queuedAt","sentAt","deliveredAt","failedAt","providerReferenceSafe","failureCode","createdAt","updatedAt"],
  studentDepartureFallbackTasks:["id","publicKey","requestId","eventKey","taskType","status","reasonCode","assignedRole","createdAt","completedAt","completedByUserId"]
};

export async function loadSafeExitBackup(client:PrismaClient):Promise<SafeExitBackup>{const entries=await Promise.all(SAFE_EXIT_BACKUP_KEYS.map(async key=>{const delegate=(client as any)[DELEGATE[key]];return[key,delegate?.findMany?await delegate.findMany({orderBy:{createdAt:"asc"}}):[]]as const;}));return Object.fromEntries(entries)as SafeExitBackup;}
export function validateSafeExitBackupRows(root:Record<string,unknown>,context?:{studentIds?:Set<string>;guardianIds?:Set<string>}):SafeExitBackup{
  const output=Object.fromEntries(SAFE_EXIT_BACKUP_KEYS.map(key=>[key,boundedRows(root[key],key,new Set(FIELDS[key]))]))as SafeExitBackup;
  const ids=(key:SafeExitBackupKey)=>new Set(output[key].map((row,index)=>required(row.id,`${key}[${index}].id`)));
  for(const key of SAFE_EXIT_BACKUP_KEYS){unique(output[key],"id",key);if(FIELDS[key].includes("publicKey"))unique(output[key],"publicKey",key);}
  const requests=ids("studentDepartureRequests"),incidents=ids("studentDepartureIncidents");
  for(const key of ["studentDepartureConsentEvidence","studentGatePasses","studentDepartureHandovers","studentDepartureEvents","studentDepartureCorrectionEvents","studentDepartureNotificationOutbox","studentDepartureFallbackTasks"]as const)links(output[key],"requestId",requests);
  links(output.studentCampusPresenceEvents,"requestId",requests,true);links(output.studentDepartureIncidents,"requestId",requests,true);links(output.studentDepartureIncidentActions,"incidentId",incidents);
  if(context?.studentIds){links(output.studentDepartureRequests,"studentId",context.studentIds);links(output.studentStandingDepartureAuthorizations,"studentId",context.studentIds);links(output.studentCampusPresenceEvents,"studentId",context.studentIds);links(output.studentDepartureIncidents,"studentId",context.studentIds);}
  if(context?.guardianIds){links(output.studentStandingDepartureAuthorizations,"guardianId",context.guardianIds);links(output.studentDepartureConsentEvidence,"guardianId",context.guardianIds,true);}
  for(const [index,row] of output.studentGatePasses.entries()){for(const field of ["tokenHash","manualCodeHash","approvedSnapshotHash"]){if(!/^[a-f0-9]{64}$/i.test(required(row[field],`studentGatePasses[${index}].${field}`)))throw new Error("Safe-exit backup contains an invalid gate-pass digest.");}}
  const allFields=SAFE_EXIT_BACKUP_KEYS.flatMap(key=>output[key].flatMap(row=>Object.keys(row).map(field=>field.toLowerCase())));for(const prohibited of ["password","passwordhash","sessiontoken","sessionsecret","signingkey","providertoken","providerpayload"])if(allFields.includes(prohibited))throw new Error("Safe-exit backup contains prohibited secret material.");
  return output;
}
export async function restoreSafeExitBackup(client:PrismaClient,backup:SafeExitBackup){const result=Object.fromEntries(SAFE_EXIT_BACKUP_KEYS.map(key=>[key,{created:0,skipped:0,errors:[]as string[]}]))as Record<SafeExitBackupKey,{created:number;skipped:number;errors:string[]}>;for(const key of SAFE_EXIT_BACKUP_KEYS){const delegate=(client as any)[DELEGATE[key]];for(const[index,row]of backup[key].entries())try{const id=required(row.id,`${key}[${index}].id`);if(await delegate.findUnique({where:{id},select:{id:true}})){result[key].skipped++;continue;}await delegate.create({data:row});result[key].created++;}catch(error){result[key].errors.push(`${key}[${index}]: ${error instanceof Error?error.message:"restore failed"}`);}}return result;}
function boundedRows(value:unknown,label:string,allowed:Set<string>){if(value===undefined)return[];if(!Array.isArray(value)||value.length>100_000)throw new Error(`${label} must be a bounded array.`);return value.map((item,index)=>{if(!item||typeof item!=="object"||Array.isArray(item))throw new Error(`${label}[${index}] must be an object.`);const row=item as Record<string,unknown>;if(!row.id||Object.keys(row).some(key=>!allowed.has(key)))throw new Error(`${label}[${index}] contains unsupported fields.`);return row;});}
function required(value:unknown,label:string){const result=String(value??"").trim();if(!result||result.length>10_000)throw new Error(`${label} is required and bounded.`);return result;}
function unique(rows:Record<string,unknown>[],field:string,label:string){const values=new Set<string>();rows.forEach((row,index)=>{const value=required(row[field],`${label}[${index}].${field}`);if(values.has(value))throw new Error(`${label}.${field} is duplicated.`);values.add(value);});}
function links(rows:Record<string,unknown>[],field:string,allowed:Set<string>,optional=false){rows.forEach((row,index)=>{if(optional&&(row[field]==null||row[field]===""))return;if(!allowed.has(required(row[field],`${field}[${index}]`)))throw new Error(`Safe-exit backup relationship ${field} is invalid.`);});}
