import { NextRequest, NextResponse } from "next/server";
import { getCurrentAuthContext, getCurrentUserEffectivePermissions } from "@/lib/auth";
import { unsafeRequestOriginAllowed } from "@/lib/request-security";
import { SafeExitError, type SafeExitActor } from "@/lib/safe-exit";

export const SAFE_EXIT_PRIVATE_HEADERS={"Cache-Control":"private, no-store, max-age=0","X-Content-Type-Options":"nosniff","Vary":"Cookie"};
export function safeExitJson(body:unknown,status=200){return NextResponse.json(body,{status,headers:SAFE_EXIT_PRIVATE_HEADERS});}
export function safeExitApiError(error:unknown){if(error instanceof SafeExitError)return safeExitJson({error:error.message,code:error.code},error.status);const message=error instanceof Error&&/Re-authentication|Authorization changed/.test(error.message)?error.message:null;return safeExitJson({error:message??"Unable to complete the Student safety action.",code:message?"REAUTHENTICATION_REQUIRED":"SAFE_EXIT_FAILED"},message?403:500);}
export async function parseSafeExitJson(request:NextRequest){if(!unsafeRequestOriginAllowed(request))throw new SafeExitError("The request origin is not allowed.",403,"ORIGIN_DENIED");const type=request.headers.get("content-type")?.split(";",1)[0]?.trim().toLowerCase();if(type!=="application/json")throw new SafeExitError("Content type must be application/json.",415,"CONTENT_TYPE_REQUIRED");const length=Number(request.headers.get("content-length")??0);if(length&&(!Number.isSafeInteger(length)||length<0||length>64*1024))throw new SafeExitError("The request body is too large.",413,"PAYLOAD_TOO_LARGE");try{const body=await request.json();if(!body||typeof body!=="object"||Array.isArray(body))throw new SafeExitError("A JSON object is required.",400,"INVALID_JSON");return body as Record<string,unknown>;}catch(error){if(error instanceof SafeExitError)throw error;throw new SafeExitError("A valid JSON request body is required.",400,"INVALID_JSON");}}
export async function safeExitApiActor(requiredAny:string[]=[]):Promise<
  | { actor: SafeExitActor; response?: never }
  | { actor?: never; response: NextResponse }
>{const context=await getCurrentAuthContext();if(!context)return{response:safeExitJson({error:"Authentication required"},401)};if(context.user.mustChangePassword)return{response:safeExitJson({error:"Password change required."},403)};const permissions=await getCurrentUserEffectivePermissions();if(requiredAny.length&&!requiredAny.some((permission)=>permissions.has(permission as any)))return{response:safeExitJson({error:"You do not have permission for this Student safety action."},403)};return{actor:{user:context.user,sessionId:context.sessionId,permissions}};}
