import { createHash, randomBytes, randomUUID } from "node:crypto";
import type { AuthUser } from "@/lib/auth";
import type { CanonicalPermission } from "@/lib/permissions";
import { captureAttendanceCalendarBasis } from "@/lib/academic-calendar";
import { requireCriticalReauthentication } from "@/lib/iam/security";
import { schoolDateKey } from "@/lib/format";
import { resolveTeacherAttendanceScope } from "@/lib/teacher-attendance-scope";
import { createGatePassMaterial, gateApprovalSnapshotHash, manualGatePassCodeHash, verifySignedGatePassToken } from "@/lib/safe-exit-gate-pass";
import { queueSafeExitNotifications, type SafeExitMaterialEvent } from "@/lib/safe-exit-notifications";

export const SAFE_EXIT_STATUSES = ["REQUESTED","CONSENT_PENDING","CONSENT_VERIFIED","CONSENT_DENIED","PARENT_UNREACHABLE","UNDER_SCHOOL_REVIEW","APPROVED","READY_FOR_HANDOVER","CHECKED_OUT","RETURNED_TO_CAMPUS","CANCELLED","EXPIRED","EMERGENCY_OVERRIDE","UNAUTHORISED_EXIT_SUSPECTED","UNAUTHORISED_EXIT_CONFIRMED","CLOSED"] as const;
export const SAFE_EXIT_SOURCES = ["PARENT_AUTHENTICATED","STUDENT_RECORDED_BY_STAFF","STAFF_MEDICAL_ROOM","OFFICE_RECORDED","LEADERSHIP_EMERGENCY","STANDING_SELF_DEPARTURE","GATE_SECURITY_INCIDENT"] as const;
export const HANDOVER_METHODS = ["LINKED_GUARDIAN","PRE_AUTHORISED_PICKUP","ONE_TIME_PARENT_AUTHORISED_PICKUP","AMBULANCE_EMERGENCY_RESPONDER","LEGAL_AUTHORITY","STUDENT_SELF_DEPARTURE"] as const;
const EMERGENCY_CATEGORIES = ["URGENT_MEDICAL_TRANSFER","EMERGENCY_EVACUATION","LEGALLY_AUTHORISED_AUTHORITY","SAFEGUARDING_EMERGENCY"] as const;
const INCIDENT_ACTIONS = ["SEARCH_ACTION","PARENT_CONTACT_ATTEMPT","LEADERSHIP_ESCALATION","LAST_LOCATION_UPDATE","STUDENT_LOCATED","RETURNED_TO_CAMPUS","CONFIRM_UNAUTHORISED_EXIT","CLOSE_INCIDENT"] as const;

export type SafeExitActor = { user: AuthUser; sessionId: string; permissions: ReadonlySet<CanonicalPermission> };
export class SafeExitError extends Error { constructor(message:string,public readonly status=400,public readonly code="SAFE_EXIT_INVALID"){super(message);} }

const requestInclude = { student:{select:{id:true,studentName:true,admissionNo:true,className:true,section:true,status:true,academicYear:true}}, consentEvidence:{orderBy:{recordedAt:"desc" as const}}, gatePasses:{orderBy:{issuedAt:"desc" as const}}, handovers:{orderBy:{verifiedAt:"desc" as const}}, events:{orderBy:{occurredAt:"asc" as const}}, campusPresenceEvents:{orderBy:{occurredAt:"asc" as const}}, incidents:{include:{actions:{orderBy:{occurredAt:"asc" as const}}}}, notificationOutbox:{orderBy:{queuedAt:"asc" as const}}, fallbackTasks:{orderBy:{createdAt:"asc" as const}} };

export async function listSafeExitRequests(client:any,actor:SafeExitActor){
  let rows:any[];
  if(actor.user.role==="PARENT"){
    if(!actor.user.guardianId)return[];
    rows=await client.studentDepartureRequest.findMany({where:{student:{guardians:{some:{guardianId:actor.user.guardianId}},deletedAt:null}},include:requestInclude,orderBy:{submittedAt:"desc"},take:200});
  }else if(actor.permissions.has("VIEW_DEPARTURE_AUDIT")) rows=await client.studentDepartureRequest.findMany({include:requestInclude,orderBy:{submittedAt:"desc"},take:500});
  else if(actor.user.role==="GATE_STAFF"||actor.permissions.has("VERIFY_GATE_PASS")) rows=await client.studentDepartureRequest.findMany({where:{status:{in:["READY_FOR_HANDOVER","EMERGENCY_OVERRIDE","CHECKED_OUT"]}},include:requestInclude,orderBy:{intendedDepartureAt:"asc"},take:200});
  else rows=await client.studentDepartureRequest.findMany({where:{requestedByUserId:actor.user.id},include:requestInclude,orderBy:{submittedAt:"desc"},take:200});
  return rows.map((row)=>serializeRequest(row,actor));
}

export async function parentSafeExitContext(client:any,actor:SafeExitActor){
  requireRole(actor,"PARENT");
  if(!actor.user.guardianId)return{children:[],requests:[],standingAuthorisations:[]};
  const links=await client.studentGuardian.findMany({where:{guardianId:actor.user.guardianId,guardian:{status:"Active"},student:{deletedAt:null,status:"Active",academicYearEnrollments:{some:{status:"ACTIVE"}}}},select:{student:{select:{id:true,studentName:true,className:true,section:true,academicYear:true}},relationshipToStudent:true,isPrimaryContact:true},orderBy:[{isPrimaryContact:"desc"},{createdAt:"asc"}]});
  const standingAuthorisations=await client.studentStandingDepartureAuthorization.findMany({where:{guardianId:actor.user.guardianId,studentId:{in:links.map((row:any)=>row.student.id)}},select:{publicKey:true,seriesKey:true,versionNumber:true,studentId:true,status:true,allowsSelfDeparture:true,eligibleClassSnapshot:true,allowedDaysJson:true,allowedStartMinute:true,allowedEndMinute:true,effectiveFrom:true,effectiveUntil:true,conditions:true,revocationReason:true,createdAt:true},orderBy:[{seriesKey:"asc"},{versionNumber:"desc"}],take:200});
  return{children:links.map((row:any)=>({...row.student,relationship:row.relationshipToStudent,isPrimaryContact:row.isPrimaryContact})),requests:await listSafeExitRequests(client,actor),standingAuthorisations:standingAuthorisations.map((row:any)=>({...row,allowedDays:JSON.parse(row.allowedDaysJson)}))};
}

export async function safeExitStudentOptions(client:any,actor:SafeExitActor){
  const students=await client.student.findMany({where:{deletedAt:null,status:"Active",academicYearEnrollments:{some:{status:"ACTIVE"}}},select:{id:true,studentName:true,admissionNo:true,className:true,section:true,academicYear:true,academicYearEnrollments:{where:{status:"ACTIVE"},select:{academicYear:true,className:true,section:true}},guardians:{select:{guardianId:true,relationshipToStudent:true,isPrimaryContact:true,guardian:{select:{displayName:true,primaryMobile:true,status:true}}}}},orderBy:[{className:"asc"},{section:"asc"},{studentName:"asc"}],take:10_000});
  const scoped=[] as any[];for(const student of students){try{await assertStudentScope(client,actor,student,new Date());scoped.push({id:student.id,name:student.studentName,admissionNo:student.admissionNo,className:student.className,section:student.section,guardians:student.guardians.filter((link:any)=>link.guardian.status==="Active").map((link:any)=>({guardianId:link.guardianId,name:link.guardian.displayName,relationship:link.relationshipToStudent,isPrimaryContact:link.isPrimaryContact,contactMasked:maskContact(link.guardian.primaryMobile)}))});}catch{/* Exact object scope intentionally omits unauthorised Students. */}}
  return scoped;
}

export async function createSafeExitRequest(client:any,actor:SafeExitActor,raw:any){
  requirePermission(actor,"REQUEST_STUDENT_DEPARTURE");
  const input=validateRequest(raw), existing=await client.studentDepartureRequest.findUnique({where:{submissionKey:input.submissionKey},include:requestInclude});
  if(existing){if(existing.requestedByUserId!==actor.user.id||existing.studentId!==input.studentId)throw new SafeExitError("Request key is already in use.",409,"IDEMPOTENCY_CONFLICT");return serializeRequest(existing,actor);}
  const student=await loadActiveStudent(client,input.studentId);
  const link=await assertStudentScope(client,actor,student,input.intendedDepartureAt);
  if(actor.user.role==="PARENT"&&input.source!=="PARENT_AUTHENTICATED")throw new SafeExitError("Parent requests must use the authenticated Parent source.",403,"SOURCE_SCOPE_DENIED");
  if(actor.user.role!=="PARENT"&&input.source==="PARENT_AUTHENTICATED")throw new SafeExitError("Authenticated Parent source is unavailable in Staff context.",403,"SOURCE_SCOPE_DENIED");
  if(input.source==="LEADERSHIP_EMERGENCY")throw new SafeExitError("Emergency authority must use the restricted override action.",400,"EMERGENCY_ACTION_REQUIRED");
  let standing:any=null;
  if(input.source==="STANDING_SELF_DEPARTURE")standing=await currentStandingAuthorization(client,student.id,input.intendedDepartureAt,true);
  const basis=await captureAttendanceCalendarBasis(client,{academicYear:student.academicYear,attendanceDate:schoolDay(input.intendedDepartureAt),className:student.className,section:student.section??""});
  const calendarBasisJson=basis.calendarBasisSnapshotJson;
  const calendarBasis=JSON.parse(calendarBasisJson) as {dayType?:string};
  if(["NON_WORKING_DAY","VACATION_DAY","EMERGENCY_CLOSURE"].includes(calendarBasis.dayType??""))throw new SafeExitError("Normal early departure is unavailable on the classified non-working day. Use the restricted emergency workflow only when an actual safety emergency exists.",409,"NON_WORKING_DAY");
  const requestNumber=`EXIT-${schoolDateKey()}-${randomBytes(4).toString("hex").toUpperCase()}`;
  const parentAuthenticated=actor.user.role==="PARENT";
  const status=parentAuthenticated||standing?"UNDER_SCHOOL_REVIEW":"CONSENT_PENDING",consentState=parentAuthenticated||standing?"VERIFIED":"PENDING";
  const row=await client.$transaction(async(tx:any)=>{
    const created=await tx.studentDepartureRequest.create({data:{requestNumber,submissionKey:input.submissionKey,source:input.source,studentId:student.id,academicYear:student.academicYear,reasonCategory:input.reasonCategory,reasonDetails:input.reasonDetails,calendarBasisJson,intendedHandoverMethod:input.intendedHandoverMethod,intendedDepartureAt:input.intendedDepartureAt,status,consentState,requestedByUserId:actor.user.id,requestedByRole:actor.user.role}});
    if(parentAuthenticated||standing)await tx.studentDepartureConsentEvidence.create({data:{requestId:created.id,outcome:"APPROVED",method:standing?"STANDING_AUTHORIZATION":"AUTHENTICATED_PARENT",guardianId:standing?.guardianId??actor.user.guardianId,guardianLinkSnapshotHash:guardianLinkHash(link),standingAuthorizationKey:standing?.publicKey??null,recordedByUserId:actor.user.id,recordedByRole:actor.user.role,notes:standing?"Current standing authorisation verified at request time.":"Authenticated linked-Parent approval recorded with request."}});
    await appendEvent(tx,created,actor,"REQUEST_SUBMITTED",null,status,`${input.submissionKey}:submitted`,null,{source:input.source,calendarBasis:JSON.parse(calendarBasisJson)});
    const recipients=await notificationRecipients(tx,student.id);
    await queueSafeExitNotifications(tx,{eventKey:`${created.id}:request`,eventType:parentAuthenticated||standing?"CONSENT_RECORDED":"AWAITING_CONSENT",requestId:created.id,requestPublicKey:created.publicKey,actorUserId:actor.user.id,guardianId:recipients.guardianId,parentUserIds:recipients.parentUserIds,leadershipUserIds:[],now:new Date()});
    return tx.studentDepartureRequest.findUniqueOrThrow({where:{id:created.id},include:requestInclude});
  });
  return serializeRequest(row,actor);
}

export async function recordSafeExitConsent(client:any,actor:SafeExitActor,requestKey:string,raw:any){
  requirePermission(actor,"RECORD_PARENT_CONSENT");
  const row=await scopedRequest(client,actor,requestKey),expectedVersion=integer(raw.expectedVersion,"Expected version",1,1_000_000),outcome=oneOf(raw.outcome,["APPROVED","DENIED","PARENT_UNREACHABLE"] as const,"Consent outcome"),method=oneOf(raw.method,["AUTHENTICATED_PARENT","VERIFIED_TELEPHONE","PRIVATE_WRITTEN_REFERENCE","STANDING_AUTHORIZATION"] as const,"Consent method");
  if(!["CONSENT_PENDING","PARENT_UNREACHABLE","CONSENT_DENIED"].includes(row.status))throw new SafeExitError("Consent can be recorded only before school review.",409,"CONSENT_STATE_CHANGED");
  if(actor.user.role==="PARENT"&&method!=="AUTHENTICATED_PARENT")throw new SafeExitError("Parent consent requires the current linked-Parent context.",403,"PARENT_SCOPE_DENIED");
  const guardianLink=await linkedGuardian(client,row.studentId,actor.user.role==="PARENT"?actor.user.guardianId:String(raw.guardianId??""));
  let contactMasked:string|null=null,witnessUserId:string|null=null,supervisorUserId:string|null=null,privateDocumentReference:string|null=null,standingAuthorizationKey:string|null=null,attemptSummary:string|null=null;
  if(outcome==="PARENT_UNREACHABLE"){attemptSummary=text(raw.telephoneAttemptSummary,"Parent contact attempts",10,1000);if(method==="AUTHENTICATED_PARENT")throw new SafeExitError("Authenticated Parent consent cannot be marked unreachable.");}
  else if(method==="VERIFIED_TELEPHONE"){
    if(outcome!=="APPROVED")throw new SafeExitError("Verified telephone evidence is only valid for affirmative consent.");contactMasked=maskContact(guardianLink.guardian.primaryMobile);attemptSummary=text(raw.telephoneAttemptSummary,"Telephone verification summary",10,1000);const witness=await authorisedWitness(client,raw.witnessUserKey,actor.user.id);witnessUserId=witness.id;supervisorUserId=witness.id;
  }else if(method==="PRIVATE_WRITTEN_REFERENCE"){
    privateDocumentReference=text(raw.privateDocumentReference,"Private written-consent reference",6,160);const supervisor=await authorisedWitness(client,raw.supervisorUserKey,actor.user.id);supervisorUserId=supervisor.id;
  }else if(method==="STANDING_AUTHORIZATION"){
    const standing=await currentStandingAuthorization(client,row.studentId,row.intendedDepartureAt,row.intendedHandoverMethod==="STUDENT_SELF_DEPARTURE");if(standing.guardianId!==guardianLink.guardianId)throw new SafeExitError("Standing authorisation no longer matches the linked Guardian.",409,"STANDING_AUTH_STALE");standingAuthorizationKey=standing.publicKey;
  }else if(actor.user.role!=="PARENT")throw new SafeExitError("Authenticated Parent approval must be performed in Parent context.",403,"PARENT_CONTEXT_REQUIRED");
  const nextStatus=outcome==="APPROVED"?"UNDER_SCHOOL_REVIEW":outcome==="DENIED"?"CONSENT_DENIED":"PARENT_UNREACHABLE",event:SafeExitMaterialEvent=outcome==="APPROVED"?"CONSENT_RECORDED":"REJECTED";
  const updated=await client.$transaction(async(tx:any)=>{
    const claim=await tx.studentDepartureRequest.updateMany({where:{id:row.id,version:expectedVersion,status:row.status},data:{status:nextStatus,consentState:outcome==="APPROVED"?"VERIFIED":outcome,version:{increment:1},rejectedAt:outcome==="DENIED"?new Date():null,rejectedByUserId:outcome==="DENIED"?actor.user.id:null}});if(claim.count!==1)throw conflict();
    await tx.studentDepartureConsentEvidence.create({data:{requestId:row.id,outcome,method,guardianId:guardianLink.guardian.id,guardianLinkSnapshotHash:guardianLinkHash(guardianLink),contactMasked,telephoneAttemptSummary:attemptSummary,witnessUserId,supervisorUserId,privateDocumentReference,standingAuthorizationKey,recordedByUserId:actor.user.id,recordedByRole:actor.user.role,notes:optional(raw.notes,"Consent notes",1000)}});
    await appendEvent(tx,{...row,version:expectedVersion+1},actor,`CONSENT_${outcome}`,row.status,nextStatus,`${row.id}:consent:${expectedVersion}`,null,{method});const recipients=await notificationRecipients(tx,row.studentId);await queueSafeExitNotifications(tx,{eventKey:`${row.id}:consent:${expectedVersion}`,eventType:event,requestId:row.id,requestPublicKey:row.publicKey,actorUserId:actor.user.id,guardianId:recipients.guardianId,parentUserIds:recipients.parentUserIds});return tx.studentDepartureRequest.findUniqueOrThrow({where:{id:row.id},include:requestInclude});
  });return serializeRequest(updated,actor);
}

export async function approveSafeExit(client:any,actor:SafeExitActor,requestKey:string,raw:any){
  requirePermission(actor,"APPROVE_STUDENT_DEPARTURE");requireLeadership(actor);
  const row=await scopedRequest(client,actor,requestKey),expectedVersion=integer(raw.expectedVersion,"Expected version",1,1_000_000);if(row.status!=="UNDER_SCHOOL_REVIEW"||row.consentState!=="VERIFIED")throw new SafeExitError("Normal approval requires current verified consent and school review state.",409,"CONSENT_REQUIRED");
  await assertCurrentConsent(client,row);
  const pickup=await validatePickupForApproval(client,row,raw),approvedDepartureAt=dateTime(raw.approvedDepartureAt??row.intendedDepartureAt,"Approved departure time"),approvalExpiresAt=new Date(Math.min(approvedDepartureAt.getTime()+60*60_000,Date.now()+24*60*60_000));
  const updated=await client.$transaction(async(tx:any)=>{const claim=await tx.studentDepartureRequest.updateMany({where:{id:row.id,version:expectedVersion,status:"UNDER_SCHOOL_REVIEW",consentState:"VERIFIED"},data:{status:"APPROVED",version:{increment:1},approvedHandoverMethod:pickup.method,approvedRecipientName:pickup.name,approvedRelationship:pickup.relationship,approvedContactMasked:pickup.contactMasked,parentAuthorisationEvidence:pickup.parentEvidence,verificationReference:pickup.verificationReference,approvedDepartureAt,approvalExpiresAt,approvedAt:new Date(),approvedByUserId:actor.user.id}});if(claim.count!==1)throw conflict();await appendEvent(tx,{...row,version:expectedVersion+1},actor,"SCHOOL_APPROVED",row.status,"APPROVED",`${row.id}:approve:${expectedVersion}`,text(raw.reason,"Approval reason",3,1000),{handoverMethod:pickup.method});const recipients=await notificationRecipients(tx,row.studentId);await queueSafeExitNotifications(tx,{eventKey:`${row.id}:approved:${expectedVersion}`,eventType:"APPROVED",requestId:row.id,requestPublicKey:row.publicKey,actorUserId:actor.user.id,guardianId:recipients.guardianId,parentUserIds:recipients.parentUserIds});return tx.studentDepartureRequest.findUniqueOrThrow({where:{id:row.id},include:requestInclude});});return serializeRequest(updated,actor);
}

export async function emergencyOverrideSafeExit(client:any,actor:SafeExitActor,requestKey:string,raw:any){
  requirePermission(actor,"EMERGENCY_OVERRIDE_STUDENT_DEPARTURE");requireLeadership(actor);await requireCriticalReauthentication(client,{user:actor.user,sessionId:actor.sessionId},String(raw.reauthPassword??""));
  const row=await scopedRequest(client,actor,requestKey),expectedVersion=integer(raw.expectedVersion,"Expected version",1,1_000_000),category=oneOf(raw.emergencyCategory,EMERGENCY_CATEGORIES,"Emergency category"),reason=text(raw.reason,"Emergency reason",12,2000),contactAttempts=arrayOfText(raw.parentContactAttempts,"Parent contact attempts",1,12,300),safeDestination=text(raw.safeDestination,"Safe destination or handover",5,500);if(/late|unreachable/i.test(reason)&&!/(medical|evacuation|authority|safeguard)/i.test(reason))throw new SafeExitError("Emergency override cannot be used merely because a Parent is late or unreachable.",400,"EMERGENCY_MISUSE_BLOCKED");
  if(row.source==="GATE_SECURITY_INCIDENT"||["UNAUTHORISED_EXIT_SUSPECTED","UNAUTHORISED_EXIT_CONFIRMED"].includes(row.status))throw new SafeExitError("An unauthorised-exit incident cannot create a gate pass or release authority.",409,"INCIDENT_GATE_PASS_BLOCKED");
  const pickup=await validatePickupForApproval(client,row,raw);if(pickup.method==="STUDENT_SELF_DEPARTURE")await currentStandingAuthorization(client,row.studentId,new Date(),true);
  let secondConfirmationUserId:null|string=null,secondUnavailable:string|null=null;if(raw.secondConfirmationUserKey){secondConfirmationUserId=(await authorisedWitness(client,raw.secondConfirmationUserKey,actor.user.id,true)).id;}else secondUnavailable=text(raw.secondConfirmationUnavailableReason,"Why second confirmation was unavailable",12,1000);
  const updated=await client.$transaction(async(tx:any)=>{const claim=await tx.studentDepartureRequest.updateMany({where:{id:row.id,version:expectedVersion,status:{notIn:["CHECKED_OUT","RETURNED_TO_CAMPUS","CANCELLED","CLOSED"]}},data:{status:"EMERGENCY_OVERRIDE",version:{increment:1},emergencyOverride:true,restricted:true,approvedHandoverMethod:pickup.method,approvedRecipientName:pickup.name,approvedRelationship:pickup.relationship,approvedContactMasked:pickup.contactMasked,parentAuthorisationEvidence:pickup.parentEvidence,verificationReference:pickup.verificationReference,approvedDepartureAt:new Date(),approvalExpiresAt:new Date(Date.now()+30*60_000),approvedAt:new Date(),approvedByUserId:actor.user.id}});if(claim.count!==1)throw conflict();await appendEvent(tx,{...row,version:expectedVersion+1},actor,"EMERGENCY_OVERRIDE_AUTHORISED",row.status,"EMERGENCY_OVERRIDE",`${row.id}:emergency:${expectedVersion}`,reason,{category,parentContactAttempts:contactAttempts.length,safeDestination,secondConfirmationUserId,secondUnavailable});const recipients=await notificationRecipients(tx,row.studentId),leadership=await leadershipUsers(tx,actor.user.id);await queueSafeExitNotifications(tx,{eventKey:`${row.id}:emergency:${expectedVersion}`,eventType:"EMERGENCY_OVERRIDE",requestId:row.id,requestPublicKey:row.publicKey,actorUserId:actor.user.id,guardianId:recipients.guardianId,parentUserIds:recipients.parentUserIds,leadershipUserIds:leadership});return tx.studentDepartureRequest.findUniqueOrThrow({where:{id:row.id},include:requestInclude});});return serializeRequest(updated,actor);
}

export async function issueSafeExitGatePass(client:any,actor:SafeExitActor,requestKey:string,raw:any){
  requirePermission(actor,"APPROVE_STUDENT_DEPARTURE");requireLeadership(actor);const row=await scopedRequest(client,actor,requestKey),expectedVersion=integer(raw.expectedVersion,"Expected version",1,1_000_000);if(!["APPROVED","EMERGENCY_OVERRIDE"].includes(row.status)||!row.approvedAt||!row.approvedHandoverMethod||!row.approvalExpiresAt||row.approvalExpiresAt<=new Date())throw new SafeExitError("A current approval is required before issuing a gate pass.",409,"APPROVAL_STALE");
  if(row.source==="GATE_SECURITY_INCIDENT")throw new SafeExitError("An unauthorised-exit incident cannot create a gate pass.",409,"INCIDENT_GATE_PASS_BLOCKED");if(!row.emergencyOverride)await assertCurrentConsent(client,row);
  const material=createGatePassMaterial(),expiresAt=new Date(Math.min(material.expiresAt.getTime(),row.approvalExpiresAt.getTime())),snapshot=approvalSnapshot(row);
  const result=await client.$transaction(async(tx:any)=>{await tx.studentGatePass.updateMany({where:{requestId:row.id,status:"ACTIVE"},data:{status:"CANCELLED",cancelledAt:new Date(),cancelReason:"Superseded by a freshly issued pass."}});const pass=await tx.studentGatePass.create({data:{requestId:row.id,tokenHash:material.tokenHash,manualCodeHash:material.manualCodeHash,manualCodeLastTwo:material.manualCodeLastTwo,approvedSnapshotHash:gateApprovalSnapshotHash(snapshot),issuedByUserId:actor.user.id,issuedByRole:actor.user.role,expiresAt}});if(row.status==="APPROVED"){const claim=await tx.studentDepartureRequest.updateMany({where:{id:row.id,version:expectedVersion,status:"APPROVED"},data:{status:"READY_FOR_HANDOVER",version:{increment:1}}});if(claim.count!==1)throw conflict();}else if(row.version!==expectedVersion)throw conflict();await appendEvent(tx,{...row,version:row.status==="APPROVED"?expectedVersion+1:expectedVersion},actor,"GATE_PASS_ISSUED",row.status,row.status==="APPROVED"?"READY_FOR_HANDOVER":row.status,`${row.id}:pass:${pass.publicKey}`,null,{expiresAt:expiresAt.toISOString(),manualCodeLastTwo:material.manualCodeLastTwo});return{passPublicKey:pass.publicKey,token:material.token,manualCode:material.manualCode,expiresAt};});return result;
}

export async function verifySafeExitGatePass(client:any,actor:SafeExitActor,raw:any){
  requirePermission(actor,"VERIFY_GATE_PASS");const now=new Date();let where:any;if(raw.token){where={tokenHash:verifySignedGatePassToken(raw.token,now).tokenHash};}else where={manualCodeHash:manualGatePassCodeHash(raw.manualCode)};
  const pass=await client.studentGatePass.findUnique({where,include:{request:{include:{student:{select:{id:true,studentName:true,className:true,section:true,status:true,academicYear:true,academicYearEnrollments:{where:{status:"ACTIVE"},select:{id:true}}}},gatePasses:true,handovers:true}}}});if(!pass)throw new SafeExitError("Gate pass is invalid or tampered.",404,"PASS_NOT_FOUND");const request=pass.request;
  if(pass.status!=="ACTIVE"||pass.consumedAt)throw new SafeExitError("Gate pass has already been used or cancelled.",409,"PASS_NOT_ACTIVE");if(pass.expiresAt<=now)throw new SafeExitError("Gate pass has expired.",410,"PASS_EXPIRED");if(request.source==="GATE_SECURITY_INCIDENT")throw new SafeExitError("An unauthorised-exit incident never has a valid gate pass.",409,"INCIDENT_GATE_PASS_BLOCKED");if(!["READY_FOR_HANDOVER","EMERGENCY_OVERRIDE"].includes(request.status)||!request.approvalExpiresAt||request.approvalExpiresAt<=now||pass.approvedSnapshotHash!==gateApprovalSnapshotHash(approvalSnapshot(request)))throw new SafeExitError("The departure approval is cancelled, stale or unavailable.",409,"APPROVAL_STALE");if(!request.emergencyOverride)await assertCurrentConsent(client,request);if(!request.student.academicYearEnrollments.length||request.student.status!=="Active")throw new SafeExitError("Student is not actively enrolled.",409,"STUDENT_INACTIVE");if(raw.studentId&&String(raw.studentId)!==request.studentId)throw new SafeExitError("Gate pass does not belong to the selected Student.",409,"WRONG_STUDENT");if(raw.recipientName&&normalizeName(raw.recipientName)!==normalizeName(request.approvedRecipientName))throw new SafeExitError("Pickup person does not match the approved handover.",409,"WRONG_PICKUP");if(raw.handoverMethod&&String(raw.handoverMethod)!==request.approvedHandoverMethod)throw new SafeExitError("Handover method does not match the approval.",409,"WRONG_HANDOVER_METHOD");if(!(await currentCampusState(client,request.studentId,now)).onCampus)throw new SafeExitError("Student is already checked out or not currently recorded on campus.",409,"ALREADY_CHECKED_OUT");
  return{passPublicKey:pass.publicKey,status:pass.status,expiresAt:pass.expiresAt,requestKey:request.publicKey,requestVersion:request.version,student:{id:request.student.id,name:request.student.studentName,className:request.student.className,section:request.student.section},approvedDepartureAt:request.approvedDepartureAt,handoverMethod:request.approvedHandoverMethod,recipient:{name:request.approvedRecipientName,relationship:request.approvedRelationship,contactMasked:request.approvedContactMasked},authorisingRole:request.emergencyOverride?"EMERGENCY_LEADERSHIP":"SCHOOL_LEADERSHIP"};
}

export async function completeSafeExitCheckout(client:any,actor:SafeExitActor,raw:any){
  requirePermission(actor,"COMPLETE_STUDENT_CHECKOUT");const verified=await verifySafeExitGatePass(client,actor,raw),expectedVersion=integer(raw.expectedVersion??verified.requestVersion,"Expected version",1,1_000_000),now=new Date();const pass=await client.studentGatePass.findUniqueOrThrow({where:{publicKey:verified.passPublicKey},include:{request:true}}),row=pass.request;
  const recipientName=text(raw.recipientName??row.approvedRecipientName,"Pickup person",2,120),relationship=text(raw.relationship??row.approvedRelationship,"Relationship",2,80),handoverMethod=oneOf(raw.handoverMethod??row.approvedHandoverMethod,HANDOVER_METHODS,"Handover method");if(normalizeName(recipientName)!==normalizeName(row.approvedRecipientName)||handoverMethod!==row.approvedHandoverMethod)throw new SafeExitError("Verified handover does not match the active approval.",409,"HANDOVER_MISMATCH");
  const updated=await client.$transaction(async(tx:any)=>{const passClaim=await tx.studentGatePass.updateMany({where:{id:pass.id,status:"ACTIVE",consumedAt:null,expiresAt:{gt:now}},data:{status:"USED",consumedAt:now,consumedByUserId:actor.user.id}});if(passClaim.count!==1)throw new SafeExitError("Gate pass was already used by another checkout.",409,"PASS_ALREADY_USED");const requestClaim=await tx.studentDepartureRequest.updateMany({where:{id:row.id,version:expectedVersion,status:{in:["READY_FOR_HANDOVER","EMERGENCY_OVERRIDE"]},activeCheckoutKey:null},data:{status:"CHECKED_OUT",version:{increment:1},activeCheckoutKey:row.studentId,checkedOutAt:now,checkedOutByUserId:actor.user.id}});if(requestClaim.count!==1)throw conflict();await tx.studentDepartureHandover.create({data:{requestId:row.id,handoverMethod,recipientName,relationship,contactMasked:row.approvedContactMasked,parentAuthorisationEvidence:row.parentAuthorisationEvidence??"Governed school approval",verificationReference:optional(raw.verificationReference,"Verification reference",160)??row.verificationReference,verifiedByUserId:actor.user.id,verifiedAt:now}});await tx.studentCampusPresenceEvent.create({data:{studentId:row.studentId,requestId:row.id,eventType:"EARLY_DEPARTURE",schoolDateKey:schoolDateKey(now),handoverMethod,recordedByUserId:actor.user.id,source:"GATE_CHECKOUT",idempotencyKey:`${row.id}:checkout`}});await appendEvent(tx,{...row,version:expectedVersion+1},actor,"CHECKOUT_COMPLETED",row.status,"CHECKED_OUT",`${row.id}:checkout`,null,{handoverMethod,passPublicKey:pass.publicKey});const recipients=await notificationRecipients(tx,row.studentId);await queueSafeExitNotifications(tx,{eventKey:`${row.id}:checkout`,eventType:"CHECKED_OUT",requestId:row.id,requestPublicKey:row.publicKey,actorUserId:actor.user.id,guardianId:recipients.guardianId,parentUserIds:recipients.parentUserIds});return tx.studentDepartureRequest.findUniqueOrThrow({where:{id:row.id},include:requestInclude});});return serializeRequest(updated,actor);
}

export async function recordSafeExitReturn(client:any,actor:SafeExitActor,requestKey:string,raw:any){
  requirePermission(actor,"RECORD_STUDENT_RETURN");const row=await scopedRequest(client,actor,requestKey),expectedVersion=integer(raw.expectedVersion,"Expected version",1,1_000_000),now=new Date();if(row.status!=="CHECKED_OUT"||row.activeCheckoutKey!==row.studentId)throw new SafeExitError("Only a currently checked-out Student can be returned.",409,"NOT_CHECKED_OUT");const updated=await client.$transaction(async(tx:any)=>{const claim=await tx.studentDepartureRequest.updateMany({where:{id:row.id,version:expectedVersion,status:"CHECKED_OUT",activeCheckoutKey:row.studentId},data:{status:"RETURNED_TO_CAMPUS",version:{increment:1},activeCheckoutKey:null,returnedAt:now,returnedByUserId:actor.user.id}});if(claim.count!==1)throw conflict();await tx.studentCampusPresenceEvent.create({data:{studentId:row.studentId,requestId:row.id,eventType:"RETURNED_TO_CAMPUS",schoolDateKey:schoolDateKey(now),locationLabel:optional(raw.locationLabel,"Return location",120)??"School gate",recordedByUserId:actor.user.id,source:"GATE_RETURN",idempotencyKey:`${row.id}:return`}});await appendEvent(tx,{...row,version:expectedVersion+1},actor,"RETURNED_TO_CAMPUS",row.status,"RETURNED_TO_CAMPUS",`${row.id}:return`,optional(raw.notes,"Return notes",500),null);const recipients=await notificationRecipients(tx,row.studentId);await queueSafeExitNotifications(tx,{eventKey:`${row.id}:return`,eventType:"RETURNED_TO_CAMPUS",requestId:row.id,requestPublicKey:row.publicKey,actorUserId:actor.user.id,guardianId:recipients.guardianId,parentUserIds:recipients.parentUserIds});return tx.studentDepartureRequest.findUniqueOrThrow({where:{id:row.id},include:requestInclude});});return serializeRequest(updated,actor);
}

export async function cancelSafeExitRequest(client:any,actor:SafeExitActor,requestKey:string,raw:any){
  const row=await scopedRequest(client,actor,requestKey);if(actor.user.role!=="PARENT")requirePermission(actor,"REQUEST_STUDENT_DEPARTURE");const expectedVersion=integer(raw.expectedVersion,"Expected version",1,1_000_000),reason=text(raw.reason,"Cancellation reason",3,1000);if(["CHECKED_OUT","RETURNED_TO_CAMPUS","CLOSED","CANCELLED"].includes(row.status))throw new SafeExitError("This request can no longer be cancelled.",409,"CANCELLATION_BLOCKED");const updated=await client.$transaction(async(tx:any)=>{const claim=await tx.studentDepartureRequest.updateMany({where:{id:row.id,version:expectedVersion,status:row.status},data:{status:"CANCELLED",version:{increment:1},cancelledAt:new Date(),cancelledByUserId:actor.user.id,activeCheckoutKey:null}});if(claim.count!==1)throw conflict();await tx.studentGatePass.updateMany({where:{requestId:row.id,status:"ACTIVE"},data:{status:"CANCELLED",cancelledAt:new Date(),cancelReason:reason}});await appendEvent(tx,{...row,version:expectedVersion+1},actor,"REQUEST_CANCELLED",row.status,"CANCELLED",`${row.id}:cancel:${expectedVersion}`,reason,null);const recipients=await notificationRecipients(tx,row.studentId);await queueSafeExitNotifications(tx,{eventKey:`${row.id}:cancel:${expectedVersion}`,eventType:"CANCELLED",requestId:row.id,requestPublicKey:row.publicKey,actorUserId:actor.user.id,guardianId:recipients.guardianId,parentUserIds:recipients.parentUserIds});return tx.studentDepartureRequest.findUniqueOrThrow({where:{id:row.id},include:requestInclude});});return serializeRequest(updated,actor);
}

export async function createStandingDepartureAuthorization(client:any,actor:SafeExitActor,raw:any){
  requirePermission(actor,"RECORD_PARENT_CONSENT");const student=await loadActiveStudent(client,String(raw.studentId??"")),link=await assertStudentScope(client,actor,student,new Date()),guardian=await linkedGuardian(client,student.id,actor.user.role==="PARENT"?actor.user.guardianId:String(raw.guardianId??""));if(actor.user.role!=="PARENT"&&!String(raw.guardianApprovalMethod??"").startsWith("VERIFIED_"))throw new SafeExitError("Staff-recorded standing authority requires verified Guardian evidence.");
  const effectiveFrom=dateTime(raw.effectiveFrom,"Effective from"),effectiveUntil=dateTime(raw.effectiveUntil,"Effective until");if(effectiveUntil<=effectiveFrom||effectiveUntil.getTime()-effectiveFrom.getTime()>370*86_400_000)throw new SafeExitError("Standing authorisation dates must be ordered and bounded to 370 days.");const allowedDays=arrayOfText(raw.allowedDays,"Allowed days",1,7,10).map((day)=>oneOf(day,["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"] as const,"Allowed day")),start=integer(raw.allowedStartMinute,"Allowed start minute",0,1439),end=integer(raw.allowedEndMinute,"Allowed end minute",0,1439);if(end<=start)throw new SafeExitError("Allowed end time must follow start time.");
  const seriesKey=raw.seriesKey?text(raw.seriesKey,"Standing authorisation series",8,80):randomUUID(),latest=await client.studentStandingDepartureAuthorization.findFirst({where:{seriesKey},orderBy:{versionNumber:"desc"}});if(latest&&(latest.studentId!==student.id||latest.guardianId!==guardian.guardian.id))throw new SafeExitError("Standing authorisation series scope cannot change.",409,"SERIES_SCOPE_CONFLICT");return client.studentStandingDepartureAuthorization.create({data:{seriesKey,versionNumber:(latest?.versionNumber??0)+1,studentId:student.id,guardianId:guardian.guardian.id,status:"ACTIVE",allowsSelfDeparture:raw.allowsSelfDeparture===true,eligibleClassSnapshot:`${student.className}${student.section?`-${student.section}`:""}`,allowedDaysJson:JSON.stringify([...new Set(allowedDays)]),allowedStartMinute:start,allowedEndMinute:end,effectiveFrom,effectiveUntil,conditions:optional(raw.conditions,"Conditions",1000),guardianApprovalMethod:text(raw.guardianApprovalMethod??(actor.user.role==="PARENT"?"AUTHENTICATED_PARENT":""),"Guardian approval method",3,80),guardianApprovedAt:new Date(),supersedesPublicKey:latest?.publicKey??null,createdByUserId:actor.user.id,createdByRole:actor.user.role}});
}

export async function revokeStandingDepartureAuthorization(client:any,actor:SafeExitActor,publicKey:string,raw:any){
  requirePermission(actor,"RECORD_PARENT_CONSENT");const current=await client.studentStandingDepartureAuthorization.findUnique({where:{publicKey}});if(!current)throw new SafeExitError("Standing authorisation was not found.",404,"NOT_FOUND");await assertStudentScope(client,actor,await loadActiveStudent(client,current.studentId),new Date());const latest=await client.studentStandingDepartureAuthorization.findFirst({where:{seriesKey:current.seriesKey},orderBy:{versionNumber:"desc"}});if(!latest||latest.publicKey!==current.publicKey||latest.status!=="ACTIVE")throw new SafeExitError("Standing authorisation is already superseded or revoked.",409,"STANDING_AUTH_STALE");return client.studentStandingDepartureAuthorization.create({data:{seriesKey:current.seriesKey,versionNumber:current.versionNumber+1,studentId:current.studentId,guardianId:current.guardianId,status:"REVOKED",allowsSelfDeparture:false,eligibleClassSnapshot:current.eligibleClassSnapshot,allowedDaysJson:current.allowedDaysJson,allowedStartMinute:current.allowedStartMinute,allowedEndMinute:current.allowedEndMinute,effectiveFrom:current.effectiveFrom,effectiveUntil:current.effectiveUntil,conditions:current.conditions,guardianApprovalMethod:current.guardianApprovalMethod,guardianApprovedAt:current.guardianApprovedAt,supersedesPublicKey:current.publicKey,revocationReason:text(raw.reason,"Revocation reason",3,1000),createdByUserId:actor.user.id,createdByRole:actor.user.role}});
}

export async function recordUnauthorisedExit(client:any,actor:SafeExitActor,raw:any){
  requirePermission(actor,"RECORD_UNAUTHORISED_EXIT");const student=await loadActiveStudent(client,String(raw.studentId??""));await assertStudentScope(client,actor,student,new Date());const submissionKey=text(raw.submissionKey,"Incident submission key",8,160),existing=await client.studentDepartureRequest.findUnique({where:{submissionKey},include:requestInclude});if(existing){if(existing.studentId!==student.id||existing.requestedByUserId!==actor.user.id||existing.source!=="GATE_SECURITY_INCIDENT")throw new SafeExitError("Incident submission key is already in use.",409,"IDEMPOTENCY_CONFLICT");return serializeRequest(existing,actor);}const confirmed=raw.confirmed===true,status=confirmed?"UNAUTHORISED_EXIT_CONFIRMED":"UNAUTHORISED_EXIT_SUSPECTED",now=new Date(),requestNumber=`EXIT-${schoolDateKey()}-${randomBytes(4).toString("hex").toUpperCase()}`,incidentNumber=`INC-${schoolDateKey()}-${randomBytes(4).toString("hex").toUpperCase()}`,lastConfirmedLocation=optional(raw.lastConfirmedLocation,"Last confirmed location",200),lastConfirmedAt=raw.lastConfirmedAt?dateTime(raw.lastConfirmedAt,"Last confirmed time"):null;
  const row=await client.$transaction(async(tx:any)=>{const request=await tx.studentDepartureRequest.create({data:{requestNumber,submissionKey,source:"GATE_SECURITY_INCIDENT",studentId:student.id,academicYear:student.academicYear,reasonCategory:"UNAUTHORISED_EXIT",reasonDetails:text(raw.summary,"Safety incident summary",10,2000),calendarBasisJson:JSON.stringify({basis:"SAFETY_INCIDENT",schoolDateKey:schoolDateKey(now)}),intendedHandoverMethod:"NONE",intendedDepartureAt:now,status,consentState:"MISSING",restricted:true,requestedByUserId:actor.user.id,requestedByRole:actor.user.role}});const incident=await tx.studentDepartureIncident.create({data:{incidentNumber,studentId:student.id,requestId:request.id,status:confirmed?"CONFIRMED":"SUSPECTED",lastConfirmedLocation,lastConfirmedAt,linkedSupportRequestKey:optional(raw.linkedSupportRequestKey,"Restricted support request reference",120),reportedByUserId:actor.user.id,confirmedByUserId:confirmed?actor.user.id:null,confirmedAt:confirmed?now:null}});await tx.studentDepartureIncidentAction.create({data:{incidentId:incident.id,actionType:confirmed?"CONFIRM_UNAUTHORISED_EXIT":"LEADERSHIP_ESCALATION",summary:text(raw.summary,"Safety incident summary",10,2000),recordedByUserId:actor.user.id,recordedByRole:actor.user.role,idempotencyKey:`${incident.id}:reported`,occurredAt:now}});await tx.studentCampusPresenceEvent.create({data:{studentId:student.id,requestId:request.id,eventType:"UNAUTHORISED_EXIT_INCIDENT",schoolDateKey:schoolDateKey(now),locationLabel:lastConfirmedLocation,recordedByUserId:actor.user.id,source:"SAFETY_INCIDENT",idempotencyKey:`${request.id}:unauthorised-exit`,occurredAt:now}});await appendEvent(tx,request,actor,confirmed?"UNAUTHORISED_EXIT_CONFIRMED":"UNAUTHORISED_EXIT_SUSPECTED",null,status,`${request.id}:incident`,null,{incidentPublicKey:incident.publicKey,lastConfirmedAt:lastConfirmedAt?.toISOString()??null});const recipients=await notificationRecipients(tx,student.id),leadership=await leadershipUsers(tx,actor.user.id);await queueSafeExitNotifications(tx,{eventKey:`${request.id}:incident`,eventType:"UNAUTHORISED_EXIT",requestId:request.id,requestPublicKey:request.publicKey,actorUserId:actor.user.id,guardianId:recipients.guardianId,parentUserIds:recipients.parentUserIds,leadershipUserIds:leadership});return tx.studentDepartureRequest.findUniqueOrThrow({where:{id:request.id},include:requestInclude});});return serializeRequest(row,actor);
}

export async function recordIncidentAction(client:any,actor:SafeExitActor,incidentKey:string,raw:any){
  requirePermission(actor,"RECORD_UNAUTHORISED_EXIT");const incident=await client.studentDepartureIncident.findUnique({where:{publicKey:incidentKey},include:{request:true}});if(!incident)throw new SafeExitError("Restricted incident was not found.",404,"NOT_FOUND");const action=oneOf(raw.actionType,INCIDENT_ACTIONS,"Incident action"),expectedVersion=integer(raw.expectedVersion,"Expected version",1,1_000_000),summary=text(raw.summary,"Action summary",3,2000),now=new Date(),nextStatus=action==="CONFIRM_UNAUTHORISED_EXIT"?"CONFIRMED":action==="STUDENT_LOCATED"?"LOCATED":action==="RETURNED_TO_CAMPUS"?"RETURNED":action==="CLOSE_INCIDENT"?"CLOSED":incident.status;
  return client.$transaction(async(tx:any)=>{const claim=await tx.studentDepartureIncident.updateMany({where:{id:incident.id,version:expectedVersion},data:{status:nextStatus,version:{increment:1},lastConfirmedLocation:action==="LAST_LOCATION_UPDATE"?optional(raw.location,"Location",200):undefined,lastConfirmedAt:action==="LAST_LOCATION_UPDATE"?now:undefined,locatedAt:["STUDENT_LOCATED","RETURNED_TO_CAMPUS"].includes(action)?now:undefined,confirmedAt:action==="CONFIRM_UNAUTHORISED_EXIT"?now:undefined,confirmedByUserId:action==="CONFIRM_UNAUTHORISED_EXIT"?actor.user.id:undefined,closedAt:action==="CLOSE_INCIDENT"?now:undefined,closedByUserId:action==="CLOSE_INCIDENT"?actor.user.id:undefined}});if(claim.count!==1)throw conflict();await tx.studentDepartureIncidentAction.create({data:{incidentId:incident.id,actionType:action,summary,outcome:optional(raw.outcome,"Action outcome",1000),recordedByUserId:actor.user.id,recordedByRole:actor.user.role,idempotencyKey:text(raw.idempotencyKey,"Action idempotency key",8,160),occurredAt:now}});if(action==="RETURNED_TO_CAMPUS")await tx.studentCampusPresenceEvent.create({data:{studentId:incident.studentId,requestId:incident.requestId,eventType:"RETURNED_TO_CAMPUS",schoolDateKey:schoolDateKey(now),locationLabel:optional(raw.location,"Return location",200)??"School gate",recordedByUserId:actor.user.id,source:"SAFETY_INCIDENT_RETURN",idempotencyKey:`${incident.id}:incident-return`}});return tx.studentDepartureIncident.findUniqueOrThrow({where:{id:incident.id},include:{actions:{orderBy:{occurredAt:"asc"}}}});});
}

export async function liveCampusRoster(client:any,actor:SafeExitActor){
  requirePermission(actor,"VIEW_LIVE_CAMPUS_ROSTER");const today=schoolDateKey(),enrollments=await client.academicYearEnrollment.findMany({where:{status:"ACTIVE",student:{deletedAt:null,status:"Active"}},select:{academicYear:true,className:true,section:true,student:{select:{id:true,studentName:true,admissionNo:true}}},orderBy:[{className:"asc"},{section:"asc"},{student:{studentName:"asc"}}],take:10_000});const ids=enrollments.map((row:any)=>row.student.id),events=ids.length?await client.studentCampusPresenceEvent.findMany({where:{studentId:{in:ids},schoolDateKey:today},orderBy:{occurredAt:"desc"}}):[],latest=new Map<string,any>();for(const event of events)if(!latest.has(event.studentId))latest.set(event.studentId,event);return{schoolDateKey:today,generatedAt:new Date(),students:enrollments.map((row:any)=>{const event=latest.get(row.student.id),outside=event&&["EARLY_DEPARTURE","NORMAL_DISMISSAL","UNAUTHORISED_EXIT_INCIDENT"].includes(event.eventType);return{studentId:row.student.id,studentName:row.student.studentName,admissionNo:row.student.admissionNo,className:row.className,section:row.section,presence:outside?"OFF_CAMPUS":"ON_CAMPUS",lastEvent:event?{type:event.eventType,occurredAt:event.occurredAt}:null};})};
}

async function scopedRequest(client:any,actor:SafeExitActor,publicKey:string){const row=await client.studentDepartureRequest.findUnique({where:{publicKey},include:{...requestInclude,student:{select:{id:true,studentName:true,admissionNo:true,className:true,section:true,status:true,academicYear:true,guardians:{select:{guardianId:true}}}}}});if(!row)throw new SafeExitError("Student departure request was not found.",404,"NOT_FOUND");if(actor.user.role==="PARENT"&&(!actor.user.guardianId||!row.student.guardians.some((link:any)=>link.guardianId===actor.user.guardianId)))throw new SafeExitError("Student departure request was not found.",404,"NOT_FOUND");if(row.restricted&&!actor.permissions.has("VIEW_DEPARTURE_AUDIT")&&!actor.permissions.has("RECORD_UNAUTHORISED_EXIT"))throw new SafeExitError("Student departure request was not found.",404,"NOT_FOUND");return row;}
async function loadActiveStudent(client:any,id:string){const student=await client.student.findFirst({where:{id,deletedAt:null,status:"Active",academicYearEnrollments:{some:{status:"ACTIVE"}}},select:{id:true,studentName:true,admissionNo:true,className:true,section:true,status:true,academicYear:true,academicYearEnrollments:{where:{status:"ACTIVE"},select:{academicYear:true,className:true,section:true}}}});if(!student)throw new SafeExitError("An active enrolled Student was not found.",404,"STUDENT_NOT_FOUND");return student;}
async function assertStudentScope(client:any,actor:SafeExitActor,student:any,when:Date){if(actor.user.role==="PARENT")return linkedGuardian(client,student.id,actor.user.guardianId);if(actor.user.role==="TEACHER"){const enrollment=student.academicYearEnrollments[0],scope=await resolveTeacherAttendanceScope(client,actor.user,{academicYear:enrollment.academicYear,date:schoolDay(when)}),allowed=scope.targets.some((target)=>target.academicYear===enrollment.academicYear&&target.className===enrollment.className&&target.section===(enrollment.section??"")&&(target.source==="TIMETABLE"||target.attendanceDate?.getTime()===schoolDay(when).getTime()));if(!allowed)throw new SafeExitError("Teacher is not assigned to this Student's exact active class scope.",403,"TEACHER_SCOPE_DENIED");return null;}if(!["SUPER_ADMIN","DIRECTOR","PRINCIPAL","ADMIN","COMPUTER_OPERATOR","GATE_STAFF"].includes(actor.user.role))throw new SafeExitError("Student scope is unavailable for this role.",403,"STUDENT_SCOPE_DENIED");return null;}
async function linkedGuardian(client:any,studentId:string,guardianId:string|null|undefined){if(!guardianId)throw new SafeExitError("A current linked Guardian is required.",403,"GUARDIAN_LINK_REQUIRED");const link=await client.studentGuardian.findFirst({where:{studentId,guardianId,guardian:{status:"Active"},student:{deletedAt:null,status:"Active"}},include:{guardian:{select:{id:true,primaryMobile:true,displayName:true,status:true}}}});if(!link)throw new SafeExitError("A current linked Guardian is required.",403,"GUARDIAN_LINK_REQUIRED");return link;}
async function currentStandingAuthorization(client:any,studentId:string,when:Date,self:boolean){const rows=await client.studentStandingDepartureAuthorization.findMany({where:{studentId},orderBy:[{seriesKey:"asc"},{versionNumber:"desc"}]});const bySeries=new Map<string,any>();for(const row of rows)if(!bySeries.has(row.seriesKey))bySeries.set(row.seriesKey,row);const latest=[...bySeries.values()],day=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Kolkata",weekday:"long"}).format(when).toUpperCase(),parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Kolkata",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(when),minute=Number(parts.find((p)=>p.type==="hour")?.value)*60+Number(parts.find((p)=>p.type==="minute")?.value);const valid=latest.find((row:any)=>row.status==="ACTIVE"&&row.effectiveFrom<=when&&row.effectiveUntil>=when&&JSON.parse(row.allowedDaysJson).includes(day)&&minute>=row.allowedStartMinute&&minute<=row.allowedEndMinute&&(!self||row.allowsSelfDeparture));if(!valid)throw new SafeExitError(self?"No current standing Guardian authorisation permits unaccompanied self-departure.":"No current standing Guardian authorisation applies.",409,"STANDING_AUTH_UNAVAILABLE");return valid;}
async function validatePickupForApproval(client:any,row:any,raw:any){const method=oneOf(raw.handoverMethod??row.intendedHandoverMethod,HANDOVER_METHODS,"Handover method");if(method==="STUDENT_SELF_DEPARTURE"){await currentStandingAuthorization(client,row.studentId,dateTime(raw.approvedDepartureAt??row.intendedDepartureAt,"Departure time"),true);return{method,name:row.student.studentName,relationship:"SELF",contactMasked:null,parentEvidence:"CURRENT_STANDING_GUARDIAN_AUTHORISATION",verificationReference:null};}return{method,name:text(raw.recipientName,"Pickup person name",2,120),relationship:text(raw.relationship,"Pickup relationship",2,80),contactMasked:raw.contact?maskContact(text(raw.contact,"Pickup contact",5,40)):null,parentEvidence:text(raw.parentAuthorisationEvidence,"Parent authorisation evidence",5,300),verificationReference:optional(raw.verificationReference,"Verification reference",160)};}
async function assertCurrentConsent(client:any,row:any){const evidence=await client.studentDepartureConsentEvidence.findFirst({where:{requestId:row.id,outcome:"APPROVED"},orderBy:{recordedAt:"desc"}});if(!evidence?.guardianId||!evidence.guardianLinkSnapshotHash)throw new SafeExitError("Current verifiable Guardian consent is required.",409,"CONSENT_STALE");const link=await linkedGuardian(client,row.studentId,evidence.guardianId);if(guardianLinkHash(link)!==evidence.guardianLinkSnapshotHash)throw new SafeExitError("The Guardian link changed after consent; fresh consent is required.",409,"CONSENT_STALE");if(evidence.method==="STANDING_AUTHORIZATION"){const standing=await currentStandingAuthorization(client,row.studentId,row.intendedDepartureAt,row.intendedHandoverMethod==="STUDENT_SELF_DEPARTURE");if(standing.publicKey!==evidence.standingAuthorizationKey)throw new SafeExitError("Standing Guardian authorisation was superseded or revoked.",409,"CONSENT_STALE");}return evidence;}
function approvalSnapshot(row:any){return{requestPublicKey:row.publicKey,studentId:row.studentId,approvedAt:row.approvedAt?.toISOString(),approvedDepartureAt:row.approvedDepartureAt?.toISOString(),approvalExpiresAt:row.approvalExpiresAt?.toISOString(),handoverMethod:row.approvedHandoverMethod,recipientName:row.approvedRecipientName,relationship:row.approvedRelationship,parentEvidence:row.parentAuthorisationEvidence,emergencyOverride:row.emergencyOverride};}
async function currentCampusState(client:any,studentId:string,now=new Date()){const event=await client.studentCampusPresenceEvent.findFirst({where:{studentId,schoolDateKey:schoolDateKey(now)},orderBy:{occurredAt:"desc"}});return{event,onCampus:!event||!["EARLY_DEPARTURE","NORMAL_DISMISSAL","UNAUTHORISED_EXIT_INCIDENT"].includes(event.eventType)};}
async function notificationRecipients(client:any,studentId:string):Promise<{guardianId:string|null;parentUserIds:string[]}>{const links=await client.studentGuardian.findMany({where:{studentId,guardian:{status:"Active"}},select:{guardianId:true,guardian:{select:{users:{where:{isActive:true,lifecycleStatus:"ACTIVE"},select:{id:true,role:true}}}}},orderBy:{isPrimaryContact:"desc"}});const parentUserIds=[...new Set<string>(links.flatMap((link:any)=>link.guardian.users.filter((user:any)=>user.role==="PARENT").map((user:any)=>String(user.id))))];return{guardianId:links[0]?.guardianId??null,parentUserIds};}
async function leadershipUsers(client:any,exclude:string):Promise<string[]>{const rows=await client.user.findMany({where:{id:{not:exclude},isActive:true,lifecycleStatus:"ACTIVE",iamRoleAssignments:{some:{role:{in:["SUPER_ADMIN","DIRECTOR","PRINCIPAL"]},status:"ACTIVE"}}},select:{id:true},take:50});return rows.map((row:any)=>String(row.id));}
async function authorisedWitness(client:any,userKey:any,actorId:string,leadershipOnly=false){const key=text(userKey,"Second authorised confirmation",8,80),user=await client.user.findUnique({where:{iamPublicKey:key},select:{id:true,role:true,isActive:true,lifecycleStatus:true}});if(!user||user.id===actorId||!user.isActive||user.lifecycleStatus!=="ACTIVE"||!(leadershipOnly?["SUPER_ADMIN","DIRECTOR","PRINCIPAL"].includes(user.role):["SUPER_ADMIN","DIRECTOR","PRINCIPAL","ADMIN","COMPUTER_OPERATOR"].includes(user.role)))throw new SafeExitError("A different active authorised Staff confirmation is required.",403,"WITNESS_REQUIRED");return user;}
async function appendEvent(tx:any,row:any,actor:SafeExitActor,eventType:string,previousStatus:string|null,newStatus:string|null,idempotencyKey:string,reason:string|null,metadata:any){await tx.studentDepartureEvent.create({data:{requestId:row.id,eventType,actorUserId:actor.user.id,actorRole:actor.user.role,previousStatus,newStatus,entityVersion:row.version,reason,safeMetadataJson:metadata?JSON.stringify(metadata):null,idempotencyKey}});}
function serializeRequest(row:any,actor:SafeExitActor){const gate=actor.user.role==="GATE_STAFF"||actor.permissions.has("VERIFY_GATE_PASS"),parent=actor.user.role==="PARENT",restricted=row.restricted&&!actor.permissions.has("VIEW_DEPARTURE_AUDIT")&&!actor.permissions.has("RECORD_UNAUTHORISED_EXIT");return{requestKey:row.publicKey,requestNumber:row.requestNumber,source:row.source,status:row.status,consentState:row.consentState,version:row.version,student:{id:row.student.id,name:row.student.studentName,className:row.student.className,section:row.student.section},reasonCategory:gate?undefined:row.reasonCategory,reasonDetails:gate||restricted?undefined:row.reasonDetails,intendedDepartureAt:row.intendedDepartureAt,approvedDepartureAt:row.approvedDepartureAt,approvalExpiresAt:row.approvalExpiresAt,handoverMethod:row.approvedHandoverMethod??row.intendedHandoverMethod,recipient:row.approvedRecipientName?{name:row.approvedRecipientName,relationship:row.approvedRelationship,contactMasked:row.approvedContactMasked}:null,emergencyOverride:row.emergencyOverride,checkedOutAt:row.checkedOutAt,returnedAt:row.returnedAt,events:gate||parent?row.events.filter((event:any)=>!["EMERGENCY_OVERRIDE_AUTHORISED"].includes(event.eventType)).map(publicEvent):row.events.map(publicEvent),consentEvidence:gate||parent?undefined:row.consentEvidence,gatePasses:row.gatePasses.map((pass:any)=>({publicKey:pass.publicKey,status:pass.status,expiresAt:pass.expiresAt,consumedAt:pass.consumedAt,manualCodeLastTwo:pass.manualCodeLastTwo})),handovers:row.handovers.map((handover:any)=>({method:handover.handoverMethod,recipientName:handover.recipientName,relationship:handover.relationship,contactMasked:handover.contactMasked,verifiedAt:handover.verifiedAt})),incidents:restricted?undefined:row.incidents,notifications:parent?undefined:row.notificationOutbox.map((item:any)=>({channel:item.channel,status:item.status,retryCount:item.retryCount,queuedAt:item.queuedAt,sentAt:item.sentAt,deliveredAt:item.deliveredAt,failedAt:item.failedAt,providerReferenceSafe:item.providerReferenceSafe,failureCode:item.failureCode})),fallbackTasks:parent?undefined:row.fallbackTasks};}
function publicEvent(event:any){return{type:event.eventType,previousStatus:event.previousStatus,newStatus:event.newStatus,occurredAt:event.occurredAt,reason:event.reason};}
function validateRequest(raw:any){return{studentId:text(raw.studentId,"Student",1,80),submissionKey:text(raw.submissionKey,"Submission key",8,160),source:oneOf(raw.source,SAFE_EXIT_SOURCES,"Request source"),reasonCategory:text(raw.reasonCategory,"Reason category",3,80),reasonDetails:optional(raw.reasonDetails,"Reason details",2000),intendedHandoverMethod:oneOf(raw.intendedHandoverMethod,HANDOVER_METHODS,"Intended handover method"),intendedDepartureAt:dateTime(raw.intendedDepartureAt,"Intended departure time")};}
function guardianLinkHash(link:any){return link?createHash("sha256").update(`${link.guardianId}|${link.studentId}|${link.relationshipToStudent}|${link.isPrimaryContact}`).digest("hex"):null;}
function schoolDay(value:Date){return new Date(`${schoolDateKey(value)}T00:00:00.000Z`);}
function maskContact(value:string){const digits=value.replace(/\D/g,"");return digits.length>=4?`••••••${digits.slice(-4)}`:"masked";}
function normalizeName(value:any){return String(value??"").trim().replace(/\s+/g," ").toLocaleLowerCase("en-IN");}
function requirePermission(actor:SafeExitActor,permission:CanonicalPermission){if(!actor.permissions.has(permission))throw new SafeExitError("You do not have permission for this Student safety action.",403,"PERMISSION_DENIED");}
function requireRole(actor:SafeExitActor,role:string){if(actor.user.role!==role)throw new SafeExitError("This action is unavailable in the current role context.",403,"ROLE_DENIED");}
function requireLeadership(actor:SafeExitActor){if(!["SUPER_ADMIN","DIRECTOR","PRINCIPAL"].includes(actor.user.role))throw new SafeExitError("Principal or Director authority is required.",403,"LEADERSHIP_REQUIRED");}
function conflict(){return new SafeExitError("The request changed. Refresh and retry with the current version.",409,"VERSION_CONFLICT");}
function text(value:any,label:string,min:number,max:number){const result=String(value??"").trim();if(result.length<min||result.length>max)throw new SafeExitError(`${label} must be ${min}-${max} characters.`);return result;}
function optional(value:any,label:string,max:number){const result=String(value??"").trim();return result?text(result,label,1,max):null;}
function integer(value:any,label:string,min:number,max:number){const result=Number(value);if(!Number.isInteger(result)||result<min||result>max)throw new SafeExitError(`${label} is invalid.`);return result;}
function dateTime(value:any,label:string){const result=new Date(String(value??""));if(!Number.isFinite(result.getTime()))throw new SafeExitError(`${label} is invalid.`);return result;}
function oneOf<T extends readonly string[]>(value:any,values:T,label:string):T[number]{const result=String(value??"");if(!values.includes(result))throw new SafeExitError(`${label} is invalid.`);return result as T[number];}
function arrayOfText(value:any,label:string,min:number,max:number,itemMax:number){if(!Array.isArray(value)||value.length<min||value.length>max)throw new SafeExitError(`${label} must contain ${min}-${max} entries.`);return value.map((item,index)=>text(item,`${label} ${index+1}`,1,itemMax));}
