import type { PrismaClient } from "@prisma/client";

export const SUPPORT_BACKUP_KEYS = ["supportQueues","supportCategoryPolicies","supportRequests","supportRequestParticipants","supportRequestLinkedChildren","supportRequestEvents","supportRequestMessages","supportRequestAttachments","supportAssignments","supportEscalations","supportSlaSnapshots","supportResolutions","supportSatisfactionResponses","supportAccessEvents"] as const;
export type SupportBackupKey = (typeof SUPPORT_BACKUP_KEYS)[number];
export type SupportBackup = Record<SupportBackupKey, Record<string, unknown>[]>;
const DELEGATE: Record<SupportBackupKey,string> = { supportQueues:"supportQueue", supportCategoryPolicies:"supportCategoryPolicy", supportRequests:"supportRequest", supportRequestParticipants:"supportRequestParticipant", supportRequestLinkedChildren:"supportRequestLinkedChild", supportRequestEvents:"supportRequestEvent", supportRequestMessages:"supportRequestMessage", supportRequestAttachments:"supportRequestAttachment", supportAssignments:"supportAssignment", supportEscalations:"supportEscalation", supportSlaSnapshots:"supportSlaSnapshot", supportResolutions:"supportResolution", supportSatisfactionResponses:"supportSatisfactionResponse", supportAccessEvents:"supportAccessEvent" };
const FIELDS: Record<SupportBackupKey,readonly string[]> = {
  supportQueues:["id","publicKey","queueCode","name","description","status","allowedAssigneeRolesJson","confidentialityJson","version","createdByUserId","createdAt","updatedAt"],
  supportCategoryPolicies:["id","publicKey","categoryCode","label","status","queueId","permittedAssigneeRolesJson","defaultPriority","defaultConfidentiality","acknowledgmentTargetMinutes","firstResponseTargetMinutes","resolutionTargetMinutes","escalationTargetMinutes","workingHoursPolicyJson","attachmentsAllowed","linkedChildRequired","version","effectiveFrom","effectiveTo","createdByUserId","createdAt","updatedAt"],
  supportRequests:["id","publicKey","reference","submissionKey","source","requesterUserId","requesterRole","requesterStaffMemberId","requesterGuardianId","requesterName","requesterType","requesterIdentifier","requesterContactChannel","requesterContactValue","identityVerified","recordedByUserId","receivedAt","signedPaperReference","categoryPolicyId","queueId","priority","confidentiality","subject","originalStatement","status","version","acknowledgedAt","firstResponseAt","resolvedAt","closedAt","reopenedCount","complainedAboutUserId","linkedReceiptReference","linkedCorrectiveActionType","linkedCorrectiveActionReference","privacyNoticeVersion","consentRecordedAt","duplicateFingerprint","retentionReviewAt","legalHold","archivedAt","createdAt","updatedAt"],
  supportRequestParticipants:["id","requestId","participantType","userId","guardianId","staffMemberId","displayLabel","visibilityScope","status","addedByUserId","endedAt","createdAt"],
  supportRequestLinkedChildren:["id","requestId","studentId","admissionReferenceMasked","childDisplaySnapshot","classSnapshot","guardianLinkVerified","guardianLinkVerifiedAt","guardianLinkVerifiedByUserId","createdAt"],
  supportRequestEvents:["id","publicKey","requestId","eventType","actorUserId","actorRole","previousStatus","newStatus","entityVersion","reason","safeMetadataJson","idempotencyKey","occurredAt","createdAt"],
  supportRequestMessages:["id","publicKey","requestId","messageType","body","authorUserId","authorRole","authorLabel","restricted","correctsMessageId","createdAt"],
  supportRequestAttachments:["id","publicKey","requestId","messageId","storageKey","safeDisplayName","mediaType","extension","byteSize","sha256","width","height","pageCount","visibility","intakeScope","recoveryStatus","backupArtifactSha256","backupKeyVersion","backupVerifiedAt","retentionReviewAt","createdByUserId","createdAt"],
  supportAssignments:["id","publicKey","requestId","queueId","assigneeUserId","assignedByUserId","reason","status","activeKey","assignedAt","endedAt","createdAt"],
  supportEscalations:["id","publicKey","requestId","escalationLevel","reasonCode","reason","fromQueueId","toQueueId","status","idempotencyKey","escalatedByUserId","escalatedAt","resolvedAt","createdAt"],
  supportSlaSnapshots:["id","publicKey","requestId","categoryPolicyId","policyVersion","acknowledgmentTargetAt","firstResponseTargetAt","resolutionTargetAt","escalationTargetAt","workingHoursPolicyJson","pausedAt","totalPausedSeconds","pauseState","createdAt"],
  supportResolutions:["id","publicKey","requestId","resolutionVersion","resolutionCategory","requesterVisibleSummary","internalActionSummary","linkedActionType","linkedActionReference","resolvedByUserId","resolvedAt","supersededAt","createdAt"],
  supportSatisfactionResponses:["id","publicKey","requestId","resolutionId","issueUnderstood","responseClear","issueResolved","rating","comment","declined","submittedByUserId","createdAt"],
  supportAccessEvents:["id","publicKey","requestId","actorUserId","sourceHash","identifierHash","eventType","outcome","safeMetadataJson","occurredAt","createdAt"]
};

export async function loadSupportBackup(client: PrismaClient): Promise<SupportBackup> { const entries = await Promise.all(SUPPORT_BACKUP_KEYS.map(async (key) => { const delegate=(client as any)[DELEGATE[key]]; return [key,delegate?.findMany?await delegate.findMany({orderBy:{createdAt:"asc"}}):[]] as const; })); return Object.fromEntries(entries) as SupportBackup; }
export function validateSupportBackupRows(root: Record<string,unknown>): SupportBackup {
  const output = Object.fromEntries(SUPPORT_BACKUP_KEYS.map((key) => [key, boundedRows(root[key], key, new Set(FIELDS[key]))])) as SupportBackup;
  const ids=(key:SupportBackupKey)=>new Set(output[key].map((row,index)=>required(row.id,`${key}[${index}].id`))), requests=ids("supportRequests"), queues=ids("supportQueues"), policies=ids("supportCategoryPolicies"), messages=ids("supportRequestMessages"), resolutions=ids("supportResolutions");
  for(const key of SUPPORT_BACKUP_KEYS) unique(output[key],"id",key); for(const key of SUPPORT_BACKUP_KEYS.filter((key)=>FIELDS[key].includes("publicKey"))) unique(output[key],"publicKey",key);
  links(output.supportCategoryPolicies,"queueId",queues); links(output.supportRequests,"queueId",queues); links(output.supportRequests,"categoryPolicyId",policies); for(const key of ["supportRequestParticipants","supportRequestLinkedChildren","supportRequestEvents","supportRequestMessages","supportRequestAttachments","supportAssignments","supportEscalations","supportSlaSnapshots","supportResolutions","supportSatisfactionResponses"] as const) links(output[key],"requestId",requests); links(output.supportAccessEvents,"requestId",requests,true); links(output.supportRequestAttachments,"messageId",messages,true); links(output.supportRequestMessages,"correctsMessageId",messages,true); links(output.supportAssignments,"queueId",queues); links(output.supportSlaSnapshots,"categoryPolicyId",policies); links(output.supportSatisfactionResponses,"resolutionId",resolutions);
  for(const [index,row] of output.supportRequestAttachments.entries()) { if(!/^[a-f0-9]{64}$/.test(required(row.sha256,`supportRequestAttachments[${index}].sha256`))||!/^[a-f0-9]{2}\/[a-f0-9]{2}\/[a-f0-9-]{36}\.(?:pdf|png|jpg|webp)$/.test(required(row.storageKey,`supportRequestAttachments[${index}].storageKey`))) throw new Error("Support attachment backup contains an invalid hash or private storage key."); }
  const keys=SUPPORT_BACKUP_KEYS.flatMap((key)=>output[key].flatMap((row)=>Object.keys(row).map((field)=>field.toLowerCase()))); for(const forbidden of ["password","passwordhash","sessionsecret","resettoken","encryptionkey","securityanswer"]) if(keys.includes(forbidden)) throw new Error("Support backup contains prohibited credential material.");
  return output;
}
export async function restoreSupportBackup(client: PrismaClient, backup: SupportBackup) { const result=Object.fromEntries(SUPPORT_BACKUP_KEYS.map((key)=>[key,{created:0,skipped:0,errors:[] as string[]}])) as Record<SupportBackupKey,{created:number;skipped:number;errors:string[]}>; for(const key of SUPPORT_BACKUP_KEYS){const delegate=(client as any)[DELEGATE[key]];for(const[index,row]of backup[key].entries())try{const id=required(row.id,`${key}[${index}].id`);if(await delegate.findUnique({where:{id},select:{id:true}})){result[key].skipped++;continue;}await delegate.create({data:row});result[key].created++;}catch(error){result[key].errors.push(`${key}[${index}]: ${error instanceof Error?error.message:"restore failed"}`);}} return result; }
function boundedRows(value:unknown,label:string,allowed:Set<string>){if(value===undefined)return[];if(!Array.isArray(value)||value.length>100_000)throw new Error(`${label} must be a bounded array.`);return value.map((item,index)=>{if(!item||typeof item!=="object"||Array.isArray(item))throw new Error(`${label}[${index}] must be an object.`);const row=item as Record<string,unknown>;if(!row.id||Object.keys(row).some((key)=>!allowed.has(key)))throw new Error(`${label}[${index}] contains unsupported fields.`);return row;});}
function required(value:unknown,label:string){const result=String(value??"").trim();if(!result||result.length>10_000)throw new Error(`${label} is required and bounded.`);return result;}
function unique(rows:Record<string,unknown>[],field:string,label:string){const values=new Set<string>();rows.forEach((row,index)=>{const value=required(row[field],`${label}[${index}].${field}`);if(values.has(value))throw new Error(`${label}.${field} is duplicated.`);values.add(value);});}
function links(rows:Record<string,unknown>[],field:string,allowed:Set<string>,optional=false){rows.forEach((row,index)=>{if(optional&&(row[field]==null||row[field]===""))return;if(!allowed.has(required(row[field],`${field}[${index}]`)))throw new Error(`Support backup relationship ${field} is invalid.`);});}
