import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { PrismaClient } from "@prisma/client";
import { unzipSync, zipSync } from "fflate";
import { decryptCloudBackup, encryptCloudBackup } from "@/lib/cloud-backup-container";
import { readSupportFile } from "@/lib/support-files";

const MANIFEST="manifest.json",MAX_ASSETS=10_000,MAX_TOTAL=500*1024*1024;
type Manifest={format:"NALANDA_SUPPORT_ASSETS_V1";createdAt:string;attachments:Array<{attachmentPublicKey:string;requestPublicKey:string;messagePublicKey:string|null;entry:string;sha256:string;byteSize:number;mediaType:string;visibility:string}>};
export class SupportAssetBackupError extends Error {}

export async function createAndVerifySupportAssetBackup(client:PrismaClient,input:{artifactPath:string;key:Buffer;keyVersion:string;restoreRoots:[string,string];attachmentPublicKeys?:string[];createdAt?:Date}){
  if(input.key.length!==32)throw new SupportAssetBackupError("Support asset backup requires a 32-byte encryption key.");const requested=[...new Set(input.attachmentPublicKeys??[])];if(requested.length>MAX_ASSETS)throw new SupportAssetBackupError("Support asset backup exceeds the bounded attachment count.");
  const attachments=await client.supportRequestAttachment.findMany({where:requested.length?{publicKey:{in:requested}}:undefined,include:{request:{select:{publicKey:true}},message:{select:{publicKey:true}}},orderBy:{publicKey:"asc"},take:MAX_ASSETS+1});if(attachments.length>MAX_ASSETS||(requested.length&&attachments.length!==requested.length))throw new SupportAssetBackupError("Support asset backup selection is invalid or incomplete.");
  const createdAt=input.createdAt??new Date(),entries:Record<string,Uint8Array>={},manifest:Manifest={format:"NALANDA_SUPPORT_ASSETS_V1",createdAt:createdAt.toISOString(),attachments:[]};let totalBytes=0;
  for(const row of attachments){const bytes=await readSupportFile(row.storageKey,row.sha256);totalBytes+=bytes.length;if(totalBytes>MAX_TOTAL)throw new SupportAssetBackupError("Support asset backup exceeds the bounded byte limit.");entries[row.storageKey]=bytes;manifest.attachments.push({attachmentPublicKey:row.publicKey,requestPublicKey:row.request.publicKey,messagePublicKey:row.message?.publicKey??null,entry:row.storageKey,sha256:row.sha256,byteSize:row.byteSize,mediaType:row.mediaType,visibility:row.visibility});}
  entries[MANIFEST]=Buffer.from(JSON.stringify(manifest),"utf8");const encrypted=await encryptCloudBackup(Buffer.from(zipSync(entries,{level:9})),{backupFormatVersion:37,createdAt,encryptionKeyVersion:input.keyVersion,key:input.key});await mkdir(path.dirname(path.resolve(input.artifactPath)),{recursive:true});await writeFile(input.artifactPath,encrypted.bytes,{flag:"wx",mode:0o600});const persisted=await readFile(input.artifactPath),artifactSha256=sha(persisted);const firstRestore=await restoreSupportAssetBackup(persisted,{key:input.key,targetRoot:input.restoreRoots[0]}),secondRestore=await restoreSupportAssetBackup(persisted,{key:input.key,targetRoot:input.restoreRoots[1]});if(firstRestore.assetDigest!==secondRestore.assetDigest||firstRestore.ownershipDigest!==secondRestore.ownershipDigest||firstRestore.attachmentCount!==attachments.length)throw new SupportAssetBackupError("Two isolated support-asset restores do not match.");if(attachments.length)await client.supportRequestAttachment.updateMany({where:{id:{in:attachments.map((row)=>row.id)}},data:{recoveryStatus:"VERIFIED",backupArtifactSha256:artifactSha256,backupKeyVersion:input.keyVersion,backupVerifiedAt:createdAt}});return{artifactSha256,attachmentCount:attachments.length,totalBytes,encryptedBytes:persisted.length,firstRestore,secondRestore};
}
export async function restoreSupportAssetBackup(container:Buffer,input:{key:Buffer;targetRoot:string}){const decrypted=await decryptCloudBackup(container,{key:input.key,maximumPlaintextBytes:MAX_TOTAL+20*1024*1024});let archive:Record<string,Uint8Array>;try{archive=unzipSync(decrypted.plaintext);}catch{throw new SupportAssetBackupError("The decrypted support asset archive is malformed.");}const manifestBytes=archive[MANIFEST];if(!manifestBytes)throw new SupportAssetBackupError("The encrypted support asset manifest is missing.");let manifest:Manifest;try{manifest=JSON.parse(Buffer.from(manifestBytes).toString("utf8"));}catch{throw new SupportAssetBackupError("The encrypted support asset manifest is invalid.");}validate(manifest,archive);const root=path.resolve(input.targetRoot),stat=await lstat(root).catch(()=>null);if(stat?.isSymbolicLink()||(stat&&!stat.isDirectory()))throw new SupportAssetBackupError("The isolated support restore target is unsafe.");await mkdir(root,{recursive:true});const asset=createHash("sha256"),ownership=createHash("sha256");let idempotent=true;for(const row of manifest.attachments){const bytes=Buffer.from(archive[row.entry]);if(bytes.length!==row.byteSize||sha(bytes)!==row.sha256)throw new SupportAssetBackupError("A restored support attachment failed exact SHA-256 verification.");const target=safePath(root,row.entry);await mkdir(path.dirname(target),{recursive:true});const current=await readFile(target).catch(()=>null);if(current){if(sha(current)!==row.sha256)throw new SupportAssetBackupError("The isolated support restore target contains a conflicting attachment.");}else{await writeFile(target,bytes,{flag:"wx",mode:0o600});idempotent=false;}asset.update(row.entry).update(row.sha256);ownership.update(row.attachmentPublicKey).update(row.requestPublicKey).update(row.messagePublicKey??"").update(row.visibility).update(row.mediaType);}return{attachmentCount:manifest.attachments.length,manifestSha256:sha(manifestBytes),assetDigest:asset.digest("hex"),ownershipDigest:ownership.digest("hex"),idempotent};}
function validate(manifest:Manifest,archive:Record<string,Uint8Array>){if(!manifest||manifest.format!=="NALANDA_SUPPORT_ASSETS_V1"||!Array.isArray(manifest.attachments)||manifest.attachments.length>MAX_ASSETS||new Date(manifest.createdAt).toISOString()!==manifest.createdAt)throw new SupportAssetBackupError("The encrypted support asset manifest is unsupported.");const expected=[MANIFEST,...manifest.attachments.map((row)=>row.entry)].sort(),actual=Object.keys(archive).sort();if(expected.length!==actual.length||expected.some((value,index)=>value!==actual[index]))throw new SupportAssetBackupError("The encrypted support asset archive contains unexpected entries.");const keys=new Set<string>(),entries=new Set<string>();for(const row of manifest.attachments){if(!uuid(row.attachmentPublicKey)||!uuid(row.requestPublicKey)||(row.messagePublicKey!==null&&!uuid(row.messagePublicKey))||keys.has(row.attachmentPublicKey)||entries.has(row.entry)||!/^[a-f0-9]{2}\/[a-f0-9]{2}\/[a-f0-9-]{36}\.(?:pdf|png|jpg|webp)$/.test(row.entry)||!/^[a-f0-9]{64}$/.test(row.sha256)||!Number.isSafeInteger(row.byteSize)||row.byteSize<1||row.byteSize>5*1024*1024||!["REQUESTER_VISIBLE","INTERNAL_NOTE"].includes(row.visibility))throw new SupportAssetBackupError("The encrypted support asset manifest contains an invalid entry.");keys.add(row.attachmentPublicKey);entries.add(row.entry);}}
function safePath(root:string,entry:string){const target=path.resolve(root,...entry.split("/"));if(!target.startsWith(`${root}${path.sep}`))throw new SupportAssetBackupError("The encrypted support asset archive contains a traversal path.");return target;}
function uuid(value:unknown){return typeof value==="string"&&/^[a-f0-9-]{36}$/.test(value);}
function sha(value:Uint8Array){return createHash("sha256").update(value).digest("hex");}
