type Row = Record<string, unknown>;
const keys = {
  teacherAnalyticsReviewCycles: ["id","cycleCode","academicYear","title","periodStart","periodEnd","status","minimumStudentCohort","metricDefinitionVersion","notes","cancellationReason","createdByUserId","openedByUserId","finalisedByUserId","archivedByUserId","cancelledByUserId","openedAt","finalisedAt","archivedAt","cancelledAt","createdAt","updatedAt"],
  teacherAnalyticsSnapshots: ["id","reviewCycleId","staffMemberId","academicYear","metricDefinitionVersion","sourceCalculatedAt","workloadJson","attendanceJson","leaveJson","substituteJson","homeworkJson","assessmentWorkflowJson","studentOutcomeJson","reportCardJson","kgRubricJson","dataQualityJson","contextJson","snapshotHash","createdByUserId","createdAt"],
  teacherAnalyticsReviews: ["id","snapshotId","status","strengthsNote","supportNeededNote","agreedActionsNote","leadershipContextNote","teacherResponse","nextReviewDate","createdByUserId","sharedByUserId","finalisedByUserId","sharedAt","teacherRespondedAt","finalisedAt","createdAt","updatedAt"],
  teacherAnalyticsEvents: ["id","reviewCycleId","snapshotId","reviewId","eventType","eventDate","reason","notes","recordedByUserId","createdAt"]
} as const;
const required = (value: unknown, label: string) => { const text=String(value??"").trim(); if(!text)throw new Error(`${label} is required`); return text; };
const date = (value: unknown, label: string) => { const parsed=new Date(String(value)); if(Number.isNaN(parsed.getTime()))throw new Error(`${label} must be a valid date`); return parsed; };
const rows = (root: Row, key: keyof typeof keys, requiredKeys: string[]) => {
  const value=root[key]; if(value===undefined)return []; if(!Array.isArray(value))throw new Error(`${key} must be an array`);
  return value.map((item,index)=>{if(!item||typeof item!=="object"||Array.isArray(item))throw new Error(`${key}[${index}] must be an object`);const row=item as Row;const unknown=Object.keys(row).filter((field)=>!(keys[key] as readonly string[]).includes(field));if(unknown.length)throw new Error(`${key}[${index}] contains unknown field: ${unknown[0]}`);for(const field of requiredKeys)required(row[field],`${key}[${index}].${field}`);return row;});
};
const unique = (data: Row[], label: string, fingerprint: (row: Row) => string) => { const seen=new Set<string>();for(const [index,row] of data.entries()){const value=fingerprint(row);if(seen.has(value))throw new Error(`${label}[${index}] duplicates ${value}`);seen.add(value);}return seen;};
const parsedJson = (value: unknown, label: string) => { try { const out=JSON.parse(required(value,label));if(!out||typeof out!=="object")throw new Error();return out; } catch { throw new Error(`${label} must contain validated analytics JSON`); } };
const containsForbidden = (value: unknown): boolean => {
  if(Array.isArray(value))return value.some(containsForbidden);
  if(!value||typeof value!=="object")return false;
  return Object.entries(value as Row).some(([key,child])=>["studentName","admissionNo","phone1","phone2","whatsappNumber","address","marksObtained","rawMarks"].includes(key)||containsForbidden(child));
};

export function validateTeacherAnalyticsBackupRows(root: Row, links: { staffMemberIds: Set<string> }) {
  const cycles=rows(root,"teacherAnalyticsReviewCycles",["id","cycleCode","academicYear","title","periodStart","periodEnd","status","minimumStudentCohort","metricDefinitionVersion"]);
  const cycleIds=unique(cycles,"teacherAnalyticsReviewCycles",(row)=>required(row.id,"cycle id"));unique(cycles,"teacherAnalyticsReviewCycles",(row)=>required(row.cycleCode,"cycle code").toUpperCase());
  for(const [index,row] of cycles.entries()){const prefix=`teacherAnalyticsReviewCycles[${index}]`;const start=date(row.periodStart,`${prefix}.periodStart`),end=date(row.periodEnd,`${prefix}.periodEnd`),status=required(row.status,`${prefix}.status`);if(end<start)throw new Error(`${prefix}.periodEnd cannot precede periodStart`);if(!Number.isInteger(Number(row.minimumStudentCohort))||Number(row.minimumStudentCohort)<5)throw new Error(`${prefix}.minimumStudentCohort must be at least 5`);if(!["DRAFT","OPEN","SNAPSHOTS_GENERATED","UNDER_REVIEW","FINALISED","ARCHIVED","CANCELLED"].includes(status))throw new Error(`${prefix}.status is unsupported`);if(status==="CANCELLED"&&!String(row.cancellationReason??"").trim())throw new Error(`${prefix} cancellation requires a reason`);}
  const snapshots=rows(root,"teacherAnalyticsSnapshots",["id","reviewCycleId","staffMemberId","academicYear","metricDefinitionVersion","sourceCalculatedAt","workloadJson","attendanceJson","leaveJson","substituteJson","homeworkJson","assessmentWorkflowJson","studentOutcomeJson","reportCardJson","kgRubricJson","dataQualityJson","contextJson","snapshotHash"]);
  const snapshotIds=unique(snapshots,"teacherAnalyticsSnapshots",(row)=>required(row.id,"snapshot id"));unique(snapshots,"teacherAnalyticsSnapshots",(row)=>`${row.reviewCycleId}|${row.staffMemberId}`);
  const jsonFields=["workloadJson","attendanceJson","leaveJson","substituteJson","homeworkJson","assessmentWorkflowJson","studentOutcomeJson","reportCardJson","kgRubricJson","dataQualityJson","contextJson"];
  for(const [index,row] of snapshots.entries()){const prefix=`teacherAnalyticsSnapshots[${index}]`,cycleId=required(row.reviewCycleId,`${prefix}.reviewCycleId`),staffId=required(row.staffMemberId,`${prefix}.staffMemberId`);if(!cycleIds.has(cycleId)||!links.staffMemberIds.has(staffId))throw new Error(`${prefix} has an invalid cycle or StaffMember link`);date(row.sourceCalculatedAt,`${prefix}.sourceCalculatedAt`);const payload=Object.fromEntries(jsonFields.map((field)=>[field.replace(/Json$/,""),parsedJson(row[field],`${prefix}.${field}`)]));if(containsForbidden(payload))throw new Error(`${prefix} contains prohibited Student identity, contact, or raw-mark data`);if(!/^[a-f0-9]{64}$/i.test(required(row.snapshotHash,`${prefix}.snapshotHash`)))throw new Error(`${prefix}.snapshotHash must be SHA-256`);}
  const reviews=rows(root,"teacherAnalyticsReviews",["id","snapshotId","status"]);
  const reviewIds=unique(reviews,"teacherAnalyticsReviews",(row)=>required(row.id,"review id"));unique(reviews,"teacherAnalyticsReviews",(row)=>required(row.snapshotId,"review snapshot"));
  for(const [index,row] of reviews.entries()){const prefix=`teacherAnalyticsReviews[${index}]`;if(!snapshotIds.has(required(row.snapshotId,`${prefix}.snapshotId`)))throw new Error(`${prefix} has an invalid snapshot link`);const status=required(row.status,`${prefix}.status`);if(!["NOT_STARTED","DRAFT","SHARED_WITH_TEACHER","TEACHER_RESPONSE_RECEIVED","FINALISED"].includes(status))throw new Error(`${prefix}.status is unsupported`);if(status==="FINALISED"&&!row.finalisedAt)throw new Error(`${prefix}.finalisedAt is required`);}
  const events=rows(root,"teacherAnalyticsEvents",["id","reviewCycleId","eventType","eventDate"]);unique(events,"teacherAnalyticsEvents",(row)=>required(row.id,"event id"));
  for(const [index,row] of events.entries()){const prefix=`teacherAnalyticsEvents[${index}]`;if(!cycleIds.has(required(row.reviewCycleId,`${prefix}.reviewCycleId`)))throw new Error(`${prefix} has an invalid cycle link`);if(row.snapshotId&&!snapshotIds.has(String(row.snapshotId)))throw new Error(`${prefix} has an invalid snapshot link`);if(row.reviewId&&!reviewIds.has(String(row.reviewId)))throw new Error(`${prefix} has an invalid review link`);date(row.eventDate,`${prefix}.eventDate`);}
  return {teacherAnalyticsReviewCycles:cycles,teacherAnalyticsSnapshots:snapshots,teacherAnalyticsReviews:reviews,teacherAnalyticsEvents:events};
}
