import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/auth";
import { PageHeader } from "@/components/ui";
import { getEffectivePermissions,permissionSetCan } from "@/lib/role-permissions";
import { getSchoolSettings } from "@/lib/school-settings";
import { SubstituteForm } from "@/components/substitute-form";
import { localSubstituteDateText } from "@/lib/substitutes";

export default async function NewSubstitutePage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const user=await requirePermission("MANAGE_SUBSTITUTES");const [permissions,settings,sp,staff,timetable]=await Promise.all([getEffectivePermissions(prisma,user.role),getSchoolSettings(prisma),searchParams,prisma.staffMember.findMany({where:{status:"ACTIVE"},orderBy:{fullName:"asc"},select:{id:true,staffCode:true,fullName:true,displayName:true,designation:true,department:true,primarySubject:true}}),prisma.timetableAssignment.findMany({include:{classSection:true,subject:true,teacher:{include:{staffMember:{select:{id:true}}}}},orderBy:[{classSection:{className:"asc"}},{subject:{name:"asc"}}]})]);const defaults={assignmentDate:sp.assignmentDate??localSubstituteDateText(),academicYear:settings.academicYear,leaveRequestId:sp.leaveRequestId??"",absentStaffMemberId:sp.absentStaffMemberId??"",timetableAssignmentId:sp.timetableAssignmentId??"",className:sp.className??"",section:sp.section??"",subject:sp.subject??"",periodLabel:sp.periodLabel??"",periodStartTime:sp.periodStartTime??"",periodEndTime:sp.periodEndTime??"",reason:sp.reason??(sp.leaveRequestId?"APPROVED_LEAVE":"MANUAL")};const timetableAssignments=timetable.map(row=>({id:row.id,teacherStaffMemberId:row.teacher.staffMember?.id??null,label:`${row.classSection.displayName} - ${row.subject.name} - ${row.teacher.name}`,className:row.classSection.className,section:row.classSection.section,subject:row.subject.name}));return <div className="page"><PageHeader title="New Substitute Plan" description="Save a draft or assign an available substitute after reviewing conflicts and advisory suggestions."/><SubstituteForm staff={staff} timetableAssignments={timetableAssignments} defaults={defaults} canManage canAssign={permissionSetCan(permissions,"ASSIGN_SUBSTITUTES")} canConfirm={permissionSetCan(permissions,"CONFIRM_SUBSTITUTES")}/></div>}
