import { notFound } from "next/navigation";
import { PrintButton } from "@/components/print-button";
import { requirePermission } from "@/lib/auth";
import { displayDate } from "@/lib/format";
import { parseHandoverItems } from "@/lib/class-x-package-handover";
import { parseClassXSnapshot } from "@/lib/class-x-document-packages";
import { prisma } from "@/lib/prisma";
import { getSchoolSettings } from "@/lib/school-settings";

export default async function ClassXHandoverPrintPage({ params }: { params: Promise<{ id: string; handoverId: string }> }) {
  await requirePermission("VIEW_CLASS_X_PACKAGES"); const p = await params;
  const [pkg, handover, settings] = await Promise.all([prisma.classXDocumentPackage.findUnique({ where: { id: p.id }, include: { student: { select: { studentName: true, admissionNo: true } }, charge: { include: { linkedMiscIncomeReceipt: { select: { receiptNumber: true } } } } } }), prisma.classXPackageHandover.findFirst({ where: { id: p.handoverId, packageId: p.id } }), getSchoolSettings(prisma)]);
  if (!pkg || !handover) notFound();
  const actor = handover.handedOverByUserId ? await prisma.user.findUnique({ where: { id: handover.handedOverByUserId }, select: { name: true, role: true } }) : null;
  const items = parseHandoverItems(handover.itemSnapshotJson), template = parseClassXSnapshot(pkg.templateSnapshotJson);
  return <main className="class-x-handover-print"><div className="no-print page-actions"><PrintButton /></div><header><img src={settings.logoPath} alt="School logo" /><h1>{settings.schoolName}</h1><p>{settings.addressLine1}, {settings.city}</p><h2>Class X Document Package Handover Acknowledgment</h2></header><div className="print-meta"><span><strong>Package:</strong> {pkg.packageNumber}</span><span><strong>Handover:</strong> {handover.handoverNumber}</span><span><strong>Date:</strong> {displayDate(handover.handoverDate)}</span></div><dl className="certificate-field-table"><div><dt>Student</dt><dd>{pkg.student.studentName}</dd></div><div><dt>Admission number</dt><dd>{pkg.student.admissionNo}</dd></div><div><dt>Class / academic year</dt><dd>Class X / {pkg.academicYear}</dd></div><div><dt>Recipient</dt><dd>{handover.recipientName} · {handover.recipientType.replaceAll("_", " ")}{handover.relationship ? ` · ${handover.relationship}` : ""}</dd></div><div><dt>Payment status</dt><dd>{pkg.charge?.status.replaceAll("_", " ") ?? "NOT REQUIRED"}{template.parentReceiptVisible && pkg.charge?.linkedMiscIncomeReceipt ? ` · Receipt ${pkg.charge.linkedMiscIncomeReceipt.receiptNumber}` : ""}</dd></div><div><dt>Staff</dt><dd>{actor ? `${actor.name} · ${actor.role.replaceAll("_", " ")}` : "Authorised school staff"}</dd></div></dl><section><h3>Physical documents handed over</h3><div className="table-wrap"><table><thead><tr><th>#</th><th>Safe document name</th><th>Issuer</th></tr></thead><tbody>{items.map((item: any, index: number) => <tr key={item.itemKey}><td>{index + 1}</td><td>{item.displayName}</td><td>{item.issuerType}</td></tr>)}</tbody></table></div></section><p className="acknowledgment">{handover.recipientAcknowledgementText}</p><div className="signature-grid"><div><span>Recipient physical signature</span></div><div><span>School physical signature</span></div></div><footer><p>Operational school handover record only. Typed names are not digital signatures. No Board certificate body, serial/security data, sensitive demographic data, Parent contact, bank details, internal notes, or raw IDs are included.</p><strong>ORIGINAL · COMPLETED HANDOVER RECORD · VERSION 1</strong></footer></main>;
}
