import { safeClientError } from "@/lib/client-errors";
import { Prisma } from "@prisma/client";
import { NextRequest, NextResponse } from "next/server";
import { requireApiPermission } from "@/lib/auth";
import { localDate } from "@/lib/expenses";
import { createMiscReceipt, miscReceiptInclude, serializeMiscReceipt } from "@/lib/misc-income";
import { prisma } from "@/lib/prisma";
import { hasRolePermission } from "@/lib/role-permissions";

export async function GET(request: NextRequest) { const auth = await requireApiPermission("VIEW_MISC_INCOME"); if (auth.response) return auth.response; try { const p = request.nextUrl.searchParams; const where: Prisma.MiscIncomeReceiptWhereInput = {}; for (const field of ["paymentMethod", "status", "studentId"] as const) if (p.get(field)) where[field] = p.get(field)!; if (p.get("itemId")) where.lines = { some: { itemId: p.get("itemId")! } }; if (p.get("from") || p.get("to")) where.receiptDate = { ...(p.get("from") ? { gte: localDate(p.get("from")) } : {}), ...(p.get("to") ? { lt: new Date(localDate(p.get("to")).getTime() + 86_400_000) } : {}) }; const sensitive = await hasRolePermission(prisma, auth.user.role, "MANAGE_MISC_INCOME"); const rows = await prisma.miscIncomeReceipt.findMany({ where, include: miscReceiptInclude, orderBy: [{ receiptDate: "desc" }, { createdAt: "desc" }], take: 500 }); const sum = (predicate: (row: typeof rows[number]) => boolean) => rows.filter(predicate).reduce((total, row) => total.add(row.netAmount), new Prisma.Decimal(0)).toFixed(2); return NextResponse.json({ receipts: rows.map((row) => serializeMiscReceipt(row, sensitive)), summary: { active: sum((row) => row.status === "ACTIVE"), cash: sum((row) => row.status === "ACTIVE" && row.paymentMethod === "CASH"), nonCash: sum((row) => row.status === "ACTIVE" && row.paymentMethod !== "CASH"), cancelled: sum((row) => row.status === "CANCELLED") } }); } catch (error) { return NextResponse.json({ error: safeClientError(error, "Unable to list miscellaneous income") }, { status: 400 }); } }
export async function POST(request: NextRequest) { const auth = await requireApiPermission("MANAGE_MISC_INCOME"); if (auth.response) return auth.response; try { return NextResponse.json({ receipt: serializeMiscReceipt(await createMiscReceipt(prisma, await request.json(), auth.user.id)) }, { status: 201 }); } catch (error) { return NextResponse.json({ error: safeClientError(error, "Unable to issue receipt") }, { status: 400 }); } }
