import Link from "next/link";
import { PageHeader, StatusBadge } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getEffectivePermissions, permissionSetCan } from "@/lib/role-permissions";
import { publicWebsiteReadinessReport } from "@/lib/public-website-reports";

export default async function WebsiteAdminPage(){
  const user=await requirePermission("VIEW_PUBLIC_WEBSITE_ADMIN");
  const [report,permissions]=await Promise.all([publicWebsiteReadinessReport(prisma),getEffectivePermissions(prisma,user.role)]);
  const canDraft=permissionSetCan(permissions,"MANAGE_PUBLIC_WEBSITE_PAGES");
  return <div className="page website-admin-page"><PageHeader title="Public Website Readiness" description="Controlled public content, accessibility, SEO and deployment planning. No DNS, hosting or provider credentials are managed here." action={<a className="button secondary" href="/" target="_blank" rel="noopener noreferrer">Open Public Site</a>}/><div className="notice warning"><strong>Prompt 20D is local only.</strong><span>No deployment, GoDaddy DNS, nameserver, MX, SPF, DKIM or DMARC change is authorised.</span></div><div className="stats-grid"><article className="stat-card"><span>Draft pages</span><strong>{report.counts.pages.DRAFT}</strong></article><article className="stat-card"><span>Ready for review</span><strong>{report.counts.pendingReviews}</strong></article><article className="stat-card"><span>Published pages</span><strong>{report.counts.pages.PUBLISHED}</strong></article><article className="stat-card"><span>Immutable versions</span><strong>{report.counts.publishedVersions}</strong></article><article className="stat-card"><span>Contact readiness</span><strong><StatusBadge status={report.gaps.publicContactComplete?"Good":"Needs Review"}/></strong></article><article className="stat-card"><span>Navigation</span><strong><StatusBadge status={report.gaps.navigationIntegrity?"Good":"Needs Review"}/></strong></article></div><section className="card card-pad"><h2>Foundation status</h2><div className="website-admin-links">{canDraft?<><Link href="/website-admin/pages">Pages</Link><Link href="/website-admin/posts">News & announcements</Link><Link href="/website-admin/settings">Public settings</Link><Link href="/website-admin/navigation">Navigation</Link></>:null}<Link href="/website-admin/reports">Readiness reports</Link><Link href="/school-app" target="_blank">School app experience</Link></div>{user.role==="VIEWER"?<p>Viewer/Auditor access is aggregate-only: no draft bodies, preview or export is exposed.</p>:null}</section><section className="card card-pad"><h2>Content gaps</h2><p>{report.gaps.unpublishedRequiredPages.length?`${report.gaps.unpublishedRequiredPages.length} required page types do not yet have an approved published CMS version.`:"All required page types have a published version."}</p><p>Public fallback pages use honest approval-pending wording and never claim affiliation, awards, results, staff qualifications, fees or student information.</p></section></div>;
}
