import type { PrismaClient } from "@prisma/client";
import { databaseTableExists } from "@/lib/database-capabilities";

export const OFFLINE_SYNC_BACKUP_KEYS = ["offlineSyncDevices", "offlineSyncMutations", "offlineSyncEvents", "offlineSyncConflictReviews"] as const;
export type OfflineSyncBackupKey = (typeof OFFLINE_SYNC_BACKUP_KEYS)[number];
export type OfflineSyncBackup = Record<OfflineSyncBackupKey, Record<string, unknown>[]>;
type EntityResult = { created: number; updated: number; skipped: number; errors: string[] };
type Result = Record<OfflineSyncBackupKey, EntityResult> & { warnings: string[] };

const FIELDS: Record<OfflineSyncBackupKey, Set<string>> = {
  offlineSyncDevices: new Set(["id","publicDeviceId","userId","label","platform","publicSigningKey","publicKeyHash","keyAlgorithm","keyVersion","status","requestedAt","approvedAt","approvedByUserId","lastSeenAt","revokedAt","revokedByUserId","revocationReason","createdAt","updatedAt"]),
  offlineSyncMutations: new Set(["id","deviceId","actorUserId","activeRole","clientMutationId","localDraftId","operationType","requestHash","payloadHash","syncSchemaVersion","referenceSnapshotVersion","baseEntityVersion","status","authoritativeEntityType","authoritativeEntityId","authoritativeReference","safeResultJson","conflictCode","rejectionCode","createdClientAt","receivedServerAt","committedAt","lastAttemptAt","createdAt","updatedAt"]),
  offlineSyncEvents: new Set(["id","deviceId","mutationId","actorUserId","eventType","safeMetadataJson","occurredAt"]),
  offlineSyncConflictReviews: new Set(["id","mutationId","deviceId","reviewedByUserId","resolutionStatus","resolutionNote","replacementMutationId","reviewedAt","createdAt"])
};
const REQUIRED: Record<OfflineSyncBackupKey, string[]> = {
  offlineSyncDevices: ["id","publicDeviceId","userId","label","platform","publicSigningKey","publicKeyHash","keyVersion","status","requestedAt","createdAt","updatedAt"],
  offlineSyncMutations: ["id","deviceId","actorUserId","activeRole","clientMutationId","localDraftId","operationType","requestHash","payloadHash","syncSchemaVersion","referenceSnapshotVersion","status","createdClientAt","receivedServerAt","lastAttemptAt","createdAt","updatedAt"],
  offlineSyncEvents: ["id","eventType","occurredAt"],
  offlineSyncConflictReviews: ["id","mutationId","deviceId","reviewedByUserId","resolutionStatus","resolutionNote","reviewedAt","createdAt"]
};

export function emptyOfflineSyncBackup(): OfflineSyncBackup { return Object.fromEntries(OFFLINE_SYNC_BACKUP_KEYS.map((key) => [key, []])) as unknown as OfflineSyncBackup; }
export async function offlineSyncSchemaAvailable(client: PrismaClient) { try { if (!(client as any).offlineSyncDevice?.findMany) return false; return await databaseTableExists(client, "OfflineSyncDevice"); } catch { return false; } }
export async function loadOfflineSyncBackup(client: PrismaClient): Promise<OfflineSyncBackup> {
  const [devices, mutations, events, reviews] = await Promise.all([
    client.offlineSyncDevice.findMany({ orderBy: [{ createdAt: "asc" }, { id: "asc" }] }),
    client.offlineSyncMutation.findMany({ orderBy: [{ createdAt: "asc" }, { id: "asc" }] }),
    client.offlineSyncEvent.findMany({ orderBy: [{ occurredAt: "asc" }, { id: "asc" }] }),
    client.offlineSyncConflictReview.findMany({ orderBy: [{ reviewedAt: "asc" }, { id: "asc" }] })
  ]);
  return { offlineSyncDevices: devices, offlineSyncMutations: mutations, offlineSyncEvents: events, offlineSyncConflictReviews: reviews };
}

export function validateOfflineSyncBackupRows(root: Record<string, unknown>): OfflineSyncBackup {
  const result = Object.fromEntries(OFFLINE_SYNC_BACKUP_KEYS.map((key) => [key, rows(root[key], key, FIELDS[key], REQUIRED[key])])) as OfflineSyncBackup;
  const devices = unique(result.offlineSyncDevices, "offlineSyncDevices", "id"); unique(result.offlineSyncDevices, "offlineSyncDevices", "publicDeviceId");
  const mutations = unique(result.offlineSyncMutations, "offlineSyncMutations", "id");
  for (const [i,row] of result.offlineSyncDevices.entries()) { oneOf(row.status,["PENDING_APPROVAL","ACTIVE","REVOKED","RETIRED"],`offlineSyncDevices[${i}].status`); if (!/^[a-f0-9]{64}$/.test(text(row.publicKeyHash))) throw new Error(`offlineSyncDevices[${i}].publicKeyHash is invalid`); json(row.publicSigningKey,`offlineSyncDevices[${i}].publicSigningKey`,2_000); }
  for (const [i,row] of result.offlineSyncMutations.entries()) { if(!devices.has(text(row.deviceId))) throw new Error(`offlineSyncMutations[${i}].deviceId is invalid`); oneOf(row.operationType,["FEE_PAYMENT","EXPENSE_DRAFT","MISC_INCOME"],`offlineSyncMutations[${i}].operationType`); oneOf(row.status,["RECEIVED","ACCEPTED","CONFLICT","REJECTED"],`offlineSyncMutations[${i}].status`); for(const field of ["requestHash","payloadHash","referenceSnapshotVersion"]) if(!/^[a-f0-9]{64}$/.test(text(row[field]))) throw new Error(`offlineSyncMutations[${i}].${field} is invalid`); if(row.safeResultJson) json(row.safeResultJson,`offlineSyncMutations[${i}].safeResultJson`,8_000); }
  unique(result.offlineSyncEvents,"offlineSyncEvents","id"); for(const [i,row] of result.offlineSyncEvents.entries()){if(row.deviceId&&!devices.has(text(row.deviceId)))throw new Error(`offlineSyncEvents[${i}].deviceId is invalid`);if(row.mutationId&&!mutations.has(text(row.mutationId)))throw new Error(`offlineSyncEvents[${i}].mutationId is invalid`);if(row.safeMetadataJson)json(row.safeMetadataJson,`offlineSyncEvents[${i}].safeMetadataJson`,4_000);}
  unique(result.offlineSyncConflictReviews,"offlineSyncConflictReviews","id"); for(const [i,row] of result.offlineSyncConflictReviews.entries()){if(!devices.has(text(row.deviceId))||!mutations.has(text(row.mutationId)))throw new Error(`offlineSyncConflictReviews[${i}] has an invalid link`);oneOf(row.resolutionStatus,["ACKNOWLEDGED","DRAFT_REVISED","DISCARDED"],`offlineSyncConflictReviews[${i}].resolutionStatus`);}
  return result;
}

export async function restoreOfflineSyncBackup(client: PrismaClient, backup: OfflineSyncBackup, maps: { users: Map<string,string>; restoredBy: string }, result: Result) {
  const deviceMap=new Map<string,string>(),mutationMap=new Map<string,string>(); const actor=(value:unknown)=>maps.users.get(text(value))??maps.restoredBy; const optionalActor=(value:unknown)=>value?actor(value):null;
  for(const [i,row] of backup.offlineSyncDevices.entries())try{const id=text(row.id),publicDeviceId=text(row.publicDeviceId),existing=await client.offlineSyncDevice.findFirst({where:{OR:[{id},{publicDeviceId}]}});if(existing){if(existing.id===id&&existing.publicDeviceId===publicDeviceId){deviceMap.set(id,id);result.offlineSyncDevices.skipped++;}else throw new Error("device identity collision");continue;}await client.offlineSyncDevice.create({data:{...dates(row,["requestedAt","approvedAt","lastSeenAt","revokedAt","createdAt","updatedAt"]),userId:actor(row.userId),approvedByUserId:optionalActor(row.approvedByUserId),revokedByUserId:optionalActor(row.revokedByUserId)}} as any);deviceMap.set(id,id);result.offlineSyncDevices.created++;}catch(error){result.offlineSyncDevices.errors.push(errorText("Offline device",i,error));}
  for(const [i,row] of backup.offlineSyncMutations.entries())try{const id=text(row.id),deviceId=deviceMap.get(text(row.deviceId));if(!deviceId){result.offlineSyncMutations.skipped++;continue;}if(await client.offlineSyncMutation.findUnique({where:{id}})){mutationMap.set(id,id);result.offlineSyncMutations.skipped++;continue;}const data={...dates(row,["createdClientAt","receivedServerAt","committedAt","lastAttemptAt","createdAt","updatedAt"]),deviceId,actorUserId:actor(row.actorUserId)} as Record<string,unknown>;const targetStatus=text(data.status);data.status="RECEIVED";data.authoritativeEntityType=null;data.authoritativeEntityId=null;data.authoritativeReference=null;data.safeResultJson=null;data.conflictCode=null;data.rejectionCode=null;data.committedAt=null;await client.offlineSyncMutation.create({data} as any);if(targetStatus!=="RECEIVED")await client.offlineSyncMutation.update({where:{id},data:{status:targetStatus,authoritativeEntityType:row.authoritativeEntityType??null,authoritativeEntityId:row.authoritativeEntityId??null,authoritativeReference:row.authoritativeReference??null,safeResultJson:row.safeResultJson??null,conflictCode:row.conflictCode??null,rejectionCode:row.rejectionCode??null,committedAt:row.committedAt?new Date(String(row.committedAt)):null}} as any);mutationMap.set(id,id);result.offlineSyncMutations.created++;}catch(error){result.offlineSyncMutations.errors.push(errorText("Offline mutation",i,error));}
  for(const [i,row] of backup.offlineSyncEvents.entries())try{const id=text(row.id);if(await client.offlineSyncEvent.findUnique({where:{id}})){result.offlineSyncEvents.skipped++;continue;}const deviceId=row.deviceId?deviceMap.get(text(row.deviceId)):null,mutationId=row.mutationId?mutationMap.get(text(row.mutationId)):null;if((row.deviceId&&!deviceId)||(row.mutationId&&!mutationId)){result.offlineSyncEvents.skipped++;continue;}await client.offlineSyncEvent.create({data:{...dates(row,["occurredAt"]),deviceId:deviceId??null,mutationId:mutationId??null,actorUserId:optionalActor(row.actorUserId)}} as any);result.offlineSyncEvents.created++;}catch(error){result.offlineSyncEvents.errors.push(errorText("Offline event",i,error));}
  for(const [i,row] of backup.offlineSyncConflictReviews.entries())try{const id=text(row.id),deviceId=deviceMap.get(text(row.deviceId)),mutationId=mutationMap.get(text(row.mutationId));if(!deviceId||!mutationId){result.offlineSyncConflictReviews.skipped++;continue;}if(await client.offlineSyncConflictReview.findUnique({where:{id}})){result.offlineSyncConflictReviews.skipped++;continue;}await client.offlineSyncConflictReview.create({data:{...dates(row,["reviewedAt","createdAt"]),deviceId,mutationId,reviewedByUserId:actor(row.reviewedByUserId)}} as any);result.offlineSyncConflictReviews.created++;}catch(error){result.offlineSyncConflictReviews.errors.push(errorText("Offline conflict review",i,error));}
  result.warnings.push("Offline challenges, replay nonces, browser drafts, offline PIN material and device private keys are intentionally excluded from backup and restore.");
}

function rows(value:unknown,label:string,allowed:Set<string>,required:string[]){if(value===undefined)return[];if(!Array.isArray(value)||value.length>100_000)throw new Error(`${label} must be a bounded array`);return value.map((item,index)=>{if(!item||typeof item!=="object"||Array.isArray(item))throw new Error(`${label}[${index}] must be an object`);const row=item as Record<string,unknown>;for(const key of Object.keys(row))if(!allowed.has(key))throw new Error(`${label}[${index}].${key} is unsupported`);for(const key of required)if(row[key]===undefined||row[key]===null||row[key]==="")throw new Error(`${label}[${index}].${key} is required`);return row;});}
function unique(items:Record<string,unknown>[],label:string,field:string){const values=new Set<string>();items.forEach((row,index)=>{const value=text(row[field]);if(!value||values.has(value))throw new Error(`${label}[${index}].${field} is missing or duplicated`);values.add(value);});return values;}
function text(value:unknown){return String(value??"").trim();} function oneOf(value:unknown,allowed:string[],label:string){if(!allowed.includes(text(value)))throw new Error(`${label} is unsupported`);} function json(value:unknown,label:string,max:number){if(typeof value!=="string"||value.length>max)throw new Error(`${label} is invalid`);try{JSON.parse(value);}catch{throw new Error(`${label} is invalid`);}} function dates(row:Record<string,unknown>,fields:string[]){const value={...row};for(const field of fields)if(value[field])value[field]=new Date(String(value[field]));return value;} function errorText(label:string,index:number,error:unknown){return `${label} ${index+1}: ${error instanceof Error?error.message:"Unknown restore error"}`;}
