import { Prisma } from "@prisma/client";
import { NextRequest, NextResponse } from "next/server";
import { requireApiPermission } from "@/lib/auth";
import { bookSettlementCsv } from "@/lib/book-cash-settlement";
import { bookSalesCsv } from "@/lib/books-finance";
import { csvCell } from "@/lib/expenses";
import { prisma } from "@/lib/prisma";

function publisherCsv(rows: any[]) { const headers = ["Expense Number", "Academic Year", "Publisher", "Invoice Number", "Invoice Date", "Approval Status", "Payment Status", "Invoice Total", "Paid", "Outstanding"]; return [headers, ...rows.map((row) => { const paid = row.payments.reduce((sum: Prisma.Decimal, payment: any) => sum.add(payment.amount), new Prisma.Decimal(0)); return [row.expenseNumber, row.academicYear, row.vendor?.name ?? "", row.invoiceNumber ?? "", row.invoiceDate?.toISOString().slice(0, 10) ?? "", row.approvalStatus, row.paymentStatus, row.netAmount.toFixed(2), paid.toFixed(2), row.netAmount.sub(paid).toFixed(2)]; })].map((line) => line.map(csvCell).join(",")).join("\r\n") + "\r\n"; }
export async function GET(request: NextRequest) { const auth = await requireApiPermission("EXPORT_BOOK_REPORTS"); if (auth.response) return auth.response; const kind = request.nextUrl.searchParams.get("kind") ?? "sales"; let csv: string, name: string; if (kind === "settlements") { const rows = await prisma.bookCashSettlement.findMany({ orderBy: { settlementDate: "asc" }, take: 10_000 }); csv = bookSettlementCsv(rows); name = "book-cash-settlements.csv"; } else if (kind === "publishers") { const rows = await prisma.expenseRecord.findMany({ where: { category: { code: "BOOKS" } }, include: { vendor: { select: { name: true } }, payments: { select: { amount: true } } }, orderBy: { invoiceDate: "asc" }, take: 10_000 }); csv = publisherCsv(rows); name = "publisher-bills.csv"; } else { const rows = await prisma.bookSaleReceipt.findMany({ include: { student: { select: { studentName: true, admissionNo: true } }, lines: true }, orderBy: { receiptDate: "asc" }, take: 10_000 }); csv = bookSalesCsv(rows); name = "book-sales.csv"; } return new NextResponse(csv, { headers: { "Content-Type": "text/csv; charset=utf-8", "Content-Disposition": `attachment; filename="${name}"`, "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" } }); }
