import Link from "next/link";
import { Prisma } from "@prisma/client";
import { PageHeader, PageShell, StatusBadge } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { localDate } from "@/lib/expenses";
import { displayDate, money } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { hasRolePermission } from "@/lib/role-permissions";

export default async function ExpensesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requirePermission("VIEW_EXPENSES"); const params = await searchParams; const manage = await hasRolePermission(prisma, user.role, "MANAGE_EXPENSES"); const value = (key: string) => typeof params[key] === "string" ? params[key] as string : "";
  const where: Prisma.ExpenseRecordWhereInput = {}; for (const field of ["approvalStatus", "paymentStatus", "paymentMethod", "vendorId", "categoryId", "departmentId"] as const) if (value(field)) where[field] = value(field); if (value("from") || value("to")) where.expenseDate = { ...(value("from") ? { gte: localDate(value("from")) } : {}), ...(value("to") ? { lt: new Date(localDate(value("to")).getTime() + 86_400_000) } : {}) }; if (value("search")) where.OR = [{ expenseNumber: { contains: value("search") } }, { description: { contains: value("search") } }, { invoiceNumber: { contains: value("search") } }];
  const [rows, vendors, categories, departments] = await Promise.all([prisma.expenseRecord.findMany({ where, include: { vendor: { select: { name: true } }, category: { select: { name: true } }, department: { select: { name: true } } }, orderBy: [{ expenseDate: "desc" }, { createdAt: "desc" }], take: 500 }), prisma.vendor.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.expenseCategory.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.expenseDepartment.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } })]);
  const total = (predicate: (row: (typeof rows)[number]) => boolean) => rows.filter(predicate).reduce((sum, row) => sum + Number(row.netAmount), 0);
  const cards = [{ label: "Total recorded", amount: total((row) => row.approvalStatus !== "CANCELLED") }, { label: "Pending approval", amount: total((row) => row.approvalStatus === "PENDING_APPROVAL") }, { label: "Approved unpaid", amount: total((row) => row.approvalStatus === "APPROVED" && row.paymentStatus !== "PAID") }, { label: "Paid", amount: total((row) => row.paymentStatus === "PAID") }, { label: "Cancelled", amount: total((row) => row.approvalStatus === "CANCELLED") }];
  return <PageShell><PageHeader title="Expenses" description="Approval and payment records are audit-safe and remain separate from student fees." action={manage ? <Link className="button" href="/expenses/new">Create Expense</Link> : undefined} /><div className="stats expense-stats">{cards.map((card) => <div className="card stat" key={card.label}><span>{card.label}</span><strong>{money(card.amount)}</strong></div>)}</div>
    <form className="card filter-grid expense-filters" method="get"><label>Search<input name="search" defaultValue={value("search")} placeholder="Expense number, invoice, description" /></label><label>From<input name="from" type="date" defaultValue={value("from")} /></label><label>To<input name="to" type="date" defaultValue={value("to")} /></label><label>Approval<select name="approvalStatus" defaultValue={value("approvalStatus")}><option value="">All</option>{["DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Payment<select name="paymentStatus" defaultValue={value("paymentStatus")}><option value="">All</option>{["UNPAID", "PARTIALLY_PAID", "PAID", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Method<select name="paymentMethod" defaultValue={value("paymentMethod")}><option value="">All</option>{["CASH", "UPI", "BANK_TRANSFER", "NEFT", "RTGS", "IMPS", "CHEQUE", "OTHER"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Vendor<select name="vendorId" defaultValue={value("vendorId")}><option value="">All</option>{vendors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Category<select name="categoryId" defaultValue={value("categoryId")}><option value="">All</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Department<select name="departmentId" defaultValue={value("departmentId")}><option value="">All</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="submit">Apply Filters</button><Link className="button secondary" href="/expenses">Clear</Link></form>
    <section className="card"><div className="table-wrap"><table><thead><tr><th>Expense</th><th>Date</th><th>Vendor / Category</th><th>Description</th><th>Net Amount</th><th>Approval</th><th>Payment</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.expenseNumber}</strong><br /><span className="muted-text">{row.academicYear}</span></td><td>{displayDate(row.expenseDate)}</td><td>{row.vendor?.name ?? "No vendor"}<br /><span className="muted-text">{row.category.name}{row.department ? ` · ${row.department.name}` : ""}</span></td><td>{row.description}</td><td>{money(Number(row.netAmount))}</td><td><StatusBadge status={row.approvalStatus} /></td><td><StatusBadge status={row.paymentStatus} /></td><td><Link href={`/expenses/${row.id}`}>View</Link></td></tr>)}</tbody></table></div>{!rows.length ? <div className="empty-state"><h3>No expenses found</h3><p>No records match the selected filters.</p></div> : null}</section>
  </PageShell>;
}
