import Link from "next/link";
import { PageHeader, PageShell } from "@/components/ui";
import { requirePermission, hasUserPermission } from "@/lib/auth";
import { miscIncomeReport } from "@/lib/misc-income";
import { moneyExact } from "@/lib/format";
import { prisma } from "@/lib/prisma";

function Group({ title, rows }: { title: string; rows: Array<{ label: string; total: string }> }) { return <section className="card"><h3>{title}</h3><div className="table-wrap"><table><thead><tr><th>Group</th><th>Total</th></tr></thead><tbody>{rows.map((row) => <tr key={row.label}><td>{row.label}</td><td>{moneyExact(Number(row.total))}</td></tr>)}</tbody></table></div>{!rows.length ? <p className="empty-state">No active income in this group.</p> : null}</section>; }
export default async function MiscIncomeReportsPage() { const user = await requirePermission("VIEW_MISC_INCOME_REPORTS"); const rows = await prisma.miscIncomeReceipt.findMany({ include: { student: { select: { studentName: true, admissionNo: true } }, lines: true } }); const report = miscIncomeReport(rows); const canExport = await hasUserPermission(user, "EXPORT_MISC_INCOME_REPORTS"); return <PageShell><PageHeader title="Miscellaneous-Income Reports" description="Active and cancelled income remain separate; no student fee Payment rows are included." action={<div className="page-actions"><Link className="button secondary" href="/misc-income">Back</Link>{canExport ? <a className="button" href="/api/misc-income/reports/export">Export CSV</a> : null}</div>} /><div className="stats">{[["Active", report.total], ["Cash", report.cash], ["Non-cash", report.nonCash], ["Cancelled", report.cancelled]].map(([label, total]) => <div className="card stat" key={label}><span>{label}</span><strong>{moneyExact(Number(total))}</strong></div>)}</div><div className="report-grid"><Group title="Date-wise" rows={report.dateWise} /><Group title="Item-wise" rows={report.itemWise} /><Group title="Student-wise" rows={report.studentWise} /><Group title="Payment-method-wise" rows={report.methodWise} /><Group title="Account-wise" rows={report.accountWise} /></div></PageShell>; }
