import assert from "node:assert/strict";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { randomBytes, randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { PDFDocument } from "pdf-lib";
import * as XLSX from "xlsx";
import { defaultTemplateDefinition } from "../lib/certificate-templates";
import { createCertificateRequest, transitionCertificateRequest } from "../lib/certificate-requests";
import { createStudentCertificateDraft, transitionCertificate, issueCertificate, createCertificateVersion, cancelIssuedCertificate } from "../lib/student-certificates";
import { prepareCertificateCharge, approveCertificateCharge, collectCertificateCharge } from "../lib/certificate-charges";
import { graduationReadiness } from "../lib/certificate-graduation-policy";
import { editCertificateTemplate } from "../lib/certificate-template-workflow";
import { renderCertificatePdf, sha256Bytes } from "../lib/certificate-pdf";
import { issuedCertificatePdf, verifyCertificateReference } from "../lib/certificate-authenticity";
import { certificateWorkbookTemplate } from "../lib/certificate-workbooks";
import { uploadCertificateBatch, approveCertificateBatch, processCertificateBatchRow, certificateBatchResults } from "../lib/certificate-bulk";
import { generateFullBackup, createBackupDocument } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";
import { restoreValidatedBackup } from "../lib/restore-database";
import { createPersistedSession } from "../lib/auth-sessions";
import { assertParentOwnsStudent } from "../lib/certificate-scope";
import { restoreCertificateExtensions } from "../lib/certificate-extension-backup";
import { hashPassword } from "../lib/password";

async function main() {
  if (process.env.NODE_ENV === "production") throw new Error("SYNTHETIC_QA_ONLY");
  const root = path.resolve("tmp/certificate-graduation-exit-1a"); mkdirSync(root, { recursive: true });
  const out = mkdtempSync(path.join(root, "run-"));
  const baseline = path.resolve("tmp/release-ci/synthetic.db");
  if (!existsSync(baseline)) throw new Error("Prepare the disposable released CI synthetic baseline first.");
  const probe = new PrismaClient({ datasourceUrl: `file:${baseline.replaceAll("\\", "/")}` });
  assert.equal(await probe.student.count(), 0, "Baseline must contain no Students"); await probe.$disconnect();
  const dbPath = path.join(out, "fixture.db"); copyFileSync(baseline, dbPath);
  process.env.DATABASE_URL = `file:${dbPath.replaceAll("\\", "/")}`;
  process.env.APP_ORIGIN = "http://127.0.0.1:3127";
  process.env.RELEASE_FEATURE_FLAGS_QA_MODE = "SYNTHETIC_COPY_ONLY";
  process.env.RELEASE_FEATURE_FLAGS_QA_ENABLED = "certificate-graduation-exit-1a,certificate-bulk-issue-1a,certificate-verification-1a";
  process.env.SESSION_SECRET = randomBytes(48).toString("hex");
  const db = new PrismaClient({ datasourceUrl: process.env.DATABASE_URL });
  let checks = 0;
  const check = (value: unknown, message: string) => { assert.ok(value, message); checks++; };
  const denied = async (work: () => Promise<unknown>, message: string) => { await assert.rejects(work, message); checks++; };
  const actors: Record<string, any> = {}, sessions: Record<string, string> = {};
  for (const role of ["SUPER_ADMIN", "ADMIN", "PRINCIPAL", "DIRECTOR", "TEACHER", "VIEWER", "PARENT"]) {
    const user = await db.user.create({ data: { username: `synthetic-graduation-${role.toLowerCase()}`, name: `SYNTHETIC ${role}`, role, passwordHash: await hashPassword(randomBytes(32).toString("hex")) } });
    await db.userRoleAssignment.create({ data: { userId: user.id, role, reason: "SYNTHETIC CERTIFICATE QA ONLY", activeKey: `${user.id}:${role}` } });
    actors[role] = user;
  }
  const prep = actors.ADMIN.id, approve = actors.PRINCIPAL.id, issue = actors.DIRECTOR.id;
  await db.schoolSettings.update({ where: { id: "school" }, data: { schoolName: "NALANDA PUBLIC SCHOOL", city: "SYNTHETIC ISSUE PLACE", addressLine1: "SYNTHETIC DOCUMENT QA ONLY", phone: "0000000000" } });
  const template = await db.certificateTemplate.create({ data: { templateCode: "SYNTHETIC-GRADUATION", certificateType: "GRADUATION", name: "SYNTHETIC Graduation Recognition", status: "ACTIVE", academicYear: "2026-27", templateDefinitionJson: JSON.stringify(defaultTemplateDefinition("GRADUATION")), createdByUserId: prep, activatedByUserId: approve } });
  await db.certificateNumberSeries.create({ data: { seriesCode: "SYNTHETIC-GRAD", certificateType: "GRADUATION", academicYear: "2026-27", prefix: "SYNTHETIC-GRAD-", nextNumber: 1 } });
  const item = await db.miscIncomeItem.create({ data: { itemCode: "GRADUATION", name: "SYNTHETIC Graduation rate", category: "CERTIFICATE", studentLinkPolicy: "REQUIRED" } });
  const rate = await db.miscIncomeRate.create({ data: { itemId: item.id, academicYear: "2026-27", amount: "125", notes: "SYNTHETIC TEST RATE ONLY - NOT SCHOOL POLICY" } });
  async function fixture(suffix: string, withEvidence = true) {
    const student = await db.student.create({ data: { admissionNo: `SYNTHETIC-GRAD-${suffix}`, studentName: `SYNTHETIC STUDENT ${suffix}`, fatherName: "SYNTHETIC GUARDIAN", phone1: "0000000000", className: "X" } });
    const enrollment = await db.academicYearEnrollment.create({ data: { studentId: student.id, academicYear: "2026-27", className: "X", status: "PASSED_OUT" } });
    if (withEvidence) await db.studentProgressionDecision.create({ data: { studentId: student.id, sourceEnrollmentId: enrollment.id, academicYear: "2026-27", decisionType: "PASSED_OUT", fromClass: "X", toStatus: "Passed Out", status: "FINALIZED", evidenceNotes: "SYNTHETIC reviewed school completion; no Board claim", finalizedByUserId: approve, finalizedAt: new Date(), effectiveDate: new Date() } });
    return student;
  }
  async function requestFor(student: any) {
    const input = { studentId: student.id, academicYear: "2026-27", certificateType: "GRADUATION", purpose: "SYNTHETIC SCHOOL RECOGNITION ONLY", idempotencyKey: randomUUID() };
    let request = await createCertificateRequest(db, input, { id: prep });
    check((await createCertificateRequest(db, input, { id: prep })).id === request.id, "Request retry idempotent");
    request = await transitionCertificateRequest(db, request.id, "review", prep);
    await denied(() => transitionCertificateRequest(db, request.id, "approve", prep), "Request self-approval denied");
    request = await transitionCertificateRequest(db, request.id, "approve", approve);
    let charge = await prepareCertificateCharge(db, request.id, prep);
    await denied(() => approveCertificateCharge(db, request.id, prep, charge.updatedAt.toISOString()), "Charge self-approval denied");
    charge = await approveCertificateCharge(db, request.id, issue, charge.updatedAt.toISOString());
    const pay = { receiptDate: new Date().toISOString().slice(0, 10), paymentMethod: "CASH" };
    const paid = await collectCertificateCharge(db, request.id, issue, pay);
    check((await collectCertificateCharge(db, request.id, issue, pay)).receiptId === paid.receiptId, "Collection retry reuses receipt");
    return request;
  }
  const missing = await fixture("NO-EVIDENCE", false);
  check(!(await graduationReadiness(db, missing.id, "2026-27")).ready, "Enrollment alone never establishes completion");
  check(!(await graduationReadiness(db, missing.id, "2025-26")).ready, "Wrong year refused");
  const student = await fixture("LONG-NAME-" + "A".repeat(100)), request = await requestFor(student);
  let cert = await createStudentCertificateDraft(db, { studentId: student.id, academicYear: "2026-27", certificateType: "GRADUATION", requestId: request.id, templateId: template.id, purpose: request.purpose }, prep);
  check((await createStudentCertificateDraft(db, { studentId: student.id, academicYear: "2026-27", certificateType: "GRADUATION", requestId: request.id, templateId: template.id, purpose: request.purpose }, prep)).id === cert.id, "Draft retry idempotent");
  const draft = await renderCertificatePdf(JSON.parse(cert.draftDataJson), "DRAFT"); writeFileSync(path.join(out, "synthetic-draft.pdf"), draft.pdf);
  check((await PDFDocument.load(draft.pdf)).getPageCount() > 0, "Draft is a parseable PDF");
  const long = JSON.parse(cert.draftDataJson); long.template.definition.body = "SYNTHETIC school completion recognition. ".repeat(90); long.template.definition.disclaimer += " Additional institutional recognition wording. ".repeat(25);
  const overflow = await renderCertificatePdf(long, "DRAFT"); writeFileSync(path.join(out, "synthetic-long-draft.pdf"), overflow.pdf); check(overflow.pages > 1, "Long wording paginates");
  const edited = await editCertificateTemplate(db, template.id, { expectedUpdatedAt: template.updatedAt.toISOString(), definition: { ...defaultTemplateDefinition("GRADUATION"), body: "School recognizes {{studentName}} in {{academicYear}}." } }, prep);
  check(edited.id !== template.id && edited.status === "DRAFT", "Approved template edit creates separate draft version");
  check((await db.certificateTemplate.findUniqueOrThrow({ where: { id: template.id } })).templateDefinitionJson === template.templateDefinitionJson, "Original template immutable");
  await denied(() => editCertificateTemplate(db, edited.id, { expectedUpdatedAt: edited.updatedAt.toISOString(), status: "ACTIVE" }, prep), "Template author activation denied");
  await denied(() => editCertificateTemplate(db, edited.id, { expectedUpdatedAt: edited.updatedAt.toISOString(), status: "ACTIVE", name: "SYNTHETIC changed by approver" }, approve), "Simultaneous edit and activation denied");
  cert = await transitionCertificate(db, cert.id, "submit", prep);
  await denied(() => transitionCertificate(db, cert.id, "approve", prep), "Draft self-approval denied");
  cert = await transitionCertificate(db, cert.id, "approve", approve);
  const receiptsBefore = await db.miscIncomeReceipt.count();
  const attempts = await Promise.allSettled([issueCertificate(db, cert.id, issue), issueCertificate(db, cert.id, issue)]);
  if (!attempts.some(r => r.status === "fulfilled")) console.error(attempts);
  check(attempts.some(r => r.status === "fulfilled"), "Concurrent issue obtains one result");
  cert = await issueCertificate(db, cert.id, issue);
  check(await db.studentCertificateVersion.count({ where: { certificateId: cert.id } }) === 1, "Concurrent/lost-ack issue stores exactly one version");
  const pdf = await issuedCertificatePdf(db, cert.id); writeFileSync(path.join(out, "synthetic-issued.pdf"), pdf);
  const artifact = await db.certificateIssueArtifact.findFirstOrThrow({ where: { certificateId: cert.id } });
  check(JSON.parse(artifact.renderProvenanceJson).fontFamily === "Georgia Bold", "Font provenance retained");
  check(sha256Bytes(await issuedCertificatePdf(db, cert.id)) === sha256Bytes(pdf), "Reprint returns identical bytes");
  check(await db.miscIncomeReceipt.count() === receiptsBefore, "PDF, issue retry and reprint create no finance rows");
  await db.miscIncomeRate.create({ data: { itemId: item.id, academicYear: "2027-28", amount: "999", notes: "SYNTHETIC NEXT YEAR ONLY" } });
  check(JSON.parse((await db.certificateRequestCharge.findUniqueOrThrow({ where: { requestId: request.id } })).snapshotJson).amount === "125", "Charged rate snapshot survives next year config");
  const revision = await createCertificateVersion(db, cert.id, "REISSUE", prep, "SYNTHETIC governed replacement");
  check(revision.status === "DRAFT" && revision.supersedesCertificateId === cert.id, "Reissue creates linked draft requiring review");
  await transitionCertificate(db, revision.id, "submit", prep); await transitionCertificate(db, revision.id, "approve", approve); await issueCertificate(db, revision.id, issue);
  check(await db.miscIncomeReceipt.count() === receiptsBefore, "Reissue reuses charge without posting");
  await cancelIssuedCertificate(db, cert.id, issue, "SYNTHETIC void acceptance");
  await denied(() => issuedCertificatePdf(db, cert.id), "Void active download denied while bytes retained");
  check(await db.certificateIssueArtifact.count({ where: { certificateId: cert.id } }) === 1, "Void retains original artifact");
  check((await verifyCertificateReference(db, "unknown")).status === "UNAVAILABLE", "Unknown token has bounded safe result");
  const fakeToken = randomBytes(32).toString("base64url"), fakeSnapshot = JSON.stringify({synthetic:true});
  const fake:any = {certificateIssueArtifact:{findUnique:async()=>({versionId:"synthetic-v1",certificateId:"synthetic-c1",snapshotHash:sha256Bytes(fakeSnapshot),expiresAt:new Date("2099-01-01")})},studentCertificate:{findUnique:async()=>({id:"synthetic-c1",status:"ISSUED",currentVersionNumber:2}),findFirst:async()=>null},studentCertificateVersion:{findUnique:async()=>({certificateId:"synthetic-c1",versionNumber:1,snapshotJson:fakeSnapshot,snapshotHash:sha256Bytes(fakeSnapshot)})}};
  check((await verifyCertificateReference(fake,fakeToken)).status === "SUPERSEDED","Older legacy version token cannot authenticate after flag-off revision");
  check((await verifyCertificateReference(fake,fakeToken,new Date("2100-01-01"))).status === "UNAVAILABLE","Expired reference has bounded safe response");
  const bulkStudent = await fixture("BULK"), bulkRequest = await requestFor(bulkStudent);
  const wb = XLSX.read(certificateWorkbookTemplate());
  XLSX.utils.sheet_add_aoa(wb.Sheets.Certificates, [[bulkRequest.requestNumber, bulkStudent.admissionNo, bulkStudent.studentName, "2026-27", "X"], ["SYNTHETIC-UNKNOWN", "SYNTHETIC-NO-MATCH", "SYNTHETIC WRONG", "2026-27", "X"]], { origin: "A2" });
  const xlsx = XLSX.write(wb, { type: "buffer", bookType: "xlsx" }); writeFileSync(path.join(out, "synthetic-bulk.xlsx"), xlsx);
  let batch = await uploadCertificateBatch(db, xlsx, template.id, prep);
  check(JSON.parse(batch.rowsJson)[1].errors.length === 1, "Invalid row has explicit error");
  await denied(() => approveCertificateBatch(db, batch.id, approve, { selected: [3], expectedUpdatedAt: batch.updatedAt.toISOString(), uploadDigest: batch.uploadDigest }), "Invalid row cannot be approved");
  await denied(() => approveCertificateBatch(db, batch.id, approve, { selected: [2], expectedUpdatedAt: batch.updatedAt.toISOString(), uploadDigest: "stale" }), "Digest stale approval refused");
  batch = await approveCertificateBatch(db, batch.id, approve, { selected: [2], expectedUpdatedAt: batch.updatedAt.toISOString(), uploadDigest: batch.uploadDigest });
  const beforeBulk = await db.miscIncomeReceipt.count();
  const bulkResult = await processCertificateBatchRow(db, batch.id, 2, issue);
  check((await processCertificateBatchRow(db, batch.id, 2, issue)).certificateId === bulkResult.certificateId, "Bulk resume does not reissue success");
  check(await db.miscIncomeReceipt.count() === beforeBulk, "Bulk resume does not collect again");
  check((await certificateBatchResults(db, batch.id)).rows[0].result === "SUCCEEDED", "Bulk results identify approved successful row");
  async function reviewedBatch(suffix: string) {
    const candidate = await fixture(suffix), request = await requestFor(candidate);
    const workbook = XLSX.read(certificateWorkbookTemplate()); XLSX.utils.sheet_add_aoa(workbook.Sheets.Certificates, [[request.requestNumber, candidate.admissionNo, candidate.studentName, "2026-27", "X"]], {origin:"A2"});
    let batch = await uploadCertificateBatch(db, XLSX.write(workbook, {type:"buffer",bookType:"xlsx"}), template.id, prep);
    batch = await approveCertificateBatch(db,batch.id,approve,{selected:[2],expectedUpdatedAt:batch.updatedAt.toISOString(),uploadDigest:batch.uploadDigest});
    return {candidate, request, batch};
  }
  const stale = await reviewedBatch("STALE");
  await db.student.update({where:{id:stale.candidate.id},data:{studentName:"SYNTHETIC CHANGED AFTER APPROVAL"}});
  await denied(() => processCertificateBatchRow(db,stale.batch.id,2,issue), "Changed target invalidates bulk approval");
  check(await db.studentCertificate.count({where:{requestId:stale.request.id}}) === 0, "Stale approval creates no issue");
  const interrupted = await reviewedBatch("INTERRUPTED");
  const beforeFailure = {receipts:await db.miscIncomeReceipt.count(),versions:await db.studentCertificateVersion.count()};
  const originalGeorgiaPath = process.env.CERTIFICATE_GEORGIA_BOLD_PATH;
  process.env.CERTIFICATE_GEORGIA_BOLD_PATH = path.join(out,"missing-font.ttf");
  try { await denied(() => processCertificateBatchRow(db,interrupted.batch.id,2,issue), "Missing Georgia interrupts PDF without issuing"); } finally {
    if (originalGeorgiaPath === undefined) delete process.env.CERTIFICATE_GEORGIA_BOLD_PATH; else process.env.CERTIFICATE_GEORGIA_BOLD_PATH = originalGeorgiaPath;
  }
  check(await db.studentCertificateVersion.count() === beforeFailure.versions && await db.miscIncomeReceipt.count() === beforeFailure.receipts, "Failed PDF creates neither issue nor collection");
  const resumed = await processCertificateBatchRow(db,interrupted.batch.id,2,issue);
  check((await processCertificateBatchRow(db,interrupted.batch.id,2,issue)).certificateId === resumed.certificateId, "Interrupted approved draft resumes exactly once");
  for (const type of ["BONAFIDE","STUDY","CONDUCT","TRANSFER"] as const) {
    const t = await db.certificateTemplate.create({data:{templateCode:`SYNTHETIC-${type}-PDF`,name:`SYNTHETIC ${type}`,certificateType:type,status:"ACTIVE",templateDefinitionJson:JSON.stringify(defaultTemplateDefinition(type)),createdByUserId:prep,activatedByUserId:approve}});
    await db.certificateNumberSeries.create({data:{seriesCode:`SYNTHETIC-${type}`,certificateType:type,academicYear:"2026-27",prefix:`SYNTHETIC-${type}-`,nextNumber:1,paddingLength:4,status:"ACTIVE",isDefault:true}});
    let c = await createStudentCertificateDraft(db,{studentId:student.id,academicYear:"2026-27",certificateType:type,templateId:t.id,issuePurpose:"SYNTHETIC reusable PDF acceptance"},prep);
    await transitionCertificate(db,c.id,"submit",prep);await transitionCertificate(db,c.id,"approve",approve);c=await issueCertificate(db,c.id,issue);
    const bytes = await issuedCertificatePdf(db,c.id);writeFileSync(path.join(out,`synthetic-${type.toLowerCase()}.pdf`),bytes);
    check(sha256Bytes(bytes) === sha256Bytes(await issuedCertificatePdf(db,c.id)), `${type} retained PDF is byte-stable`);
  }
  const guardian = await db.guardian.create({ data: { displayName: "SYNTHETIC PARENT", primaryMobile: "0000000000" } });
  await db.studentGuardian.create({ data: { studentId: bulkStudent.id, guardianId: guardian.id } });
  actors.PARENT = await db.user.update({ where: { id: actors.PARENT.id }, data: { guardianId: guardian.id } });
  await assertParentOwnsStudent(db, { ...actors.PARENT, guardianId: guardian.id }, bulkStudent.id); checks++;
  await denied(() => assertParentOwnsStudent(db, { ...actors.PARENT, guardianId: guardian.id }, student.id), "Unrelated Parent denied");
  const pendingTemplate = await db.certificateTemplate.create({data:{templateCode:"SYNTHETIC-RESTORE-DRAFT",certificateType:"GRADUATION",name:"SYNTHETIC pending template",status:"DRAFT",templateDefinitionJson:JSON.stringify(defaultTemplateDefinition("GRADUATION")),createdByUserId:prep}});
  const backup = await generateFullBackup(db, { generatedBy: "SYNTHETIC CERTIFICATE QA" });
  check(backup.metadata.backupVersion === 48, "Integrated extension uses backup v48");
  const validated = parseAndValidateBackup(JSON.stringify(backup));
  const legacy = createBackupDocument({ generatedAt: new Date(), users: [], students: [], feeStructures: [], payments: [], paymentAudits: [], generatedBy: "SYNTHETIC v45 COMPATIBILITY" });
  const relabelled = structuredClone(legacy) as any; relabelled.metadata.backupVersion = 45;
  assert.throws(() => parseAndValidateBackup(JSON.stringify(relabelled)), /BACKUP_SOURCE_/); checks++; // Genuine legacy adapters are exercised using original exporters in recovery-backup-compatibility.test.ts.
  const restores: any[] = [];
  for (let round = 1; round <= 2; round++) {
    const restorePath = path.join(out, `restore-${round}.db`); copyFileSync(baseline, restorePath);
    const restored = new PrismaClient({ datasourceUrl: `file:${restorePath.replaceAll("\\", "/")}` });
    const result = await restoreValidatedBackup(restored, validated, { id: issue, name: "SYNTHETIC RESTORE" });
    const extensionErrors = [result.certificateRequestCharges, result.certificateBulkBatches, result.certificateIssueArtifacts, result.studentCertificates, result.studentCertificateVersions].flatMap(r => r.errors);
    check(extensionErrors.length === 0, `Restore ${round}: ${extensionErrors.join("; ")}`);
    const restoredArtifact = await restored.certificateIssueArtifact.findUniqueOrThrow({ where: { id: artifact.id } });
    check(restoredArtifact.pdfHash === artifact.pdfHash && restoredArtifact.pdfBase64 === artifact.pdfBase64, `Restore ${round} keeps exact PDF bytes`);
    check((await restored.studentCertificate.findUniqueOrThrow({ where: { id: cert.id } })).status === "CANCELLED", `Restore ${round} keeps void`);
    check((await restored.studentCertificate.findUniqueOrThrow({ where: { id: revision.id } })).supersedesCertificateId === cert.id, `Restore ${round} keeps reissue link`);
    check((await restored.studentCertificate.findUniqueOrThrow({ where: { id: bulkResult.certificateId } })).workflowKey === `graduation:${bulkRequest.id}`, `Restore ${round} keeps row idempotency`);
    const receiptCount = await restored.miscIncomeReceipt.count(); await restoreValidatedBackup(restored, validated, { id: issue, name: "SYNTHETIC REPEAT RESTORE" });
    check(await restored.miscIncomeReceipt.count() === receiptCount, `Restore ${round} repeat does not repost finance`);
    const restoredDraft = await restored.certificateTemplate.findUniqueOrThrow({where:{id:pendingTemplate.id}});
    await denied(() => editCertificateTemplate(restored, restoredDraft.id, {status:"ACTIVE",expectedUpdatedAt:restoredDraft.updatedAt.toISOString()}, prep), `Restore ${round} requires fresh template preparation`);
    const restoredStudentMap = new Map<string,string>();
    for (const student of await db.student.findMany()) { const target = await restored.student.findUniqueOrThrow({where:{admissionNo:student.admissionNo}}); restoredStudentMap.set(student.id,target.id); }
    const intactResult:any = {certificateRequestCharges:{created:0,skipped:0,errors:[]},certificateBulkBatches:{created:0,skipped:0,errors:[]},certificateIssueArtifacts:{created:0,skipped:0,errors:[]}};
    await restoreCertificateExtensions(restored,validated,restoredStudentMap,intactResult);
    check(Object.values(intactResult).every((v:any)=>v.errors.length===0), `Restore ${round} intact target passes ownership/content check`);
    const targetVersion = await restored.studentCertificateVersion.findUniqueOrThrow({where:{id:artifact.versionId}});
    await restored.studentCertificateVersion.update({where:{id:targetVersion.id},data:{snapshotJson:"{}"}});
    const conflictResult:any = {certificateRequestCharges:{created:0,skipped:0,errors:[]},certificateBulkBatches:{created:0,skipped:0,errors:[]},certificateIssueArtifacts:{created:0,skipped:0,errors:[]}};
    await restoreCertificateExtensions(restored, validated, restoredStudentMap, conflictResult);
    check(conflictResult.certificateIssueArtifacts.errors.some((e:string)=>e.includes("ownership/content mismatch")), `Restore ${round} rejects conflicting target snapshots`);
    await restored.studentCertificateVersion.update({where:{id:targetVersion.id},data:{snapshotJson:targetVersion.snapshotJson}});
    const chargeSource = validated.certificateRequestCharges.find((r:any)=>r.receiptId)!;
    const originalReceipt = await restored.miscIncomeReceipt.findUniqueOrThrow({where:{id:String(chargeSource.receiptId)}});
    await restored.miscIncomeReceipt.update({where:{id:originalReceipt.id},data:{netAmount:"777"}});
    const receiptConflict:any = {certificateRequestCharges:{created:0,skipped:0,errors:[]},certificateBulkBatches:{created:0,skipped:0,errors:[]},certificateIssueArtifacts:{created:0,skipped:0,errors:[]}};
    await restoreCertificateExtensions(restored,validated,restoredStudentMap,receiptConflict);
    check(receiptConflict.certificateRequestCharges.errors.some((e:string)=>e.includes("receipt ownership/content")),`Restore ${round} rejects conflicting actual receipt amount`);
    await restored.miscIncomeReceipt.update({where:{id:originalReceipt.id},data:{netAmount:originalReceipt.netAmount}});
    restores.push({ round, extensionErrors }); await restored.$disconnect();
  }
  for (const [role, user] of Object.entries(actors)) sessions[role] = (await createPersistedSession(db, user, new Headers({ "user-agent": "SYNTHETIC CERTIFICATE BROWSER QA" }))).cookieValue;
  writeFileSync(path.join(out, "browser-private.json"), JSON.stringify({ dbPath, sessions, sessionSecret: process.env.SESSION_SECRET, studentId: bulkStudent.id, templateId: template.id, requestId: bulkRequest.id, batchId: batch.id, issuedId: bulkResult.certificateId, otherStudentId: student.id, otherCertificateId: cert.id }, null, 2));
  writeFileSync(path.join(out, "report.json"), JSON.stringify({ status: "PASSED", checks, restores, draftPages: overflow.pages, font: "Georgia Bold", syntheticOnly: true }, null, 2));
  writeFileSync(path.join(root, "latest.txt"), out);
  await db.$disconnect(); console.log(JSON.stringify({ status: "PASSED", checks, output: out }));
}
main().catch(error => { console.error(error); process.exitCode = 1; });
