import { createHash, randomBytes, randomUUID } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { assertSqliteCopyReady, assertSqliteSnapshotUnchanged, snapshotSqliteArtifacts } from "./sqlite-copy-safety";

const prefix = "OFFLINESYNC1A"; const workspace = path.resolve(".");
const operational = path.resolve(process.env.OFFLINE_SYNC_OPERATIONAL_DB ?? path.join(workspace, "prisma", "dev.db"));
const root = path.resolve(workspace, "tmp", "offline-sync-1a-copied-qa"); const copied = path.join(root, "offline-sync-copy.db"); const restored = path.join(root, "offline-sync-restore.db"); const keep = process.argv.includes("--keep");
const url = (file:string)=>`file:${file.replaceAll("\\","/")}`; let stage="preflight";
function invariant(value:unknown, code:string):asserts value{if(!value)throw new Error(code);} function hash(value:unknown){return createHash("sha256").update(typeof value==="string"?value:JSON.stringify(value)).digest("hex");}
function cleanup(){const target=path.resolve(root),parent=path.resolve(workspace,"tmp");invariant(target.startsWith(`${parent}${path.sep}`)&&target.endsWith("offline-sync-1a-copied-qa"),"CLEANUP_SCOPE_REFUSED");if(existsSync(target))rmSync(target,{recursive:true,force:true});}
function migrate(file:string){if(!existsSync(file))writeFileSync(file,"",{flag:"wx"});const entry=path.join(workspace,"node_modules","prisma","build","index.js");const run=spawnSync(process.execPath,[entry,"migrate","deploy","--schema","prisma/schema.prisma"],{cwd:workspace,env:{...process.env,DATABASE_URL:url(file)},encoding:"utf8",windowsHide:true,maxBuffer:64*1024*1024});if(run.status!==0||run.error)throw new Error(`MIGRATION_FAILED:${run.error?.message??run.stderr}`);}

async function main(){cleanup();assertSqliteCopyReady(operational,"OFFLINE_SYNC_OPERATIONAL");const before=snapshotSqliteArtifacts(operational);mkdirSync(root,{recursive:true});copyFileSync(operational,copied);migrate(copied);migrate(copied);migrate(restored);process.env.DATABASE_URL=url(copied);process.env.SESSION_SECRET=randomBytes(48).toString("base64url");
  const { prisma }=await import("../lib/prisma");const { buildReferencePack }=await import("../lib/offline-sync/reference-packs");const { processOfflineMutation }=await import("../lib/offline-sync/sync-service");const { createDeviceChallenge }=await import("../lib/offline-sync/device-trust");const { stableJson }=await import("../lib/offline-sync/contracts");const { loadOfflineSyncBackup, restoreOfflineSyncBackup, OFFLINE_SYNC_BACKUP_KEYS }=await import("../lib/offline-sync/backup");const { emptyEntityResult }=await import("../lib/restore");
  const seed=new PrismaClient({datasourceUrl:url(copied)}),restoreClient=new PrismaClient({datasourceUrl:url(restored)});let output:Record<string,unknown>={};
  try{stage="seed";const user=await seed.user.create({data:{id:randomUUID(),iamPublicKey:randomUUID(),name:"Offline Sync QA Accountant",username:`offline-qa-${randomBytes(4).toString("hex")}`,passwordHash:"$2b$12$synthetic.only.not.for.login.000000000000000000000000",role:"ACCOUNTANT",isActive:true,lifecycleStatus:"ACTIVE"}});const assignment=await seed.userRoleAssignment.create({data:{id:randomUUID(),publicKey:randomUUID(),userId:user.id,role:"ACCOUNTANT",reason:"Synthetic copied DB QA",activeKey:`${user.id}:ACCOUNTANT`}});const session=await seed.authSession.create({data:{id:randomUUID(),userId:user.id,tokenHash:hash(randomBytes(32)),credentialVersion:1,authorizationVersion:1,activeRoleAssignmentId:assignment.id,expiresAt:new Date(Date.now()+86400000),deviceSummary:"Synthetic",browserSummary:"Synthetic",networkEvidenceMasked:"local"}});const device=await seed.offlineSyncDevice.create({data:{publicDeviceId:randomUUID(),userId:user.id,label:"Synthetic trusted device",platform:"QA",publicSigningKey:JSON.stringify({kty:"EC",crv:"P-256",x:"synthetic",y:"synthetic",ext:true,key_ops:["verify"]}),publicKeyHash:hash("public"),status:"ACTIVE",approvedAt:new Date(),approvedByUserId:user.id}});
    const student=await seed.student.create({data:{admissionNo:`OFF-QA-${randomBytes(3).toString("hex")}`,studentName:"Synthetic Offline Student",fatherName:"Synthetic Parent",className:"VII",section:"A",phone1:"9000000000",academicYear:"2026-27",status:"Active"}});await seed.feeStructure.upsert({where:{academicYear_className:{academicYear:"2026-27",className:"VII"}},update:{active:true},create:{academicYear:"2026-27",className:"VII",termAmount:1000,term1Month:"June",term2Month:"September",term3Month:"December",term4Month:"February"}});const category=await seed.expenseCategory.create({data:{name:`Offline QA Category ${randomBytes(3).toString("hex")}`,code:`OQ${randomBytes(2).toString("hex")}`.toUpperCase()}});const department=await seed.expenseDepartment.create({data:{name:`Offline QA Department ${randomBytes(3).toString("hex")}`,code:`OD${randomBytes(2).toString("hex")}`.toUpperCase()}});const vendor=await seed.vendor.create({data:{vendorCode:`OV${randomBytes(3).toString("hex")}`.toUpperCase(),name:"Synthetic Offline Vendor",status:"ACTIVE"}});const item=await seed.miscIncomeItem.create({data:{itemCode:`OI${randomBytes(3).toString("hex")}`.toUpperCase(),name:"Synthetic Offline Item",category:"OTHER",studentLinkPolicy:"OPTIONAL",status:"ACTIVE"}});const rate=await seed.miscIncomeRate.create({data:{itemId:item.id,academicYear:"2026-27",amount:"25.00",status:"ACTIVE"}});
    const actor={id:user.id,name:user.name,username:user.username,email:null,designation:null,role:"ACCOUNTANT" as const,roleAssignmentId:assignment.id,authorizationVersion:1,mustChangePassword:false,guardianId:null};const pack=await buildReferencePack({userId:user.id,device});invariant(!pack.dictionaries.feeTypes.includes("Old Due")&&!pack.dictionaries.termHints.includes("Old Due"),"OLD_DUE_OFFERED_OFFLINE");const make=async(operationType:"FEE_PAYMENT"|"EXPENSE_DRAFT"|"MISC_INCOME",payload:Record<string,unknown>,suffix=randomUUID(),baseEntityVersion:string|null=null)=>({clientMutationId:`mutation-${suffix}`,localDraftId:`draft-${suffix}`,operationType,payload,payloadHash:hash(stableJson(payload)),createdClientAt:new Date().toISOString(),referenceSnapshotVersion:pack.snapshotVersion,baseEntityVersion});const run=(item:any)=>processOfflineMutation({item,requestHash:hash(item),device,user:actor,sessionId:session.id});
    stage="challenge retention";const expiredChallenge=await seed.offlineSyncChallenge.create({data:{userId:user.id,purpose:"REGISTER",publicDeviceId:randomUUID(),deviceKeyVersion:1,publicKeyHash:hash("expired-public"),challengeHash:hash("expired-challenge"),expiresAt:new Date(0)}});const issuedChallenge=await createDeviceChallenge({userId:user.id,purpose:"REGISTER",publicDeviceId:randomUUID(),keyVersion:1,publicKeyJwk:{kty:"EC",crv:"P-256",x:"synthetic",y:"synthetic",ext:true,key_ops:["verify"]}});invariant((await seed.offlineSyncChallenge.findUnique({where:{id:expiredChallenge.id}}))===null,"EXPIRED_CHALLENGE_RETAINED");const storedChallenge=await seed.offlineSyncChallenge.findUnique({where:{challengeHash:hash(issuedChallenge.challenge)}});invariant(storedChallenge?.expiresAt.toISOString()===issuedChallenge.expiresAt,"CHALLENGE_EXPIRY_MISMATCH");
    stage="acceptance and duplicate";const fee=await make("FEE_PAYMENT",{admissionNo:student.admissionNo,amountPaid:"100.00",date:"2026-08-25",paymentMode:"Cash",receivedAccount:"Cash",feeType:"Current Year Fee",termHint:"Auto"},randomUUID(),student.updatedAt.toISOString());const accepted=await run(fee),duplicate=await run(fee);invariant(accepted.outcome==="ACCEPTED"&&duplicate.outcome==="DUPLICATE_ACCEPTED","IDEMPOTENCY_FAILED");const changed={...fee,payload:{...(fee.payload as any),amountPaid:"101.00"},payloadHash:hash(stableJson({...(fee.payload as any),amountPaid:"101.00"}))};invariant((await run(changed)).code==="IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD","IDEMPOTENCY_REUSE_ACCEPTED");const paymentCount=await seed.payment.count();const oldDue=await make("FEE_PAYMENT",{...(fee.payload as any),feeType:"Old Due",termHint:"Old Due"},randomUUID(),student.updatedAt.toISOString());const oldDueResult=await run(oldDue);invariant(oldDueResult.outcome==="REJECTED"&&oldDueResult.code==="FEE_TYPE_NOT_SUPPORTED_OFFLINE"&&(await seed.payment.count())===paymentCount,"OFFLINE_OLD_DUE_ACCEPTED");
    stage="three operations and conflicts";const expense=await make("EXPENSE_DRAFT",{expenseDate:"2026-08-25",academicYear:"2026-27",vendorId:vendor.id,categoryId:category.id,departmentId:department.id,description:"Synthetic offline expense",grossAmount:"100",taxAmount:"0",deductionAmount:"0",netAmount:"100",paymentMethod:"CASH"});const miscPayload={receiptDate:"2026-08-25",academicYear:"2026-27",studentId:student.id,payerName:"Synthetic Payer",paymentMethod:"CASH",receivedAccount:"CASH_COUNTER",lines:[{itemId:item.id,expectedRateId:rate.id,expectedRateVersion:rate.updatedAt.toISOString(),quantity:1,discountAmount:"0"}]};const misc=await make("MISC_INCOME",miscPayload);invariant((await run(expense)).outcome==="ACCEPTED"&&(await run(misc)).outcome==="ACCEPTED","DOMAIN_ACCEPTANCE_FAILED");const receiptCount=await seed.miscIncomeReceipt.count();const changedRateDraft=await make("MISC_INCOME",{...miscPayload,payerName:"Changed-rate conflict"});await seed.miscIncomeRate.update({where:{id:rate.id},data:{amount:"30.00",updatedAt:new Date(rate.updatedAt.getTime()+1000)}});invariant((await run(changedRateDraft)).outcome==="CONFLICT"&&(await seed.miscIncomeReceipt.count())===receiptCount,"MISC_RATE_CHANGE_NOT_CONFLICT");const stale=await make("FEE_PAYMENT",{...(fee.payload as any),amountPaid:"50"},randomUUID(),new Date(0).toISOString());invariant((await run(stale)).outcome==="CONFLICT","STALE_REFERENCE_NOT_CONFLICT");
    stage="concurrency and load";const concurrent=await make("EXPENSE_DRAFT",{...(expense.payload as any),description:"Concurrent exactly once"});const race=await Promise.all(Array.from({length:12},()=>run(concurrent)));invariant(race.filter(row=>row.outcome==="ACCEPTED").length===1&&race.every(row=>["ACCEPTED","DUPLICATE_ACCEPTED","RETRY_LATER"].includes(row.outcome)),"CONCURRENT_DUPLICATE_FAILED");for(const row of race.filter(row=>row.outcome==="RETRY_LATER"))invariant((await run(concurrent)).outcome==="DUPLICATE_ACCEPTED","CONCURRENT_RETRY_FAILED");const started=Date.now();for(let index=0;index<75;index++)invariant((await run(await make("EXPENSE_DRAFT",{...(expense.payload as any),description:`Representative load ${index}`}))).outcome==="ACCEPTED",`LOAD_${index}_FAILED`);const loadMs=Date.now()-started;invariant(loadMs<30000,"LOAD_BUDGET_EXCEEDED");
    stage="revocation";await seed.offlineSyncDevice.update({where:{id:device.id},data:{status:"REVOKED",revokedAt:new Date(),revokedByUserId:user.id,revocationReason:"Synthetic lost-device test"}});const revoked=await run(await make("EXPENSE_DRAFT",{...(expense.payload as any),description:"Revoked device"}));invariant(revoked.outcome==="CONFLICT"&&revoked.code?.includes("DEVICE_NO_LONGER_ACTIVE"),"REVOKED_DEVICE_ACCEPTED");
    stage="backup restore twice";const backup=await loadOfflineSyncBackup(seed);invariant(backup.offlineSyncDevices.length===1&&backup.offlineSyncMutations.length>=80,"BACKUP_COUNTS_INVALID");invariant(!JSON.stringify(backup).match(/challengeHash|nonceHash|privateKey|wrappedKey/),"BACKUP_RUNTIME_SECRET_LEAK");const restoreUser=await restoreClient.user.create({data:{id:randomUUID(),iamPublicKey:randomUUID(),name:"Offline Restore QA",username:`offline-restore-${randomBytes(4).toString("hex")}`,passwordHash:"$2b$12$synthetic.only.not.for.login.000000000000000000000000",role:"SUPER_ADMIN"}});const results:any={warnings:[],...Object.fromEntries(OFFLINE_SYNC_BACKUP_KEYS.map(key=>[key,emptyEntityResult()]))};await restoreOfflineSyncBackup(restoreClient,backup,{users:new Map([[user.id,restoreUser.id]]),restoredBy:restoreUser.id},results);await restoreOfflineSyncBackup(restoreClient,backup,{users:new Map([[user.id,restoreUser.id]]),restoredBy:restoreUser.id},results);invariant((await restoreClient.offlineSyncDevice.count())===1&&(await restoreClient.offlineSyncMutation.count())===backup.offlineSyncMutations.length,"RESTORE_REHEARSAL_FAILED");
    output={verdict:"PASS",accepted:await seed.offlineSyncMutation.count({where:{status:"ACCEPTED"}}),conflicts:await seed.offlineSyncMutation.count({where:{status:"CONFLICT"}}),rejected:await seed.offlineSyncMutation.count({where:{status:"REJECTED"}}),events:await seed.offlineSyncEvent.count(),challengeRetention:"expired-purged",oldDueOffline:"rejected-with-zero-payment-writes",load:{mutations:75,milliseconds:loadMs},backup:{version:44,devices:backup.offlineSyncDevices.length,mutations:backup.offlineSyncMutations.length,restorePasses:2},operationalDatabase:"byte-identical"};
  }finally{await seed.$disconnect();await restoreClient.$disconnect();await prisma.$disconnect();}
  assertSqliteSnapshotUnchanged(before,snapshotSqliteArtifacts(operational),"OFFLINE_SYNC_OPERATIONAL");process.stdout.write(`${JSON.stringify(output,null,2)}\n`);
}
main().catch(error=>{process.stderr.write(`${prefix}_FAILED at ${stage}: ${error instanceof Error?error.stack??error.message:String(error)}\n`);process.exitCode=1;}).finally(()=>{if(!keep)cleanup();});
