import { copyFileSync,existsSync,mkdirSync,readFileSync,rmSync,statSync,writeFileSync } from "node:fs";
import { createHash,randomBytes,randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import type { Role } from "../lib/permissions";
import { RECOMMENDED_ROLE_PERMISSIONS } from "../lib/permissions";
import type { SafeExitActor } from "../lib/safe-exit";
import { approveSafeExit,approveStandingDepartureAuthorization,cancelSafeExitRequest,completeSafeExitCheckout,correctSafeExitRecord,createSafeExitRequest,createStandingDepartureAuthorization,emergencyOverrideSafeExit,issueSafeExitGatePass,listSafeExitRequests,liveCampusRoster,processOverdueSafeExitReturns,recordIncidentAction,recordSafeExitConsent,recordSafeExitReturn,recordUnauthorisedExit,revokeStandingDepartureAuthorization,safeExitStudentOptions,verifySafeExitGatePass } from "../lib/safe-exit";
import { processSafeExitNotificationOutbox } from "../lib/safe-exit-notifications";
import { generateFullBackup } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";
import { restoreSafeExitBackup } from "../lib/safe-exit-backup";
import { hashPassword } from "../lib/password";

const PREFIX=(process.argv.find(value=>value.startsWith("--prefix="))?.split("=")[1]||"SAFEEXIT1").toUpperCase(),KEEP=process.argv.includes("--keep"),workspace=path.resolve("."),operational=path.join(workspace,"prisma","dev.db"),root=path.join(workspace,"tmp",`${PREFIX.toLowerCase()}-copied-qa`),qaDb=path.join(root,"qa.db"),restoreDb=path.join(root,"restore.db"),url=(file:string)=>`file:${file.replaceAll("\\","/")}`;
const password=randomBytes(20).toString("base64url")+"Aa1!",secret=randomBytes(48).toString("base64url"),port=3271;
type Fixture={id:string;publicKey:string;assignmentId:string;sessionId:string;role:Role;name:string;username:string;guardianId:string|null;passwordHash:string};
function checked(){const value=path.resolve(root),parent=path.join(workspace,"tmp");if(!value.startsWith(`${parent}${path.sep}`)||!value.includes(`${PREFIX.toLowerCase()}-copied-qa`))throw new Error("SAFE_EXIT_QA_SCOPE_REFUSED");return value;}
function cleanup(){const value=checked();if(existsSync(value))rmSync(value,{recursive:true,force:true});}
function migrate(file:string){const pnpm=path.join(process.env.APPDATA??"","npm","node_modules","pnpm","bin","pnpm.mjs"),run=spawnSync(process.execPath,[pnpm,"exec","prisma","migrate","deploy","--schema","prisma/schema.prisma"],{cwd:workspace,env:{...process.env,DATABASE_URL:url(file)},encoding:"utf8",maxBuffer:64*1024*1024,windowsHide:true});if(run.error||run.status!==0)throw new Error(`MIGRATION_FAILED:${run.error?.message??`${run.stdout}\n${run.stderr}`}`);}
function actor(row:Fixture,permissions=RECOMMENDED_ROLE_PERMISSIONS[row.role]):SafeExitActor{return{user:{id:row.id,name:row.name,username:row.username,email:null,designation:row.role,role:row.role,roleAssignmentId:row.assignmentId,authorizationVersion:1,mustChangePassword:false,guardianId:row.guardianId},sessionId:row.sessionId,permissions};}
async function user(client:PrismaClient,role:Role,label:string,guardianId:string|null=null){const id=randomUUID(),publicKey=randomUUID(),assignmentId=randomUUID(),sessionId=randomUUID(),username=`${PREFIX.toLowerCase()}-${label.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${randomBytes(2).toString("hex")}`,passwordHash=await hashPassword(password);await client.user.create({data:{id,iamPublicKey:publicKey,name:`${PREFIX} ${label}`,username,passwordHash,role,isActive:true,lifecycleStatus:"ACTIVE",guardianId}});await client.authLoginAlias.create({data:{userId:id,type:"USERNAME",normalizedValue:username,displayMasked:username,status:"VERIFIED",isSchoolGoverned:true,verifiedAt:new Date()}});await client.userRoleAssignment.create({data:{id:assignmentId,publicKey:randomUUID(),userId:id,role,status:"ACTIVE",reason:`${PREFIX} copied database`,activeKey:`${id}:${role}`}});await client.authSession.create({data:{id:sessionId,userId:id,tokenHash:sha(`${id}:session`),credentialVersion:1,authorizationVersion:1,activeRoleAssignmentId:assignmentId,expiresAt:new Date(Date.now()+3_600_000),deviceSummary:`${PREFIX} fixture`,browserSummary:"Synthetic",networkEvidenceMasked:"local"}});return{id,publicKey,assignmentId,sessionId,role,name:`${PREFIX} ${label}`,username,guardianId,passwordHash};}
async function family(client:PrismaClient,label:string,count=1){const guardian=await client.guardian.create({data:{iamPublicKey:randomUUID(),displayName:`${PREFIX} ${label} Guardian`,primaryMobile:`90000${randomBytes(4).readUInt32BE(0).toString().padStart(10,"0").slice(-5)}`,status:"Active"}}),students=[]as any[];for(let index=0;index<count;index++){const className=index?`${PREFIX.slice(0,6)}8`:`${PREFIX.slice(0,6)}7`,student=await client.student.create({data:{admissionNo:`${PREFIX}-${label.toUpperCase()}-${index+1}`,studentName:`${PREFIX} ${label} Student ${index+1}`,fatherName:"Synthetic Guardian",className,section:"A",phone1:"9000000000",academicYear:"2026-27",remarks:`${PREFIX} copied database only`}});await client.academicYearEnrollment.create({data:{studentId:student.id,academicYear:"2026-27",className:student.className,section:"A",status:"ACTIVE",enrollmentDate:new Date()}});const link=await client.studentGuardian.create({data:{guardianId:guardian.id,studentId:student.id,relationshipToStudent:"Parent",isPrimaryContact:index===0}});students.push({student,link});}return{guardian,students};}
async function main(){cleanup();mkdirSync(root,{recursive:true});const before={hash:fileHash(operational),size:statSync(operational).size};copyFileSync(operational,qaDb);migrate(qaDb);migrate(qaDb);process.env.SAFE_EXIT_GATE_PASS_SECRET=secret;process.env.SESSION_SECRET=secret;process.env.WHATSAPP_PHONE_HASH_PEPPER=secret;const client=new PrismaClient({datasourceUrl:url(qaDb)});let restore:PrismaClient|null=null;try{
  invariant(await client.studentDepartureRequest.count()===0,"COPIED_BASELINE_NOT_EMPTY");
  const one=await family(client,"One"),many=await family(client,"Many",2),other=await family(client,"Other");
  const parent=await user(client,"PARENT","Parent",one.guardian.id),multiParent=await user(client,"PARENT","Multi Parent",many.guardian.id),unrelated=await user(client,"PARENT","Unrelated",other.guardian.id),teacher=await user(client,"TEACHER","Teacher"),office=await user(client,"COMPUTER_OPERATOR","Office"),principal=await user(client,"PRINCIPAL","Principal"),director=await user(client,"DIRECTOR","Director"),gate=await user(client,"GATE_STAFF","Gate"),accountant=await user(client,"ACCOUNTANT","Accountant"),viewer=await user(client,"VIEWER","Viewer");
  const tt=await client.timetableTeacher.create({data:{name:teacher.name,shortName:`${PREFIX.slice(0,6)}T`,maxPeriodsPerWeek:30,isActive:true}}),subject=await client.timetableSubject.create({data:{name:`${PREFIX} Subject`,shortName:`${PREFIX.slice(0,6)}S`,isActive:true}}),cohort=await client.timetableClassSection.create({data:{academicYear:"2026-27",className:`${PREFIX.slice(0,6)}7`,section:"A",displayName:`${PREFIX} 7-A`,groupName:`${PREFIX} GROUP`,isActive:true}});await client.timetableAssignment.create({data:{academicYear:"2026-27",classSectionId:cohort.id,subjectId:subject.id,teacherId:tt.id,periodsPerWeek:5}});for(const row of [teacher,office,principal,director,gate])await client.staffMember.create({data:{iamPublicKey:randomUUID(),staffCode:`${PREFIX}-${row.role}-${randomBytes(2).toString("hex")}`,fullName:row.name,displayName:row.name,staffType:row.role==="TEACHER"?"TEACHING":"NON_TEACHING",designation:row.role,status:"ACTIVE",userId:row.id,timetableTeacherId:row===teacher?tt.id:null}});
  await client.appPushSubscription.create({data:{userId:parent.id,endpointHash:sha(`${PREFIX}:push`),providerMode:"TEST_SINK",status:"ACTIVE",verifiedAt:new Date()}});
  await client.$queryRawUnsafe("PRAGMA wal_checkpoint(TRUNCATE)");copyFileSync(qaDb,restoreDb);restore=new PrismaClient({datasourceUrl:url(restoreDb)});
  const parentActor=actor(parent),multiParentActor=actor(multiParent),principalActor=actor(principal),directorActor=actor(director),gateActor=actor(gate),officeActor=actor(office),teacherActor=actor(teacher),unrelatedActor=actor(unrelated);
  const departure=new Date(Date.now()+20*60_000),attendanceBefore=await client.studentAttendanceRecord.count();
  const normal=await createSafeExitRequest(client,parentActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-normal-0001`,source:"PARENT_AUTHENTICATED",reasonCategory:"FAMILY_REQUEST",reasonDetails:"Synthetic governed normal request",intendedHandoverMethod:"LINKED_GUARDIAN",intendedDepartureAt:departure});
  const retry=await createSafeExitRequest(client,parentActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-normal-0001`,source:"PARENT_AUTHENTICATED",reasonCategory:"FAMILY_REQUEST",reasonDetails:"Synthetic governed normal request",intendedHandoverMethod:"LINKED_GUARDIAN",intendedDepartureAt:departure});invariant(retry.requestKey===normal.requestKey,"REQUEST_RETRY_DUPLICATED");
  await denied(()=>createSafeExitRequest(client,unrelatedActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-cross-0001`,source:"PARENT_AUTHENTICATED",reasonCategory:"OTHER",intendedHandoverMethod:"LINKED_GUARDIAN",intendedDepartureAt:departure}),"CROSS_FAMILY_ALLOWED");
  await denied(()=>approveSafeExit(client,teacherActor,normal.requestKey,{expectedVersion:1}),"TEACHER_APPROVAL_ALLOWED");
  let approved=await approveSafeExit(client,principalActor,normal.requestKey,{expectedVersion:1,approvedDepartureAt:departure,handoverMethod:"LINKED_GUARDIAN",recipientName:one.guardian.displayName,relationship:"Parent",contact:one.guardian.primaryMobile,parentAuthorisationEvidence:"Authenticated linked Parent request",reason:"Synthetic approval"});
  const material=await issueSafeExitGatePass(client,principalActor,normal.requestKey,{expectedVersion:approved.version});await denied(()=>verifySafeExitGatePass(client,gateActor,{token:material.token,recipientName:"Wrong Pickup",handoverMethod:"LINKED_GUARDIAN"}),"WRONG_PICKUP_ACCEPTED");const verified=await verifySafeExitGatePass(client,gateActor,{token:material.token,studentId:one.students[0].student.id,recipientName:one.guardian.displayName,handoverMethod:"LINKED_GUARDIAN"});invariant(!material.token.includes(one.students[0].student.id)&&!material.token.includes(one.students[0].student.studentName),"QR_CONTAINS_IDENTITY");
  const checkoutInput={token:material.token,studentId:one.students[0].student.id,expectedVersion:verified.requestVersion,recipientName:one.guardian.displayName,relationship:"Parent",handoverMethod:"LINKED_GUARDIAN",verificationReference:"Synthetic gate match"};const concurrent=await Promise.allSettled([completeSafeExitCheckout(client,gateActor,checkoutInput),completeSafeExitCheckout(client,gateActor,checkoutInput)]);invariant(concurrent.filter(row=>row.status==="fulfilled").length===1,"CONCURRENT_CHECKOUT_NOT_SINGLE_USE");await denied(()=>verifySafeExitGatePass(client,gateActor,{token:material.token}),"REUSED_PASS_ACCEPTED");
  invariant(await client.studentAttendanceRecord.count()===attendanceBefore,"ATTENDANCE_REWRITTEN");let roster=await liveCampusRoster(client,gateActor);invariant(roster.students.find((row:any)=>row.studentId===one.students[0].student.id)?.presence==="OFF_CAMPUS","ROSTER_NOT_CHECKED_OUT");const checked=await client.studentDepartureRequest.findUniqueOrThrow({where:{publicKey:normal.requestKey}});await recordSafeExitReturn(client,gateActor,normal.requestKey,{expectedVersion:checked.version,locationLabel:"Synthetic gate"});roster=await liveCampusRoster(client,gateActor);invariant(roster.students.find((row:any)=>row.studentId===one.students[0].student.id)?.presence==="ON_CAMPUS","ROSTER_RETURN_MISSING");
  const temporaryDeparture=new Date(Date.now()-40*60_000),expectedReturn=new Date(Date.now()-10*60_000),temporary=await createSafeExitRequest(client,parentActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-temporary-0001`,source:"PARENT_AUTHENTICATED",departureType:"TEMPORARY_EXIT_WITH_RETURN",reasonCategory:"TEMPORARY_EXIT_WITH_RETURN",reasonDetails:"Synthetic temporary appointment out-pass",intendedHandoverMethod:"LINKED_GUARDIAN",intendedDepartureAt:temporaryDeparture,temporaryReturnRequired:true,expectedReturnAt:expectedReturn,returnNotificationRequired:true});const temporaryApproved=await approveSafeExit(client,principalActor,temporary.requestKey,{expectedVersion:temporary.version,approvedDepartureAt:temporaryDeparture,handoverMethod:"LINKED_GUARDIAN",recipientName:one.guardian.displayName,relationship:"Parent",contact:one.guardian.primaryMobile,parentAuthorisationEvidence:"Authenticated linked Parent request",reason:"Synthetic temporary approval"}),temporaryPass=await issueSafeExitGatePass(client,principalActor,temporary.requestKey,{expectedVersion:temporaryApproved.version}),temporaryVerified=await verifySafeExitGatePass(client,gateActor,{token:temporaryPass.token,studentId:one.students[0].student.id,recipientName:one.guardian.displayName,handoverMethod:"LINKED_GUARDIAN"}),temporaryCheckout=await completeSafeExitCheckout(client,gateActor,{token:temporaryPass.token,studentId:one.students[0].student.id,expectedVersion:temporaryVerified.requestVersion,recipientName:one.guardian.displayName,relationship:"Parent",handoverMethod:"LINKED_GUARDIAN",verificationReference:"Synthetic temporary gate match"});invariant(temporaryCheckout.status==="RETURN_EXPECTED"&&temporaryCheckout.attendanceReconciliationRequired,"TEMPORARY_RETURN_STATE_MISSING");const corrected=await correctSafeExitRecord(client,principalActor,temporary.requestKey,{expectedVersion:temporaryCheckout.version,correctedFieldCode:"ACTUAL_RELEASE_NOTE",correctedValue:"Synthetic correction without rewriting release",reason:"Independent correction QA",idempotencyKey:`${PREFIX}-temporary-correction`});invariant(corrected.corrections.length===1,"APPEND_ONLY_CORRECTION_MISSING");const overdue=await processOverdueSafeExitReturns(client,principalActor,{now:new Date(),limit:25}),overdueRetry=await processOverdueSafeExitReturns(client,principalActor,{now:new Date(),limit:25});invariant(overdue.escalated===1&&overdueRetry.escalated===0,"OVERDUE_ESCALATION_NOT_IDEMPOTENT");const overdueRow=await client.studentDepartureRequest.findUniqueOrThrow({where:{publicKey:temporary.requestKey}});await recordSafeExitReturn(client,gateActor,temporary.requestKey,{expectedVersion:overdueRow.version,locationLabel:"Synthetic gate",notes:"Synthetic late return"});invariant(await client.studentAttendanceRecord.count()===attendanceBefore,"TEMPORARY_EXIT_REWROTE_ATTENDANCE");
  const staff=await createSafeExitRequest(client,teacherActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-staff-0001`,source:"STUDENT_RECORDED_BY_STAFF",reasonCategory:"APPOINTMENT",intendedHandoverMethod:"LINKED_GUARDIAN",intendedDepartureAt:departure});await recordSafeExitConsent(client,officeActor,staff.requestKey,{expectedVersion:staff.version,outcome:"APPROVED",method:"VERIFIED_TELEPHONE",guardianId:one.guardian.id,telephoneAttemptSummary:"Registered Guardian answered and verified the synthetic request.",witnessUserKey:principal.publicKey});
  const staleLinkBase=await createSafeExitRequest(client,officeActor,{studentId:other.students[0].student.id,submissionKey:`${PREFIX}-stale-link-0001`,source:"OFFICE_RECORDED",reasonCategory:"OTHER",intendedHandoverMethod:"LINKED_GUARDIAN",intendedDepartureAt:departure});const staleLinkConsent=await recordSafeExitConsent(client,officeActor,staleLinkBase.requestKey,{expectedVersion:staleLinkBase.version,outcome:"APPROVED",method:"VERIFIED_TELEPHONE",guardianId:other.guardian.id,telephoneAttemptSummary:"Registered synthetic Guardian confirmed before link-removal QA.",witnessUserKey:principal.publicKey});await client.studentGuardian.delete({where:{id:other.students[0].link.id}});await denied(()=>approveSafeExit(client,principalActor,staleLinkBase.requestKey,{expectedVersion:staleLinkConsent.version,approvedDepartureAt:departure,handoverMethod:"LINKED_GUARDIAN",recipientName:other.guardian.displayName,relationship:"Parent",parentAuthorisationEvidence:"Stale consent must fail",reason:"Stale link QA"}),"REMOVED_GUARDIAN_LINK_RELEASED");other.students[0].link=await client.studentGuardian.create({data:{guardianId:other.guardian.id,studentId:other.students[0].student.id,relationshipToStudent:"Parent",isPrimaryContact:true}});
  const deniedRequest=await createSafeExitRequest(client,officeActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-denied-0001`,source:"OFFICE_RECORDED",reasonCategory:"OTHER",intendedHandoverMethod:"LINKED_GUARDIAN",intendedDepartureAt:departure});const deniedConsent=await recordSafeExitConsent(client,officeActor,deniedRequest.requestKey,{expectedVersion:deniedRequest.version,outcome:"DENIED",method:"PRIVATE_WRITTEN_REFERENCE",guardianId:one.guardian.id,privateDocumentReference:`${PREFIX}-PRIVATE-WRITTEN`,supervisorUserKey:principal.publicKey});await denied(()=>approveSafeExit(client,principalActor,deniedRequest.requestKey,{expectedVersion:deniedConsent.version}),"DENIED_CONSENT_RELEASED");
  const unreachable=await createSafeExitRequest(client,officeActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-unreachable-0001`,source:"OFFICE_RECORDED",reasonCategory:"OTHER",intendedHandoverMethod:"LINKED_GUARDIAN",intendedDepartureAt:departure});const unreachableState=await recordSafeExitConsent(client,officeActor,unreachable.requestKey,{expectedVersion:unreachable.version,outcome:"PARENT_UNREACHABLE",method:"VERIFIED_TELEPHONE",guardianId:one.guardian.id,telephoneAttemptSummary:"Two unanswered calls to the registered Guardian contact."});await denied(()=>approveSafeExit(client,principalActor,unreachable.requestKey,{expectedVersion:unreachableState.version}),"UNREACHABLE_PARENT_RELEASED");await cancelSafeExitRequest(client,officeActor,unreachable.requestKey,{expectedVersion:unreachableState.version,reason:"Synthetic request cancelled after Parent remained unavailable"});
  const standing=await createStandingDepartureAuthorization(client,parentActor,{studentId:one.students[0].student.id,allowedDays:["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"],allowedStartMinute:0,allowedEndMinute:1439,effectiveFrom:new Date(Date.now()-86_400_000),effectiveUntil:new Date(Date.now()+30*86_400_000),allowsSelfDeparture:true,conditions:"Synthetic older Student policy condition",departurePattern:"Synthetic supervised activity departure",emergencyContact:one.guardian.primaryMobile,guardianApprovalMethod:"AUTHENTICATED_PARENT"});invariant(standing.status==="PENDING_SCHOOL_APPROVAL","STANDING_SCHOOL_APPROVAL_BYPASSED");await denied(()=>createSafeExitRequest(client,principalActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-self-pending-0001`,source:"STANDING_SELF_DEPARTURE",reasonCategory:"FAMILY_REQUEST",intendedHandoverMethod:"STUDENT_SELF_DEPARTURE",intendedDepartureAt:departure}),"PENDING_STANDING_AUTH_ACCEPTED");const approvedStanding=await approveStandingDepartureAuthorization(client,principalActor,standing.publicKey,{reason:"Synthetic leadership approval"}),self=await createSafeExitRequest(client,principalActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-self-0001`,source:"STANDING_SELF_DEPARTURE",departureType:"SELF_DEPARTURE_WITH_STANDING_PERMISSION",reasonCategory:"FAMILY_REQUEST",intendedHandoverMethod:"STUDENT_SELF_DEPARTURE",intendedDepartureAt:departure});invariant(self.consentState==="VERIFIED","STANDING_CONSENT_NOT_VERIFIED");await revokeStandingDepartureAuthorization(client,parentActor,approvedStanding.publicKey,{reason:"Synthetic Guardian revocation"});await denied(()=>createSafeExitRequest(client,principalActor,{studentId:one.students[0].student.id,submissionKey:`${PREFIX}-self-revoked-0002`,source:"STANDING_SELF_DEPARTURE",reasonCategory:"FAMILY_REQUEST",intendedHandoverMethod:"STUDENT_SELF_DEPARTURE",intendedDepartureAt:departure}),"REVOKED_STANDING_AUTH_ACCEPTED");
  const emergencyBase=await createSafeExitRequest(client,officeActor,{studentId:many.students[0].student.id,submissionKey:`${PREFIX}-emergency-0001`,source:"STAFF_MEDICAL_ROOM",reasonCategory:"MEDICAL",intendedHandoverMethod:"AMBULANCE_EMERGENCY_RESPONDER",intendedDepartureAt:departure});await denied(()=>emergencyOverrideSafeExit(client,gateActor,emergencyBase.requestKey,{expectedVersion:emergencyBase.version,reauthPassword:password}),"GATE_EMERGENCY_OVERRIDE_ALLOWED");await denied(()=>emergencyOverrideSafeExit(client,principalActor,emergencyBase.requestKey,{expectedVersion:emergencyBase.version,reauthPassword:password,emergencyCategory:"URGENT_MEDICAL_TRANSFER",reason:"Parent unreachable only",parentContactAttempts:["No answer"],safeDestination:"School gate",handoverMethod:"AMBULANCE_EMERGENCY_RESPONDER",recipientName:"Synthetic responder",relationship:"Responder",parentAuthorisationEvidence:"Emergency authority",secondConfirmationUserKey:director.publicKey}),"UNREACHABLE_OVERRIDE_ALLOWED");const emergency=await emergencyOverrideSafeExit(client,principalActor,emergencyBase.requestKey,{expectedVersion:emergencyBase.version,reauthPassword:password,emergencyCategory:"URGENT_MEDICAL_TRANSFER",reason:"Urgent medical transfer to the approved local hospital",parentContactAttempts:["Registered Guardian call attempted at incident start"],safeDestination:"Approved local hospital emergency department",handoverMethod:"AMBULANCE_EMERGENCY_RESPONDER",recipientName:"Synthetic ambulance responder",relationship:"Emergency responder",parentAuthorisationEvidence:"School emergency authority",verificationReference:"Synthetic responder unit",secondConfirmationUserKey:director.publicKey});invariant(emergency.emergencyOverride,"EMERGENCY_OVERRIDE_MISSING");
  const incident=await recordUnauthorisedExit(client,directorActor,{studentId:many.students[1].student.id,submissionKey:`${PREFIX}-incident-0001`,confirmed:false,summary:"Synthetic suspected unauthorised departure for restricted QA only.",lastConfirmedLocation:"Synthetic east gate",lastConfirmedAt:new Date()});invariant(incident.gatePasses.length===0,"INCIDENT_GATE_PASS_CREATED");await denied(()=>emergencyOverrideSafeExit(client,directorActor,incident.requestKey,{expectedVersion:incident.version,reauthPassword:password,emergencyCategory:"SAFEGUARDING_EMERGENCY",reason:"Safeguarding incident must remain incident-only and cannot become a release",parentContactAttempts:["Registered Guardian contacted for incident response"],safeDestination:"Student remains under incident response",handoverMethod:"LEGAL_AUTHORITY",recipientName:"Synthetic authority",relationship:"Authority",parentAuthorisationEvidence:"Incident-only QA",secondConfirmationUserKey:principal.publicKey}),"INCIDENT_EMERGENCY_GATE_AUTHORITY_CREATED");const incidentRow=await client.studentDepartureIncident.findFirstOrThrow({where:{request:{publicKey:incident.requestKey}}});await recordIncidentAction(client,directorActor,incidentRow.publicKey,{expectedVersion:incidentRow.version,actionType:"SEARCH_ACTION",summary:"Synthetic search action recorded",idempotencyKey:`${PREFIX}-search-0001`});await recordIncidentAction(client,directorActor,incidentRow.publicKey,{expectedVersion:incidentRow.version+1,actionType:"RETURNED_TO_CAMPUS",summary:"Synthetic Student located and returned",location:"Synthetic gate",idempotencyKey:`${PREFIX}-return-incident`});const parentIncident=(await listSafeExitRequests(client,multiParentActor)).find((row:any)=>row.requestKey===incident.requestKey);invariant(parentIncident&&parentIncident.reasonDetails===undefined&&parentIncident.incidents===undefined,"RESTRICTED_INCIDENT_DETAILS_LEAK");
  await client.studentCampusPresenceEvent.create({data:{studentId:other.students[0].student.id,eventType:"EARLY_DEPARTURE",schoolDateKey:"2026-08-08",recordedByUserId:director.id,source:"HISTORICAL_QA",idempotencyKey:`${PREFIX}-yesterday-presence`,occurredAt:new Date("2026-08-08T08:00:00.000Z")}});invariant((await liveCampusRoster(client,directorActor)).students.find((row:any)=>row.studentId===other.students[0].student.id)?.presence==="ON_CAMPUS","YESTERDAY_EVENT_CORRUPTED_TODAY_ROSTER");
  invariant((await safeExitStudentOptions(client,actor(accountant))).length===0,"ACCOUNTANT_STUDENT_SCOPE_ALLOWED");invariant((await safeExitStudentOptions(client,teacherActor)).some((row:any)=>row.id===one.students[0].student.id),"TEACHER_EXACT_SCOPE_MISSING");invariant(!(await safeExitStudentOptions(client,teacherActor)).some((row:any)=>row.id===many.students[1].student.id),"TEACHER_CROSS_CLASS_SCOPE_LEAK");invariant((await safeExitStudentOptions(client,actor(viewer))).length===0,"VIEWER_STUDENT_SCOPE_LEAK");
  const notification=await processSafeExitNotificationOutbox(client,{limit:100});invariant(notification.claimed>0&&notification.delivered>0,"NOTIFICATION_TEST_SINK_NOT_EXERCISED");invariant(await client.studentDepartureNotificationOutbox.count({where:{channel:"PUSH",status:"DELIVERED"}})>0,"PUSH_NOT_DELIVERED");invariant(await client.studentDepartureFallbackTask.count({where:{requestId:(await client.studentDepartureRequest.findUniqueOrThrow({where:{publicKey:incident.requestKey}})).id}})>0,"INCIDENT_FALLBACK_TASK_MISSING");
  const backup=parseAndValidateBackup(await generateFullBackup(client as never,{generatedBy:`${PREFIX} copied database QA`}));invariant(backup.metadata.backupVersion===40&&backup.studentDepartureRequests.length>=8&&backup.studentGatePasses.length>=2&&backup.studentDepartureCorrectionEvents.length===1,"SAFE_EXIT_BACKUP_INCOMPLETE");const first=await restoreSafeExitBackup(restore,backup),second=await restoreSafeExitBackup(restore,backup);invariant(first.studentDepartureRequests.created===backup.studentDepartureRequests.length&&first.studentDepartureCorrectionEvents.created===1&&second.studentDepartureRequests.skipped===backup.studentDepartureRequests.length&&second.studentDepartureCorrectionEvents.skipped===1,"SAFE_EXIT_DOUBLE_RESTORE_FAILED");invariant(JSON.stringify(backup).includes("studentCampusPresenceEvents")&&!JSON.stringify(backup).includes("appPushSubscriptions"),"BACKUP_PRIVACY_BOUNDARY_FAILED");
  const normalId=(await client.studentDepartureRequest.findUniqueOrThrow({where:{publicKey:normal.requestKey}})).id;await denied(()=>client.studentDepartureEvent.deleteMany({where:{requestId:normalId}}),"APPEND_ONLY_EVENT_DELETED");await denied(()=>client.studentDepartureRequest.delete({where:{publicKey:normal.requestKey}}),"HARD_DELETE_ALLOWED");const after={hash:fileHash(operational),size:statSync(operational).size};invariant(JSON.stringify(before)===JSON.stringify(after),"OPERATIONAL_DATABASE_CHANGED");
  if(KEEP){writeFileSync(path.join(root,"browser-credentials.json"),JSON.stringify({password,parent:{username:parent.username},teacher:{username:teacher.username},office:{username:office.username},principal:{username:principal.username},director:{username:director.username},gate:{username:gate.username},accountant:{username:accountant.username},viewer:{username:viewer.username}}),{flag:"wx"});writeFileSync(path.join(root,"runtime-env.json"),JSON.stringify({NODE_ENV:"production",DATABASE_URL:url(qaDb),SESSION_SECRET:secret,AUTH_SECRET:secret,SAFE_EXIT_GATE_PASS_SECRET:secret,WHATSAPP_PHONE_HASH_PEPPER:secret,APP_ORIGIN:`http://localhost:${port}`,PORT:String(port)}),{flag:"wx"});}
  console.log(JSON.stringify({result:`${PREFIX}_COPIED_DATABASE_VERIFIED`,operationalMutation:false,migrateDeployTwice:true,normalWorkflow:true,temporaryReturn:true,overdueEscalation:true,appendOnlyCorrection:true,attendanceReconciliationFlag:true,consentDenial:true,parentUnreachable:true,guardianLinkStaleness:true,standingLeadershipApproval:true,standingRevocation:true,emergencyReauthentication:true,unauthorisedIncident:true,incidentCannotCreatePass:true,singleUseConcurrency:true,sameDayCampusState:true,attendanceRowsUnchanged:true,notificationTestSink:true,liveProvider:false,doubleRestore:true,requests:backup.studentDepartureRequests.length,presenceEvents:backup.studentCampusPresenceEvents.length,browserFixture:KEEP?{port,credentialsPath:path.join(root,"browser-credentials.json"),runtimePath:path.join(root,"runtime-env.json")}:undefined}));
 }finally{await client.$disconnect();if(restore)await restore.$disconnect();if(!KEEP){cleanup();cleanup();}}if(!KEEP&&existsSync(root))throw new Error("SAFE_EXIT_QA_RESIDUE_REMAINS");}
async function denied(work:()=>Promise<unknown>,code:string){try{await work();}catch{return;}throw new Error(code);}function invariant(value:unknown,code:string):asserts value{if(!value)throw new Error(code);}function sha(value:string|Buffer){return createHash("sha256").update(value).digest("hex");}function fileHash(file:string){return sha(readFileSync(file));}
if(process.argv.includes("cleanup")){cleanup();cleanup();console.log(JSON.stringify({result:`${PREFIX}_FIXTURES_REMOVED`,exists:existsSync(root)}));}else main().catch(error=>{console.error(error instanceof Error?error.stack:error);process.exitCode=1;});
