import { copyFileSync,existsSync,mkdirSync,rmSync,statSync,readFileSync,writeFileSync } from "node:fs";
import { createHash,randomBytes,randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import sharp from "sharp";
import { RECOMMENDED_ROLE_PERMISSIONS,type Role } from "../lib/permissions";
import { listChildContexts } from "../lib/iam/contexts";
import { createAuthenticatedSupportRequest,createManualSupportRequest,createPublicSupportRequest,validateAuthenticatedSupportInput,validateManualSupportInput,validatePublicSupportInput,triageSupportRequest,assignSupportRequest,addSupportMessage,resolveSupportRequest,reopenOwnSupportRequest,submitSupportSatisfaction,listOwnSupportRequests,listManagedSupportRequests,loadSupportRequestForActor,createSupportAttachmentRecord,loadSupportAttachment,supportReport,escalateOverdueSupportRequests } from "../lib/support";
import { storeSupportFile,validateSupportUpload } from "../lib/support-files";
import { createAndVerifySupportAssetBackup,restoreSupportAssetBackup } from "../lib/support-asset-backup";
import { generateFullBackup } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";
import { restoreSupportBackup } from "../lib/support-backup";
import { hashPassword } from "../lib/password";

const PREFIX=process.argv.find((value)=>value.startsWith("--prefix="))?.slice("--prefix=".length).trim()||process.env.SUPPORT_QA_PREFIX?.trim()||"SUPPORT1A",KEEP=process.argv.includes("--keep")||process.env.SUPPORT_QA_KEEP==="true",workspace=path.resolve("."),operational=path.join(workspace,"prisma","dev.db"),root=path.join(workspace,"tmp",`${PREFIX.toLowerCase()}-copied-qa`),qaDb=path.join(root,"qa.db"),restoreDb=path.join(root,"restore.db"),storage=path.join(root,"storage"),url=(file:string)=>`file:${file.replaceAll("\\","/")}`;
let stage="initialising";
const browserPassword=randomBytes(18).toString("base64url")+"Aa1!",browserSecret=randomBytes(48).toString("base64url"),browserPort=3261;
let browserPasswordHash:Promise<string>|null=null;
type Fixture={id:string;publicKey:string;assignmentId:string;sessionId:string;role:Role;name:string;username:string;guardianId?:string};
function checked(){const resolved=path.resolve(root),parent=path.join(workspace,"tmp");if(!resolved.startsWith(`${parent}${path.sep}`)||!resolved.includes(`${PREFIX.toLowerCase()}-copied-qa`))throw new Error(`${PREFIX}_QA_SCOPE_REFUSED`);return resolved;}
function cleanup(){const value=checked();if(existsSync(value))rmSync(value,{recursive:true,force:true});}
function migrate(file:string){const pnpm=path.join(process.env.APPDATA??"","npm","node_modules","pnpm","bin","pnpm.mjs"),run=spawnSync(process.execPath,[pnpm,"exec","prisma","migrate","deploy","--schema","prisma/schema.prisma"],{cwd:workspace,env:{...process.env,DATABASE_URL:url(file)},encoding:"utf8",maxBuffer:64*1024*1024,windowsHide:true});if(run.error||run.status!==0)throw new Error(`${PREFIX}_MIGRATION_FAILED:${run.error?.message??`${run.stdout}\n${run.stderr}`}`);}
function actor(row:Fixture){return{id:row.id,name:row.name,role:row.role,roleAssignmentId:row.assignmentId,permissions:RECOMMENDED_ROLE_PERMISSIONS[row.role]};}
async function user(client:PrismaClient,role:Role,label:string,options:{active?:boolean;guardianId?:string;secondRole?:Role}={}){const username=`${PREFIX.toLowerCase()}-${label.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${randomBytes(3).toString("hex")}`,row:Fixture={id:randomUUID(),publicKey:randomUUID(),assignmentId:randomUUID(),sessionId:randomUUID(),role,name:`${PREFIX} ${label}`,username,guardianId:options.guardianId};browserPasswordHash??=hashPassword(browserPassword);await client.user.create({data:{id:row.id,iamPublicKey:row.publicKey,name:row.name,username,passwordHash:await browserPasswordHash,role,isActive:options.active!==false,lifecycleStatus:options.active===false?"DISABLED":"ACTIVE",guardianId:options.guardianId}});await client.authLoginAlias.create({data:{userId:row.id,type:"USERNAME",normalizedValue:username,displayMasked:username,status:"VERIFIED",isSchoolGoverned:true,verifiedAt:new Date()}});await client.userRoleAssignment.create({data:{id:row.assignmentId,publicKey:randomUUID(),userId:row.id,role,status:"ACTIVE",reason:`${PREFIX} isolated copied-database fixture`,activeKey:`${row.id}:${role}`}});if(options.secondRole)await client.userRoleAssignment.create({data:{publicKey:randomUUID(),userId:row.id,role:options.secondRole,status:"ACTIVE",reason:`${PREFIX} dual-context fixture`,activeKey:`${row.id}:${options.secondRole}`}});await client.authSession.create({data:{id:row.sessionId,userId:row.id,tokenHash:sha(Buffer.from(`${row.id}:session`)),credentialVersion:1,authorizationVersion:1,activeRoleAssignmentId:row.assignmentId,expiresAt:new Date(Date.now()+3_600_000),deviceSummary:`${PREFIX} copied QA`,browserSummary:"Synthetic",networkEvidenceMasked:"local"}});return row;}
async function guardianFamily(client:PrismaClient,label:string,count:number){const guardian=await client.guardian.create({data:{id:randomUUID(),iamPublicKey:randomUUID(),displayName:`${PREFIX} ${label} Guardian`,primaryMobile:`9000${randomBytes(4).readUInt32BE(0).toString().padStart(10,"0").slice(-6)}`,status:"Active"}}),students=[] as any[];for(let index=0;index<count;index++){const student=await client.student.create({data:{id:randomUUID(),admissionNo:`${PREFIX}-${label.toUpperCase()}-${index+1}`,studentName:`${PREFIX} ${label} Child ${index+1}`,fatherName:"Synthetic Parent",className:index?"7":"6",section:"A",phone1:"9000000000",academicYear:"2026-27"}});await client.academicYearEnrollment.create({data:{studentId:student.id,academicYear:"2026-27",className:student.className,section:"A",status:"ACTIVE"}});const link=await client.studentGuardian.create({data:{guardianId:guardian.id,studentId:student.id,isPrimaryContact:index===0}});students.push({student,link});}return{guardian,students};}
async function main(){cleanup();mkdirSync(root,{recursive:true});const before={sha256:fileSha(operational),size:statSync(operational).size};copyFileSync(operational,qaDb);stage="migration";migrate(qaDb);migrate(qaDb);copyFileSync(qaDb,restoreDb);process.env.SUPPORT_PRIVATE_STORAGE_ROOT=storage;process.env.SESSION_SECRET=browserSecret;const client=new PrismaClient({datasourceUrl:url(qaDb)}),restore=new PrismaClient({datasourceUrl:url(restoreDb)});try{
    invariant(await client.supportRequest.count()===0,`${PREFIX}_COPIED_BASELINE_SUPPORT_NOT_EMPTY`);
    const one=await guardianFamily(client,"One",1),many=await guardianFamily(client,"Many",2),other=await guardianFamily(client,"Other",1);
    const superOne=await user(client,"SUPER_ADMIN","SuperOne"),superTwo=await user(client,"SUPER_ADMIN","SuperTwo"),director=await user(client,"DIRECTOR","Director"),principal=await user(client,"PRINCIPAL","Principal"),accountant=await user(client,"ACCOUNTANT","Accountant"),operator=await user(client,"COMPUTER_OPERATOR","Operator"),teacher=await user(client,"TEACHER","Teacher"),teacherParentFamily=await guardianFamily(client,"TeacherParent",1),teacherParent=await user(client,"PARENT","TeacherParent",{guardianId:teacherParentFamily.guardian.id,secondRole:"TEACHER"}),parentOne=await user(client,"PARENT","ParentOne",{guardianId:one.guardian.id}),parentMany=await user(client,"PARENT","ParentMany",{guardianId:many.guardian.id}),unrelated=await user(client,"PARENT","Unrelated",{guardianId:other.guardian.id}),viewer=await user(client,"VIEWER","Viewer"),inactive=await user(client,"TEACHER","Inactive",{active:false});
    for(const row of [director,principal,accountant,operator,teacher,teacherParent,inactive])await client.staffMember.create({data:{id:randomUUID(),iamPublicKey:randomUUID(),staffCode:`${PREFIX}-${row.name.split(" ").at(-1)}-${randomBytes(2).toString("hex")}`,fullName:row.name,displayName:row.name,designation:row.role==="TEACHER"?"Teacher":row.role,staffType:"TEACHING",status:row===inactive?"INACTIVE":"ACTIVE",userId:row.id}});
    stage="parent contexts";const contextsOne=await listChildContexts(client,{userId:parentOne.id,sessionId:parentOne.sessionId}),contextsMany=await listChildContexts(client,{userId:parentMany.id,sessionId:parentMany.sessionId}),contextsOther=await listChildContexts(client,{userId:unrelated.id,sessionId:unrelated.sessionId});
    stage="parent request";
    const parentRequest=await createAuthenticatedSupportRequest(client,actor(parentOne),{sessionId:parentOne.sessionId,academicYear:"2026-27"},validateAuthenticatedSupportInput({category:"ATTENDANCE",subject:`${PREFIX} attendance support`,description:`${PREFIX} synthetic attendance request without any operational mutation.`,childHandles:[contextsOne.children[0].handle],contextVersion:contextsOne.contextVersion,submissionKey:`${PREFIX}-parent-submit-0001`,consent:true}));
    const retried=await createAuthenticatedSupportRequest(client,actor(parentOne),{sessionId:parentOne.sessionId,academicYear:"2026-27"},validateAuthenticatedSupportInput({category:"ATTENDANCE",subject:`${PREFIX} attendance support`,description:`${PREFIX} synthetic attendance request without any operational mutation.`,childHandles:[contextsOne.children[0].handle],contextVersion:contextsOne.contextVersion,submissionKey:`${PREFIX}-parent-submit-0001`,consent:true}));invariant(retried.id===parentRequest.id,`${PREFIX}_AUTH_RETRY_NOT_IDEMPOTENT`);
    const multi=await createAuthenticatedSupportRequest(client,actor(parentMany),{sessionId:parentMany.sessionId,academicYear:"2026-27"},validateAuthenticatedSupportInput({category:"ACADEMIC_SUPPORT",subject:`${PREFIX} multi-child question`,description:`${PREFIX} synthetic multi-child academic support request.`,childHandles:contextsMany.children.map((row)=>row.handle),contextVersion:contextsMany.contextVersion,submissionKey:`${PREFIX}-multi-submit-0001`,consent:true}));invariant(await client.supportRequestLinkedChild.count({where:{requestId:multi.id}})===2,`${PREFIX}_MULTI_CHILD_SCOPE_FAILED`);
    await denied(()=>createAuthenticatedSupportRequest(client,actor(parentOne),{sessionId:parentOne.sessionId,academicYear:"2026-27"},validateAuthenticatedSupportInput({category:"ATTENDANCE",subject:`${PREFIX} cross family`,description:`${PREFIX} synthetic cross-family tamper request must fail.`,childHandles:[contextsOther.children[0].handle],contextVersion:contextsOne.contextVersion,submissionKey:`${PREFIX}-cross-submit-0001`,consent:true})),`${PREFIX}_CROSS_FAMILY_HANDLE_ALLOWED`);
    stage="staff request";const staffRequest=await createAuthenticatedSupportRequest(client,actor(teacher),{sessionId:teacher.sessionId,academicYear:"2026-27"},validateAuthenticatedSupportInput({category:"TECHNICAL_LOGIN",subject:`${PREFIX} technical request`,description:`${PREFIX} synthetic Staff technical request with no credentials.`,childHandles:[],contextVersion:null,submissionKey:`${PREFIX}-staff-submit-0001`,consent:true}));await denied(()=>createAuthenticatedSupportRequest(client,actor(teacher),{sessionId:teacher.sessionId,academicYear:"2026-27"},validateAuthenticatedSupportInput({category:"STAFF_HR",subject:"Payslip request",description:`${PREFIX} please provide a salary slip through general support.`,submissionKey:`${PREFIX}-payslip-boundary-0001`,consent:true})),`${PREFIX}_PAYSLIP_GENERAL_QUEUE_ALLOWED`);
    const staffHr=await createAuthenticatedSupportRequest(client,actor(teacher),{sessionId:teacher.sessionId,academicYear:"2026-27"},validateAuthenticatedSupportInput({category:"STAFF_HR",subject:`${PREFIX} policy support`,description:`${PREFIX} synthetic policy-document support without salary information.`,submissionKey:`${PREFIX}-staffhr-submit-0001`,consent:true}));
    const manual=await createManualSupportRequest(client,actor(director),validateManualSupportInput({source:"PAPER_FORM_RECORDED_BY_STAFF",requesterName:`${PREFIX} Supplied Parent`,requesterType:"PARENT",requesterIdentifier:`${PREFIX}-UNVERIFIED`,category:"COMPLAINT_AGAINST_STAFF",subject:`${PREFIX} synthetic paper complaint`,statement:`${PREFIX} original synthetic statement retained exactly for governance QA.`,identityVerified:false,signedPaperReference:`${PREFIX}-PAPER-001`,submissionKey:`${PREFIX}-manual-submit-0001`,consentRecorded:true,complainedAboutUserKey:principal.publicKey}));invariant(!manual.identityVerified,`${PREFIX}_MANUAL_IDENTITY_AUTO_VERIFIED`);await denied(()=>assignSupportRequest(client,actor(director),manual.publicKey,{expectedVersion:1,assigneeUserKey:principal.publicKey,reason:"Synthetic prohibited assignment"}),`${PREFIX}_ACCUSED_ASSIGNEE_ALLOWED`);
    const publicBase={requesterName:`${PREFIX} Public`,requesterType:"PARENT",requesterIdentifier:`${PREFIX}-UNKNOWN`,contactChannel:"EMAIL",contactValue:`${PREFIX.toLowerCase()}@example.test`,category:"LOGIN_SUPPORT",message:`${PREFIX} synthetic public login request with no credentials or private data.`,consent:true,honeypot:null,submissionKey:`${PREFIX}-public-0001`},publicOne=await createPublicSupportRequest(client,validatePublicSupportInput(publicBase),`${PREFIX}-source-a`),publicNeutral=await createPublicSupportRequest(client,validatePublicSupportInput({...publicBase,requesterIdentifier:`${PREFIX}-EXISTING-LIKE`,honeypot:"bot",submissionKey:`${PREFIX}-public-0002`}),`${PREFIX}-source-b`);invariant(publicOne.accepted&&publicNeutral.accepted&&publicNeutral.neutralized,`${PREFIX}_PUBLIC_NEUTRAL_BEHAVIOR_FAILED`);
    let row=await triageSupportRequest(client,actor(director),parentRequest.publicKey,{expectedVersion:1,category:"ATTENDANCE",priority:"HIGH",confidentiality:"STANDARD",reason:"Synthetic exact-category triage"});row=await assignSupportRequest(client,actor(director),parentRequest.publicKey,{expectedVersion:2,assigneeUserKey:principal.publicKey,reason:"Synthetic authorised academic assignment"});await addSupportMessage(client,actor(director),parentRequest.publicKey,{expectedVersion:3,messageType:"REQUESTER_VISIBLE",body:`${PREFIX} requester-visible synthetic response.`},"MANAGE");await addSupportMessage(client,actor(director),parentRequest.publicKey,{expectedVersion:4,messageType:"INTERNAL_NOTE",body:`${PREFIX} private internal synthetic note.`},"MANAGE");const ownAfterMessages=await loadSupportRequestForActor(client,actor(parentOne),parentRequest.publicKey,"OWN");invariant(!JSON.stringify(ownAfterMessages).includes("private internal synthetic note"),`${PREFIX}_INTERNAL_NOTE_LEAK`);await resolveSupportRequest(client,actor(director),parentRequest.publicKey,{expectedVersion:5,resolutionCategory:"INFORMATION_PROVIDED",requesterVisibleSummary:`${PREFIX} synthetic requester resolution summary.`,internalActionSummary:`${PREFIX} synthetic internal resolution action.`});await reopenOwnSupportRequest(client,actor(parentOne),parentRequest.publicKey,{expectedVersion:6,reason:`${PREFIX} synthetic reason to reopen for further review.`});await resolveSupportRequest(client,actor(director),parentRequest.publicKey,{expectedVersion:7,resolutionCategory:"INFORMATION_PROVIDED",requesterVisibleSummary:`${PREFIX} second synthetic requester resolution.`,internalActionSummary:`${PREFIX} second synthetic internal action.`});await submitSupportSatisfaction(client,actor(parentOne),parentRequest.publicKey,{rating:5,issueUnderstood:true,responseClear:true,issueResolved:true,comment:`${PREFIX} aggregate-only feedback.`});
    const concurrent=await Promise.allSettled([assignSupportRequest(client,actor(director),staffRequest.publicKey,{expectedVersion:1,assigneeUserKey:operator.publicKey,reason:"Synthetic technical assignment A"}),assignSupportRequest(client,actor(director),staffRequest.publicKey,{expectedVersion:1,assigneeUserKey:director.publicKey,reason:"Synthetic technical assignment B"})]);invariant(concurrent.filter((item)=>item.status==="fulfilled").length===1,`${PREFIX}_CONCURRENT_ASSIGNMENT_NOT_SERIALIZED`);
    const safety=await createManualSupportRequest(client,actor(director),validateManualSupportInput({source:"IN_PERSON",requesterName:`${PREFIX} Safety Requester`,requesterType:"OTHER",category:"SAFETY_OR_BULLYING",subject:`${PREFIX} restricted safety concern`,statement:`${PREFIX} synthetic safety concern with no real person or allegation.`,identityVerified:false,submissionKey:`${PREFIX}-safety-submit-0001`,consentRecorded:true}));await triageSupportRequest(client,actor(director),safety.publicKey,{expectedVersion:1,category:"SAFETY_OR_BULLYING",priority:"URGENT",confidentiality:"SAFEGUARDING",reason:"Synthetic restricted safeguarding triage"});invariant(!(await listManagedSupportRequests(client,actor(operator))).some((item:any)=>item.publicKey===safety.publicKey),`${PREFIX}_SAFEGUARDING_OPERATOR_LEAK`);invariant((await listManagedSupportRequests(client,actor(director))).some((item:any)=>item.publicKey===safety.publicKey),`${PREFIX}_DIRECTOR_OVERSIGHT_MISSING`);
    const snapshot=await client.supportSlaSnapshot.findFirstOrThrow({where:{requestId:staffHr.id},orderBy:{createdAt:"desc"}});await client.supportSlaSnapshot.update({where:{id:snapshot.id},data:{acknowledgmentTargetAt:new Date(Date.now()-60_000)}});const overdueOne=await escalateOverdueSupportRequests(client,actor(director)),overdueTwo=await escalateOverdueSupportRequests(client,actor(director));invariant(overdueOne.created>=1&&overdueTwo.created===0,`${PREFIX}_OVERDUE_ESCALATION_NOT_IDEMPOTENT`);
    const png=await sharp({create:{width:20,height:20,channels:3,background:"#225588"}}).png().toBuffer(),file={name:`${PREFIX}.png`,type:"image/png",size:png.length,arrayBuffer:async()=>Uint8Array.from(png).buffer} as File,validated=await validateSupportUpload(file,"AUTHENTICATED"),storageKey=await storeSupportFile(validated),attachment=await createSupportAttachmentRecord(client,actor(teacher),staffRequest.publicKey,null,{...validated,storageKey},"REQUESTER_VISIBLE","OWN");await loadSupportAttachment(client,actor(teacher),attachment.publicKey,"OWN");await denied(()=>loadSupportAttachment(client,actor(unrelated),attachment.publicKey,"OWN"),`${PREFIX}_CROSS_REQUEST_ATTACHMENT_ALLOWED`);
    const assetKey=randomBytes(32),assetPath=path.join(root,"support-assets.npsbackup"),asset=await createAndVerifySupportAssetBackup(client,{artifactPath:assetPath,key:assetKey,keyVersion:"V91",restoreRoots:[path.join(root,"asset-a"),path.join(root,"asset-b")]});invariant(asset.attachmentCount===1&&asset.firstRestore.assetDigest===asset.secondRestore.assetDigest,`${PREFIX}_ASSET_DOUBLE_RESTORE_FAILED`);await denied(()=>restoreSupportAssetBackup(readFileSync(assetPath),{key:randomBytes(32),targetRoot:path.join(root,"wrong-key")}),`${PREFIX}_WRONG_ASSET_KEY_ACCEPTED`);const corrupt=Buffer.from(readFileSync(assetPath));corrupt[corrupt.length-1]^=1;await denied(()=>restoreSupportAssetBackup(corrupt,{key:assetKey,targetRoot:path.join(root,"corrupt")}),`${PREFIX}_CORRUPT_ASSET_ACCEPTED`);
    const backup=parseAndValidateBackup(await generateFullBackup(client as never,{generatedBy:`${PREFIX} copied-database QA`}));invariant(backup.supportRequests.length>=7&&backup.supportRequestAttachments.length===1,`${PREFIX}_LOGICAL_BACKUP_INCOMPLETE`);const first=await restoreSupportBackup(restore,backup),second=await restoreSupportBackup(restore,backup);invariant(first.supportRequests.created===backup.supportRequests.length&&second.supportRequests.skipped===backup.supportRequests.length&&await restore.supportRequestAttachment.count()===1,`${PREFIX}_LOGICAL_RESTORE_NOT_IDEMPOTENT`);
    await denied(()=>client.supportRequest.delete({where:{id:parentRequest.id}}),`${PREFIX}_SUBMITTED_REQUEST_HARD_DELETE_ALLOWED`);await denied(()=>loadSupportRequestForActor(client,actor(unrelated),parentRequest.publicKey,"OWN"),`${PREFIX}_CROSS_PARENT_REQUEST_ALLOWED`);await client.studentGuardian.delete({where:{id:one.students[0].link.id}});await denied(()=>loadSupportRequestForActor(client,actor(parentOne),parentRequest.publicKey,"OWN"),`${PREFIX}_REMOVED_GUARDIAN_LINK_STILL_ALLOWED`);
    const viewerReport=await supportReport(client,actor(viewer));invariant(viewerReport.lowCountSuppression&&viewerReport.staffRanking===false,`${PREFIX}_VIEWER_REPORT_GOVERNANCE_FAILED`);invariant((await listOwnSupportRequests(client,actor(teacher))).every((item:any)=>item.publicKey!==parentRequest.publicKey),`${PREFIX}_STAFF_PARENT_SCOPE_LEAK`);invariant(await client.supportRequest.count({where:{requesterName:{contains:"real"}}})===0,`${PREFIX}_REAL_REQUEST_FIXTURE_DETECTED`);invariant(await client.notificationCampaign.count({where:{channel:{not:"IN_APP"},campaignNumber:{startsWith:"SUPPORT1A-"}}})===0,`${PREFIX}_LIVE_PROVIDER_ACTIVATED`);
    const after={sha256:fileSha(operational),size:statSync(operational).size};invariant(JSON.stringify(before)===JSON.stringify(after),`${PREFIX}_OPERATIONAL_DATABASE_CHANGED`);if(KEEP){writeFileSync(path.join(root,"browser-credentials.json"),JSON.stringify({password:browserPassword,director:{username:director.username},principal:{username:principal.username},accountant:{username:accountant.username},operator:{username:operator.username},teacher:{username:teacher.username},teacherParent:{username:teacherParent.username},parent:{username:parentMany.username},viewer:{username:viewer.username}}),{flag:"wx"});writeFileSync(path.join(root,"runtime-env.json"),JSON.stringify({NODE_ENV:"production",DATABASE_URL:url(qaDb),SESSION_SECRET:browserSecret,AUTH_SECRET:browserSecret,APP_ORIGIN:`http://localhost:${browserPort}`,PORT:String(browserPort),SUPPORT_PRIVATE_STORAGE_ROOT:storage,QPDF_EXECUTABLE_PATH:process.env.QPDF_EXECUTABLE_PATH??""}),{flag:"wx"});}console.log(JSON.stringify({result:`${PREFIX}_COPIED_DATABASE_VERIFIED`,operationalMutation:false,deployTwice:true,roleMatrix:{superAdmins:2,director:1,principal:1,accountant:1,computerOperator:1,teacher:1,teacherParent:1,parentOne:1,parentMany:1,unrelatedParent:1,viewer:1,inactive:1},publicAntiEnumeration:true,parentChildScope:true,staffScope:true,internalNoteIsolation:true,restrictedVisibility:true,concurrentAssignment:true,overdueIdempotent:true,logicalRestoreTwice:true,assetRestoreTwice:true,requests:backup.supportRequests.length,attachments:backup.supportRequestAttachments.length,browserFixture:KEEP?{port:browserPort,credentialsPath:path.join(root,"browser-credentials.json"),runtimePath:path.join(root,"runtime-env.json")}:undefined}));
  }finally{await client.$disconnect();await restore.$disconnect();if(!KEEP){cleanup();cleanup();}}if(!KEEP&&existsSync(root))throw new Error(`${PREFIX}_QA_RESIDUE_REMAINS`);
}
async function denied(work:()=>Promise<unknown>,code:string){try{await work();}catch{return;}throw new Error(code);}
function invariant(value:unknown,code:string):asserts value{if(!value)throw new Error(code);}
function sha(value:Uint8Array){return createHash("sha256").update(value).digest("hex");}function fileSha(file:string){return sha(readFileSync(file));}
if(process.argv.includes("cleanup")){cleanup();console.log(JSON.stringify({result:`${PREFIX}_QA_FIXTURES_REMOVED`,exists:existsSync(root)}));}else main().catch((error)=>{console.error(`${stage}: ${error instanceof Error?error.message:String(error)}`);process.exitCode=1;});
