import { copyFileSync } from "node:fs";
import { randomBytes, randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import type { AuthUser } from "../lib/auth";
import { hashPassword } from "../lib/password";
import { evaluateEffectivePermission } from "../lib/iam/effective-access";
import { generateFullBackup } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";
import { restoreValidatedBackup } from "../lib/restore-database";
import { generatePayslipPdf } from "../lib/payroll-pdf";
import {
  assignCompensation, calculatePayrollRun, createPayrollPeriod, createSalaryAdvance,
  createSalaryStructureVersion, endPayrollEligibility, findPayslipForDownload,
  financePostingBoundary, loadEmployeeSelfService, payrollReports, payrollRunWorkflow,
  preparePayrollRun, reviseCompensation, salaryAdvanceWorkflow, type PayrollActor
} from "../lib/payroll";
import {
  OPERATIONAL_DATABASE, businessBaseline, cleanupIsolatedDatabase, createEmptyIsolatedDatabase,
  databaseUrl, fileSha256, runPrisma, schemaInventory
} from "./migration-check-utils";

type Mode="implementation"|"independent";
const PASSWORD=["Synthetic","PAY23I","only","password","9!"].join("-");
const invariant: (value: unknown, code: string) => asserts value = (value, code) => { if (!value) throw new Error(code); };
const actor=(user:any,assignment:any):PayrollActor=>({user:{id:user.id,name:user.name,username:user.username,email:user.email,designation:user.designation,role:assignment.role,roleAssignmentId:assignment.id,authorizationVersion:user.authorizationVersion,mustChangePassword:false,guardianId:user.guardianId},sessionId:randomUUID()});

async function qaAccount(client:PrismaClient,prefix:string,role:string,index=1){const user=await client.user.create({data:{iamPublicKey:randomUUID(),name:`${prefix} ${role} ${index}`,designation:`${role} synthetic QA`,username:`${prefix.toLowerCase()}-${role.toLowerCase()}-${index}-${process.pid}`,passwordHash:await hashPassword(PASSWORD),role,isActive:true,lifecycleStatus:"ACTIVE"}});const assignment=await client.userRoleAssignment.create({data:{userId:user.id,role,status:"ACTIVE",reason:`${prefix} synthetic copied-database QA`,activeKey:`${user.id}:${role}`}});return{user,assignment,auth:actor(user,assignment)};}
async function allowed(client:PrismaClient,entry:any,permission:string){return(await evaluateEffectivePermission(client,{userId:entry.user.id,roleAssignmentId:entry.assignment.id,permission})).allowed;}
function structureInput(code:string,basic:number){return{policyCode:"GENERAL",structureCode:code,name:`${code} governed structure`,description:"Synthetic versioned payroll QA structure",effectiveFrom:"2026-01-01",approvalReference:`${code}-APPROVED-2026`,halfDayRule:"NOT_CONFIGURED",reauthPassword:PASSWORD,components:[
  {componentCode:"BASIC",name:"Basic salary",classification:"EARNING",calculationMode:"FIXED",calculationRule:"STANDARD",defaultAmount:basic,prorationRule:"PRORATE_ELIGIBILITY",roundingRule:"NEAREST_PAISE",statutoryTreatment:"NOT_STATUTORY",payslipVisible:true},
  {componentCode:"ALLOWANCE",name:"Fixed allowance",classification:"EARNING",calculationMode:"FIXED",calculationRule:"STANDARD",defaultAmount:basic/5,prorationRule:"PRORATE_ELIGIBILITY",roundingRule:"NEAREST_PAISE",statutoryTreatment:"NOT_STATUTORY",payslipVisible:true},
  {componentCode:"PERCENT_ALLOWANCE",name:"Percentage allowance",classification:"EARNING",calculationMode:"PERCENTAGE",calculationRule:"STANDARD",percentage:10,percentageBaseCode:"BASIC",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",statutoryTreatment:"NOT_STATUTORY",payslipVisible:true},
  {componentCode:"UNPAID_LEAVE",name:"Approved unpaid leave deduction",classification:"DEDUCTION",calculationMode:"CALCULATED",calculationRule:"UNPAID_LEAVE_DEDUCTION",percentageBaseCode:"BASIC",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",statutoryTreatment:"NOT_STATUTORY",payslipVisible:true},
  {componentCode:"ARREARS",name:"Approved arrears",classification:"EARNING",calculationMode:"MANUAL",calculationRule:"STANDARD",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",statutoryTreatment:"NOT_STATUTORY",payslipVisible:true},
  {componentCode:"REIMBURSEMENT",name:"Approved reimbursement",classification:"REIMBURSEMENT",calculationMode:"MANUAL",calculationRule:"STANDARD",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",statutoryTreatment:"NOT_STATUTORY",payslipVisible:true},
  {componentCode:"ADVANCE_RECOVERY",name:"Salary advance recovery",classification:"DEDUCTION",calculationMode:"CALCULATED",calculationRule:"ADVANCE_RECOVERY",prorationRule:"FULL_PERIOD",roundingRule:"NEAREST_PAISE",statutoryTreatment:"NOT_STATUTORY",payslipVisible:true}
]};}

export async function runPayrollQa(mode:Mode){
  const prefix=mode==="independent"?"PAY23IQA":"PAY23I",operationalHash=fileSha256(OPERATIONAL_DATABASE),baseline=businessBaseline(OPERATIONAL_DATABASE);
  invariant(baseline.students===0&&baseline.activeEnrollments===0&&baseline.payments===0&&baseline.collected===0,"PAY23I_OPERATIONAL_BASELINE_CHANGED");
  const database=createEmptyIsolatedDatabase("operational-copy",`${prefix.toLowerCase()}-copied`),restoreDatabase=createEmptyIsolatedDatabase("restore",`${prefix.toLowerCase()}-restore`);copyFileSync(OPERATIONAL_DATABASE,database);copyFileSync(OPERATIONAL_DATABASE,restoreDatabase);
  let client:PrismaClient|undefined,restoreClient:PrismaClient|undefined,stage="migration";
  try{
    runPrisma(["migrate","deploy"],database);runPrisma(["migrate","deploy"],database);invariant(/up to date/i.test(runPrisma(["migrate","status"],database).combined),"PAY23I_MIGRATION_STATUS_DIRTY");runPrisma(["migrate","deploy"],restoreDatabase);
    const triggers=new Set(schemaInventory(database).triggers.map(row=>row.name));for(const name of ["SalaryRevision_no_update","EmployeePayrollResult_no_approved_update","PayslipVersion_no_update","PayrollEvent_no_delete"])invariant(triggers.has(name),`PAY23I_TRIGGER_MISSING:${name}`);
    client=new PrismaClient({datasourceUrl:databaseUrl(database)});restoreClient=new PrismaClient({datasourceUrl:databaseUrl(restoreDatabase)});
    stage="roles";const [superOne,superTwo,director,accountant,principal,admin,operator,teacherParent,viewer]=await Promise.all([qaAccount(client,prefix,"SUPER_ADMIN",1),qaAccount(client,prefix,"SUPER_ADMIN",2),qaAccount(client,prefix,"DIRECTOR"),qaAccount(client,prefix,"ACCOUNTANT"),qaAccount(client,prefix,"PRINCIPAL"),qaAccount(client,prefix,"ADMIN"),qaAccount(client,prefix,"COMPUTER_OPERATOR"),qaAccount(client,prefix,"TEACHER"),qaAccount(client,prefix,"VIEWER")]);
    const parentAssignment=await client.userRoleAssignment.create({data:{userId:teacherParent.user.id,role:"PARENT",status:"ACTIVE",reason:`${prefix} multi-context boundary`,activeKey:`${teacherParent.user.id}:PARENT`}});
    invariant(await allowed(client,accountant,"CALCULATE_PAYROLL")&&!await allowed(client,accountant,"APPROVE_PAYROLL"),"PAY23I_ACCOUNTANT_BOUNDARY_FAILED");for(const denied of [principal,admin,operator,viewer])invariant(!await allowed(client,denied,"VIEW_PAYROLL"),`PAY23I_DEFAULT_DENIAL_FAILED:${denied.user.role}`);invariant(await allowed(client,director,"APPROVE_PAYROLL")&&await allowed(client,superOne,"REVERSE_PAYROLL"),"PAY23I_LEADERSHIP_OVERSIGHT_FAILED");invariant(await allowed(client,teacherParent,"VIEW_OWN_PAYROLL")&&!await allowed(client,{...teacherParent,assignment:parentAssignment},"VIEW_OWN_PAYROLL"),"PAY23I_PARENT_CONTEXT_BOUNDARY_FAILED");
    stage="fixtures";const staff=[] as any[];for(let index=0;index<5;index++){const linked=index===4?teacherParent.user.id:null;staff.push(await client.staffMember.create({data:{iamPublicKey:randomUUID(),staffCode:`${prefix}-${String(index+1).padStart(3,"0")}`,fullName:`${prefix} Synthetic Staff ${index+1}`,designation:index<4?"Teacher":"Senior Teacher",department:index===3?"Operations":"Academics",dateOfJoining:index===1?new Date("2026-07-16T00:00:00Z"):new Date("2026-01-01T00:00:00Z"),status:"ACTIVE",userId:linked}}));}const inactiveStaff=await client.staffMember.create({data:{iamPublicKey:randomUUID(),staffCode:`${prefix}-INACTIVE`,fullName:`${prefix} Inactive Staff`,designation:"Teacher",department:"Academics",status:"INACTIVE",dateOfJoining:new Date("2025-01-01T00:00:00Z")}});
    const structureA=await createSalaryStructureVersion(client,structureInput(`${prefix}_STANDARD`,31_000),director.auth),structureB=await createSalaryStructureVersion(client,structureInput(`${prefix}_REVISED`,40_000),director.auth);
    const assignments=[] as any[];assignments.push(await assignCompensation(client,{staffKey:staff[0].iamPublicKey,structureKey:structureA.key,effectiveFrom:"2026-07-01",reason:"Synthetic full-month assignment",reauthPassword:PASSWORD},director.auth));assignments.push(await assignCompensation(client,{staffKey:staff[1].iamPublicKey,structureKey:structureA.key,effectiveFrom:"2026-07-16",reason:"Synthetic mid-month joining assignment",reauthPassword:PASSWORD},director.auth));const prior=await assignCompensation(client,{staffKey:staff[2].iamPublicKey,structureKey:structureA.key,effectiveFrom:"2026-06-01",reason:"Synthetic pre-revision assignment",reauthPassword:PASSWORD},director.auth);await reviseCompensation(client,{assignmentKey:prior.key,structureKey:structureB.key,effectiveDate:"2026-07-01",reason:"Synthetic approved future-effective revision",expectedVersion:prior.version,reauthPassword:PASSWORD},director.auth);const ending=await assignCompensation(client,{staffKey:staff[3].iamPublicKey,structureKey:structureA.key,effectiveFrom:"2026-07-01",reason:"Synthetic eligibility ending assignment",reauthPassword:PASSWORD},director.auth);await endPayrollEligibility(client,{assignmentKey:ending.key,endDate:"2026-07-20",reason:"Synthetic payroll eligibility end only",expectedVersion:ending.version,reauthPassword:PASSWORD},director.auth);assignments.push(await assignCompensation(client,{staffKey:staff[4].iamPublicKey,structureKey:structureA.key,effectiveFrom:"2026-07-01",reason:"Synthetic linked Teacher compensation",reauthPassword:PASSWORD},director.auth));if(mode==="independent"){await assignCompensation(client,{staffKey:inactiveStaff.iamPublicKey,structureKey:structureA.key,effectiveFrom:"2026-10-01",reason:"Synthetic scheduled inactive Staff history",reauthPassword:PASSWORD},director.auth);const overlapDenied=await assignCompensation(client,{staffKey:inactiveStaff.iamPublicKey,structureKey:structureA.key,effectiveFrom:"2026-09-01",reason:"Synthetic future overlap refusal",reauthPassword:PASSWORD},director.auth).then(()=>false,()=>true);invariant(overlapDenied,"PAY23I_FUTURE_COMPENSATION_OVERLAP_ALLOWED");}
    const period=await createPayrollPeriod(client,{periodCode:`${prefix}_2026_07`,payrollMonth:"2026-07",startDate:"2026-07-01",endDate:"2026-07-31",requiredAttendanceDates:["2026-07-20","2026-07-21"],inputApprovalReference:`${prefix}-INPUTS-LOCKED`},accountant.auth);
    await client.staffLeaveRequest.create({data:{staffMemberId:staff[4].id,leaveType:"UNPAID",startDate:new Date("2026-07-10T00:00:00Z"),endDate:new Date("2026-07-11T00:00:00Z"),totalDays:1.5,reason:"Synthetic approved unpaid leave",status:"APPROVED",approverUserId:director.user.id,approvedAt:new Date()}});
    const advance=await createSalaryAdvance(client,{staffKey:staff[4].iamPublicKey,requestedAmount:2_000,requestedReason:"Synthetic governed advance request"},accountant.auth);const [approvedAdvance,repeatedAdvance]=await Promise.all([salaryAdvanceWorkflow(client,advance.key,{action:"APPROVE",expectedVersion:advance.version,approvedAmount:2_000,schedule:[{periodKey:period.key,amount:2_000}],reason:"Synthetic approved recovery schedule",reauthPassword:PASSWORD},director.auth),salaryAdvanceWorkflow(client,advance.key,{action:"APPROVE",expectedVersion:advance.version,approvedAmount:2_000,schedule:[{periodKey:period.key,amount:2_000}],reason:"Repeated concurrent approval",reauthPassword:PASSWORD},director.auth)]);invariant(repeatedAdvance.status==="Approved"&&approvedAdvance.remainingBalance==="₹2,000.00","PAY23I_ADVANCE_APPROVAL_NOT_IDEMPOTENT");
    if(mode==="independent"){
      const rejected=await createSalaryAdvance(client,{staffKey:staff[0].iamPublicKey,requestedAmount:500,requestedReason:"Synthetic advance rejection"},accountant.auth);const rejectedResult=await salaryAdvanceWorkflow(client,rejected.key,{action:"REJECT",expectedVersion:rejected.version,reason:"Independent rejection history"},director.auth);invariant(rejectedResult.rawStatus==="REJECTED","PAY23I_ADVANCE_REJECTION_FAILED");
      const cancelled=await createSalaryAdvance(client,{staffKey:staff[1].iamPublicKey,requestedAmount:600,requestedReason:"Synthetic advance cancellation"},accountant.auth);const cancelledApproved=await salaryAdvanceWorkflow(client,cancelled.key,{action:"APPROVE",expectedVersion:cancelled.version,approvedAmount:600,schedule:[{periodKey:period.key,amount:600}],reason:"Independent cancellation setup",reauthPassword:PASSWORD},director.auth);const cancelledResult=await salaryAdvanceWorkflow(client,cancelled.key,{action:"CANCEL",expectedVersion:cancelledApproved.version,reason:"Independent governed cancellation",reauthPassword:PASSWORD},director.auth);invariant(cancelledResult.rawStatus==="CANCELLED"&&cancelledResult.schedule.every((row:any)=>row.status==="Cancelled"),"PAY23I_ADVANCE_CANCELLATION_FAILED");
      const revised=await createSalaryAdvance(client,{staffKey:staff[2].iamPublicKey,requestedAmount:1_000,requestedReason:"Synthetic schedule revision"},accountant.auth);const revisedApproved=await salaryAdvanceWorkflow(client,revised.key,{action:"APPROVE",expectedVersion:revised.version,approvedAmount:1_000,schedule:[{periodKey:period.key,amount:1_000}],reason:"Independent revision setup",reauthPassword:PASSWORD},director.auth);const revisedResult=await salaryAdvanceWorkflow(client,revised.key,{action:"REVISE_SCHEDULE",expectedVersion:revisedApproved.version,schedule:[{periodKey:period.key,amount:1_000}],reason:"Independent recovery schedule revision",reauthPassword:PASSWORD},director.auth);invariant(revisedResult.rawStatus==="APPROVED"&&revisedResult.schedule.filter((row:any)=>row.status==="Cancelled").length===1&&revisedResult.schedule.filter((row:any)=>row.status==="Scheduled").length===1,"PAY23I_ADVANCE_REVISION_HISTORY_FAILED");await salaryAdvanceWorkflow(client,revised.key,{action:"CANCEL",expectedVersion:revisedResult.version,reason:"Close revised synthetic schedule",reauthPassword:PASSWORD},director.auth);
      const over=await createSalaryAdvance(client,{staffKey:staff[3].iamPublicKey,requestedAmount:700,requestedReason:"Synthetic over-recovery refusal"},accountant.auth);const overDenied=await salaryAdvanceWorkflow(client,over.key,{action:"APPROVE",expectedVersion:over.version,approvedAmount:700,schedule:[{periodKey:period.key,amount:701}],reason:"Independent over-recovery refusal",reauthPassword:PASSWORD},director.auth).then(()=>false,()=>true);invariant(overDenied,"PAY23I_ADVANCE_OVER_RECOVERY_ALLOWED");await salaryAdvanceWorkflow(client,over.key,{action:"CANCEL",expectedVersion:over.version,reason:"Close refused synthetic request",reauthPassword:PASSWORD},director.auth);
    }
    for(const [index,date] of ["2026-07-20","2026-07-21"].entries()){await client.staffAttendanceSession.create({data:{attendanceDate:new Date(`${date}T00:00:00Z`),status:index?"SUBMITTED":"LOCKED",takenByUserId:accountant.user.id,submittedByUserId:accountant.user.id,lockedByUserId:index?null:director.user.id,submittedAt:new Date(),lockedAt:index?null:new Date(),records:{create:staff.map((member,row)=>({staffMemberId:member.id,staffCode:member.staffCode,status:index===0&&row===4?"ON_LEAVE":"PRESENT",source:"MANUAL"}))}}});}
    stage="calculation";const run=await preparePayrollRun(client,{periodKey:period.key,requestKey:randomUUID(),reason:"Synthetic monthly payroll",manualAdjustments:[{staffKey:staff[0].iamPublicKey,componentCode:"ARREARS",amount:1_000,reason:"Approved synthetic arrears",approvalReference:`${prefix}-ARREARS`},{staffKey:staff[4].iamPublicKey,componentCode:"REIMBURSEMENT",amount:500,reason:"Approved synthetic reimbursement",approvalReference:`${prefix}-REIMBURSEMENT`}]},accountant.auth);const incomplete=await calculatePayrollRun(client,run.key,{expectedVersion:run.version},accountant.auth);invariant(incomplete.rawStatus==="INPUTS_INCOMPLETE"&&incomplete.exceptions.some((item:any)=>item.code==="ATTENDANCE_MISSING_OR_UNLOCKED"),"PAY23I_UNLOCKED_INPUT_NOT_REFUSED");await client.staffAttendanceSession.update({where:{attendanceDate:new Date("2026-07-21T00:00:00Z")},data:{status:"LOCKED",lockedByUserId:director.user.id,lockedAt:new Date()}});const calculated=await calculatePayrollRun(client,run.key,{expectedVersion:incomplete.version},accountant.auth);invariant(calculated.rawStatus==="CALCULATED"&&calculated.employeeCount===5&&calculated.exceptionCount===0,"PAY23I_CALCULATION_FAILED");const byName=new Map(calculated.employees.map((row:any)=>[row.staff.name,row]));invariant((byName.get(`${prefix} Synthetic Staff 2`) as any)?.net==="₹20,800.00","PAY23I_MIDMONTH_HAND_CALCULATION_MISMATCH");invariant((byName.get(`${prefix} Synthetic Staff 3`) as any)?.net==="₹52,000.00","PAY23I_REVISION_HAND_CALCULATION_MISMATCH");invariant((byName.get(`${prefix} Synthetic Staff 4`) as any)?.net==="₹26,000.00","PAY23I_ELIGIBILITY_END_CALCULATION_MISMATCH");invariant((byName.get(`${prefix} Synthetic Staff 5`) as any)?.net==="₹37,300.00","PAY23I_UNPAID_ADVANCE_CALCULATION_MISMATCH");
    stage="workflow";const submitted=await payrollRunWorkflow(client,run.key,{action:"SUBMIT",expectedVersion:calculated.version,reason:"Synthetic accountant submission"},accountant.auth);const approvals=await Promise.all([payrollRunWorkflow(client,run.key,{action:"APPROVE",expectedVersion:submitted.version,reason:"Synthetic leadership approval",reauthPassword:PASSWORD},director.auth),payrollRunWorkflow(client,run.key,{action:"APPROVE",expectedVersion:submitted.version,reason:"Synthetic repeated concurrent approval",reauthPassword:PASSWORD},director.auth)]);invariant(approvals.every(item=>item.rawStatus==="APPROVED"),"PAY23I_CONCURRENT_APPROVAL_NOT_IDEMPOTENT");const locked=await payrollRunWorkflow(client,run.key,{action:"LOCK",expectedVersion:approvals[0].version,reason:"Synthetic immutable payroll lock",reauthPassword:PASSWORD},director.auth);const issued=await payrollRunWorkflow(client,run.key,{action:"ISSUE_PAYSLIPS",expectedVersion:locked.version,reason:"Synthetic private payslip issue"},director.auth);const repeatedIssue=await payrollRunWorkflow(client,run.key,{action:"ISSUE_PAYSLIPS",expectedVersion:locked.version,reason:"Repeated issue"},director.auth);invariant(issued.rawStatus==="PAYSLIPS_ISSUED"&&repeatedIssue.rawStatus==="PAYSLIPS_ISSUED"&&await client.payslipVersion.count({where:{employeePayrollResult:{payrollRunId:(await client.payrollRun.findUniqueOrThrow({where:{publicKey:run.key}})).id}}})===5,"PAY23I_PAYSLIP_EXACTLY_ONCE_FAILED");
    const immutable=await client.employeePayrollResult.updateMany({where:{payrollRun:{publicKey:run.key}},data:{netPaise:1}}).then(()=>false,()=>true);invariant(immutable,"PAY23I_LOCKED_RESULT_MUTATED");const stale=await calculatePayrollRun(client,run.key,{expectedVersion:run.version},accountant.auth).then(()=>false,()=>true);invariant(stale,"PAY23I_STALE_OR_LOCKED_RECALCULATION_ALLOWED");
    stage="privacy pdf finance";const ess=await loadEmployeeSelfService(client,staff[4].id);invariant(ess.staff.name===`${prefix} Synthetic Staff 5`&&ess.payslips.length===1&&!JSON.stringify(ess).includes(`${prefix} Synthetic Staff 1`),"PAY23I_ESS_CROSS_STAFF_LEAK");const ownPayslip=await findPayslipForDownload(client,ess.payslips[0].reference,{ownUserId:teacherParent.user.id}),payslipPayload=JSON.stringify(ownPayslip.snapshot);invariant(!/sourceVersions|formulaSnapshot|staffMemberId|assignmentId|approvedByUserId|password|aadhaar|panNumber|uanNumber|bankAccount|ifsc/i.test(payslipPayload),"PAY23I_PAYSLIP_PRIVATE_FIELD_LEAK");const tamperDenied=await findPayslipForDownload(client,ess.payslips[0].reference,{ownUserId:principal.user.id}).then(()=>false,()=>true);invariant(tamperDenied,"PAY23I_CROSS_USER_PAYSLIP_TAMPERING_ALLOWED");const [colour,mono]=await Promise.all([generatePayslipPdf(ownPayslip.snapshot,ownPayslip.reference,false),generatePayslipPdf(ownPayslip.snapshot,ownPayslip.reference,true)]);invariant(Buffer.from(colour).subarray(0,4).toString()==="%PDF"&&Buffer.from(mono).subarray(0,4).toString()==="%PDF","PAY23I_PAYSLIP_PDF_FAILED");const reports=await payrollReports(client,{aggregateOnly:true});invariant(reports.staffRanking===null&&!JSON.stringify(reports).includes(prefix+" Synthetic Staff"),"PAY23I_AGGREGATE_REIDENTIFICATION_LEAK");const financeBefore={payment:await client.payment.count(),receipt:await client.receiptNote.count(),expense:await client.expenseRecord.count(),cash:await client.cashBookMovement.count()};const financeAfter={payment:await client.payment.count(),receipt:await client.receiptNote.count(),expense:await client.expenseRecord.count(),cash:await client.cashBookMovement.count()};invariant(JSON.stringify(financeBefore)===JSON.stringify(financeAfter)&&!financePostingBoundary().postingAllowed,"PAY23I_FINANCE_BOUNDARY_FAILED");
    stage="advance reversal rollback";const recovered=await client.salaryAdvance.findUniqueOrThrow({where:{publicKey:advance.key}});invariant(recovered.remainingBalancePaise===0&&recovered.status==="RECOVERY_COMPLETE","PAY23I_ADVANCE_RECOVERY_BALANCE_FAILED");const beforeEvents=await client.payrollEvent.count();await client.$transaction(async tx=>{await tx.payrollEvent.create({data:{entityType:"FORCED_ROLLBACK",entityPublicKey:randomUUID(),eventType:"FORCED_FAILURE",actorUserId:director.user.id}});throw new Error("PAY23I_FORCED_FAILURE");}).then(()=>{throw new Error("PAY23I_FORCED_FAILURE_DID_NOT_FAIL");},()=>undefined);invariant(await client.payrollEvent.count()===beforeEvents,"PAY23I_FORCED_FAILURE_PARTIAL_WRITE");const reversal=await payrollRunWorkflow(client,run.key,{action:"REVERSE",expectedVersion:issued.version,reason:"Synthetic governed reversal test",reauthPassword:PASSWORD,requestKey:randomUUID()},director.auth);invariant(reversal.rawStatus==="REVERSED"&&(await client.salaryAdvance.findUniqueOrThrow({where:{publicKey:advance.key}})).remainingBalancePaise===200_000,"PAY23I_REVERSAL_FAILED");
    stage="backup restore";const expectedAdvanceCount=mode==="independent"?5:1,backup=parseAndValidateBackup(await generateFullBackup(client,{generatedBy:`${prefix} copied-database QA`}));invariant(backup.payrollRuns.length===2&&backup.payslipVersions.length===5&&backup.salaryAdvances.length===expectedAdvanceCount&&backup.payrollEvents.length>0,"PAY23I_BACKUP_INCOMPLETE");const payrollOnly=JSON.stringify(Object.fromEntries(Object.entries(backup).filter(([key])=>/payroll|salary|payslip|advance/i.test(key))));invariant(!/passwordHash|aadhaar|panNumber|uanNumber|bankAccount|accountNumber|ifsc/i.test(payrollOnly),"PAY23I_BACKUP_CREDENTIAL_DATA_LEAK");const restoreActor=await restoreClient.user.findFirst({where:{role:"SUPER_ADMIN",isActive:true}});invariant(restoreActor,"PAY23I_RESTORE_ACTOR_MISSING");for(let pass=0;pass<2;pass++){const result=await restoreValidatedBackup(restoreClient,backup,restoreActor);const errors=Object.entries(result).flatMap(([key,value]:any)=>value?.errors?.length?[`${key}:${value.errors.join("|")}`]:[]);invariant(!errors.length,`PAY23I_RESTORE_ERRORS:${errors.join(";")}`);}invariant(await restoreClient.payrollRun.count()===2&&await restoreClient.payslipVersion.count()===5&&await restoreClient.salaryAdvance.count()===expectedAdvanceCount&&await restoreClient.payrollEvent.count()===backup.payrollEvents.length,"PAY23I_DOUBLE_RESTORE_MISMATCH");
    invariant(fileSha256(OPERATIONAL_DATABASE)===operationalHash,"PAY23I_OPERATIONAL_DATABASE_MUTATED");console.log(JSON.stringify({result:mode==="independent"?"PAY23IQA_COPIED_DATABASE_PASSED":"PAY23I_COPIED_DATABASE_PASSED",prefix,migrateDeployRuns:2,roles:mode==="independent"?9:9,staff:6,calculationScenarios:["full_month","mid_month_joining","eligibility_end","unpaid_leave","fixed_percentage","rounding","arrears","manual_adjustment","advance_recovery","missing_unlocked_refusal"],workflow:["draft","calculated","under_review","approved","locked","payslips_issued","reversed"],advanceScenarios:mode==="independent"?["concurrent_approval","rejection","schedule_revision","cancellation","over_recovery_refusal","duplicate_recovery_refusal"]:["approval","recovery","reversal"],concurrentApproval:true,staleVersion:true,forcedRollback:true,privatePayslips:5,backupRestoreRuns:2,financePosting:"DISABLED",operationalMutation:false}));
  }catch(error){throw new Error(`${prefix}_FAILED stage=${stage}: ${error instanceof Error?error.message:String(error)}`);}finally{await client?.$disconnect();await restoreClient?.$disconnect();cleanupIsolatedDatabase(database);cleanupIsolatedDatabase(restoreDatabase);invariant(fileSha256(OPERATIONAL_DATABASE)===operationalHash,"PAY23I_OPERATIONAL_CHANGED_AFTER_CLEANUP");}
}
