import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, rmdirSync } from "node:fs";
import path from "node:path";
import { randomBytes, randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { assertSqliteCopyReady, assertSqliteSnapshotUnchanged, snapshotSqliteArtifacts } from "./sqlite-copy-safety";
import { seedReport23GFixtures, REPORT23G_CLASS, REPORT23G_YEAR } from "./qa23g-fixture-data";
import { buildAcademicReportSummary, getAcademicReportRun, parseAcademicReportInput, persistAcademicReportRun } from "../lib/academic-reporting";
import { loadAcademicReportSources } from "../lib/academic-reporting-sources";
import { generateFullBackup } from "../lib/backup";
import { parseAndValidateBackup } from "../lib/restore";
import { restoreValidatedBackup } from "../lib/restore-database";

const SUITE="REPORT23G",WORKSPACE=path.resolve("."),OPERATIONAL=path.join(WORKSPACE,"prisma","dev.db"),QA_PARENT=path.join(WORKSPACE,"tmp","report23g"),ROOT=path.join(QA_PARENT,`${SUITE}-${process.pid}-${randomUUID()}`),DATABASE=path.join(ROOT,"report23g.db"),RESTORE_DATABASE=path.join(ROOT,"report23g-restore.db"),secret=randomBytes(48).toString("base64url");
let stage="preflight";
function invariant(value:unknown,code:string):asserts value{if(!value)throw new Error(code);}
function databaseUrl(file:string){return `file:${file.replaceAll("\\","/")}`;}
function runPrisma(args:string[],file=DATABASE){const pnpm=path.join(process.env.APPDATA??"","npm","node_modules","pnpm","bin","pnpm.mjs");invariant(existsSync(pnpm),"REPORT23G_PNPM_RUNTIME_MISSING");const result=spawnSync(process.execPath,[pnpm,"exec","prisma",...args],{cwd:WORKSPACE,env:{...process.env,DATABASE_URL:databaseUrl(file),SESSION_SECRET:secret,AUTH_SECRET:secret},encoding:"utf8",maxBuffer:64*1024*1024,windowsHide:true});if(result.error||result.status!==0)throw new Error(`REPORT23G_PRISMA_FAILED:${args.join(" ")}:${result.error?.message??`${result.stdout}\n${result.stderr}`}`);return `${result.stdout}\n${result.stderr}`;}
function cleanup(){const resolved=path.resolve(ROOT);invariant(resolved.startsWith(`${path.resolve(QA_PARENT)}${path.sep}`),"REPORT23G_CLEANUP_SCOPE_REFUSED");if(existsSync(resolved))rmSync(resolved,{recursive:true,force:true});if(existsSync(QA_PARENT)&&readdirSync(QA_PARENT).length===0)rmdirSync(QA_PARENT);}
function actor(entry:any){return{id:entry.user.id,name:entry.user.name,username:entry.user.username,email:null,designation:entry.user.designation,role:entry.user.role,roleAssignmentId:entry.assignment.id,authorizationVersion:entry.user.authorizationVersion,mustChangePassword:false,guardianId:entry.user.guardianId};}
function denied(work:()=>Promise<unknown>){return work().then(()=>false,()=>true);}

async function main(){
  cleanup();mkdirSync(ROOT,{recursive:true});assertSqliteCopyReady(OPERATIONAL,"REPORT23G_OPERATIONAL");const before=snapshotSqliteArtifacts(OPERATIONAL);copyFileSync(OPERATIONAL,DATABASE);copyFileSync(OPERATIONAL,RESTORE_DATABASE);Object.assign(process.env,{DATABASE_URL:databaseUrl(DATABASE),SESSION_SECRET:secret,AUTH_SECRET:secret,NODE_ENV:"test"});
  stage="migration";runPrisma(["migrate","deploy","--schema","prisma/schema.prisma"]);runPrisma(["migrate","deploy","--schema","prisma/schema.prisma"]);invariant(/up to date/i.test(runPrisma(["migrate","status","--schema","prisma/schema.prisma"])),"REPORT23G_MIGRATION_DIRTY");runPrisma(["migrate","deploy","--schema","prisma/schema.prisma"],RESTORE_DATABASE);
  const client=new PrismaClient({datasourceUrl:databaseUrl(DATABASE)});
  try{
    stage="fixtures";const fixture=await seedReport23GFixtures(client,{suite:SUITE});const principal=actor(fixture.users.principal),teacher=actor(fixture.users.teacher),parent=actor(fixture.users.parent),student=actor(fixture.users.student),viewer=actor(fixture.users.viewer),accountant=actor(fixture.users.accountant);
    const [parentSession,studentSession]=await Promise.all([client.authSession.create({data:{userId:parent.id,tokenHash:randomBytes(32).toString("hex"),credentialVersion:fixture.users.parent.user.credentialVersion,authorizationVersion:fixture.users.parent.user.authorizationVersion,activeRoleAssignmentId:fixture.users.parent.assignment.id,expiresAt:new Date(Date.now()+86_400_000),deviceSummary:"REPORT23G copied database",browserSummary:"QA",networkEvidenceMasked:"local"}}),client.authSession.create({data:{userId:student.id,tokenHash:randomBytes(32).toString("hex"),credentialVersion:fixture.users.student.user.credentialVersion,authorizationVersion:fixture.users.student.user.authorizationVersion,activeRoleAssignmentId:fixture.users.student.assignment.id,expiresAt:new Date(Date.now()+86_400_000),deviceSummary:"REPORT23G copied database",browserSummary:"QA",networkEvidenceMasked:"local"}})]);
    stage="source integrity";const normalizedInput=parseAcademicReportInput({family:"BOARD_CLASS_COMPARATIVE",academicYear:REPORT23G_YEAR,examinationCodes:fixture.examCodes.slice(0,2),className:REPORT23G_CLASS,normalizationRule:"PERCENTAGE_NORMALIZED"});const normalized=await loadAcademicReportSources(client,normalizedInput,principal,"REPORT23G-LEADERSHIP");invariant(normalized.sources.length===16,"REPORT23G_LOCKED_ISSUED_SOURCE_COUNT_WRONG");const summary=buildAcademicReportSummary(normalized.sources,normalizedInput,{audience:normalized.audience,expectedCompletion:normalized.expectedCompletion,generatedAt:new Date("2026-08-03T12:00:00.000Z")});invariant(summary.compatibility.every(row=>row.compatible&&row.appliedRule==="PERCENTAGE_NORMALIZED"),"REPORT23G_NORMALIZED_COMPATIBILITY_FAILED");invariant(summary.boardClassDisclaimer&&!/eligib|certif|predict/i.test(summary.title),"REPORT23G_BOARD_BOUNDARY_MISSING");
    const incompatibleInput=parseAcademicReportInput({family:"COMPARATIVE_DELTA",academicYear:REPORT23G_YEAR,examinationCodes:[fixture.examCodes[0],fixture.examCodes[2]],className:REPORT23G_CLASS,normalizationRule:"PERCENTAGE_NORMALIZED"});const incompatibleLoaded=await loadAcademicReportSources(client,incompatibleInput,principal,"REPORT23G-LEADERSHIP");const incompatible=buildAcademicReportSummary(incompatibleLoaded.sources,incompatibleInput,{audience:"LEADERSHIP",expectedCompletion:incompatibleLoaded.expectedCompletion});invariant(incompatible.compatibility.every(row=>!row.compatible)&&incompatible.warnings.some(row=>/not compared/i.test(row)),"REPORT23G_INCOMPATIBLE_SCHEME_SILENTLY_COMPARED");
    stage="authorization privacy";const teacherInput=parseAcademicReportInput({family:"SUBJECT_PAPER_DISTRIBUTION",academicYear:REPORT23G_YEAR,examinationCodes:[fixture.examCodes[0]],className:REPORT23G_CLASS,section:fixture.sections[0],subjectCode:"MAT"});const teacherLoaded=await loadAcademicReportSources(client,teacherInput,teacher,"REPORT23G-TEACHER");invariant(teacherLoaded.sources.length===6&&teacherLoaded.sources.every(row=>row.section===fixture.sections[0]&&row.papers.length===1),"REPORT23G_TEACHER_EXACT_SCOPE_FAILED");const crossSection=parseAcademicReportInput({family:"SUBJECT_PAPER_DISTRIBUTION",academicYear:REPORT23G_YEAR,examinationCodes:[fixture.examCodes[0]],className:REPORT23G_CLASS,section:fixture.sections[1],subjectCode:"MAT"});invariant((await loadAcademicReportSources(client,crossSection,teacher,"REPORT23G-TEACHER")).sources.length===0,"REPORT23G_TEACHER_CROSS_SECTION_ALLOWED");
    const learnerInput=parseAcademicReportInput({family:"STUDENT_LONGITUDINAL",academicYear:REPORT23G_YEAR,examinationCodes:fixture.examCodes.slice(0,2),className:REPORT23G_CLASS,section:fixture.sections[0],normalizationRule:"PERCENTAGE_NORMALIZED"});const [parentLoaded,studentLoaded]=await Promise.all([loadAcademicReportSources(client,learnerInput,parent,parentSession.id),loadAcademicReportSources(client,learnerInput,student,studentSession.id)]);invariant(parentLoaded.sources.length===2&&studentLoaded.sources.length===2&&new Set([...parentLoaded.sources,...studentLoaded.sources].map(row=>row.studentId)).size===1,"REPORT23G_LEARNER_SCOPE_FAILED");invariant(await denied(()=>loadAcademicReportSources(client,teacherInput,accountant,"REPORT23G-DENIED")),"REPORT23G_ACCOUNTANT_ALLOWED");
    const viewerInput=parseAcademicReportInput({family:"CLASS_SECTION_SUMMARY",academicYear:REPORT23G_YEAR,examinationCodes:[fixture.examCodes[0]],className:REPORT23G_CLASS,section:fixture.sections[1]});const viewerLoaded=await loadAcademicReportSources(client,viewerInput,viewer,"REPORT23G-VIEWER");const viewerSummary=buildAcademicReportSummary(viewerLoaded.sources,viewerInput,{audience:"VIEWER",expectedCompletion:viewerLoaded.expectedCompletion});invariant(viewerSummary.suppressed&&viewerSummary.sections.every(section=>section.rows.every(row=>!Object.keys(row).some(key=>/student|admission/i.test(key)))),"REPORT23G_VIEWER_REIDENTIFICATION_RISK");
    stage="versioned runs";const first=await persistAcademicReportRun(client,normalizedInput,summary,normalized.sources,principal,normalized.accessScope,new Date("2026-08-03T12:00:00.000Z"));const concurrent=await Promise.all([persistAcademicReportRun(client,normalizedInput,summary,normalized.sources,principal,normalized.accessScope,new Date("2026-08-03T12:01:00.000Z")),persistAcademicReportRun(client,normalizedInput,summary,normalized.sources,principal,normalized.accessScope,new Date("2026-08-03T12:02:00.000Z"))]);invariant(concurrent.every(row=>row.runReference===first.runReference&&row.idempotent),"REPORT23G_IDEMPOTENT_CONCURRENT_RUN_FAILED");invariant(await client.academicReportRun.update({where:{publicKey:first.runReference},data:{immutableSummaryJson:"{}"}}).then(()=>false,()=>true),"REPORT23G_IMMUTABLE_RUN_UPDATED");const beforeRollback=await client.academicReportRun.count();await client.$transaction(async tx=>{await tx.academicReportAuditEvent.create({data:{eventKey:randomUUID(),reportRunId:first.id,eventType:"EXPORT_AUTHORIZED",actorUserId:principal.id,actorRole:"PRINCIPAL",safeDetailsJson:"{}"}});throw new Error("REPORT23G_FORCED");}).then(()=>{throw new Error("REPORT23G_FORCED_FAILURE_DID_NOT_FAIL");},()=>undefined);invariant(await client.academicReportRun.count()===beforeRollback&&await client.academicReportAuditEvent.count({where:{eventKey:{contains:"-"}}})===0,"REPORT23G_FORCED_FAILURE_PARTIAL_WRITE");
    stage="backup restore";const backup=parseAndValidateBackup(await generateFullBackup(client,{generatedBy:"REPORT23G copied-database QA"}));invariant(backup.academicReportDefinitions.length===1&&backup.academicReportRuns.length===1&&backup.academicReportSourceReferences.length===16&&backup.academicReportAuditEvents.length===1,"REPORT23G_BACKUP_INCOMPLETE");invariant(!/createdByUserId|actorUserId/.test(JSON.stringify({definitions:backup.academicReportDefinitions,runs:backup.academicReportRuns,audits:backup.academicReportAuditEvents})),"REPORT23G_BACKUP_ACTOR_ID_LEAK");const restoreClient=new PrismaClient({datasourceUrl:databaseUrl(RESTORE_DATABASE)});try{const restoreActor=await restoreClient.user.findFirst({where:{role:"SUPER_ADMIN",isActive:true}});invariant(restoreActor,"REPORT23G_RESTORE_ACTOR_MISSING");const[firstRestore,secondRestore]=[await restoreValidatedBackup(restoreClient,backup,restoreActor),await restoreValidatedBackup(restoreClient,backup,restoreActor)];const errors=[firstRestore,secondRestore].flatMap(item=>Object.entries(item).flatMap(([key,value]:any)=>value?.errors?.length?[`${key}:${value.errors.join("|")}`]:[]));invariant(!errors.length,`REPORT23G_RESTORE_ERRORS:${errors.join(";")}`);invariant(await restoreClient.academicReportRun.count()===1&&await restoreClient.academicReportSourceReference.count()===16&&await restoreClient.academicReportAuditEvent.count()===1,"REPORT23G_DOUBLE_RESTORE_MISMATCH");}finally{await restoreClient.$disconnect();}
    const stored=await getAcademicReportRun(client,first.runReference,principal);invariant(stored.summaryHash===first.summaryHash&&!stored.stale,"REPORT23G_STORED_RUN_CHANGED");assertSqliteCopyReady(OPERATIONAL,"REPORT23G_OPERATIONAL");assertSqliteSnapshotUnchanged(before,snapshotSqliteArtifacts(OPERATIONAL),"REPORT23G_OPERATIONAL_DATABASE_CHANGED");console.log(JSON.stringify({result:"REPORT23G_COPIED_DATABASE_PASSED",migrateDeployRuns:2,lockedIssuedSources:normalized.sources.length,rawAndWeighted:true,compatibleAndIncompatible:true,statuses:["PRESENT","ABSENT","EXEMPT","NOT_APPLICABLE","NOT_ENTERED"],grouped:true,ties:true,classes:["IX"],sections:fixture.sections,preboardRevision:true,teacherExactScope:true,learnerScope:true,viewerSuppressed:true,deniedRoles:true,deterministicConcurrent:true,immutable:true,forcedRollback:true,backupRestoreRuns:2,operationalMutation:false}));
  }finally{await client.$disconnect();cleanup();cleanup();assertSqliteCopyReady(OPERATIONAL,"REPORT23G_OPERATIONAL_POST_CLEANUP");assertSqliteSnapshotUnchanged(before,snapshotSqliteArtifacts(OPERATIONAL),"REPORT23G_OPERATIONAL_CHANGED_AFTER_CLEANUP");}
}
main().catch(error=>{console.error(`REPORT23G_FAILED stage=${stage}: ${error instanceof Error?error.message:String(error)}`);process.exitCode=1;});
