import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { fileSha256 } from "./migration-check-utils";
import { seedReport23GFixtures } from "./qa23g-fixture-data";

const INDEPENDENT=process.argv.includes("--independent"),SUITE=INDEPENDENT?"REPORT23GQA-BROWSER":"REPORT23G-BROWSER",ROOT_NAME=INDEPENDENT?"report23gqa-browser":"report23g-browser";
const WORKSPACE=path.resolve("."),OPERATIONAL=path.join(WORKSPACE,"prisma","dev.db"),ROOT=path.join(WORKSPACE,"tmp",ROOT_NAME),DATABASE=path.join(ROOT,`${ROOT_NAME}.db`),CREDENTIALS=path.join(ROOT,"credentials.json"),RUNTIME_ENV=path.join(ROOT,"runtime-env.json"),PORT=INDEPENDENT?3224:3223;
function databaseUrl(file:string){return `file:${file.replaceAll("\\","/")}`;}
function assertRoot(){const resolved=path.resolve(ROOT);if(resolved!==path.join(path.resolve(WORKSPACE),"tmp",ROOT_NAME))throw new Error("REPORT23G_BROWSER_CLEANUP_SCOPE_REFUSED");return resolved;}
function migrate(environment:NodeJS.ProcessEnv){const pnpm=path.join(process.env.APPDATA??"","npm","node_modules","pnpm","bin","pnpm.mjs");if(!existsSync(pnpm))throw new Error("REPORT23G_BROWSER_PNPM_RUNTIME_MISSING");const result=spawnSync(process.execPath,[pnpm,"exec","prisma","migrate","deploy","--schema","prisma/schema.prisma"],{cwd:WORKSPACE,env:environment,encoding:"utf8",maxBuffer:64*1024*1024,windowsHide:true});if(result.error||result.status!==0)throw new Error(`REPORT23G_BROWSER_MIGRATION_FAILED:${result.error?.message??`${result.stdout}\n${result.stderr}`}`);}
async function setup(){const operationalBefore={sha256:fileSha256(OPERATIONAL),size:statSync(OPERATIONAL).size},root=assertRoot();if(existsSync(root))rmSync(root,{recursive:true,force:true});mkdirSync(root,{recursive:true});copyFileSync(OPERATIONAL,DATABASE);const secret=randomBytes(48).toString("base64url"),password=`${randomBytes(18).toString("base64url")}Aa1!`,origin=`http://localhost:${PORT}`,environment:NodeJS.ProcessEnv={...process.env,NODE_ENV:"production",DATABASE_URL:databaseUrl(DATABASE),SESSION_SECRET:secret,AUTH_SECRET:secret,APP_ORIGIN:origin,PORT:String(PORT)};migrate(environment);Object.assign(process.env,environment);const client=new PrismaClient({datasourceUrl:databaseUrl(DATABASE)});try{const fixture=await seedReport23GFixtures(client,{suite:SUITE,browserPassword:password});const rows:any={};for(const role of ["principal","teacher","parent","viewer","student"] as const)rows[role]={username:fixture.users[role].user.username,password,path:role==="principal"||role==="viewer"?"/academic-reports":role==="teacher"?"/teacher/academic-reports":role==="parent"?"/parent/results/trends":"/student/results"};writeFileSync(CREDENTIALS,JSON.stringify(rows));writeFileSync(RUNTIME_ENV,JSON.stringify({DATABASE_URL:databaseUrl(DATABASE),SESSION_SECRET:secret,AUTH_SECRET:secret,APP_ORIGIN:origin,NODE_ENV:"production",PORT:String(PORT)}));const operationalAfter={sha256:fileSha256(OPERATIONAL),size:statSync(OPERATIONAL).size};if(JSON.stringify(operationalBefore)!==JSON.stringify(operationalAfter))throw new Error("REPORT23G_BROWSER_OPERATIONAL_DATABASE_CHANGED");console.log(JSON.stringify({result:INDEPENDENT?"REPORT23GQA_BROWSER_FIXTURES_READY":"REPORT23G_BROWSER_FIXTURES_READY",copiedDatabase:true,port:PORT,roles:Object.keys(rows),students:fixture.students.length,examinations:fixture.examCodes.length,sections:fixture.sections.length}));}finally{await client.$disconnect();}}
function cleanup(){const root=assertRoot();if(existsSync(root))rmSync(root,{recursive:true,force:true});console.log(JSON.stringify({result:"REPORT23G_BROWSER_FIXTURES_REMOVED",exists:existsSync(root)}));}
const mode=process.argv.find(value=>value==="setup"||value==="cleanup");if(mode==="setup")setup().catch(error=>{console.error(error instanceof Error?error.message:error);process.exitCode=1;});else if(mode==="cleanup")cleanup();else{console.error("Use setup or cleanup");process.exitCode=1;}
