import { NextRequest, NextResponse } from "next/server";
import { requireApiPermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { loadMarkEntry, saveMarkDraft } from "@/lib/marks";
import { loadScopedAssessment, marksError } from "@/lib/marks-api";
import { publicAssessment } from "@/lib/exams";
import { assertNoDelegatedFamilyConflict, marksAuthorityAuditContext, resolveMarksWriteAuthority } from "@/lib/academic-integrity";

export async function GET(_: NextRequest, { params }: { params: Promise<{ assessmentId: string }> }) { const auth = await requireApiPermission("ENTER_MARKS"); if (auth.response || !auth.user) return auth.response; try { const id = (await params).assessmentId; await loadScopedAssessment(auth.user, id, "WRITE"); const loaded = await loadMarkEntry(prisma, id); return NextResponse.json({ assessment: publicAssessment(loaded.assessment), exam: { examCode: loaded.assessment.examCycle.examCode, name: loaded.assessment.examCycle.name, status: loaded.assessment.examCycle.status }, students: loaded.students, events: loaded.assessment.events.map((event) => ({ eventType: event.eventType, previousMarks: event.previousMarks?.toString() ?? null, newMarks: event.newMarks?.toString() ?? null, previousEntryStatus: event.previousEntryStatus, newEntryStatus: event.newEntryStatus, reason: event.reason, notes: event.notes, actorLabel: event.actorLabel ?? "Staff", eventDate: event.eventDate })), unrelatedStoredMarks: loaded.unrelatedStoredMarks }); } catch (error) { const r = marksError(error); return NextResponse.json({ error: r.message }, { status: r.status }); } }
export async function PUT(request: NextRequest, { params }: { params: Promise<{ assessmentId: string }> }) { const auth = await requireApiPermission("ENTER_MARKS"); if (auth.response || !auth.user) return auth.response; try { const id = (await params).assessmentId; const assessment = await loadScopedAssessment(auth.user, id, "WRITE"); const body = await request.json(); const authority = await resolveMarksWriteAuthority(prisma, auth.user, { kind: "LEGACY_ASSESSMENT", assessmentId: assessment.id, examId: assessment.examCycleId, academicYear: assessment.academicYear, className: assessment.className, section: assessment.section, subjectId: assessment.timetableSubjectId, subjectName: assessment.subjectName, componentName: assessment.componentName }, "ENTER_MARKS"); const requestedAdmissions = new Set<string>((Array.isArray(body.rows) ? body.rows : []).map((row: any) => String(row?.admissionNumber ?? ""))); const linkedRows = await prisma.academicYearEnrollment.findMany({ where: { academicYear: assessment.academicYear, className: assessment.className, ...(assessment.section ? { section: assessment.section } : {}), student: { admissionNo: { in: [...requestedAdmissions] } } }, select: { studentId: true } }); await assertNoDelegatedFamilyConflict(prisma, auth.user, linkedRows.map((row) => row.studentId), authority, `legacy:${assessment.id}`); return NextResponse.json(await saveMarkDraft(prisma, id, body.rows, body.expectedUpdatedAt, { id: auth.user.id, name: auth.user.name, auditContext: marksAuthorityAuditContext(authority) })); } catch (error) { const r = marksError(error); return NextResponse.json({ error: r.message }, { status: r.status }); } }
