import { NextRequest, NextResponse } from "next/server";
import { requireApiPermission } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { loadMarkEntry, saveMarkDraft } from "@/lib/marks";
import { loadScopedAssessment, marksError } from "@/lib/marks-api";
import { publicAssessment } from "@/lib/exams";

export async function GET(_: NextRequest, { params }: { params: Promise<{ assessmentId: string }> }) { const auth = await requireApiPermission("VIEW_EXAMS"); if (auth.response) return auth.response; try { const id = (await params).assessmentId; await loadScopedAssessment(auth.user, id); const loaded = await loadMarkEntry(prisma, id); return NextResponse.json({ assessment: publicAssessment(loaded.assessment), exam: { examCode: loaded.assessment.examCycle.examCode, name: loaded.assessment.examCycle.name, status: loaded.assessment.examCycle.status }, students: loaded.students, events: loaded.assessment.events.map((event) => ({ eventType: event.eventType, previousMarks: event.previousMarks?.toString() ?? null, newMarks: event.newMarks?.toString() ?? null, previousEntryStatus: event.previousEntryStatus, newEntryStatus: event.newEntryStatus, reason: event.reason, notes: event.notes, actorLabel: event.actorLabel ?? "Staff", eventDate: event.eventDate })), unrelatedStoredMarks: loaded.unrelatedStoredMarks }); } catch (error) { const r = marksError(error); return NextResponse.json({ error: r.message }, { status: r.status }); } }
export async function PUT(request: NextRequest, { params }: { params: Promise<{ assessmentId: string }> }) { const auth = await requireApiPermission("ENTER_MARKS"); if (auth.response) return auth.response; try { const id = (await params).assessmentId; await loadScopedAssessment(auth.user, id); const body = await request.json(); return NextResponse.json(await saveMarkDraft(prisma, id, body.rows, body.expectedUpdatedAt, { id: auth.user.id, name: auth.user.name })); } catch (error) { const r = marksError(error); return NextResponse.json({ error: r.message }, { status: r.status }); } }
