import { notFound } from "next/navigation";
import { BudgetActions } from "@/components/budget-actions";
import { BudgetForm, BudgetRevisionForm } from "@/components/budget-form";
import { PageHeader, PageShell, StatusBadge } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { budgetDetailInclude, getBudgetMetrics, serializeBudget } from "@/lib/budgets";
import { displayDate, moneyExact } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { hasRolePermission } from "@/lib/role-permissions";

export default async function BudgetDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requirePermission("VIEW_BUDGETS"); const { id } = await params; const [plan, categories, departments, manage, approve, lock, revise] = await Promise.all([prisma.budgetPlan.findUnique({ where: { id }, include: budgetDetailInclude }), prisma.expenseCategory.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true, code: true }, orderBy: { name: "asc" } }), prisma.expenseDepartment.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true, code: true }, orderBy: { name: "asc" } }), hasRolePermission(prisma, user.role, "MANAGE_BUDGETS"), hasRolePermission(prisma, user.role, "APPROVE_BUDGETS"), hasRolePermission(prisma, user.role, "LOCK_BUDGETS"), hasRolePermission(prisma, user.role, "REVISE_BUDGETS")]); if (!plan) notFound(); const budget = serializeBudget(plan, await getBudgetMetrics(prisma, plan)) as any;
  return <PageShell><PageHeader title={plan.budgetNumber} description={plan.title} action={<StatusBadge status={plan.status} />} />
    <div className="stats"><div className="card stat"><span>Allocated</span><strong>{moneyExact(Number(budget.summary.allocated))}</strong></div><div className="card stat"><span>Paid actual</span><strong>{moneyExact(Number(budget.summary.paid))}</strong></div><div className="card stat"><span>Committed</span><strong>{moneyExact(Number(budget.summary.committed))}</strong></div><div className="card stat"><span>Available</span><strong>{moneyExact(Number(budget.summary.available))}</strong></div><div className="card stat"><span>Utilization</span><strong>{budget.summary.utilizationPercent == null ? "—" : `${budget.summary.utilizationPercent.toFixed(1)}%`}</strong></div><div className="card stat"><span>Over budget</span><strong>{moneyExact(Number(budget.summary.overBudget))}</strong></div></div>
    <section className="card card-pad detail-grid"><div><span className="muted-text">Academic year</span><strong>{plan.academicYear}</strong></div><div><span className="muted-text">Plan thresholds</span><strong>{plan.warningThresholdPercent}% / {plan.criticalThresholdPercent}%</strong></div><div><span className="muted-text">Effective dates</span><strong>{plan.effectiveFrom ? displayDate(plan.effectiveFrom) : "Not set"} – {plan.effectiveTo ? displayDate(plan.effectiveTo) : "Not set"}</strong></div><div><span className="muted-text">Approved by</span><strong>{budget.approvedBy ?? "Not approved"}</strong></div><div><span className="muted-text">Locked by</span><strong>{budget.lockedBy ?? "Not locked"}</strong></div><div><span className="muted-text">Description</span><strong>{plan.description ?? "—"}</strong></div></section>
    {plan.status === "DRAFT" && manage ? <BudgetForm budget={budget} categories={categories} departments={departments} /> : <AllocationTable allocations={budget.allocations} />}
    {budget.summary.unallocatedUtilized !== "0" ? <div className="notice warning">Approved expenses not matched to any allocation: {moneyExact(Number(budget.summary.unallocatedUtilized))}. These are included in plan totals and are never counted twice.</div> : null}
    <BudgetActions budget={budget} permissions={{ manage, approve, lock, revise }} />
    {["APPROVED", "LOCKED"].includes(plan.status) && revise && !(budget.revisions ?? []).some((row: any) => ["DRAFT", "PENDING_APPROVAL"].includes(row.status)) ? <BudgetRevisionForm budget={budget} categories={categories} departments={departments} /> : null}
    <section className="card card-pad"><h3>Revision History</h3>{budget.revisions.length ? <div className="table-wrap"><table><thead><tr><th>Revision</th><th>Status</th><th>Reason</th><th>Previous</th><th>Revised</th><th>Created by</th></tr></thead><tbody>{budget.revisions.map((row: any) => <tr key={row.id}><td>{row.revisionNumber}</td><td><StatusBadge status={row.status} /></td><td>{row.reason}{row.rejectionReason ? <><br /><span className="danger-text">Rejected: {row.rejectionReason}</span></> : null}</td><td>{moneyExact(Number(row.previousTotalAmount))}</td><td>{moneyExact(Number(row.revisedTotalAmount))}</td><td>{row.createdBy ?? "System"}</td></tr>)}</tbody></table></div> : <p className="muted-text">No revisions. Approved figures have not been changed.</p>}</section>
  </PageShell>;
}

function AllocationTable({ allocations }: { allocations: any[] }) { return <section className="card card-pad"><h3>Allocations versus Spending</h3><div className="table-wrap"><table><thead><tr><th>Category</th><th>Department</th><th>Allocated</th><th>Committed</th><th>Paid</th><th>Available</th><th>Utilization</th><th>Threshold</th></tr></thead><tbody>{allocations.map((row) => <tr key={row.id}><td>{row.category?.name ?? "All categories"}</td><td>{row.department?.name ?? "All departments"}</td><td>{moneyExact(Number(row.allocatedAmount))}</td><td>{moneyExact(Number(row.committed))}</td><td>{moneyExact(Number(row.paid))}</td><td className={Number(row.available) < 0 ? "danger-text" : ""}>{moneyExact(Number(row.available))}</td><td>{row.utilizationPercent == null ? "—" : `${row.utilizationPercent.toFixed(1)}%`}</td><td><StatusBadge status={row.thresholdState} />{Number(row.available) < 0 ? <span className="badge danger">AVAILABLE BELOW ZERO</span> : null}</td></tr>)}</tbody></table></div></section>; }
