import Link from "next/link";
import { PageHeader, PageShell, SectionCard } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { buildExpenseReports, localDate } from "@/lib/expenses";
import { money } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { hasRolePermission } from "@/lib/role-permissions";

export default async function ExpenseReportsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const user = await requirePermission("VIEW_EXPENSE_REPORTS"); const params = await searchParams; const from = typeof params.from === "string" ? params.from : ""; const to = typeof params.to === "string" ? params.to : ""; const canExport = await hasRolePermission(prisma, user.role, "EXPORT_EXPENSE_REPORTS"); const rows = await prisma.expenseRecord.findMany({ where: from || to ? { expenseDate: { ...(from ? { gte: localDate(from) } : {}), ...(to ? { lt: new Date(localDate(to).getTime() + 86_400_000) } : {}) } } : {}, select: { expenseNumber: true, expenseDate: true, academicYear: true, vendor: { select: { name: true } }, category: { select: { name: true } }, department: { select: { name: true } }, description: true, grossAmount: true, taxAmount: true, deductionAmount: true, netAmount: true, approvalStatus: true, paymentStatus: true, paymentMethod: true }, orderBy: { expenseDate: "desc" } }); const reports = buildExpenseReports(rows); const blocks = [["Date-wise", reports.dateWise], ["Vendor-wise", reports.vendorWise], ["Category-wise", reports.categoryWise], ["Department-wise", reports.departmentWise], ["Payment status", reports.paymentStatus], ["Approval status", reports.approvalStatus]] as const; const query = new URLSearchParams({ ...(from ? { from } : {}), ...(to ? { to } : {}) }).toString(); return <PageShell><PageHeader title="Expense Reports" description="Read-only spend summaries. Cancelled amounts are excluded; budgets are not part of this phase." action={canExport ? <a className="button" href={`/api/expenses/reports/export${query ? `?${query}` : ""}`}>Export CSV</a> : undefined} /><form className="card filter-grid" method="get"><label>From<input name="from" type="date" defaultValue={from} /></label><label>To<input name="to" type="date" defaultValue={to} /></label><button type="submit">Apply Dates</button><Link className="button secondary" href="/expenses/reports">Clear</Link></form><div className="stats"><div className="card stat"><span>Active spend</span><strong>{money(Number(reports.total))}</strong></div><div className="card stat"><span>Active records</span><strong>{reports.count}</strong></div><div className="card stat"><span>Cancelled records excluded</span><strong>{reports.cancelledCount}</strong></div></div><div className="report-grid">{blocks.map(([title, data]) => <SectionCard title={title} key={title}>{data.length ? <div className="report-list">{data.map((item) => <div key={item.label}><span>{item.label.replaceAll("_", " ")}</span><strong>{money(Number(item.total))}</strong></div>)}</div> : <p className="muted-text">No records.</p>}</SectionCard>)}</div></PageShell>; }
