import Link from "next/link";
import { Prisma } from "@prisma/client";
import { PageHeader, PageShell, StatusBadge } from "@/components/ui";
import { requirePermission, hasUserPermission } from "@/lib/auth";
import { localDate } from "@/lib/expenses";
import { displayDate, moneyExact } from "@/lib/format";
import { prisma } from "@/lib/prisma";

export default async function MiscIncomePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const user = await requirePermission("VIEW_MISC_INCOME"); const params = await searchParams; const value = (key: string) => typeof params[key] === "string" ? params[key] as string : ""; const where: Prisma.MiscIncomeReceiptWhereInput = {}; if (value("method")) where.paymentMethod = value("method"); if (value("status")) where.status = value("status"); if (value("studentId")) where.studentId = value("studentId"); if (value("itemId")) where.lines = { some: { itemId: value("itemId") } }; if (value("from") || value("to")) where.receiptDate = { ...(value("from") ? { gte: localDate(value("from")) } : {}), ...(value("to") ? { lt: new Date(localDate(value("to")).getTime() + 86_400_000) } : {}) }; const [rows, items, students, manage] = await Promise.all([prisma.miscIncomeReceipt.findMany({ where, include: { student: { select: { studentName: true, admissionNo: true } }, lines: true }, orderBy: [{ receiptDate: "desc" }, { createdAt: "desc" }] }), prisma.miscIncomeItem.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } }), prisma.student.findMany({ where: { deletedAt: null }, select: { id: true, studentName: true, admissionNo: true }, orderBy: { studentName: "asc" } }), hasUserPermission(user, "MANAGE_MISC_INCOME")]); const sum = (predicate: (row: typeof rows[number]) => boolean) => rows.filter(predicate).reduce((total, row) => total.add(row.netAmount), new Prisma.Decimal(0)); const cards = [["Active income", sum((row) => row.status === "ACTIVE")], ["Cash", sum((row) => row.status === "ACTIVE" && row.paymentMethod === "CASH")], ["Non-cash", sum((row) => row.status === "ACTIVE" && row.paymentMethod !== "CASH")], ["Cancelled", sum((row) => row.status === "CANCELLED")]] as const;
  return <PageShell><PageHeader title="Miscellaneous Income" description="Non-fee school income. These receipts and numbers remain separate from student fee Payment records." action={<div className="page-actions"><Link className="button secondary" href="/misc-income/reports">Reports</Link>{manage ? <><Link className="button secondary" href="/misc-income/items">Items & rates</Link><Link className="button" href="/misc-income/new">Create receipt</Link></> : null}</div>} /><div className="stats">{cards.map(([label, amount]) => <div className="card stat" key={label}><span>{label}</span><strong>{moneyExact(Number(amount))}</strong></div>)}</div><form className="card filter-grid" method="get"><label>From<input type="date" name="from" defaultValue={value("from")} /></label><label>To<input type="date" name="to" defaultValue={value("to")} /></label><label>Item<select name="itemId" defaultValue={value("itemId")}><option value="">All</option>{items.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Student<select name="studentId" defaultValue={value("studentId")}><option value="">All</option>{students.map((student) => <option value={student.id} key={student.id}>{student.admissionNo} — {student.studentName}</option>)}</select></label><label>Method<select name="method" defaultValue={value("method")}><option value="">All</option>{["CASH", "UPI", "BANK_TRANSFER", "NEFT", "RTGS", "IMPS", "CHEQUE", "OTHER"].map((method) => <option key={method}>{method}</option>)}</select></label><label>Status<select name="status" defaultValue={value("status")}><option value="">All</option><option>ACTIVE</option><option>CANCELLED</option></select></label><button>Apply filters</button><Link className="button secondary" href="/misc-income">Clear</Link></form><section className="card"><div className="table-wrap"><table><thead><tr><th>Receipt</th><th>Date</th><th>Student / Payer</th><th>Items</th><th>Method</th><th>Net</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.receiptNumber}</strong></td><td>{displayDate(row.receiptDate)}</td><td>{row.student ? `${row.student.studentName} (${row.student.admissionNo})` : row.payerName ?? "Walk-in payer"}</td><td>{row.lines.map((line) => line.itemNameSnapshot).join(", ")}</td><td>{row.paymentMethod.replaceAll("_", " ")}</td><td>{moneyExact(Number(row.netAmount))}</td><td><StatusBadge status={row.status} /></td><td><Link href={`/misc-income/${row.id}`}>View</Link></td></tr>)}</tbody></table></div>{!rows.length ? <p className="empty-state">No miscellaneous-income receipts match the filters.</p> : null}</section></PageShell>;
}
