import { notFound } from "next/navigation";
import { ExpenseForm } from "@/components/expense-form";
import { PageHeader, PageShell, SectionCard, StatusBadge } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { expenseDetailInclude, serializeExpense } from "@/lib/expenses";
import { displayDate, moneyExact, schoolDateKey } from "@/lib/format";
import { prisma } from "@/lib/prisma";
import { hasRolePermission } from "@/lib/role-permissions";

export default async function ExpenseDetailPage({ params }: { params: Promise<{ id: string }> }) { const user = await requirePermission("VIEW_EXPENSES"); const { id } = await params; const [row, vendors, categories, departments, manage, approve, pay, cancel] = await Promise.all([prisma.expenseRecord.findUnique({ where: { id }, include: expenseDetailInclude }), prisma.vendor.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true, vendorCode: true }, orderBy: { name: "asc" } }), prisma.expenseCategory.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true, code: true }, orderBy: { name: "asc" } }), prisma.expenseDepartment.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true, code: true }, orderBy: { name: "asc" } }), hasRolePermission(prisma, user.role, "MANAGE_EXPENSES"), hasRolePermission(prisma, user.role, "APPROVE_EXPENSES"), hasRolePermission(prisma, user.role, "MARK_EXPENSE_PAID"), hasRolePermission(prisma, user.role, "CANCEL_EXPENSES")]); if (!row) notFound(); const sensitive = manage || approve || pay || cancel; const expense = sensitive ? serializeExpense(row) : null; return <PageShell><PageHeader title={row.expenseNumber} description="Expense detail and audit history" action={<div className="page-actions"><StatusBadge status={row.approvalStatus} /><StatusBadge status={row.paymentStatus} /></div>} />
    <SectionCard title="Expense Details"><dl className="detail-grid"><div><dt>Date</dt><dd>{displayDate(row.expenseDate)}</dd></div><div><dt>Academic Year</dt><dd>{row.academicYear}</dd></div><div><dt>Vendor</dt><dd>{row.vendor?.name ?? "No vendor"}</dd></div><div><dt>Category</dt><dd>{row.category.name}</dd></div><div><dt>Department</dt><dd>{row.department?.name ?? "No department"}</dd></div><div><dt>Invoice</dt><dd>{row.invoiceNumber || "—"}</dd></div><div><dt>Gross</dt><dd>{moneyExact(Number(row.grossAmount))}</dd></div><div><dt>Tax</dt><dd>{moneyExact(Number(row.taxAmount))}</dd></div><div><dt>Deduction</dt><dd>{moneyExact(Number(row.deductionAmount))}</dd></div><div><dt>Net</dt><dd><strong>{moneyExact(Number(row.netAmount))}</strong></dd></div><div className="wide"><dt>Description</dt><dd>{row.description}</dd></div>{sensitive && row.rejectionReason ? <div className="wide"><dt>Rejection reason</dt><dd>{row.rejectionReason}</dd></div> : null}{sensitive && row.cancellationReason ? <div className="wide"><dt>Cancellation reason</dt><dd>{row.cancellationReason}</dd></div> : null}</dl></SectionCard>
    {sensitive && expense ? <ExpenseForm expense={expense} masters={{ vendors, categories, departments }} permissions={{ manage, approve, pay, cancel }} /> : null}
    <SectionCard title="Payment History" description="Each payment is preserved separately.">{row.payments.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Recorded by</th></tr></thead><tbody>{row.payments.map((payment) => <tr key={payment.id}><td>{displayDate(payment.paymentDate)}</td><td>{moneyExact(Number(payment.amount))}</td><td>{payment.paymentMethod}</td><td>{sensitive ? payment.transactionReference || payment.chequeNumber || "—" : "Restricted"}</td><td>{sensitive ? payment.recordedBy?.name ?? "Former user" : "Restricted"}</td></tr>)}</tbody></table></div> : <p className="muted-text">No payments recorded.</p>}</SectionCard>
    <SectionCard title="Audit History" description="Workflow actions are append-only; actor names are limited to finance operators."><div className="audit-timeline">{row.audits.map((audit) => <div key={audit.id}><strong>{audit.action.replaceAll("_", " ")}</strong><span>{audit.fromStatus ? `${audit.fromStatus} → ` : ""}{audit.toStatus ?? ""}</span><small>{sensitive ? `${audit.actorName} · ` : ""}{displayDate(schoolDateKey(audit.createdAt))}</small></div>)}</div></SectionCard>
  </PageShell>; }
