import {createHash} from "node:crypto";
import {gzipSync} from "node:zlib";
import {mkdirSync,readFileSync,writeFileSync,readdirSync} from "node:fs";
import path from "node:path";
import {execFileSync} from "node:child_process";
import {fixture,tarBytes} from "./product-contract-fixture";
import {hashBytes} from "../../scripts/portable/artifact-handoff";
import {materialAcquisitionRecipe} from "../../scripts/portable/product-materials";
import {verifyAcquisitionPlan} from "../../scripts/portable/material-acquisition";
import {packageMaterials} from "../../scripts/portable/material-package";
import {captureProductProcess} from "../../scripts/portable/producer-process";
import type {Preparation} from "../../scripts/portable/material-source";

/** Entire invented distribution/OCI/scanner fixture is HARNESS_ONLY. The real
 * collector, serialization, signed-input verifier and offline caller consume it.
 * gpgv's process is a labelled stand-in, not vendor signature qualification. */
export function materialFixture(){
 const raw=new Map<string,Buffer>(),put=(v:any)=>{const b=Buffer.isBuffer(v)?v:Buffer.from(typeof v==="string"?v:JSON.stringify(v));const h=hashBytes(b);raw.set(h,b);return h;};
 const elf=(tag:number)=>{const b=Buffer.alloc(64);b.set([127,69,76,70,2,1]);b.writeUInt16LE(62,18);b[40]=tag;return b;};
 const revision="a".repeat(40),packages=[{name:"@esbuild/linux-x64",version:"1.0.0",role:"esbuild"},{name:"@img/sharp-linux-x64",version:"1.0.0",role:"sharp"},{name:"@img/sharp-libvips-linux-x64",version:"1.0.0",role:"libvips"},{name:"@prisma/engines-version",version:"7.1.1-3."+revision,role:null}];
 const tarballs:any[]=[],metadata:any[]=[],origins:any[]=[],downloads:any[]=[];let lock="lockfileVersion: '9.0'\n\npackages:\n";
 for(const [i,p] of packages.entries()){const bytes=p.role?elf(i+1):Buffer.from('TEST ONLY metadata package'),member="package/"+(p.role??"version")+".node",archive=tarBytes({[member]:bytes}),url=`https://registry.npmjs.org/${p.name}/-/${p.name.split('/')[1]}-${p.version}.tgz`,sha256=put(archive),integrity="sha512-"+createHash("sha512").update(archive).digest("base64"),entry={url,sha256,bytes:archive.length};tarballs.push({...entry,integrity});downloads.push(entry);lock+=`\n  '${p.name}@${p.version}':\n    resolution: {integrity: ${integrity}}\n`;const meta=put({name:p.name,versions:{[p.version]:{name:p.name,version:p.version,dist:{tarball:url,integrity}}},time:{[p.version]:new Date().toISOString()}}),m={url:"https://registry.npmjs.org/"+p.name,sha256:meta,bytes:raw.get(meta)!.length};metadata.push(m);downloads.push(m);if(p.role)origins.push({path:"app/node_modules/"+p.role+".node",role:p.role,sha256:put(bytes),archiveSha256:sha256,url,member,format:"tar"});}
 lock+="\nsnapshots:\n";
 for(const [i,role] of ["query","schema"].entries()){const native=elf(i+10),bytes=gzipSync(native),url=`https://binaries.prisma.sh/all_commits/${revision}/debian-openssl-3.0.x/${role==="query"?"libquery_engine.so.node":"schema-engine"}.gz`,sha256=put(bytes);downloads.push({url,sha256,bytes:bytes.length});origins.push({path:"opt/nalanda-engines/"+(role==="query"?"query-engine.node":"schema-engine"),role,sha256:put(native),archiveSha256:sha256,url,member:"",format:"gzip"});}
 const now=Date.now(),snapshot=new Date(now-60000).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,""),baseStatus=Buffer.from("Package: base\nStatus: install ok installed\nVersion: 1\nArchitecture: amd64\n\n"),installed=Buffer.from(baseStatus+['openssl','ca-certificates'].map(name=>`Package: ${name}\nStatus: install ok installed\nVersion: 1\nArchitecture: amd64\n\n`).join(''));
 const debs=['openssl','ca-certificates'].map(name=>{const bytes=Buffer.from('TEST ONLY deb '+name),sha256=put(bytes),filename=`pool/${name}_1_amd64.deb`;downloads.push({url:`https://snapshot.debian.org/archive/debian/${snapshot}/${filename}`,sha256,bytes:bytes.length});return {name,version:'1',release:0,sha256,filename};});
 const index=gzipSync(Buffer.from(debs.map(d=>`Package: ${d.name}\nVersion: 1\nArchitecture: amd64\nSHA256: ${d.sha256}\nSize: ${raw.get(d.sha256)!.length}\nFilename: ${d.filename}\n\n`).join(''))),indexId=put(index),indexPath='main/binary-amd64/Packages.gz';
 const release=Buffer.from(`Codename: bookworm\nArchitectures: amd64\nDate: ${new Date(now-120000).toUTCString()}\nValid-Until: ${new Date(now+3600000).toUTCString()}\nSHA256:\n ${indexId} ${index.length} ${indexPath}\n`),releaseId=put(release),keyring=put('TEST ONLY gpgv public-key stand-in');
 for(const [suffix,id] of [['InRelease',releaseId],[indexPath,indexId]])downloads.push({url:`https://snapshot.debian.org/archive/debian/${snapshot}/dists/bookworm/${suffix}`,sha256:id,bytes:raw.get(id)!.length});
 for(const o of origins){o.checksum=null;if(o.format==='gzip'){o.checksum=put(o.archiveSha256+'  HARNESS_ONLY.gz\n');downloads.push({url:o.url+'.sha256',sha256:o.checksum,bytes:raw.get(o.checksum)!.length});}}
 const inventory=put({snapshot,packages:debs,aptReleaseFiles:[{inRelease:releaseId,packages:indexId,keyring,path:indexPath}]}),baseInstalledStatus=put(baseStatus);
 const sourceFiles:any={'pnpm-lock.yaml':lock};for(const name of ['material-provenance.py','material-collector.py','material-replay.mjs'])sourceFiles['scripts/portable/'+name]=readFileSync('scripts/portable/'+name);
 const f=fixture({acquisition:true,sourceFiles,builderFiles:{'var/lib/dpkg/status':baseStatus}});for(const [h,b] of raw)f.blobs.set(h,b);
 const prep:Preparation={contract:'NALANDA_OFFLINE_MATERIAL_SOURCE_V1',source:f.d.source,tree:f.d.tree,architecture:'amd64',lockSha256:f.put(lock),snapshot,baseInstalledStatus,inventory,tarballs,metadata,origins,downloads};
 const manager=f.put('TEST ONLY inert pnpm'),plan:any={contract:'NALANDA_MATERIAL_ACQUISITION_V1',source:f.d.source,tree:f.d.tree,architecture:'amd64',recipeSha256:f.d.recipe.sha256,lockSha256:prep.lockSha256,effectiveRecipeSha256:'',snapshot,packages:debs.map(({name,version})=>({name,version})),environmentApproval:'https://example.invalid/TEST-ONLY',pnpmArchive:f.put(tarBytes({'package/bin/pnpm.cjs':f.get(manager)})),preparation:f.put(prep),files:[...origins.filter(o=>['query','schema'].includes(o.role)).map(o=>({path:o.path.replace('opt/nalanda-engines/','engines/'),sha256:o.sha256,bytes:64})),{path:'pnpm/bin/pnpm.cjs',sha256:manager,bytes:f.get(manager).length}]};plan.effectiveRecipeSha256=hashBytes(materialAcquisitionRecipe(f.get(plan.recipeSha256),plan));
 const verify=()=>{const h=f.put(plan);return verifyAcquisitionPlan(f.get(h),h,f.d,f.get);};
 const collectorRoot=path.join(f.root,'collector');mkdirSync(collectorRoot);const save=(name:string,bytes:Buffer)=>{const target=path.join(collectorRoot,name);mkdirSync(path.dirname(target),{recursive:true});writeFileSync(target,bytes);};
 const files:Record<string,Buffer>={'var/lib/dpkg/status':installed,'usr/local/bin/node':f.get(JSON.parse(f.get(f.d.images.builder.node!).toString()).binarySha256)};
 for(const o of origins){files[o.path]=f.get(o.sha256);save('material-originals/'+o.archiveSha256,f.get(o.archiveSha256));}
 for(const stage of ['fetch','install','store']){const prefix='opt/nalanda-materials/receipts/'+stage;files[prefix+'.stdout']=Buffer.from('HARNESS_ONLY '+stage);files[prefix+'.stderr']=Buffer.alloc(0);files[prefix+'.json']=Buffer.from(JSON.stringify({exit:0,signal:null,timedOut:false,settled:true,stdout:hashBytes(files[prefix+'.stdout']),stderr:hashBytes(files[prefix+'.stderr'])}));}
 files['opt/nalanda-materials/receipts/replay.json']=Buffer.from(JSON.stringify({requests:tarballs.map(t=>({url:t.url,sha256:t.sha256})),denied:0}));
 const config=f.put({os:'linux',architecture:'amd64',config:{User:'65532:65532',Labels:{'org.opencontainers.image.revision':f.d.source,'io.nalanda.artifact-purpose':'PREPARED_DEPENDENCIES_ONLY'}}});
 let proof:any,output:any;
 const layout=()=>{const layer=f.put(tarBytes(files)),manifest=f.put({schemaVersion:2,config:{digest:'sha256:'+config,size:f.get(config).length},layers:[{digest:'sha256:'+layer,size:f.get(layer).length}]}),index=f.put({schemaVersion:2,manifests:[{digest:'sha256:'+manifest,size:f.get(manifest).length,platform:{os:'linux',architecture:'amd64'}}]});for(const h of [layer,manifest,config])save('product-oci/blobs/sha256/'+h,f.get(h));save('product-oci/index.json',f.get(index));proof={architecture:'amd64',origins,baseInstalledStatus,manifest,nodeSha256:hashBytes(files['usr/local/bin/node']),replay:[...tarballs,...metadata]};save('material-collection.json',Buffer.from(JSON.stringify(proof)));output={indexSha256:index,manifestDigest:'sha256:'+manifest,configDigest:'sha256:'+config};return {proof,output};};layout();
 const collect=()=>JSON.parse(execFileSync(f.python,['-B',path.resolve('scripts/portable/material-collector.py'),'collect',collectorRoot],{encoding:'utf8',windowsHide:true,stdio:['ignore','pipe','pipe']}));
 const pack=async()=>{const collection=collect(),processes=[];for(const stage of ['build','trivy','grype','syft'])processes.push(await captureProductProcess({stage,tool:process.execPath,args:['-e','process.stdout.write("HARNESS_ONLY captured process")']},collectorRoot,processes.length+1,new Set()));
  const subject='sha256:'+config;save('trivy.json',Buffer.from(JSON.stringify({SchemaVersion:2,Metadata:{ImageID:subject},Results:[{Target:'TEST ONLY',Class:'os-pkgs',Type:'debian',Vulnerabilities:[]},{Target:'TEST ONLY',Class:'lang-pkgs',Type:'node-pkg',Vulnerabilities:[]}]})));save('grype.json',Buffer.from(JSON.stringify({source:{target:{imageID:subject}},matches:[],ignoredMatches:[],descriptor:{version:'0.110.0'}})));save('sbom.json',Buffer.from(JSON.stringify({spdxVersion:'SPDX-2.3',packages:[{name:'nodejs'}]})));save('scanner-metadata.json',f.get(f.d.images.builder.security.metadata));
  const result=packageMaterials(collectorRoot,f.d,verify(),f.get,output,processes,collection);for(const h of readdirSync(path.join(collectorRoot,'material-output/blobs')))f.blobs.set(h,readFileSync(path.join(collectorRoot,'material-output/blobs',h)));return result;};
 const harness=()=>{const original=f.harness(),signer='A'.repeat(40);return {...original,debianTrust:{debianKeyringSha256:keyring,debianSigners:[signer]},command:(c:any,root:string)=>c.stage.startsWith('material-gpgv-')?{stage:c.stage,tool:process.execPath,args:['-e','const f=require("fs"),a=process.argv.slice(1);f.copyFileSync(a[0],a[1]);process.stdout.write(a[2]);',c.args.at(-1),c.args[c.args.indexOf('--output')+1],'[GNUPG:] VALIDSIG '+signer+' TEST_ONLY\n']}:original.command(c,root)};};
 return {f,prep,plan,verify,files,layout,collect,pack,harness,collectorRoot,save};
}
