import Link from "next/link";
import { Prisma } from "@prisma/client";
import { PageHeader, PageShell, StatusBadge } from "@/components/ui";
import { requirePermission, hasUserPermission } from "@/lib/auth";
import { displayDate, moneyExact } from "@/lib/format";
import { publisherExpenseWhere } from "@/lib/publisher-bills";
import { prisma } from "@/lib/prisma";

export default async function PublisherBillsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const user = await requirePermission("VIEW_BOOKS_FINANCE"); const p = await searchParams; const vendorId = typeof p.vendorId === "string" ? p.vendorId : ""; const [rows, vendors, manage] = await Promise.all([prisma.expenseRecord.findMany({ where: publisherExpenseWhere({ vendorId }), include: { vendor: { select: { id: true, name: true } }, payments: { select: { amount: true } } }, orderBy: [{ invoiceDate: "desc" }, { createdAt: "desc" }] }), prisma.vendor.findMany({ where: { status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } }), hasUserPermission(user, "MANAGE_PUBLISHER_BILLS")]); return <PageShell><PageHeader title="Publisher Bills" description="These are filtered existing ExpenseRecord rows. Approval, partial/final payment, cancellation, references, and audits remain in the existing expense workflow." action={<div className="page-actions"><Link className="button secondary" href="/books">Back</Link>{manage ? <Link className="button" href="/books/publisher-bills/new">Create publisher bill</Link> : null}</div>} /><form className="card filter-grid"><label>Publisher<select name="vendorId" defaultValue={vendorId}><option value="">All publishers</option>{vendors.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button>Apply</button></form><section className="card"><div className="table-wrap"><table><thead><tr><th>Expense</th><th>Publisher</th><th>Invoice</th><th>Date</th><th>Net</th><th>Paid</th><th>Outstanding</th><th>Approval</th><th>Payment</th></tr></thead><tbody>{rows.map((row) => { const paid = row.payments.reduce((sum, payment) => sum.add(payment.amount), new Prisma.Decimal(0)); return <tr key={row.id}><td><Link href={`/expenses/${row.id}`}>{row.expenseNumber}</Link></td><td>{row.vendor?.name ?? "—"}</td><td>{row.invoiceNumber ?? "—"}</td><td>{row.invoiceDate ? displayDate(row.invoiceDate) : "—"}</td><td>{moneyExact(Number(row.netAmount))}</td><td>{moneyExact(Number(paid))}</td><td>{moneyExact(Number(row.netAmount.sub(paid)))}</td><td><StatusBadge status={row.approvalStatus} /></td><td><StatusBadge status={row.paymentStatus} /></td></tr>; })}</tbody></table></div>{!rows.length ? <p className="empty-state">No publisher bills match this filter.</p> : null}</section></PageShell>; }
